infor-design/enterprise

README.md
app/views/components/datagrid/test-datepicker-dynamic-disabled-dates.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

- Added an example (compatible with 4.5.0) that shows changing dates dynamically
- Update README command
- Added new pre-edit mode event
- Added new docs for new event
Related Issue: 
https://jira.infor.com/browse/SOHO-7922
Test Plan:
- Make a test for example http://localhost:4000/components/datagrid/test-datepicker-dynamic-disabled-dates when i start on that soon.
- Make test for the new event when i start on that soon.
Steps:
- http://localhost:4000/components/datagrid/test-datepicker-dynamic-disabled-dates
- click each column to edit the date
- the disabled dates will be randomly different for each column
- new event will show in the console

SOHO-7922 - Example Showing Dynamic Disabled Dates

---

app/views/components/dropdown/example-no-search-filtering.html
app/views/components/dropdown/example-no-search-lsf.html
app/views/components/dropdown/example-no-search.html
src/components/dropdown/dropdown.js
test/components/dropdown/dropdown-light-theme.e2e-spec.js

Explain the **details** for making this change. What existing problem does the pull request solve?
Previous changes related to SOHO-7901 caused some filtering functionality on un-opened Dropdown components to disappear.  This PR re-enables them while keeping the changes related to cycling through results that share a common first character.  See the comments from Duncan on https://jira.infor.com/browse/SOHO-7901?focusedCommentId=4476991&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4476991
Also, it was discovered by the LSF team that at some point in 4.6.0, another dropdown change is causing SOHO-7932, where pressing the "DELETE" (not Mac's equivalent of Backspace) would throw JS errors, when it should simply be clearing the selected Dropdown option and …

Soho 7901 / Soho-7932 typeahead delay re-implementation / filtering improvements

---

docs/TESTING.md
test/karma.conf.js

Webpack was removing debugger statements as it was defaulting to prod mode. Developers can now pause code execution, and inspect source at runtime. Also updates documentation for a inline debugging experience where the developer can isolation suites of tests, or individual specs
https://jira.infor.com/browse/SOHO-7934
Isolate a test with appending f to describe and/or it.
Place a `debugger;`, anywhere you wish, navigate to localhost:9876, open devTools, you should land on the debugger statement.
Read, execute documentation please
Please review documentation, and make sure it is …

SOHO-7934 - Update TESTING docs, deoptimization Webpack build

---

app/views/components/popupmenu/test-empty-items.html
src/components/button/_button.scss
src/components/popupmenu/_popupmenu.scss

In some cases where popupmenu items are rendered without a visible text label, the menu item would not have a computed height, causing any icons included in that item to appear to "stack" on top of other items.  This change allows "empty" items to render with a minimum height.
https://jira.infor.com/browse/SOHO-7942
Run the demoapp and navigate to http://localhost:4000/components/popupmenu/test-empty-items.html.
- Open the popupmenu
- Confirm that all items present are empty (except for the icons), but stacking properly.
Closes SOHO-7942

SOHO-7942 - Better handling of "empty" popupmenu items.

---

publish/package.json

The master branch version should reflect what we are working on. In this case we are working on `4.7.0-dev`.
When we do special or nightly npm releases, those will get tagged/versioned outside of source control and published as snapshots in time with the date appended:
i.e. `4.7.0-dev.YYYYMMDD`.

Set master branch version back to 4.7.0-dev

---

app/views/components/toolbar/test-tooltips-populating-more-actions.html
src/components/button/button.js
src/components/toolbar/toolbar.js

This PR fixes issues that were occurring where Toolbar "More Actions" menu items that originated from a Toolbar Item with a Tooltip applied were rendering as empty.  Tooltips are now respected as a source of "More Actions" item text, and will be checked first before the contents of the Toolbar item itself are checked.
https://jira.infor.com/browse/SOHO-7942 (issue is described in comments)
- Open http://localhost:4000/components/toolbar/test-tooltips-populating-more-actions.html
- Click the in-page toolbar's "More Actions" menu button
- Make sure the first two items that display ("Send via Email" …

SOHO-7942 - Toolbar Popupmenus' propagation of text from Toolbar Items containing Tooltips

---

src/components/datagrid/datagrid.js

current datagrid control does not provide a function for find rows by field value.  this delivery add such function to  datagrid control.
sometimes, we need find rows numbers based on a row's field name, for example, we need find a row based on a row's unique id, sometimes, such id is internal, so we could not find it by going through all cells, also, performance is another consideration.
SOHO-7935 Add findRowsByValue to datagrid control
the logic is similar to the existing function selectedRows(), which selectedRows checks row's selection status, this function checks value of the field of data …

SOHO-7935 Add findRowsByValue to datagrid control

---

app/data/autocomplete-users.json
app/data/autocomplete-xss.json
app/views/components/autocomplete/example-contains.html
app/views/components/autocomplete/example-templates.html
app/views/components/autocomplete/test-xss-security.html
src/components/autocomplete/autocomplete.js
test/components/autocomplete/autocomplete-api.func-spec.js
test/components/autocomplete/autocomplete-events.func-spec.js
test/components/autocomplete/autocomplete-filtermode.func-spec.js
test/components/autocomplete/autocomplete-template.func-spec.js
test/components/autocomplete/autocomplete.e2e-spec.js
test/components/searchfield/searchfield.func-spec.js

Adding basic functional/e2e tests for the Autocomplete component (and a couple for Searchfield).
Also, the new Autocomplete tests revealed a lifecycle bug where the component's internal ListFilter component wasn't updated on an Autocomplete `updated()` call.  This is now fixed.
https://jira.infor.com/browse/SOHO-7850
Run the new Autocomplete/Searchfield functional and e2e test suites.  All of these new tests should pass.

SOHO-7850 - Autocomplete/Searchfield tests for related Searchfield refactoring

---

.travis.yml
scripts/jenkins-deploy.sh

Provides more a more generic interface to `jenkins-deploy.sh` script so that it can also be used with publish scripts.
To build `master` to the demo server, run:
```
./scripts/jenkins-deploy.sh -b master
```
This is what will be used on merges into `master`.
To deploy a specific version to the demo server, like on release of a new version, run:
```
./scripts/jenkins-deploy.sh -b 4.6.1
```
You'll then want to run a second deploy on that version, to deploy to the `latest-enterprise` demo server, so that the `/code/ids-enterprise/latest/demo` links properly point to the `latest` version:
```
./scripts/jenkins-deploy.sh -b 4.6.1 -l
```
You can also add the `-w` flag to watch the status of the …

Better arguments for deploy script

---

app/views/components/validation/test-error-on-tab.html
src/components/tabs/tabs.js

Tabs had some un-qualified / unneeded events and a memory leak. This is fixed.
SOHO-7948
- place an input out of the tabset and tab out of it. should not fire focusBar

Fixed incorrect event handlers in tabs

---

app.js

This change is necessary to run HTTPS and proxy on the `latest` demo server. This will essentially deploy `4.6.1` plus the app server patch.
It's not necessary at this time to bump a patch version of `4.6.x`. I think this fix is fine sitting on the tip of that branch and could go out if there's ever a need for `4.6.2`.

Patch app.js for demo server

---

src/components/dropdown/dropdown.js

There was a bug in the dropdown component that originated from some previous patches (SOHO-7901 and related issues), which was causing filtering not to occur properly on Dropdown components that were NOT configured with searching disabled.
https://jira.infor.com/browse/SOHO-7998
SOHO-7998:
- Open http://localhost:4000/components/dropdown/example-index
- focus the dropdown
- type "al"
- the list should properly open and display search results containing "al"
SOHO-8020: 
- Open http://localhost:4000/components/dropdown/example-clearable.html
- focus the last dropdown on the page labeled "Not …

SOHO-7998 - Dropdown Focus/Premature closing issues

---

scripts/jenkins-deploy.sh

If the Jenkins build that Travis kicks off returns a status other than `SUCCESS` or `ABORTED`, Travis will now retrieve the Jenkins log and display it.
It'll look something like this:
```
Building master as master-enterprise...
- adding Jenkins build to queue...
SUCCESS: Jenkins sucessfully queued job
Watching build #118 to report on status.....
FAILED! See log for details:
Started by remote host 198.179.75.179
Building in workspace /var/jenkins_home/jobs/soho4-swarm-deploy/workspace
[workspace] $ /bin/bash /tmp/jenkins8957704905126335100.sh
WARNING! This will remove:
- all stopped containers
- all networks not used by at least one container
- all dangling images
- all …
```

Display Jenkins log in Travis upon failure

---

app/views/components/datagrid/example-expandable-row.html
src/components/datagrid/datagrid.js

Saleshubs links in datagrid expanders broke, this fixes it
soho-8009
http://localhost:4000/components/datagrid/example-expandable-row.html
- open any expander
- click the link -> should open site in a new window
Going to make some test on datagrid next week...

Fix links not working in expandable areas

---

src/components/dropdown/dropdown.js

Fixed a bug where Dropdowns with no clearable options were appearing to be empty when using the Enter key to close a dropdown with no filtered items -- soho-7998
https://jira.infor.com/browse/SOHO-7998
- Open http://localhost:4000/components/dropdown/example-clearable.html
- focus the last dropdown on the page labeled "Not Clearable"
- open the list with the keyboard by pressing Down Arrow 
- try to enter junk data that has no matches, and press Enter/Return
- the previous selection, "New York", should remain selected (previously this series of steps was causing the dropdown to become blank, which …

SOHO-7998 (Q/A patch) - Non-clearable Dropdown Reset

---

src/components/dropdown/dropdown.js

The scenario involves a `single-select` dropdown that contains options that will always have a unique value, but may (under some circumstances) have matching text labels. If we select an option from the list, and then select a second option with a different value, but a matching text label, the dropdown component does not (as far as we can tell) detect that the selected value has been changed, and thus does not perform logic that would normally be executed when a change occurs (updating the model or triggering associated events).
This is specifically an issue for the Angular controls, where the 'change' event is required to update the Form model.  In the above scenario, the `changed` event …

SOHO-8029 - Cannot select individual options with different values but same labels

---

src/components/tabs/_tabs.scss

In Firefox, there used to be no overflow limit on vertical scrolling on Horizontal Tab lists, which was causing scrollbars to appear.  This PR removes vertical scrolling from inside of these tabs lists.
https://jira.infor.com/browse/SOHO-8034
- Pull down this branch and run the demoapp
- Open http://localhost:4000/components/tabs/example-index in Firefox on Mac.
- Ensure that it's no longer possible to scroll vertically inside the tab list (horizontal scrolling is allowed).
Closes SOHO-8034

QA - SOHO-8034 - Remove vertical scrolling from horizontal tab lists

---

.travis.yml

Runs e2e tests (`npm run e2e:ci`) if build job is kicked off from cron (which is our nightly builds). Authentication is handled with saved environment variables in Travis and sourced in the e2e config file.

Adds task to run e2e if cron task

---

src/components/form/_form.scss

Adjust the breakpoint to phone for the checkbox align center when screen lower than 1280
https://jira.infor.com/browse/SOHO-7939
- open http://localhost:4000/components/form/example-inputs.html
- Test this page by resizing the browser. Checkbox is aligned left on small screen. Aligned center both for tablet and desktop.

SOHO-7939 checkbox centered in large breakpoint

---

src/components/applicationmenu/applicationmenu.js

In Module Tabs components, Application Menu triggers are optional, and use events to open/close the Application Menu.  The event handler inside the Application Menu that handles the opening of the menu wasn't properly being identified as "User Opened", which was causing the menu to instantly close as soon as it's opened from the Module Tabs trigger.  This problem is fixed in this PR.
https://jira.infor.com/browse/SOHO-8043
- Pull the branch and open http://localhost:4000/components/tabs-module/example-app-menu-button.html
- Resize the screen to below 767px to enable the responsive Application Menu …

QA - SOHO 8043 - Module tabs' app-menu trigger instantly closes the app-menu after it's opened

---

src/components/autocomplete/autocomplete.js
test/components/autocomplete/autocomplete-select.func-spec.js

A change I made in SOHO-8036 to the Autocomplete's return object was causing some integrity problems when running the `selected` method.  If the original piece of data had properties added by app developers, it should be possible to pass those properties through the return value, as well as any event listeners attached to the `selected` event.  This PR fixes those problems and adds tests for both a clean data and modified data scenario.
https://jira.infor.com/browse/SOHO-8076
Pull this branch and run the new "Autocomplete API (selected)" functional tests.  Both should pass.
Fixes …

Q/A - SOHO-8076 - Missing properties in Autocomplete return object

---

.travis.yml

Stop builds from failing. We are receiving false negatives from BrowserStack. Tests will pass locally on Chrome OSX, but fail in the Chrome OSX VM. We have a local replacement in other branch, that will upgrade Chrome, and tests e2e tests on each branch, on every commit
Review this build on travis

SOHO-8061 - Drop failing bs e2e builds

---

app/views/components/dropdown/test-allow-custom-keystroke.html
src/components/dropdown/dropdown.js
test/components/dropdown/dropdown-updates-events.func-spec.js

Added onKeyDown param that will allow us to manipulate the default behavior of the up/down arrow
SOHO-4815
http://localhost:4000/components/dropdown/test-allow-custom-keystroke.html
- Open the dropdown
- Try to select a value on the dropdown list using the up/down arrow
- The expected behavior, You won't be able to select any value using the up/down arrow.

SOHO-4815 provide a param to control the default behavior of up/down arrow

---

src/components/datagrid/datagrid.js

http://localhost:4000/components/datagrid/test-tree-contextmenu.html
QA Notes:
- Right click on any row
- See console log for row number

SOHO-7991 - Fixed rightclick was returning wrong index TreeDatagrid

---

app/views/components/datagrid/example-filter.html
src/components/datagrid/_datagrid.scss

Column that is specified to be sortable, sort indicators was not showing when the column alignment is set to center.
SOHO-7444
http://localhost:4000/components/datagrid/example-filter
QA Notes:
- Hover to column header “Status”
- See sort indicator should be visible

SOHO-7444 - Fixed sort indicator was not showing with Datagrid

---

app/views/components/datagrid/test-editable-noneditable-field.html

As stated in SOHO-6257, Added an example page to show non-editable field behavior vs editable field by using Dropdown editor/formatter with Datagrid. 
https://jira.infor.com/browse/SOHO-6257
http://localhost:4000/components/datagrid/test-editable-noneditable-field
- Hover on any row in column ‘Non Editable’
- It should not shows the dropdown-icon (triangle)

Added example page for non-editable field with editable Datagrid

---

app/views/components/datagrid/test-focus-after-sort.html
src/components/datagrid/datagrid.js

When sorting on any column, if there is any selected cell in the grid and not currently visible (e.g. because there are many columns which doesn't fit to entire page, sort was on first and selected cell was from the last column), the view was shifted to that selected cell.
https://jira.infor.com/browse/SOHO-7682
http://localhost:4000/components/datagrid/test-focus-after-sort
- Make your browser window short as much, so you have some hidden columns
- Click to change the setting for “focusAfterSort” by clicking on button top of grid
- If the button state as “Set Focus After Sort …

SOHO-7682 - Added api options focusAfterSort with Datagrid

---

src/components/modal/modal.js

Editor Modal was closing soon “Enter” key get pressed twice
https://jira.infor.com/browse/SOHO-8059
http://localhost:4000/components/editor/test-modal
- Click on button “Show Modal” to open modal
- Press “Enter” key twice
- Modal should not close

SOHO-8059 - Fixed pressing enter key twice was closing Modal with Editor

---

src/components/slider/slider.js

- Updated handleRangeClick function to move to nearest step when clicking on range
- http://localhost:4000/components/slider/example-stepping.html
- Click on range bar near the dot (left or right side)
- Dot should now move to nearest step

SOHO-6271 Fixed issue regarding slider step

---

src/components/colorpicker/colorpicker.js

This fixes a bug seen on http://localhost:4200/colorpicker in the ng project. If you used down arrow to open the list would be messed up and in the wrong dom position.
https://github.com/infor-design/enterprise-ng/pull/79/files
http://localhost:4200/colorpicker 
- link project
- hit down arrow and see the list is ok

Fixed a bug shown in the angular component with down arrow

---

.github/PULL_REQUEST_TEMPLATE.md

I originally liked the grayed out quoted titles in the PR template, but I've slowly grown to dislike them.  
I want to know what you guys think...
Which do you like better, old:
or new (aka this PR):

Use bold for PR template headings instead of quote indent

---

test/helpers/browserstack-error-reporter.js

Corrects error reporting in BrowserStack reporting console via REST API
Run BrowserStack locally, and look for errors to be reported, `npm run e2e:local:bs`

SOHO-8061 - Correct BrowserStack REST API error reporting for any *bs.conf*

---

src/components/autocomplete/autocomplete.js
test/components/autocomplete/autocomplete-select.func-spec.js

a previous fix for SOHO-8076 was causing incorrect values to be returned as `selected` when a `data-index` attribute wasn't used in templates.  This has been fixed and a tests was added to demonstrate.
https://jira.infor.com/browse/SOHO-8076?focusedCommentId=4543384&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4543384
- Pull the branch and run the functional tests for Autocomplete.  All should pass.
Closes SOHO-8076

SOHO-8076 - autocomplete `select()` return value bugfix

---

app/views/components/datagrid/example-expandable-row.html
src/components/datagrid/datagrid.js
test/components/autocomplete/autocomplete-select.func-spec.js

When hiding and showing columns , if you have expandable row. The columns get messed up.
soho-8103
http://localhost:4000/components/datagrid/example-expandable-row.html
- expand any row
- under the ... menu personalize columns
- hide a few / show a few
Note: Hiding the expandable row is disabled..

Fixed a bug hiding/showing columns with expandableRow

---

src/components/form/_form.scss

change the css property of the class name field-checkbox to left to make it the default alignment of the checkbox inside the field.
SOHO-7939
http://localhost:4000/components/form/example-inputs.html
- open the link above. try to resize the window.
- Expected result: Checkbox should be left align in any window sizes.

SOHO-7939 make checkbox default align left

---

test/components/listview/listview.e2e-spec.js

Fixes random failing test possible due to a timing issue. This fix ensures that we wait for aria-selected, and class to be present in DOM before testing
Relates to https://jira.infor.com/browse/SOHO-8061
Focus, isolate the tests on listview.e2e.*, or just run `npm run e2e:ci` as a whole a couple of times

Wait for aria, and class selected attributes to be added to DOM

---

app/views/components/colorpicker/example-custom-labels.html
src/components/colorpicker/colorpicker.js
test/components/colorpicker/colorpicker-api.func-spec.js
test/components/colorpicker/colorpicker-aria.func-spec.js
test/components/colorpicker/colorpicker-events.func-spec.js
test/components/colorpicker/colorpicker.e2e-spec.js
test/components/colorpicker/colorpicker.func-spec.js

Added functional and e2e tests for Colorpicker
https://jira.infor.com/browse/SOHO-8078
E2E
`env PROTRACTOR_SPECS='components/colorpicker/colorpicker.e2e-spec.js' npm run e2e:local:debug`
`env npm run e2e:local:debug`
FUNCTIONAL
`npm run functional:local`

SOHO-8078 - Added functional and e2e tests for Colorpicker

---

package.json

Continue to run BrowserStack tests without failing entire build as we need to deploy nightlies every night. e2e smoke testing will continue to be executed on branch commit, and on PR.
Fail a test, place a command after this script  (grouping and using `&&` or just write your own .sh (shell script) ), that script should execute as we are returning `exit 0` not matter what.

Prevent BrowserStack cron from failing entire build, and therefore nightly builds

---

package.json

- `npm test` is a duplicate cmd, we can move the `all-checks` script content to it and avoid having to have another cmd in the list
- n/a
- make sure `npm run test` isn't used other places where the server might be required, yet unavailable

Repurpose "test" as it was a duplicate cmd

---

src/components/badges/_badges.scss

- Adjusted alignment of dismiss icon
- http://localhost:4000/components/tag/example-dismissible-and-clickable.html?locale=ar-SA#
- Upon opening the test page, dismiss icon should no longer be misaligned to the right

SOHO-8120 Adjusted alignment of dismiss icon

---

test/protractor.ci.bs.conf.js
test/protractor.local.bs.conf.js

Add unique ID to build to ensure badge reflects the correct build status. Links failing BrowserStack build to failing travis build 
Relates to SOHO-8061, SOHO-7331
Run locally, check BrowserStack dashboard... If possible, verify that TRAVIS_BUILD_NUMBER works

SOHO-8061 - Add unique ID for BrowserStack builds

---

src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js

Column that is specified to be sortable, sort indicators was not showing when the column alignment is set to center.
https://jira.infor.com/browse/SOHO-7444
https://jira.infor.com/browse/SOHO-7918
http://localhost:4000/components/datagrid/example-filter
Open above link
Hover to column header “Status”
See sort indicator should be visible
http://localhost:4000/components/datagrid/test-rowdata-issue.html
Open above link
In "Datagrid B"
Hover to star column header “Default”
See sort indicator should not be visible, and row-height not breaking
Resize and make this column wider by dragging in …

Fixed sort indicator was not showing with Datagrid

---

src/components/datagrid/datagrid.formatters.js

Click on any cell in the Price column
Remove the text from the field box
Click out of the cell. You will get "Required" icon
Click back into the same cell and start type anything and click out of the cell
The "NaN" error does NOT  appears in the field box
The change means that any invalid entry eg. 'd' is cleared.

SOHO-7839 - [All Browsers] Datagrid Editable Control: Price Column giving "Nan" error

---

src/components/datagrid/datagrid.js

Expandable row was not expanding after another row expanded
https://jira.infor.com/browse/SOHO-8154
http://localhost:4000/components/datagrid/example-expandable-row
- Click on the "+" for product id "2142201" to expand (it will expand)
- Click on the "+" for product id "2241202" to expand (it will expand and close "2142201")
- Click on the "+" for product id "2142201" to expand (it will expand and close "2241202")
- Click on the "+" for product id "2142201" to close (it will close all)
- Click on the "+" for product id "2142201" to expand (it should expand)

Fixed expand row was not expanding with Datagrid

---

test/components/colorpicker/colorpicker.func-spec.js

Removed setTimeout from colorpicker tests to prevent occasional race conditions.  The two tests that were replaced are now testing API methods instead of depending on clicks.
https://jira.infor.com/browse/SOHO-8078
Pull this branch and run the Colorpicker functional tests.
SOHO-8078

SOHO-8078 - Fixed colorpicker tests

---

app/views/components/datagrid/test-number-rounding.html
test/components/locale/locale.func-spec.js

Reviwed soho-5168 and noted it was already possible. So added an example and unit test for the exact case
soho-5168
http://localhost:4000/components/datagrid/test-number-rounding.html
- column should show 810
- run functional tests specifically this one:
https://github.com/infor-design/enterprise/blob/soho-5168-rounding/test/components/locale/locale.func-spec.js#L719

Added sample and test for soho-5168

---

src/components/dropdown/dropdown.js

With Chrome on Windows select-all was causing frozen browser with Multiselect
https://jira.infor.com/browse/SOHO-7816
http://localhost:4000/components/multiselect/test-select-all-performance
- Open above link with Windows / Chrome
- Click on multiselect “Bods” to open
- Click on first item in list “Select All”
- It should not take much time select all items
- Do same to clear the items
- See should not take much longer to clear all either
closes #117

SOHO-7816 - Fixed select-all was causing frozen browser with Multiselect

---

app/views/components/datagrid/example-filter.html
src/components/dropdown/dropdown.js
test/components/dropdown/dropdown-updates-events.func-spec.js

- Added clearable option to dropdown component
- Updated example-filter.html on datagrid to use clearable option for dropdown instead of adding a blank option
- http://localhost:4000/components/datagrid/example-filter.html
- Status filter on header should now have an empty option

SOHO-7481 Added clearable option to dropdown component

---

src/components/datagrid/_datagrid.scss

- For css prioritization, added tag 'important' on the dropdown icon top position.
- To achieved the checkbox vertically centered. datagrid-filter-wrapper should be display none if checkbox is present.
- Adjusted the handle font-size to rem to avoid issues in regards to parent's styling inheritance. 3.1rem is the equivalent value of the previous handle icon font-size 2.6em inside the class row with 1.2rem or 12px font-size.
SOHO-5888
http://localhost:4000/components/datagrid/test-in-containers.html
- Open the above page, Check the vertical and horizontal alignment of the checkbox. It …

SOHO-5888 fix display inside tabs and containers

---

src/components/typography/_typography.scss

Added css properties like overflow, line-height and the microsoft css proprietary ms-overflow-styling for IE. This will allow the label to be display properly with the input/lookup field both on IE and Chrome
[SOHO-7747](https://github.com/infor-design/enterprise/issues/252)
http://localhost:4000/components/form/test-flex.html
http://localhost:4000/components/form/test-flex.html?locale=ar-SA
- both lookup field and label should be displayed properly side by side
- Lookup/input field can accept user inputs and should not be moved or scrolled.
- Long labeled descriptions should have …

soho-7747 fix the display on IE

---

src/components/datagrid/datagrid.js

Using keyword search rows to select all, was selected all rows instead only filtered results
https://jira.infor.com/browse/SOHO-7909
http://localhost:4000/components/lookup/example-multiselect
- Click on lookup field to open modal
- Type "205" and press Enter key in search field
- It should filter with two results (Product Id - 2542205 and 2642205)
- Click on checkbox in header to select all (both rows)
- Click modal button "Apply"
- It should close the lookup modal
- In lookup field should add those selected items (Product Id - 2542205 and 2642205)

SOHO-7909 - Fixed filtered select all was not working with Lookup

---

src/components/searchfield/searchfield.js
test/components/searchfield/searchfield-events.func-spec.js

This PR: 
- Adds back a missing `selected` event trigger on Searchfield input elements that happens when a Category is selected.  This was a regression that came about during the merging of Toolbar Searchfield and Searchfield APIs.
- Added a test to demonstrate that the event is being fired.
Closes #287
Pull this branch and:
- open http://localhost:4000/components/searchfield/test-selected-event.html and choose a category from the Searchfield's category dropdown.  A toast should appear once the menu is closed, and in the Dev Console, a log statement containing the clicked anchor should …

Q/A - Searchfield: Fixed missing `selected` event trigger on input elements

---

app/views/components/dropdown/example-readonly.html
src/components/dropdown/dropdown.js

Dropdowns configured to display an icon would not invoke, and throw errors when a Dropdown List item was defined without a valid reference to an icon.  This PR fixes that.
Closes #268 
Pull this branch and:
- open http://localhost:4000/components/dropdown/test-icons-color.html
- check for an console errors.
- Select an item from the Dropdown that doesn't have an icon associated with it.
- check again for any console errors.
Everything should work properly.

Q/A - 268 - Undefined Dropdown Icons throwing an error

---

test/components/tabs/tabs-api.func-spec.js

Periodically on the CI, tests of the .teardown & .destroy fail. This fix should allow additional time (~1s) for .teardown completion.
Closes #239 
Run `npm run functional:ci` several times please  (I have rebuilt on the CI a bunch of times)

Give .teardown additional time complete for testing

---

src/components/personalize/personalize.js

- Updated personalize js to apply custom colors
- http://localhost:4000/components/tabs-module/example-toolbar-with-spillover.html?colors=80000
- After loading the page, click on 'Disable All'
- Colors in the toolbar should be fixed

SOHO-8153 Updated personalize js to apply custom colors

---

app/views/components/contextualactionpanel/test-jquery-no-flex.html
app/views/components/validation/test-range-validation.html
src/components/contextualactionpanel/contextualactionpanel.js
src/components/validation/readme.md
test/components/contextualactionpanel/contextualactionpanel.e2e-spec.js
test/components/validation/validation.e2e-spec.js

The Cap after changes early this sprint will now show buttons incorrectly in overflow if the flex toolbar option is not used.
Additional: Added a validation test / example and changed a comment related to a problem seen on that example.
Closes #338
1. test these two pages http://localhost:4000/components/contextualactionpanel/example-jquery.html and http://localhost:4000/components/contextualactionpanel/example-jquery.html
1. open the panel
1. both should have two visible buttons on the left of the modal.
**Additional Info**:
@bthharper @EdwardCoyle

Cap sizing issues

---

test/components/tabs/tabs-vertical.e2e-spec.js

Prevents this visual regression tests from running on BrowserStack as they should only run on the CI
Related to #318 
Run `npm run e2e:local:debug`, and checkout https://automate.browserstack.com/builds/7003ac7c3d4d553013e2ba61a33b57f52ffb8180/sessions/e1f1310d5569e5ed0accfdb1609a4f67bac9bf7a

318 - Run visual regress tests on Chrome, and CI only

---

test/components/colorpicker/colorpicker.e2e-spec.js

333 - Colorpicker keyboard open, and selection e2e tests

---

src/components/toolbar/toolbar.js

Fixing an error where the tooltip "More.." wouldn't appear when the more actions button was created programmatically in toolbar
Closes #345 
1. After pulling in my change, go to /toolbar/example-index.html and hover over the ... button in the toolbar in the content area:

Fixing more tooltip on programmatically created more action buttons on toolbar

---

src/components/searchfield/searchfield.js

- Added new validation to handle ctrl + backspace
- Cleared search text on ctrl + backspace
- http://localhost:4000/components/searchfield/example-clearable.html
Closes #308 
- In the search field, select "Northern Mariana Island Territory"
- Move the cursor before the word "Northern"
- Press alt+delete (Mac) or ctrl+backspace (Windows) keys
- All contents should now be cleared

308 Added clearing of search text on ctrl + backspace

---

app/views/components/listview/example-header-totals.html

Add a td tag that will correct the html structure of the bottom row
Closes #272 
Open this link http://localhost:4000/components/listview/example-header-totals.html, Check the table bottom row display. border should be displaying properly.

272 fix broken bottom border

---

app/views/components/modal/example-close-btn.html
src/components/modal/_modal.scss
src/components/modal/modal.js
test/components/modal/modal.e2e-spec.js

Closes #358
open localhost:4000/components/modal/example-close-btn.html and try the x close icon
> Note: Fixed requested changes in #359, had to do another PR coz accidentally used a master branch on that previous one

358 - X close icon for closing modals

---

src/components/dropdown/dropdown.js
test/components/dropdown/dropdown.e2e-spec.js

A bug was discovered by @tmcconechy where a Dropdown would unexpectedly open its list of selectable options after pressing `Tab` or `Shift + Tab` to navigate away.
- Caused by changes in #267
- Closes #466 
- Open http://localhost:4000/components/dropdown/example-index
- Focus the Dropdown element (by keyboard, or by clicking on it)
- If the list is open, press tab to close the list
- Press tab to navigate away
The list should remain closed and focus should be on a different element in the page.

466 - Tab key no longer causes Dropdown lists to open

---

test/components/listview/listview.e2e-spec.js

Fixes failed BrowerStack test on nightly test
> (Marked via REST API : Should remove selected items, and update status pane)
Relates to #347 corrections
You can review tests I ran on BS, or just isolate the tests, and run on Chrome, `npm run e2e:local:bs`

347 - Revert config.waitFor to config.waitsFor which fails on BS

---

package.json
test/components/dropdown/dropdown.e2e-spec.js

Fixes randomly failing dropdown keypress test
#466 #467
`npm run e2e:ci`, check CI logs

Add wait time for UI updates

---

app/views/components/datagrid/test-expand-row-on-search.html
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-settings.func-spec.js

- Prevented expanding of row templates on data grid search
- Updated validation for hiding data grid rows
- http://localhost:4000/components/datagrid/example-expandable-row.html
- Open search filter on upper right side of data grid
- Use 'lo' as keyword and hit Enter
- Row template should no longer be expanded
Closes #424

424 Prevented expanding of row templates on search

---

app/app.js
app/views/behaviors/longpress/example-index.html
app/views/behaviors/longpress/test-e2e-overlay-toggle.html
src/behaviors/longpress/longpress.js
src/behaviors/longpress/longpress.scss
src/core/_controls.scss
src/index.js
src/utils/environment.js
test/behaviors/longpress/longpress-events.func-spec.js
test/behaviors/longpress/longpress.e2e-spec.js
test/karma.conf.js
test/protractor.ci.bs.conf.js
test/protractor.ci.conf.js
test/protractor.local.bs.conf.js
test/protractor.local.debug.conf.js

This PR adds document-level event handlers for touch events that can detect when a user holds down a touch for a specified duration.  Once the duration is met without interruption, a `longpress` event is fired on the target element where the touch began.
#245
Pull this branch, build, and run the demo app.  Then:
- Open http://localhost:4000/behaviors/longpress/example-index in a mobile browser (Android, iOS) with a dev tools console connected.
- Long press the screen for at least 400 miliseconds
- In the console, a log statement should be created with a reference to the element that the …

245 - add longpress behavior

---

test/components/colorpicker/colorpicker.e2e-spec.js

Add additional tests of the modal using the keyboard primarily
Relates to #333 
Run `npm run e2e:ci` locally

Add keyboard tests for colorpicker modal

---

src/components/dropdown/dropdown.js

This PR adds a better type check to a particular spot in the Dropdown component code that detects previously selected values.
Fixes a problem that's failing e2e tests on the CI in infor-design/enterprise-ng#136
Originally part of changes in #267
- Run the Dropdown e2e tests in this project.
- Use the `/dist` folder built by this branch and build/test the Angular components to ensure its e2e tests all pass.

NG-136 - Add a type check to fix broken NG tests

---

src/components/dropdown/dropdown.js
test/components/dropdown/dropdown.e2e-spec.js

There was previously an issue where pressing the escape key on a closed Dropdown component would unexpectedly cause the list to open, due to changes in keyboard handling with its typeahead feature.  This was very obvious when closing Contextual Action Panel components that contained Dropdowns in their content area.  This PR fixes this problem.
- Caused by changes in #267 
- Closes #474 
- Open http://localhost:4000/components/contextualactionpanel/example-trigger.html
- Click the button to open the CAP
- Press the `Escape` key to close the CAP.
- The …

474 - Escape key causing the Dropdown to re-open it's list unexpectedly

---

test/components/blockgrid/blockgrid.e2e-spec.js

Blockgrid tests were passing without the Blockgrid demo page (without `npm start`)
Closes #509 
Run Blockgrid tests isolated, and without the server. All should fail. Turn on server. All should pass.

509 - Check for presence of element finder object

---

src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-api.func-spec.js

Calling updateDataset with null for the toolbar setting gives errors for landmark.
Closes #522 
`npm run functional:local`

Added null check to updateDataset

---

app/server.js
app/src/js/middleware/option-handler.js
package.json
src/components/autocomplete/autocomplete.js
src/components/listview/listview.js
src/components/popupmenu/popupmenu.js
test/components/autocomplete/autocomplete.e2e-spec.js
test/components/datepicker/datepicker.e2e-spec.js
test/helpers/e2e-utils.js
test/kitchen-sink.e2e-spec.js

Fixes an error when selecting elements from a autocomplete list. In addition to the error i found the select event goes off twice (one time with no data), so added an option to popupmenu to skip this.
Also added a new util to check the console for errors. This can be used in all the e2e tests to check for any errors. Added one test to catch stuff on the kitchen sink page.
Closes #529 
http://localhost:4000/components/autocomplete/example-index.html#
- type a
- pick one
- check the console for event data (and no more error)
Check e2e Tests

Fixes #529 Added eventing fix and fixed an error

---

src/components/accordion/accordion.js

A bug was discovered in the application menu where clicking any item inside the menu's boundaries would cause the menu to close.
Originally fixed in #324
Fixes #519 
Pull this branch and run the demoapp, then:
*Testing the original issue*
- open http://localhost:4000/components/accordion/test-with-contextmenu.html
- expand the first header
- right click the header to open a popupmenu
- close the accordion header
The Popupmenu menu should close
*Testing the new application menu bug*
- open http://localhost:4000/components/applicationmenu/example-index.html
- Resize the browser viewport to …

519 - Fix for prematurely closing application menus

---

src/components/datepicker/datepicker.js

The issue occur in the hover state in datepicker, were it added a new event each time and it didn't clear it. So the behavior still exist even in the other months.
**Fixed**
Added an ```.off``` method in the ```setLegendColor```.
```
elem.off('mouseenter.legend mouseleave.legend');
```
Then, in the handle hover states, we should add the namespace
```
elem.on('mouseenter.legend', function () {
const thisElem = $(this);
thisElem[0].style.backgroundColor = hoverColor;
thisElem.find('span')[0].style.backgroundColor = 'transparent';
}).on('mouseleave.legend', function () {
const thisElem = $(this);
thisElem[0].style.backgroundColor = normalColor;
thisElem.find('span')[0].style.backgroundColor = …
```

Fixed unnecessary hover in datepicker

---

app/views/components/datagrid/test-right-aligned-lookup.html
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.editors.js
src/components/datagrid/datagrid.formatters.js
src/components/typography/_typography.scss

columns.push({ id: 'productName', name: 'Product Name', sortable: false, field: 'productName', formatter: Formatters.Hyperlink, editor: Editors.Input, **align: 'right'** });
Lookup now support the align 'Right' option. Developers have now an option to right aligned the lookup field if needed.
Closes #228 
http://localhost:4000/components/datagrid/test-right-aligned-lookup.html
- Open link above, look for product id column
- All product id's should be right aligned. Same alignment when you click on any product id number in a row.
- Check lookup field alignment on various heights like short …

228 add right alignment support for datagrid lookup text

---

src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-validation.func-spec.js

A row's status is showing the dirty flag, when a cell has a dropdown and the user selects the same value from the dropdown. Landmark issue, since the column.field property will be set to something like "fields.ReasonType.value". So within the updateCellNode function, the code for getting the oldVal needs to be changed.
Closes #538 "

Datagrid inadvertenly showing dirty flag for dropdowns

---

app/views/components/icons/example-tooltips.html
src/components/initialize/initialize.js
src/components/tooltip/tooltip.js
test/components/tooltip/tooltip.e2e-spec.js

A feature request was made for allowing tooltips to be present on standalone icons.  This PR enables tooltips on icons during a mouse hover, or a long press on a touch screen, even if the icon isn't focusable by normal means.
Closes #400 
Pull this branch and run the demo app... then:
_Retest hover on desktop:_
- open http://localhost:4000/components/icons/example-tooltips.html in a desktop browser
- mouseover one of the in-page icons
- a tooltip should show containing some text describing the icons
_Test the longpress for icons in a mobile browser (iOS Safari/Android Chrome):_
- open …

400 - Tooltips directly on icons via hover/longpress

---

src/components/datagrid/datagrid.js

- Stopped nested clicks from propagating
- http://localhost:4000/components/datagrid/example-nested-grids.html
Closes #371 
- Expand 4th row, click on any of the links inside nested grid
- Before, the cells on the outer grid is being focused instead of the clicked cells
- Now, the cells containing the clicked links should now be selected

371 datagrid nested link click

---

src/components/spinbox/_spinbox.scss

The spinbox height is not aligned to the height of it's side buttons when wrapped inside a .field-short class. This causes the spinbox to seem misaligned with the side buttons.
Closes #547.
Pull this branch and run the app. Open http://localhost:4000/components/validation/example-short-fields.html. Visually ensure the spinbox is the same height as it's surrounding plus and minus buttons.

547 - Spinboxes not aligned correctly

---

app/views/components/applicationmenu/example-top-level-buttons.html

Add 'is-selectable' class to '.popupmenu' element to allow proper spacing for checkmark left of text.
Closes #521.
Pull branch and run app. Open example page located in pro0ject at ./app/views/components/applicationmenu/example-top-level-buttons.html by putting http://localhost:4000/components/applicationmenu/example-top-level-buttons.html into browser. Confirm checkmark no longer overlaps text and maintains correct spacing.

521 - Dropdown list checkmark overlapping text

---

app/views/components/contextmenu/example-index.html
app/views/components/contextmenu/test-input-fields.html
src/behaviors/longpress/longpress.js
src/components/popupmenu/_popupmenu.scss
src/components/popupmenu/popupmenu.js
test/components/popupmenu/popupmenu.func-spec.js

This PR adds functionality to the popupmenu's context menu configuration that allows for a "longpress" to replace the `contextmenu` event behavior on a touch device.  Long-pressing the screen on an iOS or Android device replaces what would be right-clicking with a mouse in a desktop environment.
#245 
Pull this branch and run the demoapp.  Then:
_In a desktop browser:_
- open http://localhost:4000/components/contextmenu/example-index
- right-click anywhere in the page
- the context menu should open
_In a mobile browser (iOS Safari or Android Chrome):_
- open …

245 - Longpress to open Context Menus

---

app/views/components/lookup/test-states.html

- Fixed issue regarding dirty indicator not showing up on lookup
- Removed data-init='false' attribute from lookup element with dirty tracking
- http://localhost:4000/components/lookup/test-states.html
Closes #297 
- Open the dirty tracking lookup field
- Select different compressor
- Dirty tracking should now be displayed

297 Removed data-init=false attribute from lookup with dirty tracking

---

src/components/pager/pager.js
test/components/datagrid/datagrid-paging.func-spec.js

Issue: When paging is indeterminate prev page was never called when starting a datagrid mid page
What I did: Removed the drawing optimization for indeterminate paging since pagNum can't really change when paging is indeterminate, it isn't relevant to indeterminate paging. 
Closes #567
See git hub issue for these details.

fix for indeterminate paging not calling previous sometimes

---

app/views/components/field-options/example-index.html
src/components/field-options/_field-options.scss
src/components/field-options/field-options.js
src/components/input/_input.scss
src/core/_config.scss

Previously, mobile devices had difficulty using Field Options buttons due to their dependency on hover and focus events.  This PR sets up a touch-device mode, which permanently displays the field options button in environments where a touch screen is present.
Closes #555
Pull this branch and run the demoapp, then:
_In a desktop browser:_
- open http://localhost:4000/components/field-options/example-index
- hover each field and ensure that the field options button for each is displayed
- focus each field and ensure that the field options button for each is displayed
_In a mobile browser:_
- …

555 - Permanently enable the Field Options button's visibility on touch-based devices

---

app/views/components/contextmenu/example-field-options.html
app/views/components/field-options/example-input-fields.html

Added an example to show off the concept of using Field Options as a means to display a context menu.
#245 (longpress behavior)
#555 (touch-enabled field options)
- open http://localhost:4000/components/contextmenu/example-field-options.html
- all examples should show a working context menu attached to each field options button

245 - example of field options being used to display context menus

---

app/views/components/button/example-disabled-button-tooltip.html
src/components/button/_button.scss
src/components/button/readme.md

Disabled elements are not allowed to handle events in most browsers. A hover event to display element title is desired on disabled inputs and buttons.
Closes #453 
- Pull branch and run app.
- Visit example page to verify title renders as tooltip: http://localhost:4000/components/button/example-disabled-button-tooltip
- Review documentation for further instruction or documentation on purpose of / reasoning behind this workaround: ./src/components/button/readme.md

453 - SOHO-6041 show tooltips on disabled inputs and buttons

---

app/views/components/applicationmenu/test-empty.html
app/views/components/button/example-disabled-button-tooltip.html
app/views/components/button/example-index.html
app/views/components/button/test-on-tab.html
app/views/components/input/test-short-field-sizes.html
app/views/components/input/test-short-fields-validated.html
app/views/components/input/test-short-fields.html

Rampant misspelling of `role="presentation"`.
Closes #586 .
Pull this branch and `grep -rnw app/views/ -e 'role="presenatation"'` from root to recursively search all files for the misspelling.

586 - Role attribute value misspelling

---

src/components/popupmenu/popupmenu.js
test/components/popupmenu/popupmenu.e2e-spec.js

As per notes on 597, found clickout was no longer working
Closes #597
http://localhost:4000/components/contextmenu/example-index.html
- right click to open
- click on body to close
Also confirm long press still works on android and ios

597 - Fixed body click to close contextmenu again

---

src/components/modal/_modal.scss

Changed the `top: 0;` to `bottom: 0;` in _modal.scss (line: 298)
```
.btn-close {
position: absolute;
right: 0;
bottom: 0;
.icon {
width: 16px;
}
}
```
Closes https://github.com/infor-design/enterprise/issues/505
- Run http://localhost:4000/components/contextualactionpanel/test-nested.html
- Click Contextual Action Panel button
- Click Show Nested Modal button, Close Button should be underneath of the content.
**File Change/s**
**M** - src/components/modal/_modal.scss

505 - Fixes layout issue in nested modal

---

src/components/datagrid/datagrid.js

Sometime this version space key broke when entering data in a datagrid cell. This fixes that.
Closes #624 
- click into activity cell
- type "this is a space"
Spaces will work

624 - Make space key work again 

---

test/protractor.ci.bs.conf.js

Attempts to fix failing datetime tests on BS by specifying eastern US timezone (America/New_York), as we not sure what the default timezone is.
Check bs cron tests in the morning.
Screenshot of timezone passed correctly... and link to test.
https://automate.browserstack.com/builds/6eeace5179d6524a50f94db121afe12aa59dccc8/sessions/c638dd3ceb0d4016dc76e0412578e0029f4b43f9

Set timezone to Eastern Standard (Americas/New_York)

---

src/components/spinbox/_spinbox.scss

Unaddressed misalignment on iOS and Firefox discovered in QA.
Closes #547 
Related to [this comment](http://github.com/infor-design/enterprise/issues/547#issuecomment-413833103)
- Pull down and run app.
- Test http://localhost:4000/components/validation/example-short-fields in iOS (Xcode Simulator) and Firefox.
- Ensure all `.spinbox input` located as child of `field-short` class are aligned properly.

547 - Spinbox alignment off in iOS, Firefox

---

.travis.yml
test/protractor.ci.bs.conf.js

We are attempting to get all the tests working on the same timezone, in the case, America_New_York which is UTC -4:00. Tests are fired the next day, and that makes tests failed, as they are reporting the next day as the next next day.
| Timezone       | UTC |
| ------------- |:-------------:|
| Default  |	0:00 |
So, let's try setting everything to the expected timezone.
| Timezone       | UTC |
| ------------- |:-------------:|
| America/New_York |	−05:00 (or -4:00 DST)
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
https://www.browserstack.com/automate/capabilities
#649  …

649 - Set Timezones to New_York

---

src/components/hierarchy/hierarchy.js

Fixes selection event fires multiple times (stacks up) when paging back and forth.
Closes 654
Add code change and then..
1. Go to http://localhost:4000/components/hierarchy/example-paging.html
2. Expand a leaf
3. Go back
4. Expand again
In the network observe the request is fetched one time after expanded a second time

Fix for - Hierarchy control selection event firing multiple times when paging. #654

---

src/components/popupmenu/popupmenu.js
test/components/popupmenu/popupmenu.e2e-spec.js

A regression bug was reported in Mac Safari, where Popupmenus were closing before they were supposed to if a user was holding down the `Ctrl` key while clicking (The Mac OSX eqivalent of a PC's right click).  This PR fixes that issue.
Fixes #647
Pull the branch and run the demoapp.  Then:
- Open http://localhost:4000/components/contextmenu/example-index in Mac Safari
- use `Ctrl` + click to open a context menu anywhere in the page.
- release the `Ctrl` key.  The menu should not close, and should remain open.
Additionally, the tester should also check that inside the context menu, clicking …

647 - [Mac Safari] fix for menus prematurely closing while holding "ctrl" key

---

src/components/dropdown/dropdown.js
src/components/field-options/field-options.js
src/components/popupmenu/popupmenu.js
src/layouts/_layouts.scss
src/utils/environment.js

This PR addresses some mobile usability issues that came up as a result of the work on #245 (and related #555):
- Popupmenus that open up while a software keyboard is visible on screen would sometimes become half-sized or cut off.  Often the menus were positioned in a way that covered the trigger buttons, due to a timing issue that was causing the menus to open during the keyboard animations.
- Active states of input fields and field-options buttons would sometimes remain if a field options menu was opened, and focus was set on an outside input field.
- It was sometimes possible to incorrectly scroll out of bounds on an iOS device (read: the blue header was not always present on-screen …

245 and 555 - Fixes for cutoff popupmenus and incorrect active states on fields with options

---

src/components/colorpicker/colorpicker.js

Modal will not close on press of dropdown arrow. Only colorpicker will close.
Closes #491 .
Also remedied a small whitespace issue.
Still to add is keypress functionality mentioned in comments to related issue and specifically [here](https://github.com/infor-design/enterprise/issues/491#issuecomment-415541832).
Pull branch, run app, hit [url test page](http://localhost:4000/components/colorpicker/test-modal.html).
- Click button to show modal
- Click dropdown arrow to show colorpicker.
- Click dropdown arrow again to close colorpicker.
**Additional context**
See comments on old PR: #660

491 - Clean reset and PR for Color palette not closing on no color choice

---

src/utils/environment.js

This code causes an error when running IE. It in the end made it appear like paste was not working.
This should fix it as the warnings where chrome specific.
Fixes #548
- run IE
- check console for now errors
- paste in the editor with ctrl-c

548 - Fix paste and IE errors

---

src/components/modal/modal.js

- Disabled closing of modal on enter key if target is not a button
- http://localhost:4000/components/modal/example-index.html
Closes #331 
- Click "Show Modal" button to display modal box
- Type in "test" on input field
- Hit Enter key
- Modal box should no longer close upon hitting Enter key

331 disabled closing of modal on enter key if target is not a button

---

src/components/icons/svg.html

Icons on the tree when in + - mode are reversed.
Closes #685
http://localhost:4000/components/tree/example-plus-minus-folders.html
- expand and collapse nodes 
- notice that the + means its closed and the - means it is open the icons were inverted

Reverse incorrect icons

---

src/components/modal/_modal.scss

I reverted the `.modal-content .btn-close` to `top: 0` and created a new css rule specific only inside of the modal-buttonset class.
```
> .modal-buttonset {
.btn-close {
position: relative;
bottom: 0;
}
}
```
So this solution will also fixed the issue in nested modal https://github.com/infor-design/enterprise/pull/602
Closes https://github.com/infor-design/enterprise/issues/662
- Run http://localhost:4000/components/modal/example-close-btn.html
- Click Show Modal button
- X button should now be on the top-right of the modal

662 - Fixed modal x button

---

app/views/components/cards/test-tabs-card.html
src/components/tabs/_tabs-horizontal.scss
src/components/tabs/_tabs.scss

The issue is very inconsistent when resizing the browser and it flickers.
I changed the right: 51px to right: 0; to eliminate the white space when the button arrow is not yet visible.
This is under the `.tab-container` and `.horizontal` container.
```
&::after {
right: 0; // bleed into the tab list (width of this element + 1 for border) & eliminate unncessary white space
}
```
Then I created a css rule where I will back the position of the fade edge in the tab list so that it will not overlap when the button arrow is visible.
```
.has-more-button.tab-container.horizontal,
.has-more-button.tab-container.header-tabs {
&::after {
right: 51px;
}
}
```
I created a test page for this, …

671 - Fixes whitespace in tablist in a card

---

app/views/components/validation/example-short-fields.html

Unable to view selected item in dropdown as inline style width was too small. Increased to 40px for dropdown and multiselect for adequate visibility of selected item on close of dropdown and multiselect.
Closes #673 
- Pull associated branch.
- `npm start` to run app.
- Browse to [URL](http://localhost:4000/components/validation/example-short-fields.html)
- Ensure visibility of selected item in dropdown and multiselect "Custom" fields

673 - dropdown selected item

---

src/components/editor/editor.js
test/components/editor/editor-api.func-spec.js

548 was failed QA because 'ng' is removed from all text when pasting. This fixes that
Closes #548
http://localhost:4000/components/editor/example-index.html
- copy any text with ng in it
- paste

548  - Added a fix to not strip ng from text

---

src/components/popupmenu/popupmenu.js
test/components/datagrid/datagrid.e2e-spec.js

Regression solved when reopening submenus on a popup menu using immediate mode.
Closes #701
http://localhost:4000/components/datagrid/test-contextmenu.html
- right click the grid
- click out
- right click again (submenu should now be shown)

701 - submenu cutoff

---

src/components/applicationmenu/applicationmenu.js
src/components/autocomplete/autocomplete.js
src/components/searchfield/searchfield.js
test/components/autocomplete/autocomplete-api.func-spec.js

A regression was found where searchfield components inside of application menus would not reset the menu's filtering when the clear button was clicked.  This PR fixes that bug.
Closes #702 
- Pull this branch and run the demoapp.
- open http://localhost:4000/components/applicationmenu/example-filterable.html
- In the app menu's searchfield, type "history".  The app menu should filter all results out except for the "History" header.
- Click the X button to clear the searchfield's contents.
After clicking the X, all of the accordion's items present.
Also, make sure the functional tests pass. …

702 - Fix for App Menu Searchfield's clear button

---

app/views/components/autocomplete/example-searchfield.html
src/components/datagrid/datagrid.editors.js
src/components/searchfield/searchfield.js

It was reported that example http://localhost:3000/components/autocomplete/example-searchfield.html didnt work. On examination it wasnt that bad of a regression, just an older example that needed updating. Did some cleanup to resolve.
Closes #714 
http://localhost:3000/components/autocomplete/example-searchfield.html
- focus and type 'm'
- after that the list should show some items
For good measure try the state column on this example as well.
http://localhost:4000/components/datagrid/test-editable-autocomplete.html

Added fix for not running source

---

app/src/js/routes/data.js

Fixes #743
Pull this branch and run the demoapp, then:
- open http://localhost:4000/components/dropdown/example-index
- open a dev tools console
- check this page's response headers.  Ensure there are no `Access-Control-Allow-Origin` or `Access-Control-Allow-Headers` headers.
- then, open http://localhost:4000/api/states
- check this page's response headers.  Ensure there are `Access-Control-Allow-Origin` and `Access-Control-Allow-Headers` headers passed.

743 - Allow CORS from Demoapp REST endpoints

---

src/utils/environment.js

Backing out some changes made to remove the `console.warn` for passive event listeners on `touchstart` events.  This unfortunately caused some breakage on the ListBuilder component in #742. 
#414 
pull this branch and run the demoapp, then:
- open http://localhost:4000/components/listbuilder/example-index.html
- ensure that the ListBuilder component invoked by checking any of the toolbar buttons, and selecting/deslecting the ListBuilder items.

Backing out changes related passive event listeners on touchstart events

---

test/components/dropdown/dropdown.e2e-spec.js
test/components/multiselect/multiselect.e2e-spec.js

Attempting to fix a couple of sporadically failing e2e tests by ensuring they are properly setup for `async`/`await`.
#753
Pull this branch and run the e2e tests.  Ensure there are no timeouts on the two tests that are changed.

753 - Fix Dropdown/Multiselect tests that were missing `await`

---

src/components/datagrid/_datagrid.scss

Added classes like l-right-text and l-center-text with position absolute to align the sort-indicator on RTL mode
Closes #502 
1. Open http://localhost:4000/components/datagrid/test-rtl-text.html?locale=ar-SA
1. Check the sort-indicator in datagrid table header particulary the BDO header. 
1. The "All sort" indicator should be vertically and horizontally aligned besides the labels.

502 - RTL datagrid sort indicator alignment

---

app/views/kitchen-sink.html

This PR fixes an issue on the demoapp's landing page (The kitchen sink) where it's suddenly possible to right click anywhere for an IDS context menu, which clashes with some other components that implement a right click for some operations.
#764 
- pull this branch and run the demoapp
- open http://localhost:4000
- scroll down to "Right Click Menu"
- ensure that there are two input fields there that can be right clicked for a context menu.   There should NOT be an explanation to right-click anywhere on the page.

764 - Fix for context menu example

---

app/src/sass/_directory.scss
src/components/accordion/_accordion.scss
src/components/badges/_badges.scss
src/components/bullet/_bullet.scss
src/components/button/_button.scss
src/components/calendar/_calendar.scss
src/components/circlepager/_circlepager.scss
src/components/colorpicker/_colorpicker.scss
src/components/counts/_counts.scss
src/components/datagrid/_datagrid.scss
src/components/drag/_drag.scss
src/components/header/_header.scss
src/components/hierarchy/_hierarchy.scss
src/components/hyperlinks/_hyperlinks.scss
src/components/icons/_icons.scss
src/components/input/_input.scss
src/components/listview/_listview.scss
src/components/pager/_pager.scss
src/components/popupmenu/_popupmenu.scss
src/components/processindicator/_processindicator.scss
src/components/searchfield/_searchfield.scss
src/components/slider/_slider.scss
src/components/toast/_toast.scss
src/components/typography/_typography.scss
src/core/_config.scss
src/layouts/_layouts.scss
src/themes/dark-theme.scss
src/themes/high-contrast-theme.scss

We want to slowly replace references to direct color variables from the color palette and use contextual token variables in their place.
_i.e_ Replace `color: $azure06` with `color: $color-primary`
Closes #708 
1. `npm start` to start the demo app
1. Verify
- Colors look normal on the normal theme
- Some colors change when switching themes ~, specifically the new Uplift theme~
_Edit: The themes aren't changing properly as there is a major structure/cascade issue on the tokens side. This can still be merged, but don't expect to see anything different on the Uplift theme when switching and …

First pass at replacing some color palette color variables with token variables

---

app/views/components/tree/example-preserve-restore.html
src/components/tree/readme.md
src/components/tree/tree.js

Need a method to preserve the original state of nodes in terms of enablement (disabled or enabled) and then restore the nodes to that original state once preserved.
Closes #751 .
- Pull branch and run app.
- Go to http://localhost:4000/components/tree/example-preserve-restore.html
- Click Preserve button. Note which nodes are disabled or enabled.
- Open developer tools console.
- Remove class `is-disabled` and/or `aria-disabled="true"` from any given node(s). Add  class `is-disabled` and/or `aria-disabled="true"`to any given node(s).
- Click Restore button. Note that nodes return to …

751 - Add preserve and restore methods for tree

---

src/components/bar/bar.js
src/components/monthview/monthview.js
test/components/datepicker/datepicker-api.func-spec.js
test/components/monthview/monthview-api.func-spec.js

Made a fix for faulty markup on tooltips that caused them to render badly on bar charts. In order to pass tests going forward had to fix the failing monthview tests.
Explanation is today is a new year in arabic calendar. So basically the month changed going forward since the calendar shows todays date. This isnt really reflected in the test either so bumped the year so the tests pass going forward.
Closes #739 
- test any of the examples on the ticket such as http://localhost:4000/components/bar-grouped/example-animation.html by hovering the bar set
- Tooltip now ok.
- Let tests run

739 - Added fix to bar chart tooltips, Fixed Failing Month Tests

---

app/src/docs.scss
app/src/index.scss
package.json
scripts/configs/sass.js
src/components/busyindicator/_busyindicator.scss
src/components/button/_button.scss
src/components/calendar/_calendar.scss
src/components/cards/_cards.scss
src/components/checkboxes/_checkboxes.scss
src/components/datagrid/_datagrid.scss
src/components/dropdown/_dropdown.scss
src/components/header/_header.scss
src/components/hierarchy/_hierarchy.scss
src/components/listview/_listview.scss
src/components/processindicator/_processindicator.scss
src/components/radios/_radios.scss
src/components/switch/_switch.scss
src/components/tabs/_tabs-horizontal.scss
src/components/tabs/_tabs.scss
src/components/typography/_typography.scss
src/core/_config.scss
src/layouts/_layouts.scss
src/patterns/_card-deck.scss
src/patterns/_header-detail.scss
src/patterns/_master-detail.scss
src/patterns/list-detail/_list-detail.scss
src/themes/dark-theme.scss
src/themes/high-contrast-theme.scss
src/themes/light-theme.scss
src/themes/uplift-theme.scss

- Moved sass imports up one level from config, to their corresponding themes for proper sass/token/color cascade and overriding
- upgraded to use ids-identity@1.3.2
- refactored some existing vars into tokens
https://github.com/infor-design/enterprise/issues/785
1. `npm i`
1. `npm run build`
1. <http://localhost:4000>
- View the regular theme
- Compare it to the other themes. The most dramatic Uplift theme change will be the primary color to a deeper blue. (screenshots are on the ticket)

Tweak the order of some sass imports for correct theming

---

test/components/tree/tree.e2e-spec.js
test/components/tree/tree.func-spec.js

Creates tests for disable(), enable() methods on Tree.
Closes #752 .
- Pull branch `752-add-tree-tests`
- `npm run start` (`npm i` first if need to compile node_modules)
- `npm run test` to run all tests
- can `npm run functional:local` for just functional tests
- can `env PROTRACTOR_SPECS='components/tree/tree.e2e-spec.js' npm run e2e:ci` for just end-to-end tests on Tree.
- Ensure new tests pass
- For extra credit, comment on robustness of tests and suggest any improvements

752 - add tests for new Tree methods

---

src/components/dropdown/_dropdown.scss
src/components/dropdown/dropdown.js
src/components/trackdirty/trackdirty.js

Possible issue in mobile bubbling the touchStartCallback function.
Tried to debug in safari web inspector (while my phone is connected) and it seems that the function is working but after this function is done, it started to close the dropdown while scrolling.
Added a `e.stopPropagation()` at the end of the line.
Closes https://github.com/infor-design/enterprise/issues/656
This is only reproducible in:
- http://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html 
- Open in any mobile browser
This is my assumption solution. Let me know your thoughts.

656 - Added fix for dropdown closing when scrolling

---

docs/TESTING.md
src/components/dropdown/dropdown.js
test/components/dropdown/dropdown.e2e-spec.js
test/components/lookup/lookup.e2e-spec.js

This PR re-enables some Dropdown e2e tests that check some keyboard functionality.  Previously, they were disabled because they were not always passing on TravisCI, and it wasn't clear whether or not the tests for them were correct.  The tests have been modified to work more reliably, and have been re-enabled.
Additionally, a handful of duplicate Lookup tests were removed, and the remaining tests were renamed for better context.  There were also some previously failing lLookup tests that were fixed.
- Closes #570
- partially updates #753 
Note that one of the two tests can be further improved after some changes to the Dropdown component.  Made a …

753/570 - Fix dropdown e2e tests

---

docs/templates/documentationjs/theme-ids-website/section._

Updates the heading of the generated docs pages to a less redundant and more recognizable term.
Formerly:
* Updates will be included the next time docs are generated for a release.

Update section title in docs template

---

src/components/editor/editor.js

Append a dynamic id in the input field and in bind modals.
line(912)
```
<label for="image-${this.id}">${Locale.translate('Url')}</label>
<input id="image-${this.id}" name="image-${this.id}" type="text" value="${this.settings.image.url}">
```
line(826)
```
self.insertImage($(`#image-${self.id}`).val());
```
Closes https://github.com/infor-design/enterprise/issues/746
- Run http://localhost:4000/components/editor/example-index.html
- Click on the Insert Image button
- Inspect the input field and observe that the id is "image".
- There should be a unique id in the input field not just …

746 - Added fix for unique id editor

---

src/components/lookup/_lookup.scss

Adding `-webkit-text-fill-color` and set it as the same variable/value of color property.
Closes https://github.com/infor-design/enterprise/issues/762
- Run http://localhost:4000/components/lookup/example-editable-strict.html
- Click on the lookup icon. The "Lookup that can only be edited by selection in modal" window will appear
- Select 2142201, 2241202, 2342203 and click the "Apply"
- In the "Lookup that can only be edited by selection in modal" The color of the text should now appearing in black.

762 - Added fix for lookup color text

---

scripts/deploy-documentation.js

Seeing `NAN` as a time value for elapsed time in the documentation deploy script. The fix was using the proper key in the stopwatch object.
n/a
1. `npm run documentation -- --test-mode --dry-run`
- Make sure all elapsed seconds (purple in terminal) are numbers (including "0") and not "NAN"

Fixed "NAN" in deploy docs script

---

src/components/dropdown/dropdown.js

My initial fix is to change the value of `searchInputHeight` from `34` to `24` in dropdown.js.
Closes https://github.com/infor-design/enterprise/issues/786
- Run http://localhost:4000/components/dropdown/test-extra-padding-short-fields.html
- Expand the dropdown
- There should be no scrollbar.

786 - Initial fix for dropdown height

---

app/views/components/datagrid/example-grouped-headers.html
app/views/components/datagrid/test-update-grouped-headers.html
src/components/datagrid/datagrid.js

When some columns hidden by default at render time or by updating later header group colspan was not aligning because it was calculating wrong value.
Group headers were not updating when columns reorder. While dragging column for reorder the drop target indicator arrows were not aligning with each case row height and filterable headers.
This PR should fix all those alignment issue and correct colspan value.
Closes infor-design/enterprise-ng#147
Closes #374 (formerly) https://jira.infor.com/browse/SOHO-8151
http://localhost:4000/components/datagrid/example-grouped-headers.html
- Open above …

NG-147, 374 - Fixed hidden column and group headers alignment with Datagrid

---

app/views/components/tree/test-sortable-update-dataset.html
src/components/tree/tree.js

Dataset was not syncing when drag-drop/sorting tree nodes
Closes #718
http://localhost:4000/components/tree/test-sortable-update-dataset.html
- Run in console `$('#addnode-tree').data('tree').settings.dataset`
- Result object data should be as:
```
-Public Folder
-New Item 1
-New Item 2
-Node 2.1
-Node 2.2
-Node 2.2.1
-Node 2.2.1.1
```
- Drag "New Item 2" and drop "Public Folders"
- Drag "New Item 2" and drop at same level "Public Folder"
- Drag "New Item 2" and drop "New Item 1"
- Drag "New Item 2" and drop at same level "Public Folder"
- Run again …

718 - Fixed data was not sync with sorting Tree

---

app/views/components/dropdown/test-onkeydown-ctrlkey.html
src/components/dropdown/dropdown.js

Fixes an issue where the `ctrlKey` keydown event was not firing. This was a purposeful non-event as there was as preexisting issue that pressing `ctrlKey` + `someOtherKey` fired an event in dropdown search for `someOtherKey`. Now, the `ctrlKey` is caught in callback `onKeyDown` and event is fired, allowing custom code implementation inside the `ctrlKey` keypress.
Test page markup came directly from client. No alterations made in an effort to demonstrate the fix with content they provide.
Closes #793 .
- Pull branch
- `npm start`
- Browse to …

793 - Fix ctrlkey onkeydown and add test page

---

src/components/popupmenu/popupmenu.js

- Disabled popup menu when containing tab is disabled
- http://localhost:4000/components/tabs/example-enable-disable.html
Closes #736 
- Click "Disable Entire Tabs Control" button to disable tab control
- Click on disabled "Dropdown" tab menu
- Popup menu should not be displayed since tab menu is disabled

Disabled opening of popup menu when element is disabled

---

app/views/components/datagrid/test-save-settings.html
src/components/datagrid/datagrid.js

It doesn't return an array or object, instead, it returns a scalar value. There's a condition that if there's an array, that's the only time that it will execute the selected property.
```
if (input.is('select')) {
if (conditions[i].value instanceof Array) {
for (let j = 0; j < conditions[i].value.length; j++) {
input.find(`option[value="${conditions[i].value[j]}"]`).prop('selected', true);
}
} else {
input.find(`option[value="${conditions[i].value}"]`).prop('selected', true);
}
input.trigger('updated');
}
```
Closes https://github.com/infor-design/enterprise/issues/791
- Run …

791 - Added fixes for save filter

---

app/views/components/datagrid/example-keyword-search.html
src/components/datagrid/datagrid.js

Adding formatted value for ampersand.
```
value = value.replace(/(<([^>]+)>)|(amp;)|(&lt;([^>]+)&gt;)/ig, '');
```
Closes https://github.com/infor-design/enterprise/issues/778
- Run http://localhost:4000/components/datagrid/example-keyword-search.html
- Click on search icon
- Type "&" (with trailing space)
- There should be a results and highlighted.

778 - Added fix for datagrid search special characters

---

app/views/components/dropdown/example-placeholder.html
app/views/components/multiselect/example-placeholder.html
src/components/dropdown/_dropdown.scss
src/components/dropdown/dropdown.js
test/components/dropdown/dropdown.e2e-spec.js
test/components/multiselect/multiselect.e2e-spec.js

Allows a user to view placeholder text in the multiselect dropdown when no options are selected. Also added an example for dropdown
Closes #832 
http://localhost:4000/components/dropdown/example-placeholder.html
and
http://localhost:4000/components/multiselect/example-placeholder.html
Placeholder will show if nothing is selected, note that the dropdown has a blank item in it to reset the placeholder.
Thanks @picitelli !

832 - Added examples and fixes to placeholders on dropdowns

---

app/views/components/datagrid/example-keyword-search.html
src/components/datagrid/datagrid.js

The innerHTML produces `&amp;` instead of `&`. I just replace the value of it when searching.
```
if (this.innerHTML.replace('&amp;', '&') === this.textContent)
```
I also added the `amp;` in the regEx.
Closes https://github.com/infor-design/enterprise/issues/849
Relates https://github.com/infor-design/enterprise/pull/828
- Run http://localhost:4000/components/datagrid/example-keyword-search.html 
- Type words with special characters like &, #, %
- Searching words with those characters should be highlighted.

849 - Added fix for special characters search highlighting

---

app/views/components/tree/test-sortable-update-node.html
src/components/tree/tree.js
test/components/tree/tree.e2e-spec.js

After use updateNode() sortable/drag-drop was stop working. Toggle node was also selecting nodes with multiple select. This PR will fix these issue.
Closes #618
Closes #582
http://localhost:4000/components/tree/test-sortable-update-node.html
- Drag-drop any node to change the sorting
- Should not be any issue with drag-drop
- Click on button "Update"
- It should change "Public Folders" (file type) to be "New Public" (Folder Type)
- And add two new nodes in this folder
- Drag-drop any node (including these new added) to change the sorting
- Should not be any issue with …

618, 582 - Fixed sortable update node and multiple toggle/select mixed with Tree

---

package.json
src/core/_controls.scss

http://localhost:4000/components/notification/example-index.html was missing styles, added back a merged out _notifcation.scss
Also demo.css was giving a 404 on the demo server on any page. fx http://localhost:4000/components/notification/example-index.html
Fixes #675
- run npm run start
- check notifcations page
- check console for errors.

Restore missing demo styles

---

src/layouts/_layouts.scss

http://localhost:4000/components/calendar/example-index.html
- had a layout issue when selecting a day, the event details would flow to the bottom
Fixes #675 (more)
http://localhost:4000/components/calendar/example-index.html
- click a day with an event
- details should show on the right
@EdwardCoyle can you follow up on the layout issues that you were addressing where you added this?
https://github.com/infor-design/enterprise/blame/9b817555ddfee31739d758105c1212a1ae62dafb/src/layouts/_layouts.scss#L808
Im not sure what issue you saw. Perhaps add the font size to the real element

Fix for calendar layout issue

---

src/components/datagrid/datagrid.formatters.js
src/components/datagrid/datagrid.js

- Updated applyFilter function to enable filtering of datagrid rows using tree child elements
- http://localhost:4000/components/datagrid/test-tree-filter.html
- Closes #437 
- Click on searchfield under "Task" column header
- Test keywords "quotes", "contact" or other keywords that can be found on child nodes
- Rows should be filtered accordingly

Enabled filtering of child rows

---

test/components/tabs/tabs-api.func-spec.js
test/components/toolbar-flex/toolbar-flex-api.func-spec.js

Trying to fix some [test failures](https://travis-ci.com/infor-design/enterprise/jobs/148821759#L2315) that cropped up during the nightly build of EP over the weekend. 
The test failures in question are not e2e tests like the one's we've been fixing in #753.  They are functional tests that randomly failed.  After some discussion with @tmcconechy, we decided to attempt to fix this failure by removing references to extra elements on the page, which can unexpectedly cause test failures in some cases.  The Flex Toolbar tests require a Popupmenu on the page, so some extra cleanup code has been added to remove extraneous Popupmenus.
n/a
**Steps necessary …

Improve Flex Toolbar functional tests

---

src/components/charts/_charts.scss
src/components/completion-chart/_completion-chart.scss
src/components/completion-chart/completion-chart.js

Removing some margin when in tablet view. It seems that the issue occurs on that viewport.
Closes https://github.com/infor-design/enterprise/issues/886
- Run http://localhost:4000/components/completion-chart/example-colors.html
- Try to resize or change the viewport of the browser.
- `#880e0e` and `alert-yellow` completion bar should now be aligned properly

886 - Added fix for completion chart alignment issue

---

app/views/components/datagrid/example-keyword-search.html
src/components/datagrid/datagrid.js
src/utils/string.js

Creating an escape regEx for `highlightingSearchRow()`
In string.js
```
stringUtils.escapeRegExp = function escapeRegExp(s) {
return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); //$& whole matched string
};
```
Then use it in the `highlightingSearchRow()`
```
const exp = new RegExp(`(${stringUtils.escapeRegExp(term)})`, 'gi');
```
I also used the xssUtils.unescapeHTML for the special characters.
```
if (xssUtils.unescapeHTML(this.innerHTML) === this.textContent) {
```
Closes https://github.com/infor-design/enterprise/issues/860
- Run …

860 - Added fix for $ sign highlighting

---

src/components/tree/tree.js

- Closed popup menu when clicking on other tree nodes
- http://localhost:4000/components/tree/example-context-menu.html#
Closes #898 
- Right-click on the Node Two to open the contextmenu
- Click on the Node One or on the child nodes of Node Two
- Contextmenu should now close

898 - Closed popup menu when clicking on other tree nodes

---

app/views/components/datagrid/example-export-from-button.html
src/utils/excel.js

Exportable true/false columns was not working. It should work as all columns with `exportable: true` (or without exportable key with column node in user data) should be exported. All columns with `exportable: false` should be excluded. Their should be no missing data in between columns.
Closes #787
http://localhost:4000/components/datagrid/example-export-from-button.html
- Click on "Export To Csv"
- Click on "Export To Excel"
- Go to downloaded location
- Should be two files downloaded "myExport.xls" and "myExport.csv"
- Open "myExport.xls" it might show warning about …

787 - Fixed exportable true/false columns was not working with Datagrid

---

app/views/components/autocomplete/example-keyword.html
src/components/autocomplete/autocomplete.js
src/components/listfilter/listfilter.js

- Added keyword filterMode for autocomplete component
- http://localhost:4000/components/autocomplete/example-keyword.html
Closes #418 
- Type in "al ca wy" or any keyword with space in between
- Autocomplete should be able to filter out data using those keywords

418 - Added keyword filterMode for autocomplete component

---

src/components/dropdown/_dropdown.scss

- Updated ios multiselect alignment
- http://localhost:4000/components/multiselect/example-index.html
Closes #912 
- Go to http://localhost:4000/components/multiselect/example-index.html on any iOS browsers
- Open the multiselect dropdown
- Checkboxes should now be aligned

912 - Updated ios multiselect alignment

---

src/components/datepicker/datepicker.js

Clear was giving an error on range picker. This fixes it.
Closes #937 
(Before was an error, now its fixed). 
http://localhost:4000/components/datepicker/example-range.html
- on the "Range - No Initial value" field
- open picker
- hit cancel 
- check other pickers for "fun"

937 - Fix datepicker error [v4.11.x]

---

src/components/input/_input.scss

Fixed alignment of the X on clearable inputs, that broke.
Closes #919 
http://localhost:4000/components/input/example-clearable.html
- type
- ensure the x is centered (and works ok)

919 - Added fix for padding issue [v4.11.x]

---

app/views/components/validation/test-resetform.html
src/components/validation/validator.js
test/components/validation/validation.e2e-spec.js

Reset form was resetting the form, but after that no errors will ever appear again. Added a test for this case as well.
Closes #936
http://localhost:4000/components/validation/test-resetform.html
- clear email field and tab out and an error should show
- click reset form button and error will reset
- clear email field and tab out again  error will show (before it did not)

936 - resetForm function not allowing errors to appear after [v4.11.x]

---

src/components/validation/validator.js

Possible solution for validation not firing on mobile. 
On `listclosed.validate` checks for touch device, adds `.focus()` then `.blur()` after `100ms`
closes #659 
* go to http://localhost:4000/components/dropdown/example-validation.html
* open dev tools and select ios device or use xcode ios simulator 
* select empty from the dropdown.

659 - Dropdown mobile validation

---

gruntfile.js
scripts/generate-bundle-banner.js

This PR addresses several issues with the comment banner used on generated CSS and JS files:
- Previously the banner didn't match between JS and CSS files.  
- The one being used in CSS was hardcoded against an old license, and wasn't having the date/revision properly applied.  It was also still calling the project "SoHo Xi"
- no way to pass a list of custom components to the banner
- no way to mark a `(custom)` identifier after the IDS version.
Closes #856 
pull this branch and run:
```sh
npm run build:custom -- --components=button,input,popupmenu
```
1. Ensure the following files both …

856 - Modified the banner generator used on compiled files to match on JS/SCSS [v4.11.x]

---

app/views/components/message/example-index.html
src/components/message/message.js
src/components/modal/_modal.scss

Creates a setting that allows the choice of a status for a message modal and styles accordingly. Some mild refactoring occurred during this PR to reduce overhead and promote semantic class naming.
Closes #703 .
- Pull branch
- Run app
- Browse to http://localhost:4000/components/message/example-index
- Click Error, Warning, and Success buttons and ensure new styling is in effect and appropriate. Styling is appearance of SVG of appropriate color and color of `modal-title`

703 - Add message modal status icon and color options

---

app/views/components/tabs-multi/example-index.html
src/components/popupmenu/popupmenu.js

Fixes the spillover `popupmenu` not opening on mobile by changing the multi-tab demo to only enable `action-popupmenu` on desktop.
closes #619 
* Open http://localhost:4000/components/tabs-multi/example-index.html
* Open mobile devtools in Chrome.
* Tap/Click on the "More" button in the tab menu.

619 - Fix tabs spillover dropdown

---

app/views/components/lookup/test-custom-matching.html
src/components/datagrid/datagrid.js
src/components/lookup/lookup.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/lookup/lookup.e2e-spec.js
test/components/monthview/monthview.e2e-spec.js
test/components/multiselect/multiselect.e2e-spec.js

Recent pr's to allow multiselect across pages broke some selection in lookup in different cases. This was raised as 3 issues all fixed by the same thing. The problem is that now the selected rows are kept on a separate array, this array got out of sync.
Added new tests for all the test scenarios mentioned.
Closes #949
Closes #953
Closes #928
http://localhost:4000/components/datagrid/example-multiselect
* open list
* tab once to grid
* down and up arrow to pick one
* space to select
http://localhost:4000/components/datagrid/example-multiselect
* select first row
* select second row
* sort …

949 - lookup issues [v4.11.x]

---

test/components/monthview/monthview-api.func-spec.js

Some tests started to fail because the arabic month changed. Trying to stablize these.
Because the calendar is driven by gregorian and then "converted" to arabic the month starts out on a gregorian month and then is changed, but the starting day might be someplace in the middle of the month it gets off. This should fix , but have to keep an eye on this when the next month changes.
Closes #975
Ensure functional tests pass on CI.

975 - Fix month view tests [v4.11.x]

---

src/components/searchfield/_searchfield-toolbar.scss
src/components/tabs-module/_tabs-module.scss

Fixed incorrect bg color on "in-page" non-collapsible searchfields
Closes #972 
- open a browser to http://localhost:4000/components/datagrid/test-click-event-on-rows.html
- in-page searchfield background color should match to IDS color `graphite02`, appearing like this...
...and not like this...

972 - Fix incorrect searchfield background color [v4.11.x]

---

app/views/components/datagrid/test-empty-message-contained.html
src/components/emptymessage/emptymessage.js

Click event is not invoked on `emptyMessage` button.
Closes #667 
- Pull branch
- Run app
- http://localhost:4000/components/datagrid/test-empty-message-contained
- Click `dataqrid` header to make `emptyMessage` appear
- Click `emptyMessage` button to invoke `emptyMessage` button click event and ensure event invokes.

667 - Add click event option to emptyMessage button.

---

app/views/components/datagrid/test-accept-default-date-value.html
src/components/datagrid/datagrid.formatters.js

- Allowed use of default non date value for date fields
- Added test page
- http://localhost:4000/components/datagrid/test-accept-default-date-value.html
Closes #891
- On load, the "Order Date" on the 3rd row should have "N/A" as a default value

891 Allowed use of default non date value for date fields

---

src/utils/excel.js

Adds an optional parameter of "sep=," to the `exportToCsv` method. Fixes issue when a user's locale setting uses `;` as default separator in csv files. 
closes #378 
* change your machine's language setting to Swedish in System Preferences > Language & Region
* go to http://localhost:4000/components/datagrid/example-export-from-button.html 
* export to csv

378 - Datagrid csv export

---

app/views/components/modal/test-dynamic-content.html

Chrome console error:
_Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-012427b8' http://squizlabs.github.io http://myserver.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution._
N/A
- Pull branch
- Run app
- Browse to http://localhost:4000/components/modal/test-dynamic-content
- Open Chrome Dev Tools
- Click "Open Modal"
- Select second option in Type input field ("This Value Shows More Content")
- Ensure there are no errors in …

Fix modal test-dynamic-content page console error.

---

src/components/tabs/tabs.js

If `prevLi.is(notATab)` set the first available tab to selected instead of the previous tab.
closes #947 
* go to http://localhost:4000/components/tabs/example-enable-disable-individual-tabs.html
* Disable the "Form Elements" tab
* dismiss the dismissable tab
* the first available selectable tab will be selected and focused

947 - Fix disabled tab accessible

---

src/components/hierarchy/_hierarchy.scss

Adding this fix for responsive view, aiming a width from 320px to 450px so the back button will not cut off, and also, it will eliminate the scroll bar.
Closes https://github.com/infor-design/enterprise/issues/933
- Run http://localhost:4000/components/hierarchy/example-paging.html
- Make the page responsive (minimum width of 320px, max width of 450px).
- On the first load of the page, scrollbar should now be unseeable.
- Click on Kaylee Edwards and you will be able to see the back button.
- Back button should be in a proper position and not cutoff.

933 - Fix back arrow button gets cut off on responsive view

---

src/components/datagrid/datagrid.js
test/components/hierarchy/hierarchy.func-spec.js

Error icon tooltips were not showing after hide one time.
Closes #1008
- Click on empty cell in column "activity" (row 3)
- Click on another cell to validate the cell
- The error icon displays, but tooltip for this error icon should be hidden
- Hover on the icon should be able to see the error message tooltip

1008 - Fixed validation icon tooltips with Datagrid

---

src/components/editor/editor.js

On Windows Edge, IE and Firefox, alignment was not clear formatting when done with Select All.
#473
http://localhost:4000/components/editor/test-clear-formatting.html
- Apply Right Align on the first paragraph
- Press Command+A or Ctrl+A to select all
- Click Clear Formatting icon
- See it should clear the selected formatting

473 - Fixed alignment was not clear formatting with editor

---

src/components/datagrid/datagrid.js

Takes a deep copy of the originalcolumns so that any change is not updated via Javascripts reference to the object.
Closes #1009 
Go to '/components/datagrid/example-reorder.html'
reorder the datagrid buttons
Click on 'the reset to default button under the more button for the datagrid'
repeat steps 2 and 3.

1009 - Datagrid reset to default does not work on second attempt

---

src/components/contextualactionpanel/_contextualactionpanel.scss

By default, the background color that was used in the contextual action panel modal inherits the modal content bg color which is white. So the white background that you're seeing is still the modal, not the detail section of contextual panel.
To fix this, adding a background color on the modal body wrapper of the contextual action panel so that it will not affect the entire page that uses the modal. Reuse the variable that was utilized in detail section.
Closes https://github.com/infor-design/enterprise/issues/285
Relates https://github.com/infor-design/enterprise/issues/393
- Run …

285 - fix for high contrast background color in contextual panel

---

app/src/js/routes/directory-list.js
app/views/tests/listing/api.html
app/views/tests/listing/functional.html

This PR fixes an issue in the demoapp's directory listing we discovered where some old regex matches that were meant to strip out `.JS/.SCSS/.MD` files from the index pages was causing test files with certain names to be removed from the list.
Closes #985 
- Open http://localhost:4000/tests/listing/list
- Ensure that there are two files in the list, called `Api` and `Functional`.

985 - Remove unnecessary limits on demoapp file names

---

src/components/datagrid/datagrid.js

While selecting downwards from Id 1 to Id 10, then select upwards with a mixed selectable tree grid row was not activating.
Closes #412
http://localhost:4000/components/datagrid/test-tree-row-activated.html
- Try clicking rows downwards from Id 1 to Id 10 (not on checkbox)
- Then click upwards
- It should activate row as soon clicked on it

412 - Fixed row was not activating with tree datagrid [v4.12.x]

---

app/app.js
app/src/js/middleware/remove-headers.js

To comply with our agreed-upon Veracode dynamic scan mitigations, this PR strips out identifying headers from the demoapp.
Closes #959 
- Pull down this branch
- Run the demoapp
- Open http://localhost:4000
- Open a dev tools console to the network tab and click the entry for `localhost`.  Ensure that there are no entries in the "Response Headers" that have a key of `Server` or `X-Powered-By`:

959 - Added demoapp middleware for stripping out identifying headers

---

src/components/datagrid/datagrid.js

A bug where new row added with rowstatus did not display tooltip on hover in IE11.
Closes #1081 .
Came out of #227 and #994 . Failed QA as this bug was reported. This bug existed prior to completion of related PR and Issue previously mentioned here.
- Pull branch
- Run app
- Go to IE11 on Windows and browse up app
- Click Add Row Status
- Click Add Row under "..."
- Verify hover works on tooltip hover of all rows (especially new row)
- Extra credit for checking on another OS/Browser as well

ie11-no-rowstatus-tooltip

---

src/core/_config.scss

Restore original color of readonly input text.
Fixes #1055 
1. `npm run start`
1. Visit http://localhost:4000/components/input/example-index?font=source-sans and compare the input readonly state to urls listed in the issue. It should match `v4.8.0`.

1055 - Restore the v4.8.0 readonly input color [4.12.x]

---

src/components/textarea/textarea.js
test/components/textarea/textarea-settings.func-spec.js

Add maxLength as setting option to text area component
Closes #1046
Pass maxLength as an option to `textarea()` e.g. `maxLength: 10` then max characters allowed going to become 10

1046 - Adds maxLength settings option to textarea component

---

app/src/index.scss
app/src/js/custom-route-options.js
app/src/sass/_code.scss
app/src/sass/_typography.scss
app/views/components/renderloop/example-delayed-start.html
app/views/components/renderloop/example-hook-into-counter.html
app/views/includes/head.html
src/utils/renderloop.js
test/components/renderloop/_sohoConfig.js
test/components/renderloop/renderloop-manual.func-spec.js

This PR adds a detectable setting for the RenderLoop via the optional `SohoConfig` object that allows the RenderLoop to be started manually, instead of the default automatic method.  When setting `SohoConfig.renderLoop.noAutoStart = true;`, the RenderLoop must be started manually in order to have any affect on the components in which it's utilized.
In addition, some related, demoapp-specific CSS was organized/moved around while creating examples related to this issue.
- Blocks infor-design/enterprise-ng#214
- Closes #1095
- Open …

1095 - Add `SohoConfig` setting to allow a manual start of the RenderLoop

---

app/views/components/contextualactionpanel/example-workspaces.html
src/components/contextualactionpanel/_contextualactionpanel.scss
src/components/contextualactionpanel/contextualactionpanel.js
src/components/modal/modal.js
src/components/toolbar-flex/_toolbar-flex.scss

It seems that the cancel button is working properly now.
The remaining issues:
1. Cancel Button is at highlighting state when modal pops up.
2. Alignment issue upon resizing.
_Fix (1. Cancel Button)_
In the `contextualactionpanel.js`, changing the `focus()` event to `blur()`, instead of removing the condition for selecting the first button element in the `.flex-toolbar`.
```
if (!selected.length && self.toolbar.is('.flex-toolbar')) {
selected = self.toolbar.find('button').first();
selected.blur();
return;
}
```
_Fix (2. Alignment issue)_
Alignment issue is visible in the mobile view, at max width of 500px.
Since the title is a bit longer, what I did was to not display it on the mobile …

393 - Contextual Action Panel Control

---

src/components/editor/editor.js

Unable to change the background color of words that were previously changed in Chrome. Looping thru each elements found in selection's parent and remove style with the background color.  Adding a clearing background style in any element node of selection's parent before the setTimeout will fix the issue. 
```
for (let i = 0, j = els.length; i < j; i++) {
if (els[i].hasAttribute('style')) {
els[i].style.backgroundColor = '';
}
}
```
Closes https://github.com/infor-design/enterprise/issues/392
- Run http://localhost:4000/components/editor/example-with-backcolor.html
- Highlight the word …

392 - Unable to change the background color of previously highlighted words in Chrome

---

src/components/datagrid/datagrid.js
test/components/popupmenu/popupmenu.func-spec.js

Warning, Info icons tooltip was not showing with Datagrid.
Closes #1078
http://localhost:4000/components/datagrid/test-editable-paging-validation-notoolbar.html
- Remove a value from any row in the column "Activity"
- Click on another cell to validate the cell
- The alert icon should display (no tooltip should show at this time)
- Hover on the icon should be able to see the alert message tooltip

1078 - Fixed warning info icons tooltip with Datagrid [v4.12.x]

---

app/views/components/datagrid/test-save-settings.html

Rows of a given page number doesn't appear in Datagrid with save settings after reload page.
Changing the static data to a server side data, and adding HTTP request and HTTP response.
Closes https://github.com/infor-design/enterprise/issues/798
- Run http://localhost:4000/components/datagrid/test-save-settings.html
- Set on pagination text field a page number like 2
- Refresh the page
- You should be able to see the rows in the Datagrid related to that page number.

798 - Fixes data on given page number in datagrid

---

src/components/rating/rating.js
src/utils/utils.js

IE 11 was giving an error on the rating component because IE 11 doesnt not have `Math.rating`
Closes #1130
http://localhost:4000/components/rating/list
- test all these pages on IE 11 and Chrome...

1130 - Math.sign error on rating component in ie11 [v4.12.x]

---

src/components/searchfield/_searchfield.scss

Adding `.ios` and `.mac` as parent class and target the `.searchfield` as the child and adding the id of the input field will fix the issue in mac and iOS.
Relate https://github.com/infor-design/enterprise/issues/1104
- Run http://localhost:4000/components/searchfield/example-context-search-style.html
- On Mac Chrome Click into the "Context Search" box and type in "Hello World"
- On iOS iPhone X Click into the "Context Search" box and type in "Hello World"
- The background color theme should not be different for both.

1104 - Fix bg color in mobile ios, mac

---

src/components/header/_header.scss
src/components/searchfield/_searchfield.scss

Fixing and adjusting alignments of elements in mobile perspective. Applied mobile first approach.
The alignment issue of list box exist only in iPhone device. 
Closes https://github.com/infor-design/enterprise/issues/1106
- Pull this branch.
- Run http://localhost:4000/components/searchfield/example-header-compact.html
- Test it in an actual device (iPhone, for testing the alignment of the searchfield). BrowserStack will also do. (Did the testing, debugging, trial and error using it).
- Click on on the drop down and select " Product References".
- Type " Hello World" in the searchfield …

1106 - Fix alignment of text and searchfield box

---

src/components/tree/tree.js

Events were called twice.
Closes #1003 
- Pull branch
- Run app
- Browse to http://localhost:4000/components/tree/example-sortable.html
- Ensure `dragstart` and `dragend` only fire once each when dragging an item in tree.

1003 - Rename tree dragstart and dragend

---

app/views/components/datagrid/test-paging-indeterminate-landmark.html
app/views/components/datagrid/test-paging-indeterminate-pagetwo.html
src/components/pager/pager.js
test/components/datagrid/datagrid.e2e-spec.js

Some recent changes made the paging stop work for Landmark, if a specific page other than page one is loaded initially. Fixed this and added several test pages and tests to cover the scenarios around this.
Closes #1162
These 3 cases are now covered by the added tests
http://localhost:4000/components/datagrid/test-paging-indeterminate-landmark.html
- this starts on last page
- previous should work
- try all the paging buttons 
- try each of the button on a fresh loading of the page 
http://localhost:4000/components/datagrid/test-paging-indeterminate-pagetwo.html
- This should start on page …

1162 - Added a fix for paging issues with landmark [v4.12.x]

---

src/components/searchfield/searchfield.js

Take away a 10px on calculating the searchfield width to fix the issue.
This solution also fix this example
http://localhost:4000/components/searchfield/example-go-button.html
Closes https://github.com/infor-design/enterprise/issues/1101
- Run http://localhost:4000/components/searchfield/example-categories-and-go-button.html
- Placeholder should not be cutoff.

1101 - Fix for cutoff placeholder in searchfield component

---

app/views/components/colorpicker/test-clearable.html
src/components/colorpicker/colorpicker.js

Adds an `customColors` option to colorpicker settings. When set to true, the colorpicker will not append Azure01 to the color list.
Added a demo to http://localhost:4000/components/colorpicker/test-clearable.html
This could cause issues when/if the intention is to add custom colors on top of default colors. Not sure if that is an actual use case.
closes #1135 
* pull branch
* go to http://localhost:4000/components/colorpicker/test-clearable.html
* Make sure default color Azure01 is not added to color list when `clearable = false` and `customColors = true`

1135 - Fixes colorpicker clearable=false adding Azure01

---

package.json
src/components/searchfield/searchfield.js

This PR adds a [polyfill for Promises](https://github.com/taylorhakes/promise-polyfill) so that we can use them throughout IDS source code.  It also integrates promises into the Searchfield component's `expand()/collapse()` methods for future use in getting rid of some focus traps that exist in the current working branch for #269.  The usage of Promises in the Searchfield source code uses the "ponyfill" method so that we don't conflict with any existing promise implementation.
Closes #1172 
#269 
- run `rm -rf node_modules && npm install`
- run the demoapp and use IE11 …

1172 - Added promise polyfill, integrated with expand/collapse in Searchfield

---

src/components/datepicker/datepicker.js

Error on the time when clicking today if set to 1 AM
Closes #1087 
Visit http://localhost:4000/components/datepicker/example-timeformat
Note: useCurrentTime must be set to true. Other pages will not work if useCurrentTime is set to false which is the default.
Repeat the steps on the ticket.
To Reproduce
Steps:
1. Open the date picker on the "Date-Time Picker in Locale (Time to Current)"
2. Select 1:00 AM on the time picker
3. Click "Today" button
See Issue happen, values on the time picker (1:00 AM) will be applied, not the current time.

1087 - Fix on Datepicker Issue when Clicking Today button

---

.release-it.json
package.json
scripts/after-release.sh
scripts/jenkins-deploy.sh

Previously, the jenkins script could just fail quietly when credentials weren't correct. This adds a credential check before doing anything else. It also adds a flag where you can optionally queue the build if there's an existing build running rather than cancelling that build (the default behavior).
n/a
Should work on it's own when we merge in the PR. I'll check back on how the Travis builds handle this.

Have Jenkins deploy script check auth and optionally queue

---

app/views/components/tree/test-expand-collapse-all.html
src/components/tree/tree.js
test/components/tree/tree.func-spec.js

When expands/collapse one node with tree, expand al and collapse all was no longer working.
Closes #1183
http://localhost:4000/components/tree/test-expand-collapse-all.html
- Click on any folder node to expand/collapse
- Now use top buttons (Expand All / Collapse All)
- It should show/hide tree nodes

1183 - Fixed expand and collapse all with tree

---

app/views/components/datagrid/test-editable-lookup.html
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-api.func-spec.js
test/components/datagrid/datagrid.e2e-spec.js

1. After opened lookup editor tooltips was stop displaying with datagrid. 
2. Soon lookup cell gets validation error icon, then if hover that cell only error icon was showing now  with this PR it will show both error and lookup icon in cell.
3. if lookup cell have validation error icon it should adjust the position for error icon soon hover to show lookup icon in that place.
Closes #1186
http://localhost:4000/components/datagrid/test-editable-lookup.html
- Click on any cell in column "Product Id" to go in edit mode
- Remove all text and click somewhere else or press enter …

1186 - Fixed lookup editor tooltip with datagrid

---

app/views/components/validation/example-validation-form.html
src/components/validation/validator.js

The change makes sure that if all the form rules return that the form passes the validation, eg no errors, that the result is returned. There was an issue if one of the alert rules failed, but another passed.
The expected result would be that validateForm returns the true result and the alert message is displayed on the control
Closes #1174 
1. open 'http://localhost:4000/components/validation/example-validation-form.html'
2. enter a value into all of the fields.
3. check the browser console for the validateForm result

1174 - ValidateForm may not return a resolved state

---

app/views/components/datagrid/test-group-headers-update-columns-landmark.html

Modified example page to run `updateColumns()` in source callback method with datagrid.
Closes #435 (formerly) https://jira.infor.com/browse/SOHO-6990
http://localhost:4000/components/datagrid/test-group-headers-update-columns-landmark.html
- Should be render with group-headers
- Group "Product Stuff" should be two columns "Product Id" and "Product Name"
- See pagination, should be all buttons disabled
**Additional notes**:
Modified the example page so `updateColumns()` method can run only once. In this example it is running in source callback method. Which caused to be …

435 - Modified example test page with datagrid

---

package.json

The dark theme was incorrect in its coloring.
https://github.com/infor-design/enterprise/issues/1062#issuecomment-438617201
1. `npm i && npm start`
1. Verify the `dark theme` blue is `368ac0` for the check marks in the theme switcher (dropdown)

Use ids-identity@2.0.1 for dark theme fix

---

src/components/datagrid/_datagrid.scss

The header text was not aligning when used with left/right align and filter option with datagrid.
Closes #1124
http://localhost:4000/components/datagrid/test-fixed-header-toolbar-filter.html
- See all header text should align (top to bottom) fine.

1124 - Fixed header text alignment with datagrid

---

app/views/components/datagrid/test-contextmenu-dynamic.html
src/components/popupmenu/popupmenu.js
test/components/popupmenu/popupmenu.e2e-spec.js

Fixing issue where an error is thrown in the console if a popupmenu's ul doesn't exist in the dom when right clicking on a datagrid row. This is because the default setting for popupmenu is a trigger of immediate, so the init method was trying to open and display a menu that didn't exist.
Closes #1216 
You can test this fix by navigating to the test case in the PR, right clicking on a row on the table. No menu should open up, and no error should be seen in the log.
Then on that test page, you can click the "Insert Context Menu" button, and right click on a row again. The menu should open …

1216 - Blocking context menu being opening on a datagrid if the menu doesn't exist in the dom

---

src/components/toolbar-flex/toolbar-flex.js
src/utils/utils.js

This PR fixes a bug that was found during Q/A testing on `4.13.x`, where the Flex Toolbar was not working due to the usage of `Array.from()` in key parts of its initialization.  This method is not supported in IE.
- #269 
- Fixes #285
- #1244  
- Pull this branch and run the demoapp in IE11
- Open http://localhost:4000/components/toolbar-flex/example-index (use `10.0.2.2` instead of `localhost` if on a Windows VM in Virtualbox)
- Click any of the regular toolbar buttons or the action button.  A toast should appear.
- Use the keyboard to navigate the toolbar.  Navigation should be possible. …

269 - Replace usage of `Array.from()` in Flex Toolbar for IE support [v4.13.x]

---

src/components/dropdown/dropdown.js

When scrolling in the form, while dropdown list is open, it doesn't close (in mobile).
Changing the touchPrevented to false in `scrollDocument` function will fix this. 
Closes https://github.com/infor-design/enterprise/issues/1069
- Run http://localhost:4000/components/form/example-inputs.html in mobile device or in browserstack
- After clicking the the dropdown list, scrolling should close the list and not floating.

1069 - Fix for dropdown scrolling in mobile

---

src/components/modal/modal.js

Removing all the code that closes the CAP on the `popstate` event.
Closes https://github.com/infor-design/enterprise/issues/1207
- Run http://localhost:4000/components/contextualactionpanel/example-index
- Click 'Contextual Action Panel' button
- In the browser console, type window.location.hash = "something"
- The modal should not be closed and it can be reopened by clicking the button.

1207 - Remove popstate event in modal

---

src/components/popupmenu/popupmenu.js
src/components/tooltip/tooltip.js

This PR adds a more comprehensive set of changes to the Popupmenu/Tooltip components that allow for better state checking between the two components, if they're established on the same trigger element.  This PR improves a set of changes added in PR #1245 that only half-fixed the original issue.
- Fixes #1242
- Supersedes #1245
- Open http://localhost:4000/components/toolbar-flex/example-eyebrow.html?locale=ar-SA in IE11 (use http://10.0.2.2 if running IE in a virtual machine)
- Hover the "More Actions" menu of the in-page toolbar, which is the …

1242 - Prevent Tooltips from staying open when a Popupmenu is activated [v4.13.x]

---

src/components/tooltip/tooltip.js
src/utils/utils.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/tabs/tabs.e2e-spec.js

If opening the time pickers on the date dialog it would never close after. While doing this i noticed the uniqueId function was not working for giving unique id's over a subset of items fx modal, tooltip datagrid. 
- Fixed this and adjusted test that relied on something inconsistent and out of order. 
- Fixed an additional test that was flaky.
Closes #1278
http://localhost:4000/components/datepicker/example-timeformat.html
- open the picker on the first field
- select a time from either the min or hour dropdown
- try to click out of the dialog to close (it didnt before this fix)

1278 - datepicker wont close [v4.13.x]

---

app/views/components/message/example-index.html
src/components/message/message.js
test/components/message/message-xss.func-spec.js

Creates a setting to allow customization of allowed HTML tags in a message. Default tags are `<a><b><br><br/><del><em><i><ins><mark><small><strong><sub><sup>`. Empty string results in all tags being stripped. Adds a test to ensure all tags are stripped if empty string is used.
References #379 .
Supersedes #1275 .
- Pull branch
- Run app
- http://localhost:4000/components/message/example-index
- Click Allow Tags button. Tags should format message (looks like a ransom note).
- Dismiss message.
- Click Disallow Tags button. Tags should be stripped and no formatting appear in message.

379 - Refactor message HTML tag allowance

---

app/views/components/searchfield/example-index.html
src/components/autocomplete/autocomplete.js
src/components/searchfield/searchfield.js

This PR changes Searchfield to prevent a double `selected` event from firing.  The `selected` event is already fired by the Autocomplete component (which is built into some Searchfield components), so the duplicate code firing the event in Searchfield is unnecessary.  
Along with removing this came a small refactor in the Searchfield that only fires the `allResultsCallback` if it's provided.  Previously there was an entire secondary code path that was "re-selecting" the autocomplete list item inside Searchfield.  This extraneous code has been removed.
Closes #1259
- Pull this branch and …

1259 - Prevent searchfield's`selected` event from firing twice [v4.13.x]

---

src/components/accordion/accordion.js

- Fixed issue regarding popup not able to dismiss
- http://localhost:4000/components/accordion/test-with-contextmenu.html
Closes #639
- Right click on "Personal" and the context menu pop opens with "Menu1 and Menu 2"
- Click on "Position" or anywhere else on the page
- Popup menu should now be dismissed

639 - Fix for popup not dismissing [v4.13.x]

---

app/views/components/datagrid/test-editable-validation.html
src/components/datagrid/_datagrid.scss

The .short-rowheight was applying a margin to error-icon that would make any .l-right-text not visible within the cell.
Closes #1253 
1. Go to 'http://localhost:4000/components/datagrid/test-editable-validation.html' 
2. Remove the price from the field
3. change row height to short

1253 - Error Icon not visible when Datagrid Row Height is 'Short'

---

app/views/components/autocomplete/example-case-sensitive.html
src/components/autocomplete/autocomplete.js
src/components/listfilter/listfilter.js
test/components/autocomplete/autocomplete-filtermode.func-spec.js
test/components/listfilter/listfilter-api-string.func-spec.js

This PR fixes/re-implements case sensitive filtering capability to the ListFilter and Autocomplete component.  In addition, tests and an example page for the feature have been added.
Closes #385
- Pull this branch and run the demo app
- Open a browser to http://localhost:4000/components/autocomplete/example-case-sensitive.html
- Type the word "california" with varying differences in case sensitivity.  There are several to choose from that should always match the case provided.
Additionally, run the functional tests for ListFilter and Autocomplete.

385 - Implement case-sensitive filtering in ListFilter/Autocomplete

---

src/components/popupmenu/_popupmenu.scss

Fixes the background on highlighted popupmenu items that are disabled  (is-disabled/disabled class) but keep the is-focused class after a :hover on them causing the background to be in highlighted status.
I added in the scss the background-color: transparent for those situations in which the is-focused is still on the disabled item.
Fixes https://github.com/infor-design/enterprise/issues/982
- compile scss
- check the example of popupmenu with disabled submenus and new css

Closes #982 - Fix Highlighted background on popupmenu items disabled

---

src/components/dropdown/_dropdown.scss
src/utils/environment.js

Fixed a layout issue on the checkboxes in multi select in Edge 18.
Closes #1336 
- test in Edge 17 and 18...
- open http://localhost:4000/components/multiselect/example-index.html
- open the first list
- look at the checkboxes

1336 - Add fix for multiselect checkbox layout issue in IE edge 18 [v4.13.x]

---

src/components/datepicker/datepicker.js

Datepicker with range was not display on selected range when opened again.
Closes #1337
http://localhost:4000/components/datepicker/example-range.html
- Open the "Range - No initial value" date picker
- Select some date range from different then current month
- Soon date range selected, date picker should be close out
- Reopen the date picker and see it should open with selected month view

1337 - Fixed selected dates with range datepicker [v4.13.x]

---

src/components/trackdirty/trackdirty.js

https://github.com/infor-design/enterprise/pull/1287 Caused a regression on normal input fields in regards to showing a dirty indicator on dirty fields.
Closes #1335
http://localhost:4000/components/editor/example-dirty-tracking.html
- Open test page on IE Edge
- Click on second paragraph then click on H4 on toolbar
- Dirty tracking icon should now be seen
http://localhost:4000/components/input/example-index.html
- Open test page on IE Edge
- edit the dirty tracking field and tab out

1335 - Add fix for edge regression on dirty indicator [v.4.13.x]

---

src/components/accordion/accordion.js
src/components/applicationmenu/applicationmenu.js
src/components/applicationmenu/readme.md
src/components/popupmenu/popupmenu.js
src/components/popupmenu/readme.md
src/components/trackdirty/trackdirty.js
test/components/accordion/accordion.e2e-spec.js
test/components/trackdirty/trackdirty.e2e-spec.js

The context menu + accordion support added in 4.13 caused some issues. So to fix it went with a different and better fix. To fix this i removed the audible span which was for screen readers and probably a bit too much noise so considered unneeded.
Also added a fix for the dirty indicator on edge which was pushed on the wrong branch.
Fixes #1349
Fixes #1335 (moves fix to 4.13)
Fixes #639 (again)
Need to go through the various cases on accordion that failed lately.
http://localhost:4000/components/accordion/example-index.html
- many panes can open
- toggle some panes with both the header + …

1349 - Added a better context menu / accordion fix [v4.13.x]

---

scripts/build.js
scripts/build/run-build-process.js
scripts/generate-bundle-banner.js
scripts/minify.js
test/components/datagrid/datagrid.e2e-spec.js

This PR fixes issues when attempting to run the IDS Custom Builder on Windows, mainly:
- Bad CMD syntax on windows machines when attempting to run Node child processes via the build script (Rollup and Node-Sass were being passed bad strings)
- Missing line feeds in files generated on Windows due to the usage of `\n`.
Note that these problems are recent, as of the changes in #962 
Closes #1348
On a Windows machine:
- pull this branch and run `npx grunt`.  The entire process should complete without errors.
- run `npm run build:custom -- --test-mode --dry-run`.  
- Open the `temp/` folder in …

1348 - Fix problems with builds on Windows

---

src/components/busyindicator/readme.md
src/components/button/readme.md
src/components/datagrid/readme.md
src/components/datepicker/readme.md
src/components/homepage/readme.md
src/components/listview/readme.md
src/components/menubutton/readme.md
src/components/searchfield/readme.md
src/components/swaplist/readme.md
src/components/toolbarsearchfield/readme.md

As noted on #1373 we found if there is .html in the slugs, then links do not work. Fixed this for 4.13.x then to be merged back on master
Fixes #1373 
Cant test in normal way just have to approve - then has to be deployed to staging and spot check datagrid/swap list pages in the docs by clicking github links.

1373 - Fix bad links [v4.13.x]

---

src/components/hierarchy/_hierarchy.scss

Windows 10 IE 11: Hierarchy Context Menu With Details Component: Profile text is cut off. Fixing it by adding some padding specific only in IE and IE11.
Closes https://github.com/infor-design/enterprise/issues/931
- Run http://localhost:4000/components/hierarchy/example-context-menu-with-details.html
- Click on the three dot eclipse button for Kaylee Edwards on Windows 10 IE 11 (Test it via Browserstack)
- Her profile should not cut off

931 - Added fix for hierarchy profile text cut off

---

src/components/hierarchy/_hierarchy.scss

In hierarchy component, the left edge of the leaf should be same with the image placeholder. 
Closes https://github.com/infor-design/enterprise/issues/932
- Run http://localhost:4000/components/hierarchy/example-many-children.html
- Go to Mary Butler hierarchy
- Check the one that don't have image
- The color of left edge and the image placeholder border should be the same.

932 - Added fix for image placeholder color same as the left edge

---

src/components/modal/modal.js

- Fixed issue regarding tooltip being shown on modal
- http://localhost:4000/
Closes #1053 
- On responsive view scroll down to the slider and move the slider
- Click on "Show Modal" button
- The numeric tooltip should now be hidden

1053 - Fixed issue regarding tooltip being shown on modal

---

app/views/components/datagrid/test-editable-lookup-mask.html
src/components/datagrid/datagrid.editors.js
test/components/datagrid/datagrid.e2e-spec.js
test/protractor.local.debug.conf.js

This PR enables the ability to use Masks on Lookup Editor fields in a Datagrid, the same way you'd use a mask in a normal input field.
Closes #406
- Navigate to http://localhost:4000/components/datagrid/test-editable-lookup-mask
- Select any cell in the "Product ID" column
- Attempt to key letters as the value.  See that no letters are allowed to be used.  Using numbers will work.
There's also a new e2e test for this page/case that should pass

406 - Datagrid: use Mask component with Lookup Editors

---

src/components/hierarchy/_hierarchy.scss

Hierarchy Context Menu With Details Component: Profile text is cut off. Fixing it by adding some padding specific only in Firefox.
Closes https://github.com/infor-design/enterprise/issues/931
Related PR https://github.com/infor-design/enterprise/pull/1392
- Run http://localhost:4000/components/hierarchy/example-context-menu-with-details.html
- Click on the three dot eclipse button for Kaylee Edwards on Firefox (Mac)
- Her profile should not cut off

931 - Added fix hierarchy profile text cut off in firefox

---

src/components/arrange/arrange.js
src/components/button/button.js
src/components/datagrid/datagrid.js
src/components/editor/editor.js
src/components/swaplist/swaplist.js
src/components/validation/validator.js
src/utils/behaviors.js
test/components/datagrid/datagrid.e2e-spec.js

Fixed a bug in datagrid that made tooltips show up all the time on mobile on dropdown columns.
Some minor refactoring of the isTouch indication
Fixes #1396 
Fixes #1395
For 1396
http://localhost:4000/components/datagrid/test-dropdown-window-size.html
- on IOS sim...
- open the action column 
- should now not show tooltips (disabled entirely as it was clunky here)
For 1395
- blank out a cell in the activty column so a validation error appears
- hover the first two headers (no tooltip should appear)
- resize row id column so …

1396 - Add fix for touch tooltips in datagrid and some minor refactoring [v4.14.x]

---

.stylelintrc
src/components/datagrid/_datagrid.scss
src/components/dropdown/_dropdown.scss
src/components/dropdown/dropdown.js

This PR fixes a regression where the "overflow" tooltip that displays the full contents of a Dropdown/Multiselect component whose inner text is too long to fit.  A series of several changes against `v4.14.x` caused this to stop working.
- Closes #1400 
- Related: #1214 
- Related: #1380
_For this issue:_
- Open a browser to http://localhost:4000/components/dropdown/test-multiselect-with-tooltip
- Hover the multiselect.  Ensure no tooltip is displayed (content isn't overflowed)
- Open the multiselect and pick all the items
- Close the multiselect and hover it. A tooltip should display …

1400 - Better fix for missing tooltip that doesn't modify widths [v4.14.x]

---

app/views/components/datagrid/test-dirty-indication.html
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-validation.func-spec.js

Added support for clear dirty cells for specific cell, all cells in given row, or specific cell.
Closes #1303
http://localhost:4000/components/datagrid/test-dirty-indication.html
- Make changes to any cells it should add dirty indicator to the cell
- Dirty cells can be clear by clicking the button "Clear Dirty"
– Clear Dirty > Specific Cell (row: 2, cell: 5)
– Clear Dirty > All Cells in Row (row: 2)
– Clear Dirty > All (all cells in grid)

1303 - Added support for clear dirty cells with datagrid

---

src/components/monthview/monthview.js

This is a follow up fix for setting the first day of week. 
_**Issue**_: The corresponding date doesn't move or change the same as the first day of week. It should expect to be the same date even it change the setting of `firstDayOfWeek`.
Closes https://github.com/infor-design/enterprise/issues/1179
Related PR https://github.com/infor-design/enterprise/pull/1326
- Run http://localhost:4000/components/datepicker/test-set-first-day-of-week.html
- Click the calendar icon
- The calendar should start on Monday
- In test html, you can manipulate the `firstDayofWeek`
- It …

1179 - Fixes calendar date move as the first day of week [4.14.x]

---

src/components/modal/modal.js

If dropdown use with validation in modal window. It was not let is pass validation and causing the not to submit form.
#1213
http://localhost:4000/components/modal/example-validation.html
- Click button "Add Context" to open modal window
- In modal window see button "Submit" should be disabled
- Fill "Email and Description" fields
- Leave the "Type" dropdown list blank
- Click button "Cancel"
- Open the Modal again
- See button "Submit" should be disabled
- Soon fill/remove all required fields with (*) in label text
- See the button "Submit" it should be enabled/disabled

1213 - Fixed dropdown validation after cancel in modals [v4.14.x]

---

app/views/components/tree/example-ajax.html
src/components/tree/tree.js

Previously selected nodes were being selected again after child nodes are loaded via AJAX.
Closes #1270
http://localhost:4000/components/tree/example-ajax.html
- Click "Node One" to select
- Click "Node Two" to load its child nodes
- See "Node One" should deselect and only "Node Two" be selected
- See console log for `selected` should fire one per click

1270 - Fixed selected nodes and ajax loading with tree

---

src/components/modal/modal.js

If invalid email use with validation in modal window and canceled to close modal. Then reopen model was let user to submit the form because submit button was enabled.
#1213
http://localhost:4000/components/modal/example-validation.html
- Click button "Add Context" to open modal window
- In modal window see button "Submit" should be disabled
- Fill all the fields, but keep INVALID email e.g 'test123!@yahoo.com'
- Button "Submit" should be disabled
- Click button "Cancel"
- Open the Modal again
- See button "Submit" should be disabled
- Soon fill/remove all required fields …

1213 - Fixed invalid email validation after cancel in modals [v4.14.x]

---

src/components/bar/bar.js
test/components/about/about.e2e-spec.js
test/components/calendar/calendar.e2e-spec.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/datepicker/datepicker.e2e-spec.js
test/components/lookup/lookup.e2e-spec.js
test/components/tabs/tabs-api.func-spec.js

Fix a few tests that broke on chrome driver 45 and 2018 year change.
Fix an IE error where Object.values is used.
NA
- let tests run
- run http://localhost:4000/ and check all charts load at the bottom 
- test page http://localhost:4000/components/bar/example-long-text.html

Fix tests for 2018 & Add IE 11 fix for Object.values [v4.14.x]

---

app/views/components/datagrid/test-tree-update-row.html
src/components/datagrid/datagrid.formatters.js
src/components/datagrid/datagrid.js

if a row contains sub-rows, updateRow() was causing to row extra one indent space.
If a row was the last row of sub-rows, updateRow() causing to row one less indent pace.
Closes #405
Closes #1361 - fixed id issue
http://localhost:4000/components/datagrid/test-tree-update-row.html
- See the rows indentation in grid tree should be fine
- Select value from top dropdown and
- Click button "Update Row" it will update row data for given row
- See the rows indentation in grid tree should not change

405 - Fixed update row was misaligning indentation with treegrid

---

app/views/components/datagrid/test-tree-editable.html
src/components/datagrid/datagrid.js

Using editable and treegrid, extra text (Expand / Collapse) was adding to the target node after edit parent node cell.
Closes #1145
http://localhost:4000/components/datagrid/test-tree-editable.html
- Click on any parent node's cell text with (+/-) icon to get in edit mode
- Click anywhere else on the page or "Enter" key to get out from edit mode without make any changes
- See in that cell's content should not added any extra text (Expand / Collapse)

1145 - Fixed extra text expand-collapse with tree datagrid

---

app/views/components/datagrid/example-empty-message-after-load.html
src/components/datagrid/datagrid.js

fix for empty message not displaying after setEmptyMessage call after initially being null
The empty message will now display after being set through setEmptyMessage after originally being null.
See issue #1467 
1. To test just run the http://localhost:4000/components/datagrid/example-empty-message-after-load.html
1. click the "show empty message" button.
- empty message should display

1467 - fix for empty message not displaying

---

app/views/components/datagrid/test-link-hrefs.html
src/components/datagrid/datagrid.js

Probably had this question 10 times now. After adding this code in 4.6 links no longer redirect unless you use the click function. Correcting this.
Closes #1473 
http://localhost:4000/components/datagrid/test-link-hrefs.html
- click any links in the datagrid
- they will now redirect the url
NOTE: I dont have real URLS so the urls will fail but the page will redirect is the point.

1473 - Allow hrefs to redirect 

---

app/views/components/datagrid/test-tree-filter-child-on-match.html
src/components/datagrid/datagrid.formatters.js
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-settings.func-spec.js
test/components/datagrid/datagrid-tree.func-spec.js

Make filtered child rows a setting `allowChildExpandOnMatch` to display the children nodes with tree datagrid.
Closes #1422
http://localhost:4000/components/datagrid/test-tree-filter-child-on-match.html
- Use switch "allowChildExpandOnMatch" to toggle the settings
- Apply "Contains" filter on "Task" column with the word "HMM"
- if "allowChildExpandOnMatch" is "true"
- there should be 21 rows, 18-visible, 3-hidden(2,3,4 -in column "id")
- and in first row "+" button should be enabled
- if "allowChildExpandOnMatch" is "false"
- there should be 6 rows, all 6-should be …

1422 - Added support to allowChildExpandOnMatch with datagrid

---

app/views/components/datagrid/test-filter-lookup-click-function.html
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js

Adding support for returning the datagrid object for a lookup filter using a custom click function.
"Closes #1486"
1. Pull in change and navigate to /components/datagrid/test-filter-lookup-click-function
2. Click the trigger icon for the lookup in the filter row for Product Id
3. An alert should popup with the message "Grid information found"
Can also run the e2e tests, since I automated the above test.

Adding returning the grid object when the lookup filter is using a custom click function

---

src/components/dropdown/dropdown.js

When no-search setting is in `true`, it is unable to type ahead to select values when `Capslock` key is enabled.
Closes https://github.com/infor-design/enterprise/issues/1301
Related PR #363 
- Run http://localhost:4000/components/dropdown/example-no-search.html
- `Caps lock` key should enabled
- Type `S`
- Expected to see value starts with letter 'S' in the dropdown
**AdditIonal Expected Behavior**
- Run http://localhost:4000/components/dropdown/example-index
- Caps lock should also work on this test page.

1301 - Added fix for caps lock not working in no-search settings

---

src/components/editor/editor.js

Replaces bullets pasted in from a Word doc with list items in Editor. Also cleaned up some comment typos.
Closes #1351.
- http://localhost:4000/components/editor/example-index.html
- Pull branch
- Run app
- Paste in a bulleted list from Word
- [Test Doc.docx](https://github.com/infor-design/enterprise/files/2741551/Test.Doc.docx)
- Ensure bullets are converted to list items and appear correctly
Another solution to this would be to strip bullets upon pasting into editor and let user highlight their list and click the 'unordered list' button in the toolbar of the editor. Would create a …

1351 - Fix Editor pasted bulleted list

---

test/components/accordion/accordion.e2e-spec.js
test/components/datagrid/datagrid.e2e-spec.js

Saw a couple tests fail on master and browser stack. Hoping this solves it.
1. Needed possibly a longer sleep while it animates / opens/closes
1. Only waits for the datagrid not the rows to render

Improve 2 Nightly Tests 

---

src/components/hierarchy/_hierarchy.scss

- Updated margin-left of image-placeholder to 0px
- http://localhost:4000/components/hierarchy/example-context-menu-with-details.html?locale=ar-SA
Closes #1310 
- On load, top leaf should now be closer to the image on the upper right

1310 - Updated margin-left of image-placeholder to 0px

---

src/utils/lifecycle.js

Busy indicator tends to close right after it's started because the `close()` method is called after clicking on menu accordions.
Closes https://github.com/infor-design/enterprise-ng/issues/281
- Run the enterprise on your local machine to generate the build js
- Get the zip file attached here https://github.com/infor-design/enterprise-ng/issues/281
- Download and run `npm prune && npm install`
- Run `npm run build` then after, `ng s`
- Copy the build js file of enterprise from `dist/js/sohoxi.js`
- Then paste it to `node_modules/ids-enterprise/js/sohoxi.js`
- Open …

381 - Added fix for busy indicator closed after each click on menu

---

src/components/searchfield/searchfield.js

- Fixed issue regarding ellipsis not being shown on responsive mode
- http://localhost:4000/components/field-filter/example-index.html
Closes #1068 
- Make the page responsive
- Click on the Lookup icon
- The product lookup list window pops up
- The ellipsis should now be visible

1068 - Fixed issue regarding ellipsis not being shown

---

src/components/tabs-module/_tabs-module.scss

The tab content is a bit unreadable in mobile view. Adjusted some elements. Seems that when you resize it on browser there's no issue, but in actual device specifically in Android, there are some discrepancies on two different sections
Closes https://github.com/infor-design/enterprise/issues/971
- Open http://localhost:4000/components/tabs-multi/example-index
- Test it in browser then resize it to `320px` or test it actual device
- Tab should be more readable then previously

971 - Added fix for tab content being cutoff in mobile

---

app/views/components/calendar/test-specific-month.html
test/components/calendar/calendar.e2e-spec.js

Because the event data had some events in the next 14 days the upcoming event section is now being rendered and the visual tests is failing. This fixes that issue by "not" rendering that section for the visual test.
Please merge this first!

NA - Fix visual calendar test

---

src/components/editor/editor.js

Clear formatting was not working with `blockquote` and editor.
Closes #1002
http://localhost:4000/components/editor/test-clear-formatting.html
- Select some text
- Click on `Background-color` and choose any color
- Click on `Block quote`
- Now click `Clear Formatting`
- It should clear the formatting

1002 - Fixed clear formatting with editor

---

app/views/components/searchfield/test-long-options.html
src/components/popupmenu/_popupmenu.scss

- Updated separator css to prevent separator from being out of place
- http://localhost:4000/components/searchfield/test-long-options.html
Closes #1500 
- Click on searchfield and type in "item" and a dropdown with long item names should popup
- Scroll the dropdown to the right to see the long item names
- The separator should now be in place and not being scrolled

1500 - Updated separator css to prevent separator from being out of place

---

app/views/components/tree/example-context-menu.html
src/components/datagrid/datagrid.js
src/components/popupmenu/popupmenu.js
test/components/popupmenu/popupmenu.e2e-spec.js

Noticed since 4.14 popupmenus that use immediate only worked once. This fixes that.
Had to unwind 3 other issues to address. Made removeOnDestroy as a new optional setting in case thats needed.
Closes #1507 
Relates to https://github.com/infor-design/enterprise/pull/1483
Relates to https://github.com/infor-design/enterprise/pull/1217
http://localhost:4000/components/datagrid/test-contextmenu-dynamic.html
- should be able to right click several times
http://localhost:4000/components/datagrid/test-contextmenu-dynamic.html
- right click in grid - nothing happens
- hit button to insert the …

1507 - Fixed an issue where immediate popups would not reopen

---

app/views/components/popupmenu/test-multiple-context-menu-destroy.html

There was an ES6 syntax error in the test page that was causing this to break in IE11
related to #1025 
* pull branch
* test popupmenus in IE11 http://localhost:4000/components/popupmenu/test-multiple-context-menu-destroy.html

1025 - Fix IE11 bug

---

src/components/datagrid/_datagrid.scss
src/core/_config.scss
src/themes/dark-theme.scss
src/themes/high-contrast-theme.scss

When editing cells in High Contrast theme, the background color was not filling to whole cell.
Closes #1421
- Change the theme to High Contrast
- Type "test edit" in the Activity column of the first row
- See the background color should fill to whole cell

1421 - Fixed background color for editing cells with datagrid

---

app/views/includes/applicationmenu-menubutton.html
src/components/applicationmenu/_applicationmenu.scss

Having a long name will overlap the icon image. Adjust some css properties to fix it.
Closes https://github.com/infor-design/enterprise/issues/1454
- Run http://localhost:4000/components/applicationmenu/example-menubutton
- Click hamburger menu.
- I change the text to a long name.
- You can also add it to validate via inspecting the element in the browser.
- There should be no alignment/layout issue.

1454 - Added fix for accordion text wrapping incorrectly

---

src/components/hierarchy/_hierarchy.scss
src/components/hierarchy/hierarchy.js

Fix for back button wrapping in mobile views on hierarchy chart.
https://github.com/infor-design/enterprise/issues/1528
1. Get new code from PR
2. http://localhost:4000/components/hierarchy/example-paging
3. Reduce screen to phone size via chrome emulator. Or use mobile device
4. Expand a leaf to display back button.
5. Back should not wrap

Fix for #1528, Hierarchy, Back button wraps in mobile views.

---

app/views/components/datagrid/example-filter.html
src/components/datagrid/datagrid.js

Passing in the editorOptions for a datepicker when the filter type is changed.
"Closes #1532 "
To test:
1. Pull in the change
2. Navgiate to http://localhost:4000/components/datagrid/example-filter.html
3. Open the datepicker for Order Date, without changing the filter type.
4. The month and year should be dropdowns.
5. Close the datepicker and change it's filter type to 'in range'. Then reopen the datepicker
6 . The month and year should be dropdowns.

1532 - Ensure that the passed in editorOptions are used when the datepicker gets recreated with a change in filter type

---

app/src/js/middleware/csp-handler.js
package.json
test/components/dropdown/dropdown-updates-events.func-spec.js

We found that CSP is not support for nonce values on Safari <=9 (iphone 6s or lower).
This fixes this by allowing the unsafe-inline for just those cases.
#971 
- pull branch
- restart server
- open any page at all like http://localhost:4000/components/datagrid/example-index.html
- do that on Iphone 6s and then on any newer browser plus chrome desktop

971 - Added solution so pages can run on safari <=9 [v4.15.x]

---

app/views/components/datepicker/example-month-year-format.html
app/views/components/datepicker/example-month-year-picker.html
docs/CHANGELOG.50.md
src/components/datepicker/datepicker.js
src/components/monthview/monthview.js
test/components/datepicker/datepicker-api.func-spec.js
test/components/datepicker/datepicker-settings.func-spec.js

The datepicker advanceMonths setting was wrongly named as it worked on years. Made a new setting so you can choose how far back and forward you want to go.
Established CHANGELOG.50.md for notes on breaking changes (we will merge this when minor release is done back to CHANGELOG).
Closes #970 
http://localhost:4000/components/datepicker/example-month-year-picker.html
- open picker
- open year picker (this example shows one year back and 8 ahead now)

970 - Renamed advance months setting for [v5.0.x]

---

app/src/js/routes/directory-list.js

This PR fixes an issue in the demoapp that was causing bad hyperlinks to be created when running on a Windows system.  The problem was due to some incorrect detection of unix path separators in Windows.
Closes #1549 
- Pull this branch and run the demoapp on a Windows VM
- Navigate to http://localhost:4000/components/dropdown
- Click any example link in the list.  All of these links should be relative URL paths, and should all be working correctly.
Paging @fitzorama

1549 - Better support for Windows paths

---

src/components/datagrid/datagrid.js
test/components/area/area-api.func-spec.js
test/components/blockgrid/blockgrid-api.func-spec.js
test/components/bubble/bubble-api.func-spec.js
test/components/datagrid/datagrid.e2e-spec.js

Selected rows was not working as expected after second page with server side paging and datagrid.
Closes #1545
http://localhost:4000/components/datagrid/example-paging.html
- Go to 2nd page
- Click on checkbox in header row to Select All (10 rows)
- Deselect some of them
- See the number of selected items should change
- The "Select All" icon should change from tick to "-“ icon

1545 - Fixed server side selected rows with datagrid [v4.15.x]

---

app/views/components/hierarchy/example-lazy-load.html
app/views/components/hierarchy/example-single.html
app/views/components/hierarchy/test-infor-org.html
src/components/hierarchy/_hierarchy.scss
src/components/hierarchy/hierarchy.js

Fixed hierarchy issues in IE and IOS. These were not totally last regressions as initially thought.
#1564 - Was regressed in 4.11
#1565 - Seemed to never work
(If that matters)
Closes #1564 
Closes #1565 
#1565 
Was an issue because the getJSON command cached the ajax request so the ID's were the same in subsequent ajax calls. This caused the rows to not load since the ID's where not unique since the request is cached.
- launch IE 11 (browserstack or VM)
- open http://localhost:4000/components/hierarchy/example-single.html 
- open Richard Fairbanks
- open Kaylee Edwards -> should now open …

1564 - Hierarchy Browser Issues [v4.15.x]

---

src/components/dropdown/_dropdown.scss
src/components/validation/validator.js
test/components/applicationmenu/applicationmenu.e2e-spec.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/datepicker/datepicker.e2e-spec.js
test/components/dropdown/dropdown-updates-events.func-spec.js
test/components/validation/validation.e2e-spec.js

Fixes #1556 
- the added e2e test covers this but
- go to http://localhost:4000/components/validation/example-multiple-errors.html
- in the console type `$('select.dropdown').removeError().addError({ message: 'Dropdown error.', inline: false });` and an error should show
- in the console type `$('select.dropdown').removeError();` and an error should go away
Extra Credit: Edit the page so the dropdown has `field-short` instead of `field` and rerun the steps. I noticed the alignment was off so fixed that too.

1556 - Added a fix from remove error on inline errors

---

app/views/components/busyindicator/test-inside-modal.html
src/components/busyindicator/busyindicator.js
src/components/modal/_modal.scss

Busy indicator pushed far down out of view, when it was using inside the modal.
Closes #827
http://localhost:4000/components/busyindicator/test-inside-modal.html
- Click on button "Show Modal" to bring up the modal dialog
- Click on button "Show Busy Indicator" to activate the busy indicator
- See the Busy Indicator should show fine

827 - Fixed busy indicator was showing offset inside modal

---

.travis.yml

Travis is running the deploy unnecessarily on PR and custom branches.
n/a
1. Examine the tests/results from this branch/PR.
1. See that neither check has the "deploy" stage included
1. Make sure that commits to `master` still "deploy"

Travis CI: Use logic to exclude deploy stage for specific conditions

---

package.json
scripts/deploy-documentation.js

The `documentJsToHtml()` in the `deploy-documentation.js` script wasn't returning a promise to parse the documentation comments in the proper order of events leading to missing `api` data.
Note this doesn't require a v4.15.x patch, but I wanted it to be in the branch in case we ever have to redeploy the documentation for it.
#1377 
1. Checkout branch `4.15.x`
1. Run `npm run documentation -- --test-mode --dry-run --site=prod`
1. You should see `docs/ids-website/dist/docs/button.json` file now has a populated `"api"` property.

1377 - Fixed deploy docs script async fn timing [v4.15.x]

---

app/views/components/field-filter/example-filtertype.html
docs/CHANGELOG.md
src/components/field-filter/field-filter.js
test/components/field-filter/field-filter-api.func-spec.js
test/components/field-filter/field-filter.e2e-spec.js

Added support to getFilterType() and setFilterType() api methods with FieldFilter control.
Closes #1181
http://localhost:4000/components/field-filter/example-filtertype.html
- Open developer tools and watch for logs
- Click on buttons "Set(by Index), Set(by Value)" to change filter type
- Click on button "Get" to get current filter type

1181 - Added support to get and set filter type with fieldfilter

---

app/views/components/line/example-index.html
docs/CHANGELOG.md

Missing the legend 'Component C' on Mobile view.
Added abbreviation and short name and display it depends on the width (481px to 768px viewport = abbreviation, then 480 and below = short name).
Closes https://github.com/infor-design/enterprise/issues/609
- Run http://localhost:4000/components/line/example-index
- Test it on mobile viewport and tablet viewport, or just resize the browser down to 320px
- Comp A, Comp B, Comp C should display on 481px to 768px viewport
- A, B, C legend should display on mobile viewport (480px and below)

609 - Added fix for line chart responsive issue on Mobile

---

test/protractor.ci.debug.conf.js

When doing e2e testing and resetting the baseline images, the cli returns: `Failed: Image not found, saving current image as new baseline.` but it never creates the baseline.
n/a
none

N/A - E2E change autosave option to true for debug configs

---

docs/CHANGELOG.md
src/patterns/stepprocess/stepprocess.js

Stepprocess expanding or collapsing a folder show the step as being selected, this leaves a disconnect with the end user on what step is selected and what is showing in the step panel frame.
https://github.com/infor-design/enterprise/issues/1633
Include:
* Go to http://localhost:4000/patterns/stepprocess-markup.html#profile
* Expand/collapse folder

Step Process Control folder should not be selectable #1633

---

app/views/components/editor/example-preview.html
docs/CHANGELOG.md
src/components/editor/_editor.scss
src/components/editor/editor.js
test/components/editor/editor-api.func-spec.js
test/components/editor/editor.e2e-spec.js

Added new state called “preview” a non editable mode to editor. Where it only shows the HTML with no toolbar, borders etc.
Closes #1413
http://localhost:4000/components/editor/example-preview.html
- See the editor it should be not editable
- Click top button "Change to Editable Mode"
- Apply any changes to editor content (text color, bold, block quote etc.)
- Click top button "Change to Preview Mode"

1413 - Added support to preview mode with editor

---

app/views/components/hierarchy/example-minimal.html
app/views/components/hierarchy/example-stacked.html
app/views/examples/landmark/example-orgchart.html
src/components/hierarchy/hierarchy.js
test/components/hierarchy/hierarchy-stacked-api.func-spec.js

There are inconsistencies between the new stacked layout vs the current existing layouts. The stacked layout examples were passing in data as an object vs an array. Allowing an object causes issues with the Angular wrapper which expects the data set to be an array. To resolve this I am updating the control to make sure only an array is passed in as data.
https://github.com/infor-design/enterprise/issues/1629
Navigate through existing examples. http://localhost:4000/components/hierarchy/example-stacked.html Everything should still work as expected. All tests should pass.

1629 - Updating hierarchy control to make sure dataset is an array and not an object

---

app/views/patterns/stepprocess-markup.html
src/patterns/stepprocess/_stepprocess.scss

Step process exhibited a few UI regressions. And adjusted some strangely layed out text.
Closes #1662 
http://localhost:4000/patterns/stepprocess-markup.html#profile
- resize to tablet size
- tab into the second level ... button
- ensure focus is visible
http://localhost:4000/patterns/stepprocess-markup.html#profile
- back on desktop size
- look at the chevrons on the step menu - they should no longer be huge

1662 - UI Fixes to Step Process [v4.16.x]

---

app/views/components/pager/example-standalone.html
docs/CHANGELOG.md
src/components/pager/pager.js
test/components/pager/pager-api.func-spec.js
test/components/pager/pager-events.func-spec.js

This PR:
- Adds the tooltip customization fields from @pwpatton's example on #1466 (I changed the fields to work off of a `change` event to make it more automatic, matchin our other gauntlet tests)
- Adds tests to the Pager functional test suite for setting custom tooltips through invoking, and updating existing tooltips.
- Fixed propagation of the `pagesizes` setting when using `PagerAPI.updated()` (was previously merging the array values, instead of replacing the array outright).
- Improved the pager test suite in general (using the `cleanup` method, changed lifecycle, etc)
Please note that the original issue described in #1466 was actually fixed in the Listview/Pager refactoring done in …

1466 - Add Custom Tooltip tests, improved some pager tests

---

app/views/components/datagrid/example-custom-filter-conditions.html
app/views/components/datagrid/test-filter-lookup-click-function.html
app/views/components/datagrid/test-filter-mask.html
app/views/components/datagrid/test-filter-with-tooltip.html
test/components/datagrid/datagrid.e2e-spec.js

While not really a bug the behavior was confusing and flagged by QA so added a quick fix and made a test for the actual feature of having a mask on the filter row input fields.
Closes #1672
- new test should run fine
- http://localhost:4000/components/datagrid/test-filter-mask - qty and product name are constrained by a mask
- http://localhost:4000/components/datagrid/example-filter  product name allows spaces (now has no mask)

1672 - Added test and example for filter mask [v4.16.x]

---

docs/CHANGELOG.md
src/components/popupmenu/popupmenu.js
test/components/dropdown/dropdown.e2e-spec.js

Fix for QA issue where dropdowns do not reopen when closing by clicking a popupmenu button. Sorted Change log and added a test for this case.
Closes #1670 
http://localhost:4000/components/dropdown/example-index.html
- open dropdown
- click actions ... button -> dropdown closes
- click dropdown to open again -> will now reopen.

1670 - Added a fix for menubuttons not reopening dropdowns [v4.16.x]

---

src/components/pager/pager.js

When sorting the pager is recreated leaving a div in the page that adds extra space.
Closes #1685
http://localhost:4000/components/datagrid/example-fixed-header.html
- sort several times
- page should not increase in size anymore

1685 - Added fix for extra space [v4.16.x]

---

docs/CHANGELOG.md
src/components/toolbar-flex/toolbar-flex.item.js
test/components/toolbar-flex/toolbar-flex-api.func-spec.js

Fixing the issue of the events not being handled for menu buttons in toolbar-flex.item.js. This reconnects the selected events again.
"Closes #1709"
1. Go to '/components/toolbar-flex/example-more-actions-ajax'
2. Click on Menu Button, and then select Menu Button Option 1
3. The toast message appears with "Select Menu Item: Menu Button Option 1"
4. Shrink the window so the Menu Button is overflowed into the More Menu.
5. Open the more menu, hover over the Menu Button, and in the submenu select Menu Button Option 1
6. The toast message appears with "Select Menu Item: Menu Button Option 1"

1709 - Toolbar Flex: fixing menu button selected event

---

docs/CHANGELOG.md
src/components/calendar/calendar.js

No modal should be defined as there is no template for the controls to allow the user to add the event.
This should either only show when a template exists, or have a way to disable to modal, eg a read-only calendar.
Closes #1684 
1. Go to '/components/calendar/test-ajax-events.html'
2. Double Click on a date

1684 - Calendar: Disable the new event modal when no template is defined

---

src/components/editor/editor.js

We tried to run editor tests in 5.1.0 of NG and it errors out without this change. This issue found itself on this branch https://github.com/infor-design/enterprise-ng/pull/381
- Pull that branch and run `npm run test`
- Build this branch and copy into the node_modules/ids-enterprise folder and replace (or use npm link pattern)
- rerun `npm run test` on the ng branch
- make sure editor works on the ng branch with this change
- make sure http://localhost:4000/components/editor/example-preview.html works on EP still 
https://github.com/infor-design/enterprise-ng/pull/381

NA- Added a safety check [v4.16.x]

---

app/views/components/datagrid/test-filter-editable.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Datagrid was not filtering properly on a `null` value in Order Date.
Closes #1718.
- Pull branch
- Run app
- Goto: http://localhost:4000/components/datagrid/example-filter.html
- Filter on Order Date with `is-not-empty` filter (will show 7 results with id: 1, 2, 3, 4, 5, 5, 6)
- Should NOT show two results: one `''` and one `null`.

1718 - Datagrid is-not-empty filter on null

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js

The stretch column does not work correctly and within the Edge browser a space can be seen.
Closes #1716 
Go to 'http://localhost:4000/components/datagrid/test-columns-stretch-column.html'
The grid column's should fill the grid

1716 - Datagrid: stretch column not working in Edge browser

---

app/views/components/datagrid/test-before-row-activated.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/locale/locale.func-spec.js

Added support to cancel `rowactivated` event with datagrid. Now datagrid will trigger the new event `beforerowactivated` which will wait/sync to cancel or proceed to do `rowactivated` event.
Closes #1021
http://localhost:4000/components/datagrid/test-before-row-activated.html
- Click on any row to make it activated
- See `beforerowactivated` is triggered
- Then `rowactivated` is triggered

1021 - Added support to cancel rowactivated with datagrid

---

src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js
src/utils/utils.js

Fixes a followup issue on #1686 where an extra scrollbar occurred. Also added a util that can be used if the scrollbar size is needed elsewhere.
Fixes  #1686
- Try for each of the three options in  Mac -> System Preferences -> General -> Show Scrollbars 
- Load http://localhost:4000/components/datagrid/example-frozen-columns page in Mac- Safari, Chrome and FF, reloading the page each time changing the setting.
Should now not see the extra scroll bar on the right column and the scrollbars should appear in order.

1686 - Added a fix for extra scroll bars [v4.16.x]

---

src/components/listview/listview.js
test/components/listview/listview-events.func-spec.js

Recent list view changes will now cancel out listview rendering when calling `updated()` with no new settings. The problem with this is in angular thats how it works as the settings are outside in the wrapper. I adjusted the updated function so it has the same logic but still renders with no settings.
Please review and give your opinion @EdwardCoyle in case im missing a reason behind this.
@pwpatton Please verify on your end.
Closes #1738 
- Added a test for this that shows that render is happening because the event `rendered` is called in both cases when calling the `updated` both with …

1738 - Allow updated to refresh with no settings [v4.16.x]

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/editor/editor.js

After some changes the `filtered` event no longer fires on disableClientSideFilter. The result of this is that you cant get notification to trigger your backend anymore when disableClientSideFilter: true.
CC @Mincol
Fixes #1689 
http://localhost:4000/components/datagrid/test-disable-client-filter-and-sort.html
- sort on any column -> only the visual indicator should stay, nothing happens because its disabled otherwise , the end user would then do this server side
- type 22 in any filter column -> only the filter condition should stay -> nothing happens because its disabled otherwise , the …

1689 - Ensure filtered event is called on disableClientSideFilter

---

app/views/components/listview/example-custom.html

Added a sample that mimics the way list view is used in enterprise-ng
#1747
- http://localhost:4000/components/listview/example-custom.html
- click on mulitple selection button
- click on show dataset 2
verify checkboxes are still displayed.

new sample that initializes and updates the listview from html

---

app/views/components/datagrid/test-icon-buttons.html
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-columns.func-spec.js

The frozen columns code had the effect of making click events not fire on columns when either:
- there is a hidden column
- there is more than one click function per column set
Fixes #1749 
- make sure the new test works
- go to http://localhost:4000/components/datagrid/test-icon-buttons.html
- click each of the two buttons and watch the console. There should be data for both of these columns

1749 - Fix non firing click event [v4.16.x]

---

test/components/datagrid/datagrid-validation.func-spec.js

Added functional test to confirm this not an issue anymore. It solved with another PR https://github.com/infor-design/enterprise/pull/1173
Closes #1019
- Pull and built this branch
- Run functional tests `npm run functional:ci`

1019 - Added test for dirty and error row-status with datagrid

---

app/views/patterns/stepprocess.html
docs/CHANGELOG.md
src/components/radios/_radios.scss

This PR removes some z-index values that were previously applied to Radio Buttons.  This change was causing some visual bugs where radio buttons would often appear "in front" of elements that they should sit "behind", in terms of z-order.  This was especially present on the Stepprocess pattern, but was also causing a rendering problem on Accordion components.
This PR also adds some radio buttons to the step process example for testing purposes.
Closes #1014 
Closes #1568 
Firstly, pull this branch and run the demoapp.
_To test the Stepprocess (#1014):_
- Go to …

1014/1568 - Removed z-index changes on radios

---

app/views/components/datagrid/example-editable.html
app/views/components/datagrid/test-editable-colorpicker.html
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.editors.js
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/tree/tree.e2e-spec.js

Fixed two regressions for 4.16 as noted on the test steps.
Fixes #1771
Fixes #1772
Testing #1771 
- press add row status
- press  go back one page and then back to the first page -> status should stay around
- reload
- press add row status
- press add under the .. menu -> status should sty around but the new indicator is not shown as there is a setting around it
Testing #1772 
- select an item in the last columns dropdown list moving down from top to bottom
- …

1772 - Fixed two regression datagrid bugs [v4.16.x]

---

app/views/components/dropdown/example-readonly.html
docs/CHANGELOG.md
src/components/dropdown/_dropdown.scss
src/components/dropdown/dropdown.js
test/components/dropdown/dropdown.e2e-spec.js

Added support to make dropdown readonly fields optionally not tab-able.
Closes #1591
http://localhost:4000/components/dropdown/example-readonly.html
- Tab thru each field on the page
- Field "Readonly Dropdown (No Tab Stop)"
- Should not be tab able

1591 - Added support for not tab-able to readonly dropdown

---

app/views/components/datagrid/test-horizontal-scroll.html
src/components/datagrid/_datagrid.scss

Solves issue #1618. `.datagrid-body` height calculation was not being properly adjusted for medium and short row heights when filter rows and/or column groups were present. This fix adjusts _datagrid.scss and adds test-horizontal-scroll.html.
Closes #1618 
- Open http://localhost:4000/components/datagrid/test-horizontal-scroll.
- Change the row heights.
- Witness the horizontal scroll bar remain in place for each example
- make sure the bottom row isnt cut off.

Fix horizontal scroll bar display with medium rows

---

app/src/sass/layouts/_embedded.scss

In the embedded demos on design.infor.com, there's often little to no margin between the theme switching tab bar and the component content.
n/a
**Before:**
**After:**

Fix padding issue for embedded layouts in website [v4.16.x]

---

app/src/js/middleware/option-handler.js
app/views/includes/head.html
docs/CHANGELOG.md

This PR removes the ability to change the font in the demoapp view query parameters (fx: http://localhost:4000?font=source-sans).  This was necessary for some initial testing on new IDS themes, but is no longer necessary since the decision was made that multiple fonts on a theme will not be supported.
Closes #1747 
- Run the demoapp in verbose mode with `node --inspect-brk ./app/server.js --verbose`
- Open any page with the font query param (fx: http://localhost:4000?font=source-sans)
- Ensure that there are no messages about fonts changing present in the Node.js …

1747 - Demoapp: remove `font` query parameter

---

app/src/js/middleware/option-handler.js
app/src/js/routes/custom-icons.js
scripts/build.js
scripts/configs/cssmin.js
scripts/configs/sass.js
src/components/personalize/personalize.js
src/themes/uplift-theme.scss

Seeing that we've got the fundamentals of color, typography, and iconography working in the components, I feel we can now mark it as `beta`.
- Updates references to `uplift-alpha` theme to be just `uplift`
- Renames theme file
- Updates banner to be `beta`
Depends on merging #1795
- `npm start` and got to http://localhost:4000/?theme=uplift
- You should see the uplift theme and an updated banner in the bottom

Mark uplift theme as beta

---

app/data/hc-john-randolph-multi-root.json
app/data/hc-multi-root.json
app/views/components/hierarchy/test-multi-root.html
src/components/hierarchy/_hierarchy-stacked.scss
src/components/hierarchy/hierarchy.js

**Is your feature request related to a problem? Please describe.**
Cherry picked changes from https://github.com/infor-design/enterprise/issues/1677 for this PR.
Need a way to render multiple roots. For example.
```
{
"ancestorPath": null,
"centeredNode": null
"children":  [{..childrenUrl}, {..childrenUrl}, {...childrenUrl}]
}
```
**Describe the solution you'd like**
Cards will display as one level if there are multiple roots on the initial data load (see attached screenshot).
**Additional context**

1677- Hierarchy stacked layout needs ability to support multi root data structure [4.16.x]

---

app/views/components/hierarchy/example-index.html
app/views/components/lookup/test-single-select-serverside.html
app/views/components/popupmenu/test-multiple.html
app/views/components/tree/test-preserve-restore.html

Some examples wont load on IE , in particular the Hierarchy one as noted. Removed the arrow functions so this will work. This probably doesnt need a new build as it was just an example page but thats debatable.
Closes #1815
http://localhost:4000/components/hierarchy/example-index.html
- load page in IE 11

1815 - Remove some arrow syntax functions so examples work on IE11 [v4.16.x]

---

app/views/components/datagrid/example-modal-datagrid.html
docs/CHANGELOG.md
src/components/modal/modal.js

Modal overflows the width of the page at larger breakpoints.
There was no option for manipulating the max-width of the modal.
Reverted the `calcWidth` multiplier back to 1 from 1.05 which was added here and created the bug: #393. I retested #393 and it looks fine.
Added an option to dictate max-width of the modal. Defaults to `null`.
Closes #1802.
Related to #393.
- Pull branch
- Run app
- Browse to new page: http://localhost:4000/components/datagrid/example-modal-datagrid
- Observe there is no overflow of the modal
- Play around with changing the maxWidth option in the example page

1802 - Datagrid hide column display issues

---

app/views/components/tabs/example-composite-form.html
package.json
src/components/expandablearea/expandablearea.js

When user resizes the browser with the expandablearea `is-expanded`, the applyIE11Fix does not take effect.
Relates to #1768.
- Pull branch
- Run app
- In IE11
- Expand browser window to desktop size
- Ensure expandablearea `is-expanded`
- Browse to http://localhost:4000/components/compositeform/example-index.html
- Collapse browser window to mobile size
- Ensure there is no overflow
- Expand back out to desktop size
- Follow above IE11 steps but use http://localhost:4000/components/tabs/example-composite-form.html

1768 - Tabs IE11 mobile overflow QA FAIL

---

src/components/pager/_pager.scss
src/components/pager/pager.js
src/layouts/_layouts.scss

This PR adds an additional patch as a follow up to #1691, specifically for fixing some mobile-layout related problems on the Pager and its page-size selector button.  The issues are documented [in this comment](https://github.com/infor-design/enterprise/issues/1459#issuecomment-475228968)
Closes #1459
Pull this branch and run the demoapp.
_Test the landscape orientation bug and visibility of page size selector (**NOTE**: To test these issues, you need to be using an iPhone, or running an iPhone simulator on a Mac)_
- Open Safari and navigate to …

1459 - Fix page size selector bugs on responsive List/Detail view [v4.17.x]

---

src/components/datagrid/datagrid.js
test/components/blockgrid/blockgrid-api.func-spec.js
test/components/blockgrid/blockgrid-events.func-spec.js

Added fixes for noted QA issues on 1716. Some things were not working perfectly when changing to landscape mode and the sizeColumnsEqually feature was broken. Also fixed one deprecation warning in the tests. Also removed one deprecation in datagrid as the function is actually different so the comment is incorrect
Fixes #1716 
http://localhost:4000/components/datagrid/test-columns-stretch-column.html
- open on an IOS device or browser stack
- turn the device to landscape mode (this should now work)
http://localhost:4000/components/datagrid/test-columns-equal.html
- all columns should be …

1716 - Added QA fix for landscape stretch column and size columns equally [v4.17.x]

---

src/components/dropdown/dropdown.js

Made additional fix so that #1731 was solved for IE 11. Did this by removing old code with a timeout.
Tested back old stuff and could not reproduce any issues.
Closes #1731 
- Retest steps on https://github.com/infor-design/enterprise/pull/97
- open IE 11
- go to http://localhost:4000/components/dropdown/example-no-search-lsf.html
- click on the first Dropdown to open it
- hit tab
- should close the list and go to the next field.

1731 - Added additional fix for IE, Tab focus [v4.17.x]

---

app/views/components/datagrid/test-before-row-activated.html
src/components/datagrid/datagrid.js

Example page for rowactivated was not working with IE11.
Closes #1021
http://localhost:4000/components/datagrid/test-before-row-activated.html
- Open above link with IE11
- Click on any row to make it activated
- See `beforerowactivated` is triggered
- Then `rowactivated` is triggered

1021 - Fixed rowactivated for ie11 with datagrid [v4.17.x]

---

src/components/radar/radar.js

Fixed radar labels were cut off on small view ports.
Closes #1553
http://localhost:4000/components/radar/test-long-text.html
- Open above link with Galaxy S5
- Or resize to Galaxy S5 viewport
- See labels should not cut off

1553 - Fixed small size cutoff radar [v4.17.x]

---

app/views/patterns/builder-subtitle-test.html
docs/CHANGELOG.md
src/patterns/_builder.scss

In the Builder Panel Header, when the text is very long, it is being cropped. This becomes an issue for us when app is viewed on mobile because space becomes limited and fewer characters can be shown.
Closes #1814 
Goto 'http://localhost:4000/patterns/builder-subtitle-test.html'

1814 - Cropped Header for Builder Panel When Text is Long

---

docs/templates/documentationjs/theme-ids-website/section._

We needed to update the template to match the IDS website. I did this into `4.17.x` because it doesn't touch any consumer code and doesn't need QAd.
See pull request infor-design/website#773 for details
1. Test a documentation deploy to staging
---
Also reviewing the code change is easier to see with "hide whitespace" option on the diff:

Update the jsdoc template for website visuals [4.17.x]

---

app/views/components/datagrid/test-addrow-tabbing.html
app/views/components/datagrid/test-editable-validation.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/tooltip/_tooltip.scss

1822 - DataGrid: Tabbing through a new row moves focus to next line for a lookup column
1829 - DataGrid: Validation tooltip does not wrap words correctly across multiple lines
1822 
A datagrid with actionableMode: true and cellNavigation: true is setting focus to the next cell in the next row when tabbing from a lookup column where the user has typed in a value.
1829
If a validation rule has a long message than the words may not wrap correctly. This required a change to the validation message for the rule.
Closes #1822 
Closes #1829 
1822
1. Goto …

1822 & 1829- DataGrid tabbing and validation messages

---

src/components/radar/radar.js

Fixed radar labels were cut off on very small view ports.
Closes #1553
http://localhost:4000/components/radar/test-long-text.html
- Open above link with Win10 Firefox
- Resize the browser window to all the way smaller 
- See labels should not cut off

1553 - Fixed more small size cutoff radar [v4.17.x]

---

app/views/components/line/test-one-entry.html
src/components/line/line.js

x-axis labels were not showing on line graphs with only one value. This PR adds a check for the data length and does not remove the last entry if <= 1
closes #1674 
- Pull branch
- Check http://localhost:4000/components/line/test-one-entry.html
- make sure x-axis label is visible

1674 - Fix x-axis label not showing on line graphs with one value

---

docs/CHANGELOG.md
src/components/breakpoints/_breakpoints.scss
src/components/searchfield/_searchfield-toolbar.scss
src/components/tabs-module/_tabs-module.scss

Close icon (x) appears outside of searchfield input.
Closes #1704.
Pull branch and run app.
- Browse to the three pages noted in the issue by QA:
- http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
- http://localhost:4000/components/tabs-module/example-category-searchfield.html
- http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html
- Notice the close icon is now appearing in the searchfield input.
This may need some tweaking as I'm not 100% on the placement of some of these items. Happy to take suggestions.

1704 - Tabs-module searchfield x icon

---

app/src/js/routes/general.js

This PR fixes a bug in the demoapp where, on component pages (and basically any page using the general route), query parameter strings in a URL with a file extension (.html) would incorrectly be included in a filename while attempting to resolve a matching view template.
Closes #1884 
- Navigate to http://localhost:4000/components/form/example-forms?theme=uplift.  Everything should render properly.
- Next, navigate to http://localhost:4000/components/form/example-forms.html?theme=uplift.  Everything should render properly.
- Next, navigate to …

1884 - Fix demoapp's handling of query parameters on component pages

---

app/views/components/notification/example-index.html

This PR fixes the main Notification sample page to work against HTML markup that will be the same among the demoapp's layouts.  Previously, the main example was broken on the IDS website because it was targeting the wrong element with an `.insertBefore()` statement.
Changing the above also fixed an additional problem on the sample where some of the Header's elements weren't able to be clicked.
Fixes #1893 
Fixes #1639 
Pull this branch and run the demoapp, then...
_To test the layout problem:_
- Navigate to http://localhost:4000/components/notification/example-index.html.  The four …

1893 - Fix Notifications example to work on common element in all layouts [v4.17.x]

---

src/components/datagrid/datagrid.js
src/components/drag/drag.js

Fixed resize 2nd last column was not working with datagrid.
Closes #1890
http://localhost:4000/components/datagrid/example-filter
- Resize the "Status" column
- Should be working fine

1890 - Fixed resize 2nd last column was not working with datagrid [v4.17.x]

---

src/components/locale/cultures/en-US.js
test/components/locale/locale.func-spec.js

This PR fixes a bug in the IDS `en-US` culture file that was causing incorrect number formatting due to an incorrect `groupSize` definition.  It was previously set to `[3,0]`, where it needed to be `[3,3]`.
Additionally, some functional tests were altered to reflect the correctly formatted values with a `[3,3] groupSize.
Closes #1907
All functional tests related to the `Locale` API, specifically the ones that test `Locale.formatNumber()` against `en-US`, should all pass.
----
paging @pwpatton @fitzorama

1907 - Fix for incorrect groupSize definition on US Locale [v4.17.x]

---

test/components/datepicker/datepicker.e2e-spec.js

One datepicker test keeps failing in the cron job.
n/a
1. go to `datepicker.e2e-spec.js`
1. Mark the right `it` test to be `fit` (get the test from the files changed tab for this PR) 
1. `npm run start && npm run e2e:local:debug`
---
- 🚫 A note to the change log.

e2e - Use a date variance vs enum array for testing

---

app/views/components/datagrid/test-custom-number-formats.html
docs/CHANGELOG.md
src/components/locale/locale.js
test/components/locale/locale.func-spec.js

Fixed trailing zeros were getting ignored when displaying thousands values with German Locale.
Closes #1840
http://localhost:4000/components/datagrid/test-custom-number-formats.html?locale=de-DE
- All functional tests related to the Locale API should pass
- Review last two columns (Integer, Decimal)
- See 1st row should be (Integer:145.000, Decimal:145.000,00)
- And 2nd row should be (Integer:283.423, Decimal:283.423,00)

1840 - Fixed trailing zeros were getting ignored with german locale

---

docs/CHANGELOG.md
src/components/datepicker/datepicker.js

Doing triage on #411 i found the solution was very simple so included a fix. For this to work we will need to merge and bump versions in the NG pr https://github.com/infor-design/enterprise-ng/pull/417
Fixes NG 411 
http://localhost:4200/ids-enterprise-ng-demo/datepicker
- go to the custom validation field at the bottom
- tab out 
- error should show no matter what you type
(or take my word for it since they depend on each other) https://github.com/infor-design/enterprise-ng/pull/417

NG411 - Fixes unintentional removal of custom validation

---

test/components/datepicker/datepicker.e2e-spec.js

The 1min variance was too small for testing the one datepicker test.
n/a
- CI passes
Please include the following in your PR:
- 🔕 A note to the change log.

e2e - Up the datepicker variance amount to 2 mins

---

docs/CHANGELOG.md
src/components/dropdown/_dropdown.scss
src/components/dropdown/dropdown.js

Fixed multiselect dropdown unchecking "Select All" was not getting clear after close dropdown with Safari browser.
Closes #1882
http://localhost:4000/components/multiselect/test-select-all.html
- Open above link with safari
- Click on dropdown to open list
- Click on "Select All" option to select all items
- Click somewhere else to make dropdown close its list
- Click again on dropdown to open list
- Click on "Select All" option to unselect all items
- Click on any item in dropdown list
- Should toggle select/unselect with one click

1882 - Fixed selected all was not working with dropdown

---

package.json
src/components/datagrid/datagrid.formatters.js

Fixes the check on 1, '1'
https://github.com/infor-design/enterprise/issues/1948
Add a data grid component, with some data.
Add a column which use Soho.Formatters.Checkbox
Column should be checked if data contains either true, 1, or '1'

1948 - Fixes datagrid checkboxes when string  '1' and '0 is used as the source

---

app/views/patterns/builder-subtitle-test.html
src/components/datagrid/datagrid.editors.js
src/patterns/_builder.scss

Closes #1814 
1. Open  http://localhost:4000/patterns/builder-subtitle-test.html on IE 11
2. ensure the the sub-header is not cropped and has an ellipsis

1814 - Fix ellipsis on header for IE11

---

docs/CHANGELOG.md
package.json
src/components/button/_button.scss
src/components/searchfield/_searchfield-toolbar.scss

We were seeing issues with using opacity in button disabled state styles, so we adapted the tokens and are now using those. Yes there will be slight visual changes, but nothing drastic.
You can read more about it in the following design-system pull requests:
- https://github.com/infor-design/design-system/pull/361
- https://github.com/infor-design/design-system/pull/366
#1914 
1. `npm i && npm run start`
1. Compare the following links and make sure the buttons look disabled
- Sscreenshot here: https://github.com/infor-design/design-system/pull/361#pullrequestreview-225246269)
- Screenshot …

1914 - Replace opacity property from buttons disabled state css

---

app/views/components/datagrid/test-codeblock.html
app/views/components/datagrid/test-editable-before-commitcelledit.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.editors.js
src/components/datagrid/datagrid.js

For editable datagrid added support for
- Tab thru in edit mode
- Event `beforecommitcelledit` to stay in edit mode till ready to commit
- Example page for code block custom editor and event `beforecommitcelledit`
Closes infor-design/enterprise-ng#355
http://localhost:4200/ids-enterprise-ng-demo/datagrid-code-block-editor
- Build and run enterprise-ng with this fix
- Go in to edit mode by pressing enter key or click to any cell in last column "Code Block"
- Should be able to navigate thru inputs in editor by tab key
- Press Enter key to go out from edit mode …

355 - Added support for tab thru to multiple inputs in edit mode datagrid

---

app/views/components/datagrid/test-custom-tooltip-dynamic.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/lookup/lookup.js
test/components/toolbar-flex/toolbar-flex-api.func-spec.js

Removes the `audible` span from the lookup label so that the code block does not use that text in the tooltip. Will need to revisit the screen reader implementation using `aria-haspopup` instead.
related to ([#354](https://github.com/infor-design/enterprise-ng/issues/354))
- `npm run build` and move the `dist` into enterprise-ng `node_modules` or `npm link` this branch to enterprise-ng.
- create test page in enterprise-ng with the attached example. [CodeBlockTooltip.zip](https://github.com/infor-design/enterprise/files/3069086/CodeBlockTooltip.zip)
- make sure the tooltip only displays the …

NG354 - Fixes tooltip in code block

---

src/components/notification/notification.js

The different notification classes were not being added to the notification DOM elements, because IE11's `classList` implementation does NOT support multiple parameters for the `add()` & `remove()` methods. See [caniuse classList()](https://caniuse.com/#feat=classlist).
- https://github.com/infor-design/enterprise/issues/1857
1. View the screenshots in the issue above
1. `npm run start`
1. Open Chrome
1. Go to http://localhost:4000/components/notification/example-index.html
1. verify the notifications look right
1. Open IE11
1. Go to …

1857 - Only use 1 parameter for classList.add() for IE11 support [4.18.x]

---

docs/CHANGELOG.md
src/components/dropdown/dropdown.js

Fixed previous selection was not clear after uncheck "Select All" option.
Closes #2003
http://localhost:4000/components/multiselect/test-select-all.html
- Click on dropdown to open list
- Select Alabama then close the dropdown, Alabama will be displayed on the dropdown
- Open the dropdown again, click "Select All" then close the dropdown
- All States will be displayed on the dropdown
- Open the dropdown again and uncheck "Select All" then close the dropdown
- See dropdown should be all clear, previous selection should not be displayed

2003 - Fixed previous selection was not clear with multiselect [4.18.x]

---

.travis.yml

- This will change the CI to only Build (test) pushed branches:
- `master`
- `A.B.x` branches (i.e. `4.10.x`)
- Existing functionality should continue to...
- Build/test pull requests into `master` AND released branches
- Only deploy when the base branch is `master`
n/a
1. Make sure that non-master and non-released branches are not building like they were before
1. Make sure testing still happens on PRs
1. Make sure `master` still deploys on merges from PRs
1. Generally check for anything woky

Only run CI on master and release branches

---

app/views/components/tabs/example-activated-event.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/tabs/tabs-api.func-spec.js

`aria-checked` attribute was not toggling on selection of header checkbox.
Closes #1961.
- Pull branch
- Run app
- Visit http://localhost:4000/components/datagrid/example-multiselect
- Open Dev Tools
- Find `multiselect` checkbox in header in Elements tab
- Interact multiple times with header `multiselect` checkbox and ensure `aria-checked` toggles correctly

1961 - Datagrid aria-checked incorrect

---

src/components/dropdown/_dropdown.scss
src/components/dropdown/dropdown.js

Fixed tooltip was not displaying with dropdown.
Closes #2016
http://localhost:4000/components/dropdown/example-tooltips.html
- Hover on the dropdown
- Tooltip should show
http://localhost:4000/components/dropdown/test-multiselect-with-tooltip.html
http://localhost:4000/components/multiselect/example-index.html
- Click on dropdown to open list
- Select items so it can over flow the text box
- Close the dropdown list
- Hover on the dropdown
- Tooltip should show
**Additional context**:
No change log as its not a new fix

2016 - Fixed tooltip was not displaying with dropdown [4.18.x]

---

docs/CHANGELOG.md
src/utils/excel.js

Exported data was incorrectly lining up between `thead` and `tbody` elements.
`indexOf` was being called on elements in an array of elements wherein the elements were themselves being actively removed in a loop; causing `indexOf` to report false positives based on a changing base.
Closes #2001.
- Pull branch
- Run app
- Visit http://localhost:4000/components/datagrid/example-export-from-button.html
- Use the two "Export..." buttons and ensure the downloaded files correctly reflect the visible data.

2001 - Fix incorrectly exported Datagrid CSV/Excel data [v4.18.x]

---

src/components/dropdown/dropdown.js

Fixed previous selection tooltip was displaying on Mobile with Dropdown.
Closes #2052
http://localhost:4000/components/dropdown/example-index.html
http://localhost:4000/components/dropdown/example-tooltips.html
- Open above link with Android and iOS
- Select item in the dropdown
- Close the dropdown, then open again
- See tooltip should not show when not necessary
http://localhost:4000/components/multiselect/example-index.html
- Open above link with Android and iOS
- Select item/s in the dropdown
- Close the dropdown
- See tooltip should not show if text not overflowed
**Additional …

2052 - Fixed tooltip on mobile with dropdown [v4.18.x]

---

docs/CHANGELOG.md
src/components/dropdown/_dropdown.scss

Dropdown close icon was misaligned on iOS and Android.
Closes #2018.
- Pull branch
- Run app
- Visit each of the URLs on mobile and ensure the close icon is properly aligned.
- http://localhost:4000/components/multiselect/example-index.html 
- http://localhost:4000/components/dropdown/example-index.html

2018 - Fix misaligned Dropdown close icon on mobile [v4.18.x]

---

app/views/components/dropdown/example-icons.html
app/views/components/personalize/example-color-theme-api.html

Fixed the examples to work in IE and fixed a duplicate ID.
Fixes #2013 (more)
http://localhost:4000/components/dropdown/example-icons.html
http://localhost:4000/components/personalize/example-color-theme-api.html
- both these examples work to change the header color in IE (and other browsers)
- for the http://localhost:4000/components/dropdown/example-icons.html example if you select the last two items they should no longer highlight each (they had duplicate IDS)

2013 - Follow up fixes [v4.18.x]

---

src/components/datagrid/_datagrid.scss

Extra margins for scrollbars were causing RTL fixed header columns to be misaligned. This PR adds css overrides to remove the margin on ios and android.
closes #1957 
- pull branch
- go to http://localhost:4000/components/datagrid/example-fixed-header.html?locale=he-IL#
- In mobile dev tools select an android or ios device and make sure the header columns remain aligned when scrolling horizontally.

1957 - Fixes datagrid misaligned columns on mobile

---

app/views/patterns/list-detail.html
docs/CHANGELOG.md
src/patterns/list-detail/_list-detail.scss

This PR removes some legacy code in the list/detail pattern that was causing text on inline Toolbar Searchfields to be transparent, and therefore illegible.
Closes #2075 
- Pull this branch and run the demoapp.
- Navigate to http://localhost:4000/patterns/list-detail
- Open the Searchfield inside the detail area's toolbar (not the header toolbar)
- Enter some text.  Ensure that the text is legible.
**Included in this PR:**
----
Paging @Sovia @pwpatton

2075 - Fixes transparent text bug on List/Detail > Toolbar > Searchfield combination

---

src/components/dropdown/_dropdown.scss

Dropdown close icon on Chrome in Android on mobile was misaligned.
Relates to #2018.
- Pull branch
- Run app
- Visit http://localhost:4000/components/dropdown/example-editable in Chrome on Android mobile
- Ensure close icon on dropdown is correctly aligned after opening dropdown

2018 - Dropdown close icon misaligned FAILED QA [v4.18.x]

---

docs/CHANGELOG.md
src/utils/excel.js

Since 4.17 the export failed on windows. This is because IE doesnt like assigning to classList so i changed it to set it as an attribute.
Fixes #2018 
http://localhost:4000/components/datagrid/example-export-from-button.html
- hit the two buttons and export to see a download
- test on all browsers (especially IE)

2081 - Excel Export Fails on Windows [v4.18.x]

---

src/components/dropdown/dropdown.js

Fixed tooltip was not closing on Mobile with multiselect.
Closes #2052
http://localhost:4000/components/multiselect/example-index.html
- Open above link with Android and iOS
- Select items many in the dropdown list so text overflowed
- Close the dropdown list
- See tooltip should show
- Click anywhere else or open another dropdown
- Tooltip opened should close at this point
**Additional context**:
No change log as its not a new fix

2052 - Fixed tooltip on mobile was not closing with multiselect [v4.18.x]

---

src/components/searchfield/_searchfield-toolbar.scss
src/components/searchfield/_searchfield.scss
src/core/_config.scss
src/themes/dark-theme.scss
src/themes/high-contrast-theme.scss

This PR fixes some problems with the Toolbar Searchfield found during Q/A:
- There was previously no difference between the color of the placeholder text and the user-keyed text on in-page Toolbar Searchfields, which was making it hard to discern which Searchfields had user-keyed text entered.
- If text had previously been entered into a collapsible Toolbar Searchfield, it was possible to close the Searchfield, and see the "X" button present while hovering the Searchfield.
Closes #2075
Examine the following pages on all available themes, and ensure that the color of the placeholder text in …

2075 - Fix placeholder text and "X" button on in-page Toolbar Searchfields [v4.18.x]

---

src/components/datagrid/_datagrid.scss

Fixed dropdown border colors were inconsistent in iOS devices with filterable datagrid.
Closes #2073
http://localhost:4000/components/datagrid/test-filter-disabled.html
- Open above link with iOS
- See dropdown borders color in header filter
- Should not be inconsistent
**Additional context**:
No change log as its not a new fix

2073 - Fixed dropdown border colors for iOS with datagrid [v4.18.x]

---

app/views/components/column/test-custom-tooltips.html
docs/CHANGELOG.md
src/components/column/column.js
test/components/column/column.e2e-spec.js

Added support to existing custom tooltip content in the callback setting.
Closes #1909
http://localhost:4000/components/column/test-custom-tooltips.html
- Hover 1st column and see the tooltip (three lines info, name, value)
- Hover 2nd column and see the tooltip (three lines name, short name, value)
- Hover 3rd column should not show tooltip
- Any other columns should show tooltip	with two lines (name, value)

1909 - Added support for custom tooltip callback with column chart

---

app/views/components/input/example-required-fields.html
app/views/components/input/test-legacy-required-fields.html
app/views/components/signin/example-index.html
docs/CHANGELOG.md
src/components/form/form.js
src/components/form/readme.md
src/components/input/_input.scss
src/components/input/readme.md

This PR reverses some changes that removed the display of the red asterisk from required form field labels.  The previous method of displaying these asterisks was not accessibility friendly, but has been added back to provide backwards compatibility, and time for deprecation.  The new, more-accessible method of using these asterisks has been made "opt-in" by way of adding an additional CSS class to the label.
Additionally, the Form component's automatic appending of the accessibility-friendly markup has been changed to check for the class.  Documentation and a changelog note for these changes have also been added.
- Related to #421
- Reverses some …

Adds backward-compat for accessible required input field labels [v4.18.x]

---

app/views/components/message/example-index.html
docs/CHANGELOG.md
src/components/message/message.js
test/components/message/message-xss.func-spec.js

**Explain the details for making this change. What existing problem does the pull request solve?**
Markup was visibly added to the title of the message component. This is now an option and is strictly audible.
Closes #2120.
- Visit http://localhost:4000/components/message/example-index.html
- ensure audible text is in message title of first button through dev tool
- use JAWS to ensure it's read 
**This PR includes**:

2120 - Message unwanted visible alert [v4.18.x]

---

docs/CHANGELOG.md
src/components/personalize/personalize.js
src/components/personalize/personalize.styles.js

Improves maintainability of personalized CSS styles by separating into standalone file and formatting. This PR **does not** change any specific styles, only improves the readability of the styles.
Closes #2127
Compare there are no visual differences between:
* https://master-enterprise.demo.design.infor.com/components/personalize/example-classes.html
* http://localhost:4000/components/personalize/example-classes.html
or 
* http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized.html?theme=uplift&colors=7025B6
* …

2127 - Separate personalize styles into own file

---

app/views/components/applicationmenu/example-personalized-role-switcher.html
docs/CHANGELOG.md
src/components/applicationmenu/applicationmenu.js

Do not know why but https://github.com/infor-design/enterprise/pull/1982 when merged never actually went into master.. its simply not in the histroy https://github.com/infor-design/enterprise/commits/master/src/components/applicationmenu/applicationmenu.js
No clue what happened so resubmitted
- Initialize expandable area within application menu
- Add support to close expandable area
Fixes #1978
- Open http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html
- Make sure role switcher is expanding/collapsing and expandable area is closed when a role is …

1978 - Expandable area updates within application menu (Readded)

---

docs/CHANGELOG.md
src/components/modal/_modal.scss

Fixed contextual action panel the close button was misaligned.
Closes #1943
http://localhost:4000/components/contextualactionpanel/test-full-content.html
http://localhost:4000/components/modal/example-close-btn.html
- Click button to open
- See the close button should not misaligned

1943 - Fixed cap close button was misaligned

---

app/views/components/datagrid/test-destroy.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed when using context menu with datagrid was not properly destroyed which being created multiple times.
Closes infor-design/enterprise-ng#392
Closes #2140
http://localhost:4000/components/datagrid/test-destroy.html
- Run on console `$('.popupmenu-wrapper').length;`
- Should result 1
- Right click on both rows to open context menus
- While menu is open, run on console `$('.popupmenu-wrapper').length;`
- Should result 2
- Click on top buttons "Destroy" then "Invoke"
- Run on console `$('.popupmenu-wrapper').length;`
- Should result 1
- Right click …

392 - Fixed context menu with datagrid was not properly destroyed

---

app/views/components/personalize/example-classes.html
app/views/components/personalize/example-tabs.html
src/components/monthview/monthview.js
src/components/personalize/personalize.js
src/components/personalize/personalize.styles.js
src/utils/color.js

Brian noted some problems on the personalized tabs example https://github.com/infor-design/enterprise/issues/1962#issuecomment-491172208 this fixes them. Also to reuse a function i extracted it into its own color utils and added a few color functions i was aware of.
Fixes #1962 (Further)
Issue 1
http://localhost:4000/components/personalize/example-tabs.html
- change color to anything but azure or default
- change back to default (should stay azure on default)
Issue 2
http://localhost:4000/components/personalize/example-tabs.html
- this wont happen now because 1 is fixed.
Issue 3 …

1962 - Fixes failed QA personalized tabs bugs

---

app/views/components/applicationmenu/test-filterable-custom.html
app/views/includes/applicationmenu-with-searchfield-custom.html
docs/CHANGELOG.md
src/components/applicationmenu/applicationmenu.js
test/components/applicationmenu/applicationmenu.e2e-spec.js

Was requested to have a manual search field in the app menu that doesnt function by filtering the list. To do this now if you set `filterable: false` it wont actively remove the menu enabling you to do this.
Fixes #2066 
http://localhost:4000/components/applicationmenu/test-filterable-custom.html
- the filter field should show up
- typing in it will just do a toast now and not filter the list, simulating the usage.
http://localhost:4000/components/applicationmenu/example-filterable.html
- type role in the filter field
- this should still work

2066 - Adds the ability to add a custom search in app menu

---

docs/CHANGELOG.md
src/components/toolbar/_toolbar.scss

Fixed disabled button color for contextual toolbar in datagrid was not applying.
Closes #2150
- Navigate to http://localhost:4000/components/datagrid/example-multiselect.html
- Select any row
- Contextual toolbar with button "Remove" should show up
- Run on console `$('#remove-btn').disable();`
- See button "Remove" should have disabled color

2150 - Fix disabled button color for contextual toolbar in datagrid

---

docs/CHANGELOG.md
src/components/locale/locale.js
src/components/typography/_typography-uplift.scss
src/components/typography/_typography.scss
src/core/_controls-uplift.scss
test/components/locale/locale.func-spec.js

Made some changes to the lang attribute that are actually wrong, so reverted them. This makes the fonts change again for some languages.
Noticed the font order was inverted and updated the fonts based on Korean and Chinese user feedback.
Added placeholders for fonts in uplift and made Source Sans Pro still work there for now.
Fixes #2144 
http://localhost:4000/components/datagrid/example-index.html?locale=ar-EG
http://localhost:4000/components/datagrid/example-index.html?locale=ar-SA
http://localhost:4000/components/datagrid/example-index.html?locale=ja-JP …

2144 - Restore font changing

---

app/views/components/accordion/test-close-children-on-collapse.html
app/views/components/datagrid/example-beforeselect-veto.html
app/views/components/datagrid/test-contextmenu-in-events.html
app/views/utils/example-keyboard.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/index.js
src/utils/keyboard.js
test/components/accordion/accordion.e2e-spec.js
test/components/datagrid/datagrid-selection.func-spec.js
test/components/datagrid/datagrid-settings.func-spec.js
test/components/keyboard/keyboard.func-spec.js

Adds a beforeSelect callback to datagrid so that you can veto row selection. The requirements listed needed to also know if CTRL or shift is pressed, so re-added the keyboard module to start up #643 , this had the functionality needed to see the pressed keys anytime. To let the events run through had to fix up the contextmenu function. Bonus: can now right click datagrid as long as no context menu functionality is attached for inspection.
Fixes #1906 
http://localhost:4000/components/datagrid/example-beforeselect-veto.html
- Selecting rows is not possible.
- But if you hold down CTRL key …

1906 - Add a fixes so that beforeSelect can be vetoed

---

app/views/components/datagrid/example-paging.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed pager was not working while removing rows with datagrid. After removing 1 Row in 1000 data, the page was became 1 of 1.
Closes #1985
- Navigate to http://localhost:4000/components/datagrid/example-paging.html
- See bottom of grid pager should have 1 of 100
- Select any row
- Contextual toolbar with button "Remove" should show up
- Click on button "Remove"
- See the pager should be updated
- If page get refresh or any other call to load data like filter, next/prev page or records per page change
- Then removed rows will render back because this …

1985 - Fix where pager was not working while removing rows with datagrid

---

docs/CHANGELOG.md
docs/TRANSLATIONS.md
src/components/locale/cultures/sv-SE.js

Updated Swedish translation for `set Time` with Timepicker.
Closes #2153
- Navigate to http://localhost:4000/components/timepicker/example-index.html?locale=sv-SE
- Click clock icon to open time picker popup
- See the button text should be `Sätt tid`

2153 - Update swedish translation for set time with timepicker

---

app/views/components/personalize/example-classes.html
app/views/components/personalize/example-form.html
app/views/components/personalize/example-form2.html
app/views/components/personalize/example-tabs.html

IE 11 shows a check as transparent and not RGBA so the example didnt work in IE11.
This fixes that.
Fixes #1963 for IE
http://localhost:4000/components/personalize/example-form2.html
http://localhost:4000/components/personalize/example-form.html
- load these in IE and the blue color will show initially

1963 - Fixes some personalize examples to work in IE 11

---

.eslintrc.js
package.json
src/utils/utils.js
test/components/bar/bar-api.func-spec.js
test/components/searchfield/searchfield-categories.func-spec.js
test/helpers/func-utils.js

Add a plugin to `eslint` to check for browser compatible code (using `browerslist` requirements).
n/a
1. Watch the tests and make sure `estlint` succeeds
2. If you want you can run `npm run eslint` on your own.
---
🔧  An e2e or functional test for the bug or feature.
🚫  A note to the change log.

Add ES6 browser code compatibility linting

---

src/components/spinbox/spinbox.js

QA failed #2017 on edge as it appeared like it was inserting twice on click. This is really just the long press but it seems a little more sensitive on edge. Also added autocomplete off as saw the browser autocomplete popping up on testing.
Fixes #2107
http://localhost:4000/components/field-options/example-index.html
or
http://localhost:4000/components/spinbox/example-index.html
- click once on + and - and it should add or subtract one
- press down on either button and it should more slowly count up and down
- try on edge

2107 - Fixes spinbox tolerance on long press

---

app/views/components/hierarchy/test-multiple-charts.html
src/components/hierarchy/hierarchy.js

Fix for issue https://github.com/infor-design/enterprise/issues/2205. Fixes scoping issues which are preventing multiple hierarchy charts from loading properly on the same page.
https://github.com/infor-design/enterprise/issues/2205
1. Go to http://localhost:4000/components/hierarchy/test-multiple-charts.html
2. Click on tab two.
3. Both charts should load the same

2205 - Fix multiple hierarchy instance interference

---

src/components/field-options/_field-options.scss
src/components/searchfield/_searchfield.scss

This PR changes CSS values that affect the placement of the field options button when attached to input fields with a clearable (X) button attached.  Previously the button was appearing inside the input field. 
This was reported as an additional Q/A issue [here](https://github.com/infor-design/enterprise/issues/1862#issuecomment-494337434).
Closes #1862 
- Navigate to http://localhost:4000/components/field-options/example-index  
- Find the input field labeled "Clearable Input" and ensure that the Field Options button is properly aligned with/without …

1862 - Fix Clearable Input/Field Options alignment

---

app/views/components/datagrid/test-dirty-change-cell-externally.html
src/components/datagrid/datagrid.js

Based on QA comments, made an option to save the indicator across page. Also fixes some line endings. @davidcarlsonberg To address these comments https://github.com/infor-design/enterprise/pull/2194#pullrequestreview-240072985
1. I made the cells also clear
2. But the ! line means in progress it doesnt get added to all lines, it was just part of the example for the first line
Fixes #2091
http://localhost:4000/components/datagrid/test-dirty-change-cell-externally.html
- press change cell
- also edit a cell on row 2 for example quantity
- go to page two
- go back to page one
- should now …

2091 - Fixes some QA issues on the external dirty examples

---

docs/CHANGELOG.md
src/components/colorpicker/_colorpicker.scss

The readonly input font color is transparent and, only on IE11, not visible.
Closes #2134.
- Visit localhost:4000/components/colorpicker/example-sizes.html in IE11
- Verify you can see the text when changing colors through the colorpicker in the readonly input 
("Extra Small" label)

2134 - Colorpicker text not visible in IE11

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed header checkbox was not sync after removing selected rows with datagrid.
Closes #2226
- Navigate to http://localhost:4000/components/datagrid/example-multiselect.html
- Select 1st, 2nd, and 3rd rows
- See header checkbox (should be partial selected)
- Click Remove button
- See header checkbox (should be un-selected after removing rows)

2226 - Fix header checkbox was not sync with datagrid [v4.19.x]

---

src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js

Re-adds the fix from https://github.com/infor-design/enterprise/pull/2243 to the correct branch.
Fixes #2228 
- Navigate to http://localhost:4000/components/datagrid/example-paging-client-side.html
- Click Id column header to sort
- Click the Next Page button, then Click Previous Page
- See sorting arrow icon should stay even after changing grid page
ColGroup Test.
- Navigate to http://localhost:4000/components/datagrid/test-paging-select-indeterminate-single.html
- Click the Next Page button

2228 - Fix an issue with the sort indicator being missing [v4.19.x]

---

docs/CHANGELOG.md
src/components/contextualactionpanel/_contextualactionpanel.scss

Contextual Action Panel title is too close to the left side at phone screen size.
Closes #2249.
- Visit http://localhost:4000/components/contextualactionpanel/example-index.html
- Ensure at small screen sizes (under phone) the CAP title is not too close to the edge.

2249 - Contextual Action Panel title too close to edge at mobile [v4.19.x]

---

app/views/components/datagrid/test-filter-lookup-click-function.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js

Fixed custom filter conditions were not setting up filter button with datagrid.
Closes #2234
- Navigate to http://localhost:4000/components/datagrid/test-filter-lookup-click-function.html
- Click on the filter options next to the lookup for column `Product Id`
- See in console should not be any error
- Popup should open to select filter conditions

2234 - Fix custom filter conditions for filter button popup with datagrid [v4.19.x]

---

src/components/locale/locale.js
test/components/contextualactionpanel/contextualactionpanel-as-settings.func-spec.js
test/components/datagrid/datagrid.e2e-spec.js

Fixes a bug found when running tests in random order. The problem would be no promise is returned in the case that the language is already loaded.
N/A
- tests should pass
- can re-run `npm run functional:ci` several times
- if you wanted to you could run `for i in {1..10}; do npm run functional:ci; done` with only these tests in locale with a `fit` on them this made it occur every time.
```
Locale API
✔ Should parse Dates with dashes in them
✔ Should format percent
✔ Should be possible to set the language to something other than the current locale
✔ Should Get the Parent Locale
```

NA - Fix a test failure and bug when language is already resolved [v4.19.x]

---

app/views/includes/head.html
src/components/colorpicker/colorpicker.js
src/components/personalize/personalize.bootstrap.js
src/components/personalize/personalize.js
src/components/personalize/readme.md
test/components/personalize/personalize-api.func-spec.js

Landmark used manual themes which would cause an extra overlay to occur in some cases. In addition fixed some bugs:
- Color picker was not initializing
- Added a config to skip default Personalization Init (This may not be needed to solve landmarks issue 100% but just in case)
- Fix to prevent the theme and overlay from adding extra times
Fixes #2258 
1. Go to: http://localhost:4000/components/personalize/example-form.html?theme=uplift&variant=dark
- look at the theme on the html tag
- use theme theme switcher and make sure the tag is correct
- debug personalize init and make sure its not …

2258 - Allow manual personalization [v4.19.x]

---

app/views/components/modal/test-checkbox.html
docs/CHANGELOG.md
src/components/checkboxes/_checkboxes.scss

Fixed the Modal was disappears if its content use checkbox in it with RTL settings.
Closes infor-design/enterprise-ng#332
- Navigate to http://localhost:4000/components/modal/test-checkbox.html?locale=ar-EG
- Click on button "Show Modal" to open modal
- Modal should open and show it's content fine

332 - Fix the modal was disappears if its content use checkbox in it with rtl

---

app/views/components/datagrid/example-grouping-multiselect.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js

Sorting is not working on columns when `selectable: 'multiselect'`.
Closes #2251.
- Pull branch and run app
- Visit http://localhost:4000/components/datagrid/example-grouping-multiselect.html
- Ensure sorting works on all headers.
- Also test other grouping examples.

2251 - Datagrid grouping multiselect not sortable [v4.19.x]

---

app/views/components/datagrid/test-save-settings.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/tooltip/_tooltip-uplift.scss

Fixes a bug when using a lookup column with editorOptions some operations. Also fixes column reset.
Fixes #2279 
Fixes #1921 (coincidentally)
http://localhost:4000/components/datagrid/test-filter-lookup-click-function.html
- in this example an alert should show if the grid object is found on the clickArgs (should still alert)
http://localhost:4000/components/datagrid/test-save-settings.html
- drag, sort page, extend columns
- reload the page and things should still be saved
- click the lookup filter and it should still open a dialog
- reset columns will set back to factory defaults …

2279 - Fixes a JSON error in datagrid with lookups [v4.19.x]

---

src/components/accordion/_accordion-uplift.scss
src/components/accordion/_accordion.scss

Minor adjustments for the visual style of the accordion on the Uplift theme:
- Fix alignment of text to expander icons on subheaders
- Removes some Safari-specific CSS that was causing alignment issues of the Chevron in both the Soho and Uplift themes.
#2289 
- Open http://localhost:4000/components/accordion/example-accordion-panels.html?theme=uplift in various browsers
- Open the "Learning" header on any of the three accordions.  Ensure the alignment of the text to the (+/-) buttons looks centered.
- Open the same page in Safari against both Uplift and Soho …

2289 - Uplift Accordion Adjustments [v4.19.x]

---

src/components/editor/_editor.scss

This PR fixes an issue with the Uplift Editor's H3/H4 tags, which previously appeared to overlap when spanning multiple lines.
#2289 
- Open http://localhost:4000/components/editor/example-index.html.  Change the top paragraph to an H3 and then an H4.  Ensure the text doesn't overlap itself.
- Open http://localhost:4000/components/editor/example-index.html?theme=uplift.  Change the top paragraph to an H3 and then an H4.  Ensure the text doesn't overlap itself.

2289 - Uplift Editor Adjustments [v4.19.x]

---

src/components/tabs-module/_tabs-module-uplift.scss
src/components/tabs/_tabs-uplift.scss

This PR fixes a problem in Module tabs where the "More Tabs" dropdown no longer works properly, due to a miscalculation on overflowed tabs.  This was happening because of the tab sizes changing.
#2289
- Open http://localhost:4000/components/tabs-module/example-app-menu-button.html?theme=uplift
- Ensure tabs look right, and on desktop breakpoint, the app menu trigger along with three tabs are displayed, and the more button is not displayed.
- Ensure that collapsing to phone breakpoint causes the more button to display.

2289 - Uplift Module Tabs Adjustments [v4.19.x]

---

src/core/_config.scss
src/themes/theme-soho-dark.scss
src/themes/theme-uplift-dark.scss

This PR changes the colors of the "alternate" day text in the Monthview calendar layout to better stand out on all color schemes/variants.
#2289 
Pull branch, run app, test the following pages and ensure the text colors for the days that are displayed, but not part of the current month, are less "visible" than the days that ARE part of the current month:
- http://localhost:4000/components/monthview/example-index.html
- http://localhost:4000/components/monthview/example-index.html?theme=soho&variant=dark
- http://localhost:4000/components/monthview/example-index.html?theme=soho&variant=contr …

2289 - Uplift Monthview Adjustments [v4.19.x]

---

app/views/components/datagrid/test-editor-dropdown-source.html
src/components/datagrid/datagrid.js
src/components/dropdown/dropdown.js
test/components/datagrid/datagrid.e2e-spec.js

The way landmark does filtering with clientSideFilter set the values in the filter row would be reset.
Fixes #2296 
Go to http://localhost:4000/components/datagrid/test-editor-dropdown-source.html#
- open the filter dropdown on the header and pick one value
- close the filter dropdown by clicking out and the value should show
- type a value in the text input filter in the header and hit enter
- both values should still be there
-  open the filter dropdown on the header and pick one two values
- close the filter dropdown by clicking out and the value should show
IMPORTANT: This example …

2296 - Fix a bug restoring filter [v4.19.x]

---

src/themes/theme-uplift-dark.scss

The filter row color was incorrect for dark/uplift, changed the color in the config.
#2289 
Go to 
http://localhost:4000/components/datagrid/example-filter.html?theme=uplift&variant=dark
- filter row icons and text should be visible now

2289 - Fix Datagrid uplift + dark filter row [v4.19.x]

---

app/views/components/datagrid/example-beforeselect-veto.html

The veto example used a feature not available in IE11. Changed the logic.
Fixes #2321
http://localhost:4000/components/datagrid/example-beforeselect-veto.html
- open in IE11 (and retest other browsers)
- hold ctrl or command (mac)
- click the checkbox and it should select
- check the console for no errors

2321 - Fix an ie 11 incompatibility in the example [v4.19.x]

---

src/components/personalize/personalize.styles.js

Fixes IE11 issues with the personalize examples
Fixes #2298  (Failed comment) 
Fixes #2277 (Failed comment) 
http://localhost:4000/components/personalize/example-classes.html?theme=uplift
http://localhost:4000/components/personalize/example-form.html?theme=uplift
http://localhost:4000/components/personalize/example-form2.html?theme=uplift
http://localhost:4000/components/personalize/example-form3.html?theme=uplift
http://localhost:4000/components/components/personalize/example-form4.html?theme=uplift
http://localhost:4000/components/components/personalize/example-form4.html?theme=uplift
- …

2298 - Fix personalize examples for IE11 [v4.19.x]

---

app/views/components/autocomplete/test-xss-security.html
app/views/components/dropdown/test-xss.html
app/views/components/modal/test-xss.html
docs/CHANGELOG.md
src/components/autocomplete/autocomplete.js
src/components/dropdown/dropdown.js
src/components/modal/modal.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/dropdown/dropdown.e2e-spec.js
test/components/locale/locale.func-spec.js

This is a patch for 4.18.2. It addresses two XSS issues found in autocomplete and dropdown.
Fixes infor-design/enterprise-ng#502
Fixes infor-design/enterprise-ng#503
Fixes infor-design/enterprise-ng#511
- open the console
- http://localhost:4000/components/autocomplete/test-xss-security.html
- type '<'
- check the console, should be no CSP errors or any document alerts.
http://localhost:4000/components/dropdown/test-xss.html
- open the console
- open the list
- select the item with the script code in it
- check the console, should be no CSP errors or any document alerts. …

502/503 - Patch for Xss issues [v4.18.x]

---

app/views/components/pager/example-standalone.html
docs/CHANGELOG.md
src/components/pager/pager.js

Because we have a position: sticky menu the pager dropdown menu is not sizing correctly when its open in our app. The existing option attachPageToBody fixes this but the pager doesnt have a way to set it.
Fixes #2355 
- go to http://localhost:4000/components/pager/example-standalone.html
- toggle the attach pagesize menu to body checkbox
- look in the dom and notice the page size menu 
- if checked the page size chooser menu should be at the dom level
- if unchecked the page size chooser will show in the pager element.

2355- add attachToBody option to standalone-pager for pageSizeChooser menu [v4.19.x]

---

src/components/locale/locale.js
src/components/tooltip/tooltip.js
test/components/locale/locale.func-spec.js

Saw some errors loading locales that depend on another locale on deployed pages. es-ES -> es-US and en-US -> en-GB ect..
Fixes #2216 
- go to https://2216-locale-error-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?locale=en-GB
- https://2216-locale-error-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?locale=es-ES
- https://2216-locale-error-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?locale=de-DE
- not not all languages are translated yet so if one is not found it should …

2216 - Missing Languages on en-GB (or "child" languages) [v4.19.x]

---

app/data/compressors.js

Updates the compressor serverside dataset to allow for more of the filter operations. Previously it was coded for just equals and contains.
Closes #2301 
1. Visit http://localhost:4000/components/datagrid/test-save-settings-serverside.html
2. Filter the Quantity column on Does Not Equal and type a number that exists in a cell in that column.
3. Ensure the column is filtered against that number and filter option.

2301 - Datagrid Server side filtering dataset

---

docs/CHANGELOG.md
src/components/popupmenu/popupmenu.js

Fixed js error was showing after removing menu item with Popupmenu.
Closes infor-design/enterprise-ng#414
- Pull and build this EP branch
- Pull and build NG branch ([414-popupmenu-removed-item](https://github.com/infor-design/enterprise-ng/tree/414-popupmenu-removed-item))
- Navigate to http://localhost:4200/ids-enterprise-ng-demo/menu-button
- Click the charts menu to open
- Click last item `Click this to remove myself`
- See the console, should not be any error

414 - Fix js error was showing after removing item with popupmenu

---

app/views/components/datagrid/example-list.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Text date in the dataset are sorted as text, you can not always determine if the string is a date or if it needs to be parsed to a date to sort correctly, so I added a sortFunction to allow the value to be converted to a value for the sort. This can then be used for any column type, eg DropDown list sorted by the label or value. 
Closes #2274 
1. Go to http://localhost:4000/components/datagrid/example-list
2. Click the "Customer Since" column header to sort in ascending order

2274 - Datagrid Column sortFunction

---

app/src/js/middleware/info-handler.js
app/views/components/compositeform/_header.html
app/views/components/menubutton/example-submenu-icons.html
app/views/components/popupmenu/example-selectable.html
app/views/components/toolbar/test-ajax-from-menubutton-in-spillover.html
app/views/components/toolbar/test-ajax-from-toolbar-on-spillover.html
app/views/components/toolbar/test-ajax-on-spillover.html
app/views/components/toolbar/test-tooltips-populating-more-actions.html
app/views/includes/head.html
app/views/includes/header-actionbutton.html
app/views/includes/header.html
docs/CHANGELOG.md
src/components/header/header.js
src/components/listview/_listview.scss
src/components/personalize/personalize.js
src/components/toolbar/toolbar.js
src/themes/theme-uplift-contrast.scss
test/components/datagrid/datagrid.e2e-spec.js
test/components/personalize/personalize-api.func-spec.js
test/components/personalize/personalize.e2e-spec.js
test/components/toast/toast.e2e-spec.js
test/kitchen-sink.e2e-spec.js

Updated the theme switcher to include the uplift theme. In doing so split it into 3 submenus.
Also fixed a couple bugs noticed in the examples as related.
- Sending a non existant theme leaves the overlay on
- The uplift / high contrast example hover state was wrong
- The text in dark theme was wrong on list view
- Fixed a bug where a toolbar with submenus may have too much padding
- Updated a couple tests that failed randomly
Closes #2325
http://localhost:4000/components/listview/example-index.html?theme=soho&variant=dark
- notice the text color …

2325 - Add uplift theme to the switcher

---

app/views/components/datagrid/example-paging.html

Update the example so that the selection is not cleared on sorting.
Closes #2322 
Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging.html
Click the Checkbox column header
Click the Id column header to sort
See issue: notice that the checkbox column header will be unchecked
Click the checkbox of first row
Now check the checkbox column header again
See issue: Checkbox column header is now unchecked

2322-Datagrid Update example to select across pages

---

app/views/components/field-options/example-input-fields.html
docs/CHANGELOG.md

Fixed input example was not working with field options.
Closes #2348
- Pull this branch and build/run the demoapp
- Navigate to http://localhost:4000/components/contextmenu/example-field-options.html
- Open the field options data for Input SM
- Open the field options data for Input LG
- Focus should disappear on the previous field

2348 - Fix input example was not working with field options

---

src/components/accordion/accordion.js
src/components/popupmenu/popupmenu.js

The popup close method, should close all the menus including the submenus. 
The accordion has two calls to closePopups(e), and one does not pass the event, so this should be checked before running any methods.
Closes #2371 
1. Go to 'http://localhost:4000/components/accordion/test-with-contextmenu.html'
2. Click on the more button on the page and set the color
3. Click on the Personal accordion item to expand
Other checks include leaving the more button menu open and using the accordion, and using the accordion's popup, right click on the header and then using the accordion while the popup …

2371 - PopupMenu: SubMenu still have is-open class after selection

---

src/components/colorpicker/_colorpicker.scss

The large color picker's individual elements are stacking right before the 480px breakpoint where they become responsive. This PR increases the breakpoint at which they become responsive and prevents the stacking.
Closes #1995.
Relates to #2123.
- Pull branch and run app
- Visit http://localhost:4000/components/colorpicker/example-sizes.html
- ensure all colorpickers work as expected and are responsive to smaller breakpoints.
- Visit http://localhost:4000/components/form/example-inputs.html
- ensure the colorpicker acts responsively within the grid
- Visit any other colorpicker pages in …

1995 - Colorpicker large cut off FAILED QA

---

app/views/components/datagrid/test-columns-min-max-widths.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Request a mechanism to constrain a column width, as this is useful for textarea columns to allow for some wrapping.
Closes #2313 
1. Goto 'http://localhost:4000/components/datagrid/test-columns-min-max-widths.html'
The Description column has a min and max constraint
2. Edit any description so that it is wider than 550 px, the maximum constraint value.
3. Page to next page 
4. Page to next page 
5. Change the edited description to a shorter description
The datagrid has stretchColumnOnChange enabled so the resize can happens on the change. (The column will only shrink on paging)

2313-Add minWidth and maxWidth to the columns

---

app/views/components/modal/test-toolbar.html

This new test page serves to demonstrate that the first focused item in a modal with a toolbar and a datagrid is the first non-disabled toolbar button.
Resolves #2026.
- Visit http://localhost:4000/components/modal/test-toolbar.html
- Click "Open Modal"
- Observe the first focused and tabbable item is the first non-disabled button in the toolbar.
¿- [ ] An e2e or functional test for the bug or feature.?
¿- [ ] A note to the change log.?

2026 - Modal: Tabbing initial focus

---

app/views/components/datagrid/example-custom-toolbar.html
app/views/components/datagrid/example-drilldown.html
app/views/components/datagrid/example-paging-client-side.html
app/views/components/datagrid/example-paging.html
app/views/components/datagrid/example-reorder.html
app/views/components/datagrid/test-editor-dropdown-source.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/dropdown/dropdown.js
test/components/datagrid/datagrid.e2e-spec.js

When using serverside filtering and a multiselect as the grid is filtered the header row would reload and the context/data in the multiselect would fail. To fix it made a fix to handle arrays in dropdown.js and made loadData not reload the header the majority of the time except for init.
Also while testing all examples did some light cleanup.
**Impact**:
- Full regression test of dropdown and datagrid and multiselect
- @Sovia please test this in landmark
Fixes #2383 
- go to http://localhost:4000/components/datagrid/test-editor-dropdown-source
- open the filter dropdown in the header and …

2383 - Fix for Multiselect filter issues [v4.19.x]

---

src/components/tooltip/tooltip.js

The tooltip on dropdown cells was generating an error with null markup on IE in some very specific situations in landmark.
Fixes #2403 
- this issue was verified in landmark was unable to make a test
- test tooltip examples a bit for any hidden issues
~~- [ ] A note to the change log.~~ Need first 4.19.3 issue merged first.

2403 - Fix an undefined error on IE [v4.19.x]

---

app/views/components/tooltip/test-chart-ajax-tooltip-bar.html
app/views/components/tooltip/test-chart-ajax-tooltip-column.html
src/components/tooltip/tooltip.js

The fix to #2405 caused a minor regression on the focus tooltips. This fixes both issues
Fixes #2415 
Caused by #2405
- re-test #2405 (nothing to test really the fix was verified by @pwpatton )
- go to http://localhost:4000/components/tooltip/example-trigger-focus.html
- click the button 
- tooltip should show because the button is focused , note that there is no focus state on click by design
- tab into the button
- tooltip should show as well

2415 - Fix both the undefined error on tooltip and an new bug on focus tooltips [v4.19.x]

---

docs/CHANGELOG.md
src/components/editor/editor.js

When using the tab key to indent in the editor the cursor will break out of the editor after doing the indent. This fixes that issue.
Fixes #2421 
- go to http://localhost:4000/components/editor/example-index.html
- put cursor at the bottom and click the number list icon
- type something and hit enter
- hit tab to do an indent (the editor used to loose focus here)

2421 - Fix a bug using tab to indent in editor

---

app/views/components/datagrid/example-placeholder.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.formatters.js

Able to use the placeholder on additional Formatters:
* DropDown
* Lookup
* Decimal
Closes #2408 
1. goto 'http://localhost:4000/components/datagrid/example-placeholder.html'
2. A placeholder is visible on the additional Formatters

2408 - Datagrid: placeholder on additional Formatters

---

app/views/components/dropdown/test-long-text.html
docs/CHANGELOG.md
src/components/dropdown/dropdown.js

Fixed ellipsis was not working when use firefox new tab with dropdown.
Closes #2236
- In Firefox, create a new tab (Ctrl-T)
- Paste http://localhost:4000/components/dropdown/test-long-text.html into the address bar
- Press Enter
- The dropdown should display with ellipsis
- Using F5 to refresh it should keep display with ellipsis

2236 - Fix ellipsis was not working with dropdown

---

app/views/patterns/builder-nosidebar.html
app/views/patterns/builder-subtitle-test.html
app/views/patterns/builder-wizard.html
app/views/patterns/builder.html

This PR Fixes a demoapp issue where a Header Hamburger button is present on the "detail" area of the Builder pattern while on larger form factors.  This button doesn't have any functionality in this pattern while on the "desktop" view.  It should only be present when the viewport lands on the "detail" area while in "tablet"/"phone" view, where it acts as a "Go Back" button.
Additionally, this PR restores the navigation ability that used to be present when clicking an item on the "list" side while looking at the "phone"/"tablet" views.
Closes #2115 
- Look at all …

2115 - Hide the header hamburger on large-form-factor Builder-pattern screens

---

src/components/datagrid/datagrid.js

**Explain the details for making this change. What existing problem does the pull request solve?**
#2429 was closed before I was able to review and the fix missed some other situation not put on the initial ticket, (sorting and filtering).
This is a rework of #2404 , so that it will do just what it intended, not to resize the columns when the multi-select dropdown is opened.
**Related github/jira issue (required):**
Fixes #2428
**Steps necessary to review your pull request (required):**
retest #2404 
But specifically go to http://localhost:4000/components/datagrid/test-editor-dropdown-source
open the header multiselect and pick some items -> the columns should not change size when selecting
go to http://localhost:4000/components/datagrid/test-paging-select-indeterminate-single.html
Sort …

2428 - Improve a fix for re-measuring datagrid columns (2)

---

app/views/components/datagrid/test-editable-paging-validation.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Remove the row error information if the row has been removed.
Closes #2436
1. Go to 'http://localhost:4000/components/datagrid/test-editable-paging-validation.html'
2. Select a row and also remove the Product Name 
3. Page to the next page, so that the nonVisibleCellErrors created and visible
4. Click on the remove button to remove the row 
You can test creating multiple error and only removing some on another page.

2436 - Remove nonVisibleCellErrors when rowRemove is called

---

app/src/index.scss
src/components/bar/bar.js
src/components/column/column.js
src/components/line/line.js
src/components/pie/pie.js
src/components/radar/radar.js
src/components/treemap/treemap.js

When i first fixed #2058 things worked but https://github.com/infor-design/enterprise/pull/2373/files#diff-bc5de2d974df82ad6e9bc8bc7933773dR17 added an extra set of variables that caused the colors to be wrong. Fixed this. Also fixed that the theme change in the switcher didnt work.
Fixes #2058 
- clean the `app/dist` folder
- stop server and run `npm run quickstart` so the demo app is generated properly
- `npm run start` again
- go to http://localhost:4000/components/bar-stacked/example-index.html?theme=uplift and make sure that the legend color is correct
- go to …

2058 - Fix theme color issues in charts

---

app/views/components/datagrid/example-keyword-search.html
app/views/components/datagrid/test-editor-dropdown-source.html
app/views/components/datagrid/test-timezone-formats.html
src/components/datagrid/datagrid.js
src/components/locale/locale.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/locale/locale.func-spec.js

It was found that the filter would only run every second time do to some bad flag logic. Found this code wasn't needed so removed to fix. While running tests I found there was a time-bomb bug in the timezone code so fixed this (when running at certain times (8:58 fx).
Fixes #2444 
http://localhost:4000/components/datagrid/test-timezone-formats?layout=nofrills&locale=nl-NL
- page should show timezones at 00:00
http://localhost:4000/components/datagrid/test-editor-dropdown-source
- in the text field type com then enter and should see a toast
- in the text field type "" then enter and should …

2444 - Fix an issue where filtering will only run every second time [v4.19.x]

---

app/views/components/popupmenu/example-submenus.html
app/views/components/popupmenu/test-scrolling.html
docs/CHANGELOG.md
src/components/popupmenu/_popupmenu.scss
src/components/popupmenu/popupmenu.js

We had some older rules in for IOS workarounds that caused popupmenus to not scroll and submenus to not show on IOS. This issue fixes these things.
Fixes #1928
Fixes #645
Fixes #2362 (duplicate)
- go to http://localhost:4000/components/popupmenu/test-scrolling on an IOS sim or browser stack
- if the menu isnt cut off try and go to landscape mode
- click the button to open the menu
- attempt to scroll the list up and down (will now work)
- go to http://localhost:4000/components/popupmenu/example-submenus.html also  on an IOS sim or browser stack
- click the submenus and they should open now …

1928 - Fix popupmenu scrolling and submenus so that they will work on IOS

---

app/views/components/images/example-index.html
docs/CHANGELOG.md
src/components/images/_images.scss

This provides a solution for the desire to have a focus-state on an image where the width and height are not defined by the CSS. Creates a class `.image-auto` for this purpose and places it in the example page for demonstration purposes.
History here: https://github.com/infor-design/enterprise/issues/2025#issuecomment-506010618
Close #2025 . 
- Visit http://localhost:4000/components/images/example-index.html
- Ensure `.image-auto` is focusable.

2025 - Images tabbable .image-auto

---

app/views/components/personalize/test-state.html
app/views/includes/head.html
docs/CHANGELOG.md
src/components/header/header.js
src/components/personalize/personalize.js

#2335 was failed because when the url params are used the checkbox in the theme switcher were incorrect. This fixed that.
Fixes #2335 
- pull this and build normally
- go to a url with the parms such as http://localhost:4000/components/personalize/example-form.html?theme=soho&variant=contrast
- open the theme switcher in the top right and make sure the checkboxes are correct
- try different theme/variant combos

2335 - Fix that makes the theme switcher to reflect whats sent in the url params

---

app/views/components/dropdown/test-filter-types.html

This PR builds upon PR #2388 and just improves a Dropdown-specific test that demonstrates filter modes.  The test now designates between "word" and "phrase" startsWith filters.  
Closes #1606 
- Navigate to http://localhost:4000/components/dropdown/test-filter-types.html
- Test each Dropdown by typing "Co" into their search inputs:
- the Contains filter should have 6 results
- the PhraseStartsWith filter should have 2
- the WordStartsWith filter should have 3
- An improved visual test

1606 - Improve test for dropdown filter types

---

app/views/components/bar/test-custom-tooltips.html
docs/CHANGELOG.md
src/components/bar/bar.js

Add the same tooltip dynamic functionality to the bar chart type
Closes #2447
Goto 'http://localhost:4000/components/bar/test-custom-tooltips.html'
Hover on the first item, as the custom tip will show the value.

2447 - Bar: Unable to use the {{value}} expression in the tooltip

---

docs/CHANGELOG.md
src/components/tabs/_tabs.scss

The more tabs button is not styled as disabled at responsive breakpoints.
Closes #2347 .
- Visit http://localhost:4000/components/tabs/example-enable-disable.html#programmatic-tabs-disabled
- Click the `Disable Entire Tab Control` button
- ensure at responsive breakpoints that the `.tab-more` button is appropriately styled when tabs are disabled

2347 - Tabs: responsive more tabs button not disabled

---

app/views/components/images/example-index.html

#2025 failed QA because the placeholder images were not focusable, missing a tabindex="0".
QA fail reported here: https://github.com/infor-design/enterprise/issues/2025#issuecomment-507735013
Closes #2025 
- Visit http://localhost:4000/components/images/example-index.html
- ensure all images _and placeholders_ are focusable/tabbable

2025 - Images: Make tabbable - FAILED QA

---

docs/CHANGELOG.md
src/components/popupmenu/popupmenu.js
test/components/colorpicker/colorpicker.e2e-spec.js

When in RTL, the colorpicker left and right arrows advance opposite to their native direction. This PR fixes that issue by adding a RTL check and swapping the key events appropriately.
Closes #2352 .
- Visit http://localhost:4000/components/colorpicker/example-index.html & http://localhost:4000/components/colorpicker/example-index.html?locale=ar-EG (RTL)
- Open colorpicker, focus into colorpicker menu, ensure left and right arrows advance correctly (left is left and right is right)

2352 - RTL: Colorpicker menu arrows advance oppositely

---

app/views/components/datagrid/example-mixed-selection.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/calendar/calendar-api.func-spec.js
test/components/datagrid/datagrid-selection.func-spec.js

The selected event fires when the loadData method is called because unSelectAllRows is called to deselect rows. This caused issues as the event is "false". This PR fixes that.
Also removed a fdescribe from my last pr.
Fixes #2470 
- This is covered by a functional tests
- Added a manual simple test:
- open console
- open page http://localhost:4000/components/datagrid/example-mixed-selection.html
- should not see any selected events in the console
- try to select rows (should see the event)
- unselect all (should see the event)

2470 - Fix a bug to prevent the selected event from firing on load

---

app/views/components/popupmenu/test-malformed-popupmenu.html
docs/CHANGELOG.md
src/components/popupmenu/popupmenu.js
test/components/popupmenu/popupmenu.e2e-spec.js

This PR fixes an error found in the Landmark client where the Popupmenu doesn't gracefully handle a missing `<ul>` element while submenus are being constructed or reconstructed. 
Closes #2458 
- Open http://localhost:4000/components/popupmenu/test-malformed-popupmenu.html
- Examine a dev tools console to ensure there are no JS errors when the page loads.
- Click the "Open me" button.
- Hover your mouse over the lowest menu item in the list (which contains a malformed submenu)
- Ensure there are no JS errors after hovering.
This is also covered by a new set of …

2458 - Popupmenu: Fix error when submenu wrappers are defined, but submenus are missing

---

docs/CHANGELOG.md
src/components/tabs/tabs.js

The current code checks for the length of existing tabs and adds a new tab with an ID based off that length. When a tab is deleted, this is not accounted for, thus leaving the function to add a tab susceptible to duplicate tab creation and double focusing. This PR introduces an independent count to alleviate this issue.
This is indicated as a `demo-app-bug`in the original issue but I think it's a legitimate bug.
Closes #2345 .
- Visit http://localhost:4000/components/tabs/example-add-tab-button.html
- Choose the first radio button option
- Add and delete new tabs at …

2345 - Tabs: new tab duplication

---

docs/CHANGELOG.md
src/components/bar/bar.js
src/components/column/column.js
src/components/personalize/personalize.js
src/components/personalize/personalize.styles.js

There was Failed QA because tooltip for bar chart was stop working with some other change, so this PR will fix it and contrast color for tooltip text.
Closes #2097
- Navigate to http://localhost:4000/components/homepage/example-hero-widget.html
- Click top right `...` action button to change theme/colors
- See tooltip should show with bar chart
- See the tooltip text color should be easy readable

2097 - Fix tooltip with bar and column charts

---

docs/CHANGELOG.md
src/components/tabs/tabs.js

After removing two tabs at once in the example, a tab selection is not made and the focus remains outside of any "existing" tabs. We now invoke the `select()` method inside the `hide()` method to ensure proper focusing.
Closes #2346 .
- Visit http://localhost:4000/components/tabs/example-hidden-tabs.html
- Follow instructions in issue (also below)
- Click "Show Hidden Tabs" button
- Click "Tab # 6"
- Click "Hide Tabs 2 and 5" button
- Ensure focus remains with "Tab # 6"
~- [ ] An e2e or functional test for the bug or …

2346 - Tabs: wrong focus after hiding

---

app/views/components/pager/example-standalone.html
docs/CHANGELOG.md
src/components/pager/pager.js
src/components/popupmenu/popupmenu.js
test/components/colorpicker/colorpicker-events.func-spec.js

This PR fixes a couple of Pager issues:
- We added a Popupmenu-specific setting for the Page Size Selector button in #2354, where it would've been ideal to pass an entire object for Popupmenu settings for the button.  Due to time constraints and infrastructure needed on the NG side, we weren't able to add the full settings object in that previous issue.  This PR adds the full object on the EP side, deprecates the old setting with a warning message, and gracefully handles switching the old setting to the new one internally.  The new setting is also documented on the Pager component docs.
- @fitzorama discovered a memory leak that began occurring with the previous change.  This PR fixes the …

2356/2484 - Deprecate Pager setting for attachToBody, fix Pager memory leak

---

app/views/components/form-compact/example-index.html
app/views/components/form-compact/example-list-detail.html
docs/CHANGELOG.md
src/components/datepicker/_datepicker.scss
src/components/form-compact/_form-compact-uplift.scss
src/components/form-compact/_form-compact.scss
src/components/form-compact/form-compact.js
src/components/lookup/_lookup.scss
src/components/timepicker/_timepicker.scss
src/components/typography/_typography-uplift.scss
src/core/_config.scss
test/components/timepicker/timepicker.e2e-spec.js

This PR: 
- brings the style for the Compact Form into alignment with recent design iterations, as outlined in infor-design/design-system#370.  The styles shrink the input field fonts, change the header style, and add a gutter between nested grids (see [V5 Notes](https://paper.dropbox.com/doc/Compact-Form--AgGu0QJk83oONJo1DNMYEB_FAg-R8idPCwaQcbGBbIZVX3Md#:h2=V5:) in Dropbox Paper)
- Allows for the use of checkboxes/radios in the compact form with proper alignment/font sizes.
#2193
- Pull this branch, build, run app.
- Navigate to http://localhost:4000/components/form-compact/example-index.h …

2193 - Add Checkbox and Radio field types to the Compact Form

---

docs/CHANGELOG.md
src/components/lookup/lookup.js

The browser autocomplete is interfering with the lookup. This PR adds `autocomplete="off"` to the lookup input field to prevent it from appearing and interfering.
Closes #2366 .
Relates to #2364 which will be resolved in a separate PR.
- Visit http://localhost:4000/components/lookup/example-index.html and any related lookup example pages
- Ensure `autocomplete="off"` is present in the markup of all lookup inputs.

2366 - Lookup: Listbox and browser autocomplete conflict

---

docs/CHANGELOG.md
src/components/compositeform/compositeform.js
src/components/field-options/field-options.js
src/components/popdown/popdown.js
src/components/tooltip/tooltip.js
src/patterns/stepprocess/stepprocess.js
src/utils/deprecated.js

Add a warning and change log entry and console log note for some components we hope to remove and deprecate. Added a new `warnAboutRemoval` function for better explanation. Also found a bug that cropped up on tests so added a safety check.
Fixes part of #1476 
- open http://localhost:4000/components/field-options/example-index.html  and look for the warning in the console
- open http://localhost:4000/patterns/stepprocess and look for the warning in the console
- open http://localhost:4000/components/popdown/example-index.html and look for the warning in the console
- open …

1476- Add some warnings for future deprecated components

---

docs/CHANGELOG.md
src/components/toolbar-flex/_toolbar-flex.scss

The flex toolbar has an `height: 100%` that caused some issues in some layouts. Removed this without negative effects.
Fixes infor-design/enterprise-ng#474
- pull this branch and build
- restest http://localhost:4000/components/toolbar-flex for issues
- can also test https://github.com/infor-design/enterprise-ng/pull/549

474- Fix an issue with height 100% in flex toolbar

---

test/components/multiselect/multiselect.e2e-spec.js

This PR attempts to make a randomly-failing Multiselect e2e more stable by adding a `sleep()` call.
N/A
The e2e tests should pass with no issue.  We should probably just run the tests on this PR several times to confirm it works.

N/A - try to fix Mutliselect e2e test race condition during nightly build

---

docs/CHANGELOG.md
src/components/dropdown/dropdown.js

This fixes memory leaks in dropdown caused by event listeners left open. Screenshot below shows a heap comparison with the original vs this fix and you'll notice a bunch of other objects aside from Dropdown and detached elements now being GC'd properly.
Closes #2493 
1. Go to http://localhost:4000/components/dropdown/test-destroy.html
2. Open the Memory tab in Chrome Developer Tools
3. Click on 'Destroy Dropdown One' and 'Destroy Dropdown Two'
4. Click the 'Collect garbage' button to make sure the browser has collected garbage
5. Click the 'Take snapshot' button to see the memory heap.
6. …

fixes #2493 dropdown memory leak issue

---

src/components/toast/toast.js

Fixed issue for toast with responsive view when saved position is in view and after loads while off the page.
Closes #1876
- Navigate to http://localhost:4000/components/toast/example-draggable.html
- Open the browser wider
- Click on button `Show Toast Message` to open toast
- Drag toast to the far right
- Click `X` in toast or wait for time out to close the toast
- Close the browser window and navigate back to same page
- Resize the browser to narrow
- Click on button `Show Toast Message` to open toast
- See toast should open in view area

1876 - Fix saved position with responsive view for toast

---

app/views/components/datagrid/test-editor-dropdown-source-prior-filter.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed method setFilterConditions() was not working for multiselect filter with datagrid.
Closes #2414
- Navigate to http://localhost:4000/components/datagrid/test-editor-dropdown-source-prior-filter.html
- On page load see the filter for column `Action`
- Should be populated (`Place On-Hold, Request Review`)
- And grid rows should not be filtered because the setting disableClientFilter is on.

2414 - Fix set filter conditions only for multiselect with datagrid

---

app/views/components/datagrid/example-grouping-paging.html
src/components/datagrid/datagrid.js

Fixed method selectAll() was not working on 2nd page with groupable datagrid.
Closes #1796
- Navigate to http://localhost:4000/components/datagrid/example-grouping-paging.html
- Go to 2nd page
- Click on `Select all` checkbox in header to select all
- See it should select all rows on this page

1796 - Fix select all on 2nd page with groupable datagrid

---

src/themes/theme-uplift-light.scss

This PR further increases the difference in color between an input field's placeholder text and actual text.  In the case of the Multiselect component, this difference can be seen on examples that display placeholder text.
Closes #2528
- Open http://localhost:4000/components/multiselect/example-placeholder.html?theme=uplift&variant=light&colors=0563C2
- Examine the difference between the "Select A State" placeholder text, and a selected option.  Make sure there is a significant difference between the text colors.
- If you have the `aXe` browser plugin, …

Multiselect - Increase difference in color between placeholder and selected items [v4.20.x]

---

docs/CHANGELOG.md
src/components/personalize/personalize.js

There was Failed QA because some dark text color, so this PR will update some of the personalization colors.
Closes #2539
- Navigate to http://localhost:4000/components/list?theme=uplift
- Click top right `...` action button to change theme/colors
- Inspect text color should be light and readable for Turquoise, Slate, and Graphite

2539 - Fix some personalization text colors [v4.20.x]

---

docs/CHANGELOG.md
src/components/locale/locale.js

This fixes a race condition in locale when using a locale that shares strings. For example es-US and ar-SA (sharing es and ar respectively). only way i could fix was a conditional timeout. Originally noted on #2365
Fixes #2540 
- http://localhost:4000/components/locale/test-translated-strings.html?locale=ar-SA
- http://localhost:4000/components/locale/test-translated-strings.html?locale=es-ES
- http://localhost:4000/components/locale/test-translated-strings.html?locale=es-US
- try loading all these with a fresh cache (CTRL + Reload)
- ensure pages load
- ensure all tests pass
**Included in …

2540- Fix a race condition loading messages [v4.20.x]

---

app/views/components/datagrid/test-editor-dropdown-source-prior-filter.html
test/components/listbuilder/listbuilder-api.func-spec.js

Fixed example page for method setFilterConditions() was not working for ie11 with datagrid.
Closes #2414
- Use ie11
- Navigate to http://localhost:4000/components/datagrid/test-editor-dropdown-source-prior-filter.html
- On page load see the filter for column `Action`
- Should be populated (`Place On-Hold, Request Review`)
- And grid rows should not be filtered

2414 - Fix example page was breaking on ie11 with datagrid [v4.20.x]

---

src/components/modal/_modal-uplift.scss
src/components/modal/_modal.scss

This PR makes a better change to Modals that consist of single line messages.  The previous changes -- part of #2318 -- mistakenly broke scrolling on all modals.  This PR reverses that change and adds a bit of padding to prevent the scrollbar's appearance unless it's necessary.
- Related to #2318 
- Closes #2547 
- Pull this branch and run the app.
- Open http://localhost:4000/components/modal/test-full-content-buttons.html?theme=uplift
- Shrink the browser window so that the inner contents of the modal are scrollable.  The modal contents should scroll up and down as expected.
- Open …

2547 - fix modal scrolling

---

app/views/components/datagrid/test-lookup-with-mask.html
app/views/components/lookup/example-index.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.editors.js
src/components/lookup/lookup.js
test/components/bar/bar-grouped.e2e-spec.js

In a very specific example with datagrid, new rows and lookup with a mask. The value is cleared when selected. This issue fixes it. Also added a possible fix for a test i saw fail and an example of a lookup mask to the lookup page for testing, there wasnt any issue with it but i kept it in for reference.
Fixes #2305 
- open an IE VM
- open http://localhost:4000/components/datagrid/test-lookup-with-mask in IE11
- click add row to top 
- click into the product id cell with zero in it to focus
- click the lookup to open and pick a value (should now select)
- also test lookup editing with …

2305 - Fix lookup so it works when used with mask/datagrid

---

docs/CHANGELOG.md
src/components/searchfield/_searchfield-toolbar.scss

The close icon in a toolbar searchfield defers pointer events when the class `is-open` is not present. This PR changes the class for this rule to `active` to ensure all toolbar searchfield close icons are considered and also changes the approach to `display: none;` from `pointer-events: none;` to ensure there is no display of the close icon that is potentially uninteractable.
Also tested the pages on this PR as this is where the rule in question was created.
https://github.com/infor-design/enterprise/pull/2086
Closes #2578 .
- Pull branch, build and run app
- Visit …

2578 - Searchfield: Close icon [v4.20.x]

---

app/views/components/datagrid/example-paging-client-side.html
app/views/components/datagrid/example-paging.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js

QA found some regressions with paging and remove row and i fixed the behavior. For serverside paging removeRow wont work so removed the clear from it but made it work on the other client side examples.
Fixed #2590 
- select and remove row 4
- go to page 2
- select and remove row 7
- will now go to page one
- go to http://localhost:4000/components/datagrid/example-paging
- select a row(s) -> there is now no Contextual toolbar you cannot clear here
- http://localhost:4000/components/datagrid/example-paging-client-side
- …

2590  - Fixing paging and removeRow in datagrid [v4.20.x]

---

app/views/components/input/test-comparison-of-fields.html
docs/CHANGELOG.md
src/components/datepicker/_datepicker-uplift.scss
src/components/dropdown/_dropdown-uplift.scss
src/components/lookup/_lookup-uplift.scss
src/components/searchfield/_searchfield-uplift.scss
src/components/searchfield/_searchfield.scss
src/components/timepicker/_timepicker-uplift.scss

This PR fixes a handful of minor text/icon/padding alignments on the Searchfield component.  This PR also adds a test page that implements a Searchfield alongside of other complex components so we can better see it on a "form" environment.
Additionally, there are minor Uplift-centered tweaks to the style of the components included on that test page.
Closes #2612
- Open http://localhost:4000/components/searchfield/example-index?theme=uplift in various browsers.  Ensure the alignment looks good between the icon/text.  Also check RTL.
- Open …

2612 - Improve Uplift Searchfield styles [v4.20.x]

---

app/views/components/datepicker/test-placeholder.html
docs/CHANGELOG.md
src/components/datepicker/_datepicker.scss
src/components/datepicker/datepicker.js

Fixes two issue in datepicker, one is an IE Edge placement issue with the title. The second is a mask issue on the range date picker.
Fixes #2598 
Fixes #2597 
2598
- go to http://localhost:4000/components/datepicker/example-index on IE edge and/or IE 11
- Look at the title (month year) layout should look similar to chrome
- also test http://localhost:4000/components/datepicker/test-no-month-year-picker.html
2597
- go to http://localhost:4000/components/datepicker/example-range on IE edge or IE 11
- in the first range picker "Range - No Initial value" select any range
- click out of the …

2598/2597 - Fix range picker mask showing 'loc' and title placement [v4.20.x]

---

docs/CHANGELOG.md
src/components/datepicker/datepicker.js
src/components/monthview/monthview.js

Fixed some range issues with datepicker.
Closes #2595
Closes #2599
- Navigate to http://localhost:4000/components/datepicker/example-range.html
Issue: 1
1. Open picker `Range - No Initial value`
2. Today's date should be highlighted with blue background
3. Click on footer button `Select`
4. See it should be able to select this date
5. Picker still open till you pick the 2nd date
Issue: 2
1. Refresh the page
2. Open picker `Range - No Initial value`
3. Click on any date and it will select the date
4. Now use arrow key or hover to any date
5. You …

2595/2599 - Fix range issues with datepicker [v4.20.x]

---

src/components/contextualactionpanel/_contextualactionpanel.scss
src/components/header/_header.scss
src/components/masthead/_masthead.scss

This PR adds some CSS rules for the height of a Flex Toolbar when contained by Headers, Mastheads, and Contextual Action Panels.  A previous change to fix a height-related bug in Flex Toolbars caused them to become misaligned in these cases.  The fix provided satisfies the original fix and makes vertical centering work again.
N/A
Pull this branch, run the app, and check the Toolbars on the following pages to ensure they appear vertically-centered within their containers:
- http://localhost:4000/components/contextualactionpanel/example-workspaces.html
- …

N/A - Fix vertical centering of Flex Toolbar contained by header components [v4.20.x]

---

docs/CHANGELOG.md
src/components/listview/listview.js

update render function to reflect filtered status of items
highlight marks should be cleaned before new filter action, otherwise, new filter action would fail.
Fixes #infor-design/enterprise-ng/issues/466 
1. build sohoxi.js
1. update node_modules\ids-enterprise\dist\js\sohoxi.js in enterprise-ng
1. run command: npm start
1. open http://loalhost:4200 in a browser, and open ListView page, enter 063003 in search box, make sure only item with text 063003  would be displayed, other items are not displayed.
1. then change 063003 to 0, make sure all items are displayed and also highlight marks …

466 - Listview: Search not working the same in NG

---

app/views/components/fileupload-advanced/test-custom-errors.html
docs/CHANGELOG.md

Added custom errors example page with fileupload advanced.
Closes #2620
- Navigate to http://localhost:4000/components/fileupload-advanced/test-custom-errors.html
- Try to create the errors and see the error strings as
- Allowed File Types: `Only files can be upload (.jpg, .png or .gif)` 
- Max File Size: `(2 MB) Max file size allow to be upload` 
- Max Files In Process: `Max (3) files can be process at once`

2620 - Add custom errors example page with fileupload advanced

---

app/views/components/circlepager/example-index.html
docs/CHANGELOG.md
test/components/circlepager/circlepager.e2e-spec.js

Removed unnecessary `paddings (right, left, bottom)`. Having these paddings has an impact on mobile and it affects the script and tends to iterate. (Check the elements).
Closes https://github.com/infor-design/enterprise/issues/2589
- Pull this branch and run the app
- Navigate to http://localhost:4000/components/pager/example-circlepager.html
- Resize the browser to mobile or use mobile device
- You should able to see the circle pager

2589 - Fix circle pager not showing on mobile

---

src/components/dropdown/dropdown.js
test/components/datepicker/datepicker.e2e-spec.js

We missed checking having a dropdown opened and then destroying. There was an additional memory leak which i fixed.
Fixes #2493 further.
- go to http://localhost:4000/components/dropdown/test-destroy.html
- open each dropdown once and close
- click both destroy buttons
- open the Memory tab in Chrome Developer Tools
-  click the 'Collect garbage' button to make sure the browser has collected garbage
-  click the 'Take snapshot' button to see the memory heap.
-  Filter the results in the snapshot to 'dropdown' and ensure you see nothing in memory
No Change …

2493 - Fix memory leak on open dropdowns [v4.20.x]

---

src/components/spinbox/_spinbox-uplift.scss

This PR fixes styling [problems discovered](https://github.com/infor-design/enterprise/issues/2612#issuecomment-519470284) while doing Q/A on #2612
Closes #2612 
- Open http://localhost:4000/components/input/test-comparison-of-fields.html?theme=uplift on various browsers.  Also try `rtl` by adding `&locale=ar-EG` to the end of the URL.
- Ensure the Spinbox's vertical text and button alignment in the field appears to match the others.

2612 - Fix text/icon alignment on Spinbox fields [v4.20.x]

---

docs/CHANGELOG.md
src/components/lookup/lookup.js
src/components/modal/modal.js

Fixed memory leak issues with lookup and modal after destroy.
Closes #2494
Closes #2497
Lookup
- Navigate to http://localhost:4000/components/lookup/test-destroy.html
- Open lookup and pick any value
- Click on button `Destroy`
- It should remove lookup icon
- There should left text-filed and picked value in it
- Click to `Memory` tab in developer tools
- Click the `Collect garbage` garbage bin icon
- It will collect all the garbage from browser
- Click the button `Take snapshot` to see the memory heap
- After the scan …

2494/2497 - Fix memory leak with lookup and modal

---

docs/CHANGELOG.md
scripts/build.js
src/components/searchfield/_searchfield.scss
src/components/toolbar-flex/_toolbar-flex.scss

This PR fixes a bug in the Custom Builder that renders it unable to complete a build when including files with more than one period in the filename, such as `toolbar-flex.item.js`.
Closes #1322 
- Run a custom build in "dry-run" mode that only includes Autocomplete and Flex Toolbar.  Do this  by running the following command:
```sh
npm run build -- --components=autocomplete,toolbar-flex --dry-run
```
- Inspect the output of the file `temp/components.js` file.  Make sure it correctly includes the export for Flex Toolbar, but not the Flex Toolbar Item:
```js
// …
```

1322 - Fix custom build errors when including files with extra punctuation

---

app/views/components/datagrid/test-editable-onkeydown.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-settings.func-spec.js
test/components/datagrid/datagrid.e2e-spec.js

While addressing 536 is was noted that the datagrid onKeydown event only fired on tab. Expanded this to fire on any key
Fixes #536 (will add a PR for the NG part)
- go to http://localhost:4000/components/datagrid/test-editable-onkeydown.html
- click in any cell and type
- any key you type will omit an event shown in the toast and veto (nothing will happen otherwise as the event is vetoed)

536 - Make the onKeydown fire on any type of key

---

docs/CHANGELOG.md
src/components/slider/slider.js

The colors object is using outdated theme names (pre introduction of uplift) and returning undefined.
Closes #2647 
- Visit http://localhost:4000/components/slider/example-colors-and-ticks.html and http://localhost:4000/components/slider/example-vertical.html
- ensure the slider demo works as expected

2647 - Slider: Colors object uses old theme names

---

app/views/components/toast/test-positions.html
docs/CHANGELOG.md
src/components/toast/toast.js
test/components/toast/toast.e2e-spec.js

Fixed memory leak issues with Toast control after destroy.
Closes #2634
- Navigate to http://localhost:4000/components/toast/example-index.html
- Click on button `Show Toast Message` to open toast
- Wait or click `X` for the toast message to be closed (which call the destroy method)
- Click to `Memory` tab in developer tools
- Click the `Collect garbage` garbage bin icon
- It will collect all the garbage from browser
- Click the button `Take snapshot` to see the memory heap
- After the scan completes, filter the result in …

2634 - Fix memory leak with toast

---

app/views/components/dropdown/test-updating-long-text.html
docs/CHANGELOG.md
src/components/dropdown/dropdown.js
src/components/tooltip/_tooltip.scss

Fixed tooltip on all browsers and ellipsis on firefox, ie11 was not showing with long text after updating dropdown.
Closes #2534
- Navigate to http://localhost:4000/components/dropdown/test-updating-long-text.html
- Both Dropdowns should render empty
- Click on button `Update`
- Now it should fill with long text
- It should show ellipsis on all browsers
- On hover it should show the tooltip

2534 - Fix tooltip and ellipsis after update dropdown

---

docs/CHANGELOG.md
src/components/editor/editor.js

Fixed clear formatting was causing to break while switch mode on Firefox with Editor.
Closes #2424
- Use Firefox
- Navigate to http://localhost:4000/components/editor/test-source-formatter.html
- Editor should open in source mode
- Click button `VISUAL` to go to visual mode
- Select all then click button `Clear Formatting`
- Click button `HTML` to go back to source mode
- See content, should have proper indentation

2424 - Fix clear formatting on firefox with editor

---

app/views/components/popupmenu/test-flex-toolbar.html

This PR adds a quick typecheck to a new test added, preventing console errors when clicking buttons on the test page in a specific order.
Closes #2664 
- Pull this branch, run the app
- Open http://localhost:4000/components/popupmenu/test-flex-toolbar.html
- Click the "Destroy Menu Button" button
- Click the "Trigger `updated()` on Menu Button Only" butotn
- Open a dev tool console. Ensure that there are no errors on the page.

2664 - Add typecheck to test [v4.21.x]

---

docs/CHANGELOG.md
src/components/datagrid/_datagrid-uplift.scss

Fixed short row height was misaligning in Uplift theme with Datagrid.
Closes #2717
- Navigate to http://localhost:4000/components/datagrid/example-list.html?theme=uplift&variant=light&colors=0563C2
- Click `...` three dot action button top of grid
- Set row height to Short
- Hover to any row
- See last column `Action Item`
- Should aligned properly

2717 - Fix misaligned short row with datagrid [v4.21.x]

---

src/components/applicationmenu/_applicationmenu-uplift.scss
src/components/cards/_cards-uplift.scss
src/components/charts/_charts.scss
src/components/checkboxes/_checkboxes.scss
src/components/editor/_editor-uplift.scss
src/components/header/_header-uplift.scss
src/components/input/_input-uplift.scss
src/components/radios/_radios.scss

This PR makes a few additional changes to the Uplift theme to satisfy some issues discovered during Q/A of v4.21.x.  It also takes the additional step of improving compatibility with IE11 by removing all `unset` properties in favor of other alternatives.
Closes #2541 
Pull this branch, run app, and check the following pages to make sure things look swell:
- http://localhost:4000/components/listview/example-index.html?theme=uplift
- http://localhost:4000/components/cards/example-group-action.html?theme=uplift
- http://localhost:4000/components/input/example-index.html?theme=uplift
- …

2541 - Additional Uplift Theme Improvements [v4.21.x]

---

package.json

Set chokidar to fix at 1.0.1 as 1.0.2 has issues in that fails as per https://github.com/paulmillr/chokidar/issues/855
Also removed the node version check on npm i for now as this fails on jenkins as that version is not there.
NA
- `rm -rf node_modules && npm i`
- start grunt watch
- save a js file and should reload

Fix dependency and build issue

---

docs/CHANGELOG.md
src/components/icons/icons.js
src/components/toolbar/toolbar.js

This PR makes a few tweaks to the Toolbar and Icon components that better suit the SPA-nature of Angular components.  Specifically, these tweaks fix the Contextual Action Panel bugs found in the Angular wrapper for that component.
- The Icon component was changed to prevent the storage of a full URL on the `use` setting when coupled with a base tag.
- The Toolbar component was changed to fix the condition that makes the conditions for destroying an invoked Searchfield to work better in an SPA lifecycle.
- Related to infor-design/enterprise-ng#594
- infor-design/enterprise-ng#604 depends on this PR.
**Steps necessary to review your pull request …

NG-594 - Improvements to Toolbar/Icon for Angular CAP Lifecycle

---

package.json
src/components/dropdown/dropdown.js
src/components/popupmenu/popupmenu.js

Fixes an issue where the layout broke when closing filter row popdowns (maybe similar problems elsewhere).
Also added the contents of https://github.com/infor-design/enterprise/pull/2727 so we do not have this issue on the 4.21.x branch.
Fixes #2709 
- go to http://localhost:4000/components/datagrid/example-filter.html
- open any filter row dropdown and close it
- layout should be ok and filter should work
- For good measure test the following as well for the same issue:
http://localhost:4000/components/datagrid/test-editable-time has error …

2709 - Fix a serious filter row issue [v4.21.x]

---

app/views/components/datagrid/test-overlaps-row-cell-indicators.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js

Fixed new row and dirty cell were not working with Datagrid.
Closes #2729
- Navigate to http://localhost:4000/components/datagrid/test-overlaps-row-cell-indicators.html
- Click on toolbar button `Add Row`
- Change cell values on the new row
- See for dirty indicator (yellow triangle) should show in changed cell
- Dirty indicator should not show if new row and first cell, because it has row status icon in this cell
- For this new row and first cell, dirty indicator just visually not showing on browser but it added to …

2729 - Fix new row and dirty cell with datagrid [v4.21.x]

---

app/views/components/datagrid/test-export-custom-separator.html
docs/CHANGELOG.md
src/utils/excel.js

Added support for separator to use custom string or object type with Export to CSV.
Closes #2490
- Navigate to http://localhost:4000/components/datagrid/test-export-custom-separator.html
- Click on each button to download CSV file with custom setting
- Open saved file with text editor to review the outcome

2490 - Add custom separator support with export to csv

---

src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js

QA spotted a regression with respect to which rows stay expanded in tree i caused in adding frozen columns + tree.
Fixes #2732 
- go to http://localhost:4000/components/datagrid/example-tree
- collapse: Follow up action with Acme Canada
- collapse:  Follow up action with Residental New York
- collapse:  Follow up action with Residental Baltimore
- expand:  Follow up action with Residental Baltimore -> Follow up action with Acme Canada and Follow up action with Residental New York should still be collapsed
- retest http://localhost:4000/components/datagrid/test-tree-frozen-columns.html
- …

2732 - Fix a regression in tree expansion [v4.21.x]

---

src/components/monthview/monthview.js

When clicking links in the new datepicker month/year view the NG app will restart.
Fixes #603 
- pull the branch and build
- copy the dist files to an ng node_modules/ids-enterprise folder (or use npm link)
- run the NG app to http://localhost:4200/ids-enterprise-ng-demo/datepicker
- open the standard date picker and go into the month/year view
- click links (year and month) and the app should not redirect
- scroll up and down and click links (year and month) and the app should not redirect
- smoke test picker functionality in EP as well …

603 - Prevent the redirects in NG on picker [v4.21.x]

---

docs/CHANGELOG.md
src/components/accordion/accordion.js
src/utils/lifecycle.js

Fixed two bugs seen in landmark:
1) The busy indicator would immediate close in angular / landmark when the app menu loads
2) The siftFor doing a expensive body selector would call once per accordion pane in the menu (180 times) which was slow on IE. Fixed this by adding a new parameter so its not called on app menu build.
Fixes #2767 
- test in landmark
- retest page http://localhost:4000/components/accordion/test-close-children-on-collapse.html
- pull this done and npm link or copy the dist to node_modules in ids-enterprise
- put a debug on the `siftFor` function and load …

2767 - Fix some accordion issues for NG [v4.21.x]

---

src/components/datagrid/_datagrid.scss

While testing a chart PR i noticed 4.21 has a regression no on empty widgets. So scoped the new CSS better.
- NA
- go to http://localhost:4000/components/bar/test-empty.html - should look as before as per https://4200-enterprise.demo.design.infor.com/components/bar/test-empty.html
- go to http://localhost:4000/components/datagrid/test-empty-card.html - should be able to scroll

NA - Fix a regression on empty widgets [v4.21.x]

---

src/components/dropdown/_dropdown.scss
src/core/_config.scss
src/themes/theme-uplift-contrast.scss
src/themes/theme-uplift-dark.scss
src/themes/theme-uplift-light.scss

This PR fixes a couple of visual bugs in the Uplift theme:
- The box shadow color and placement on Dropdown Lists has been improved.
- The disabled color for icons on pager buttons is now more distinct from other button colors.
Closes #2748 
- Examine the Dropdown List's box shadow colors on all Uplift variants: http://localhost:4000/components/dropdown/example-index.html?theme=uplift
- On that same sample, ensure that when filtering the dropdown, the Search icon is fully visible and not cut off.
- Examine the disabled color on pager buttons on …

2748 - Fix Uplift Color Issues

---

app/views/components/message/test-escaped-title.html
app/views/components/modal/test-escaped-title.html
app/views/components/modal/test-xss.html
docs/CHANGELOG.md
src/components/form/_form.scss
src/components/modal/modal.js
test/components/message/message.e2e-spec.js
test/components/modal/modal.e2e-spec.js

The original issue #246 only fixed xss on the title for messages not modal. This fixes it for both.
Fixes #246 
- go to http://localhost:4000/components/message/test-escaped-title.html
- open the message
- title should say `<script>alert("menuXSS")</script>`
- go to http://localhost:4000/components/modal/test-escaped-title.html
- open the modal
- title should say `<script>alert("menuXSS")</script>`

246 - Fix incorrect xss removal on modal

---

app/views/components/tabs-module/example-category-searchfield-go-button.html
docs/CHANGELOG.md
src/components/searchfield/searchfield.js

This turned out to be an example issue. Searchfield with categories was acting up and styling incorrectly when options were injected via html attribute data-options. Moved these to a <script>.
Closes #2745 
- Visit http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html
- Play around with the Searchfield with Categories and ensure there are nothing overlapping as per the issue description.

2745 - Tabs: Searchfield X button and text overlap

---

test/components/toolbar/toolbar-searchfield.e2e-spec.js

This PR just adds a quick e2e test that checks a test page for errors.  The Toolbar Searchfield's `noSearchfieldReinvoke` setting has a strange lifecycle that should be checked for errors whenever the Toolbar or Searchfield components are modified, and this provides a quick smoke test.
Closes #2692
Ensure all the tests on this branch pass

2692 - Add e2e test for `noSearchfieldReinvoke` to check for errors

---

app/views/components/mask/test-percent-locale.html
docs/CHANGELOG.md
test/components/mask/mask.e2e-spec.js

The logic was already in place for 434 so added an example and some tests.
Closes #434 
- go to http://localhost:4000/components/mask/test-percent-locale
- type: 100
- should show to the en-US format: `100 %`
- http://localhost:4000/components/mask/test-percent-locale?locale=ar-SA
- type: 100
- should show to the ar-SA format: `٪ 100`
- http://localhost:4000/components/mask/test-percent-locale?locale=tr-TR
- type: 100
- should show to the tr-TR format: `%100`

434 - Add Percent Locale examples

---

src/components/searchfield/_searchfield-toolbar.scss

Text is overlapping the close icon in the searchfield in the toolbar at phone screen size. This PR reduces the right position of the close icon when responding to phonedown screen width.
Closes #2745 
- Pull branch, build, run app.
- Visit localhost:4000/components/tabs-module/example-category-searchfield-go-button.html
- Reduce screen size to phone and type lots of characters in the searchfield and ensure text does not overlap the close button.

2745 - Tabs Searchfield x-button and text overlap FAILED QA

---

app/views/components/datagrid/example-paging.html
app/views/components/datagrid/test-editable-paging-validation-notoolbar.html
app/views/components/datagrid/test-editable-paging-validation.html
src/components/datagrid/datagrid.js
src/components/listview/listview.js
src/components/pager/pager.js
test/components/blockgrid/blockgrid-api.func-spec.js
test/components/datagrid/datagrid.e2e-spec.js

The feature done on 2797 did not work for sorting and filtering. Found that afterpaging did not fire for client side paging (maybe never have actually). Refactored some code to an afterPaging method but kept the event in case it is used.
Fixes #2797 
- go to http://localhost:4000/components/datagrid/example-paging-client-side
- 0 search for "ssor 1" -> rows will be highlight and filtered
- sort on any sortable column -> rows will remain highlight and filtered
- go to page 2 -> rows will remain highlight and filtered
- retest http://localhost:4000/components/lookup/example-multiselect-paging …

2797 - Fix keyword search to reset on paging and sort

---

app/views/includes/head.html

The code i added to change out the icons in the demo app did not work when deployed because i had localhost hardcoded and due to CSP.
Fixes #2743 
Fixes #2741 
- IMPORTANT: Use your machine name and not localhost , you can find this in system prefs - sharing - edit
- go to http://usmvtmcconechy:4000/components/icons/example-index.html (use your name)
- switch to vibrant theme -> icons should change
- go to http://usmvtmcconechy:4000/components/editor/example-index.html
- switch to vibrant theme -> icons should change

2743 / 2741 - Fix path to be relative when switching theme

---

app/views/components/toolbar-flex/test-header-like-title-in-span.html
docs/CHANGELOG.md
src/components/contextualactionpanel/_contextualactionpanel.scss
src/components/toolbar-flex/_toolbar-flex.scss

The css rule for the toolbar flex title was for the Contextual Action Panel title. Thus, the solution will target the `.modal.contextual-action-panel` as it's parent. The toolbar flex title shouldn't be truncated anymore.
I created a test page for this issue.
Closes https://github.com/infor-design/enterprise/issues/2810
Relates https://github.com/infor-design/enterprise/issues/2605
- Pull this branch and run the app
- Navigate to http://localhost:4000/components/toolbar-flex/test-header-like-title-in-span.html
- The title text shouldn't be truncated anymore.
Additional Testing (For …

2810 - Fix title gets truncated even there's enough space in toolbar flex

---

docs/CHANGELOG.md
package.json

Adds 3 new icons for WFM. For this updated the design system release with the new icons.
Addresses #419 (DS)
- look at the new icons (both themes)
- `icon-bed`, `icon-phone` and `icon-phone-linear` and `user-clock`and `icon-submit` and `icon-transfer`

419 - Add new design release for 5 new icons

---

src/components/charts/charts.js

Fixed there were errors in the console when a legend was clicked with charts.
Closes #2699
http://localhost:4000/components/column-grouped/example-contextmenu.html
http://localhost:4000/components/column-stacked/example-contextmenu.html
http://localhost:4000/components/donut/example-contextmenu.html
http://localhost:4000/components/line/example-contextmenu.html
http://localhost:4000/components/pie/example-contextmenu.html
http://localhost:4000/components/radar/example-contextmenu.html
- Click on any …

2699 - Fix clicked legend error with charts

---

docs/CHANGELOG.md
src/components/calendar/_calendar.scss
src/components/form/_form.scss

Fix the overlapping calendar upcoming description to duration when text is too long. 
Additional fixes (UI issues):
-  spinbox count cut off
-  checkbox all day alignment (not the same as the SOHO) in uplift light theme
Closes https://github.com/infor-design/enterprise/issues/2778
- Navigate to http://localhost:4000/components/calendar/example-index.html
- Create event with name "New Random Event12345"
- Verify the name of the newly created event in the Upcoming panel
- Check it for both SOHO and Uplift theme
- Text should no longer overlap
Additional Testing for UI …

2778 - Calendar: Fix overlapping calendar upcoming description

---

docs/CHANGELOG.md
src/components/field-options/_field-options-uplift.scss

Adjusting the width of input field large to align the option menu in uplift theme only. SoHo theme seems looks fine.
Closes: https://github.com/infor-design/enterprise/issues/2765
- Pull this branch and run the app
- Navigate to http://localhost:4000/components/contextmenu/example-field-options.html?theme=uplift&variant=light&colors=0563C2
- Hover the input full field to show the action menu
- Input full field and action menu should align in a single row

2765 - Field Options: Fix misaligned option menu in full length input field

---

app/views/components/fieldset/example-index.html
docs/CHANGELOG.md

The example page with chart is not being initialized. Change the example page by initializing the chart component.
Closes: https://github.com/infor-design/enterprise/issues/2610
- Pull this branch and run the app
- Navigate to http://localhost:4000/components/fieldset/example-index.html?theme=uplift&variant=light&colors=0563C2
- Resize the browser and check the completion chart labels
- Completion chart labels shouldn't overlapping each other

2610 - Fieldset: Fix overlapping labels when resizing the browser

---

docs/CHANGELOG.md
src/components/accordion/accordion.js

This PR fixes a problem with Accordion headers on Safari where clicking on accordion headers while another header had focus would not allow the focus state to clear.  If all accordion headers were clicked, eventually a focus state would be present on all headers.  This is no longer the case.
Closes #2851 
- Pull this branch, build, run app.
- Open http://localhost:4000/components/accordion/example-accordion-panels.html in Mac OSX Safari
- Click multiple top-level headers in the same accordion.  When clicking a new header, the previously-selected header should lose its focus state. …

2851 - Fix focus state on accordion headers that couldn't be cleared in Safari

---

app/views/components/datagrid/test-actions-reload.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.formatters.js
src/components/popupmenu/popupmenu.js
test/components/datagrid/datagrid.e2e-spec.js

Fixed actions menu was not opening after reload the data with Datagrid.
Closes #2876
- Navigate to http://localhost:4000/components/datagrid/test-actions-reload.html
- Click on any row `...` three dots action button in column `Action`
- Popup menu should open
- Click on top button `Reload` to reload data
- Click again on any row `...` three dots action button in column `Action`
- Popup menu should open

2876 - Fix actions menu with datagrid

---

src/components/emptymessage/_emptymessage.scss

The fix i made for empty message did not work with a filter row. This fixes.
Fixes #2845 
- go to http://localhost:4000/components/datagrid/example-empty-message.html
- make chrome as short as possible
- notice the icon goes under the header
- now in the .. menu - hide filter row
- notice the icon still now goes under the header

2845 - Add a better fix for empty message zindex [v4.22.x]

---

app/views/components/contextualactionpanel/test-beforeclose.html
docs/CHANGELOG.md
src/components/contextualactionpanel/contextualactionpanel.js
src/components/modal/modal.js

Fixed the case where `beforeclose` event was not working with contextual action panel.
Closes #2826
- Use iPhone
- Navigate to http://localhost:4000/components/contextualactionpanel/test-beforeclose.html
- Click on button `Contextual Action Panel`
- Click on button `Toggle to set close (False/True)`, this will update the preference on event `beforeclose`
- Try to close the panel by click button `X Close` or press `Escape` key
- It should only close if set to `True`

2826 - Fix beforeclose event with contextual action panel

---

src/components/applicationmenu/_applicationmenu-uplift.scss

This PR fixes the problem described in [this comment](https://github.com/infor-design/enterprise/issues/2739#issuecomment-538894947) where bullets on App Menu Accordion list items were causing text to shift down.
Closes #2739 
- Open Chrome on an Android device, simulator, browserstack, etc.
- Navigate to http://localhost:4000/components/applicationmenu/test-six-levels.html?theme=uplift
- Expand the app menu, and the "Level 1 Outbound Links" header.  Ensure the text is adjacent to the bullet point on "Level 2 List Header", and is not pushed down beneath …

2739 - Fix Uplift App Menu bullet placement in some versions of Android Chrome [v4.22.x]

---

app/views/components/colors/example-index.html
package.json

@kevinwhitedesign pointouted out that slate08 in uplift was not the new value anymore.
I found out that the hex change on this fix/PR https://github.com/infor-design/design-system/pull/405/files#diff-29b10ecab34514390228105c58e01e1dR85 for some reason did not get into IDS. So fixed this.
Also fixed the color page to change.
- npm i
- go to http://localhost:4000/components/colors/example-index.html
- slate08 is 313236 in soho/subtle
- use the theme switcher and change to uplift/vibrant
- slate08 is no #5C5861 in soho/subtle (note that before this change the colors didnt 100% get updated)

NA - Fix slate 08 and colors page [v4.22.x]

---

.travis.yml

This PR adds a Webhook to TravisCI that should enable us to see some build information in an MS Teams channel.
n/a
Check [this channel](https://teams.microsoft.com/l/channel/19%3a68f97f3d3db4430fa12cdde4da9654b1%40thread.skype/IDS%2520Dev%2520Notifications?groupId=a9f75c6d-a5d9-4556-9125-a5538f972afb&tenantId=457d5685-0467-4d05-b23b-8f817adda47c) to see if you see notifications from TravisCI (requires a valid Infor email address).

Add Webhook for MS Teams notification channel to TravisCI config

---

docs/CHANGELOG.md
src/components/toolbar/toolbar.js

This PR fixes a problem with dropdown/toolbar menu on iOS device (Safari & Chrome browser) is being cut off when clicking the more button. Adding `attachToBody: true` if the environment is **iOS**.
Closes https://github.com/infor-design/enterprise/issues/2800
- Pull this branch, then run the app
- Use iOS device or browserstack (Safari and Chrome )
- Navigate to http://localhost:4000/components/toolbar/example-inside-form-tag.html
- Click `...` button
- toolbar menu shouldn't cut off

2800 - Toolbar: Fix toolbar/dropdown menu cut off on iOS device

---

app/views/components/datagrid/test-update-settings.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-api.func-spec.js

Fixed Datagrid pager was not updating with updated method.
Closes #2759
- Navigate to http://localhost:4000/components/datagrid/test-update-settings.html
- See the pager below the grid
- Make un/checked paging checkbox on top of grid and click button `Update`
- See the pager below the grid, should show or removed based on checkbox option

2759 - Fix datagrid pager was not updating with updated method

---

app/views/components/colorpicker/test-modal.html
docs/CHANGELOG.md
src/components/popupmenu/popupmenu.js
test/components/popupmenu/popupmenu-updates-events.func-spec.js

Fixed bubbling destroy event with popupmenu.
Closes #2809
- Navigate to http://localhost:4000/components/colorpicker/test-modal.html
- Open modal
- Open color picker popup menu and pick any color
- Color picker popup menu should close
- See console should not fire destroy event

2809 - Fix bubbling destroy event with popupmenu

---

docs/CHANGELOG.md
src/components/pie/_pie.scss

This PR fixes a problem with legends get cut off on mobile view. Remove unnecessary css properties.
Closes https://github.com/infor-design/enterprise/issues/902
- Pull this branch, run the app
- Use device toolbar on Chrome then use iPhone X, or use browserstack
- Navigate to http://localhost:4000/components/donut/example-index.html
- Legends shouldn't cut off

902 - Pie Chart: Legend get cut off on mobile view

---

docs/CHANGELOG.md
src/components/popupmenu/popupmenu.js

This PR fixes a problem in iOS environments where it was not previously possible to type with a keyboard on input fields that also had a context menu assigned to them.
Closes #2613 
- Open a browser on an iPhone/iPad, simulator, BrowserStack, etc.
- Navigate to localhost:4000/components/input/example-contextmenu.html
- Focus the input field with a tap.  It should now allow the user to type or perform selection on the text.
- Press and hold on the input field.  After a longpress, a context menu should appear as expected.

2613 - Allow the user to type on Input Fields coupled with a Context Menu (iOS)

---

src/components/popupmenu/popupmenu.js

This PR pushes the changes made in #2977 back to v4.22.x, for a potential release against that branch.
Closes #2800
**Steps necessary to review your pull request (required):**
- Pull branch, build, run app.
- Use iOS device or browserstack (Safari and Chrome)
- Navigate to http://localhost:4000/components/toolbar/example-inside-form-tag.html
- Click `...` button to open the Popupmenu
- The Popupmenu in the Header Toolbar shouldn't be cut off

2800 - Default all Popupmenus to using `attachToBody` setting when in Mobile Safari [v4.22.x]

---

app/views/components/datagrid/test-filter-zero-as-text.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed text filter was not working to filter string include zeroes with Datagrid.
Closes #2854
- Navigate to http://localhost:4000/components/datagrid/test-filter-zero-as-text.html
- Filter column `Property Name Title` with text string `0001`
- Only rows that have `0001` in this column value should be visible (should be 3 matching rows)

2854 - Fix zeroes for text filter with datagrid

---

app/views/components/accordion/test-all-chevrons.html
app/views/components/accordion/test-all-plus-minus.html
app/views/components/accordion/test-display-chevron-setting.html
app/views/components/applicationmenu/test-all-chevrons.html
app/views/includes/applicationmenu-all-chevrons.html
docs/CHANGELOG.md
src/components/accordion/_accordion-mixins.scss
src/components/accordion/_accordion.scss
src/components/accordion/accordion.js
src/components/applicationmenu/_applicationmenu-uplift.scss
test/components/accordion/accordion-api.func-spec.js

This PR adds a setting to the Accordion component, `expanderDisplay` that enables changing the expander button icon.  By default, the accordion uses the "chevron"-style icon on its top-level headers, and uses "plus-minus" style icons on its subheaders.  This PR fulfills a feature request that allows for the usage of all chevron-style icons throughout a nested accordion stack.
Additionally, the `displayChevron` setting, which allows for the conversion of all icons to the "plus-minus" style, was deprecated in favor of the new setting, which handles all display modes.  Deprecation warnings have been added for this setting, and a test demonstrating internal conversion of the setting has been …

2900 - Enable usage of chevron icons on all levels of Accordion headers

---

app/views/components/tabs-vertical/example-outbound-links-page1.html
app/views/components/tabs-vertical/example-outbound-links-page2.html

This PR fixes a demoapp bug where a set of vertical tabs samples that demonstrate how to use the component's tab list as simple outbound links was previously not working.  It appears that this stopped working after we added the lazy-loading tab feature.
Closes #2576 
- Open http://localhost:4000/components/tabs-vertical/example-outbound-links-page1.  In the tab panel area, there should be text present saying "Page 1 is Showing".
- Click the link in the tab list for Page 2.  This should navigate the browser to …

2576 - Fix Vertical Tabs test samples that demonstrate outbound links

---

src/components/popupmenu/popupmenu.js
src/components/toolbar/toolbar.js

This PR builds on @ericangeles's previous change set for this issue (#2901), making a change to all Popupmenu instances where the `attachToBody` setting is defaulted to `true` instead of simply at the toolbar level.  This fixes a number of problems in various Popupmenu instances in iOS settings.
Closes #2800 
- Pull branch, build, run app.
- Use iOS device or browserstack (Safari and Chrome )
- Navigate to http://localhost:4000/components/toolbar/example-inside-form-tag.html
- Click `...` button to open the Popupmenu
- The Popupmenu in the Header Toolbar shouldn't be cut off
**Included in …

2800 - Default all Popupmenus to using `attachToBody` setting when in Mobile Safari

---

app/views/components/mask/test-number-parsing.html
docs/CHANGELOG.md
src/components/locale/locale.js
test/components/locale/locale.func-spec.js

Fixed parseNumber() to properly remove spaces.
Closes #2959 
- Navigate to http://localhost:4000/components/mask/test-number-parsing.html?locale=fr-FR
- Enter `1234567,12` into the Number Field and then tab out
- The Number Field should display `1 234 567,12`
- Parsed Number result field should display `1234567.12`
- Change the url to test cultures with other group and decimal values:
- locale=es-ES - Enter `1234567,12` and tab out
- Number Field should display `1.234.567,12`
- Parsed Number result field should display `1234567.12`
- …

Locale: parseNumber not parsing correctly when culture file has group of space

---

docs/CHANGELOG.md
src/components/dropdown/_dropdown-uplift.scss
src/components/dropdown/_dropdown.scss

This PR fixes UI issues in field filter component. I also noticed some movement of the icons when you open the field filter dropdown.
- Filter icons are not vertically aligned/centered
- Field filter dropdown shows the content info when it is open on a `270px` below height of browser
Additional issue noticed:
- Icon is moving when clicking/opening the ff dropdown
Closes https://github.com/infor-design/enterprise/issues/2951
**1.)**
- Navigate to http://localhost:4000/components/field-filter/example-index.html
- Filter icons should now align to …

2951 - Fix UI issues in field filter

---

app/views/components/datagrid/test-tree-children-expand-collapse.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed the tree children expand and collapse was not working with Datagrid.
Closes infor-design/enterprise-ng#633
- Navigate to http://localhost:4000/components/datagrid/test-tree-children-expand-collapse.html
- Expand row with id `8`
- Expand row with id `14`
- Expand row with id `19`
- Now Collapse row with id `8`
- Then again expand row with id `8`
- See the row `14` and `19` should be expanded
- And make sure the row `26` should not be expanded at this point

633 - Fix tree children expand and collapse with datepicker

---

docs/CHANGELOG.md
src/components/searchfield/_searchfield-toolbar.scss

This PR fixes missing X button in searchfield on a mobile viewport. There's a css rule that causes the icon to be transparent. Not sure if it's uses on a special case so I created a new rule.
Closes https://github.com/infor-design/enterprise/issues/2948
- Navigate to http://localhost:4000/components/lookup/example-index.html
- Click the Lookup filter in Product field
- In the search field, type `Test`
- Try to resize the browser up to `767px` below or use mobile device
- X button should still be visible
~~- [ ] …

2948 - Fix missing x button on mobile viewport

---

app/views/components/dropdown/test-placeholder-initial-selected.html
docs/CHANGELOG.md
src/components/dropdown/_dropdown.scss
src/components/dropdown/dropdown.js
test/components/dropdown/dropdown.e2e-spec.js
test/components/multiselect/multiselect.e2e-spec.js

Fixed placeholder was incorrectly renders when initially set selected item with Dropdown.
Closes #2870
- Navigate to http://localhost:4000/components/dropdown/test-placeholder-initial-selected.html
- See dropdown text should be `Delaware`
- Open dropdown list and select first item (blank item)
- See placeholder text should show
Check below links should work fine too
http://localhost:4000/components/dropdown/example-placeholder.html
http://localhost:4000/components/multiselect/example-placeholder.html

2870 - Fix placeholder for initially selected with dropdown

---

docs/CHANGELOG.md
src/components/autocomplete/autocomplete.js
test/components/autocomplete/autocomplete-events.func-spec.js

This PR addresses a couple issues in the Autocomplete component (and by proxy, the Searchfield):
- The Autocomplete no longer binds events and invokes the popupmenu every time a search term is changed.
- The Autocomplete properly cleans up the `#ac-is-arialive` element, responsible for accessibility/speech announcements whenever the search term is changed, instead of stacking multiple of these elements.
Closes #2888
- Open http://localhost:4000/components/searchfield/example-index?theme=uplift
- Type "Co" in the searchfield.
- Wait until the results list …

2888 - Fixed memory leaks and multiple event handlers in Searchfield/Autocomplete

---

docs/CHANGELOG.md
src/components/locale/locale.js
test/components/locale/locale.func-spec.js

Fixed parseDate() was not working for leap year (February 29) with Locale.
Closes #2737
- Navigate to http://localhost:4000/components/datepicker/example-anniversary-format.html
- Click on the date picker icon for the Month Day field
- Datepicker will open, select February 29 2016
- Datepicker should close and will display value `February 29`
- Tab out of the field
- It should remain display value `February 29`
Additionally check:
- Open developer tools and run
- Enter > Soho.Locale.parseDate("0229", "MMdd", false);
- Response > Mon Feb 29 2016 …

2737 - Fix parse date for leap year with locale

---

app/views/components/contextualactionpanel/test-close-button-flex-from-settings.html
app/views/components/contextualactionpanel/test-close-button-flex.html
app/views/components/contextualactionpanel/test-close-button-from-settings.html
app/views/components/contextualactionpanel/test-close-button.html

Some Contextual Action Panel (CAP) samples added as part of #2984 contained a hard-coded minimum width that was causing issues in responsive scenarios.  This PR adjusts those new samples to only display the minimum width when above the "phone-to-tablet" breakpoint.
- Related to #2984
- Closes #2834
Pull this branch, build, and run the app.  Check the following samples at responsive breakpoints and make sure the CAP fits within the page boundary properly:
- http://localhost:4000/components/contextualactionpanel/test-close-button?theme=uplift
- …

2834 - Fix min-width issues with new CAP samples

---

app/views/components/locale/test-extend-messages.html
docs/CHANGELOG.md
src/components/locale/locale.js
test/components/locale/locale.func-spec.js

nb-NO has problems and will jse in several situations related to locale translations. Because its pattern is different than other locales in that the language nb is not the same as its parent language no. So did this mapping
Fixes #3035 
- go to http://localhost:4000/components/locale/test-extend-messages.html?locale=nb-NO
- check console and ensure no errors
- page should load and translate one thing and then add two ~faky translations~
- http://localhost:4000/components/locale/test-translated-strings.html?locale=nb-NO should not error anymore and show norweigen text …

3035 - Fix a jse using nb-NO locale

---

src/components/form/_form.scss
src/components/modal/_modal.scss

This PR makes some CSS style changes to the Textarea/Inputs on responsive forms contained inside of a Modal or Contextual Action Panel.  These changes fix a bug in IE11/Edge that was causing the size of textareas to shift if they had a large amount of text pasted into them.
Closes #2968
- Open IE11 or Edge
- Navigate to http://localhost:4000/components/contextualactionpanel/example-index.html
- Open the Contextual Action Panel.
- In the textarea, paste this large blob of text:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod …

2968 - Fix Textarea size shift on IE11/Edge

---

.github/CODEOWNERS

This PR removes individual names of developers from the Github `CODEOWNERS` file and instead makes the [IDS Engineering Team](https://github.com/orgs/infor-design/teams/eng-ids/members) a dynamic list of code owners for this repo.

change `CODEOWNERS` file to work off of Github Teams

---

test/components/datepicker/datepicker.e2e-spec.js
test/components/locale/locale.func-spec.js

Some tests (newer) seem to now fail because of incorrect month padding and time change.
This should fix.

Fix a few tests

---

app/src/js/middleware/csp-handler.js
app/views/components/applicationmenu/example-personalized-role-switcher.html
app/views/components/applicationmenu/test-all-chevrons.html
app/views/components/applicationmenu/test-hcm-icons.html
app/views/components/applicationmenu/test-hcm.html
app/views/components/applicationmenu/test-personalized-role-switcher-long-title.html
app/views/components/button/example-disabled-button-tooltip.html
app/views/components/datagrid/example-index.html
app/views/components/datagrid/test-actions-reload.html
app/views/components/dropdown/test-xss.html
app/views/components/personalize/example-color-theme-api.html
app/views/components/toolbar-flex/example-index.html
app/views/components/toolbar-flex/example-more-actions-ajax.html
app/views/components/toolbar-flex/test-empty-buttonset-ajax-more-menu.html
app/views/components/toolbar-flex/test-gauntlet.html
app/views/includes/head.html
docs/CHANGELOG.md
src/components/dropdown/_dropdown.scss
src/components/dropdown/dropdown.js
src/components/listfilter/listfilter.js
src/utils/xss.js
test/components/dropdown/dropdown.e2e-spec.js

The xss was not working when doing a backspace in dropdown. (There were CSP errors).
Fixes infor-design/enterprise-ng#650
**Test One**
- pull this and restart the demo app
- go to http://localhost:4000/components/dropdown/test-xss.html
- type a and make sure it filters
- make sure you can select the <> formatted items
- backspace to clear
- make sure no console errors (CSP Error will happen if it injects)
**Test Two**
- go to http://localhost:4000/components/dropdown/test-special-chars.html
- make sure you can select all the items especially `<test>`
**Test Three**
- go to …

650 - Fix xss issues in dropdown

---

docs/CHANGELOG.md
src/themes/theme-uplift-contrast.scss

Fix font color of column headers in datagrid in cards.
Closes https://github.com/infor-design/enterprise/issues/2830
- Navigate to http://localhost:4000/components/cards/test-datagrid.html?theme=uplift&variant=contrast
- Column headers should be visible

2830 - Fix column headers font color in uplift high contrast

---

src/components/dropdown/dropdown.js
src/utils/xss.js
test/components/dropdown/dropdown.e2e-spec.js

650 was failed QA because some strings cannot be searched correctly due to missing encoding re-correction. This fixes that problem. Addressing this comment https://github.com/infor-design/enterprise-ng/issues/650#issuecomment-550225737 on this PR
Note: I noticed searching for ( and ) was an issue in all older versions (for what thats worth)
Fixes #650 
- go to http://localhost:4000/components/dropdown/test-xss.html
- type ( or ) and it should work (in the first dropdown)
- type x and it should work (in the first dropdown)
- type t in the (second dropdown) and it should work

650 - Fix encoding in dropdown search

---

src/components/calendar/calendar-shared.js
test/components/calendar/calendar.e2e-spec.js

When adding the events with a modal, there was an error in a moved/refactored function. This corrects this issue
Fixes #3094 
- double click a date
- enter some text on the subject
- press apply
- should add the date and not have any errors in the console

3094 - Fix Calendar Errors adding with the Modal [v4.23.x]

---

app/views/components/datagrid/test-new-row-dirty-indicators.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-editing.func-spec.js

Fixed getModifiedRows() method was not working with Datagrid. It had duplicate entries for the same row.
Added support to get Only Changed Values as return array for get modified rows method.
Closes #2908
Closes #2958
issue# 2908
- Navigate to http://localhost:4000/components/datagrid/test-dirty-change-cell-externally.html
- Click on button `Change Cell` on top of grid
- See in console, should return only one entry in results array
issue# 2958
- Navigate to http://localhost:4000/components/datagrid/test-new-row-dirty-indicat …

2908/2958 - Fix get modified rows method with datagrid

---

src/components/calendar-toolbar/calendar-toolbar.js
src/components/calendar/calendar-shared.js
src/components/datepicker/datepicker.js
src/components/monthview/monthview.js
src/components/week-view/week-view.js
test/components/calendar/calendar.e2e-spec.js

Addresses three more QA issues. I added on test as adding tests for switching and add modal, proved unstable in the past so skipping for now.
Fixes #3096 
Fixes #3126 
Fixes #3107 
** Testing 3096**
- change to day view
- move forward two days
- switch to week view
- click today -> the first day of the week should not change
** Testing 3126**
- advance one month with the > icon
- open the date picker
- datepicker should match the selected day/month year …

Misc - Fix more calendar bugs [v4.23.x]

---

app/views/components/emptymessage/test-button-click.html
docs/CHANGELOG.md
src/components/emptymessage/emptymessage.js
test/components/emptymessage/emptymessage-api.func-spec.js

The empty message button click setting fired no matter where you clicked. This is incorrect, so i fixed it.
Fixed #3139 
- go to http://localhost:4000/components/emptymessage/test-button-click.html
- click the button and notice a toast
- click anywhere else in the widget and notice no toasts.

3139 - Fixed problems with empty message click

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed personalized columns were not working when toggle columns and drag drop with Datagrid.
Closes #3004
- Navigate to http://localhost:4000/components/datagrid/example-export-from-button.html
- Click on toolbar button `...` then click on `Personalized Columns`
- In personalized modal window uncheck `Quantity` and `Status`
- Click on `Close` to close the modal window
- Drag and Drop the column `Action Item` (could be any column) to where column `Quantity` was located
- Click again on toolbar button `...` then click on `Personalized Columns`
- …

3004 - Fix personalized columns with datagrid

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-filtering.func-spec.js

Fixed grouping filter was not working after do sort with Datagrid.
Closes #3012
- Navigate to http://localhost:4000/components/datagrid/example-grouping-filter.html
- Use column `Location` to filter `USA`
- Should filter accordingly
- Click any column header to sort the list (ascending/descending)
- Should keep filter and sorted result

3012 - Fix group filter after sort with datagrid

---

docs/CHANGELOG.md
src/components/sparkline/sparkline.js

This PR fixes a small bug in the Sparkline Chart, where changing themes using the personalization API would cause the chart to throw a JS error.  This is due to a bug in how the `updated()` method previously handled transforming incoming settings.
This PR also makes it possible to pass a `settings` object as a second argument if triggering an `updated` event on the Sparkline chart.
Closes #3159
- Open http://localhost:4000/components/sparkline/example-index.html
- Use the theme changer to switch to "Vibrant" theme.
- Open a dev tools console and make …

3159 - Prevent Sparkline Chart from throwing errors during a theme change

---

app/views/components/calendar/test-specific-month.html
src/components/calendar/calendar.js
src/components/monthview/monthview.js
src/components/personalize/personalize.js
test/components/calendar/calendar-api.func-spec.js
test/components/calendar/calendar.e2e-spec.js

Attempting to fix #3136, while i don't see the issue. I know that this code was giving me timing issues before. So move the event triggering to AFTER the style sheet is loaded and the old one is removed. Also fixed the calendar tests by fixing a bug, that the week would change every day in the weekview.
Fixes #3136 
**Resize Bug**
- go to http://localhost:4000/components/tabs/example-index.html?theme=soho&variant=light&colors=2578a9
- select last (or any tab)
- change between subtle and vibrant themes (the tab selection indicator should resize after and look aligned over the tab) …

3136 - Fix theme change to fire resize after load / Calendar Tests

---

app/views/components/datagrid/test-custom-date-formats.html
docs/CHANGELOG.md
src/components/locale/locale.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/locale/locale.func-spec.js

When using a format of `yyyy-MM-ddTHH:mm:ss.SSS` the date formatter would drop leading zeros. This addresses the issue, also added some more tests
Fixes #2696 
- covered by unit tests but added one visual test page
- check out http://localhost:4000/components/datagrid/test-custom-date-formats.html and it shows a bunch of formats (Date (Time Millis)) being the fixed one. The main thing to note is all dates should have a .NNN (a dot and three digits at the end in that column)

2696 - Fix truncating of leading zeros

---

app/views/components/datagrid/test-hide-pager-if-one-page-filter.html
docs/CHANGELOG.md
src/components/pager/pager.js
test/components/datagrid/datagrid.e2e-spec.js

Fixed hide pager on one page and filter was not working correctly with Datagrid.
Closes #2676
- Navigate to http://localhost:4000/components/datagrid/test-hide-pager-if-one-page-filter.html
- See pager nav below the grid, should be showing
- Use column `Activity` to filter `Assemble Paint`
- Should filter accordingly (two results only)
- See pager nav below the grid, should not be showing now
- Clear the filter, should show all the rows
- See pager nav below the grid, should be showing again

2676 - Fix hide pager on one page with datagrid

---

app/views/components/mask/test-number-parsing.html
docs/CHANGELOG.md
src/components/mask/mask-input.js

This PR fixes a bug where Safari would not fire a change event if a Masked Input field was modified, but the value didn't contain a decimal.  This is fixed by simply forcing the event to go off when a change is made, and making an internal record that the event was fired so it doesn't reoccur.
Closes #3002
- Open http://localhost:4000/components/mask/test-number-parsing.html in Safari
- In the field "Number Field", type "12345" and tab out.  The next field, "Parsed Number Result" should be modified to contain "12345".
- Tab back into the "Number Field", …

3002 - Fix Safari "change" event not firing

---

app/views/components/datagrid/test-editable-single-column.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid-uplift.scss
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js

Fixed editable single column was not working with Datagrid.
Closes #3023
- Navigate to http://localhost:4000/components/datagrid/test-editable-single-column.html
- Grid should render one column only
- Click on any cell to go in edit mode
- Should be able to edit the cell

3023 - Fix editable single column with datagrid

---

src/core/_reset.scss

Recent change caused colors to "go dark" in safari. This fixes the issue but it is curious so gave a look @EdwardCoyle 
Also hoping the calendar tests to work on this PR. Testing for that as well.
Fixes #3183 
- open mac safari
- go to http://localhost:4000/components/datagrid/example-index
- text should look same again like https://4230-enterprise.demo.design.infor.com/components/datagrid/example-index.html
- also test IOS

3183 - Fix text color in safari

---

app/views/components/datagrid/test-custom-number-formats.html
app/views/components/dropdown/test-on-modal.html
docs/CHANGELOG.md
src/components/locale/locale.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/locale/locale.func-spec.js

Datagrid had a bug that meant if a string is provided in the current locale for a number it wont parse correctly if the decimal format is a `,` (such as nl-NL). This fixes the issue and adds some tests
Fixes #3165 
- go to http://localhost:4000/components/datagrid/test-custom-number-formats?locale=nl-NL
- the last column values should be the same as in the test file `100,00`, `836,45`, `1.200,12`, `1.200,12`, `10,99`, ` 130.300,00`, `130.300,00` ect..
- go to http://localhost:4000/components/datagrid/test-custom-number-formats
- numbers should be the same but in current locale still …

3165- Fix a bug parsing numbers

---

app/views/includes/head.html
docs/CHANGELOG.md
src/components/theme/theme.js

This PR fixes some issues with some demoapp-specific code that handles using query parameters to persist changes in theme/personalization across page refreshes:
- Previously, using the switcher to set theme or variant on a url like http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm.html would also set the color.  When the page would refresh after the settings change, it would unexpectedly adjust personalized areas to the persisted color.
- Previously, due to the implementation of the persistence, adding another query param for controlling demoapp settings to a URL that already contained theming settings (fx: `?&theme=uplift&locale=ar-EG`) would cause the …

Fix bugs with persistence of query params controlling personalization

---

src/components/toast/toast.js

Fixed an issue with Toast where open the 2nd toast before 1st not being completed yet, both toast were appearing on the same position.
Closes #3025
- Navigate to http://localhost:4000/components/toast/example-draggable.html
- Click on each button to show the toast message
- Drag and drop to different positions each
- Close and open page again, then open each toast message (try to open the 2nd toast before 1st get completed)
- See each message should remain the saved position

3025 - Fix another case for saved position with toast

---

src/components/locale/locale.js
src/components/tooltip/tooltip.js

https://github.com/infor-design/enterprise/commit/92230036ffe2f00f7d00c0bf94d677080595d996#diff-0732597cd96cb9d201490dfa8fe61b4b caused an issue that made datepickers no longer load correctly in IE 11. This fix works but feel free to suggest a "better" fix.
Fixes #3226 
- Open IE11
- go to http://localhost:4000/components/datepicker/example-index.html
- open the list and make sure it renders
- retest https://github.com/infor-design/enterprise/pull/3203

3226 - Remove a console log and fix a placement bug

---

app/views/components/dropdown/test-configured-as-multiselect.html

This PR fixes a demoapp sample that had duplicate ID attributes on multiple Dropdown examples, causing some of the Dropdowns to appear not to retain state.  
Closes #3105
- Pull this branch, build, run the app.
- Using IE11, open http://localhost:4000/components/dropdown/test-configured-as-multiselect.html?locale=he-IL
- Open the dropdown labeled "Legacy MoveSelectedToTop"
- Select some values, and close the dropdown.  The pseudo-element should appear to set the values properly.
- Reopen the menu.  The items that were previously selected should still be checked off.

3105-  Fix dropdown/multiselect test sample to not have duplicate IDs

---

docs/CHANGELOG.md
src/components/compositeform/_compositeform.scss

Fixed scroll was not working on mobile view for scrollable-flex layout with tabs.
Closes #2931
- Navigate to http://localhost:4000/components/tabs/example-composite-form-on-side.html
- Click on mobile icon in dev tool window to switch mobile viewport inspector 
- Use any phone device and flip the device to landscape mode
- See the content on page should be scrollable

2931 - Fix scroll on mobile view with tabs

---

src/components/spinbox/_spinbox.scss

This PR fixes an issue on the `xs` size Spinbox on the Vibrant theme, where an incorrect amount of padding was causing the spinbox to appear to wrap.
Closes #1384
- Open http://localhost:4000/components/spinbox/example-sizes.html?theme=uplift&variant=light
- Ensure the field labelled "Extra-Small Spinbox" renders all on one line, and appears to be the same width (including buttons) as the corresponding Input field.

1384 - Fix incorrect padding on `xs` Spinbox size [v4.24.x]

---

docs/CHANGELOG.md
src/components/tooltip/tooltip.js

Fixed the calendar layout was not working on ie11 with Datepicker.
Closes #3226
Open IE11
http://localhost:4000/components/datepicker/example-index.html
- Open the calendar
- Make sure it renders
- The functionality of the calendar should work fine
also check this
http://localhost:4000/components/popover/example-attached-to-textbox.html
- Mouse over the icon inside the text box
- Popover should show up
- Switch between themes then verify the popover again
- Should show popover content

3226 - Fix the calendar layout with datepicker [v4.24.x]

---

src/components/datagrid/datagrid.js

Fixed resize columns were not working on safari with Datagrid.
Closes #1818
- Navigate to http://localhost:4000/components/datagrid/test-column-sizing.html
- Click any column header to make sort
- After sort then resize any column by dragging
- It should work fine

1818 - Fix resize columns with datagrid [v4.24.x]

---

src/components/emptymessage/_emptymessage.scss

Fixed empty message was not showing for ie11 with Datagrid.
Closes #2363
- Open ie11
- Navigate to http://localhost:4000/components/datagrid/example-filter.html
- Type something to filter in any column which does not match
- Empty message should show
Scrolling header on safari fixed with other PR #3238

2363 - Fix empty message with datagrid [v4.24.x]

---

app/data/accounts-sm.json
docs/CHANGELOG.md
src/components/datagrid/datagrid.groupby.js
test/components/datagrid/datagrid.e2e-spec.js

The floating point math in JS was causing aggregator display values to add up wrong. This is a fix.
Fixes #3233 
- go to http://localhost:4000/components/datagrid/example-summary-row.html
- ensure the last two columns add up correctly
- http://localhost:4000/components/datagrid/example-grouping-totals also adds up correctly

3233 - Fix aggregator sum errors

---

src/components/input/_input.scss
src/themes/theme-soho-contrast.scss
src/themes/theme-uplift-contrast.scss

Fixed some missing styles on the safari, placeholders on search.
Fixes #3040 
http://localhost:4000/components/header/example-searchfield-expanded.html
- placeholder should be white at 50%
http://localhost:4000/components/input/example-index.html?theme=uplift&variant=contrast
- disabled input should show its placeholder
- also i lowered the placeholder color as it was the same as text
http://localhost:4000/components/colorpicker/test-states.html?theme=uplift&variant=contrast
- disabled input should show its placeholder
http://localhost:4000/components//fileupload/example-index.html?theme=so …

3040 - Fix header text color in safari [v4.24.x]

---

src/components/datagrid/datagrid.js

Fixed two issues that may cause NG upgrade issues. Two bugs...first is that if the columns are initially empty array then calling updateColumns fails to put columns on. Second is that if a message is opened then opening a personalization dialog after will next time fail as it uses the same beforeopen event
Fixes infor-design/enterprise-ng#688 (NG)
- pull this branch and build
- apply the changes over to a branch of NG off latest master (copy the node_modules/ids-enterprise or use npm link)
- go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-breadcrumb
- page should show column …

688 - Fix two errors shown in the NG project [v4.24.x]

---

app/views/components/homepage/example-four-column.html
app/views/components/homepage/example-scenario-a.html
app/views/components/homepage/example-scenario-b.html
app/views/components/homepage/example-scenario-c.html
app/views/components/homepage/example-scenario-d.html
app/views/components/homepage/example-scenario-e.html
app/views/components/homepage/example-scenario-f.html
app/views/components/homepage/example-scenario-g.html
app/views/components/homepage/example-scenario-h.html
app/views/components/homepage/example-scenario-i.html
app/views/components/homepage/example-scenario-j.html
app/views/components/homepage/example-scenario-k.html
app/views/components/homepage/example-scenario-n.html
app/views/components/homepage/example-scenario-o.html
app/views/components/homepage/example-scenario-p.html
docs/CHANGELOG.md
src/components/homepage/homepage.js

Fixed the DOM order was not working for triple width widgets with Homepage.
Closes #3101
- Navigate to http://localhost:4000/components/homepage/example-scenario-p.html
- While browser width more then `740px`
- See the order of widget should be as
- 1st row `(A) single-width` and `(B) single-width`
- 2nd row `(C) tripple-width`
- 3rd row `(D) tripple-width`
- 4th row `(E) tripple-width`

3101 - Fix to keep the widget dom order with homepage

---

docs/CHANGELOG.md

I pushed accidentally the core fix of this issue direct to 4.24.x so the steps are a bit wierd. Just noting but the fix should be safe. Except for the changelog.
If looks good will post a new nightly on dev tomorrow AM and release a NG dev build.
Examine fix changes here already accidentally pushed : https://github.com/infor-design/enterprise/commit/4704df485f1f5f48d4a0dfaa10bcc223a8e849ce 
Fixes infor-design/enterprise-ng#690 (NG)
- go to http://localhost:4000/components/datagrid/test-update-columns-empty
- hit update to updateColumns
- resize a column or two
- hit …

690 - Fix for datagrid resetColumns when columsn are empty [v4.24.x]

---

src/components/editor/editor.js

Changed the conversion logic to cover the cases on http://localhost:4000/components/editor/example-customize-buttons.html
Fixes #3253 
- go to http://localhost:4000/components/editor/example-customize-buttons.html
- the h1 and h2 buttons should be replaced with a font picker
- any other example that convert old settings need to be checked?
- test pages on http://localhost:4000/components/editor/

3253 - Change conversion logic for one example [v4.24.x]

---

src/components/datagrid/datagrid.js

Fixed a bug when restoring columns after a rerender when some are hidden. When this occurs the width becomes zero so the column was not visible.
Fixes #3266 
- go to http://localhost:4000/components/datagrid/example-custom-toolbar.html
- in the .. menu open personalize columns
- hide the product name and / or activity column
- on the toolbar do a search for .99 (this used to do a rerender and sets the hidden widths to zero)
- in the .. menu open personalize columns
- show the product name and / or activity column
- their restore size should be roughly what it was before when visible.

3266 - Fix restoring columns after rerender [v4.24.x]

---

docs/CHANGELOG.md
src/components/locale/cultures/zh-CN.js
src/components/locale/cultures/zh-Hans.js
src/components/locale/cultures/zh-Hant.js
src/components/locale/cultures/zh-TW.js
test/components/calendar/calendar.e2e-spec.js

Translators told us all ZH locales are wrong in the datepicker/monthview. This corrects them.
Fixes #3081 
- go to http://localhost:4000/components/datepicker/example-index.html?locale=zh-CN
- open calendar
- should be of format `2019年 12月` fx `<yearno>年 <monthno>月`
- effects all zh* locales

3018 - Correct ZH month translations

---

app/views/components/datagrid/test-tree-editable-children.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/calendar/calendar.e2e-spec.js

Fixed data after commit edit was not in sync for tree with Datagrid.
Closes infor-design/enterprise-ng#659
- Navigate to http://localhost:4000/components/datagrid/test-tree-editable-children.html
- Click on checkbox in column `view` to make checked for `Workflows` 3rd row
- See console for `arguments: rowData > view` should be updated(true/false)
- And also `data: [0] > children[0] > children[0] > children[0] > children[0] > view` should be updated(true/false)

659 - Fix data after commit edit for tree with datagrid

---

src/components/accordion/_accordion.scss
src/components/accordion/accordion.js
src/components/applicationmenu/_applicationmenu-uplift.scss

This PR fixes a few issues on the filtered styles of an Uplift application menu:
- Extraneous space underneath of a matching top-level filter result, which was caused by a list of children with all children filtered away, is now properly hidden.
- Sizing changes to top-level, expandable headers have been implemented to help strange padding issues.
- A small adjustment to the way `expand()` works now prevents accordion headers with no panes/content from completing the `expand()` process, which was altering the style and incorrectly triggering events.
Closes #2925 
- Pull this branch, build, …

2925 - Fix filtered header styles on Uplift App Menu [v4.24.x]

---

docs/CHANGELOG.md
src/themes/theme-uplift-contrast.scss
src/themes/theme-uplift-dark.scss
test/components/calendar/calendar.e2e-spec.js

Fixed scrollbar styles for windows chrome to work with all themes.
Closes #3172
- Open windows chrome
- Navigate to http://localhost:4000/components/listview/example-index.html
- Change the theme to `Vibrant`
- See scrollbar style on every `Variant` or `Colors` options
also check for JS error (cannot reproduce, it might be fixed by other issue)
http://localhost:4000/
- Switch the themes or colors
- See in console should not be any JS error

3172 - Fix scrollbar styles for windows chrome

---

docs/CHANGELOG.md
src/components/searchfield/_searchfield.scss
src/components/searchfield/searchfield.js

This PR fixes an overlapping text when searchfield is clearable which close icon button is presented.
Closes https://github.com/infor-design/enterprise/issues/3135
- Navigate to any test pages that has clearable searchfield e.g.,
1. http://localhost:4000/components/searchfield/example-index.html
2. http://localhost:4000/components/searchfield/test-application-server-data-label.html
- Type any as you go through the searchfield.
- Long text should not overlap the close icon button.
- Test also to non-clearable searchfield. It should not affect nor …

3135 - Fix overlapping text when searchfield is clearable

---

app/views/components/modal/test-trigger-button-return-focus.html
src/components/modal/modal.js

Fixed returns focus to trigger button after closing with Modal.
Closes #3166
- Navigate to http://localhost:4000/components/modal/example-index.html
- Click on button Show Modal to open modal
- Click on button Cancel to close the modal
- See the trigger button `Show Modal` should be focused

3166 - Fix trigger return focus with Modal

---

src/components/datagrid/datagrid.js

Fixed add row for grouping on 2nd page was not working with Datagrid.
Closes #2801
- Navigate to http://localhost:4000/components/datagrid/test-group-editable-addrow.html
- Select any row and click on toolbar button `Add Row` then try all options
- Should add new row fine
- Go to next page
- Select any row and click on toolbar button `Add Row` then try all options
- Should add new row fine

2801 - Fix add row for grouping with datagrid

---

docs/CHANGELOG.md
src/components/calendar/calendar.js

Closes #3170 
Allow the event types data to define if the item is checked.
- Go to http://localhost:4000/components/calendar/example-index.html
- Open the console to use the calendarAPI and type:
```
// Uncheck the first event type
$('.calendar').data('calendar').settings.eventTypes[0].checked = false
// Render the eventTypes based on the current settings
$('.calendar').data('calendar').renderEventTypes()
```

3170 - The checked attribute for renderEventTypes

---

docs/CHANGELOG.md
src/components/accordion/_accordion.scss

Fixed all panes were expanded and there was no way to be close with Accordion.
Closes infor-design/enterprise-ng#701
- Pull and build ([NG master](https://github.com/infor-design/enterprise-ng.git))
- Navigate to http://localhost:4200/ids-enterprise-ng-demo/accordion
- Only the second pane should be expanded on load
- Collapse/expand should work fine

701 - Fix expanded panes with accordion

---

app/views/components/mask/test-input-type-numeric.html
docs/CHANGELOG.md
src/components/mask/mask-input.js
src/utils/utils.js
test/components/mask/mask.e2e-spec.js

This PR fixes a bug in the system that renders correctly-masked values into Mask Input fields with a `type="number"` attribute.  The component was previously attempting to use the `setSelectionRange()` API on these elements, but that API doesn't exist on number fields, and was causing Javascript errors to throw and mask values to be incorrect.
This PR removes the use of this API when Masks are configured against number inputs.
Closes #3315
- Open http://localhost:4000/components/mask/test-input-type-numeric.html
- Try to key in numbers beyond the …

3315 - Fix errors thrown when using Masks on HTMLInputElement number fields

---

docs/CHANGELOG.md
src/components/accordion/_accordion-uplift.scss
src/components/accordion/_accordion.scss
src/components/applicationmenu/_applicationmenu-uplift.scss
src/components/applicationmenu/applicationmenu.js
src/themes/theme-uplift-light.scss

This PR fixes a couple problems related to filtering on the Application Menu:
- When filtering, children of items that had been filtered out would sometimes be hidden by an accordion pane with `display: none;`.  This has been resolved, and items that match the search term, but may be children of items that DON'T match the search term, are all properly displayed.  The non-matching parents have a slightly different text color.
- When using the Searchfield with keyboard navigation, using the Tab key to go from the searchfield to the X button would previously cause the filter to reset.  This has been resolved, and the filter now only disappears if the X button is clicked.
**Related github/jira …

3285 - Fix App Menu usability issues

---

app/views/components/modal/example-index.html

Fixed return focus was not working for safari with Modal.
Closes #3166
- Use safari
- Navigate to http://localhost:4000/components/modal/example-index.html
- Click on button Show Modal to open modal
- Click on button Cancel to close the modal
- See the trigger button Show Modal should be focused

3166 - Fix return focus for safari with modal

---

app/views/components/mask/test-number-mask-gauntlet.html
docs/CHANGELOG.md
src/components/locale/locale.js
src/components/mask/masks.js
test/components/mask/mask.e2e-spec.js
test/components/mask/masked-input-api.func-spec.js

Fixed enter all digits was not working for fr-FR with Locale.
Closes #3217
- Navigate to http://localhost:4000/components/mask/test-number-mask-gauntlet.html?locale=fr-FR
- For the Number: 1 000,00 field, enter `1234,`
- Should let you enter and the value should change to `1 234,`
- For the Millions: 1 000 000,00 field, enter 1234567,
- Should let you enter and the value should change to `1 234 567,`
- For the Billions: 1 000 000 000,00 field, enter 1234567890,
- Should let you enter and the value should change to `1 234 567 890,`
- Also see …

3217 - Fix enter all digits for fr-fr with locale

---

app/views/components/popdown/test-first-last-tab-custom-elements.html
app/views/components/popdown/test-first-last-tab-custom.html
app/views/components/popdown/test-first-last-tab.html
docs/CHANGELOG.md
src/components/popdown/popdown.js
test/components/popdown/popdown.e2e-spec.js

Added support for tabbing into and exit out of the Popdown.
Closes #3218
http://localhost:4000/components/popdown/test-first-last-tab.html
http://localhost:4000/components/popdown/test-first-last-tab-custom.html
http://localhost:4000/components/popdown/test-first-last-tab-custom-elements.html
- Click or tab into the first Date field
- Press tab (the popdown opens, and the first field should be focused)
- Press tab (the second field in the popdown should be focused)
- Press tab (the popdown should dismiss, and the next field …

3218 - Add support for tab in and out with popdown [v4.25.x]

---

app/views/components/mask/test-input-type-numeric.html
src/components/mask/mask-input.js
test/components/button/button-api.func-spec.js
test/components/popupmenu/popupmenu.func-spec.js

This PR is a Q/A follow up issue for PR #3322, which fixes a couple things:
- The original issue was that the number input field was not allowing the user to enter leading zeroes. This wasn't a bug with the component, but was an issue with the sample not having the `allowLeadingZeroes` setting turned on.  The sample has been updated to allow leading zeroes.
- It was possible to enter double decimal points on `input[type="number"]` fields, due to issues with detection of non-numeric characters specifically on these fields.  The ability to do this has been removed.
Closes #3315 
- Pull this …

3315 - Prevent masks on number input fields from allowing double decimal points [v4.25.x]

---

src/components/badges/_badges.scss
src/components/dropdown/_dropdown.scss
src/components/tag/tag.js
test/components/tag/tag.func-spec.js

This PR fixes a couple issues:
- Incorrect icon placement on IE11 when using the Linkable tag (#3113).
- There was an issue when using Tags in NG (issue number TBD) where the extra CSS class for changing state/color wouldn't match the new component setting.  This PR fixes the Tag to add/remove the correct classes to match the setting.  This is needed to facilitate fixes on the NG side, coming in another PR.
Closes #3113 
Pull this branch, build, run the app.  Then:
_Test IE for correct icon placement:_
- Open http://localhost:4000/components/tag/example-linkable.html?theme=uplift&variant=li …

3113/3114 - Q/A improvements for the Tags Component / Fix NG Issues [v4.25.x]

---

docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss

Fixed focus in date picker field was not aligning with Datagrid.
Closes #3350
- Navigate to http://localhost:4000/components/datagrid/example-placeholder.html
- Click on any cell in column `Order Date`
- See it should be aligned while in edit mode

3350 - Fix focus align in date picker field with datagrid [v4.25.x]

---

docs/CHANGELOG.md
src/components/accordion/_accordion-uplift.scss
src/components/accordion/_accordion.scss
src/components/applicationmenu/_applicationmenu-uplift.scss
src/themes/theme-uplift-contrast.scss
src/themes/theme-uplift-dark.scss
src/themes/theme-uplift-light.scss
test/components/button/button-api.func-spec.js

This PR fixes misaligned placeholder text in Application Menu Searchfields on the Vibrant theme.
Closes #3055
Closes #3364 
Pull this branch, build, run the app.  Then:
_Test placeholder text alignment:_
- Open http://localhost:4000/components/applicationmenu/example-filterable?theme=uplift&variant=light in Firefox
- Look at the empty searchfield and ensure its placeholder text is aligned vertically in the center of the input field.
_Test JP bullet point alignment:_
- Open http://localhost:4000/components/applicationmenu/test-six-levels.html?locale=ja-JP
- Expand the "Level 1" app menu …

3055 - Fix alignment of placeholder text in App Menu Searchfields in Vibrant theme [v4.25.x]

---

src/components/dropdown/_dropdown-uplift.scss
src/components/dropdown/_dropdown.scss
test/components/popupmenu/popupmenu.func-spec.js

This PR fixes a bug on text/icon alignments of Tags within the Multiselect component in some browsers.
Closes #3370
- Open http://localhost:4000/components/multiselect/example-index and http://localhost:4000/components/multiselect/example-index?theme=uplift in Firefox, IE, and Edge on a Windows machine.  Ensure the text/icon alignment looks right.

3370 - Fix IE/Edge/Firefox icon alignment on Multiselect Tags [v4.25.x]

---

app/views/components/datagrid/test-editable-lookup.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid-uplift.scss
src/components/datagrid/_datagrid.scss
src/components/searchfield/_searchfield-uplift.scss
src/themes/theme-uplift-light.scss

Went to fix the padding on this issue so that the editor will not overlap and noticed some issues which i fixed.
- search field icon was out of alignment in uplift
- the datagrid sort color was invisible in uplift (light)
May require test (Visual test) adjustments?
Fixes #3160 
- go to http://localhost:4000/components/datagrid/test-editable-lookup.html
- test this page in all themes and variants for the following:
- expand the search toolbar and type - icons should be align OK
- edit the lookup field (product id) and this should align -> also test this in all three row heights 
- in uplift …

3160 - Fix lookup layout issues and padding [v4.25.x]

---

src/components/datagrid/_datagrid-uplift.scss
src/components/datagrid/_datagrid.scss

Fixed focus in date picker field for vibrant theme was not aligning with Datagrid.
Closes #3350
- Navigate to http://localhost:4000/components/datagrid/example-placeholder.html?theme=uplift
- Click on any cell in column `Order Date`
- See it should be aligned while in edit mode
- Focus cell style `blue border, shadow` should not cut off

3350 - Fix date picker focus align for vibrant theme with datagrid [v4.25.x]

---

docs/CHANGELOG.md
scripts/data/expected-files.json
src/components/splitter/_splitter-uplift.scss
src/components/splitter/_splitter.scss
src/components/splitter/splitter.js
src/core/_controls-uplift.scss

The splitter destroy event did not remove the expand/collapse button. Also adjust the icon for uplift.
Fixes #3371 
- go to http://localhost:4000/components/splitter/test-collapse-button.html?theme=uplift&variant=light
- in the console type:
```
$('#splitter').data('splitter').destroy()
$('#splitter').splitter({'collapseButton': true})
```
- the top expand button should still work.

3371 - Fix destroy and uplift for expand button on the splitter

---

app/views/components/validation/test-just-error-class.html
docs/CHANGELOG.md
src/components/validation/validation.jquery.js
test/components/validation/validation.e2e-spec.js

If a field just had a error class on it then the removeMessage function would fail to remove it. This used to work in older versions before adding different message types.
Fixes #3318 
- go to http://localhost:4000/components/validation/test-just-error-class.html
- click the button
- class / red border should be removed

3318 - Remove error class in removeMessage

---

app/views/components/datagrid/test-reload-focus.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed focus on reload data was forced to be on active cell with Datagrid.
Closes infor-design/enterprise-ng#358
- Navigate to http://localhost:4000/components/datagrid/test-reload-focus.html
- Click on any cell in grid to get focused
- Click on `Input Textbox` and start typing
- Every keystroke, grid should reload data with one less row
- And focus should remain on `Input Textbox`

358 - Fix focus on reload data with datagrid

---

docs/CHANGELOG.md
src/themes/theme-uplift-contrast.scss

**Datagrid**: It fixes hover background color when hovering in uplift high contrast.
Closes https://github.com/infor-design/enterprise/issues/3338
- Navigate to http://localhost:4000/components/datagrid/example-alternate-row-shading.html?theme=uplift&variant=contrast
- Make sure you're in vibrant theme and high contrast variant.
- Play it around. Hover state shouldn't be the same as the alternate row background color.

3338 - Fix hover color in uplift high contast in Datagrid

---

app/views/components/datepicker/example-custom-format.html
docs/CHANGELOG.md
src/components/locale/locale.js
src/components/validation/validation.js

Fixed setting date format with comma character was not working with Datepicker.
Closes #3008
- Navigate to http://localhost:4000/components/datepicker/example-custom-format.html
- Open last Datepicker `Uses Commas (MMM d, yyyy)`
- Choose any date
- Click somewhere else to blur from field
- Should remain date in field fine

3008 - Fix comma in format with datepicker

---

docs/CHANGELOG.md
src/components/applicationmenu/_applicationmenu-uplift.scss
src/components/applicationmenu/_applicationmenu.scss
src/core/_config.scss
src/themes/theme-uplift-contrast.scss
src/themes/theme-uplift-dark.scss
src/themes/theme-uplift-light.scss

Fixed overlap button when label is too long, and aligned dropdown icon in application menu uplift theme. Adjust the `max-width` a bit of span inside of the button will do the trick. This bug occurs when the application menu contains a lot of menus (which the scrollbar will appear). 
This will also fix the focus state to not also overlap on accordion content container.
Closes https://github.com/infor-design/enterprise/issues/3133
- Navigate to http://localhost:4000/components/applicationmenu/example-menubutton.html?theme=uplift&variant=contrast&col …

3133 - Add fix for overlapping button in application menu uplift theme

---

app/views/components/applicationmenu/test-all-plusminus.html
app/views/includes/applicationmenu-all-plusminus.html
docs/CHANGELOG.md
src/themes/theme-uplift-contrast.scss
src/themes/theme-uplift-dark.scss
src/themes/theme-uplift-light.scss

This PR improves the color contrast between font and background colors in the Application Menu in the Vibrant theme.  Previous changes from #3298 and #3356 modified token colors, which inadvertently lowered the amount of contrast between font and background colors on all variants of the Vibrant theme.
Closes #3400
- Open http://localhost:4000/components/applicationmenu/example-personalized-roles.html?theme=uplift&variant=light
- Also open http://4240-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=uplif …

3400 - Vibrant theme App Menu colors Q/A [v4.25.x]

---

app/views/components/mask/test-input-type-numeric.html
app/views/components/mask/test-number-leading-zeroes.html
docs/CHANGELOG.md
src/components/mask/mask-input.js
src/components/mask/masks.js
test/components/mask/mask.func-spec.js

This PR fixes a regression in the way Number Masks handle leading zeroes on standard input fields (read: not number input fields).  Previously it was not possible to add more than one zero to the integer part of a Number Mask on an input field that was configured to allow leading zeroes.  It was also not possible to type a zero, then any other number in these same fields.  These issues are now resolved.
Closes #3315 
- Open http://localhost:4000/components/mask/test-number-leading-zeroes
- In the "Text Inputs" section, choose either of the inputs that …

3315 - Fix standard inputs not allowing leading zeroes in Number Masks [v4.25.x]

---

src/components/badges/_badges-uplift.scss
src/components/badges/_badges.scss

This PR makes general across-the-board adjustments to the alignment of text/icons/line height on Tag components in all browsers.  This was due to misalignments found on this component in Windows Chrome, which uncovered a difference in line-height of the font between Windows/Mac platforms.
Closes #3410
Pull this branch, build, and run the app.  Then test the following pages in every browser/os combination you can think of:
- http://localhost:4000/components/tag/example-index.html
- http://localhost:4000/components/tag/example-index.html?theme=uplift&variant=light
- …

3410 - Fix tag text/icon alignment on Windows [v4.25.x]

---

docs/CHANGELOG.md
src/components/cards/_cards-uplift.scss
src/components/header/header.js
src/components/listview/_listview.scss
src/themes/theme-soho-contrast.scss
src/themes/theme-uplift-contrast.scss
src/themes/theme-uplift-dark.scss
src/themes/theme-uplift-light.scss

Fixed the scrollbars on windows, the changes to colors in uplift made them come out very ugly.
Also fixed a few minor things in list and datagrid in uplift themes to improve the contrast and display.
Fixes #3413 
- open a windows 10, chrome (latest) VM
- test http://localhost:4000/components/datagrid/example-frozen-columns.html - in all 6 themes, only in uplift mode (3 uplift themes) the scrollbars will change (not in soho)
- test http://localhost:4000/components/listview/example-index.html - in all 6 themes, only in uplift mode (3 uplift themes) the scrollbars will change (not in soho) …

3413 - Improve the colors of custom scrollbars in windows [v4.25x]

---

docs/CHANGELOG.md
src/components/colorpicker/_colorpicker.scss
src/components/dropdown/_dropdown.scss
src/core/_config.scss
src/themes/theme-soho-contrast.scss
src/themes/theme-soho-dark.scss
src/themes/theme-uplift-contrast.scss
src/themes/theme-uplift-dark.scss
src/themes/theme-uplift-light.scss

This PR fixes color inconsistencies of the icons when the fields are in readonly state for dropdown, datepicker, and colorpicker. 
Additional fixes
- Hovering on icon color shouldn't look active. It should still be the same.
- Hovering on the field shouldn't change the border color.
Following the icon colors (for all themes) of the file upload example. 
See: https://design.infor.com/code/ids-enterprise/latest/demo/components/fileupload/example-index
Closes https://github.com/infor-design/enterprise/issues/3176
Open the three test pages from …

3176 - Fix color inconsistencies of the icons

---

docs/CHANGELOG.md
src/components/calendar/_calendar.scss
src/components/calendar/calendar.js
src/components/week-view/week-view.js

Fixed some issues with Calendar.
- Link was not working on monthview to switch to day view when clicked on more events.
- Date selection was not persist when switching from month view to week view to day view.
- On week or day view, clicking on any event was adding `#` to the url.
Closes #3181
Closes #3319
- Navigate to http://localhost:4000/components/calendar/test-ajax-events.html
- It should land on month of `August 2018`
- Click on `+3 more` link for date `22nd`
- It should switch to day view to show all the events on that day
- Refresh the …

3181/3319 - Fix more event link and selected date on week view with calendar

---

docs/CHANGELOG.md
src/components/locale/locale.js
test/components/locale/locale.func-spec.js

Fixed formatDate() method was not working for es-419 with Locale.
Closes #3363
- Navigate to http://localhost:4000/components/datepicker/example-index?locale=es-419
- Run in console `Soho.Locale.formatDate('22 ene. 2020 00:00', Soho.Locale.calendar().dateFormat.datetime);`
- It should return `"22 ene. 2020 00:00"`

3363 - Fix formate date for es-419 with locale

---

docs/CHANGELOG.md
src/components/accordion/_accordion.scss
src/components/accordion/accordion.js
src/components/applicationmenu/applicationmenu.js
src/components/autocomplete/autocomplete.js
test/components/accordion/accordion-api.func-spec.js

This PR fixes a handful of bugs in the App Menu's Accordion when combined with a Searchfield for filtering available headers.
Closes #3131 
Pull this branch, build, run the app.  Then check the following:
*Issue 1 - Check visibility of parent headers that don't match the filter, but contain children that do:*
- Open http://localhost:4000/components/applicationmenu/example-filterable.html
- In the input, type "role".  The accordion headers not containing the word "role" should all be filtered out.  The ones containing the word "role" should all be expanded, despite this accordion being …

3131 - Fix app menu accordion filtering issues

---

docs/CHANGELOG.md
src/components/toolbar/toolbar.js

This PR fixes an issue where some `destroy()` methods being called in the Toolbar component's `teardown()` method were not typechecking for the method, and sometimes would incorrectly try to call it on an object or data property defined as `button`.  This PR adds a check for a function to these calls before they're run.
Closes #3449
- Need to run this PR against the latest NG to see the effect.
- Open http://localhost:4200/ids-enterprise-ng-demo/toolbar-state
- Open a developer tools console
- Use the Application menu to switch to another standard toolbar test, such as …

3449 - Added typecheck for `destroy` functions in Toolbar teardown.

---

app/views/components/modal/test-fileupload-scroll.html
docs/CHANGELOG.md
src/components/fileupload/fileupload.js

Fixed tabbing out was causing to modal dialog disappear with Fileupload.
Fixes #3458
- Navigate to http://localhost:4000/components/modal/test-fileupload-scroll.html
- Click on the button `Show Modal`
- The modal should display and focus should be in the first field
- Use tab key to tab through all the fields, file upload in the last field
- Modal dialog should not disappears when tabbing out of the file upload field

3458 - Fix modal disappear on tabbing out with fileupload

---

src/components/checkboxes/_checkboxes.scss
src/components/icons/_icons-uplift.scss
src/components/icons/_icons.scss

Fixed additional layout issues in firefox and ios.
Fixes #3147 
- open http://localhost:4000/components/checkboxes/example-index.html
- test the dirty indicator in Chrome, Firefox and IOS (ipad)
If its close i'm leaving this not worrying about a half pixel

3147 - Fix checkbox alignment in checkboxes and dirty indicators

---

app/views/components/datagrid/example-fixed-header.html
app/views/components/datagrid/example-reorder.html
src/components/datagrid/_datagrid-uplift.scss
src/components/datagrid/_datagrid.scss
src/components/textarea/textarea.js

A bug in css caused drag drop of columns to not work in IE11. Fixed this and also sorted out some icon placement issues on the header row.
Fixes #2565 
- go to http://localhost:4000/components/datagrid/example-reorder.html?theme=uplift&variant=light
- hover the columns and check the drag drop icon placement in both filter row and no filter row
- open http://localhost:4000/components/datagrid/example-grouped-headers (or same issue really on http://localhost:4000/components/datagrid/example-reorder.html) in IE. Should be able to drag the columns in IE as well.

2565 - Fix ie drag columns and icon placement

---

docs/CHANGELOG.md
src/components/calendar/calendar-shared.js
src/components/calendar/calendar.js
src/components/locale/locale.js

Fixed adding an event was inconsistent in Safari with Calendar.
Closes #3079
- Use Safari
- Navigate to http://localhost:4000/components/calendar/example-index.html
- Click `Today`
- Click `+` button and Click `Add Event (Modal)`
- Make sure the picked date in `From` and `To` both today's date and the All day is checked
- See the added event should only be for today's date

3079 - Fix add event in safari with calendar

---

docs/CHANGELOG.md
src/components/radios/_radios.scss

Fixed radio group alignment issue, radio group was overlapping fields.
Closes #3466
- Navigate to http://localhost:4000/components/form/example-compact-mode.html
- Scroll to Radio Group section
- See fields should not overlap

3466 - Fix radio group alignment with forms

---

app/views/components/datagrid/test-expandable-row-frozen-columns-bothsides.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed using rowTemplate/expandableRows and frozenColumns was not rendered properly with Datagrid.
Closes #2867
- Navigate to http://localhost:4000/components/datagrid/test-expandable-row-frozen-columns.html
- Click on `+` button in row-1
- Row should expands including the left pane
- Click on `+` button in row-4
- Row-1 should collapse and this row-4 should expands including the left pane
- http://localhost:4000/components/datagrid/test-expandable-row-frozen-columns-bothsides.html
- Use same steps for frozen left and right side
**Included in …

2867 - Fix expandable rows and frozen columns with datagrid

---

docs/CHANGELOG.md
src/components/datagrid/_datagrid-uplift.scss
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js
src/components/modal/_modal.scss
src/utils/utils.js

Fixed reset to default was not working properly with Datagrid.
Closes #3487
- Navigate to http://localhost:4000/components/datagrid/example-custom-toolbar.html
- Click on `...` button in grid toolbar
- Select `Personalize Columns`
- Uncheck `Product ID`
- Click on modal button `Close`
- See column `Product ID` should be hidden
- Click again on `...` button in grid toolbar
- Select `Reset to Default`
- See column `Product ID` should show again

3487 - Fix reset to default with datagrid

---

docs/CHANGELOG.md
src/components/form-compact/_form-compact-uplift.scss
src/components/form-compact/_form-compact.scss

Fixed fileupload was not aligning with Forms Compact. Also fixed the checkboxes were not aligning for RTL in Uplift/Vibrant theme.
Closes #3483
- Navigate to http://localhost:4000/components/form-compact/example-index.html
- Check the alignment for fileupload
- Check checkboxes http://localhost:4000/components/form-compact/example-index.html?locale=ar-EG

3483 - Fix fileupload alignment with forms compact

---

src/components/place/place.js

This PR fixes a Q/A issue that cropped up due to changes on #3119, where using an RTL-based locale was sometimes incorrectly making tooltips/popovers set the position of their arrows on the wrong side of the element.  This issue has been fixed.
Closes #3119
- Open http://localhost:4000/components/popover/example-alternate-positions.html?locale=ar-EG
- Click both buttons and ensure the arrow appears on the side of the popover that faces the button.

3119 - Fix arrow placement on tooltip/popovers in some RTL situations [v4.26.x]

---

docs/CHANGELOG.md
src/themes/theme-soho-dark.scss
src/themes/theme-uplift-dark.scss

https://github.com/infor-design/enterprise/issues/3339
Changes the  background color in uplift dark for expandable searchfields when in a toolbar.
Fixes #3339
- open http://localhost:4000/components/datagrid/example-custom-toolbar.html?theme=soho&variant=dark
- expand the search 
- should have a background subtle fille
- open http://localhost:4000/components/datagrid/example-custom-toolbar.html?theme=uplift&variant=dark
- expand the search 
- should have a background subtle fille

3339 - Change background color in uplift

---

docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss

When on IOS the tree text for the datagrid was very big because of -webkit-text-size-adjust: none; 
So did a reset on it here. Note that the bug is  inverse in reality. The tree text was too big, the other text was the normal / correct size.
Fixes #3347 
- go to http://localhost:4000/components/datagrid/example-tree.html?theme=uplift&variant=contrast
- open it on IOS (iphone x for example)
- the tree text should be the same size as other text

3347- Fix large IOS text in Datagrid Tree

---

src/components/header/header.js

This PR fixes a small bug in the implementation of the EP demoapp's theme switcher button (which is also used in the NG demoapp), which didn't properly support being used in a Flex Toolbar.  There was a previously a conflict when firing the `selected` event.  This PR fixes that issue.
Related to infor-design/enterprise-ng#745
- Pull this branch, build, `npm link` or symbolic link to a working copy of [`enterprise-ng`](https://github.com/infor-design/enterprise-ng), and build/run NG.
- Open http://localhost:4200/ids-enterprise-ng-demo/
- Use the theme switcher to select a different …

NG#745 - Allow theme switcher to work when implemented in a Flex Toolbar

---

docs/CHANGELOG.md
src/components/swaplist/_swaplist-uplift.scss
src/components/swaplist/_swaplist.scss

Fixed lists were overlapping on uplift theme with Swaplist.
Closes #3452
- Navigate to http://localhost:4000/components/swaplist/example-index.html?theme=uplift&variant=light
- See on all variant `light`, `dark` and `high contrast`
- List should not look overlapping

3452 - Fix overlapping on uplift theme with swaplist

---

app/views/components/datagrid/test-expandable-row-multiselect.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js

When using shift key to multiselect rows with the expandable row feature enabled. The wrong rows would be selected. This PR addresses this. Also made the row activation go away in this configuration as it was confusing as it looked like the row was selected
Fies #2302 
- go to http://localhost:4000/components/datagrid/example-expandable-row-one-only.html
- row should be azure on expand
- go to http://localhost:4000/components/datagrid/test-expandable-row-multiselect
- row should not be azure on expand
- click row 2 checkbox
- hold shift key down
- click row 5c heckbox
- rows in-between …

2302 - Add fix for using multiselect and expandable row

---

app/views/components/datagrid/test-columns-stretch-column.html
src/components/datagrid/datagrid.js

1. Correct the stretchcolumnidx on firstrender
2. Correct an issue with some filter types types (date, dropdown) and the totalWidths value
Closes #3481 
1) 
1. http://localhost:4000/components/datagrid/test-columns-stretch-column.html
2. Take note of how wide the last column is set
3. reduce the size of the browser window
4. Refresh the page.
2)
(comment out line 928 of datagrid.js to show the original behaviour)
1. http://localhost:4000/components/datagrid/test-columns-stretch-column.html
2. Open the order date and filter and select a value
(The width is outputted to the console, the …

3481 - Datagrid: firstrender and getStretchColumnIdx

---

docs/CHANGELOG.md
src/components/colorpicker/_colorpicker-uplift.scss
src/components/colorpicker/_colorpicker.scss

The colorpicker icon caret is too much close to the right edge of the field. Added also some fix in modal section where it appears that the caret icon is not vertically align.
Closes https://github.com/infor-design/enterprise/issues/3508
- Navigate to http://localhost:4000/components/colorpicker/example-sizes.html?theme=uplift&variant=light
- Caret icons should not too close to the right edge of the field
- Test also the modal sample of colorpicker
- http://localhost:4000/components/colorpicker/test-modal.html?theme=uplift&variant=light
- Open the …

3508 - Fix color picker icon position

---

docs/CHANGELOG.md
src/components/bar/bar.js

Fixed bar chart was not resizing on homepage widget resize.
Closes #2669
- Navigate to http://localhost:4000/components/homepage/example-filled
- Resize the page, so the widget size changes
- See chart should resize fine

2669 - Fix resize with bar chart

---

docs/CHANGELOG.md
src/components/tabs/_tabs.scss

Fixing the position of the error icon that's too close to the border upon focus state.
Closes https://github.com/infor-design/enterprise/issues/3544
- Navigate to http://localhost:4000/components/tabs/example-dropdown-tabs.html
- Click the Plastic tab and go to Plates
- Tab out each input field to show the error/validation
- The Plastic tab should also display the error icon beside of it
- Click other tab until the focus show
- Then go back to the Plastic tab (This should highlight/focus)
- Error icon should have enough space and not too close to …

3544 - Fix error icon too close to the border upon focus state

---

docs/CHANGELOG.md
src/components/blockgrid/blockgrid.js
src/components/locale/locale.js

The NG example did not set a data.id so the selection did not show any info within the events. To fix this i default the index to the count if its empty. Also changed internal calls to call the non-deprecated method.
Fixes infor-design/enterprise-ng#748
**Enterprise Testing**
- load http://localhost:4000/components/blockgrid/example-singleselect.html
- Select a block in the grid
- Check the console in browser developer tools
- Notice how selectedRows contains the idx attribute and it does have a proper value.
- notice no deprecated methods
- test http://localhost:4000/components/blockgrid/ …

748 - Remove deprecated calls and default the index in Block grid

---

app/views/components/hierarchy/test-paging.html
docs/CHANGELOG.md
src/components/hierarchy/hierarchy.js

Removing the following deprecated options from Hierarchy control.
- paging
- mobileView
Closes #3579
- Paging example can be tested at http://localhost:4000/components/hierarchy/test-paging.html
- Apply changes to verify the paging still work
- test other examples http://localhost:4000/components/hierarchy/

#3579 - Hierarchy, Deprecating paging option and mobileView option.

---

docs/CHANGELOG.md
src/components/busyindicator/busyindicator.js

Fixed js error was showing when a display delay, the busy-indicator parent removed and added via *ngIf before the busyindicator shown.
Closes infor-design/enterprise-ng#703
- Pull and build ([NG master](https://github.com/infor-design/enterprise-ng.git))
- Replaced the [zipped files](https://github.com/infor-design/enterprise-ng/files/4052831/busyindicator.zip) provided in original issue infor-design/enterprise-ng#703 to `src/app/busyindicator/`
- Navigate to …

703 - Fix js error with busy indicator

---

docs/CHANGELOG.md
src/components/colorpicker/colorpicker.js
test/components/colorpicker/colorpicker.e2e-spec.js

Reset/none swatch doesn't have a default value to change the text color when selecting it. Added a `000000` value as a default color.
Closes https://github.com/infor-design/enterprise/issues/2035
- Navigate to http://localhost:4000/components/editor/example-index.html
- Select some amount of text then change the text color you want
- Select it again then change it to none swatch
- Text should change to black

2035 - Added font color for none/rest swatch

---

app/views/components/applicationmenu/test-click-event-propagation.html
docs/CHANGELOG.md
src/components/accordion/accordion.js
test/components/applicationmenu/applicationmenu.e2e-spec.js

This PR removes some code from Accordion headers that was stopping external click event handlers from propagating and ultimately running in most cases.  This was causing issues when developers attempted to run their own click handlers on accordion headers outside of the component, which was a problem in Angular environments.
Closes infor-design/enterprise-ng#321
- Open http://localhost:4000/components/applicationmenu/test-click-event-propagation.html
- Click any of the accordion headers.  They should correctly fire a toast containing their …

NG#321 - Allow click events attached to accordion headers to propagate

---

docs/CHANGELOG.md
src/components/datepicker/datepicker.js
src/components/monthview/_monthview.scss

The popover adds height causing the datepicker to extend/expand. And also, the dates overlap in the monthview container on a smaller view. 
The solution supports portrait and landscape view. For some reason, testing it on landscape position, the datepicker (when open) doesn't behave the same way when it's in portrait.
Solution
- Removed height and adjust the min-height when the window height is less than 400
- Adjusted height and width on a smaller view via media queries.
Closes https://github.com/infor-design/enterprise/issues/3569
- Open on …

3569 - Fix popover height and datepicker layout on smaller/mobile view

---

app/views/layout-embedded.html

We are changing the demos to use uplift but this change is needed for when you switch tabs.
https://github.com/infor-design/website/issues/861
- go to http://localhost:4000/components/typography/example-index.html?theme=uplift&variant=light&layout=embedded
- hit the tabs
- theme should stay as uplift

Fix embedded layout to use uplift [v4.26.x]

---

app/views/components/dropdown/test-in-modal-content.html
docs/CHANGELOG.md
src/components/dropdown/dropdown.js

This PR makes changes to the Dropdown component's calculation of surrounding scrollable regions when invoked inside a Modal. Previously, a custom scrollable area would not be detected by the Dropdown, causing its list to remain open if the scrolling region was scrolled by the user.  This bug is now fixed.
Closes #2650
- Open http://localhost:4000/components/dropdown/test-in-modal-content.html
- Check the radio button that says "`test-content` (`scrollable-y` section)"
- Click "Create Modal".
- When the modal opens, click the Dropdown to open the …

2650 - Allow Dropdowns to close their lists when scrolling a custom Modal region

---

src/components/processindicator/_processindicator-uplift.scss
src/components/processindicator/_processindicator.scss

This is an additional fix for #3509 failed QA ticket. Some icons on other devices and browsers (probably on Edge).
Closes #3509 
- Test and open to different devices or use browserstack. Test also to all browsers
- Navigate to http://localhost:4000/components/processindicator/example-index.html
- Process indicator icons should centered/aligned properly in circle indicators
- Test this also on uplift theme

3509 - Add fix on misalignment of process indicator icons

---

src/components/datepicker/datepicker.js

A follow up fix for failed QA ticket. Issue has been reproduced via uplift theme.
Issue:
- Datepicker extends it's height on mobile view in uplift theme
Closes https://github.com/infor-design/enterprise/issues/3569
- Open in browserstack in iPhone 11 Pro, safari browser
- Navigate to http://localhost:4000/components/datepicker/example-range.html?theme=uplift&variant=light
- Scroll to the bottom of the page
- Select/Click Range - Max (2) Days input field
- Then click datepicker icon
- The datepicker monthview shouldn't look odd (Issue: datepicker …

3569 - Fix responsive layout of datepicker in uplift

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/lookup/lookup.js

Fixed selected values were clearing when use server side data with Lookup.
Closes infor-design/enterprise-ng#588
- Pull and build NG branch ([588-lookup-selected-serverside](https://github.com/infor-design/enterprise-ng/tree/588-lookup-selected-serverside))
- Navigate to http://localhost:4200/ids-enterprise-ng-demo/lookup
- Open lookup `Products (Async Results) Multi Select` (last one on the page)
- Select the first value (or any value)
- Click Apply
- Re-open …

588 - Fix selected values with lookup

---

app/views/components/validation/test-error-on-tab-with-addmessage.html
docs/CHANGELOG.md
src/components/tabs/_tabs-uplift.scss
src/components/tabs/_tabs.scss
src/components/validation/validation.jquery.js
src/components/validation/validator.js
test/components/colorpicker/colorpicker-aria.func-spec.js
test/components/validation/validation.e2e-spec.js

When calling addMessage the api would not call setIconOnParent and populate the parent tab with an error icon.
Fixes infor-design/enterprise-ng#711 
- go to http://localhost:4000/components/validation/test-error-on-tab-with-addmessage.html
- toggle the button and the icon should hide and show on both the field and the tab
- check the styling on both themes

711 - Made addMessage show the error on the parent

---

src/components/tooltip/tooltip.js
src/utils/dom.js

This PR fixes some recent changes in Tooltip, which were using `HTMLElement.classList.add()/remove()` in some places where an SVG element may be present as the trigger element.  This is not supported in IE11 and was causing Javascript console errors, along with preventing higher level components like Datepicker from opening.  This has now been fixed.
Closes #3659 
- Open http://localhost:4000/components/datepicker/example-timeformat.html in IE11
- Click any of the triggers to open the Datepickers. They should open with no issues.
- Inspect the …

3659 - Fix Tooltip Trigger code to allow SVG triggers [v4.27.x]

---

app/views/components/bullet/example-format.html
docs/CHANGELOG.md
src/components/bullet/bullet.js
test/components/bullet/bullet-api.func-spec.js

Added support to format ranges and difference values with Bullet Chart.
Closes #3447
- Navigate to http://localhost:4000/components/bullet/test-formate-axis.html
- See the values should formatted like `1M` or `200k` etc.

3447 - Add support to format values with bullet chart

---

docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/core/_config.scss
src/themes/theme-soho-contrast.scss
src/themes/theme-soho-dark.scss
src/themes/theme-uplift-contrast.scss
src/themes/theme-uplift-dark.scss

The group line color was not visibile in uplift dark mode so made a new variable.
Fixes #3649
- go to http://localhost:4000/components/datagrid/example-grouping-totals.html?theme=uplift&variant=dark
- close some group rows
- should be a visible line between the group rows now
- test all six modes

3649 - Fix darkmode uplfit group line color

---

src/components/trackdirty/trackdirty.js
test/components/editor/editor.e2e-spec.js

LM QA found one more issue switching an extra time and reseting the dirty tracker on editor.
Fixes #3670
1. go to http://localhost:4000/components/editor/test-dirty-tracking-reset.html
1. change some text
1. dirty indicator will show
1. click the button and dirty indicator will reset
1. switch to HTML view
1. change some text
1. dirty indicator will show
1. click the button and dirty indicator will reset
1. switch to Visual mode
1. change some text
1. dirty indicator will show
1. click the button and dirty indicator is not resetting

3670 - Additional fix for dirty editor reset [v4.27.x]

---

src/components/datagrid/datagrid.js

QA didnt work well with frozen columns and colspans. This adds an additional fix and fixes the size of the columns in safari.
Fixes #3416
- as before try these in Mac Safari and Mac Chrome....
- go to http://localhost:4000/components/datagrid/test-frozen-columns-with-colspan.html
- in the example code edit the `frozenColumns` section temporarily..
- try with all 3 commented out
- try with each commented out
- in all cases the columns should render the same (QA can not test this just test the example)
```
frozenColumns: {
// left: ['selectionCheckbox'],
left: ['selectionCheckbox', …
```

3416 - Add additional fixes for safari with frozen colspan [v4.27.x]

---

app/views/components/lookup/test-custom-click.html
app/views/components/lookup/test-custom-modal.html
app/views/components/lookup/test-multiple-custom-modals.html
app/views/components/modal/test-no-autofocus.html
src/components/lookup/lookup.js
src/components/modal/modal.js
src/utils/utils.js
test/components/modal/modal.e2e-spec.js

This PR fixes a bug introduced in #3633 that created an infinite loop related to a new `focusin` event listener in nested modals.
Closes #3682 
- Open http://localhost:4000/components/lookup/test-modal-lookup.html in IE11
- Click "Select State".  The Modal should open.
- Click the Lookup's trigger button.  The Lookup should open.
- When the Lookup is displayed, it should be possible to navigate quickly and navigate with the keyboard.  There should be no JS console errors.
Additionally, you can test this on this page in IE11.  There should be no …

3682 - Fix infinte loop in nested modals [v4.27.x]

---

app/data/orgstructure-original.json
docs/CHANGELOG.md
src/components/hierarchy/hierarchy.js

Added a check  in `getActionMenuItems` (`src/components/hierarchy/hierarchy.js`). If `a.data.type === 'separator'` the function will render a list item with a class of separator in the action menu list.
closes #3636 
- navigate to http://localhost:4000/components/hierarchy/example-context-menu-with-details.html
- click the action menu in the first card. You should now see a separator above the "Delete" menu item.

3636 - Add separator support in Hierarchy action menus

---

src/components/editor/_editor.scss
src/components/editor/editor.js

QA uncovered an issue when switching theme while the source view is open. This is a fix for that.
Fixes #3688 
- go to http://localhost:4000/components/editor/example-index.html?theme=soho&variant=contrast
- click the HTML button to go to source view
- change them to vibrant
- try combinations of themes , switching and having HTML vs VISUAL view open

3688 - Fix a bug switching themes in source mode [v4.27.x]

---

docs/CHANGELOG.md
src/themes/theme-soho-dark.scss
src/themes/theme-uplift-dark.scss

Make the swap buttons color more noticeable as a disabled button in dark variant subtle theme. This fix shouldn't affect other themes/variants.
Closes https://github.com/infor-design/enterprise/issues/3709
- Navigate to http://localhost:4000/components/swaplist/example-disable-dragging.html
- Theme should be `Subtle` and the Variant should be `Dark`
- The disabled swap buttons should now look disabled and not same as the active

3709 - Fix disabled swap buttons color in dark variant

---

src/components/trackdirty/trackdirty.js

The dirty tracking in editor did not work in source view in IE11. This is a fix
Fixes #3720 
- open IE 11
- go to http://localhost:4000/components/editor/test-dirty-tracking-reset.html
- switch to HTML view
- change text
(these are shorter steps than the issue - but that whole view didnt work in IE 11)

3720 - Fix IE11 editor dirty tracking bug [v4.27.x]

---

app/views/components/datagrid/test-empty-message-two-rows.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js

Added an important bug to 4.27. The empty message was showing in some incorrect cases, specifically when the number of filter elements equals the number of visible elements. Fixed this
Fixes #3597
- go to http://localhost:4000/components/datagrid/test-empty-message-two-rows.html
- filter on Product id - contains - 22 
- one of one record should show 
- no empty message should show
- test any samples in http://localhost:4000/components/datagrid with "empty + message" in the name

3697 - Add a fix for incorrect empty message [v4.27.x]

---

app/views/components/popupmenu/example-icons.html
app/views/components/popupmenu/example-shortcut-text.html
docs/CHANGELOG.md
src/components/popupmenu/_popupmenu.scss
src/components/popupmenu/readme.md

Adds a css class `shortcut-text` to display shortcut keys in contextmenu
closes #3490 
- pull branch
- go to http://localhost:4000/components/popupmenu/example-shortcut-text.html
- open menu and you should see examples, ie `Ctrl+Shift+Right`

3490 - Add shortcut display to contextmenu

---

docs/CHANGELOG.md
src/components/icons/_icons-uplift.scss

The `plus-minus` icon in application menu breaks apart when zooming out the browser in IE11, uplift theme.
When zooming in or out, you'll encounter issues because of round and text rendering. Making sure that the elements and or layouts must survive a bit of stretching without breaking down.
Add up a `1px` on icon's height to get through when zooming out in IE11 only.
Closes https://github.com/infor-design/enterprise/issues/3070
- Navigate to http://localhost:4000/components/applicationmenu/test-six-levels.html?theme=uplift&variant=light and open …

3070 - Fix applicationmenu icons breaks apart when zoomed out in IE11

---

docs/CHANGELOG.md
src/components/radar/radar.js

Fixed labels were cutoff at desktop view with Radar Charts.
Closes #3510
- Navigate to http://localhost:4000/components/radar/example-hcm.html?theme=uplift&variant=light
- Resize browser window to desktop viewport
- See the labels should not cutoff

3510 - Fix labels alignment with radar charts

---

docs/CHANGELOG.md
src/components/dropdown/dropdown.js

Adds a function to check for tag element in the `touchend` and `touchcancel` event handler. If element being touched is a tag cancel the toggle and let the tag handle it.
closes #3640 
- pull branch
- check http://localhost:4000/components/multiselect/example-index.html or http://localhost:4000/components/multiselect/example-index.html?theme=uplift&variant=light on a mobile device browser.

3640 - Fix Multiselect tags dismiss button on mobile 

---

src/components/checkboxes/_checkboxes.scss

When checkboxes receive focus and they are offscreen in a scrollable container, they will not be scrolled into view automatically.  This is because the input element was positioned fixed and off-screen.  This addresses this issue by positioning it absolute and on-screen so it can be focused like other input elements.
**Related github/jira issue**:  
Fixes #3751
- Place a checkbox component on any page within a scrollable container and scroll so it's no longer visible.  In my case, I started with the sample page: https://design.infor.com/code/ids-enterprise/latest/demo/components/checkboxes/example-index
- Open Chrome Dev Tools
- Inside the element inspector, locate the `<form id="test-form">` element in the document.
- Set an …

3751 - Set position absolute and onscreen for checkboxes so they can be scrolled into view when focused.

---

app/views/components/modal/test-long-title-large-content.html
src/components/modal/_modal.scss

This is a follow up fix for https://github.com/infor-design/enterprise/issues/3479. The `-webkit-line-clamp` is not supported in IE11, so I created a pure CSS that will fix this issue. 
Closes https://github.com/infor-design/enterprise/issues/3479
- Open in IE11 browser (via browserstack or windows) and navigate to http://localhost:4000/components/modal/test-long-title-large-content.html
- Click `Show Modal` button
- The title should be multi line with ellipsis
- Tooltip should also work

3479 - Fix multiline ellipsis in IE

---

app/data/hc-john-randolph-dynamic-actions.json
app/views/components/hierarchy/example-stacked-ajax-popupmenu.html
src/components/hierarchy/hierarchy.js

Fix for https://github.com/infor-design/enterprise/issues/3760. Added an example where actions are dynamically loaded into actions menu for hierarchy cards. This reproduces the issue reported in https://github.com/infor-design/enterprise/issues/3760.
Closes #3760
1. Get new example from PR
2. Go to http://localhost:4000/components/hierarchy/example-stacked-ajax-popupmenu.html
3. Click on action menu button to get actions.
4. Notice the menu now sizes properly on the initial click.

Fix for 3760, Hierarchy, Context menu fails to size correctly when dynamically loading actions.

---

docs/CHANGELOG.md
src/components/accordion/_accordion.scss
src/components/applicationmenu/_applicationmenu-uplift.scss

This PR fixes a CSS bug on Android devices, where the bullet icon in the Application Menu appears larger and is not correctly aligned with text.
Closes #1429
- Open http://localhost:4000/components/applicationmenu/test-six-levels-icons.html on an Android device (I tested on a BrowserStack VM connected to a Samsung Galaxy S10)
- Use the hamburger to open the menu
- Open the "Level 1" header.  Find the "Level 2 List Item Header".  It should line up well versus the text, and the icons in the other adjacent headers.
- Keep navigating into "Level 2", "Level 3", etc. All the bulleted headers …

Change the size of bullets on App Menu/Accordion on Android devices

---

src/components/button/_button.scss

Fixd button was flow off on mobile.
Closes #3769
- Navigate to http://localhost:4000/components/button/example-index.html
- Resize browser window to small viewport (iPhone 5/SE on chrome devtools)
- See last `Action` button in `Tertiary`
- Should aligned fine
http://localhost:4000/components/contextualactionpanel/example-jquery.html
http://localhost:4000/components/contextualactionpanel/example-markup.html?theme=uplift&variant=light
- On small viewport
- See the button should have `...` ellipsis
- Button width not more than viewport width

3769 - Fix button was flow off on mobile

---

src/components/popupmenu/_popupmenu.scss

Fixes an IE11 issue that was found in QA
related to #3490  
- pull branch
- go to http://localhost:4000/components/popupmenu/example-shortcut-text.html in IE11
- Make sure the menu items with shortcut text are not broken into 2 lines. Here's a reference to the [bug](https://github.com/infor-design/enterprise/issues/3490#issuecomment-613909438) that was found

3490 - Fix IE11 shortcut text in context menu

---

app/views/components/autocomplete/test-focus.html
docs/CHANGELOG.md
src/components/autocomplete/autocomplete.js
test/components/autocomplete/autocomplete.e2e-spec.js

This PR fixes an issue on the Autocomplete list where it was previously possible for the Autocomplete list to incorrectly open after the input field has already lost focus, causing focus to become stolen by the autocomplete list.
Closes #3639
- Open http://localhost:4000/components/autocomplete/test-focus
- Focus the first input field
- Type "utah", then immediately press the Tab key.
- Focus should change to and remain on the second input field, and the Autocomplete list should not open.

3639 - Prevent Autocomplete List from opening after its Input field loses focus

---

app/views/components/hierarchy/example-stacked-ajax-popupmenu.html
src/components/hierarchy/_hierarchy-base.scss
src/components/hierarchy/hierarchy.js

-Fixed detail fields background color and arrow so it looks better when context menu has overflow.
-Fixed IE11 not loading error
-Fixed context menu arrow position so it centers on action menu button.
https://github.com/infor-design/enterprise/issues/3760
1. Get new example from PR https://github.com/infor-design/enterprise/pull/3761
2. Go to http://localhost:4000/components/hierarchy/example-stacked-ajax-popupmenu.html
3. Click on action menu button to get actions.
- Menu should size properly
- Menu arrow should center on action button
- Example should load properly in IE11
Example with …

Fix for issues found in #3760. IE11 fails to load, context menu arrow does not center on action menu button

---

docs/CHANGELOG.md
src/components/colorpicker/_colorpicker.scss
src/components/popupmenu/popupmenu.js

Fixes an issue where the color swatches shift when the colorpicker has a scrollbar. Adds a check for the colorpicker height and adds a class to modify the width to accommodate the scrollbar.
closes #2266
- pull branch
- go to http://localhost:4000/components/colorpicker/example-index.html and make sure the swatches don't shift over in a short viewport.

2266 - Fix Colorpicker swatches shifting in small viewport

---

app/views/components/fileupload-advanced/test-max-files.html
docs/CHANGELOG.md
src/components/fileupload-advanced/fileupload-advanced.js
src/components/fileupload/_fileupload-uplift.scss
src/components/fileupload/_fileupload.scss
src/components/locale/cultures/en-US.js
src/components/progress/progress.js

Added support to api settings `maxFiles` to limit number of uploads with FileUploadAdvanced.
Closes #3512
- Navigate to http://localhost:4000/components/fileupload-advanced/test-max-files.html
- Drag or use `Select Files` button to upload
- See max two files can be upload only

3512 - Add support to max files limit with file upload advanced

---

app/views/components/contextualactionpanel/test-destroy.html
app/views/components/contextualactionpanel/test-nested.html
app/views/components/dropdown/test-2000-items.html
app/views/components/modal/test-two-in-page.html
docs/CHANGELOG.md
src/components/contextualactionpanel/contextualactionpanel.jquery.js
src/components/contextualactionpanel/contextualactionpanel.js
src/components/contextualactionpanel/readme.md
src/components/modal/modal.manager.js
src/components/toolbar/toolbar.js
test/components/contextualactionpanel/contextualactionpanel.e2e-spec.js

CAP did not work with nested CAPs anymore. I went back to check if this worked all the way to 4.18 on the new example here and could not find any evidence it ever worked. But maybe NG worked as it destroyed better.
Fixes #3785
Fixes infor-design/enterprise-ng#801
**Test 1**
- go to http://localhost:4000/components/contextualactionpanel/example-index.html
- this example and all examples in http://localhost:4000/components/contextualactionpanel should work ok still as before
**Test 2**
- go to http://localhost:4000/components/contextualactionpanel/test-destroy.html
- repeatedly open the cap …

801 - Fix nested caps and memory leaks

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Resizing the first column when frozen will jump. This PR fixes it.
Fixes #3741
- go to http://localhost:4000/components/datagrid/example-index
- resize between the first and second column (id) - should work nice
- go to http://localhost:4000/components/datagrid/example-frozen-columns.html
- resize between the first and second column (activity) - should work nice

3741- Add a fix for resizing the first frozen column

---

src/components/timepicker/timepicker.js

Adds a follow up fix found by QA i missed. For 3750 / the am/pm is not working in some cases
Fixes #3750 
- go to http://localhost:4000/components/datepicker/test-12hr-time.html?locale=af-ZA
- open the picker and pick a date and time with `nm.`
- renter the picker and `nm.` should be selected
- always reopening the picker should match am/pm in the field

3750 - Add follow up fix to time picker

---

app/views/components/fileupload-advanced/test-file-removed.html
docs/CHANGELOG.md
src/components/fileupload-advanced/fileupload-advanced.js
src/components/progress/progress.js

Added support to fire event `fileremoved` for attached file removed with FileUploadAdvanced.
Closes #3548
- Navigate to http://localhost:4000/components/fileupload-advanced/test-file-removed.html
- Drag or use `Select Files` button to upload
- After file complete uploading, next to file name `x` button will show
- Click on that `x` button to remove attached file
- A toast should show stating that file removed

3548 - Add support to fire event file removed with fileuploadadvanced

---

app/views/components/lookup/example-filter-lookup.html
app/views/components/lookup/example-filter-row.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixes and issue where using `filterable: true` and `keywordFilter: true` together breaks the lookup modal. This PR adds a check to cancel the `checkRow` function if `columnDef` is `undefined`
closes #3772 
- Pull Branch
- go to http://localhost:4000/components/lookup/example-filter-lookup.html
- Open the lookup modal, select a row and click apply.
- Make sure you can open the lookup modal again

3772 fix lookup keyword filter

---

app/views/components/datagrid/example-modal-datagrid.html

This PR simply adjusts one of the Datagrid examples to include a close button on the Modal.  This better demonstrates that the correct element is focused (first available grid cell) when the Modal opens.
Closes #3607 
- Navigate to http://localhost:4000/components/datagrid/example-modal-datagrid.html
- Click "Open Modal"
- When the Modal opens, ensure the focused element is the first checkbox in the first data row in the grid.
----
@claudenbach

3607 - Add close button to example page with Datagrid inside a Modal

---

src/components/contextualactionpanel/contextualactionpanel.jquery.js
test/components/contextualactionpanel/contextualactionpanel.e2e-spec.js

After a recent fix some CAP examples failed to work. Specifically saw it when the contents are a string. Example was also missing a regression test.
Fixes #3809
- go to http://localhost:4000/components/contextualactionpanel/example-trigger.html
- click the button and a cap should open again with no errors in the console
- try the pages with example in them on http://localhost:4000/components/contextualactionpanel/ for good measure

3809 - Fix an error opening caps with string contents

---

app/views/components/applicationmenu/example-personalized-role-switcher.html
docs/CHANGELOG.md
src/components/accordion/accordion.js
src/components/applicationmenu/_applicationmenu-uplift.scss
src/components/applicationmenu/applicationmenu.js
test/components/applicationmenu/applicationmenu.e2e-spec.js

This PR fixes a usability issue around the Role Switcher menu inside Application Menus, where it was not previously possible to dismiss the switcher menu with the Escape key.  Additionally, this PR improves control of the menu by keyboard, and sets a focus target when the menu is initially opened, to allow the user to navigate with arrows/tab (or dismiss with Escape).
Closes #3477
- Open http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html?theme=uplift&variant=light
- Use the Role Switcher button to open its menu.
- …

3477 - Allow App Menu's Role Switcher to be dismissed with Escape Key

---

app/views/components/applicationmenu/test-click-event-propagation.html
src/components/tooltip/_tooltip-uplift.scss

QA had some notes on 3759, decided to fix this.
Fixes #3759 
- go to http://localhost:4000/components/popover/example-index?theme=uplift&variant=light
- open the popup - now the title is not insanely large
- go to http://localhost:4000/components/applicationmenu/test-click-event-propagation?theme=uplift&variant=light
- there is no extra scrollbar on the header

3759 - Added a few small fixes

---

app/views/components/autocomplete/test-on-change.html
docs/CHANGELOG.md
src/components/autocomplete/autocomplete.js

Fix change event was not firing while navigating list with Autocomplete.
Closes #804 
- Navigate to http://localhost:4000/components/autocomplete/test-on-change.html
- Type `a` and an list with available option will open
- Press arrow down/up keys to navigate list
- See change event in console while navigating list (First time it looks fire twice, but its not -it fire one for search field leave and one for content change)

804 - Fix change event with autocomplete

---

docs/CHANGELOG.md
src/components/splitter/_splitter.scss

Fixed collapse button was misaligned with Splitter.
Closes #3825
- Navigate to http://localhost:4000/components/splitter/test-collapse-button.html
- See collapse button should not misaligned

3825 - Fix collapse button with splitter

---

scripts/build.js
src/components/modal/_modal.scss

This PR fixes a recent regression in custom builds where the new Modal Manager was incorrectly being imported into `components.js` when it shouldn't (Modal Manager is part of core, and doesn't need to be written into this file as an import).
Closes #3822
- Run `npm run build -- --components=modal --dry-run`
- Navigate to the enterprise project folder, and open `temp/components.js` in a text editor.  It should only include one export for `modal.js`.
- In the terminal run `npm run build -- --components=modal`.  The build should complete with no errors.
- Run the demoapp …

3822 - Prevent double import of modal manager during custom builds with Modals
