infor-design/enterprise

app/views/components/accordion/test-add-dynamically.html, docs/CHANGELOG.md, src/components/accordion/accordion.js, test/components/accordion/accordion-api.func-spec.js, test/components/accordion/accordion.e2e-spec.js
This PR fixes a regression in the Accordion that was preventing consumers from updating individual accordion headers without doing a full teardown of the entire accordion.  Script errors were being thrown when attempting this previously.
Additionally, there is now a demo for this test case, along with new e2e/functional tests.
Closes #3826
- Open http://localhost:4000/components/accordion/test-add-dynamically.html?layout=nofrills
- Expand the Accordion Header labeled "Favorites"
- Click the "Add new favorite" button several times.
- See that …
=> 3826 - Fix Accordion lifecycle to allow individual header updates without a full teardown [v4.28.x]

docs/CHANGELOG.md, src/components/datepicker/datepicker.js, src/components/validation/validation.js, test/components/datepicker/datepicker.e2e-spec.js
When using en-GB on the Month format picker the date would incorrect be marked as invalid.
Fixes #3833
- go to http://localhost:4000/components/datepicker/example-anniversary-format.html?locale=en-GB
- open Month Day picker and hit apply to insert todays date + month
- tab
- should be no validation error
=> 3833 - Add fix for date first month and day validation

app/views/components/autocomplete/test-in-modal-content.html, src/components/popupmenu/popupmenu.js
Added a re-fix for 3072 as we missed the case where the input is just a little bit cut off. Added a test page
Fixes #3072
- Navigate to http://localhost:4000/components/autocomplete/example-templates.html
- Open developer tools (make sure its dock to bottom)
- Enlarge developer tools so that the demo view is very small height and autocomplete partially hidden (like just the bottom border)
- Search for q and select the option
- See event fire as shown in the toast
- added a new test page for later …
=> 3072 - Added anther fix for autocomplete being out of position [v4.28.x]

app/views/components/toast/test-modal.html, docs/CHANGELOG.md, src/components/toast/toast.js, test/components/toast/toast.e2e-spec.js
This PR adds keyboard detection to the Toast and allows individual toasts to become dismissed one-by-one by pressing/holding the Escape key.
Closes #3521
Pull this branch, build, and run the demoapp.  Then:
_Test basic functionality (covered by e2e test):_
- Navigate to http://localhost:4000/components/toast/example-index.html
- Make a bunch of toasts
- Press the `Escape` key.  One by one, the toasts should dismiss.
- Make a lot of toasts.
- Hold the `Escape` key.  One by one, the toasts should quickly be dismissed (based on the user's keyboard response settings).
_Test combination with …
=> 3521 - Allow dismissal of Toasts with the Escape key

app/views/components/pie/test-label-currency.html, app/views/components/pie/test-percent-decimal-places.html, docs/CHANGELOG.md, src/components/charts/charts.js, src/components/pie/pie.js
Fixed rounds decimal places for percent values were not working with Pie.
Closes #3599
- Test on both Android and iOS device
- Navigate to: http://localhost:4000/components/pie/test-percent-decimal-places.html
- See the values should be rounds two decimal places
=> 3599 - Fix rounds decimal percent values with pie chart

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/core/_config.scss, src/themes/theme-soho-contrast.scss, src/themes/theme-soho-dark.scss, src/themes/theme-uplift-contrast.scss
Fixes the visibility of sort icons when toggling and when the column is in active.
Closes https://github.com/infor-design/enterprise/issues/3692
1.)
- Navigate to http://localhost:4000/components/datagrid/example-expandable-row-one-only.html
- Select any first item in column to activate it
- Click sort filter
- Icon should be visible
- Test this on different variants and themes
2.)
- Navigate to http://localhost:4000/components/datagrid/example-export-from-button.html?theme=soho&variant=dark
- Select any first item in column to activate it
- Click …
=> 3692 - Fix sort icons visibility when column is in active

app/views/components/datagrid/example-filter.html, docs/CHANGELOG.md, test/components/datagrid/datagrid.e2e-spec.js
Fixed contents filtertype was not working on example page with Datagrid.
Closes #2887
- Test on both Android and iOS device
- Navigate to: http://localhost:4000/components/datagrid/example-filter.html
- Use column `Activity (Contents Filter)` to filter
- See the grid should filter rows
=> 2887 - Fix contents filtertype example datagrid

docs/CHANGELOG.md, src/components/hierarchy/hierarchy.js, src/components/popupmenu/popupmenu.js
This PR makes a quick fix to the Hierarchy component that allows More Actions menus on leaves to be opened via clicking again.  This had been broken after some recent work in #3761 and #3783
Closes #3873
- Open http://localhost:4000/components/hierarchy/example-context-menu-with-details.html?theme=uplift&variant=light
- Click the More Actions "..." menu on the leaf labeled "Kaylee Edwards".  The Popupmenu should open and there should be no JS errors.
**Additional Context**
- Raised an additional issue for …
=> 3873 - Make Hierarchy "More Actions" menus open via click [v4.28.x]

scripts/build.js
This PR fixes a previous change to Custom Builds to use Node's `path.join()` for excluded file globbing paths.  This was preventing Locale builds from properly excluding culture files on any non-Unix-based file systems.
- Closes #3839 
- Related to #3841 
- Run a custom build dry run of Locale with npm run build -- --components=locale --dry-run.
- Open your project folder and find temp/components.txt. Open this in a text editor and make sure only locale.js is present. No culture or info paths should exist here.
- In your terminal run npm run build -- …
=> 3839 - Fix custom builds for Locale on Windows [v4.28.x]

app/views/components/multiselect/test-header-strings.html, docs/CHANGELOG.md, src/components/dropdown/dropdown.js, src/components/multiselect/multiselect.js, test/components/dropdown/dropdown-updates-events.func-spec.js, test/components/multiselect/multiselect.e2e-spec.js
Added support to api settings to `allTextString` and `selectedTextString` for custom headers with Multiselect.
Closes #3554
- Navigate to: http://localhost:4000/components/multiselect/test-header-strings.html
- Open multiselect field titled `States`
- See the header strings selected as `Chosen` and not selected as `Available to choose`
=> 3554 - Add support to custom header strings with multiselect

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixed keyword search results were breaking the html markup for icons, badges and hyperlink with Datagrid.
Closes #3855
Closes #3731
3855
- Navigate to: http://localhost:4000/components/datagrid/example-singleselect.html
- Open the search filter and type `error`
- See error icons and error badges should show
3731
- Navigate to: http://localhost:4000/components/datagrid/example-keyword-search.html
- Open the search filter and type `air`
- See error hyperlinks should remain links
=> 3855/3731 - Fix keyword search with datagrid

app/views/components/datagrid/test-alerts.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixed blank tooltip was showing when use Alert Formatter and no text with Datagrid.
Closes #2852
- Navigate to: http://localhost:4000/components/datagrid/test-alerts.html
- Resize the column `Alert Choose Header` width till icons partial hidden
- Hover over any icon in that column
- Tooltip should not show
=> 2852 - Fix blank tooltip with datagrid

app/data/states-multiselect.json, app/views/components/multiselect/example-ajax.html, docs/CHANGELOG.md, src/components/dropdown/dropdown.js, test/components/multiselect/multiselect-api.func-spec.js
This PR makes a change to how the Dropdown/Multiselect components detect selected values from incoming JSON via a `source` setting, fixing an issue where it was not possible to set selected values from a backend.
Closes #2656 
- Open http://localhost:4000/components/multiselect/example-ajax
- See that the Multiselect has one pre-populated value (Florida, "FL")
- Click the Multiselect to open it.
- When the list renders, see that three more states have been added to the list of selected values (NJ, NY, and PA), and the original pre-populated value …
=> 2656 - Enable Dropdown/Multiselect AJAX calls to populate selected values

app/views/components/dropdown/test-truncated-text-on-modal.html, docs/CHANGELOG.md, src/components/dropdown/_dropdown.scss
The reported bugs were being fixed already. Found another one where the tooltip content gets cut off. This fix will only isolate on dropdown inside of modal.
Closes
- https://github.com/infor-design/enterprise/issues/3106
- #3185
- Navigate to http://localhost:4000/components/dropdown/test-truncated-text-on-modal.html
- Click `Add Context` button
- Select the long text on dropdown
- Hover on it
- Tooltip should pop up without any problem
- Test this also on uplift theme
=> 3106 - Fix tooltip gets cut off on modal

docs/CHANGELOG.md, src/components/about/about.js, src/components/modal/modal.js, test/components/about/about.e2e-spec.js
This PR fixes a regression that was preventing About dialogs from being closed properly via keyboard, creating a situation where they couldn't be displayed more than once.
Closes #3898
- Open http://localhost:4000/components/about/example-index.html
- Click the "Show About Screen" button.  The About dialog should appear.
- Press the Escape key.  This closes the About dialog using the Modal Manager stack and its events.
- Click the "Show About Screen" button again.  The About dialog should be displayed with no console errors. …
=> 3898 - Allow Modal Manager to close About dialogs from its Modal stack via keyboard

docs/CHANGELOG.md, src/components/swaplist/swaplist.js
Fixed dragging items more than once was not working on Android or iOS devices with Swaplist.
Closes #1423
- Test for Android and iOS device
- Navigate to: http://localhost:4000/components/swaplist/example-index.html
- Select multiple items from one of the lists and drag them over to the next one
- Items will move
- Select moved items again and drag them back to same list
- Try again as many times, drag and drop should work fine
=> 1423 - Fix drag more than once on android or ios with swaplist

app/views/components/tabs-module/example-category-searchfield-go-button-home.html, app/views/components/tabs-module/example-category-searchfield-go-button.html, docs/CHANGELOG.md, src/components/searchfield/_searchfield-toolbar.scss, src/components/searchfield/_searchfield-uplift.scss
Fixes an issue where the search bar background color was going to transparent on smaller breakpoints.
closes #3871 
- Pull and build branch
- go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
- make sure the search bar and button maintain there background color on smaller breakpoints.
=> 3871 - Tabs search bar responsive

docs/CONTRIBUTING.md, src/components/personalize/readme.md
Fix broken change log link in CONTRIBUTING.md and correct typo in the personalize readme
Click the "Change Log" link on enterprise/blob/master/docs/CONTRIBUTING.md and ensure it goes to the change log
Verify that step 2 in the themes section of personalize/readme.md says `theme-soho-svg.html` or `theme-uplift-svg.html` (it has uplift listed twice)
=> Broken contributing.md link and personalize readme typo fix

app/views/includes/applicationmenu-personalized-role-switcher.html, docs/CHANGELOG.md, src/components/applicationmenu/applicationmenu.js, test/components/applicationmenu/applicationmenu.e2e-spec.js
This PR fixes an issue in Application Menus where clicking an App Menu Toolbar button on a menu configured with `dismissOnClickMobile` would not properly dismiss the application menu.  
Closes #2831
- Go to http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html
- Open Developer Tools - Toggle Device toolbar to iPhone
- Open the Application Menu
- Click on the any of the application menu's toolbar button, it should dismiss the menu.
----
@vonnyw
=> 2831 - Allow Application Menus to be closed when their inner toolbar buttons are clicked

src/components/swaplist/swaplist.js
Updated to use whole `LI` item instead of tree dot icon `handle` on touch devices with swaplist
1423
- Use iOS device
- Navigate to: http://localhost:4000/components/swaplist/example-index.html
- Select multiple items from one of the lists
- Use whole LI item and drag them over to the next one
- Items will move
- Select moved items again and drag them back to same list
- Try again as many times, drag and drop should work fine
=> 1423 - Update handle on touch devices with swaplist

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.e2e-spec.js
Fixed keyword search results were not showing for paging, if searched from other than 1st page it came blank table with Datagrid.
Closes #3629
- Navigate to: http://localhost:4000/components/datagrid/example-paging-client-side.html
- Click `Next Page` icon button to go to next page
- Type `Compressor 0` in the keyword input box
- Press `Enter` to search
- Grid should show one result
=> 3629 - Fix keyword search with datagrid

docs/CHANGELOG.md, src/utils/utils.js, test/components/utils/extend.func-spec.js
Sunsystems data contains recursive objects. This was fixed on 3759 but we found an additional bug when saveColumns is used the deepCopy is still blowing up. To fix this refactored deepCopy to use the new enhanced extend function
Fixes #3759 
- smoke test datagrid this may effect save columns.
- retest http://localhost:4000/components/datagrid/test-save-settings-manual.html
- retest http://localhost:4000/components/datagrid/test-save-settings.html
- on those two try hiding and resizing columns and reloading the page - it should persist all that …
=> 3759 - Add an additional fix for max stack size errors

app/views/components/datagrid/test-empty-message-button.html, docs/CHANGELOG.md, src/components/emptymessage/_emptymessage.scss, test/components/datagrid/datagrid.e2e-spec.js
Datagrid empty message areas have a feature to add buttons. But the pointer events were turned off so this did not work. This fixes the issue.
Fixes #3922
- go to http://localhost:4000/components/datagrid/test-empty-message-button
- click the button and you should get a toast
- also test http://localhost:4000/components/datagrid/test-empty-card.html
- make sure you can still scroll the container
=> 3922 - Make datagrid empty buttons clickable

app/views/components/spinbox/example-range-limits.html, app/views/components/tree/test-update-node-with-children.html, docs/CHANGELOG.md, src/components/spinbox/readme.md, src/components/spinbox/spinbox.js, test/components/spinbox/spinbox-settings.func-spec.js, test/components/spinbox/spinbox.e2e-spec.js
If the min value in spinbox is something other than a single digit number the routine didnt work to validate the value typing inline. So in order to fix this made processOnBlur the default and removed the old logic.
Also fixed some docs and added a support example in tree.
Fixes #3909 
- go to http://localhost:4000/components/spinbox/example-range-limits.html
- in the second input try to change the value to 111 -> should be possible to get any value to stay in there between 100 and 200
- try and type less or greater values like 50 or 250 -> the value will stay but when you leave the field …
=> 3909 - Fix spinbox validation

src/components/arrange/arrange.js, src/polyfills/jquery-passive-events.js, src/polyfills/polyfills.js
This PR attempts to get rid of many console warnings that will be displayed by our internal usage of `touchstart` and `mousewheel` jQuery events.  This is done be polyfilling jQuery's handling of these event types and overriding them to add `passive: true` to their arguments, per the [recommendation by a jQuery core team member here](https://github.com/jquery/jquery/issues/2871#issuecomment-497963776)
Closes #414
- Pull this branch, build, run the demoapp.
- Open kitchen sink page (http://localhost:4000) with a dev tools console present
- Scroll up and down in the page body.  No console …
=> 414 - Polyfill jQuery `mousewheel`/`touchstart` events to be passive

src/components/calendar/_calendar.scss, src/components/monthview/_monthview.scss
Fix a QA issue noted on #2788
Fixes #2788
- go to http://localhost:4000/components/calendar/test-specific-month.html
- click on a day
- note the buttons should be on the bottom now 
- try this in Safari and Chrome...
- also fixed an issue when clicking the day a blue state would show briefly that looked odd
=> 2788 - Fix safari calendar bugs

app/views/components/homepage/example-editable.html, docs/CHANGELOG.md, src/components/homepage/homepage.js
Need to allow handling of events in different ways. It can be more useful for the event to fire on the widget sometimes.
Closes  #3679
Run the demo app and go to http://localhost:4000/components/homepage/example-editable.html
Resize, reorder, remove widgets.
Expect to see two events in the console. One will fire on the homepage element, and the other on the widget element.
=>  #3679 Homepage: Edit events should trigger on widgets

src/components/line/line.js
Fixed scroll bar for card action with line chart.
Fixes #2670
- Navigate to: http://localhost:4000/components/line/example-axis-ticks.html?theme=uplift&variant=light&colors=0066D4
- See the chart should fit properly and no scroll bar in widget
=> 2670 - Fix scroll bar for card action with line chart

docs/CHANGELOG.md, src/components/spinbox/spinbox.js, test/components/spinbox/spinbox.e2e-spec.js
The spinbox component had remains of old mask options being set that made it not work properly to mask. Removed the older mask options and just have the new mask stuff
Fixes #3939 
- go to http://localhost:4000/components/spinbox/example-range-limits.html
mask
- in the first field since the max is ten you can type 2 numbers, if you type over ten it will be corrected on tab since mask doesnt support that
- in the second field since the max is ten you can type 3 numbers, if you type over 200  it will be corrected on tab since mask doesnt support that
=> 3939 - Add mask fixes to spinbox

app/views/components/accordion/test-expand-collapse-by-id.html, docs/CHANGELOG.md, src/components/accordion/accordion.js, test/components/accordion/accordion-api.func-spec.js
Changed the accordion collapse and expand api to let it take an ID and look for the header that way. Will add the NG settings for all of 4.29 later 
Fixes infor-design/ids-enterprise#783
- go to http://localhost:4000/components/accordion/test-expand-collapse-by-id.html
- in the end the third accordion should be expanded (the API code in the example is expanding and collapsing the last one so it ends closed) then expands the third
- covered by a new functional test
=> 783 - Allow ID to be passed to accordion collapse and expand

app/views/components/popdown/test-contains-lookup.html, app/views/components/popdown/test-trigger-lookup.html, docs/CHANGELOG.md, src/components/lookup/lookup.js, src/components/popdown/_popdown.scss, src/components/popdown/popdown.js, test/components/popdown/popdown.e2e-spec.js
This PR adds improved checks for "open" subcomponents within a Popdown content area, to prevent the Popdown from closing prematurely while interacting with these subcomponents.  Previously, when trying to work with Lookups specifically, clicking the lookup trigger or anywhere within an open Lookup component that was originally opened from a Popdown component would cause the Popdown to close unexpectedly.  This is now fixed.
infor-design/enterprise-ng#760
- Pull this branch, build, run the demoapp.
- Open http://localhost:4000/components/popdown/test-contains-lookup.html
- Click the Popdown …
=> ng760 - Prevent Popdown from closing when a nested Modal is opened.

docs/CHANGELOG.md, src/components/accordion/_accordion.scss
Makes the chevron icon perfectly centered in Safari browser and iOS devices. 
Closes https://github.com/infor-design/enterprise/issues/2161
- Open in Safari, http://localhost:4000/components/accordion/example-index.html
- Chevron icon should perfectly centered now
- Test this on iOS devices too, if needed
- Test in Uplift theme
=> 2161 - Fix alignment of chevron icon in Safari

app/views/components/datepicker/example-custom-format.html, src/components/datagrid/_datagrid.scss, src/components/locale/readme.md, src/components/tabs/_tabs-uplift.scss, src/components/tabs/_tabs.scss, src/components/tabs/tabs.js, src/components/validation/validator.js
Fixed two QA issues as detailed in the steps below.
Fixes #3960
Fixes #3935
**Issue 3960**
- go to http://localhost:4000/components/datagrid/example-tooltips.html?theme=uplift&variant=dark&colors=50535a
- the link should be visible as before and should stay visible during hover
- try all themes
**Issue 3935**
- go to http://localhost:4000/components//tabs/example-enable-disable-individual-tabs-with-keydown.html?theme=soho&variant=light&colors=0066D4
- go to the last tab and then shifttab out of the input to both show an error in the tab and focuss it
- the focus state should not cut off …
=> MISC - Fix tab and datagrid QA bugs [v4.29.x] 

app/views/components/spinbox/example-sizes.html, src/components/spinbox/_spinbox.scss, src/components/spinbox/spinbox.js
Adds a couple more small spinbox fixes.
Fixes #3970
Fixes #3969
- go to http://localhost:4000/components/spinbox/example-sizes.html
- in "Small Spinbox" type 999999 -> no thousands seperator should appear
- in "Extra-Small Spinbox" type 0-9 -> the single digit should now show
- try these both in uplift and soho theme
=> 3970 / 3969 - Add more spinbox fixes [v4.29.x]

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
The animation transition for buttons was being applied on datagrid rows that had class ~.btn
Fixes #3803 
- go to http://localhost:4000/components/datagrid/test-actions-reload.html
- bring the mouse down the first actions column slowly and watch the hover state
- all cells should now change color at the same time
=> 3808 - Remove an unneeded animation

app/views/components/datagrid/example-singleselect.html, app/views/components/datagrid/test-tree-select-siblings.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid-settings.func-spec.js, test/components/datagrid/datagrid.e2e-spec.js
The poster requested that we add a setting so that rows can not be deselected (rows must always be selected so its not valid to have rows unselected). To do this i added a new setting.
Fixes #3791 
- go to http://localhost:4000/components/datagrid/example-singleselect
- click row two -> it will select
- click row two again -> it will not deselect
- click row three -> it will select, deselecting the previous selection
- go to http://localhost:4000/components/datagrid/test-tree-select-siblings.html
- click row one -> it will select
- click row one again -> it will not deselect
- click row …
=> 3791 - Add a fix to avoid deselecting selected rows

app/views/components/tabs-module/example-add-tab-button.html
After doing some testing on #3872, it appears the Module Tabs Tooltips are working as expected, but the sample that was being tested did not enable the setting that creates tooltips, as it's an opt-in feature.  This PR simply enables this setting on the example page in question.
Closes #3872
- Open http://localhost:4000/components/tabs-module/example-add-tab-button.html
- In the first tab (which should be active), uncheck "Fill With Garbage" and create a very long title for the name of the tab.  No content is necessary.
- Click "Create New Tab". …
=> 3872 - Modify test page to demonstrate working Module Tabs Tooltips

docs/CHANGELOG.md, src/components/listview/listview.js, src/components/tree/tree.js, src/utils/utils.js
Fixed previous text selection was not clearing after clicked to any tree-node with Tree.
Closes #3794
- Navigate to: http://localhost:4000/components/tree/example-ajax.html
- Right click on a node
- Node text should have blue selection
- If context menu opened click somewhere else, or press `esc` key to close context menu
- Node text should still have blue selection
- Now without clicking anywhere else, click on another node
- The blue selection for previous node should go away
=> 3794 - Fix previous text selection with tree

app/app.js, app/src/js/middleware/cmd-params-handler.js, app/src/js/middleware/option-handler.js, app/src/js/set-import-style.js, app/views/includes/head.html, docs/CHANGELOG.md, docs/DEVELOPER.md
This PR adds middleware to the Demoapp that makes matching terminal flags available for the same settings that we normally use for testing via URL query params.  It's now possible to run the demoapp with parameters such as:
```sh
node app/server.js --verbose --locale=es-ES colors=#941e1e
```
N/A
- Pull this branch and build the library if necessary
- Run the demoapp manually with `node app/server.js --verbose --locale=es-ES colors=#941e1e` (or test other combinations of the settings found [here](https://github.com/infor-design/enterprise/compare/add-demoapp-cmd-flags?expand=1#diff-3c3a0c18d …
=> Enable execution of the Demoapp with persisting settings

docs/CHANGELOG.md, src/components/validation/validator.js
In some cases the modal that works with lookup would not fire the events in the right sequence to catch all the validation events. This fixes the issue
Fixes infor-design/enterprise-ng#810
- go to http://localhost:4000/components/lookup/example-index.html
- select a value in the first lookup
- clear the value within the field
- open the lookup again and select the same value as before
try other combos like
- select a value in the first lookup
- clear the value within the field
- open the lookup again and select a different value 
and
- select a value in the first lookup
- clear the value …
=> 810 - Fix a bug with validation in lookup

app/views/components/datagrid/test-row-reorder-paging.html, docs/CHANGELOG.md, src/components/arrange/arrange.js, src/components/datagrid/datagrid.js
Fixed data was not in sync for row reorder and paging with Datagrid, also found arrange was broken after drag end the dragged item was returning to its initial place so this PR will fix arrange issue too.
Closes #3794
- Navigate to: http://localhost:4000/components/datagrid/test-row-reorder-paging.html
- Use first column tree dots icon handle to drag rows
- Drag any row to change the order
- See after drag-end dragged item should stay where it droped
- Do the same on different pages, then revisit the pages
- See the rows should stay as you had …
=> 3749 - Fix row reorder and paging data sync with datagrid

docs/PUBLISH.md, scripts/jenkins-deploy.sh, src/components/column/column.js, test/components/datepicker/datepicker.e2e-spec.js
A ~ update of eslint has some lint errors. Fixing these. Also the build name on jenkins was renamed.
- rm -rf node_modules
- npm i
- npm run build
-  npm run eslint:error-only
=> Fix build link and lint errors on fresh node_modules

docs/CHANGELOG.md, src/components/applicationmenu/_applicationmenu-uplift.scss
Fix the dropdown icon not properly centered in Safari.
Closes https://github.com/infor-design/enterprise/issues/3766
- Open Safari and go to http://localhost:4000/components/applicationmenu/example-menubutton.html?theme=uplift&variant=light&colors=0066D4
- Dropdown icon should properly aligned with the text beside it.
=> 3766 - Fix dropdown icon position in Safari

docs/CHANGELOG.md, src/components/tooltip/tooltip.js, test/components/modal/modal.e2e-spec.js
This PR changes how Popovers are rendered when nested within Modal components, in order to fix the `tabindex` order of focusable elements.  This fixes an accessibility issue where it was not possible to access the contents of a Popover with the keyboard while nested within a Modal.
Close #3644
- Open http://localhost:4000/components/modal/test-external-components?layout=nofrills
- Click the "Show Modal" button
- Use the keyboard to tab into the "Click to Show Popover" button
- Press the enter key to activate the Popover
- Press the tab key …
=> 3644 - Fix focus traps when nesting Popovers within Modals

docs/CHANGELOG.md, src/components/dropdown/dropdown.js, test/components/dropdown/dropdown.e2e-spec.js, test/components/monthview/monthview-api.func-spec.js
Changed the behavior of dropdown so that it selects the highlighted item on tab.
Fixes #3028
- go to http://localhost:4000/components/dropdown/example-index.html
- open the list and arrow down a few times
- hit tab or shift tab
- the last highlighted item will now be selected
- open the list again and type O 
- hit tab or shift tab
- the last highlighted item (arizona) will be selected
- try various combinations of type ahead and select
- smoke test to http://localhost:4000/components/multiselect/example-index.html (it was actually doing the selection on tab already) …
=> 3028- Make dropdown select on tab

src/components/accordion/_accordion.scss, src/components/accordion/accordion.js, src/components/calendar/calendar.js, test/components/calendar/calendar.e2e-spec.js
When dealing with a huge list of accordions plus a couple of expensive methods forcing reflow as mentioned here: https://gist.github.com/paulirish/5d52fb081b3570c81e3a, the whole application performance suffers. Anything you do is unbearably slow even just ticking a checkbox.
The proposed style changes here is not going to affect how the accordion would look. Doing the `display:none` when the panel is not expanded just helps the browser deal with the force reflows more easily.
I am unable to create a reproducible example in this repo since the problem only occurs when using the library in an angular project where those methods mentioned above are …
=> NA - Add fixes to speed up accordion

src/components/dropdown/_dropdown-uplift.scss
I noticed in this screenshot from @janahintal that the padding on Uplift theme was off in the Multiselect with tags. This PR patches that in all browsers.
Closes #3767
Closes #4055 
- Pull the branch, build, and run the app
- Open http://localhost:4000/components/multiselect/test-select-all-tags.html?theme=uplift&variant=light
- Open the Multiselect and select all
- Try and scroll the Tag List.  It should be flush with the left/right edges of the pseudo-element.
=> 3767/4055 - Multiselect padding followup fix

app/views/components/applicationmenu/test-performance.html
This is an improvement of the example in test-performance.html showing how the application menu affects performance of other components in the page.
Added a checkbox and a toolbar then calling a toolbar update after a timeout when the checkbox is ticked.
1. Go to http://localhost:4000/components/applicationmenu/test-performance.html
2. Hit the record button on devtools performance tab.
3. Tick the checkbox
4. Stop recording
1. The application menu is **OPEN** and **WITHOUT** the `display:none` fix in #4052 originally from #4040 - You'll noticed that ticking the checkbox shows a delay in animation. Performance below shows a recalc …
=> test-performance.html improvement

app/views/components/datepicker/test-change-event.html, docs/CHANGELOG.md, src/components/datepicker/datepicker.js, test/components/datepicker/datepicker.e2e-spec.js
In a couple cases the change event didnt fire right.
Fixes infor-design/enterprisee-ng#853
Fixes #4075
- go to http://localhost:4000/components/datepicker/test-change-event.html
- open the picker and click today -> toast will fire
- blank out the field -> toast will fire
- open the picker and click today again -> toast will fire (this wasnt working before)
- go to http://localhost:4000/components/datepicker/example-range.html
- in the "Range - No Initial value" field open the picker
- click June 3
- click June 3rd again
- check the console and there should be two events one with one value …
=> 853 - Add fixes for datepicker change event

app/views/components/datagrid/example-paging.html, docs/CHANGELOG.md
Fixed example page for filter and pager was not working properly with Datagrid.
Closes #3856
- Navigate to: http://localhost:4000/components/datagrid/example-paging.html
- Filter `3` on `Product Id`
- Select the filter row with id `3` while filtering
- Now clear the filter to show all the records
- Selected row should remain selected
=> 3856 - Fix example page for filter and pager with datagrid

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.e2e-spec.js
An issue regressed where checkboxes in an expandable row could no longer be checked.
Fixes #4062
- go to http://localhost:4000/components/datagrid/test-expandable-row-checkboxes.html#
- expand any row
- click the checkbox (it should toggle and it wasnt before)
=> 4062 - Add fix for checkboxes in an expandable datagrid row

app/views/components/lookup/test-paging-server-side-keyword-search.html, docs/CHANGELOG.md
Added example page for server side keyword search with Lookup.
Closes #2806
- Navigate to: http://localhost:4000/components/lookup/test-paging-server-side-keyword-search.html
- Open lookup modal
- See top title results count should be `1000`
- Search for `1` now results should change to `271`
- Change search to `0` now results should change to `181`
- Clear search to show all rows
- See results count should back to be `1000`
=> 2806 - Add example page for server side keyword search with lookup

app/views/components/datepicker/test-change-event.html, src/components/datepicker/datepicker.js, test/components/datepicker/datepicker.e2e-spec.js
Essentially reverse the fix for https://github.com/infor-design/enterprise/pull/3593 as it seems to work ok now. And its better to have change fire more than once rather than case it doesn't fire and data gets lost. In most cases we get the right change events but in a couple multistep operations you may now get an extra change event.
But the change event should never NOT fire for a change at least once
Fixes #4087 
- go to http://localhost:4000/components/datepicker/test-change-event.html
- click first field
- pick a value in the picker
- clear the field
- without leaving pick a new value …
=> 4087 - Datepicker change event getting missed

app/views/components/datagrid/example-singleselect.html, docs/CHANGELOG.md
Updated example page for keyword search to fix error state with Datagrid.
Closes #3961
- Navigate to: http://localhost:4000/components/datagrid/example-singleselect.html
- Use the keyword search and filter for `error`
- Should show rows only with error in it
=> 3961 - Update example page for keyword search with datagrid

app/views/components/field-options/example-fieldset.html, docs/CHANGELOG.md, src/components/field-options/_field-options-uplift.scss, src/components/field-options/_field-options.scss, src/components/field-options/field-options.js
Fixed the focus style was not aligning with Field Options.
Closes #3628
- Navigate to: http://localhost:4000/components/field-options/example-fieldset.html
- Click on any filed single line like `Building Suppliers`
- Or Multy line as `4209 Industrial Avenue, Los Angeles, California 90001 USA`
- Filed options button `three dotes` should align properly
=> 3628 - Fix focus style alignment with field options

docs/CHANGELOG.md, package.json
Merged two new icons `print-preview` and `tree-node` in an updated design system
Fixes #3978 
- make sure to do `npm i` to get the latest ids identity
- check out the print-preview icon 
- check it in uplift too
- go to http://localhost:4000/components/tree/example-index.html?theme=uplift&variant=light&colors=0066D4
- tree icon should not look like radio button any more
=> 3978 - Add design system release for new icons

app/views/components/hierarchy/test-vertical-tabs.html, docs/CHANGELOG.md, src/components/hierarchy/hierarchy.js
Hierarchy selection causes tab selection to be removed. This happens because both tabs control and hierarchy control have the same class name for selection state.
https://github.com/infor-design/enterprise/issues/3597
1. Pull PR
2. Launch ids-enterprise project
3. Navigate to  http://localhost:4000/components/hierarchy/test-vertical-tabs.html
4. Verify that selection of tabs is no longer lost when expanding a hierarchy leaf
=> Fixed hierarchy selection issue when nested inside of tabs.

src/components/field-options/_field-options-uplift.scss, src/components/field-options/field-options.js
Fixed the styles for focus was not aligning with Field Options.
Closes #3628
- Navigate to: http://localhost:4000/components/field-options/example-fieldset.html?theme=uplift&variant=light&colors=0066D4
- Click on any filed single line like `June 21, 2015 (4 days)`
- Or Multi line as `4209 Industrial Avenue, Los Angeles, California 90001 USA`
- Filed options button `three dotes` should align properly
=> 3628 - Fix focus alignment with field options

docs/CHANGELOG.md, src/components/accordion/_accordion.scss, src/components/calendar/_calendar.scss
Fixes a bug where the border top color is wrong in uplift dark and high contrast theme.
Noticed that this line causes the issue
https://github.com/infor-design/enterprise/blob/master/src/components/accordion/_accordion.scss#L568
Moving this to its specific component (calendar) so it will not affect the entire accordion that was being used in other components.
I found out that line of css code was part of this fix https://github.com/infor-design/enterprise/commit/7b4420f19a5a97f5ed98604033e3f25f5ed8ccb4
Closes https://github.com/infor-design/enterprise/issues/4042
- Pull this branch, build, …
=> 4042 - Fix wrong border top color in application menu

app/views/components/datagrid/test-tree-tooltip.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.e2e-spec.js
Fixed the tooltip for tree grid was not working properly with Datagrid.
Closes infor-design/enterprise-ng#827
- Navigate to: http://localhost:4000/components/datagrid/test-tree-tooltip.html
- Hover on any cell (specially row with child nodes) in `Time` column
- See the tooltip content should related to cell value
There was js error showing, so check should not show anymore
- Navigate to: http://localhost:4000/components/datagrid/test-tree-tooltip.html
- Hover on any parent cell with +/- button in `Task` column
- See …
=> 827 - Fix the tooltip for tree grid with datagrid

src/components/breadcrumb/breadcrumb.js
IE 11 treats children as undefined not length = 0 so added a fix
Fixes #4117
Fixes #4116
Fixes #4115
Load the kitchen sink in IE 11 and check the console for no errors
=> Misc - Fix IE bug [v4.30.x]

app/views/components/modal/test-external-components.html, src/components/tooltip/tooltip.js
Changed around a fix for https://github.com/infor-design/enterprise/commit/4e2217ba2799311ad4fccea137f9c9e6eebed259#diff-0732597cd96cb9d201490dfa8fe61b4b as it introduced a stacking context issue. That caused popovers like datepicker to get cut off and tooltips to shift content.
Now to get the tabing behavior, developers have to set attachToBody: false on the popovers on modals in order to solve for that issue.
Fixes #4124
- go to http://localhost:4000/components/modal/example-close-btn.html
- hover the close button til you get the tooltip
- hit close
- try again -> button should not shift …
=> 4124 - Add fix for shifting button by making a preference [v4.30]

app/views/components/tree/test-add-node.html, app/views/components/tree/test-remove-all-children-and-update.html, docs/CHANGELOG.md, src/components/tree/tree.js
1) Added option to add new child node on top or bottom with Tree.
2) Fixed an issue where the tree node still shows folder icon after all children and `children` property deleted.
Closes #3915
Closes #4026
- Navigate to: http://localhost:4000/components/tree/test-add-node.html
- Select any tree node
- Click on button `Add Node`
- Choose the position to add new node
- If selected node not folder type and chosen position is `Top` or `Bottom`, it will change selected node type to folder
- If there is no-selected node it will add top/bottom to tree …
=> 3915/4026 - Fixed an issue and add option for add new child with tree

docs/CHANGELOG.md, src/components/listfilter/listfilter.js
Fixes an issue where "phraseStartsWith" does not filter the list after deleting a character. The incoming text had a bunch of extra spaces in it which was causing the index of the character to be off.
closes #4047 
- Go to http://localhost:4000/components/dropdown/test-filter-types.html
- In the PhraseStartsWith Filter text input and type "a"
- Dropdown list shows Alabama, Alaska ...
- Type another "a" ("aa" in the text input)
- List should be empty
- Delete second "a" leaving one "a" in the input
- List should filter again correctly
=> 4047 - Fix dropdown phraseStartsWith filter

docs/CHANGELOG.md, src/components/locale/locale.js, test/components/datepicker/datepicker.e2e-spec.js
If using a secondary / non default calendar (ie gregorian on ar-SA). The calendar would error when tabbing out of he field.
Fixes #4130
- go to http://localhost:4000/components/datepicker/test-ar-sa-gregorian.html
- open the picker and select a value
- tab out of the field
- check the console for errors (should be none)
=> 4130 - Add fix for gregorian locale on ar-SA

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
Changed non vendor prefix fill-available to stretch. As it was causing downstream build issues. Doesn't effect anything since the browsers use the vendor prefix but was giving a ton of warnings in down steam builds.
Will patch this back to 4.30 soon
Fixes #4133
- retest steps on https://github.com/infor-design/enterprise/pull/4009
=> 4133 - Add fix for invalid css property [v4.30.x and v.4.31.x]

app/views/components/locale/test-set-value.html, docs/CHANGELOG.md, src/components/datepicker/_datepicker.scss, src/components/datepicker/datepicker.js, src/components/locale/locale.js, test/components/locale/locale.e2e-spec.js, test/components/locale/locale.func-spec.js
Added several fixes uncovered on a new test page. See steps and is covered by tests.
Fixes #4160 
**Main issue**
- go to http://localhost:4000/components/locale/test-set-value.html
- each field should fill in with an arbitrary date (selecting a new date will fill the bottom set of fields)
- go to http://localhost:4000/components/locale/test-set-value.html?locale=ar-SA
- each field should fill in with an arbitrary date (selecting a new date will fill the bottom set of fields)
- the problem was the MMdd Field wasnt working and neither was yyyyMM Field
**Supplemental issue**
- on …
=> 4160 - Locale and datepicker bugs with ar-SA (umalqura) [v4.30.x]

docs/CHANGELOG.md, src/components/toast/toast.js
Fixes a bug where the toast message doesn't dismissed when pressing ESC.
Having unique id's creates multiple containers. Because of that, we need to connect all of the toast elements on a single instance for the escape dismissal to work. If there are multiple unique containers, it creates its own indexes.
Closes https://github.com/infor-design/enterprise/issues/3986
- Navigate to http://localhost:4000/components/toast/example-draggable.html
- Click `Show Toast Message 1` multiple times
- Drag this container to another place
- Click also `Show …
=> 3986 - Fix toast message doesn't dismissed when pressing ESC

app/views/components/mask/test-dates-no-separators.html, docs/CHANGELOG.md, src/components/locale/locale.js, src/components/mask/masks.js, test/components/mask/mask.func-spec.js
Re-raising this PR against a clean, recent cut of `master`.
----
This PR adjusts the detection of date/time format characters in the built-in Date masking function to allow it to process date/time strings that don't contain separators or other special characters.  
Closes #3963
- Open http://localhost:4000/components/mask/test-dates-no-separators.html
- Fill out the fields according to their placeholders and make sure non-allowed input is thrown out.  All fields are also validated by the Datepicker, so invalid dates should be correctly flagged …
=> 3963 - Add ability to pass date formats with no literals to Mask

docs/CHANGELOG.md, src/components/dropdown/dropdown.js
Fixes an issue where pressing `backspace` in Windows 10 and `fn + delete` in Mac OS was inserting a special character in the input field. Using `String.fromCodePoint` to check for the special char in windows. Also checking for IE11 as this is not supported, but the bug was actually not occurring in IE11 so I think it's safe.
closes #4020 
- pull and run branch
- Go to http://localhost:4000/components/datagrid/example-editable.html click in an editable cell in the Action column.
- Select a new value, "Shipped" for example.
- In Windows press `backspace`  / In Mac OS press `fn + delete`
- …
=> 4020 - Fix Dropdown backspace special character bug

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid-tree.func-spec.js
Fixed column filter results were inconsistent for tree grid with Datagrid.
Closes #4031
http://localhost:4000/components/datagrid/test-tree-filter.html
- Apply "Contains" filter on `Task` column with the word `More`
- It should have parent and all child nodes, if not expanded use expand/collapse button
- There should be 10 rows as: 7, 10, 12, 13, 14, 15, 18, 20, 21, 22
If only parent got match then make expand/collapse button to be collapsed, disabled and should not any children nodes added
- Apply "Contains" filter on `Task` column with the word …
=> 4031 - Fix filter results for tree grid with datagrid

docs/CHANGELOG.md, src/components/datagrid/datagrid.formatters.js
Fixed the time picker editor was switching between AM and PM when set to 12:00 with Datagrid.
Closes #4149
- Navigate to: http://localhost:4000/components/datagrid/example-filter.html
- Enter either 12 AM or 12 PM on any cell in column `Time`
- Tab out from it, and see it should not switches between AM/PM
=> 4149 - Fix am and pm for timepicker editor with datagrid

docs/CHANGELOG.md, src/components/applicationmenu/_applicationmenu.scss
Fixed the Header was unable to hide for RTL and ie11 with Application Menu.
Closes #2154
- Use win10 ie11 (Desktop or Tablet view)
- Navigate to: http://localhost:4000/components/header/example-index?locale=he-IL
- Click on the hamburger icon
- See application menu should not overlap the hamburger icon
=> 2154 - Fix header alignment for rtl and ie11 with application menu

app/views/components/datagrid/example-nested-grids.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.e2e-spec.js
Clicking nested rows regressed. This is a fix for this.
Fixes #4197 
- go to http://localhost:4000/components/datagrid/example-nested-grids.html
- expand a row
- click the delete button on any nested row
- toast should show
=> 4197 - Add fix for clicking nested rows

app/views/components/blockgrid/example-paging.html, docs/CHANGELOG.md, src/components/blockgrid/blockgrid.js
When working on implementing the missing paging features of the Blockgrid API into NG, I ran into an issue where it was possible to try and render dataset items that didn't exist.  This was happening because the calculation of the displayed records on a page were sometimes incorrect in the EP component.  This PR fixes that issue.
infor-design/enterprise-ng#836 (NG issue)
infor-design/enterprise-ng#878 (PR)
Make sure all existing Blockgrid tests pass (demo of this case is in the NG component).
=> NG#836 - Fix bug in displayed dataset rendering in Blockgrid

app/views/components/datagrid/test-empty-message-small.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid-uplift.scss, src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js, src/components/emptymessage/_emptymessage.scss, src/components/emptymessage/emptymessage.js, test/components/datagrid/datagrid-settings.func-spec.js
Added the setting for empty message small height with Datagrid.
Closes #3609
- Navigate to: http://localhost:4000/components/datagrid/test-empty-message-small.html
- See the empty message
- Should be small height
- Only title text should showing (no icon, button etc.)
- Check for all themes and row height sizes
=> 3609 - Add the setting for empty message small height with datagrid

docs/CHANGELOG.md, src/components/popupmenu/popupmenu.js
Fixed the overlapping icons with Popupmenu.
Closes #4201
- Navigate to: http://localhost:4000/components/datagrid/example-editable.html
- Click on grid action (three dots) button `...`
- Click on `+ Add` item
- Open again the `...` button
- See there should not be any check mark icon in `+ Add` item
=> 4201 - Fix overlapping icons with popupmenu

src/components/datagrid/_datagrid-uplift.scss, src/components/datagrid/_datagrid.scss
Fix icon and height for empty message small height with Datagrid.
Closes #3609
- Navigate to: http://localhost:4000/components/datagrid/test-empty-message-small.html
- See icon in header `In Stock` should be aligned
- See the empty message
- Should be small height
- Only title text should showing (no icon, button etc.)
- Check for all themes and row height sizes
=> 3609 - Fix icon and height for empty message small height with datagrid

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixed select all rows were keep adding to selected array every time method `selectAllRows()` run with Datagrid.
Closes #4195
- Navigate to: http://localhost:4000/components/datagrid/test-filter-paging-client-side.html
- To select all rows run console: `$('#datagrid').data('datagrid').selectAllRows();`
- Get all selected rows: $('#datagrid').data('datagrid').selectedRows();
- Should do 11-selected items array
- Repeat steps, to select all few times: `$('#datagrid').data('datagrid').selectAllRows();`
- Get again all …
=> 4195 - Fix select all rows with datagrid

app/views/components/blockgrid/example-paging.html, docs/CHANGELOG.md, src/components/blockgrid/blockgrid.js, test/components/blockgrid/blockgrid-api.func-spec.js
This PR makes a change to the Blockgrid Pager's default configuration to hide the first/last pager buttons, per the original design.  This PR also makes all Pager settings configurable when using the Pager within the Blockgrid, by passing a new `pagerSettings` object.  Additionally, some inline documentation from the source code was updated.
- infor-design/enterprise-ng#836
- #4204 
- Open http://localhost:4000/components/blockgrid/example-paging.html?theme=uplift
- Observe the only paging buttons that should be present are the Previous, Next and …
=> NG#836 - Fix pager button display bug on Blockgrid [v4.31.x]

app/views/components/datagrid/test-tree-update-data.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixed rows were not render properly when use method `updateDataset()` for treegrid with Datagrid.
Closes #4213
- Navigate to: http://localhost:4000/components/datagrid/test-tree-update-data.html
- Expand all rows
- Should show 7-rows `Id` as: 1, 2, 4, 5, 3, 6, 7
=> 4213 - Fix render rows for dynamically update with tree datagrid [v4.31.x]

docs/CHANGELOG.md, src/components/contextualactionpanel/contextualactionpanel.js, src/components/modal/modal.js, test/components/contextualactionpanel/contextualactionpanel.e2e-spec.js
This PR fixes a small bug in Contextual Action Panels, where it previously wasn't possible to click its Close button if a child component of the CAP was currently open (such as Dropdown, Autocomplete, or any others with an active list subcomponent).  
Closes #4112
- Pull this branch, build, and run the demoapp.
- Open http://localhost:4000/components/contextualactionpanel/example-index.html
- Open the CAP
- Open the "Ship Terms" dropdown list
- Click the close button without closing the dropdown list.   The CAP should close.
=> 4112 - Make CAP close button work in cases where its subcomponents are open

app/views/components/datagrid/example-row-numbers.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.formatters.js, src/components/datagrid/readme.md, test/components/datagrid/datagrid.e2e-spec.js
Added a new built in formatter to format a number column.
Fixes #1904
- go to http://localhost:4000/components/datagrid/example-row-numbers
- should bea new readonly column showing the row number down across all pages
- sort any column, row number will stay the same
- enable the filter column in the .. menu
- filter on something -> row number will show for that number as if it was unfiltered
=> 1904 - Added a row number column formatter

docs/CHANGELOG.md, src/components/lookup/_lookup.scss, src/components/searchfield/_searchfield-toolbar.scss, src/components/searchfield/_searchfield-uplift.scss, src/core/_config.scss
Adds an adjustment to the box shadow for Searchfields with category buttons (focus state)
closes #4181 
- Go to http://localhost:4000/components/toolbarsearchfield/example-alternate-style-with-categories.html?theme=soho&variant=light&colors=0066D4
- Make sure when the Searchfield opens it matches design in #4181 
- Check for breaking changes in other examples http://localhost:4000/components/toolbarsearchfield
=> 4181 - Adjust the Searchfield focus state

app/views/components/tabs/test-container-resize-homepages.html, app/views/components/tabs/test-container-resize-with-toolbar.html, docs/CHANGELOG.md, src/.eslintrc.js, src/components/tabs/tabs.js
This PR adds internal detection for resizing of a Tabs panel/list container.  In browsers that support it, the Tabs component now sets up a [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) that will respond by automatically triggering the IDS global `resize` event on the body tag.
In older browsers such as IE11, it's still necessary to trigger the `resize` event manually.  This PR also exposes Tabs' `handleResize()` method as public API for this purpose.
There's also a new test page added that specifically recreates the resize conditions from @anhallbe's test in the NG repo.
Related to …
=> NG#860 - Add ResizeObserver to Tabs list/panels for resize handling detection

docs/CHANGELOG.md, src/components/popupmenu/_popupmenu.scss
This PR fixes a minor display issue with the shortcut text on small breakpoints
closes #3984 
- Pull and run this branch
- Go to http://localhost:4000/components/popupmenu/example-shortcut-text.html?theme=soho&variant=light&colors=2578a9
- Open chrome DevTools and select Iphone 5 / SE
- The shortcut text should no longer wrap to two lines
=> 3984 - Fixed a minor issue with the shortcut text on small breakpoints.

docs/CHANGELOG.md, src/themes/theme-uplift-contrast.scss, src/themes/theme-uplift-dark.scss
Fixed a bug where the text input error state border color would be wrong in the vibrant, dark and high contrast.
closes #4248 
- Go to http://localhost:4000/components/input/example-index.html?theme=uplift&variant=contrast&colors=0066D4
- Focus in/out of a required field and see that the error state is now working.
=> 4248 - Fixed text input error state border color 

docs/CHANGELOG.md, src/components/tree/tree.js
Fixed the return focus state was not working properly after closing the context menu with Tree.
Closes #4252
Navigate to: http://localhost:4000/components/tree/example-context-menu.html
1st Test
- Tab to focus `Node One` (should show blue focus)
2nd Test
- Click `Node Two` to expand
- Right click `Node 2.1` (context menu should open)
- Press `Escape` key or click a menu item (should show blue focus on Node 2.1)
- Click another node after closing the menu (should focus node with no focus state shown)
3rd Test
- Click `Node Two` to expand
- Right …
=> 4252 - Fix return focus state for context menu with tree

src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.e2e-spec.js
Updated the fix on https://github.com/infor-design/enterprise/issues/3980 to solve https://github.com/infor-design/enterprise/issues/4261 by..
- making it happen with no timeout
- checking and ignoring certain keys
- calling api same way
Fixes #4261
- click in the grid and arrow to the Action field
- type a key like a or b and the dropdown should open and filter
- reset 
- click in the grid and arrow to the Action field hit enter -> this will enter edit mode but wont open
- now type a and it should filter
- reset 
- …
=> 4261 - Add new fix for entering edit mode in dropdown [v4.31.x]

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixed the dynamic tooltip was not working properly with Datagrid.
Closes #4260
- Navigate to: http://localhost:4000/components/datagrid/test-custom-tooltip-dynamic.html
- Hover to any cell in column `Exception`
- Tooltip should show
- Make column `Exception` wider
- Hover to any cell again in column `Exception`
- Still tooltip should show
=> 4260 - Fix dynamic tooltip with datagrid

docs/CHANGELOG.md, src/components/homepage/homepage.js
Fixed the columns were not showing properly after resize browser window with Homepage. This issue was produced only in Angular project.
Closes infor-design/enterprise-ng#894
Closes infor-design/enterprise-ng#895
- Pull ([NG master](https://github.com/infor-design/enterprise-ng.git))
- If [PR 898](https://github.com/infor-design/enterprise-ng/pull/898) not merged then switch to branch `git checkout 894-homepage-maximize-columns`
- Build NG project
issue 894
- …
=> ng894/ng895 - Fix columns resize with homepage

app/views/components/fileupload-advanced/test-send-completed-nodata.html, docs/CHANGELOG.md, src/components/fileupload-advanced/fileupload-advanced.js
Fixed method `status.setCompleted()` not firing event `fileremoved` with FileUploadAdvanced.
Closes #4230
- Navigate to: http://localhost:4000/components/fileupload-advanced/test-send-completed-nodata.html
- Upload any file and after completed
- Press Remove File (X) button
- Should run a toast after click on Remove File (X)` button.
=> 4294 - Fix set status completed on send method with FileUploadAdvanced

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixed the check box filter was not working with Datagrid.
Closes #4271
- Navigate to: http://localhost:4000/components/datagrid/test-tree-filter.html
- Use filter on column `Portable`
- The check box filter should work properly
- Use toggle `+/-` button to show/hide
- Also some nodes checkbox checked(true/false opposite as filter), but included because as parent node
- If choose to filter `Selected` (6, 7, 10-parentnode, 11, 15-parentnode, 17, 18-parentnode, 20)
- If choose to filter `Not Selected` (1, 2, 3, 4, 5, 7-parentnode, 8, 9, 10, 12, …
=> 4271 - Fix the check box filter with datagrid

src/components/popupmenu/_popupmenu.scss
This PR contains QA fixes for the Popupmenu shortcut text on small screens. Made adjustments to shortcut text breakpoint and spacing on screens below 400px.
closes #3984
- Go http://localhost:4000/components/popupmenu/example-shortcut-text.html?theme=uplift&variant=light&colors=2578a9
- Open dev tools to iPhone 5/SE and check in Mac/Safari on a small screen.
- Make sure the shortcut text does not break to second line.
- Check both themes.
=> 3984 - Fix shortcut text breakpoint and spacing

app/views/components/datagrid/test-tree-filter-paging.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.e2e-spec.js
Fixed the filter and paging for treegrid was not working properly with Datagrid.
Closes #4293
- Navigate to: http://localhost:4000/components/datagrid/test-tree-filter-paging.html
- Use filter on column `Position`
- Apply the filter `> 30`
- See only rows with `Position` values 37, 38 and 40 should be displayed
=> 4293 - Fix the filter and paging for treegrid with datagrid

docs/CHANGELOG.md, src/components/tabs/tabs.js
This PR fixes an issue in the Tabs `add()` API, where it was incorrectly picking up `#` at any location in the string and attempting to use the whole string as an ID selector.  This behavior has been fixed, and now allows special characters in Tab titles.
Closes #4179
- Open http://localhost:4000/components/tabs-module/example-legacy-style.html
- Uncheck the "fill with garbage" box, enter `!@#$%^&*()` in the "Tab Name" field, and click the "Create New Tab" button
- There should be a new tab created with `!@#$%^&*()` as the title, with no JS errors …
=> 4179 - Allow special characters to be used in Tab titles

app/views/components/datepicker/example-index.html, src/components/monthview/monthview.js
Fixed a small error clicking the edge and then clicking another item in the month/year picker.
Fixes #4320
- go to http://localhost:4000/components/datepicker/example-index.html
- click the month/year to open the month year picker
- select the selected month in the dom and remove class 'is-selected"
- click another month
- should be no error - and work as expected
- note that this happens clicking the edge as well but this was easier to reproduce
=> 4320 - Fix error in datepicker

docs/CHANGELOG.md, src/components/toolbar-flex/_toolbar-flex.scss, test/components/datepicker/datepicker.e2e-spec.js
H2's had an extra scrollbar
Fixes #4325
- go to http://localhost:4000/components/toolbar-flex/example-index?theme=uplift&variant=light
- look for an extra scroll bar item as per the original issue, you wont see it because i fixed it :)
=> 4325 - Remove extraneous scrollbar

docs/CHANGELOG.md, src/components/editor/_editor.scss
Bullets in RTL mode did not have the margin negated in RTL mode. Added a quick fix.
Fixes #4327
- go to http://localhost:4000/components/editor/example-index.html?locale=ar-SA
- clear all text
- type Test (enter) Test
- select all text
- click bullet list
- list should be visible and look lovely now
=> 4327 - Add fix for RTL bullets in editor

docs/CHANGELOG.md, scripts/data/expected-files.json, src/components/tabs-header/_tabs-header-uplift.scss, src/components/tabs-header/_tabs-header.scss, src/components/tabs-vertical/_tabs-vertical.scss, src/components/tabs/_tabs-uplift.scss, src/components/tabs/_tabs.scss, src/core/_controls-uplift.scss
Fixes the page container layout, add more icon focus, and add more icon size on uplift theme, mobile view. 
Also added possible related issue that I noticed when testing the page:
- Fix caret icon position on dropdown when it exceeds the tab
Closes https://github.com/infor-design/enterprise/issues/4289
- Go to http://localhost:4000/components/tabs-header/example-add-tab-button.html?theme=uplift&variant=light
- Resize the page down to `766px`
- The page layout should not contain a big white space on top and should not have paddings both left and …
=> 4289 - Fix page layout and add more icon size

app/views/components/tree/example-plus-minus-folders.html, docs/CHANGELOG.md, src/components/tree/_tree-uplift.scss, src/components/tree/_tree.scss, src/components/tree/tree.js
We used to be able to add an svg icon the text node of the tree. But changes/encoding broke this. So added it back
Fixes #4305
- go to http://localhost:4000/components/tree/example-plus-minus-folders.html
- should see one icon in the main JS and one added via addNode
- should look good now and everything else works
- also try uplift mode.
=> 4305 - Add ability to add icon in node text

docs/CHANGELOG.md, src/components/tabs/tabs.js, test/components/tabs/tabs.e2e-spec.js
This PR makes a quick change to the `remove()` method to account for tabs that might be hidden by a nested parent.  Previously removing tabs that were contained by a hidden tab panel would throw a JS error.  This has been fixed.
Closes #4356
- Open http://localhost:4000/components/tabs/test-nested-horizontal-tabs.html
- Click on "Tab #2" to reveal the nested tabs container.  Ensure "Tab #4" is present.
- Click on "Tab #1" to hide the nested tabs container again.
- Open a dev tools console and type …
=> 4356 - Fix Removing Nested Tabs

docs/CHANGELOG.md, src/components/editor/editor.js, test/components/editor/editor.e2e-spec.js
This PR fixes a bug in the Editor where when text is partially selected and changed by the Fontpicker, the Fontpicker's state wasn't correctly updated.
Closes #4309 
- Open http://localhost:4000/components/editor/example-index.html
- Clear the editor contents and type "test test"
- Use either keyboard or mouse to select just the first "test".
- Open the Fontpicker and choose "Header 1".  The entire block of text should change from `<p>`-wrapped to `<h3>`-wrapped, and the text inside the Fontpicker should immediately read "Header 1".
**Included …
=> 4309 - Fix Fontpicker to correctly match partially modified Editor content

docs/CHANGELOG.md, src/components/editor/_editor.scss, src/components/toolbar-flex/toolbar-flex.item.js
This PR makes a small change to the timing of calculation of the overflow in Flex Toolbars.  Previously, this was causing issues in certain toolbars (very prevalent in the Formatter Toolbar/Editors) where some items that were overflowed were not being displayed in the menu.  This has been fixed.
Closes #4296
- Open http://localhost:4000/components/editor/example-index.html
- Shrink the page so that one or more buttons on the formatter toolbar are cut off by the edge of the editor.
- Click the "..." More Actions button.  Ensure that all buttons …
=> 4926 - Fix missing "More Actions" items in Flex Toolbars

docs/CHANGELOG.md, src/components/tree/tree.js
Fixed toggle node without making select/unselect was not working properly with Tree. For this case we have setting `expandTarget: 'icon'` which was broken when ran thru api `tree.toggleNode(targetNode)`, so this PR should fix it.
Closes #3927
- Navigate to: http://localhost:4000/components/tree/test-expand-target.html (example should use setting `expandTarget: 'icon'`)
- Run in console below commands, to see toggle/select/unselect node state
```
var treeApi = $('#json-tree').data('tree'); // get tree api
var targetNode = …
```
=> 3927 - Fix toggle node without selection with tree

app/views/components/lookup/test-beforeshow-cancel.html, docs/CHANGELOG.md, src/components/lookup/lookup.js
Fixed the event `beforeShow` was only triggers one time with Lookup.
Closes infor-design/enterprise-ng#899
- Navigate to: http://localhost:4000/components/lookup/test-beforeshow-cancel.html
- Click on the lookup icon
- Toast shows (but lookup modal should not open)
- Click as many times, it should show toast every time it clicked
Test in NG
- Pull and build ([NG master](https://github.com/infor-design/enterprise-ng.git))
- Copy and replace "dist" folder from `enterprise` to …
=> 899 - Fix before show event with lookup

app/views/components/lookup/test-short-field-custom.html, docs/CHANGELOG.md, src/components/lookup/_lookup.scss
Fixed short field icon padding was misaligned in RTL mode with Lookup.
Closes #1812
- Navigate to:
- http://localhost:4000/components/lookup/test-short-field-custom.html?locale=ar-EG
- http://localhost:4000/components/lookup/test-short-field-custom.html?theme=uplift&variant=light&colors=0066D4&locale=ar-EG
- See lookup input text `DA` and icon should not overlap
=> 1812 - Fix short field icon padding in rtl with lookup

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixed filter was not working if user types slow in the filter input for treegrid with Datagrid.
Closes #4270
- Navigate to: http://localhost:4000/components/datagrid/test-tree-filter.html
- Use filter for column `Order Date`
- Type slow `06/02/2014` (DO NOT: use picker, copy/paste, or type fast) and press enter
- Should show only two rows with id: 7 and 8 (row id: 7 - date not match but show, because parent node)
=> 4270 - Fix filter while type slow for treegrid with datagrid

app/views/components/toast/example-index.html, docs/CHANGELOG.md, src/components/toast/toast.js, test/components/toast/toast-api.func-spec.js
Adds the ability to set id's or arbitrary attribute on/in the toast API. This can be done by straight string or use a function that has the toast count in it. And you can set one or more at a time
Fixes #4275
- cases covered by tests but can be tested manually:
- go to http://localhost:4000/components/toast/example-index.html
- click show toast
- (quickly) inspect the DOM and notice an ID is appended
=> 4275 - Add id setting to toast

docs/CHANGELOG.md, src/components/locale/locale.js
When nb-NO is used as a language (normal is to use the language `'nb`) then for some reason in angular you may get a max stack error. This fixes that issue.
Fixes infor-design/enterprise-ng#874
- build this branch
- copy it to a NG local running project (node_modules)
- edit src/app/datagrid/datagrid-dynamic.demo.ts so the constructor is
```
constructor(
private service: DataGridDemoService
) {
Soho.Locale.setLanguage('nb-NO').done(function () {
Soho.Locale.translate('AboutText');
});
}
```
- go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-dynamic
- should not get an error in …
=> 874 - Fixed stack overflow when setting nb-NO

app/views/components/datagrid/test-paging-select-serverside-mixed.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixed activated row on 2nd or any subsequent page was not highlighting for mixed selection mode with Datagrid.
Closes infor-design/enterprise-ng#900
- Navigate to: http://localhost:4000/components/datagrid/test-paging-select-serverside-mixed.html
- Click any row in 1st page to make it active (blue background should apply)
- Goto 2nd or any subsequent page
- Click any row
- See it should make row active as 1st page (blue background should apply)
=> 900 - Fix activated row highlight with datagrid

docs/CHANGELOG.md, src/components/accordion/_accordion-mixins.scss, src/components/pager/pager.js
Using the arrow key in the page size selector threw an error. This is because the pager's keyboard logic is triggered.
Fixes #4383
- open the page size selector
- use arrow up and down and the enter to select
- ensure you can still use arrow keys across the pager toolbar
=> 4383 - Fix an error using arrow keys with pagesize selector

app/views/components/datagrid/test-alerts-right-align.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
Fixed icons right text alignment for extra-small row height with Datagrid.
Closes #4355
- Navigate to: http://localhost:4000/components/datagrid/test-alerts-right-align.html
- Change row height to extra-small
- Make the column `Alert w Text` width wider
- See column text should not be truncated
=> 4355 - Fix icons right text alignment with datagrid

docs/CHANGELOG.md, src/components/validation/validator.js
Fixed after the execution resetForm() was not resting dropdown and editor the fields with Validation.
Closes #4259
- Navigate to: http://localhost:4000/components/validation/example-validation-form.html
- Select the blank item in dropdown `State` and click anywhere to trigger the validation
- Run in console as below
- `$('body').resetForm();` it should remove validation error
- `$('#states').data();`, it should return `dropdown` api which should NOT contain key/value for `isValid`
- `$('div.dropdown').data();`, it should …
=> 4259 - Fix error after reset form with validation

docs/CHANGELOG.md, src/components/editor/editor.js
Fixes #4411 
- go to http://localhost:4000/components/editor/example-index.html
- click at the end of the first paragraph and hit enter
- switch to the visual view
- switch back -> See that the formating is the same as previous
- test scenarios of stripping empty tags
=> 4411 - Fix incorrect stripping of b tags in the editor

docs/CHANGELOG.md, src/components/popupmenu/popupmenu.js
Fixed an issue where the Colorpicker closes when pressing or clicking outside the swatch but inside the colorpicker popup.
closes #3559 
- Go to http://localhost:4000/components/colorpicker/example-index.html 
- Click on the whitespace in between or outside of the swatches.
- The Colorpicker should stay open.
- Click on a swatch and the Colorpicker should behave as expected.
=> 3559 - Fix Colorpicker selection issue

docs/CHANGELOG.md, src/components/toolbar-flex/toolbar-flex.js
Found that in this example the tabindex is not set on the initial item. This is actually (at least partly) because if updated is called it will reset the tabindex. Applied a fix
Fixes #4418
- go to http://localhost:4000/components/header/example-flex-toolbar.html
- tab to toolbar - you should hit the hamburger and it should show
=> 4418 - Fix flex toolbar tabbing

src/components/datagrid/_datagrid.scss, src/components/toast/toast.js
Fixed a comment on https://github.com/infor-design/enterprise/commit/54c5234d128dce769d64056d141ed0c30abfa9ca#commitcomment-42722706 and fixed an issue with the background color and errors on a recent fix
Fixes #4420
- make the order date have an error by existing after edit mode
- try hovering and making sure the background color doesnt bleed
=> 4420 - Correct back color and exit early

docs/CHANGELOG.md, src/components/page-layouts/_layouts.scss
This fixes the height for the sidebar of a list detail in responsive view.
Closes #4426 
1. Go to http://localhost:4000/components/page-patterns/example-list-detail-search-paging.html?theme=uplift&variant=light
2. Shrink window down to responsive view
3. Notice the paging bar
=> Fix side bar height in responsive mode

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Added PR for contribution / fix as noted on https://github.com/infor-design/enterprise/issues/4429
Fixes #4429
- Click dropdown cell on first row (column/cell 9) - up/down arrow and it works fine
- Open up DevTools and in the developer console type:-
```
$('#datagrid').data('datagrid').setActiveCell(0, 9)
```
- Click back into browser with grid and attempt to use up/down keys on the list. Notice that the up/down arorw is working now
=> 4429 - Add a fix for setfocus and arrow keys

src/components/datagrid/_datagrid.scss
Fixed icon background was different for row hover with Datagrid.
Closes #4264
- Navigate to: http://localhost:4000/components/datagrid/example-editable.html
- Click on any cell in column `Portable`
- Keep the mouse pointer on same cell (so it keep hover on row)
- Use right arrow key to focus cell in column `Action` in same row
- Soon it got focus, cell should show icon in column `Action`
- See the background for this icon should be fine
=> 4264 - Fix icon background with datagrid [v4.33.x]

src/components/tabs/tabs.js
This is a follow up fix for https://github.com/infor-design/enterprise/issues/4332. When `tab-more` element is visible, the animated bar is not correctly position in their respective tab when selected.
Closes https://github.com/infor-design/enterprise/issues/4332
Related/Previous PR https://github.com/infor-design/enterprise/pull/4397
- Go to http://localhost:4000/components/tabs/example-index.html?theme=uplift&variant=light&colors=0066D4&locale=ar-EG
- Resize the page until the `tab-more` el will show
- The animated bar should perfectly position …
=> 4332 - Fix the position of animated bar when more button is visible (RTL) [4.33.x]

app/views/components/line/example-localize.html, docs/CHANGELOG.md, src/components/bar/bar.js, src/components/column/column.js, src/components/completion-chart/completion-chart.js, src/components/line/line.js, src/components/locale/locale.js, src/components/pie/pie.js, test/components/line/line.e2e-spec.js
Changed the charts so that when you set the locale it will set d2 defaultLocale. This all the numbers in charts (for example decimal and group seperator). The K for example 1K is not common in other languages so is not localized but still can be used
Fixes #4437
- compare http://localhost:4000/components/line/example-localize.html?locale=de-DE
and http://localhost:4000/components/line/example-localize.html
- notice the numbers have group separator which changes from comma to decimal
- also check in the tooltip
- since this applies now to ALL d3 charts - smoke test some charts, test as many …
=> 4437 - Add localization to charts

src/components/calendar/calendar-shared.js, src/components/calendar/calendar.js, test/components/datepicker/datepicker.e2e-spec.js
Added a better fix for calendar colors as the previous fix did not fix it all. This continues on #4439
Fixes #4447
- dbl click a day and add an event and pick admin -> color should be purple when inserted (try others as well)
- in the + menu select Add Event modal, and make the same test. this should now be fixed
- confirm the two events on http://localhost:4000/components/calendar/test-event-color-override.html still are fixed colors
=> 4447 - Added a better fix for calendar colors [v4.33.x]

docs/CHANGELOG.md, src/components/colorpicker/colorpicker.js, src/components/editor/editor.js, src/components/popupmenu/popupmenu.js, src/components/toolbar-flex/toolbar-flex.item.js, test/components/datepicker/datepicker.e2e-spec.js
Fixed the color picker was not opening the popup for overflow menu and had name as undefined in list with Editor.
Closes #4398
- Navigate to: http://localhost:4000/components/editor/example-index.html
- Make the browser window small so that the button `Text color` NOT fit in toolbar ( can use device toolbar mode in dev tools)
- Click the `...` action button to open menu
- See color picker button name should list as `Text color`
- Click on it and see it should open the color picker popup
=> 4398 - Fix color picker for overflow menu with editor

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, src/utils/xss.js
Fixed the leading spaces were removed on editing cells with Datagrid.
Closes #4380
- Navigate to: http://localhost:4000/components/datagrid/example-editable.html
- Click on any cell in column `Activity` to go in edit mode
- Edit text with leading/trailing spaces
- Click enter key to commit the edit mode
- Click enter key again to go in edit mode
- See it should keep leading/trailing spaces
=> 4380 - Fix leading spaces on editing cells with datagrid

docs/CHANGELOG.md, src/components/page-layouts/_summary-form.scss
Fixes summary form data from getting cut off on a smaller viewport.
Closes https://github.com/infor-design/enterprise/issues/3861
- Go to http://localhost:4000/components/fieldset/example-index.html?theme=uplift&variant=light
- Resize the browser or toggle device toolbar
- Summary form data below should not cut off
=> 3861 - Fix summary form data gets cut off on mobile view

docs/CHANGELOG.md, src/components/bar/bar.js, src/components/column/column.js, src/utils/excel.js
Fixed the special characters (é, à, ü, û, ...) export to csv was not generated them correctly with Datagrid.
Closes #4347
- Navigate to: http://localhost:4000/components/datagrid/example-export-from-button.html
- Click on toolbar button `Export To Csv`
- It should download file `muExport.csv`
- Open this download file with `MS Excel`
- See in column `Extra`, all the special characters should be generated correctly
=> 4347 - Fix special characters export to csv with datagrid

docs/CHANGELOG.md, src/components/editor/editor.js
Fixed the focus was getting lost after execute toolbar buttons with Editor.
Closes #4335
- Navigate to: http://localhost:4000/components/editor/example-index.html
- Tab to editor toolbar button `B`
- Press `Enter`
- See the focus should remain on the button
=> 4335 - Fix focus on toolbar buttons with editor

app/views/components/popupmenu/test-return-focus.html, docs/CHANGELOG.md, src/components/listview/_listview-uplift.scss, src/components/listview/_listview.scss, src/themes/theme-soho-contrast.scss, src/themes/theme-uplift-contrast.scss
Readonly and non-selectable listview should not have hover state.
Closes https://github.com/infor-design/enterprise/issues/4452
- Go to http://localhost:4000/components/listview/example-index?theme=uplift&variant=light&colors=0066D4
- Hover the items
- It should not have hover styling
- Test this also on all themes and variants combinations
=> 4452 - Fix readonly and non-selectable listview should not have hover state

app/views/components/about/example-index.html, app/views/components/contextualactionpanel/example-workspaces.html, app/views/components/donut/example-index.html, app/views/components/pie/example-index.html, docs/AUTOMATION.md, docs/CHANGELOG.md, docs/CSP.md, docs/SECURITY.md, src/components/about/about.js, src/components/about/readme.md, src/components/charts/charts.js, src/components/contextualactionpanel/contextualactionpanel.js, src/components/contextualactionpanel/readme.md, src/components/donut/readme.md, src/components/pie/pie.js, src/components/pie/readme.md, test/components/about/about.e2e-spec.js, test/components/contextualactionpanel/contextualactionpanel.e2e-spec.js, test/components/dount/donut.e2e-spec.js, test/components/pie/pie.e2e-spec.js
Adds the attributes/automation id / id functionality for donut, cap, pie and about. this included docs and tests.
Also updated the SECURITY.md since its shown on the github page in the wrong context. 
@deep7102 checkout that i added the legend code and how i did it with PIE. this might be done the same on other charts
Part of 4498 but doesnt close it all
- review the text in the docs
- go to http://localhost:4000/components/donut/example-index.html and http://localhost:4000/components/pie/example-index.html and check that the slices get an id from the data
- go to …
=> 4498 - Add automation id for donut, pie, cap and about

app/views/components/area/example-index.html, app/views/components/bubble/example-index.html, app/views/components/line/example-index.html, app/views/components/scatterplot/example-index.html, docs/AUTOMATION.md, docs/CHANGELOG.md, src/components/area/readme.md, src/components/bubble/readme.md, src/components/line/line.js, src/components/line/readme.md, src/components/scatterplot/readme.md, test/components/area/area.e2e-spec.js, test/components/bubble/bubble.e2e-spec.js, test/components/line/line.e2e-spec.js, test/components/scatterplot/scatterplot.e2e-spec.js
Adds the attributes/automation id/ id functionality for area, bubble, line and scatterplot charts.
- Navigate to:
- http://localhost:4000/components/area/example-index.html
- http://localhost:4000/components/bubble/example-index.html
- http://localhost:4000/components/line/example-index.html
- http://localhost:4000/components/scatterplot/example-index.html
- Check for `id` and `data-automation-id` attributes, get from the settings (each line, dot, symbol and legend)
- Review the text in the docs …
=> 4498 - Add automation id for area, bubble, line and scatterplot charts

app/views/components/autocomplete/example-index.html, app/views/components/dropdown/example-index.html, app/views/components/field-filter/example-index.html, app/views/components/popupmenu/example-index.html, docs/CHANGELOG.md, src/components/autocomplete/autocomplete.js, src/components/autocomplete/readme.md, src/components/dropdown/dropdown.js, src/components/dropdown/readme.md, src/components/field-filter/field-filter.js, src/components/field-filter/readme.md, src/components/popupmenu/popupmenu.js, test/components/autocomplete/autocomplete.e2e-spec.js, test/components/dropdown/dropdown.e2e-spec.js, test/components/field-filter/field-filter.e2e-spec.js, test/components/popupmenu/popupmenu.e2e-spec.js
Adds automation is attributes for autocomplete, field filter, dropdown and popupmenu
related to #4498 
- pull and run branch
- go to http://localhost:4000/components/autocomplete/example-index.html and make sure the element gets automation id from the settings
- go to http://localhost:4000/components/field-filter/example-index.html and make sure the field wrapper, label and select get an automation id from the settings
- go to http://localhost:4000/components/dropdown/example-index.html open the dropdown and make sure the dropdown list, label, input, trigger and listbox get an automation …
=> 4498 - Automation IDs for autocomplete, field filter, dropdown and popupmenu

app/views/components/contextmenu/example-index.html, app/views/components/fieldset/example-index.html, app/views/components/popover/example-index.html, docs/AUTOMATION.md, src/components/contextmenu/readme.md, src/components/fieldset/readme.md, src/components/popover/readme.md, test/components/fieldset/fieldset.e2e-spec.js, test/components/popover/popover.e2e-spec.js
Add automation ids to fieldset, contextmenu and popover
related to #4498 
- pull and run branch
- go to http://localhost:4000/components/fieldset/example-index.html make sure the root element has an id/automation-id
- go to http://localhost:4000/components/contextmenu/example-index.html make sure all the menu items have an id/automation-id
- go to http://localhost:4000/components/popover/example-index.html make sure all the menu items have an id/automation-id make sure the `popover-contents` element, the apply button and the view more buttons have an id/automation-id …
=> 4498 - Add automation ids to fieldset, contextmenu and popover

app/views/components/bullet/example-index.html, app/views/components/bullet/test-data-group-automation.html, app/views/components/stepchart/example-index.html, docs/AUTOMATION.md, docs/CHANGELOG.md, src/components/bullet/bullet.js, src/components/bullet/readme.md, src/components/stepchart/readme.md, src/components/stepchart/stepchart.js, test/components/bullet/bullet.e2e-spec.js, test/components/stepchart/stepchart.e2e-spec.js
Adds the attributes/automation id/ id functionality for Bullet and Stepchart Charts.
Bullet
- Navigate to:
- http://localhost:4000/components/bullet/example-index.html
- http://localhost:4000/components/bullet/test-data-group-automation.html
- Check for `id` and `data-automation-id` attributes, get from the settings (each title, subtitle, range, measure, marker for single and grouped)
- Review the text in the docs
Stepchart
- Navigate to:
- http://localhost:4000/components/stepchart/example-index.html
- Check for `id` and …
=> 4498 - Add automation id for bullet and stepchart charts

app/views/components/listview/example-singleselect-no-deselect.html, docs/CHANGELOG.md, src/components/listview/listview.js, test/components/listview/listview.e2e-spec.js
Adds a new option to listview to prevent the deselection of rows in single select mode.
Fixes #4376 
- go to http://localhost:4000/components/listview/example-singleselect-no-deselect.html
- select a row
- select another row
- try and toggle off selection on a row (you cant, this is the new option)
=> 4376 - Add allowDeselect feature

app/views/components/rating/example-index.html, app/views/components/slider/example-index.html, app/views/components/spinbox/example-index.html, docs/AUTOMATION.md, docs/CHANGELOG.md, src/components/slider/readme.md, src/components/slider/slider.js, src/components/spinbox/readme.md, src/components/spinbox/spinbox.js, test/components/rating/rating.e2e-spec.js, test/components/slider/slider.e2e-spec.js, test/components/spinbox/spinbox-settings.func-spec.js, test/components/spinbox/spinbox.e2e-spec.js
Adds the attributes (ids & automation ids) for rating, slider, and spinbox. Also includes e2e and docs.
Partial #4498 
1.) Rating
- Go to http://localhost:4000/components/rating/example-index
- Open developers tool and inspect the element
- `rating` and `one - five star` elements should have ids and automation ids
2.) Slider
- Go to http://localhost:4000/components/slider/example-index
- Open developers tool and inspect the element
- `slider`, `slider wrapper`, `slider hitarea`, `slider range`, `slider handle`, and `slider ticks` should all have …
=> 4498 - Add ids and automation ids for Rating, Slider and Spinbox

app/views/components/completion-chart/example-variations.html, app/views/components/targeted-achievement/example-index.html, docs/AUTOMATION.md, docs/CHANGELOG.md, src/components/completion-chart/completion-chart.js, src/components/completion-chart/readme.md, src/components/targeted-achievement/readme.md, test/components/completion-chart/completion-chart.e2e-spec.js, test/components/targeted-achievement/targeted-achievement.e2e-spec.js
Adds the attributes/automation id/ id functionality for Completion Chart and Targeted Achievement Charts.
Bullet
- Navigate to: http://localhost:4000/components/completion-chart/example-variations.html
- Check for `id` and `data-automation-id` attributes, get from the settings
- For 1st chart see (name, total-value, total-bar, remaining-bar, remaining-value, remaining-text, completed-bar, completed-value and completed-text)
- For 7th chart see (info-value, info-text, total-bar, remaining-bar, completed-bar, completed-value, …
=> 4498 - Add automation id for completion chart and targeted-achievement charts

docs/CHANGELOG.md, src/components/homepage/homepage.js
Fixed four column widgets were incorrectly positioned, left aligned on large screen with Homepage.
Closes #4541
- Navigate to: http://localhost:4000/components/homepage/example-four-column.html
- Widgets main container should be in center of screen
=> 4541 - Fix incorrectly positioned widgets with homepage

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.e2e-spec.js
When doing server side filtering with keyword search the highlight didnt show up. This fixes this issue.
Fixes #4488
- go to http://localhost:4000/components/datagrid/test-keyword-search-serverside?layout=nofrills
-  click into the search field in the toolbar
- type "214" and then enter
- the list should both filter down and show the highlights in bold
=> 4488 - Add fix for keyword search highlighting

app/views/components/button/example-menubutton.html, app/views/components/contextmenu/example-index.html, app/views/components/contextmenu/example-page-rightclick.html, app/views/components/popupmenu/example-ajax.html, app/views/components/popupmenu/example-index.html, app/views/components/toolbar-flex/example-index.html, app/views/components/toolbar-flex/example-more-actions-default-behavior.html, docs/AUTOMATION.md, docs/CHANGELOG.md, src/components/button/button.js, src/components/button/readme.md, src/components/popupmenu/popupmenu.js, src/components/popupmenu/readme.md, src/components/toolbar-flex/readme.md, src/components/toolbar-flex/toolbar-flex.item.js, src/components/toolbar-flex/toolbar-flex.js, test/components/button/button-api.func-spec.js, test/components/popupmenu/popupmenu.e2e-spec.js, test/components/popupmenu/popupmenu.func-spec.js, test/components/toolbar-flex/toolbar-flex-api.func-spec.js
This PR adds:
- the ability to pass automation ids and other custom attributes to the Flex Toolbar and its Items via the `attributes` setting
- the `attributes` setting in the Button and Popupmenu APIs (couldn't just do this with markup so I had to add the APIs -- added tests/examples/docs for these where there weren't any)
related to #4498 
Pull this branch, build, run the app:
_Context Menu:_
- Open http://localhost:4000/components/contextmenu/example-index.html - The automation ids should work here but I had to change the logic slightly - the first input field, menu `<ul>`, and all …
=> 4498 - Add attributes/ids to Flex Toolbar, enable `attributes` setting in Button/Popupmenu APIs

app/views/components/lookup/example-index.html, docs/AUTOMATION.md, docs/CHANGELOG.md, src/components/lookup/lookup.js, src/components/lookup/readme.md, test/components/lookup/lookup.e2e-spec.js
This PR adds the `attributes` setting to the Lookup component for custom/automation ids
- related to #4498 
- depends on #4552 (needs to be tested with datagrid `attributes` API but should work)
- Open http://localhost:4000/components/lookup/example-index.html
- Inspect the first Lookup field's input and trigger icon.  Both should have `data-automation-id`
- Open the lookup by clicking the trigger icon.  When it opens:
- The Modal should have any auto-generated attributes set on their respective elements (`.modal` container, its trigger button, …
=> 4498 - Add the `attributes` setting to Lookup, add docs/tests/examples

app/views/components/editor/example-index.html, app/views/components/hierarchy/example-context-menu-with-details.html, docs/AUTOMATION.md, src/components/editor/editor.js, src/components/editor/readme.md, src/components/hierarchy/hierarchy.js, src/components/hierarchy/readme.md, test/components/editor/editor.e2e-spec.js, test/components/hierarchy/hierarchy.e2e-spec.js
Adds the attributes/automation id/ id functionality for Editor and Hierarchy.
Editor
- Navigate to: http://localhost:4000/components/editor/example-index.html
- Check for `id` and `data-automation-id` attributes, get from the settings (for each button, fontpicker options, colors in color-picker, url/image modal input, modal dropdown options and modal buttons)
- Review the text in the docs
Hierarchy
- Navigate to: http://localhost:4000/components/hierarchy/example-context-menu-with-details.html
- Check for `id` and …
=> 4498 - Add automation id for editor and hierarchy

docs/CHANGELOG.md, src/components/tabs-module/_tabs-module-uplift.scss
Fixes alignment of tab items in uplift theme.
Closes https://github.com/infor-design/enterprise/issues/4538
- Navigate to http://localhost:4000/components/tabs-module/example-index.html?theme=uplift&variant=light&colors=0066D4
- Check the tab items
- Tab items (text) should centered correctly
=> 4538 - Fix misalignment tab items in uplift theme

docs/CHANGELOG.md, src/components/autocomplete/autocomplete.js
When the autocomplete ajax calls are slow and you do a second request the dropdown will open with both requests. This fixes the issue
Fixes #4387
- go to http://localhost:4000/components/autocomplete/example-index.html
- once the page loads open chrome tools and go to the network tab and set the speed to 3g
- type "a" and wait for the request to start
- quickly backspace and type "c"
- only the "c's" should show in the dropdown (last request)
=> 4387 - Fix for slow autocomplete ajax calls

app/views/components/processindicator/example-index.html, app/views/components/tree/example-ajax.html, app/views/components/tree/example-select-multiple.html, docs/AUTOMATION.md, src/components/processindicator/readme.md, src/components/tree/readme.md, src/components/tree/tree.js, test/components/tree/tree.e2e-spec.js
Adds the attributes/automation id/ id functionality for Tree and Processindicator.
Tree
- Navigate to:
- http://localhost:4000/components/tree/example-ajax.html
- http://localhost:4000/components/tree/example-select-multiple.html
- Check for `id` and `data-automation-id` attributes, get from the settings (for link, icon and checkbox)
- Review the text in the docs
Processindicator
- Navigate to: http://localhost:4000/components/processindicator/example-index.html
- Check for `id` and `data-automation-id` attributes, added directly …
=> 4498 - Add automation id for tree and processindicator

app/views/components/editor/example-preview.html, docs/CHANGELOG.md, src/components/editor/editor.js
LM uses font size css and font tag in the editor when they integrate with external tools. This was getting stripped out and causing end user confusion.
Removed this stripping.
Fixes #4557
- go to http://localhost:4000/components/editor/example-preview.html
- notice i have a font size and font tag at the bottom in prevew
- go into edit mode
- should still show the  font size and font tag
- switch to preview
- should still show the  font size and font tag code
- switch back to edit mode
- should still show the  font size and font tag (before the font-size was stripped) …
=> 4557 - Fix stripping of font-size

app/views/components/about/test-nested.html, docs/CHANGELOG.md, src/components/about/about.js, src/components/modal/modal.js, test/components/about/about.e2e-spec.js
This PR fixes an issue where the About dialog was unable to be closed by click, after a nested modal had previously been closed.  
- Related to infor-design/enterprise-ng#915
- Depended on by infor-design/enterprise-ng#937 
- Open http://localhost:4000/components/about/test-nested.html
- Click "Open About Screen"
- Inside the About dialog, click the "Open Nested Modal" button
- Click the "X" button inside the nested modal to close it
- Click the "X" button inside the About dialog.  It should close the About dialog as expected. …
=> NG#915 - Fix issue where closing About after closing nested Modal was impossible

docs/CHANGELOG.md, src/components/dropdown/dropdown.js, test/components/dropdown/dropdown.e2e-spec.js
Fixes the last option icon when filtering in dropdown search field. Removing the script that changes the last icon to `icon-empty-circle`.
Closes https://github.com/infor-design/enterprise/issues/4474
- Go to http://localhost:4000/components/dropdown/example-icons
- In first element, click on the dropdown and remove the text in the search field
- It should not change the last icon to `icon-empty-circle`
- It should add `icon-empty-circle` in search field only (Updated)
=> 4474 - Fix the last option icon changes when filtering

docs/CHANGELOG.md, src/components/fileupload-advanced/fileupload-advanced.js
Fixed abort method was not working properly to remove the file block when upload fails with fileupload advanced.
Closes infor-design/enterprise-ng#938
- Pull and build NG branch ([938-fileupload-advanced-ngsend](https://github.com/infor-design/enterprise-ng/tree/938-fileupload-advanced-ngsend))
- Navigate to http://localhost:4200/ids-enterprise-ng-demo/fileupload-advanced
- Use last field on the page labeled as: `Send Method`
- Upload a …
=> 938 - Fix abort method with fileupload advanced

app/views/components/datagrid/test-editable-select-on-edit.html, app/views/components/datagrid/test-editable-spinbox.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.editors.js, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid-settings.func-spec.js
Added setting for selection on enter edit mode with Datagrid.
Closes #4485
- Navigate to: http://localhost:4000/components/datagrid/test-editable-select-on-edit.html
- Click on any editable cell, text should `not` be selected
- Navigate to: http://localhost:4000/components/datagrid/test-cell-edit-callback.html
- Click on any editable cell, text should be selected
=> 4485 - Add setting for selection on enter edit mode with datagrid

docs/CHANGELOG.md, src/components/field-options/_field-options-uplift.scss, src/components/field-options/_field-options.scss, src/components/field-options/field-options.js
Fixed the action button was misaligned for safari with Field Options.
Closes #4610
- Use safari mac
- Navigate to: http://localhost:4000/components/field-options/example-index.html?theme=uplift&variant=dark&colors=0066D4
- Try field options in each field
- See action button should not misalign
- Also in compact mode
=> 4610 - Fix alignment with field options

docs/CHANGELOG.md, src/components/colorpicker/colorpicker.js, src/components/tooltip/tooltip.js
Fixes an issue where toggling a colorpicker while another one was open the colorpicker would not select a color. Also fixes a separate issue where custom colors and their default counterparts were both getting the `is-selected` class.
closes #4146 
- Go to http://localhost:4000/components/colorpicker/example-custom-labels.html
- Open the bottom colorpicker
- While it's open, click on the trigger button in the top one 
- The colorpicker should close
- Open the top colorpicker and you should still be able to select a color
=> 4146 - Fix Colorpicker not selecting when multiple present on page

docs/CHANGELOG.md, src/components/tree/tree.js
Fixed the parent value was get deleted after use `addNode()` method with Tree.
Closes #4486
- Navigate to: http://localhost:4000/components/tree/test-add-node-with-parent-option.html
- Run in console as below:
- `var tree = $('#tree').data('tree');`
- `tree.addNode({id: 'newTestNode', text: 'New Test Node', parent: 'leadership'});`
- `tree.findById('newTestNode');`
- Check the return data for `parent` key/value should not be blank
=> 4486 - Fix parent for addnode method with tree

src/components/datagrid/_datagrid.scss
#4268 wasnt working on safari correctly so this is an additional fix.
Fixes #4268
- open http://localhost:4000/components/datagrid/example-summary-row.html in safari
- try all 4 row sizes and scroll down and ensure the bottom row is properly placed
=> 4268 - Add fix for safari

app/views/components/message/example-index.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js, test/components/datepicker/datepicker.e2e-spec.js
The fix to https://github.com/infor-design/enterprise/issues/4476 used spread to merge the updated data with the dataset. This dropped some information. Changed this to a deep copy merge.
Fixes #4674
Relates to #4476
- test http://localhost:4000/components//datagrid/example-row-reorder.html -> fixed an issue with a grey background around the icon
- build this branch and copy it over to the latest master in enterprise-NG
- run and go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-rowreorder -> try to reorder a row more than once and it should work again. note that this example has …
=> 4674 - Fix to update row

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.e2e-spec.js
When the rows selected are only some of the available rows the aria-checked state was wrong. This fixes that issue
Fixes #4491
- go to http://localhost:4000/components/datagrid/example-multiselect.html
- select one (not all rows)
- inspect the header checkbox dom and the `aria-checked` state should be `mixed`
- unselect all and the `aria-checked` state should be `false`
- select all and the `aria-checked` state should be `true`
=> 4491 - Fix mixed selection aria state

app/views/components/dropdown/test-8000-items.html, docs/CHANGELOG.md, src/components/dropdown/dropdown.js
CRM gave us an example with 8000 dropdown items with tooltips. The main issue preventing this from working well was the tooltips being initialized. Instead I made it a delegated event.
Also fixed a click issue thats related and fixed a few selectors to make it a bit faster. Decided we should not patch this as needs a bigger testing effort
Fixes #4672
Fixes #4638
- go to http://localhost:4000/components/dropdown/test-8000-items.html
- opening the page should not be too slow
- open the list -> this is much faster than before
- go to http://localhost:4000/components/dropdown/example-index
- …
=> 4672 - Fix performance with tooltips

docs/CHANGELOG.md, src/components/pager/pager.js
The pager - automation id feature did not attach ID's to the menu if the attachToBody option was used. This corrects that.
Fixes #4692
- go to http://localhost:4000/components/pager/example-standalone.html
- click "show page size selector"
- click "Attach page size menu to body"
- Open the page size menu
- inspect the dom on the menu on the menu items, they should have id's the same as they do when "Attach page size menu to body" is checked 
=> 4692 - Correct the id's when using attachToBody

app/views/components/rating/example-readonly.html, docs/CHANGELOG.md, src/components/rating/rating.js
Fixes a bug in the readonly function that prevent toggling the state back and forth from working correctly.
Fixes infor-design/enterprise-ng#958
- go to http://localhost:4000/components/rating/example-readonly.html
- it is initially readonly and you cant click the rating
- hit the toggle - now you can click the rating
- hit the toggle again - now you can't click the rating (this part was fixed)
=> 958 - Fix readonly function

app/views/components/datagrid/test-lookup-filter.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
When calling the applyFilter api the lookup filter did not refresh the clear button.
Fixes #4693 
- go to http://localhost:4000/components/datagrid/test-lookup-filter
- it calls applyFilter in the example so the x should be enabled
- try the following in the console tto make sure you can also reset it
```
$('#datagrid').data('datagrid').applyFilter([{ columnId: 'productId', operator: 'contains', value: '' }]);
// Reload Page
grid.applyFilter([])
```
=> 4693 - Fix to datagrid so that applyFilter refreshes the clear checkbox

docs/CHANGELOG.md, src/components/editor/_editor.scss
Fixes hyperlinks were not clickable when the editor is in readonly state.
Closes https://github.com/infor-design/enterprise/issues/4702
- Go to http://localhost:4000/components/editor/test-readonly.html
- Hyperlink should be clickable
=> 4702 - Fix hyperlinks not clickable in readonly state

docs/CHANGELOG.md, src/components/lookup/lookup.js
FIxes a bug submitted by @kvchaudhari that solves an issue doing selection in multiselect across pages
Fixes infor-design/enterprise-ng#954
1. pull this branch and build and copy over to an NG project
1 . Go to ids-enterprise-ng-demo/lookup
1. Go to "Products (Async Results) Multi Select" lookup -> Now there is no record selected in lookup.
1. Now click on browse button and open lookup pop up.
1. Go to page 2 and select only one record and click on apply button.
1. Now again open that popup and select one record from page 1 -> expect 2 records selected
1. Test out …
=> 954 - Add fix for multiselect selection

src/components/datagrid/_datagrid.scss
Adds an additional fix on #4693 for safari.
Fixes #4683
- go to http://localhost:4000/components/datagrid/test-lookup-filter-click-clear in safari
- click the lookup search and the X will show -> the x alignment should be ok
=> 4693 - Add fix for safari

docs/CHANGELOG.md, src/components/listview/_listview.scss, src/components/listview/listview.js
Fixed selectable text for touch devices with Listview.
Closes #4655
- Use iPhone11
- Navigate to: http://localhost:4000/components/listview/example-contextmenu.html
- Long press on a list row
- Context menu should open
- Text for list view row should not be selectable on touch devices
=> 4655 - Fix selectable text for touch devices with listview

app/views/components/tree/test-escape-node.html, docs/CHANGELOG.md, src/components/tree/tree.js
Fixed character entity was stripped for addNode() method with Tree.
Closes #4694
Navigate to: http://localhost:4000/components/tree/test-escape-node.html
- See both node text should have less than(<) and more then(>) sign
- 1st node text should be `<online>`
- 2nd node text should be `<online 2 after updateNode>`
Navigate to: http://localhost:4000/components/tree/example-ajax.html
- See 1st node text (should have less than sign)
- Click on 2nd node to open folder
- See 1st node text in that folder (should have less than sign) too
**Included in …
=> 4694 - Fix stripped character entity with tree

docs/CHANGELOG.md, src/components/calendar/calendar.js, test/components/calendar/calendar.e2e-spec.js
This PR fixes a small regression in the Calendar's legend area, where checkboxes were no longer linked correctly to their labels because of differing automated ids.  The issue is now fixed.
Closes #4746
- Open http://localhost:4000/components/calendar/example-index.html
- Try checking/unchecking any of the legend labels.  This should work now.
@jbrcna
=> 4746 - Fix regression in calendar linking legend checks to labels

app/views/components/dropdown/example-no-search.html, docs/CHANGELOG.md, src/components/dropdown/dropdown.js, test/components/dropdown/dropdown-updates-events.func-spec.js, test/components/dropdown/dropdown.e2e-spec.js
Adds some fixes for automation ID's on dropdown. To be patched to 4.36. Mainly the problem was some id's are missing and some are not overriding with the setting.
Fixes #4742
- go to http://localhost:4000/components/dropdown/example-index.html and open the list
- ensure the following have both an id and automation-id
```
select + div.dropdown-wrapper > div.dropdown`
.dropdown-list > ul
.dropdown-list > label
.dropdown-list > input
.dropdown-list > ul > li.dropdown-option > a
```
- go to http://localhost:4000/components/dropdown/example-no-search.html and open the list
- ensure …
=> 4742 - Add additional automation ID's

src/components/calendar/calendar.js
This is a follow up fix to PR #4747, after it was discovered that clicking on a legend checkbox was still not linked to showing/hiding events.  This PR changes the method of linking legend items to events to use the `name` attribute, instead of `id`s which are now variable.
Closes #4746 
- Pull, run, build
- Open http://localhost:4000/components/calendar/example-index.html
- Choose any date and add a new event.  Be aware of the event type you pick.
- After adding the event, toggle the event type's checkbox.  It should hide/show the event as expected.
=> 4746 - Re-link calendar events to legend clicks

src/components/modal/_modal-uplift.scss, src/components/tabs/_tabs-uplift.scss, src/components/tabs/_tabs.scss
This is a follow up fix for https://github.com/infor-design/enterprise/issues/4711. Added here the remaining types that was not included.
Added:
- success
- alert
Closes https://github.com/infor-design/enterprise/issues/4711
Related PR https://github.com/infor-design/enterprise/pull/4733
- Go to http://localhost:4000/components/tabs/test-info-message-and-icon.html
- Click Add Context button
- In the input field, type Test to trigger the info message and icon (In this test page, I already included the custom script to show those)
- In the template, …
=> 4711 - Fix remaining validation types

docs/CHANGELOG.md, src/components/listview/listview.js, src/components/swaplist/swaplist.js
Fixed user attributes need to be override existing attributes with Swaplist.
Closes infor-design/enterprise-ng#970
- Navigate to: http://localhost:4000/components/swaplist/example-index.html
- See 2nd swaplist the root element `id` should be `example2-swaplist`
=> 970 - Fix user attributes with swaplist

app/views/components/modal/test-focusable-elements.html, docs/CHANGELOG.md, src/utils/utils.js, test/components/modal/modal.e2e-spec.js
This PR makes some adjustments to the current method for retrieving focusable elements within a component, to better account for elements with `tabindex="-1"` and `disabled` attributes.
Closes #4740
- Open http://localhost:4000/components/modal/test-focusable-elements
- Click "Show Modal"
- When the modal opens, the third input field down labelled "Problem" should be focused.
=> 4740 - Improve detection of non-focusable elements in Modals

app/views/components/locale/test-format-big-negative.html, docs/CHANGELOG.md, src/utils/number.js, test/components/locale/locale.func-spec.js
Fixed a bug with big numbers where if the 11th digit is a zero in the middle of the number it will get lost due to incorrect logic in the toFixed routines.
Fixes #4656
- go to http://localhost:4000/components/locale/test-format-big-negative.html
- click the button
- the number should be the same in the lower field
=> 4656 - Added a fix for locale losing a digit

src/components/spinbox/spinbox.js, test/components/spinbox/spinbox-settings.func-spec.js, test/components/spinbox/spinbox.e2e-spec.js
**Explain the details for making this change. What existing problem does the pull request solve?**
When setting the [step] attribute, the spinbox would no longer allow double digits. 
Related github/jira issue (required):
Fixes #4762 
1. Go to 'example-stepped-intervals' under the spinbox component at https://master-enterprise.demo.design.infor.com/components/spinbox/example-stepped-intervals.html
2. Click on the spin up button until the number is in the double digits
3. Click or tab out of the spinbox
4. Notice that only one digit remains in the spinbox
5. Try typing multiple digits into the spinbox
6. Notice that only one digit is allowed
=> Stepped interval spinbox doesn't work properly for double digits

app/views/components/tabs/example-index.html, docs/CHANGELOG.md, src/components/trackdirty/trackdirty.jquery.js
Fixed error were showing when use trackdirty with tabs.
Closes infor-design/enterprise-ng#936
- Navigate to: http://localhost:4000/components/tabs/example-index.html
- See in console should not be any error
- Click on tab `Opportunities`
- Type something into `Dirty Tracking` input and blur
- Dirty indicator should show
Test on angular side:
- Pull and build NG branch ([master](https://github.com/infor-design/enterprise-ng))
- Copy and replace "dist" folder from `enterprise` …
=> 936 - Fix error were showing when use trackdirty with tabs 

app/views/components/busyindicator/test-activate-close.html, docs/CHANGELOG.md, src/components/busyindicator/busyindicator.js
Fixed an error was showing when called `close()` method too soon after `activate()` with Busy Indicator.
Closes infor-design/enterprise-ng#980
- Navigate to: http://localhost:4000/components/busyindicator/test-activate-close.html
- Click on button `Submit to activate Busy Indicator`
- See in console should not be any error
Test on angular side:
- Pull and build NG branch ([master](https://github.com/infor-design/enterprise-ng))
- Copy and replace "dist" folder from …
=> 980 - Fix an error was showing when close too soon with busy indicator

app/views/components/form/example-disabled-field.html, src/components/editor/editor.js, src/components/slider/slider.js
I didn't fully fix 4739 so adding more fixs to fix an error in editor, an extra tab in the slider and an extra tab in disabled multiselect. Wont bother patching this.
Fixes #4739
- go to http://localhost:4000/components/form/example-disabled-field.html
- disable the form with the button
- tab through the form (should not be able to tab anywhere but the link in the editor)
=> 4739 - Fix issues on disabled example (4.37.x)

app/views/components/homepage/example-editable.html, docs/CHANGELOG.md, src/components/homepage/homepage.js
Fixed the wrong metadata was sending for resize, reorder and remove card events with Homepage.
Closes #4798
- Navigate to: http://localhost:4000/components/homepage/example-editable.html
- Move Widget A (top left) to position of Widget B (top right)
- See the logs in console, should have updated data
- Resize or Remove card
- See the logs in console, should have updated data
=> 4798 - Fix wrong metadata for resize, reorder and remove card with homepage (4.37.x)

app/views/components/splitter/example-splitter-right-custom-width.html, docs/CHANGELOG.md, src/components/splitter/splitter.js
Fixed the splitter was dragging to wrong direction in RTL.
Closes #1813
- Use `Incognito Window`
- Navigate to: http://localhost:4000/components/splitter/example-index.html?locale=ar-SA
- Dragging the splitter, should go in correct side
=> 1813 - Fix splitter drags the wrong direction in rtl (4.37.x)

app/views/components/datagrid/test-custom-number-formats.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.editors.js, src/components/locale/locale.js
If a user sets the number format to something with different decimal character that the locale then editing will mess up the values in a decimal formatter.
Fixes #4806
- go to http://localhost:4000/components/datagrid/test-custom-number-formats.html
- edit the last column -> its using a comma as a decimal place which is different than the locale
- this should work
- click in a cell in the last column and then click out -> it should not change the value
=> 4806 - Fix editing in datagrid (4.37.x)

app/views/components/checkboxes/test-tables.html, docs/CHANGELOG.md, src/components/checkboxes/_checkboxes.scss
Fixed a regression when checkboxes are in certain layouts clicking will click the wrong one.
Fixes #4808
- go to http://localhost:4000/components/checkboxes/test-tables.html
- click first checkbox (should work and not click the last one)
- retest https://github.com/infor-design/enterprise/pull/3764 
- go to http://localhost:4000/components/checkboxes/example-index.html
- Open Chrome Dev Tools
- Inside the element inspector, locate the <form id="test-form"> element in the document.
- Set an element style on the span with "margin-top: 1000px" to get the checkboxes off the screen.
- Inside …
=> 4808 - Add fix for checkbox position (4.37.x)

docs/CHANGELOG.md, src/components/datagrid/_datagrid-uplift.scss, src/components/datagrid/_datagrid.scss
Fixes some alignment issues related to editing datagrid.
Fixes #4814
- go to vibrant mode
- switch to medium row height
- edit a field -> alignment should be ok
- click ... then add -> do this twice so one row has readonly column in the last column
- click validate all cells
- see that the icon doesnt have a shadow around it anymore
=> 4814 - Fix editor alignment issues

docs/CHANGELOG.md, src/components/dropdown/_dropdown-uplift.scss, src/components/dropdown/_dropdown.scss, src/components/lookup/_lookup.scss, src/components/timepicker/_timepicker.scss
Fixes the cursor overlapped the icon in right-aligned lookup and input fields when selecting the field. 
I also noticed issues in timepicker and dropdown field. This PR also covered the fixes for these issues.
- No spacing in between the text and icon in Timepicker field.
- UI Issues in dropdown once open. (Misalignment, dropdown list cutoff, etc.)
**Related GitHub/Jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/4718
- Go to http://localhost:4000/components/input/test-short-fields-right-aligned.html
Firstly, test the main issue (Lookup field)
- Select the …
=> 4718 - Fix the cursor overlapped the icon when selecting the field

docs/CHANGELOG.md, src/components/validation/validator.js, test/components/validation/validation.e2e-spec.js
The input validation messages did not have correct aria. Added `aria-invalid` and `aria-describedby`.
Fixes #4830
- go to http://localhost:4000/components/validation/example-index.html
- clear the email field and tab out
- the error message div will get an id
- the error input will get aria-invalid and aria-described by pointing at the div
- optionally try a screen reader
- try this on http://localhost:4000/components/validation/test-message-types.html as well
=> 4830 - Improve input error accessibility

docs/CHANGELOG.md, src/components/accordion/accordion.js
The the afterexpand and aftercollapse events fired before the states are set. Have a look @EdwardCoyle not sure why they might be like that?
Fixes #4838
- go to http://localhost:4000/components/accordion/example-accordion-panels.html
- paste the folling in the console
```
const $accordions = $('div.accordion ');
function listOpenHeaders() {
const states = $(this).children('.accordion-header').map((i, header) => {
return {
text: $(header).text().trim(),
expanded: $(this).data('accordion').isExpanded(header)
}
}).toArray();
console.log(states);
}
$accordions.on({
afterexpand: …
```
=> 4838 - Fix accordion events

docs/CHANGELOG.md, src/components/rating/_rating.scss
There was an extra call to a scss property (color: $rating-bg-color;) in _rating.scss line 79 that was overriding the color of the stars on there off state. Color on off state should be a dark gray / black color not orange. 
https://github.com/infor-design/enterprise/issues/4853
- go to http://localhost:4000/components/rating/example-index.html
- click the first star once to make it selected
- click the first star once to make it unselected - the border should not be the yellow color
=> 4853 - Fixed color of unclick rating star

app/views/components/tabs-module/example-category-searchfield-go-button-home.html, docs/CHANGELOG.md, src/components/searchfield/_searchfield.scss
Fixes missing clear button if the search field has categories in tabs module. 
Closes https://github.com/infor-design/enterprise/issues/4898
- Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
- Type anything in searchfield to show the `x` button
- It should show the clear button
- Click the `x` button
- It should clear the search field
- Test also on a classic theme and on mobile viewport/phone device
=> 4898 - Fix missing clear button

app/views/components/tooltip/example-icon-in-tooltip.html, docs/CHANGELOG.md, src/components/tooltip/tooltip.js, test/components/message/message.e2e-spec.js, test/components/tooltip/tooltip.e2e-spec.js
We found that the example showing a tooltip with an icon broke. This fixes the issue. It was caused by a change to the code that links content by ID.
Fixes #4827
- go to http://localhost:4000/components/tooltip/example-icon-in-tooltip.html
- hover the button -> should see a icon in the content
- go to http://localhost:4000/components/tooltip/test-tooltip-starts-with-pound-sign.html
- hover the button -> should see a # in the content
=> 4827 - Add fix for linking tooltips to id content

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, src/components/locale/locale.js, test/components/locale/locale.func-spec.js, test/components/message/message.e2e-spec.js
When using a flex toolbar for the datagrid toolbar it was throwing an error clicking toolbar buttons. This is the fix.
Fixes #4941
- go to http://localhost:4000/components/datagrid/example-custom-toolbar-flex.html
- click the toolbar button -> check the console should be no error
- try the functions in the .. menu that are not examples only and ensure they work (personalize, row heights ect)
=> 4941 - Add fix for flex datagrid toolbar error

docs/CHANGELOG.md, src/components/locale/cultures/en-US.js, src/components/validation/validation.js
In the validation.js there is a date object that contains a **check** method. This method does not take into account if the date picker has a time value or not. On line 127 I have added a conditional statement that checks if the **dtApi.settings.showTime** returns true, based on this condition the message inside of the **Locale.translate** will change based on the given Date picker.
https://github.com/infor-design/enterprise/issues/4888
Include:
- Navigate to the each of the date picker competent pages, one will have a date value and the other will have a date time value. 
**Date Value:** …
=> 4888 - Incorrect validation message for invalid value issue

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js
In the datagrid filter row code. The filter type popup did not close when focusing an input. This PR solves this issue
Fixes #4766
- go to http://localhost:4000/components/datagrid/example-compact-mode.html
- open any filter dropdown
- click to focus any field -> dropdown menu should shut
=> 4766 - Added fix to close the filter menu

docs/CHANGELOG.md, src/components/busyindicator/busyindicator.js
changed calculation of when to place the busy indicator over the content
closes #4953 
=> BusyIndicator: Is showing below the datagrid #4953

src/components/datagrid/datagrid.js, src/components/popupmenu/popupmenu.js
Added a new fix to #4766 because open fires on a delay of 300ms it was possible to make it fail if you clicked into the input quickly.
Fixes #4766
- go to http://localhost:4000/components/datagrid/example-compact-mode.html
- click on the filter button in the order date column
- VERY quickly click into the input -> menu should still close
=> 4766  - Add better fix to closing datagrid menu

docs/CHANGELOG.md, src/components/circlepager/circlepager.js, src/components/toast/toast.js
This PR fixes an issue with toasts not being announced by the screen readers when in a live region. To solve this i moved the region to the item itself using technique 4 of https://codepen.io/vloux/pen/exYQKR
In addition found that it is announced and removal too and fixed that
Fixes #4519 
- go to http://localhost:4000/components/toast/example-index.html
- enable Chrome Vox
- tab to the button - wait for it to read out entirely (since its set to polite it wont "talk over") other bits the screen reader is using
- hit enter -> should read the announcement in the toast
- wait for it to end …
=> 4519 - Fix toast live region announcement

app/views/components/popupmenu/test-multiple.html, docs/CHANGELOG.md, src/components/popupmenu/popupmenu.js, test/components/popupmenu/popupmenu.e2e-spec.js
This PR fixes an issue in Popupmenu instances that are shared between two or more trigger elements.  A regression recently occurred that caused Popupmenus to fully unwrap and revert their locations in the DOM, even while shared between different trigger elements.  This has been fixed.
Closes infor-design/enterprise-ng#987
Related to infor-design/enterprise-ng#1012
- Pull this branch, build, run
- Open http://localhost:4000/components/popupmenu/test-multiple.html?layout=nofrills
- Right click each input field and open their menus at least once
- Click "Destroy 1st Field"
- Right click the …
=> NG#987 - Fix shared Popupmenu lifecycle

docs/CHANGELOG.md, src/components/lookup/_lookup-new.scss
Added a scss/css statement to encapsulate the .the close.icon selectors to remove any extra top property to fix the alignment issue in the lookup component 
Fixed https://github.com/infor-design/enterprise/issues/4933
Include:
- Navigate to the lookup component page 
http://localhost:4000/components/lookup/example-index.html
- Click on the magnifying glass inside of in the input to open the modal
- Inside of the input type a search were keyword is described.
- After typing the search the X will appear on the right side of the input.  
- Click the tab key to change the focus to the button …
=> 4933 button single select

docs/CHANGELOG.md, src/components/breadcrumb/_breadcrumb.scss, src/components/editor/editor.js
Fixed an issue where separators that appear immediately after the header drop-downs don't appear.
#4751 
Go to http://localhost:4000/components/editor/example-customize-buttons.html and see that there is now a separator after the initial header dropdown.
Before:
After:
=> 4751 - Fix Editor separator

app/views/components/accordion/test-textarea-inside-of-accordion.html, docs/CHANGELOG.md, src/components/accordion/accordion.js
Fixes the textarea options being ignored after the page load inside of an accordion. Basically, the `scrollHeight` of the textarea was unable to find because of the accordion component. I found out that the accordion pane was hidden at first so technically, the textarea's `scrollHeight` wasn't there and will always be zero.
Fixed it via making the pane displayed so that the textarea gets its `scrollHeight` and gets calculated correctly.
Closes https://github.com/infor-design/enterprise/issues/4977
- Go to …
=> 4977 - Fix textarea options being ignored inside of accordion

docs/CHANGELOG.md, src/components/input/_input.scss
Fixes an issue where the disabled search bar for inputs don't appear disabled in Safari
#4611 
1. Open Safari
2. Go to http://localhost:4000/components/form/example-disabled-field.html
3. Select "Click to Disable"
3. Observe the greyed out search bar in the bottom of the screen
=> Changed the Safari disabled searchfield color

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
Data grid row indicators and row statuses overlap.
Closes #4918 
1. Visit http://localhost:4000/components/datagrid/test-dirty-indication.html
2. Open console and type:
```
const grid = $('#datagrid').data('datagrid');
grid.rowStatus(0, "error", "some test status");
grid.setDirtyIndicator(0, 0, true);
```
-> See that there is no dirty indicator, but row status exists
3. Select first row
-> See that there is no visual background artifacts on status cell.
=> 4918 - datagrid rowstatus and dirty indicator overlapping

docs/CHANGELOG.md, src/components/tabs/tabs.js
This PR fixes the inconsistency of element in tabs event. Changing from `li` to `a` element for consistency. It was reported in NG but the fix is in enterprise. 
Closes https://github.com/infor-design/enterprise/issues/4566
- Link the enterprise dist to the NG project
- Go to http://localhost:4200/ids-enterprise-ng-demo/tabs-dismissible (in NG)
- console.log the `tab` param in demo ts file `(tabs-dismissible.demo.ts)`
- Dismiss a tab
- The `a` element should be the target and not the `li`
~~- [ ] An e2e or …
=> 4566 - Fix inconsistency in tabs event

docs/CHANGELOG.md, src/components/locale/locale.js, src/components/timepicker/timepicker.js, test/components/locale/locale.func-spec.js
Fixed am/pm dot was causing issue to parseDate() method for greek language with Locale.
Closes #4793
- Navigate to:
- http://localhost:4000/components/timepicker/example-index.html?locale=el-GR
- http://localhost:4000/components/datepicker/example-timeformat.html?locale=el-GR
- Open picker
- Change around dropdown and pick that changed time
- After close the picker see, it should have the value you selected
- Open picker again, see now it should set to the value was picked
- Check for both `π.μ.` and `μ.μ.`
- Open developer tools and run
``` …
```
=> 4793 - Fixed am/pm dot issue for greek language with locale

app/views/components/datagrid/test-copy-paste-from-excel.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid-settings.func-spec.js
Fixed copy paste html to editable cell was cause to generate new cells with Datagrid.
Closes #4848
- Navigate to: http://localhost:4000/components/datagrid/example-editable.html
- Copy below html
```
<!DOCTYPE html>
<html>
<body>
<p>Click the button to alert the hostname of the current URL.</p>
<button onclick="myFunction()">Try it</button>
<script>
function myFunction() {
alert(location.hostname);
}
</script>
</body>
</html>
```
- Click on any cell in column `Activity*`
- This cell should be in edit mode now
- Paste here the copied html
- See …
=> 4848 - Fixed copy paste html to editable cell with datagrid

app/views/components/toast/test-bottom-right-draggable-position.html, docs/CHANGELOG.md, src/components/toast/_toast.scss
This PR fixes the issue of  where it's unable to drag down the toast message to its current position if the `position` setting is set to `bottom right`.
Closes https://github.com/infor-design/enterprise/issues/5015
- Go to http://localhost:4000/components/toast/test-bottom-right-draggable-position.html
- Click the button to trigger the toast message
- Drag toast message up then let go
- Grab again and try to drag down
- It should be able to move/drag it down
~~- [ ] An e2e or functional test for the bug or …
=> 5015 - Fix draggable toast message at bottom right position

docs/CHANGELOG.md, src/utils/environment.js, test/components/about/about.e2e-spec.js
The version was displaying as [Object][Object]. This is the fix
Fixes #5069
- go to http://localhost:4000/components/about/example-index.html
- open the about and scroll to the bottom
- The IDS Version should display as a number (fx 4.51.0-dev)
- Inspect the dom and look at the html element at the top. The data-sohoxi-version should also display as a number (fx 4.51.0-dev) 
=> 5069 - Fix bad version display

app/views/components/input/example-password.html, docs/CHANGELOG.md, src/components/form/_form-new.scss, src/components/form/_form.scss, src/components/form/form.js, test/components/input/input.e2e-spec.js
The password reveal feature is slightly off in uplift mode and a bigger problem because it used type="password" chrome would never let you ignore the autocomplete. To get around this i use the css way of setting the security feature on
NA
- go to http://localhost:4000/components/input/example-password.html?theme=new
- and http://localhost:4000/components/input/example-password.html?theme=classic
- in both cases the hide/show password feature should be aligned
- to test the auto complete go to https://stackblitz.com/edit/ids-hidereveal-xvhqlq?file=index.html
- type in the field and hit …
=> 5099 - Change Reveal to use css instead of password

src/components/searchfield/_searchfield-new.scss, src/components/searchfield/_searchfield.scss, src/components/searchfield/searchfield.js
Searchfield in certain cases was staggering when you resize the window. In addition, the X button was briefly hovering slightly higher when this event was triggered.
Closes #5076 
(the functionality fix does not have specific issue -- was just related)
- pull  `5074-toolbar-resize-menu-stagger-and-close-button-fix`  locally
- visit http://localhost:4000/components/toolbar/example-no-action-button.html
(1) trigger staggering issue
- make sure dev tools are closed
- resize window to width slightly above the minimum breakpoint in Chrome
- type any text into search field
- drag browser edge to …
=> 5074 - Toolbar Resize Menu Stagger & Close Button fix

docs/CHANGELOG.md, src/components/dropdown/dropdown.js, test/components/dropdown/dropdown-api.func-spec.js
Was pointed out by the TAAS team that the dropdown could use an aria-readonly attribute.
Fixes #5107
- go to http://localhost:4000/components/dropdown/example-readonly.html
- inspect the main .dropdown div on one of the readonly examples
- should have aria-readonly: "true"
=> 5107 - Add aria-readonly to dropdown

app/views/components/lookup/test-states.html, docs/CHANGELOG.md, src/components/lookup/lookup.js
Reverted some changes in https://github.com/infor-design/enterprise/commit/b90bb8e8406baac8c842932af039991cfcbb8339#diff-3f1934dc1d84a5236f9e5386034c6900619e2e2b910caef8c0d8153dc8c8ec26 as it caused readonly lookups to appear not readonly. It was perhaps not noticed that there is a non-editable lookup and a readonly lookup
Fixes #5149
- go to http://localhost:4000/components/lookup/test-states.html
- notice there is a readonly field with right styling again
- and now a non editable lookup example (you cant type)
- recheck http://localhost:4000/components/form/example-readonly-inputs.html …
=> 5149 - Add fix for non-editable lookup

app/views/components/tabs-module/example-sortable.html, docs/CHANGELOG.md, src/components/arrange/arrange.js, src/components/tabs-module/_tabs-module.scss, src/components/tabs/_tabs-new.scss, src/components/tabs/_tabs.scss, src/components/tabs/tabs.js, test/components/tabs/tabs-settings.func-spec.js
Added support to sortable drag and drop tabs. Non touch devices it's good with almost every type of tabs `Module`, `Vertical`, `Header`, `Scrollable` and `Regular`. For touch devices only support with `Module` and `Vertical` Tabs.
Closes #4520
- Navigate to: http://localhost:4000/components/tabs-module/example-sortable.html
- Rearrange tabs use drag and drop
- It should work fine
=> 4520 - Add sortable drag and drop to tabs

app/views/components/tabs-module/example-category-searchfield-go-button-home.html, docs/CHANGELOG.md, src/components/toolbar/toolbar.js, test/components/toolbar/toolbar.e2e-spec.js
This PR fixes a bug in the original Toolbar code (when coupled with Searchfields) that in some cases would force a single toolbar button to sit inside of the "More Actions" menu, when the button could instead just stand by itself.  The order of the overflow calculation has been adjusted to prevent this issue.
Closes #4857 
- Pull/build/run
- Open http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?layout=nofrills
- Open developer tools and toggle the device toolbar.  Set the mode to "responsive"
- Shrink the size of the window to be incredibly …
=> 4857 - Prevent single buttons from remaining in Toolbar overflow

docs/CHANGELOG.md, src/components/lookup/_lookup-new.scss, src/components/searchfield/_searchfield-new.scss, src/components/searchfield/_searchfield-toolbar.scss, src/components/searchfield/_searchfield.scss, src/components/searchfield/searchfield.js, src/components/tabs-module/_tabs-module.scss
There were cases of several alignment search issues, and we had not covered all permutations in Safari.
Particularly we are focused on addressing alignment on 5090 and 5158 in this branch, but there were a few other fixes in regards to this as well and in general Safari should be more similar to Chrome.
Note: this is not for off-by-one issues in specific theme/browser, as those can be very particular/nuanced to isolate. There may be other functional pre-existing issues in these icons but the main goal was to make sure the disappearing X and any pronounced/super easily distinguishable alignment issues as those can be particular obvious for end users.
To be able to keep the scope of this …
=> 5090/5158 - X Button Issues and Predictable Safari Behavior

app/views/components/tabs-module/test-lsf-addtabs-scenario-2.html, docs/CHANGELOG.md, src/components/tabs/tabs.js, test/components/tabs/tabs-module.e2e-spec.js
This PR makes a change to the `rename()` method on the Tabs API to also change the "More Tabs" menu items.  Previously, when updating a tab's name, the change would not immediately occur in the More Tabs menu if the menu was open.  This is no longer the case -- the menu item updates immediately.
Closes #5105
- Pull, run, build
- Open http://localhost:4000/components/tabs-module/test-lsf-addtabs-scenario-2
- Click the Add Tabs "+" button on the top-right of the viewport until the "More Tabs" menu appears, opens, and displays items.  As you click the "+" button, the new line added should …
=> 5105 - Improve Tabs `rename()` API to also change the "More Tabs" menu items.

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR fixes a bug where unselecting all items in an active page affects other selected items on other pages as well.
There's a line of code that resets the `this._selectedRows` after mapping it.
I also noticed that the selected counts don't reflect immediately. Fixed it too.
Closes https://github.com/infor-design/enterprise/issues/4503
- Go to http://localhost:4000/components/lookup/example-multiselect-paging-serverside
- Click the lookup button
- Tick top checkbox to Select all on first page
- Move to Page 2
- Tick top checkbox to Select all on …
=> 4503 - Fix unselected items on active page and display counts

app/views/components/tabs-module/test-lsf-addtabs-scenario-2.html, src/components/tabs/tabs.js
This is a followup fix for PR #5165 that addresses the following:
- lets the rename API fully work with/without a leading hash `#` symbol in the ID string.  The test page for the original issue has been modified to use the regular ID string without the hash.
- enables better detection of dismissible tabs when attempting to rename a tab in the "More" menu.  Previously the dismissible "X" button wasn't being passed to newly-renamed more menu items.
Supersedes #5165
Closes #5105
- Open http://localhost:4000/components/tabs-module/test-lsf-addtabs-scenario-2
- Click the Add …
=> 5105 - Enable tabs rename API to work with/without hash

app/views/components/radios/test-legend-tag-as-label.html, docs/CHANGELOG.md, src/components/radios/_radios.scss
This PR fixes the flickering of legend tag as a label inside of the fieldset.
This issue only exists on Chrome. Found out that legend tag should be relative to the fieldset as it's parent. Adding `position: relative` will fix the issue.
Closes https://github.com/infor-design/enterprise/issues/4901
- Go to http://localhost:4000/components/radios/test-legend-tag-as-label.html
- Select a radio input that is not in the last fieldset.
- Click radio label1 and radio label2 several times to test
- Legend tag (as label) should not flicker
**Included in …
=> 4901 - Fix flickering of legend tag

app/views/components/datagrid/test-cell-with-leading-space-dirty-indicator.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR fixes where the cell/s with a leading space triggers the dirty indicator even without changing the cell value on second blur/selection.
For conditional purpose, I use `trim` method to remove the white space. Trim method doesn't mutate the original state, safe to say that the display will look as it is.
Closes https://github.com/infor-design/enterprise/issues/4825
- Go to http://localhost:4000/components/datagrid/test-cell-with-leading-space-dirty-indicator.html
- Click the first row quantity ` 1` to trigger editing
- Click outside the …
=> 4825 - Fix cell value to not trigger dirty indicator with a leading space

app/views/components/datagrid/test-editable-dropdown-width.html, docs/CHANGELOG.md, src/components/dropdown/dropdown.js
Fixed dropdown focus and arrow key was moving across the grid cells, which let open multiple dropdowns with Datagrid.
Closes #4851
- Navigate to: http://localhost:4000/components/datagrid/test-editable-dropdown-width.html
- Click on any cell in 1st column `Action 0` (the dropdown will open)
- Press enter to close the dropdown, then press enter twice to open it up again
- Press right arrow key
- Focus should not move to next column, it should stay in opened dropdown input
=> 4851 - Fix dropdown focus and arrow keys with datagrid

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
Was trimming the backlog and stumbled over a small fix so including it. See steps
Fixes #4962
- go to http://localhost:4000/components/datagrid/test-expandable-row-multiselect.html
- select a row with the checkbox 
- click the +/i icon and watch the animation (see that its not cut)
- try with row unselected ect
=> 4962 - Fix animation issue

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
After the new implementation of shared popupmenu lifecycle, for some reason, the server-side paging in Datagrid does not work properly or it appears to affect the behavior of the Popupmenu instance.
This PR fixes reopening of filter options after doing sorting on server-side paging.
Closes https://github.com/infor-design/enterprise/issues/5073
- Go to http://localhost:4000/components/datagrid/test-filter-paging-server-side.html
- Click on any filter options dropdown (keep it open)
- Do a sort (on any of the columns)
- Close the filter options …
=> 5073 - Fix reopening of filter options after doing sorting on server-side paging

docs/CHANGELOG.md, src/components/locale/cultures/th-TH.js
The first day in the thai calendar should be monday according to the translation team so updated it. Monday === จ
Fixes #5199
- go to http://localhost:4000/components/datepicker/example-index.html?locale=th-TH
- open calendar
- first day of the week should be `จ`
=> 5199 - Change thai start day to monday

docs/CHANGELOG.md, src/components/mask/mask-api.js, src/components/mask/masks.js, test/components/mask/mask.e2e-spec.js
This PR fixes a bug in number masks where trying to replace the value of a number-masked input field with a valid decimal input would incorrectly cause the value to disappear.  The expected behavior, which is pre-filling a zero and accepting the decimal input, is now correctly implemented instead.
Closes #4974
- Open https://main-enterprise.demo.design.infor.com/components/mask/test-number-leading-zeroes.html
- In the first input field, type "123.123"
- Select all the text in the field (CMD/CTRL + A)
- Type the decimal point ".".  The formatted value should read "0.", and …
=> 4974 - Allow decimal input on replacement of number masked field value

app/views/components/dropdown/test-typeahead-automation-id.html, app/views/components/multiselect/test-typeahead-automation-id.html, docs/CHANGELOG.md, src/components/dropdown/dropdown.js, test/components/dropdown/dropdown.e2e-spec.js
This PR Fixes a bug where the prefix id were missing in dropdown list when searching with typeahead settings. This fixes both dropdown and multiselect.
Closes https://github.com/infor-design/enterprise/issues/5053
1.) Test in Dropdown component
- Go to http://localhost:4000/components/dropdown/test-typeahead-automation-id
- Open dropdown and search
- Then check the elements, it should have the prefix id for all the list items
2.) Test in Multiselect component
- Go to http://localhost:4000/components/multiselect/test-typeahead-automation-id
- Open …
=> 5053 - Fix missing prefix id attribute when searching with typeahead settings

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
This PR fixes the tag text in the datagrid column is not shown properly when hovering it on Alternate Row Shading.
Closes https://github.com/infor-design/enterprise/issues/5210
- Go to http://localhost:4000/components/datagrid/example-alternate-row-shading.html?theme=new&mode=contrast&colors=003876
- Hover a tag item in a row
- The text in the tag item should be seen properly
=> 5210 - Datagrid Alternate Row Shading Tag not shown properly on hover

docs/CHANGELOG.md, src/components/about/_about.scss
This PR fixes the overflowing scrollbar in About Modal on a smaller viewport.
Closes https://github.com/infor-design/enterprise/issues/5206
- Go to http://localhost:4000/?theme=classic&mode=contrast&colors=133c59
- Scroll to About Section
- Click the "Show About Screen"
- Minimize the screen to see in responsive view
=> 5206 - Fix for Spilling Scrollbar

docs/CHANGELOG.md, src/components/field-options/_field-options-new.scss, src/components/field-options/_field-options.scss
This PR fixes multiple UI misalignments
- Colorpicker field options
- Clearable input field options once close button is visible
- Clearable searchfield close button
Closes https://github.com/infor-design/enterprise/issues/5139
- Go to http://localhost:4000/components/field-options/example-no-init.html
- Find the `Color Picker`, then hover on it to show the field options button, then click to trigger
- Field options should align with colorpicker input
- Find `Clearable Input`, then do a search
- Field options should align with clearable input
- …
=> 5139 - Fix misalignment of (colorpicker, clearable input, clearable searchfield) on field options

app/views/components/dropdown/test-virtual-scroll-blank-option.html, docs/CHANGELOG.md, src/components/dropdown/dropdown.js, test/components/dropdown/dropdown.e2e-spec.js
This PR fixes a bug in Dropdown where it wasn't possible for the dropdown to highlight blank options in the list when the list opened. This is now possible.
Closes #5095
- Pull, build, run!
- Open http://localhost:4000/components/dropdown/test-blank-option.html
- Open the dropdown list.  The second option "Alabama" should be highlighted in blue.
- Press the up arrow key once to highlight the blank option.
- Press "Enter" on the keyboard.  The blank option should become selected and the list should close.
- Re-open the menu. The blank option should remain highlighted in blue.
- Test this on …
=> 5095 - Enable highlighting of blank dropdown options

src/components/datagrid/datagrid.js
This is a follow up fix for https://github.com/infor-design/enterprise/issues/5067 PR (https://github.com/infor-design/enterprise/pull/5203)
QA saw that the checkbox was being added to the next column when changing the row height.
Closes https://github.com/infor-design/enterprise/issues/5067
Related PR https://github.com/infor-design/enterprise/pull/5203
- Go to http://localhost:4000/components/datagrid/test-change-selectable-with-frozen-columns.html
- Toggle the `Switch Select Mode` to activate the `mixed`
- Then toggle again it to activate …
=> 5067 - Fix rendering of UI on different row height (Changing selectable mode from single to mixed, vice versa)

docs/CHANGELOG.md, src/components/calendar/calendar.js
This PR fixes a bug where if the calendar event is not set to whole day then the week view and day view will not properly render on UI.
Closes https://github.com/infor-design/enterprise/issues/5195
- Go to http://localhost:4000/components/calendar/example-index.html
- Create an event `Add Event API`
- Click to Edit the newly created event
- Unchecked `All day` option to edit the time
- Change the time to 7am - 12pm
- Switch to WeekView or DayView
- Should be working by now and properly rendered
~~- [ ] An e2e or …
=> Missing Event Highlight in Calendar Week View and Day View

src/components/field-options/_field-options-new.scss, src/components/field-options/_field-options.scss
This PR is a follow up fix on Safari, Firefox, and Edge issue in Field Options Colorpicker and clearable input.
Closes https://github.com/infor-design/enterprise/issues/5139, https://github.com/infor-design/enterprise/issues/5138
Related PR https://github.com/infor-design/enterprise/pull/5216
- Open on Safari, Firefox and Edge
- Go to http://localhost:4000/components/field-options/example-no-init.html
- Find the `Color Picker`, then hover on it to show the field options button, then click to trigger
- Field options should align with colorpicker …
=> 5139 - Additional fix for field options on Safari, Firefox, and Edge

docs/CHANGELOG.md, src/components/popupmenu/_popupmenu.scss
This PR fixes the overflowing of long tab label, making it ellipsis.
Closes https://github.com/infor-design/enterprise/issues/5187
- Go to http://localhost:4000/components/tabs-module/example-add-tab-button.html
- Add more tabs by clicking the `+` icon on the upper right section of the page
- Go to `New Tab Builder` Tab
- Uncheck the `Fill with the Garbage` and do a manual Tab Name. Make it a long text.
- Then click `Create New Tab`
-  Click `More` tab to trigger the dropdown
- The long tab label that you created should not be overflowed and it …
=> 5187 - Fix overflowing of tab label when it's too long

app/views/components/bar-grouped/test-execute-script.html, docs/CHANGELOG.md, src/components/bar/bar.js, src/components/line/line.js
Fixed onerror script was able to execute with bar chart.
Closes infor-design/enterprise-ng#1030
- Navigate to: http://localhost:4000/components/bar-grouped/test-execute-script.html
- See the yAxis first entry should be `<img src=x onerror=prompt(1)>`
- In dev tools change view to `Responsive` mode (around width: 445)
- See the yAxis first entry should updated to `<img src=x one...`
- It should not execute the `prompt(1)` script
Test NG
- Pull and build NG branch ([main](https://github.com/infor-design/enterprise-ng.git))
- …
=> 1030 - Fix execute script with bar chart

docs/CHANGELOG.md, src/components/field-options/_field-options-new.scss, src/components/field-options/_field-options.scss
This PR fixes (Compact and Non Compact Mode) on Edge
- Position of close icon in searchfield with field options
- Alignment of field options of all components in the test page
QA dm me about these issues.
Closes https://github.com/infor-design/enterprise/issues/5138
Related Issue https://github.com/infor-design/enterprise/issues/5139
Related PR https://github.com/infor-design/enterprise/pull/5230 https://github.com/infor-design/enterprise/pull/5216
- Pull this branch build, and run the app
1.)
- Go to http://localhost:4000/components/field-options/example-index on it on Edge Browser
- Go …
=> 5138 - Fix close icon position in searchfield with field options

docs/CHANGELOG.md, src/components/monthview/_monthview.scss
This PR fixes the selection range rendering in the mobile view.
Closes #5211 
- Pull this branch down, then build and run the app
- Go to http://localhost:4000/components/datepicker/example-range.html
- Open up mobile view
- Check if selection range rendering looks like the following: 
=> 5211 - Fixed Bug Issue in Mobile Selection Range Rendering

src/components/field-options/_field-options-new.scss, src/components/field-options/_field-options.scss
This is a follow up fix for field options issues on clearable input and colorpicker in Windows Firefox
Closes https://github.com/infor-design/enterprise/issues/5139
- Use a windows machine or a BrowserStack
- Go to https://github.com/infor-design/enterprise/issues/5139
- Go to colorpicker section, and click the field options
- Should align with the colorpicker field
- Go to Clearable Input section, click the field options
- Should align with the Clearable Input
- Test on both themes
~~- [ ] An e2e or functional …
=> 5139 - Fix field options of clearable input and colorpicker

docs/CHANGELOG.md, src/components/searchfield/_searchfield-new.scss
This PR fixes the searchfield icon that is not properly aligned in firefox view.
Closes https://github.com/infor-design/enterprise/issues/5290
- Go to http://localhost:4000/components/toolbar-flex/example-searchfield-collapsible.html
- Click on the searchfield button
=> 5290 - Fix Searchfield Icon is not properly aligned in Firefox

docs/CHANGELOG.md, src/utils/number.js
Due to a bug in the toFixed function, super larger negative numbers got an extra zero added when calling formatNumber. This issue fixes that.
Fixes #5308 
- go to http://localhost:4000/components/locale/test-format-big-negative.html
- paste in -1482409800.81
- click format
- check that the number is exact
- try more numbers as you want
- tests for this pass
- [ x] An e2e or functional test for the bug or feature.
=> 5308 - Add a fix for big negative numbers

app/views/components/personalize/example-classes.html, docs/CHANGELOG.md, src/components/personalize/personalize.styles.js
Fixed hyperlinks were not showing up for dark theme with Personalization.
Closes #5144
- Navigate to: http://localhost:4000/components/personalize/example-classes.html
- See the right side to hero section
- There are two hyperlinks `Incidents` and `More Info`
- Change theme the Mode to `Dark` and the Colors to `Amber`
- See those hyperlinks should show properly
=> 5144 - Fix hyperlinks for dark theme with personalization

docs/CHANGELOG.md, src/components/pager/pager.js
Fixed tooltip was not working after switch to 2nd page for disable/enable buttons with standalone Pager.
Closes infor-design/enterprise-ng#1047
- Pull this branch and build/run the demo app (This issue was only reproduce with NG)
- Pull and build NG branch ([main](https://github.com/infor-design/enterprise-ng.git))
- Navigate to http://localhost:4200/ids-enterprise-ng-demo/datagrid-standalone-pager
- After clicking next in pager button, the first and previous buttons are gets enable, and …
=> 1047 - Fix tooltip for 2nd page with standalone pager

app/views/components/dropdown/example-setvalue.html, docs/CHANGELOG.md
This PR fixes the dropdown value from updating whenever the "more actions" button is selected
Closes #5222 
- Pull this branch down, then build and run the app.
- Go to http://localhost:4000/components/dropdown/example-setvalue.html
- Click on the "more actions" button
- Check if the dropdown value is still Option One
=> 5222 - Fixed Bug Issue Updating Dropwndown Value When the "More Actions" Button Was Selected

app/views/components/datagrid/example-list-lookup.html, app/views/components/mask/test-decimal.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
Adds a follow up fix to the hover state on is-list style datagrids. Also small cleanup in the css linting.
And an example for future testing.
Fixes #5157 
- go to http://localhost:4000/components/datagrid/example-list-lookup
- hover the last column on the cell
- should show a lookup icon and not have a wierd grey background
=> 5157 - Add fix to hover states

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixed personalize column headers were not rendering properly with Datagrid.
Closes #5361
Navigate to:
- http://localhost:4000/components/datagrid/example-colspan.html or http://localhost:4000/components/datagrid/example-books.html
- Click on the actions button on the upper right of the datagrid
- Click on Personalize Columns then just click on/off the checkboxes
- See the column headers should render properly
=> 5361 - Fix personalize column headers with datagrid

app/views/components/actionsheet/example-breakpoints.html, app/views/components/actionsheet/example-callbacks.html, app/views/components/actionsheet/example-index.html, app/views/components/actionsheet/example-no-icons.html, app/views/components/actionsheet/test-many-actions.html, app/views/components/actionsheet/test-no-cancel.html, src/components/actionsheet/_actionsheet.scss, src/components/actionsheet/actionsheet.js, src/components/button/_button.scss, src/components/button/button.js, src/components/cards/_cards.scss
This PR addresses items brought to us during design Q/A (@kevinwhitedesign).  Also included in this PR:
- Fixed a minor lifecycle bug I discovered while testing that would accidentally render the menu markup multiple times if the trigger button was clicked multiple times.
- Moved some code around from the recent work on the new card design from #5295 to enable use of the "vertical" actions button everywhere. (@ericangeles) 
Closes #5256
Related to #5305 
- Pull, Run, Build!
- Open http://localhost:4000/components/actionsheet/example-index.
- Make sure the trigger button's icon is …
=> 5256 - Action Sheet design Q/A changes

app/views/components/lookup/test-multiselect-description-only.html, docs/CHANGELOG.md, src/components/lookup/lookup.js
Added api setting to allow duplicate selected value to input element with Lookup.
Fixes infor-design/enterprise-ng#986
- Navigate to: http://localhost:4000/components/lookup/test-multiselect-description-only.html
- Open lookup modal, on 1st page, select three rows value with `Soxtest` from 1st column and press `Apply`
- See lookup input value should be `Soxtest,Soxtest,Soxtest`
=> 986 - Add api setting to allow duplicates with lookup

app/views/components/lookup/test-multiselect-description-only.html, docs/CHANGELOG.md, src/components/lookup/lookup.js
Fixed selection for server side and paging was not working with Lookup.
Fixes infor-design/enterprise-ng#986
Navigate to: http://localhost:4000/components/lookup/test-multiselect-description-only.html
scenario 1
- Refresh the page
- Open lookup modal and select anything
- Click on `Show Selected` and see log in console should show results
scenario 2
- Refresh the page
- Open lookup modal and select single record on any page
- After modal close, click on `Show Selected` should show one record in array
- Open again modal and unselect the same …
=> 986 - Fix selection for server side and paging with lookup

app/views/components/datagrid/example-placeholder.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.formatters.js, src/components/datagrid/datagrid.js
Updated the Decimal formatter to prevent NaN from being displayed when the user doesn't enter a value and updated the placeholder example page dropdown so that the blank value was not a number which caused other options to display NaN when selected. Additionally added more type safety to coercion to prevent edge cases like the drop down from causing future issues
Closes ([#5395](https://github.com/infor-design/enterprise/issues/5395))
-Build and Run the application
- navigate to the datagrid placeholder example http://localhost:4000/components/datagrid/example-placeholder.html
To test the …
=> 5395 nan appears in datagrid fields for undefined selections

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js
Fixed row reorder handle align was not right for extra small and small height with Datagrid.
Fixes #5233
- Navigate to: http://localhost:4000/components/datagrid/example-grouping-row-reorder.html
- Try small and extra small datagrid height
- See reorder handle should not misalign
=> 5233 - Fix row reorder handle align for xs and sm height with datagrid

app/views/components/fileupload/test-required.html, docs/CHANGELOG.md, src/components/fileupload/fileupload.js
This PR adds the "required" asterisk to fileupload labels at page `components/fileupload/test-required`.
Closes #5285 .
- Visit http://localhost:4000/components/fileupload/test-required.html
- Ensure the required asterisk appears on required fields.
=> 5285 - Add Required Asterisk to Fileupload Label

src/components/cards/cards.js
This PR fixes issues when using angular's interpolation. Getting an error when you don't have anything set in template setting. This is a blocker in angular.
Closes #5253 
- To make sure it works, you just need to remove the template setting in either `example-single-select` or `example-multi-select` test page in Cards component.
- You should not get any error in the console regarding template utils.
=> 5253 - Fix template rendering in angular interpolation

app/views/components/lookup/test-multiselect-description-only.html, src/components/lookup/lookup.js
Fixed to update selection rows for server side and paging with Lookup.
Fixes infor-design/enterprise-ng#986
- Navigate to: http://localhost:4000/components/lookup/test-multiselect-description-only.html
- Open lookup modal and select some rows
- Click `Apply` to close lookup modal
- Click `Show Selected` to see current selected rows in console
- Click `Update Selected` will remove first entry from `selectedRows`
- See in lookup input field and in console by `Show Selected` button
=> 986 - Fix to update selected rows with lookup

docs/CHANGELOG.md, src/utils/excel.js
Fixed bug that prevented the order date column (not including the header) from being exported.
Closes #5332 
- Pull this branch down, then build and run the app
- Go to http://localhost:4000/components/datagrid/example-frozen-columns.html
- Click on the more button and then select Export to Excel
- Open the excel document and see if all column headers (specifically Order Date) match the following data below it 
=> 5332 - Fixed Additional Bug Preventing Order Date Column From Being Exported

app/views/components/donut/example-index.html, app/views/components/donut/test-automation-attributes.html, docs/CHANGELOG.md, src/components/charts/charts.js, src/components/pie/pie.js, test/components/area/area.e2e-spec.js, test/components/bar/bar-grouped.e2e-spec.js, test/components/bar/bar-stacked.e2e-spec.js, test/components/bubble/bubble.e2e-spec.js, test/components/column/column-grouped.e2e-spec.js, test/components/column/column-stacked.e2e-spec.js, test/components/dount/donut.e2e-spec.js, test/components/line/line.e2e-spec.js, test/components/pie/pie.e2e-spec.js, test/components/positive-negative/positive-negative.e2e-spec.js, test/components/radar/radar.e2e-spec.js, test/components/scatterplot/scatterplot.e2e-spec.js
This PR fixes a bug where automation ids is not properly rendered on legend, text and slices in charts.
Closes https://github.com/infor-design/enterprise/issues/5441
- Go to http://localhost:4000/components/donut/test-automation-attributes.html
- Open Inspect, check the legends, slices and text for automation ids.
=> 5441 - Fix automation ids not showing on legends, text and slices

app/views/components/message/example-index.html, app/views/components/message/test-long-title.html, docs/CHANGELOG.md, src/components/message/message.js
Message max-width is hard-coded in modal so when title size is long the message width does not increase to the size of it's container.
Fixes #5443 
- Pull branch, run app, visit http://localhost:4000/components/message/test-long-title.html
- Click the  button
- Notice the message text extends to the full width of it's container.
- Also notice that the modal now resizes toward it's max-width if the message text is long (this may be an undesired side-effect of simply removing the max-width from the message and perhaps we should consider placing a max-width setting option on modal and …
=> 5443: Message max-width is hardcoded in modal

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.formatters.js
Fixes a bug where the selection color would bleed through the clickable tags (easy one found in triage).
Fixes #5533
- go to http://localhost:4000/components/datagrid/test-alerts.html
- select a row
- look at the tags and make sure the selection color isnt bleeding through the icon
=> 5533 - Fix the selection color on clickable tags

src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.formatters.js
This PR fixes the alignment of multiple checkboxes and text on `medium`, `small`, and `extra-small` row heights.
Closes https://github.com/infor-design/enterprise-ng/issues/1075
- Go to http://localhost:4000/components/datagrid/test-multi-select-dropdown-selection.html?theme=new&mode=light&colors=2578a9
- Open the multiselect dropdown
- Checkboxes and text should not overlapping each other
- Test on different row heights
~~- [ ] A note to the change …
=> NG1075 - Add fix for other row heights

docs/CHANGELOG.md, src/components/datepicker/_datepicker-new.scss, src/components/lookup/_lookup-new.scss, src/components/lookup/_lookup.scss, src/components/spinbox/_spinbox.scss, src/components/timepicker/_timepicker.scss, src/components/validation/validator.js
This PR fixes a bug for both lookup and timepicker for short field and its icons not rendering properly.
It will also fix the box-shadow in spinbox-sm.
Closes https://github.com/infor-design/enterprise/issues/5541
Closes https://github.com/infor-design/enterprise/issues/5558
**#5541**
**1st Issue**
- Go to http://localhost:4000/components/validation/example-short-fields.html using all your browsers
- Click on spinbox-sm
**2nd Issue**
- Go to http://localhost:4000/components/validation/example-short-fields.html & …
=> 5541/5558 - Fix for Lookup/Timepicker icon not rendering properly in Safari. Fix for Spinbox box shadow not rendering properly

docs/CHANGELOG.md, scripts/build.js, src/components/charts/_charts-new.scss, src/components/charts/_charts.scss, src/components/charts/charts.js
This PR addresses a bug in the custom build system, where including the base charts API directly would throw a Node error due to an incorrectly-named import.  This issue has been fixed.
Closes #5463 
- Clean any previous builds: `npm run clean`
- Run a custom build with just charts:  `npm run build -- --components=charts`.  The build should complete without any errors
- Clean again: `npm run clean`
- Run a custom build that builds a pie chart:  `npm run build -- --components=charts,pie`
- Launch the demoapp: `npm run quickstart`
- Open …
=> 5463 - Fix error when running custom builds containing Charts

app/views/components/emptymessage/example-chart-with-auto-height.html, docs/CHANGELOG.md, src/components/homepage/_homepage.scss
This PR fixes the position of the empty message of the chart when using the auto height widget/card.
Closes https://github.com/infor-design/enterprise/issues/5527
- Go to http://localhost:4000/components/emptymessage/example-chart-with-auto-height.html
- Empty message should be visible and it should be inside of the card/widget container
- Test on classic mode too
=> 5527 - Fix empty message chart with an auto height widget/card

src/components/tree/tree.js
Fixed hide-focus was added to custom icons with Tree
N/A
Tests should pass
=> Fix hide focus for custom icons with tree

app/views/components/datagrid/test-count-in-select-all-current-page-setting.html, docs/CHANGELOG.md
This PR adds a test page for the `selectAllCurrentPage` setting with toolbar count to verify and test further. It has been an issue from `4.38.x` to `4.52.x` that the count doesn't update correctly/immediately when selecting/removing rows in the other pages.
Resolved in `4.53.x` EP.
Closes https://github.com/infor-design/enterprise/issues/4921
- Go to http://localhost:4000/components/datagrid/test-count-in-select-all-current-page-setting
- Select all items
- Count should be 10
- Move to page 2
- Count should still be 10
- Select 2 items
- Count …
=> 4921 - Add test page for selectAllCurrentPage with toolbar count

docs/CHANGELOG.md, src/utils/number.js, test/components/locale/locale.func-spec.js
Fixed an additional issue where formating / parsing larger numbers was failing.
Fixes #5605 
- go to http://localhost:4000/components//locale/test-format-big-negative.html
- paste in `12345678910` and hit the button -> should be `12345678910.00`
- patry more combinations with zero at the end with different widths
=> 5605 - Fix issue with fixTo

src/components/lookup/_lookup-new.scss, src/components/lookup/_lookup.scss, src/components/timepicker/_timepicker-new.scss, src/components/timepicker/_timepicker.scss
This PR fixes a bug for both lookup and timepicker for short field and its icons not rendering properly.
It will also fix the box-shadow in spinbox-sm. (Follow up fix)
Closes https://github.com/infor-design/enterprise/issues/5541
Closes https://github.com/infor-design/enterprise/issues/5558
**1st Issue**
- Go to http://localhost:4000/components/form/example-compact-mode.html using **Safari**
- Check on the timepicker and lookup buttons/icons
**2nd Issue**
- Go to http://localhost:4000/components/validation/example-short-fields.html using …
=> 5441 - Follow up fix for timepicker and lookup

app/views/components/locale/test-format-number-15-decimal.html, docs/CHANGELOG.md, src/components/locale/readme.md, src/utils/number.js, test/components/locale/locale.func-spec.js
Landmark uncovered using 15 decimal places rounded the number wrongly. Expand official support to 20 decimals as this is the max that can be done with toLocaleString
Fixes #5622
- go to http://localhost:4000/components/locale/test-format-number-15-decimal.html
- type 1234.45 and tab and should get a total of 15 decimals
- try 123 and other numbers
=> 5622 - Expand decimal support for format number

src/components/popupmenu/popupmenu.js
This PR fixes the unwanted navigation link `#` that occurs on the URL on NG wrapper. My guess is that when using the `ngIf` directive, before the e.preventDefault() being called, it does remove the element in the DOM. It doesn't recognize the `this.menu` element since it was being removed already. Changing it to `$(document)` instead.
Closes https://github.com/infor-design/enterprise/pull/5356
Dependency PR https://github.com/infor-design/enterprise-ng/pull/1128
- Pull this branch, and build
- The build here is the dependency (basically the fix on angular) but you can test it also here in …
=> NG#1046 - Fix unwanted navigation link on Angular

app/views/components/datagrid/test-tree-selected-rows-idx.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixed the selection idx was not updating after append/update data to child nodes for tree with Datagrid.
Closes #5631
- Navigate to: http://localhost:4000/components/datagrid/test-tree-selected-rows-idx.html
- Click on checkbox in 2nd row to select `z`
- Click on top button `Selected Row Idx`
- Alert should display `Selected Rows Index = 1`
- Click ok to close alert
- Click on `+` plus sign in 1st row
- It should insert child nodes to 1st row
- Now click again on top button `Selected Row Idx`
- This time alert should display `Selected Rows …
=> 5631 - Fix the selection idx for tree with Datagrid

app/views/components/contextualactionpanel/test-complex-toolbar-flex.html, docs/CHANGELOG.md, src/components/contextualactionpanel/contextualactionpanel.js, src/components/modal/modal.js, src/components/searchfield/searchfield.js, src/components/toolbar-flex/toolbar-flex.js, test/components/contextualactionpanel/contextualactionpanel-as-settings.func-spec.js, test/components/toolbar-flex/toolbar-flex-api.func-spec.js
This PR adds a couple enhancements to some Enterprise components for finer-grain control of Toolbar buttons via the ButtonSet API:
- Flex Toolbars with `.toolbar-section.buttonset` elements now automatically invoke `ButtonSet` components on these sections.
- Flex Toolbars now provide access to the ButtonSet APIs on these sections via the `ButtonsetAPIs` property (returns an array since there can potentially be multiple ButtonSet components depending on the Toolbar)
- Contextual Action Panel components configured to use Flex Toolbars provide a reference to their Toolbar's first-found ButtonSet API using the `buttonsetAPI` property (mimicking how the Modal provides access).
**Related …
=> NG#1101 - Add Buttonset API to Flex Toolbar `buttonset` areas and allow access from Contextual Action Panels

docs/CHANGELOG.md, src/components/cards/_cards.scss, src/core/_config.scss, src/themes/theme-classic-contrast.scss
Some reason fixes made th ecard buttons invisible on some themes.
Fixes #5647
- go to http://localhost:4000/components/cards/example-index
- change between the 2 versions and 3 themes
- the ... button should be visible
=> 5647 - Add fix to button contrast

app/views/components/splitter/example-searchfield.html, docs/CHANGELOG.md, src/components/popupmenu/popupmenu.js
Reverted the fix on https://github.com/infor-design/enterprise/pull/5617 as it caused #5649 and #5648
A new NG only fix was added to cover it https://github.com/infor-design/enterprise-ng/pull/1134
Added a new example for another bug for later
Fixes #5649
Fixes #5648
- Go to http://localhost:4000/components/calendar/example-index.html
- Click on Add/"+" on the upper right
- Click on Add Event(Modal)
-  click the the "All day" checkbox -> should work
- go to http://localhost:4000/components/checkboxes/example-checkbox-groups.html
- open the ... menu and pick a color
- click the checkboxes …
=> 5649/5648 - Revert fix for popupmenu that handled clicks different

package.json
This PR updates the chrome driver and chrome version to 94. And we noticed that it has an issue when running `e2e:ci`. It's not working for both local and on docker instances even after updating the stable version of chrome.
N/A
- Do `npm i`
- Build then run the app
- Run `npm run e2e:ci` it should work and should not encounter any error regarding ChromeDriver
- Optional: Test also on the docker instances
- Make sure you are on the latest and stable version of Chrome
~~- [ ] A …
=> MISC - update chrome driver that will fix e2e to work

app/views/components/line/test-all-data-points-are-zero-look.html, docs/CHANGELOG.md, src/components/line/line.js
This PR fixes the position of the line chart when all values are zeros. The line chart should not be centered and it should be close to the names.
Closes https://github.com/infor-design/enterprise/issues/5640
- Go to http://localhost:4000/components/line/test-all-data-points-are-zero-look.html
- The line chart should be close below with the names and not be centered
=> 5640 - Fix line position when all values are zero

docs/CHANGELOG.md, src/components/searchfield/searchfield.js, src/components/splitter/_splitter.scss
Searchfield will change width is splitter moves and the splitter container becomes smaller.
Closes #4696 
- Go to: http://localhost:4000/components/splitter/example-searchfield.html
- Move splitter
- Searchfield should change width when splitter gets closer to it
=> 4696 - Change width of searchfield when parent container becomes smaller

docs/CHANGELOG.md, scripts/data/expected-files.json, src/components/treemap/_treemap-new.scss, src/components/treemap/_treemap.scss, src/core/_controls-new.scss
This PR fixes Treemap's misaligned footer-text on the new theme.
Closes https://github.com/infor-design/enterprise/issues/5365
- Go to: http://localhost:4000/components/treemap/example-stats.html?theme=new
- Compare the above to: https://main-enterprise.demo.design.infor.com/components/treemap/example-stats.html?theme=new
- Go to: http://localhost:4000/components/treemap/example-stats.html?theme=classic
- Compare the above to: https://main-enterprise.demo.design.infor.com/components/treemap/example-stats.html?theme=classic …
=> 5365 - Treemap fix broken footer text on new theme

src/components/datepicker/_datepicker-new.scss, src/components/datepicker/_datepicker.scss
Follow up fix for datepicker trigger position in class theme.
Was not tested thoroughly. Just need to move the CSS rules to the `New` Mode file.
Closes https://github.com/infor-design/enterprise/issues/5751
- Open in Safari and go to http://localhost:4000/components/form/example-compact-mode.html
- Check the position of datepicker trigger button
- Toggle Compact Mode
- It should position correctly
- Test in Classic
- Check the position of datepicker trigger button
- Toggle Compact Mode
- It should position correctly …
=> 5751 - follow up fix for datepicker icon position in classic mode

docs/CHANGELOG.md, src/components/calendar/_calendar.scss
This PR will fix the header days where it should be seen when scrolled down in Calendar
Closes https://github.com/infor-design/enterprise/issues/5742
- Go to http://localhost:4000/components/calendar/example-index.html
- Make the browser tab shorter until you see a scroll bar
- Scroll it to see that you can see the days
=> 5742 - Calendar Fix Header Days

docs/CHANGELOG.md, src/components/tabs-vertical/_tabs-vertical.scss, src/components/tabs/tabs.js, test/components/tabs/tabs.puppeteer-spec.js
This PR fixes the regression bug where tabs are not working inside of modal. The issue has something to do with the vertical tabs in the modal. Reverting back to the original script and fixing the floating border indicator via CSS only.
Added unit testing for catching log errors in case we encounter the same issue.
Closes https://github.com/infor-design/enterprise/issues/5867
Related/Affected PR https://github.com/infor-design/enterprise/pull/5725
- Go to http://localhost:4000/components/tabs/test-modal-error.html
- Check the logs if there's an …
=> 5867 - Fix tabs not working in modal [regression bug 4.57.x]

app/views/components/column-grouped/example-axis-labels.html, docs/CHANGELOG.md, src/components/column/column.js
This PR adds the ability to attach axis labels `(top, right, bottom, left)` in the column-grouped chart. It also supports the RTL position.
You can set this using `axisLabels` setting e.g.
```javascript
axisLabels: {
left: 'Left axis label',
top: 'Top axis label',
right: 'Right axis label',
bottom: 'Bottom axis label'
}
```
Closes https://github.com/infor-design/enterprise/issues/5721
- Go to http://localhost:4000/components/column-grouped/example-axis-labels
- On the example page, you will see labels on different positions in the column-grouped …
=> 5721 - Ability to add axis labels in column-grouped chart

src/components/grid/readme.md
Per [this comment](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1637679462321?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1637678727395&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1637679462321) on Teams, fixing a bad link to the codebase in the site documentation
N/A
On the readme, make sure the link inside the Breakpoints section that points to the SASS file correctly points to a Github code page on specific lines: …
=> Fix link to code in documentation

app/views/components/popupmenu/test-contextmenu-with-datagrid.html, docs/CHANGELOG.md, src/components/popupmenu/popupmenu.js
This PR fixes breaking of the shared menu if a Datagrid is present. It looks like that the issue from datagrid paging (unable to reopen filter options after paging) has been resolved even without the condition for datagrid filter wrapper in popupmenu.
Closes https://github.com/infor-design/enterprise/issues/5818
- Go to http://localhost:4000/components/popupmenu/test-contextmenu-with-datagrid.html
- Click the `Destroy 1st Field` button
- Right click the remaining input field
- Popupmenu should be shown correctly
Another thing to test
- Go to …
=> 5818 - Fix breaking of shared menu if a datagrid present

test/components/accordion/accordion.puppeteer-spec.js
This PR fixes the issue in an accordion test that's failing in the build due to the selector that couldn't find. It just needs to add delay to be able to find the element since accordion has some sort of animation delay.
N/A
- Build should pass (hopefully)
- Test on local via `npm run e2e:puppeteer accordion`
- Should pass the ajax test
=> N/A - Fix unit testing test in accordion

app/views/components/button/example-badge.html, app/views/components/notification-badge/example-show-hide.html, app/views/includes/application-menu-icons.html, docs/CHANGELOG.md, src/components/accordion/accordion.js, src/components/button/button.js, src/components/notification-badge/notification-badge.js, test/components/notification-badge/notification-badge.puppeteer-spec.js
This PR will change the method names used in notification badge implementation.
Closes https://github.com/infor-design/enterprise-ng/issues/1169
- For Buttons: => http://localhost:4000/components/button/example-badge.html
- For Accordion Headers: => http://localhost:4000/components/applicationmenu/example-menu-notification.html
- For Enable/Disable: => http://localhost:4000/components/notification-badge/example-show-hide.html
=> 1169 - Notification Badge Method Name Change

docs/CHANGELOG.md, src/components/spinbox/_spinbox.scss, src/components/spinbox/spinbox.js
This PR removes the ripple effect in spinbox control when it's being disabled, also added a disabled property to it.
Closes https://github.com/infor-design/enterprise/issues/5719
- Go to http://localhost:4000/components/spinbox/example-range-limits.
- Click on - or + tabs to reach a minimum or maximum value.
- As we reach the min or max value, - or + sections are disabled.
- Clicking the disabled button should not show the ripple effect.
- Ripple effect will only show if the button is not disabled.
~~- [ ] An …
=> 5719 - Remove ripple effect in spinbox control when it's disabled

docs/CHANGELOG.md, src/components/listview/_listview-new.scss
This PR fixes the position of the alert icon in RTL.
Closes https://github.com/infor-design/enterprise/issues/5827
- Go to http://localhost:4000/components/listview/example-status.html?locale=he-IL
- Alert dot icon should be visible and it should be seen beside the alert text
- Test in classic mode
=> 5827 - Fix the alert icon position in RTL

app/views/components/datagrid/example-export-format.html
Changed how locale and datagrid is updated when another locale is selected in dropdown so it won't go to localhost.
Addresses comments in #5663 
- Go to: http://localhost:4000/components/datagrid/example-export-format.html
- Change locale in dropdown
- Page should not reload anymore, datagrid re-renders instead
=> 5663 - Updated example page

app/views/components/modal/test-modal-datagrid-escape-closing.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Modal will close when Escape key is pressed in datagrid.
Closes #5796 
- Go to: http://localhost:4000/components/modal/test-modal-datagrid-escape-closing.html
- Focus on filter row input fields
- Press Escape
- Modal should close
=> 5796 - Close modal if Escape key is pressed in datagrid

app/views/components/contextualactionpanel/test-undefined-button.html, docs/CHANGELOG.md, src/components/emptymessage/emptymessage.js, src/components/toolbar/toolbar.js
Due to faulty logic when the toolbar is initialized it is pulling in any buttons with `id="undefined"` when there is a more button with no `aria-controls` on it. This addresses this issue.
TO BE PATCHED in 4.58 once merged
Fixes https://github.com/infor-design/enterprise-ng/issues/1194
- go to http://localhost:4000/components/contextualactionpanel/test-undefined-button
- the page should work as normal - before the button would be moved into the toolbar menu automatically
=> 1194 - Fix a bug with undefined ids on buttons

app/views/components/timepicker/example-hour-range.html, docs/CHANGELOG.md, src/components/timepicker/timepicker.js, test/components/timepicker/timepicker-settings.func-spec.js, test/components/timepicker/timepicker.e2e-spec.js, test/components/timepicker/timepicker.puppeteer-spec.js
This PR will add a setting in timepicker to limit the hours that can be selected.
Closes https://github.com/infor-design/enterprise/issues/5880
- Go to http://localhost:4000/components/timepicker/example-hour-range.html
- Click the Timepicker in (12hr Format)
- Choose `PM` in `Day Period`
- Check the `Hours`. Can only see till `6PM`
- Click the Timepicker in (24hr Format)
- Check the `Hours`. Can only see till `14:00`
=> 5880 - Timepicker Feature Option Limit Hours

app/views/components/datagrid/test-dynamic-mask-with-filter.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
A column's maskOptions function was never called when the datagrid also has a filter row. This is a fix.
Fixes #5847
- go to http://localhost:4000/components/datagrid/test-dynamic-mask-with-filter.html
- edit in the quanity column
- the first 3 rows allow no decimals
- the last row does allow it
- also see the console to confirm the dynamic function is being called
=> 5847 - Fix an issue with maskOptions functions on grids with filtering

app/views/components/line/example-empty.html, docs/CHANGELOG.md, src/components/line/line.js
Added default values on line width and y-axis when data in dataset is blank to fix type error occurring when the data in dataset is an empty array.
Addresses this issue: https://github.com/infor-design/enterprise-ng/issues/1172
- Go to: http://localhost:4000/components/line/example-empty.html
- Check console, there should be no error 
=> 1172 NG - Added default values for when there is no data in dataset

docs/CHANGELOG.md, src/components/dropdown/dropdown.js, src/components/editor/editor.js, src/utils/environment.js
Because using the userAgent is deprecated the last few browser/os versions do not update this information. So the version can no longer be obtained. For this reason the version is removed from the OS field on the about dialog
Fixes #5813
Fixes #5803 
- pull/build
- go to http://localhost:4000/components/about/example-index.html
- look at the OS and platform for windows and mac there is no no version shown
=> 5813 - Remove the version from the OS on about

app/views/components/modal/example-hidden-field.html, app/views/components/modal/example-index.html, docs/CHANGELOG.md, src/components/modal/modal.js, test/components/modal/modal.puppeteer-spec.js
This PR will fix modal focus issues with inline display none.
Closes https://github.com/infor-design/enterprise/issues/5875 
- Go to http://localhost:4000/components/modal/example-hidden-field.html
- Click `Show Modal`
- Tab around the modal - should skip the hidden field
=> 5875 - Fix on Modal Focus with Hidden Display None

.stylelintrc, docs/CHANGELOG.md, src/components/hyperlinks/hyperlinks.jquery.js, src/components/list-detail/list-detail.jquery.js, src/components/stepchart/stepchart.jquery.js, src/components/stepchart/stepchart.js, src/components/toolbar-flex/toolbar-flex.item.jquery.js, src/components/toolbar-flex/toolbar-flex.jquery.js, src/components/week-view/week-view.js, test/components/datagrid/datagrid.puppeteer-spec.js
Some components with destroy in the jquery wrapper had memory leaks. Checked for them all and fixed.
Also added ignore to stylelint for some files and fixed a lint warning
Fixes #6020 
- go to http://localhost:4000/components/toolbar-flex/example-more-actions-predefined.html
- in the console type:
```
$('#flex-toolbar').data() 
// should return data
$('#flex-toolbar').data('toolbar-flex').destroy()
// no error
$('#flex-toolbar').data() 
// should be empty now
```
- test any other components similarly like this...
=> 6020 - Fix memory leaks on data removal

src/components/searchfield/_searchfield-new.scss
Follow up fix for close icon alignment in firefox.
Closes https://github.com/infor-design/enterprise/issues/5954
- Open Firefox browser and navigate to http://localhost:4000/components/datagrid/example-custom-toolbar.html
- Make the browser smaller or toggle the Responsive Design Mode (firefox)
- Click the search icon and type anything to show the close icon
- It should be vertically aligned
=> 5954 - Follow up fix for icon alignment in firefox

src/polyfills/jquery-passive-events.js
When longpressing inside a nested context menu container, there are errors related to passive events in the console.
https://github.com/infor-design/enterprise-ng/issues/1207
=> 1207 - General: Passive Events Errors in Console

app/views/components/contextualactionpanel/example-cap-tabs-vertical-scroll.html, docs/CHANGELOG.md, src/components/modal/modal.js, test/components/contextualactionpanel/contextualactionpanel.puppeteer-spec.js
This PR fixes a regression bug where the elements in Tabs (inside of Contextual Action Panel) were getting disabled. I noticed that this bug occurs if the `li` element doesn't have `is-selected` initially. It has something to do with the fix [here](https://github.com/infor-design/enterprise/issues/5875) related to a modal. Added a condition that will not affect those elements that haven't been visible prior to opening a modal.
The issue has been raised in the NG version.
Closes https://github.com/infor-design/enterprise-ng/issues/1210
1.) Original …
=> NG1210 - Fix elements getting disabled in Tabs CAP [regression bug]

src/components/datagrid/_datagrid-new.scss, src/components/datagrid/_datagrid.scss
Follow up fix for close icon position on mobile classic theme.
Closes #5947
- Open in BrowserStack or actual android device then in Firefox browser http://localhost:4000/components/datagrid/example-columnsizing.html?theme=classic&mode=light&colors=2578a9
- Open any dropdown element
- Close icon should be vertically aligned
- Test also in the New theme
=> 5947 - Follow up fix for close icon issue on mobile classic theme

app/views/components/homepage/example-calendars.html, docs/CHANGELOG.md, src/components/calendar/calendar.js
The calendar component did not work with more than one in the same page. Made this possible to satisfy a t2v use case.
Im not convinced the UI looks very good with it there as its too small but this is what they asked for.
Fixes #6042
- go to http://localhost:4000/components/homepage/example-monthviews.html
- see you can have one in each widget
- go to http://localhost:4000/components/homepage/example-calendars.html
- see you can have one in each 2 out of 3 widgets
- also test http://localhost:4000/components/calendar and http://localhost:4000/components/monthview for any issues
**Included …
=> 6042 - Fix calendar to allow more than one in a page

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR will fix a bug where leading spaces not triggering dirty indicator in editable data cell.
Closes https://github.com/infor-design/enterprise/issues/5927
- Go to http://localhost:4000/components/datagrid/test-cell-with-leading-space-dirty-indicator.html
- Click on add leading spaces to Compressor in the first cell under the Product Name column
- Tab out of the cell
=> 5927 - Datagrid Leading Spaces not triggering dirty indicator

src/components/toolbar-flex/readme.md
Adds a brief explanation of the selected event for flex toolbar (based on Ms Teams chat)
=> Chore: Add docs on toolbar selected event

app/views/components/datagrid/example-modal-datagrid-tabbing.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR will fix a bug in datagrid where filterable headers cannot be tab through in modal.
Closes https://github.com/infor-design/enterprise/issues/5735 
- Go to http://localhost:4000/components/datagrid/example-modal-datagrid-tabbing.html
- Click `Open Modal`
- Perform a shift-tab (or tab) until focus is on a field in the filter row
=> 5735 - datagrid modal unable to tab fields

app/views/components/datagrid/test-stretch-last-column.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
I tried to fix a lint error but fixed the chained assignment in the wrong order so the values were off.
fixes #6063
- go to http://localhost:4000/components/datagrid/test-stretch-last-column.html
- resize the last column to the right -> make sure you can still see it and scroll to it
- resize the next column to it to the left -> make sure you can still scroll right and see it 
See https://user-images.githubusercontent.com/76002134/151219770-0710ad8b-2655-4c9b-965b-49c97605b5fe.gif for clarification if needed
=> 6063 - Fix stretch column last

docs/CHANGELOG.md, src/components/editor/editor.js
Added check to see if list items are selected before clearing format.
Closes #5592 
- Go to: http://localhost:4000/components/editor/test-clear-formatting.html
- Make a bullet list and a numbered list below the existing text.
- Select "Embrace e-commerce action-items, reintermediate, ecologies"
- Click the Clear Formatting icon.
=> 5592 - Fix a bug which clears list format when it's not part of the selected text

docs/CHANGELOG.md, src/components/actionsheet/actionsheet.js
This is a follow-up fix in Angular wrapper (implementing Actionsheet in NG) where the `renderRootElems` method doesn't re-rendered when going to other action sheet test pages (due to SPA routing concept).
Closes & Relates https://github.com/infor-design/enterprise-ng/issues/1188
- Get the dist file of the app and go to the NG version
- Test the dist in this PR https://github.com/infor-design/enterprise-ng/pull/1219
- Follow the instructions in that PR and navigate to different action sheet test page
~~- [ ] An …
=> NG1188 - fix rendering of renderRootElems method in SPA

app/views/components/modal/test-toggle-disabled.html, package.json, src/components/modal/modal.js, test/components/modal/modal.e2e-spec.js
This PR is a followup to #6088 that does the following:
- Reduces use of `MutationObserver` so only one is used (scoped to the Modal and its focusable elements)
- Fixes a minor tabbing bug that was recently introduced where sometimes focus could be placed on elements outside the Modal
- Adds a test
- Closes #6086
- Related to #6088
- Open http://localhost:4000/components/modal/test-toggle-disabled.html
- Open the Modal and click the "test" button to display a previously-hidden input
- Use Shift + Tab to focus the input.  Focus should not escape the modal, should skip the …
=> 6086 - Improve change of tabindex when Modal subcomponents are displayed/hidden

docs/CHANGELOG.md, src/components/popupmenu/_popupmenu.scss
This is an issue with the popupmenu associated with tabs overflow.
Close icon should be properly aligned in the popupmenu.
#6083 
- Visit http://localhost:4000/components/tabs/example-enable-disable.html?theme=classic&mode=light&colors=2578a9
- Emulate a responsive environment
- Pull down dropdown (popupmenu) with tab overflow and notice "Dismissible" close icon is vertically centered and right aligned.
=> 6083 - Tabs: 'x' icon is not aligned in responsive view

docs/CHANGELOG.md, src/components/editor/editor.js
This PR will fix a bug in editor where CTRL-H (add hyperlink) breaks the interface.
Closes https://github.com/infor-design/enterprise/issues/6015
- Go to http://localhost:4000/components/editor/example-index.html
- Resize the browser window such that the add hyperlink option is not visible
- Press ctrl-H to open the add hyperlink modal
- Attempt to add the hyperlink (press 'insert' button)
=> 6015 - Fix for add hyperlink modal via CTRL-H 

app/views/components/modal/test-focusable-elements.html
Following up fix. QA identified the first field isnt disabled but the label was made disabled.
Fixes #6131
- go to http://localhost:4000/components/modal/test-focusable-elements.html
- the first field has no tabindex - it is not disabled so it shouldnt have a disabled label
=> 6131 - Fix wrong disabled

docs/CHANGELOG.md, src/components/tag/tag.js, test/components/tag/tag.func-spec.js
Adds `type="button"` to tag buttons.
Fixes #6149
- go to http://localhost:4000/components/tag/example-index.html
- inspect the dismissible tag -> make sure the button has `type="button"`
=> 6149 - Make tag buttons have a type

docs/CHANGELOG.md, src/components/tabs/tabs.js
Tabbing is focusing on a parent element without functionality.
Fixes #6110 
Visit [/tabs/example-index](http://localhost:4000/components/tabs/example-index.html) and tab to see the area mentioned in the issue is no longer focused.
=> 6110 - TabIndex on Tab List Container

docs/CHANGELOG.md, src/components/header/_header.scss
Searchfield should not be at full width if it's collapsible.
Addresses one of the issues mentioned here: https://github.com/infor-design/enterprise-ng/issues/1225
- Pull this branch and build
- In NG, pull this branch: https://github.com/infor-design/enterprise-ng/tree/1225-flextoolbar
- Use this IDS version and build NG
- Go to: http://localhost:4200/ids-enterprise-ng-demo/searchfield-header
- Searchfield should be collapsed 
=> NG1225 - Searchfield in header should not be full width if collapsible

docs/CHANGELOG.md, src/components/trackdirty/trackdirty.js
This PR will fix a bug where dirty tracker is not reset when using lots of new line in Edge.
Closes #6032 
- Go to http://localhost:4000/components/editor/test-dirty-tracking-reset.html
- Edit the text on the RTE and use multiple page breaks (return) as much as possible. (see screenshots)
- put the mouse cursor at the end of the first word of the first line and press enter
- put the mouse cursor at the end of the first word of the second line and press enter
- put the mouse cursor at the end of the first word of the third line and press enter
- …
=> 6032 - dirty indicator editor fix

app/views/components/datagrid/test-images-error.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
In some cases the event for image errors did not fire at the right time (like addRow). Moved the event handler
Fixes #5442 again 
- go to http://localhost:4000/components/datagrid/test-images-error.html
- press add row
- all image placeholders should still be working
=> 5442 - Fix image callback

docs/CHANGELOG.md, src/components/monthview/monthview.js
Current default is to use 1 letter to show day of the week, however, based on the IDS design pattern, looks like for calendar in page view, 3 letter should be the default. 
Fixes https://github.com/infor-design/enterprise/issues/6193
- compare http://localhost:4000/components/calendar/test-range-in-month.html  -> https://main-enterprise.demo.design.infor.com/calendar/test-range-in-month.html 
=> 6193 - Calendar: use abbreviated letter as default

docs/CHANGELOG.md, src/components/datagrid/_datagrid-new.scss, src/components/datagrid/_datagrid.scss
This PR addresses UI issues of the datepicker icon trigger and time value when it's in editing mode.
Closes https://github.com/infor-design/enterprise/issues/6198
1.) Datagrid with Datepicker
- Go to http://localhost:4000/components/datagrid/test-editable-datetime.html
- Click on any Date cells or datepicker icons
- No alignment issues should be found
- Test in Classic mode and in different browsers (Firefox, Edge, Safari)
2.) Datagrid with Timepicker
- Go to http://localhost:4000/components/datagrid/test-timepicker-24.html
- Click on any Date …
=> 6198 - Fix UI alignment issues in datagrid datepicker & timepicker when is-editing [regression bug]

docs/CHANGELOG.md, src/components/applicationmenu/_applicationmenu-new.scss
Removes a Safari-specific CSS rule to move down the button svg arrow.
Resolves #5722 
- Visit http://localhost:4000/components/applicationmenu/example-menubutton.html in Safari
- Ensure the arrow is aligned properly
=> 5722 - ApplicationMenu: Menu Button Arrow Misaligned in Safari

app/views/components/datagrid/test-count-in-select-all-current-page-setting.html, docs/CHANGELOG.md, src/components/pager/pager.js, test/components/datagrid/datagrid.e2e-spec.js
Updated check on hiding pager. If the pagesize selected is greater than the records and hide pager on one mode is set to true, hide only the pager and not the pagesize selector.
Closes #3706 
- Go to http://localhost:4000/components/datagrid/test-count-in-select-all-current-page-setting.html
- Select pagesize to 100
- Pagesize selector should still be visible
=> 3706 - Fix on pagesize selector being hidden

app/views/components/contextualactionpanel/example-markup.html, docs/CHANGELOG.md
Versions of the CAP markup are added to the DOM under the trigger button. These injections are not necessary to demonstrate that the example works (can take markup from the page and put it into the CAP). As this markup injection behavior is confusing, we are removing it.
Relates to #6065 
- Visit http://localhost:4000/components/contextualactionpanel/example-markup.html
- Notice no markup is added to the page after clicking open the CAP multiple times in any theme.
=> 6065 - CAP: Remove Markup Injection from Example

test/components/fileupload/fileupload-advanced.puppeteer-spec.js
closes #6279 
related to #5671 
3. run npm run e2e:puppeteer file upload-advance
Steps
Given user is on [https://main-enterprise.demo.design.infor.com//components/fileupload-advanced/example-failed.html](https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-failed.html)
When I Upload a file
Then it should be able to upload the file
When I click Set Failed button
Then it should stop the upload progress
And show error message in toast and in file container
=> 6279 - file-upload failed status puppeteer script 

app/views/components/modal/example-close-btn.html, docs/CHANGELOG.md, src/components/modal/modal.js
Change minimum width only if screen size is greater than 400.
Addresses issue in: https://github.com/infor-design/enterprise-ng/issues/1240
- Use any device with screen width more narrow than 400 pixels. Or Inspect element and switch to mobile
- Go to: http://localhost:4000/components/modal/example-close-btn.html
- Click Show Modal (Full)
- Content should fit in screen
=> NG1240 - Fix on too wide minimum width when close button is enabled

docs/CHANGELOG.md, src/components/swipe-action/_swipe-action.scss
The swipe action component was missing css to hide the scroll bar in FF. This fixes it
Fixes #6312 
- pull, build, run
- go to http://localhost:4000/components/swipe-action/example-index.html
- in Firefox and Chrome and compare
- Should be no visible scrollbar in firefox now
=> 6312 - Fix visible scroll bar in FF

docs/CHANGELOG.md, src/components/field-options/_field-options-new.scss, src/components/field-options/_field-options.scss
This PR will fix a bug on the Color Picker Field Options alignment when in compact mode in Safari 
Closes https://github.com/infor-design/enterprise/issues/6256
- Go to http://localhost:4000/components/field-options/example-index.html
- Click on compact mode
- Scroll down to color picker
- Click in field to show field options
=> 6256 - FieldOptions: compact misaligned in Safari

docs/CHANGELOG.md, src/components/searchfield/searchfield.js
Removed input value check so that value in safari will be cleared.
Closes #6185 
- In Safari, go to: http://localhost:4000/components/searchfield/example-index.html
- Type something in searchfield
- Click on clear button
- Searchfield should clear value
The input value check was for a bugfix on toolbarflex (#5792). It looks to be working now without the check, but please test it just in case:
- Go to: http://localhost:4000/components/toolbar-flex/example-index.html
- Add a text in the first searchfield
- Click outside searchfield
- Minimize screen …
=> 6185 - Fix on clear not working in Safari

src/components/tabs-module/_tabs-module.scss
Focus state is off on close "X" button in searchfield.
Relates to #6207 
- Visit http://localhost:4000/components/tabs-module/example-toolbar-with-spillover.html?theme=new&mode=light
- Focus X button after typing in searchfield and notice color and position.
=> 6207 Follow up - X Button Focus Fix

docs/CHANGELOG.md, src/components/listview/listview.js
This PR fixes the position of the flex toolbar when selecting items in the list view. It was an introduced bug from the PR https://github.com/infor-design/enterprise/pull/6309. Added additional conditions to isolate the fix in the contextual toolbar.
Closes https://github.com/infor-design/enterprise/issues/6346
- Go to http://localhost:4000/components/cards/example-group-action.html
- Select any on the list to show the counts
- The elements of the toolbar should not move anywhere
- Test also …
=> 6346 - Fix flex toolbar position when selecting items in the listview [regression bug]

src/components/datagrid/_datagrid.scss
This is a follow-up fix for the previous PR https://github.com/infor-design/enterprise/pull/6310. QA found a minor issue on extra small row height in firefox.
Closes https://github.com/infor-design/enterprise/issues/6233
- Go to http://localhost:4000/components/datagrid/example-list-lookup.html?theme=classic&mode=contrast&colors=133c59 open in firefox
- Change the row height to extra small
- Click on any `Product Id` cells
- There should be no cut off border on top of the cell when is-editing
~~- [ ] An e2e or …
=> 6233 - Follow up fix for datagrid border td when editing in firefox

app/views/components/tabs/example-dismissible-tabs.html, docs/CHANGELOG.md, src/components/tabs/tabs.js
This PR fixes the firing of the activated event on closing a tab.
Closes https://github.com/infor-design/enterprise/issues/1452
- Go to http://localhost:4000/components/tabs/example-dismissible-tabs.html
- Open the console in debugger tool
- Close any tab via clicking `x` icon
- Afer closing a tab, it should only fire the close event
=> 1452 - Fix activated event fires on closing a tab

src/components/field-filter/_field-filter.scss
This PR will fix a bug on field filter short that the text does not displayed in dropdown and the label/text appearing on the dropdown-wrapper when in classic mode in Firefox.
Closes https://github.com/infor-design/enterprise/issues/5126
1st Issue 
- Go to http://localhost:4000/components/field-filter/example-short.html
- Click on the dropdown and select an item
2nd Issue 
- Go to http://localhost:4000/components/field-filter/example-short.html?theme=classic&mode=light&colors=2578a9
- Click on the …
=> 5126 - Field Filter short: text is not displayed in dropdown

docs/CHANGELOG.md, src/components/charts/_charts.scss
This PR fixes the alignment of the legend and legend color with the highlight of the selected legend
Closes https://github.com/infor-design/enterprise/issues/6301
- Go to http://localhost:4000/components/donut/example-legend-bottom-single-widget.html
- Click a legend 
=> 6301 - Donut Chart: Legend selected highlight issue

docs/CHANGELOG.md, src/components/monthview/_monthview.scss
Shortened the width of the range block so that any consecutive dates clicked will be detected.
Closes #6272 
- Go to: http://localhost:4000/components/datepicker/example-range.html
- Select a range that does not exceed a whole week
- Reopen datepicker
- Select a range a day after the previous range
- Date should be selected
=> 6272 - Datepicker consecutive range date bugfix

app/views/components/datagrid/example-editable.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR adds a trimSpaces option for leading spaces upon blur. 
Closes https://github.com/infor-design/enterprise/issues/6244
- Go to http://localhost:4000/components/datagrid/example-editable.html
- Click on the "Assemble Paint" cell 
- Add leading Spaces 
- Click away from the cell
- Click on the "Assemble Paint" cell 
=> 6244- Datagrid: Leading spaces are visible upon blur 

app/views/components/locale/test-format-date.html, docs/CHANGELOG.md, src/components/locale/cultures/lv-LV.js, test/components/locale/locale.puppeteer-spec.js
This PR corrects the date format for the Latvian language.
Closes https://github.com/infor-design/enterprise/issues/6123
- Go to http://localhost:4000/components/locale/test-format-date.html
- Check the last input `lv-LV (dd.MM.yyyy.)`
- The value should be `05.12.2019.`
- It should have a dot at the end of the date
=> 6123 - Fix incorrect date format the for the Latvian language

src/components/monthview/_monthview.scss
Shorten width of range block on end date to be able to click on the next date.
Closes #6272 
- Go to: http://localhost:4000/components/datepicker/example-range.html
- Select a range that does not exceed a whole week
- Reopen datepicker
- Select a range a day after the previous range
- Date should be selected
=> 6272 - Shorten width of range block on end date

src/components/datagrid/_datagrid.scss
Follow-up fix for the close icon in Datagrid column dialog. I also adjusted the height to `18px`.
Closes #6375
- Go to http://localhost:4000/components/datagrid/example-index
- Click the `...` button and select `Personalize Columns`
- Type anything in the searchfield
- Close icon should show in a vertically aligned position
- Test in New and Classic
=> 6375 - Follow-up fix for close icon in datagrid column dialog

docs/CHANGELOG.md, src/components/toolbar-flex/toolbar-flex.item.js
This PR fixes the `addMenuElementLinks` function incorrectly executed when the menu item has multi-level submenus.
Closes https://github.com/infor-design/enterprise/issues/6120
- Go to http://localhost:4000/components/toolbar-flex/example-more-actions-predefined
- Need to open the js file of `toolbar-flex-item.js` and add this `console.log('item '+ i + ' : ' + elems[i].innerText + ' linked');` in line 821 after `item.elementLink = elems[i];`
- Build the app again and go to the page
- You should be able to see `item 3 : Menu Button Item #4 linked` …
=> 6120 - Fix addMenuElementLinks incorrectly executed when having multi-level submenus

src/components/toolbar-flex/toolbar-flex.item.jquery.js, src/components/toolbar-flex/toolbar-flex.jquery.js
Fix leak caused by this.element on toolbar-flex and toolbar-flex-item
=> fix: Set this.element  to undefined on jquery destroy

app/views/components/modal/test-async.html, docs/CHANGELOG.md, src/components/lookup/lookup.js
Added check to see if lookup input element is visible before opening lookup. If it's not visible, lookup should not show.
Closes #6218 
- Go to: http://localhost:4000/components/modal/test-async
- Click on Show Modal
- Click on lookup icon
- Lookup should show after around 2 seconds
- Close modal and click on Show Modal again
- Click on lookup icon and either press "Esc" or close the modal right after
- Modal should close, lookup should not show 
=> 6218 - Fixed bug where lookup still appears when modal closes

docs/CHANGELOG.md, src/components/searchfield/_searchfield-new.scss, src/components/searchfield/_searchfield-toolbar.scss
This PR fixes a bug where the search icon is misaligned in Firefox.
Closes https://github.com/infor-design/enterprise/issues/6405
- Go to http://localhost:4000/components/toolbar/example-index.html
- Click to edit searchfield 
=> 6405 - Toolbar: Search icon misaligned in Firefox

app/views/components/datagrid/test-toggle-editable.html, docs/CHANGELOG.md
This PR fixes a bug where the datepicker icon is not visible when the datagrid starts as non editable and toggled to editable and is visible when the datagrid starts as editable and toggled to non editable.
Closes https://github.com/infor-design/enterprise/issues/6289
Scenario 1 
- Go to http://localhost:4000/components/datagrid/test-toggle-editable.html
- Hover over the date cells 
- Click the edit button
- Hover over the date cells 
Scenario 2 
- Set editable: true on initialization in …
=> 6289 - Datagrid: Datepicker icon visibility when toggling datagrid editable setting

docs/CHANGELOG.md, src/components/week-view/week-view.js
This PR fixes the bug where the month-year label does not change which arrow is clicked. 
Closes https://github.com/infor-design/enterprise/issues/6415
- Go to http://localhost:4000/components/week-view/example-index.html
- Click on the left/right arrow button
=> 6415 - Weekview: Month-Year Label is not changing upon clicking the arrow

app/views/components/applicationmenu/test-app-menu.html, docs/CHANGELOG.md, src/components/modal/modal.js
App menus with resizable set to true will wrap page containers in a resizable container, changing the layering of popups (popups get nested deeper). Modals are not included in it. Added check in modal where if the resizable container exists, place the modal in the resizable container to bring back the original layering of modal and page containers.
Addresses issue in: https://github.com/infor-design/enterprise-ng/issues/1272
- Go to: http://localhost:4000/components/applicationmenu/test-app-menu.html
- Click on "Show Modal"
- Click on timepicker
- …
=> NG1272 - Fixed bug where popup goes behind modal when in application menu in resizable mode

src/components/searchfield/_searchfield-toolbar.scss
Relates to #5173 . Specifically resolves https://github.com/infor-design/enterprise/issues/5173#issuecomment-1134655374
Relates to #5178 . Specifically resolves https://github.com/infor-design/enterprise/issues/5178#issuecomment-1132580265
- Visit http://llocalhost:4000/components/tabs-module/example-category-searchfield-go-button.html
- Resize browser to 766 width, step increase to 769
- Ensure Close Button is always visible after typing text and Go Button is always visible.
- Visit http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html …
=> 5173v2 + 5178v2 - Tabs: Go Button Overlaps X Icon in Mobile View

src/components/button/_button-new.scss
Follow-up fix for https://github.com/infor-design/enterprise-ng/issues/1282. Typo on `teritary` should be `tertiary`.
Related PR https://github.com/infor-design/enterprise/pull/6492
Fixes https://github.com/infor-design/enterprise-ng/issues/1282
- Check the class name `tertiary` and not `teritary`
- In `_button-new.scss` Lines: 8, 46 and 60.
=> NG1282- Fix typo class name (tertiary)

docs/CHANGELOG.md, src/components/tabs/tabs.js
This PR will fix a bug where tab focus indicator is not aligned properly in RTL composite forms.
Closes https://github.com/infor-design/enterprise/issues/6464
- Go to http://localhost:4000/components/tabs/example-composite-form-on-side.html?locale=ar-sa
- Focus on the tabs
=> 6464 - Tabs Focus Indicator

docs/CHANGELOG.md, test/components/datepicker/datepicker.puppeteer-spec.js
closes https://github.com/infor-design/enterprise/issues/6421
related to https://github.com/infor-design/enterprise-ng/issues/1256
3. run npm run e2e:puppeteer Datepicker
Given I’m on[ 'http://localhost:4000/components/datepicker/test-input-datefield-clear.html'](http://localhost:4000/components/datepicker/test-input-datefield-clear.html)
When Select start and end date in range2 field (label is Date with Range (set via range))
And Press clear button.
Then range2 value should be cleared.
=> 6421 -  datepicker clear pptr test

docs/CHANGELOG.md, src/components/accordion/_accordion.scss
This PR fixes the bug where the bottom borders are missing in dark mode for the completely disabled accordion.
Closes https://github.com/infor-design/enterprise/issues/6406
- Go to http://localhost:4000/components/accordion/example-disabled.html?theme=new&mode=dark&colors=0066D4
=> 6406 - Accordion: bottom borders missing in dark mode

app/views/components/datepicker/test-datepicker-french.html, docs/CHANGELOG.md, src/components/datepicker/datepicker.js
This PR will fix a bug where the datepicker is displaying NaN when using french format. (This will also fix for Deutsch)
Closes https://github.com/infor-design/enterprise-ng/issues/1273
- Go to http://localhost:4000/components/datepicker/test-datepicker-french.html
- Open `Datepicker`
=> NG1273 - Fix for NaN in Datepicker French

app/views/components/donut/example-legend-bottom.html, docs/CHANGELOG.md, src/components/charts/charts.js
Chart will do bottom legend placement only when specified in settings.
Closes #6474 
- Go to: http://localhost:4000/components/donut/example-legend-bottom
- Legends should be in right placement
- Click Toggle Legend
- Legends should be in bottom placement
=> 6474 - Removed automatic legend bottom placement

docs/CHANGELOG.md, src/components/modal/_modal.scss, src/components/modal/modal.manager.js, test/components/message/message.puppeteer-spec.js, test/components/modal/modal.e2e-spec.js
Fixes a bug with the overlay in chrome. By using RGBA the issue goes away.
Fixes #6566 
- open http://localhost:4000/components/modal/example-index.html
- click the button. should not be too dark
- make sure this page still works http://localhost:4000/components/modal/test-overlay-opacity.html
- as does this one http://localhost:4000/components/message/test-overlay-opacity.html
=> 6566 - Fix modal overlay on chrome

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Changed the check on saving page number. If active page is greater than the current possible number of pages, change active page to maximum possible pages.
Closes #6475 
- Go to: http://localhost:4000/components/datagrid/test-dirty-indication-after-remove-row.html
- Go to page 2
- Click on Delete Row (One)
- Datagrid should still stay in page 2
=> 6475 - Fixed a bug where page changed to one on removing a row in datagrid

app/views/components/validation/test-manual-error-on-field.html, docs/CHANGELOG.md, src/components/validation/validator.js
When sing manual validation routines some of the events are not being removed properly when the validation is removed. This solves the issue while keeping previous fixes
Fixes #6547 
- pull and run the demo app
- go to http://localhost:4000/components/validation/test-manual-error-on-field.html
- click show message
- click in the field and verify the focus shows the error
- click hide error
- click in the field and verify the focus now longer shows the error (as it did before the fix)
=> 6547 - Fix validation issue

docs/CHANGELOG.md, src/components/toolbar-flex/toolbar-flex.jquery.js, src/components/toolbar-flex/toolbar-flex.js
The angular lifecycle is having some issues tearing down the flex toolbar when its in a Contextual Action Panel. This fixes the issue
Fixes https://github.com/infor-design/enterprise-ng/issues/1327
- pull this branch and then `npm run build`
- copy the dist folder to an https://github.com/infor-design/enterprise-ng folder (in node_modules/ids-enterprise/dist) and replace it (effectively getting this fix on an NG branch
- run the ng demo app and go to http://localhost:4200/ids-enterprise-ng-demo/contextual-action-panel
- Click "Panel with Searchfield in flex toolbar"
- Click X
- The overlay …
=> 1327 - Fix CAP teardown error

docs/CHANGELOG.md, src/components/charts/charts.js
This PR fixes the bug where the result logged in the console is not the same as the Soho Interfaces.
Closes https://github.com/infor-design/enterprise-ng/issues/1296
Case 1: 
- Go to http://localhost:4000/components/bar/test-selected?theme=uplift&variant=light
- Click on any bar 
- See the result that is logged in the console 
Case 2: 
- Go to http://localhost:4000/components/column-grouped/example-get-selected?theme=uplift&variant=light
- Click on any column 
- See the result that is logged in the console 
Case 3: 
- Go to …
=> 1296- Chart: Wrong interfaces of SohoChartSelectEvent

docs/CHANGELOG.md, src/components/applicationmenu/applicationmenu.js
The app menu had some events that attached to every input in the page. Also fixed an issue where if the accordion was missing then you would get a lot of errors in the app menu.
Fixes #6592 
1. Clone https://github.com/infor-design/enterprise-ng-quickstart
1. build this branch and copy it over
1. npm run start
1. go to http://localhost:4200/ and open app menu
1. type anything in the filter
1. should not see any errors
Also:
1. run this branch
2. test filtering still works http://localhost:4000/components/applicationmenu/example-filterable.html
3. test other examples on …
=> 6592 - Fix app menu eventing and default

package.json, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.puppeteer-spec.js
This PR is a follow-up fix for expanding the treegrid via keyboard and added e2e to capture the functionality.
Closes
- #6434 
Related PR
- https://github.com/infor-design/enterprise/pull/6578
- Go to http://localhost:4000/components/datagrid/test-tree-with-checkbox.html
- Focus on the cell with the expand button
- Hit space
- It should expand the row of treegrid
=> 6434 - Follow-up fix for expanding the treegrid via keyboard

docs/CHANGELOG.md, src/components/listview/listview.js, src/components/toolbar-flex/_toolbar-flex.scss
This PR changes the target to a contextual toolbar when adding selection text. 
Closes https://github.com/infor-design/enterprise/issues/6591
- Go to: http://localhost:4000/components/listview/test-multiselect-flex.html
- Select items
- Contextual toolbar should appear
=> 6591 - ListView: Any toolbar-flex gets a "selection title" if it wrapped under widget class with soho-listview as a sibling

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid-aria.func-spec.js, test/components/datagrid/datagrid.puppeteer-spec.js
This PR fixes redundant `aria-describedby` attribute at cells.
Closes
- #6530 
- Go to http://localhost:4000/components/datagrid/test-landmark.html
- Check the cells
- It should not have `aria-describedby` attribute
=> 6530 - Fix redundant aria-describedby attribute

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, src/components/dropdown/dropdown.js
This PR fixes the overflowing of the multiselect dropdown on the page and pushes the container near the screen's edge.
Closes
- #6580 
- Go to http://localhost:4000/components/datagrid/example-filter.html
- Shrink the screen width so that "Activity" or "Activity (Multi)" is near the right edge of the screen
- Click open the dropdown
- Dropdown should be placed inside of the datagrid container and the page should not add white space
- Test in RTL position too http://localhost:4000/components/datagrid/example-filter?theme=new&mode=light&colors=0066D4 …
=> 6580 - Fix overflowing of dropdown in datagrid when at edge of the screen

docs/CHANGELOG.md, src/components/tabs/_tabs.scss
Edited css of close icon in Firefox.
Closes #6610 
- In Firefox, go to: http://localhost:4000/components/tabs-header/example-add-tab-button.html
- Add Tab with + button
- New tab should have close icon
=> 6610 - Fix on close button not showing in Firefox

app/views/components/datagrid/test-tree-mixed.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR will fixed unselectRow on treegrid sending rowData incorrectly.
Closes https://github.com/infor-design/enterprise/issues/6548
- Go to http://localhost:4000/components/datagrid/test-tree-mixed.html
- Collapse the task label `Follow up action with Residential Baltimore`
- Select the row for the task labeled, `Follow up action with Residental Housing`
- Unselect the same row (the one with the task labeled, `Follow up action with Residental Housing`
- In the debugger console, notice that the rowData for the unselected row should be correct …
=> 6548 - treegrid unselectrow rowdata

app/views/components/datagrid/test-datagrid-grouping-tooltip.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR will fix incorrect rowData for grouping tooltip callback.
Closes https://github.com/infor-design/enterprise-ng/issues/1298
- Go to http://localhost:4000/components/datagrid/test-datagrid-grouping-tooltip.html
- `Hover` each of the rows to display the `tooltip`
- See the `rowData` correctly displaying in the `Console`
=> NG1298 - rowData for grouping tooltip callback

docs/CHANGELOG.md, src/components/searchfield/_searchfield-toolbar.scss
This PR fixes the styling of the toolbar searchfield category when active.
Closes
- https://github.com/infor-design/enterprise/issues/6618
- Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html
- Click on the searchfield
- Searchfield border should be visible and should look correct
- Select any value in the category button
- Text should be visible
=> 6618 - Fix border style of searchfield in category when active

docs/CHANGELOG.md, src/components/datepicker/datepicker.js
Added check to trigger change event when range datepicker is setting today for the second date.
Closes https://github.com/infor-design/enterprise-ng/issues/1334
- Go to: http://localhost:4000/components/datepicker/example-range.html
- Open any range datepicker
- Click "Today" link on the datepicker dialog
- Check browser console, change event is triggered (date should be printed in console)
- Click "Today" link again on the datepicker dialog
- Check browser console, change event should be triggered again
=> NG1334 - Fix on change event not triggered when set Today is called twice

app/views/components/datepicker/test-datepicker-today-increment-key.html, app/views/components/datepicker/test-increment-decrement-day.html, docs/CHANGELOG.md, src/components/datepicker/datepicker.js, test/components/datepicker/datepicker.e2e-spec.js
This PR will add a setting for to allow keyboard hotkeys for increment and decrement of days in datepicker.
Closes https://github.com/infor-design/enterprise/issues/6632
Closes https://github.com/infor-design/enterprise/issues/6653
- Go to http://localhost:4000/components/datepicker/test-datepicker-today-increment-key.html
- In the first date field, press `t` to enter todays date
- While in the date field, press the `+` key
- The date should be incremented
- While in the date field, press the `-` key
- The date should be decremented
**Included in …
=> 6632 - Datepicker Increment/Decrement Settings

app/views/components/datagrid/test-editable-alerts.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
This PR fixes the visibility of datagrid alert icon when the trigger cell is active and moving cell content when hovering over.
Closes
- #6663 
- Go to http://localhost:4000/components/datagrid/test-editable-alerts
- Check the `Action` Column
- Alert icon should be visible
- Hover on the cell
- It should not move when hovering over
- Test on different row heights
=> 6663 - Fix visiblity of datagrid alert icon in datagrid trigger cell

docs/CHANGELOG.md, src/components/datepicker/datepicker.js, test/components/datepicker/datepicker-events.func-spec.js
When the MonthView Calendar is opened from a Datepicker. The monthrendered event was not firing on the initial load. This is inconsistent behavior and causes hacks / work arounds.
https://github.com/infor-design/enterprise-ng/issues/1345
=> Datepicker - Trigger monthrendered

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
This PR fixes the trigger icon background color on hover when a row is activated.
Closes
- #6679 
- Go to http://localhost:4000/components/datagrid/test-landmark
- Activate a row by clicking a noneditable cell (click `Dakar XLT 2 `) it should highlight the row.
- Then hover over other cells that have an icon when hovering.
- The trigger icon background should be the same as the color of the row.
- Test in classic and in different modes
=> 6679 - Fix trigger icon background color on hover when row is activated

docs/CHANGELOG.md, src/components/tooltip/tooltip.js
This PR fixes the tooltip event handlers not cleaning up properly on the `hide` method.
Closes
- #6613 
- Go to http://localhost:4000/components/popover/test-popover-tooltip
- In `tooltip.js` add a `debugger` in line `1094` under `detachOpenEvents` method
- On the test page, click the button `Click to Show Popover`
- Then click the close icon on popover to go through the line of code
- Print the `self.uniqueId` in the console tab
- It should return a value `popover-1`
- Before this fix, the `self` object is the window object, not the tooltip so it …
=> 6613 - Fix tooltip event handlers not cleaning up properly on hide

app/views/components/editor/test-editor-no-ids.html, docs/CHANGELOG.md, src/components/editor/editor.js
This PR will fixed a bug where dark screen is rendered after inserting an image in editor.
Closes https://github.com/infor-design/enterprise-ng/issues/1323
- Go to http://localhost:4000/components/editor/test-editor-no-ids.html
- Click on the insert an image button from the toolbar of the soho editor
- Paste the following link https://helpx.adobe.com/content/dam/help/en/photoshop/using/convert-color-image-black-white/jcr_content/main-pars/before_and_after/image-before/Landscape-Color.jpg and click insert
=> NG1323 - Insert Image rendering dark screen

docs/CHANGELOG.md, src/components/popdown/popdown.js
The event "clickoutside" was not being triggered due to "#popdown-example-trigger" not existing in Angular, changed element to popdown element instead.
Addresses issue in https://github.com/infor-design/enterprise-ng/issues/1304
- Pull this branch, build the app
- Use this version for NG
- Pull NG branch: https://github.com/infor-design/enterprise-ng/pull/1351
- Build and run NG
- Go to: http://localhost:4200/ids-enterprise-ng-demo/popdown
- Click on My Cart
- Popdown should appear
- Click outside My Cart
- Popdown should close
=> NG1304. Fix "clickoutside" not triggering in NG popdown

docs/CHANGELOG.md, src/components/searchfield/_searchfield-new.scss, src/components/toolbar-flex/_toolbar-flex.scss
Fixes 6705. This has been fixed in 4.65.x. This change is also needed in 4.64.x
**Related github/jira issues (required)**:
https://github.com/infor-design/enterprise/issues/6705
https://github.com/infor-design/enterprise/commit/64161d0b4f4350a489c0814ce28d9a9090e44e8e
1. Checkout branch 6705-searchfield
2. Navigate to http://localhost:4000/components/toolbar-flex/test-gauntlet.html
3. Resize browser to smaller resolution.
4. Notice no scrollbar under search icon.
=> Fix for git issue #6705. Searchfield icon has overflow underneath when collapsed.

app/views/components/colors/example-index.html, docs/CHANGELOG.md, src/components/button/_button.scss, src/components/colors/_colors.scss, src/core/_config.scss, src/themes/theme-classic-dark.scss, src/themes/theme-new-dark.scss
Resolves #6711 - Added CSS classes for IDS Status Colors affecting color and border-color properties
Added '.status-XX-border' and '.status-XX-color' classes in the colors.scss that apply status colors to border-color and color properties respectively
Renamed 'status-XX-bg-color' variables in config.scss to a more general 'status-XX-color' name
Included proposed changes in CHANGELOG
These new classes allow developers to apply the IDS status colors to border color and color CSS properties (not just background colors)
Resolves #6711
Resolves / Enhances WFM-44554
Resolves / Enhances WFM-46441 …
=> 6711 - Added CSS classes for IDS Status Colors to target color and border-color properties

src/components/searchfield/_searchfield-toolbar.scss
This is a follow-up fix for the Searchfield toolbar getting shrunk when typing.
Closes
- #6618 
- Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html
- Type anything in the search field
- Input field should not be shrinking when typing
=> 6618 - Follow-up fixes for Searchfield getting shrink when typing

src/components/datagrid/datagrid.js
This is a follow-up fix where the header tooltip icon doesn't work when changing row heights.
Closes 
- #6490 
- Go to http://localhost:4000/components/datagrid/example-header-icon-with-tooltip.html
- Test first the header icon tooltip after the page load
- Hover on the info icon under `Product Name` column header
- It should show the tooltip content with a `Product Name` header
- Change row height to small
- Hover again on the info icon
- It should show the tooltip content with a `Product Name` header
~~- [ ] An …
=> 6490 - Fix header icon tooltip not working when changing row heights

app/views/components/applicationmenu/example-index.html, app/views/components/applicationmenu/example-performance.html, app/views/components/applicationmenu/test-app-menu.html, app/views/components/applicationmenu/test-container.html, app/views/components/applicationmenu/test-long-content-string.html, app/views/components/applicationmenu/test-manual-init.html, app/views/components/applicationmenu/test-performance.html, app/views/components/applicationmenu/test-six-levels-icons.html, app/views/components/applicationmenu/test-six-levels.html, app/views/components/applicationmenu/test-tooltips.html, app/views/includes/applicationmenu-from-comps.html, app/views/includes/applicationmenu-many-items.html, app/views/includes/applicationmenu-menubutton.html, app/views/includes/applicationmenu-openlarge.html, app/views/includes/applicationmenu-with-searchfield-custom.html, app/views/includes/applicationmenu-with-searchfield.html, app/views/includes/applicationmenu.html, docs/CHANGELOG.md, src/components/applicationmenu/readme.md
By Request this PR removes the infor logo from app-menu. But kept the ability as a feature if a logo such as a customer logo is wanted. Visual Tests may be needed
Fixes #6726
- go to http://localhost:4000/components/applicationmenu/example-index.html
- check for no logos other places in http://localhost:4000/components/applicationmenu
=> 6726 - Remove infor logo from app menu

docs/CHANGELOG.md, src/core/_config.scss, src/themes/theme-classic-contrast.scss, src/themes/theme-classic-dark.scss, src/themes/theme-new-contrast.scss, src/themes/theme-new-dark.scss, test/components/validation/validation.e2e-spec.js
https://github.com/infor-design/enterprise/issues/6446 Caused an issue where some info colors in dark mode reverted to the header color which was changed to slate.
Fixes #6763 
- go to http://localhost:4000/components/tag/example-index.html?theme=new&mode=dark&colors=0066D4 -> info tag should be azure again
- go to http://localhost:4000/components/badges/example-index.html?theme=new&mode=dark&colors=0066D4-> info tag should be azure again
- go to http://localhost:4000/components/icons/example-index.html?theme=new&mode=dark&colors=0066D4)
- select one svg element and add class `info` it …
=> 6763 - Fix info color after header changes

app/views/components/datagrid/test-tree-grouped-headers.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixes a big where the datagrid will error, when hovering cells, if tooltips and grouped rows are being used together.
Fixes #6753 
-  go to http://localhost:4000/components/datagrid/example-tooltips.html
- hover the cells and header in the first column
- check the console and should be no errors
- on the cells in the body, a tooltip will appear
=>  6753 - Add fixes for an error with grouped headers and tooltips

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.puppeteer-spec.js
Column width will only change if it's specified in column settings.
Closes #6725 
- Pull this branch and build
- Use this IDS version to build in IDS NG
- Build and run IDS NG
- Go to: http://localhost:4200/ids-enterprise-ng-demo/modal-dialog
- Click on "Dialog with DataGrid"
- Datagrid should be in default width and have no inline width style on the table element
Using the same IDS build, test the issue mentioned here: https://github.com/infor-design/enterprise-ng/pull/1361
=> 6725 - Change inline width only if column width is specified

.github/workflows/env-deploy.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

docs/CHANGELOG.md, src/components/editor/editor.js
This PR will fix a bug in editor where blockquote is not continued in the next line.
Closes https://github.com/infor-design/enterprise/issues/6794
- Go to http://localhost:4000/components/editor/example-index?theme=uplift&variant=light
- Enter Text
- Select the text
- Click `Block quote` format
- Unselect the text
- Press Enter
=> 6794 - editor block quote format

app/views/components/datagrid/test-landmark.html, docs/CHANGELOG.md, package-lock.json, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid-aria.func-spec.js, test/components/datagrid/datagrid.puppeteer-spec.js
This PR allows overriding the `aria-describedby` value in the cells by adding the `ariaDescribedBy` setting in the column.
Closes #6530 
- Go to http://localhost:4000/components/datagrid/test-landmark
- Inspect the cells in `Product Name` column `td` element
- The `aria-describedby` values of all cells should be `id-row-1-cell-1 `and incrementing +1 e.g., `id-row-2-cell-1`
- Check also the `Manufacturer` Column (the first one)
- It should also be the same as the `Product Name` column but the incrementing part is in the cell, eg., …
=> 6530 - add setting ariaDescribedBy in the column to override the aria-describedby value

docs/CHANGELOG.md, src/components/bar/bar.js
This PR will fix a bug in bar charts grouped, where arias are identical to each series.
Closes https://github.com/infor-design/enterprise/issues/6748
- Go to http://localhost:4000/components/bar-grouped/example-formatter.html
- Inspect element for each of the bars.
- See that they have identical aria labels.
=> 6748 - Bar Charts Identical Arias

app/views/components/textarea/test-toggle.html, docs/CHANGELOG.md, src/components/textarea/textarea.js
This PR will fix a bug in textarea where validation breaks after enabling/disabling.
Closes https://github.com/infor-design/enterprise/issues/6773
- Go to http://localhost:4000/components/textarea/test-toggle.html
- Focus the textarea and then click anywhere outside it to remove the focus. The validation error should now should up.
- Click the `Toggle` button and confirm the textarea is disabled.
- Click the `Toggle` button again to enable the textarea.
- Start typing in the textarea and notice that the validation is now okay. …
=> 6773 - fix for validation breaks after enabling disabling

app/views/components/editor/example-dirty-tracking.html, app/views/components/editor/test-dirty-tracking.html, docs/CHANGELOG.md, src/components/trackdirty/trackdirty.js
This PR will fix a bug in editor where breaking space doesn't render dirty indicator properly.
Closes https://github.com/infor-design/enterprise-ng/issues/1363
- Go to http://localhost:4000/components/editor/test-dirty-tracking.html
- Try to type a letter to the editor to make it dirty
- Delete the typed letter
=> NG1363 - rich text editor breaking space dirty indicator

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.puppeteer-spec.js
There are times that parseNumber is called multiple times, causing it to convert the value again. Added checks to avoid parseNumber being called again.
Closes https://github.com/infor-design/enterprise-ng/issues/1370
- Go to: http://localhost:4000/components/datagrid/example-editable.html?locale=de-DE
- On any Price cell, change to "1,5"
- Cell should be 1,500
- Click to edit, change nothing, and press Enter
- Cell should be 1,500
=> 1370 - Additional checks when updating cell so that numbers aren't converted twice

docs/CHANGELOG.md, src/components/lookup/lookup.js
Fixed the bug where a field stays disabled when the field is not a direct parent of the lookup. Took the same logic to find the parent field from the disable function to the enable function.
Fixes #6145
Wasn't sure how to create a functional test for the issue since each functional test uses the same lookup configuration but there are multiple scenarios.
=> 6145 lookup disablefix

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid.puppeteer-spec.js
This PR will fix a bug in datagrid where is empty and is not empty is not working properly.
Closes https://github.com/infor-design/enterprise/issues/5273
- Go to http://localhost:4000/components/datagrid/test-tree-filter.html
- On the `Description` Column, click `Is Empty` filter
=> 5273 - datagrid filter is empty not working

app/views/components/datagrid/example-editable.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Additional fixes on dirty indicator not updating correctly on drag columns.
Addresses comments in #6867 
- Edit a cell so that dirty indicator will pop up
- Select another column and drag it next to the dirty cell (do both left and right sides)
- Dirty indicator should still stay on the cell
Check this gif for a better reference: https://user-images.githubusercontent.com/76002134/193113958-67d4f1fd-824c-46d1-9168-02105c8b1ef0.gif
- Edit a cell do that dirty indicator will pop …
=> 6867 - Fix on dirty indicators not updating correctly

app/views/components/datagrid/example-editable.html, docs/CHANGELOG.md, src/components/datepicker/datepicker.js, src/utils/environment.js
Included the "+" and "-" key values in Firefox for increment/decrement keydown check in datepicker.
Closes #6877 
- In Firefox, go to:
- http://localhost:4000/components/datagrid/example-editable.html
- http://localhost:4000/components/datepicker/test-datepicker-today-increment-key.html
- Select a date cell to edit
- Press the "+" and "-" keys on the QWERTY keyboard to increment/decrement the date
=> 6877 - Added Firefox increment/decrement keys

src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js
This PR will fix a bug in datagrid where clear dirty cell does not work properly in frozen columns.
Closes https://github.com/infor-design/enterprise/issues/6952
- Go to http://localhost:4000/components/datagrid/test-addrow-with-frozen-columns.html
- Click `Add Row`
- Enter new values for each of the columns in the new row
- Notice the dirty indicator on each cell
- Click on `Save and New`
=> 6952 - datagrid dirty cell indicator frozen 4.68.x

docs/CHANGELOG.md, src/components/dropdown/dropdown.js
This PR will fix a bug in dropdown where there is a null in a list when changing language to chinese.
Closes https://github.com/infor-design/enterprise/issues/6916
- Go to http://localhost:4000/components/dropdown/example-index.html
- Download a Chinese Language Input in Mac or PC and use it as keyboard input.
- In the dropdown box type in the first letter of the item you're searching for and select it.
- Check the Console, there should be no error.
=> 6916 - dropdown cannot read property null

app/views/components/datepicker/test-mask-disable-update.html, docs/CHANGELOG.md, src/components/mask/mask-input.js, src/components/mask/masks.js
Updated regex expression for mask
Closes https://github.com/infor-design/enterprise-ng/issues/1380
- Go to: http://localhost:4000/components/datepicker/test-mask-disable-update.html
- Select dates in both datepickers
- Click outside
- Click Update Disable button
- Change the dates in the datepickers
- Click outside
=> NG1380. Fixed a bug in mask value in datepicker when update is called

app/views/components/applicationmenu/test-accordion-card.html, docs/CHANGELOG.md, src/components/accordion/accordion.js
Haven't been able to replicate it in IDS but have done it in Angular (stackblitz doesn't provide the correct example but based on what's in it, I'm assuming the bug was found in Angular). The card is in a resize container which does not get excluded in the click interceptor. Added resize container in the excluded list.
Note: Requires this for NG https://github.com/infor-design/enterprise-ng/pull/1406
Closes #6820 
- Pull this branch and build
- Go to: http://localhost:4000/components/applicationmenu/test-accordion-card.html
- Click on accordion to expand
- Card should not close
- Use this …
=> 6820 - Fixed a bug where expanded card closes in NG when opening accordion

src/components/counts/_counts.scss
This PR will fix a bug in counts where two rows of labels cause misalignment (in firefox).
Closes https://github.com/infor-design/enterprise/issues/6845
- Go to http://localhost:4000/components/counts/test-widget-long-title.html in Firefox
- See the two row label
=> 6845 - count widget misalignment

docs/CHANGELOG.md, src/components/calendar/_calendar-toolbar-new.scss, src/components/calendar/calendar-toolbar.js, src/components/datepicker/datepicker.js, src/components/monthview/monthview.js
Fixed a bug where disabled dates in Safari were not showing. Added disable state for Today if current date is disabled.
Closes #6920 
Test in Chrome, Edge, and Safari
- Click on a datepicker cell
- Monthview should show disabled dates
- Click on Today
- Today should be disabled
=> 6920 - Fixed a bug in datagrid where disabled dates were not showing in Safari

src/components/calendar/calendar-toolbar.js, src/components/monthview/monthview.js
Now monthview.js will call the destroy function from calendar-toolbar.js, the resize event handlers is destroyed in teardown() properly.
#7032 
Added a toggle button to simulate destroy and create the calendar:
initially 3 resize handler events
on destroy, the 2 resize handler events created by calendar-toobar.js is properly destroyed
creating calendar again, resize.length becomes 3 again
=> 7032 Fixed Calendar Toolbar Destroy

docs/CHANGELOG.md, src/components/modal/modal.js
This PR fixes a bug where custom modal script gets error after closing the modal in the second time.
Closes #7057
- Go to http://localhost:4000/components/lookup/test-custom-modal.html
- Click on Lookup icon
- Close modal by clicking Cancel or Apply
- Repeat steps 2 and 3
- Check the console tab in developer tools, it should have no error
=> 7057 - Fix script error after closing the lookup modal

app/views/components/checkboxes/test-checkboxes-with-form-responsive.html, docs/CHANGELOG.md, src/components/form/_form-new.scss, src/components/form/_form.scss, src/components/grid/_grid.scss, test/components/form/form.e2e-spec.js
This PR fixes a bug where checkbox labels not wrapping when using `form-responsive` class. I also fixed the dirty tracker position.
Closes https://github.com/infor-design/enterprise/issues/6826
- Go to http://localhost:4000/components/checkboxes/test-checkboxes-with-form-responsive.html
- Notice the checkbox labels should wrapping now
- Test the dirty tracking
- Dirty tracker should be positioned correctly
=> 6826 - Fix unwrapping checkbox label when using form-responsive class

src/components/form/_form-new.scss
This PR fixes dirty tracker position in Firefox.
Closes #6826
Related PR https://github.com/infor-design/enterprise/pull/7078
- Open http://localhost:4000/components/checkboxes/test-checkboxes-with-form-responsive.html in Firefox
- Click the Dirty Tracking checkbox
- Dirty tracker should positioned correctly
=> 6826 - Follow-up fix dirty tracker position in Firefox

docs/CHANGELOG.md, src/components/datagrid/_datagrid-new.scss
This PR fixes a bug where datepicker icon background color is incorrect upon hovering.
Closes #7053
- Go to http://localhost:4000/components/datagrid/example-custom-filter-conditions.html, http://localhost:4000/components/datagrid/example-custom-filter-conditions-and-defaults.html, http://localhost:4000/components/datagrid/example-compact-mode.html
- Hover on the datepicker trigger icon
- Background should be transparent
=> 7053 - Fix incorrect background color of datepicker trigger when hovering

docs/CHANGELOG.md, src/components/toolbar/_toolbar.scss
Contextual toolbar button hover background color is set to transparent.
Closes #7090 
- Go to: http://localhost:4000/components/listview/example-multiselect.html
- Select an item
- Hover on "Assign" button
- No light background should appear
- Check other themes as well
=> 7090 - Fix on contextual button hover color

app/views/components/donut/example-colors.html, docs/CHANGELOG.md, src/components/charts/charts.js
Added info and theme color options for chart
Closes #7084 
- Go to: http://localhost:4000/components/donut/example-alerts
- Info color and legend should be blue
- Go to: http://localhost:4000/components/donut/example-colors
- Check colors
=> 7084 - Added 'info' and theme color options in settings

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR solves the issue #7128 by using dataRowIdx for summary rows instead of actualIndex, which is null in that case.
Fixes #7128
See the steps in issue, you should not be able to reproduce the bug.
=> 7128: Use dataRowIdx also for summary rows.

docs/CHANGELOG.md, src/components/tabs/tabs.js
This PR will fix bug where tab list is not viewable dark mode classic view.
Closes https://github.com/infor-design/enterprise/issues/7097
- Go to http://localhost:4000/components/tabs/example-index?theme=classic&mode=dark&colors=2578a9l
- Try to select a tab. Tabs should be viewable when selected.
=> 7097 - Dark Mode Classic View Tabs

docs/CHANGELOG.md, package-lock.json, package.json
Design pushed new design system icons. Adding them...
Fixes #7142
- on the page new icons for the following should be there
```
up-down-chevron
approve-all
import-spreadsheet
microphone
```
=> 7142 - Add new icons from design

app/views/components/dropdown/example-ajax.html, app/views/components/multiselect/example-ajax.html, docs/CHANGELOG.md, src/components/dropdown/dropdown.js, test/components/dropdown/dropdown-api-func-test.js, test/components/multiselect/multiselect-api-func-test.js
This PR fixes disabled options not disabled when using ajax and not templateManaged by adding a check for disabled flags to `buildOption` function
Closes #7150 
- go to http://localhost:4000/components/dropdown/example-ajax.html and http://localhost:4000/components/multiselect/example-ajax.html
- open the dropdown
- see some options are disabled
=> 7150 - Dropdown/Multiselect disabled options

app/views/components/header/example-flex-toolbar.html, docs/CHANGELOG.md, src/components/personalize/personalize.styles.js, src/themes/theme-new-contrast.scss, src/themes/theme-new-light.scss
This PR fixes color of disabled button in alabaster and in personalize colors.
Closes #7166
- Go to 
- http://localhost:4000/components/header/example-flex-toolbar.html
- http://localhost:4000/components/header/example-flex-toolbar.html?colors=BB5500
- http://localhost:4000/components/header/example-disabled-buttons.html?colors=7928E1
- http://localhost:4000/components/header/example-disabled-buttons.html?colors=0066D4
- Disabled button should look disabled now
~~- [ ] An e2e or functional test for the bug or …
=> 7166 - Fix button disabled color in toolbar/toolbar flex [4.80.x]

src/components/personalize/personalize.styles.js
This is a follow-up fix for the incorrect button color in the personalization after it has been clicked.
Closes #7166
- Go to http://localhost:4000/components/header/example-flex-toolbar.html?colors=BB5500&theme=new&mode=light
- Click the non disabled button
- After clicking, hover out
- Font color should be white
- Test also in different colors
=> 7166 - Follow-up fix for button color after click

app/views/components/popupmenu/test-masthead.html, docs/CHANGELOG.md, src/components/masthead/_masthead-new.scss, src/components/masthead/_masthead.scss, src/components/popupmenu/popupmenu.js, src/components/searchfield/_searchfield-new.scss, src/components/searchfield/_searchfield-toolbar.scss
Removed containerClass undefined check
Closes #7005 
- Go to: http://localhost:4000/components/popupmenu/test-masthead
- Click on "No Class"
- Click on "Has Class"
- Both popups should use inverse colors
=> 7005 - Fix on inverse colors not showing in popupmenu in masthead

docs/CHANGELOG.md, package-lock.json, package.json, src/components/charts/charts.js, src/components/datagrid/datagrid.js, src/components/personalize/personalize.js, test/jest.config.cjs
This fixes bar chart issues due to canvas being nulled out for jest tests to pass. This is fallout from some d3 changes.
This was only an issue on main and does not require patches.
Fixes #7183 
Fixes #7181 
- go to http://localhost:4000/components/bar/example-long-text.html -> long test should all appear again
- go to http://localhost:4000/components/bar/example-axis-labels.html -> left axis label should appear again
=> 7183/ 7181 - Fix bar chart regressions

docs/CHANGELOG.md, src/components/bar/bar.js, test/components/bar/bar-puppeteer-test.js
When updating d3 from 5 to 7 i introduced a bug with single bar chart selection, noticed by QA. This is the fix
Fixes #7182
- pull and build and go to http://localhost:4000/components/bar/example-index.html
- click each bar starting with the first
- the bar you click should be selected not the middle one as before.
=> 7182 - Add fix for selection

docs/CHANGELOG.md, src/components/button/_button-new.scss, src/components/button/_button.scss
Design QA report a minor alignment issue in icon buttons.
Fixes #7201 
- go to http://localhost:4000/components/button/example-index.html
- inspect the two icons buttons
- make sure they are 34x34 and the icon looks centered
=> 7201 - Fix icon centering

docs/CHANGELOG.md, src/components/locale/locale.js, src/components/timepicker/timepicker.js, src/utils/date.js, test/components/timepicker/timepicker-puppeteer-test.js
This PR fixes field value when day period goes first in the time format by using locale format date to set value on the field
Closes #7116 
- go to http://localhost:4000/components/timepicker/example-index.html?locale=ko-KR
- select a time and press the `Set Time` button
- see the day period goes first in the field and there are no validation errors
- go to http://localhost:4000/components/timepicker/example-index.html?locale=zh-CN
- select a time and press the `Set Time` button
- see the day period goes first in the field and there are no validation errors
**Included in …
=> 7116 - Timepicker fix field value when day period goes first in the time format

docs/CHANGELOG.md, src/components/validation/validation.js, test/components/timepicker/timepicker-puppeteer-test.js
This PR fixes 24h validation in time validation by using `Locale.parseDate` with `strictTime` option
Closes #7188 
- go to http://localhost:4000/components/timepicker/example-index.html?locale=nl-NL
- in the input field enter the '1' character and press tab
- see a validation error appears
~- [] An e2e or functional test for the bug or feature.~
=> 7188 - Timepicker fix 24h validation

app/views/components/datagrid/test-rtl-swap.html, docs/CHANGELOG.md, src/components/locale/locale.js
Updated dir to ltr instead of removing dir attribute when changing locales to make Safari update alignments.
Closes https://github.com/infor-design/enterprise-ng/issues/1431
- Open Safari
- Go to: http://localhost:4000/components/datagrid/test-rtl-swap
- Click on Arabic button
- Check alignments. Click on editable fields and check alignments
- Click on English button
- Check alignments. Click on editable fields and check alignments
=> NG 1431 - Fixed bug in Safari where dynamically switching from RTL to LTR doesn't update all the alignments

src/components/locale/locale.js, src/components/timepicker/timepicker.js, test/components/locale/locale-func-test.js
This PR adds fix to parseDate function for `ah...` time formats and fixes extra value in hours dropdown for timepicker component
Fixes #7116 
- go to http://localhost:4000/components/timepicker/example-index.html?locale=zh-CH
- set a time
- see there is no validation error
- select an hour (11 or 12), select AM->PM or PM->AM, see the hours dropdown doesn't have any extra value in it, just a number
- set time and see there is no validation error
=> 7116 - Timepicker add fixes to parseDate function for ah time formats

app/views/components/datagrid/test-card-cell-is-list.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
When rows are very tall the hover color and selection color for mixed mode would blend incorrectly. This is a fix
Fixes #7232 
- go to http://localhost:4000/components/datagrid/test-card-cell-is-list.html
- hover the rows
- then click the row (not the checkbox) to activate
- should be no bleed through of either state
- test also http://localhost:4000/components/datagrid/test-tree-mixed.html
=> 7232 - Fix hover color in is list/mixed mode

docs/CHANGELOG.md, src/components/tabs/tabs.js
This pull request will fix the alignment of focus in RTL view.
Closes https://github.com/infor-design/enterprise/issues/6992
- Go to http://localhost:4000/components/tabs-header/example-index.html?locale=ar-SA
- Go to http://localhost:4000/components/compositeform/test-with-tab-headers-horizontal.html?locale=ar-SA
- Go to http://localhost:4000/components/header/example-tabs-alternate.html?locale=ar-SA
- Go to http://localhost:4000/components/header/example-tabs-alternate.html?theme=new&mode=contrast&colors=0066D4&locale=ar-SA
- Go to …
=> 6992 - Tabs Regression RTL

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR adds `off` for drag events what fixes dragging columns after a cancelled drop moves more than one column
Closes #7017 
- go to http://localhost:4000/components/datagrid/example-reorder.html
- grab a column and move it somewhere where reordering doesn't happen (same place where it was, between columns like in the issue  #7017  etc) so `dragstart` `drag` `dragend` events trigger but the datagrid doesn't rerender
- grab the column and move it so reordering does happen this time
- see the order of the columns is correct and `settingschanged` event triggers only once …
=> 7017 - Datagrid Fix dragging columns after a cancelled drop moves more than one column

src/components/personalize/personalize.js, src/components/personalize/personalize.styles.js
This PR fixes header secondary button hover state and a console error appearing when selecting a color
Fixes [#7204 ](https://github.com/infor-design/enterprise/issues/7204#issuecomment-1447643018)
- go to http://localhost:4000/components/personalize/example-header-buttons.html
- select new theme and some color
- hover over the secondary button, background color should be the same as the other buttons
- browser's console should not have any errors
=> 7204 - Personalize Fix header secondary button bg color on hover

app/views/components/applicationmenu/example-index.html, app/views/components/applicationmenu/example-performance.html, app/views/components/builder/example-builder-nosidebar.html, app/views/components/builder/example-builder-subtitle-test.html, app/views/components/builder/example-builder-wizard.html, app/views/components/builder/example-builder.html, app/views/components/button/example-badge.html, app/views/components/form-compact/example-list-detail.html, app/views/components/header/example-emphasize-id.html, app/views/components/header/example-emphasize-page-title.html, app/views/components/header/example-eyebrow.html, app/views/components/header/example-record-id.html, app/views/components/header/test-header-gauntlet.html, app/views/components/page-patterns/example-list-detail-search-paging.html, app/views/components/page-patterns/example-list-detail.html, app/views/components/page-patterns/test-landmark-requisitions-screen.html, app/views/components/toolbar-flex/test-gauntlet.html, app/views/components/toolbar-flex/test-toolbar-nav-badge.html, app/views/includes/header-appmenu-trigger.html, app/views/includes/header-svg-go-back-trigger.html, app/views/includes/header.html, docs/CHANGELOG.md, src/components/button/_button-new.scss, src/components/button/_button.scss, src/components/header/_header.scss, src/components/header/header.js
This PR changes the header from a pseudo-element to an actual svg icon. Adjusted the width, height, and position of the notification dots.
Closes #7163
1.) Application Menu
- Go to
- http://localhost:4000/components/applicationmenu/example-index
- http://localhost:4000/components/applicationmenu/example-performance
- Check the header/hamburger-menu
- It should use the actual svg icon
- The SVG icon should be `24x24`
2.) Builder
- Go to
- http://localhost:4000/components/builder/example-builder-nosidebar (Resize the page to show the arrow back …
=> 7163 - Change header pseudo element to actual svg icon

src/components/toolbar-flex/_toolbar-flex-searchfield.scss, src/core/_config.scss, src/themes/theme-classic-light.scss
This is a follow-up fix for color issues (texts and icons) in alabaster/default classic.
Closes #7136 
Related PR #7238 
- Go to http://localhost:4000/components/homepage/example-hero-widget.html?theme=classic&mode=light&colors=default
- Check all the texts and icons
- It should complement with the alabaster color (white)
=> 7136 - Follow-up fix in hero color issues in alabaster classic

src/components/spinbox/_spinbox-new.scss, src/components/spinbox/_spinbox.scss, src/themes/theme-classic-dark.scss
This PR addresses the spinbox UI issue on mobile iOS when using the classic theme. Additionally, I've noticed and fixed an issue with the trigger icon hover color in the classic dark theme, which was incorrect.
Closes https://github.com/infor-design/enterprise/issues/7149
Related PR https://github.com/infor-design/enterprise/pull/7248
- If you have browserstack, change the localhost to your connected IP address e.g., mine is http://10.88.66.132:4000/components/form/example-compact-mode.html?theme=classic&mode=light&colors=default
- Check the …
=> 7149 - Fix spinbox UI on the iOS mobile classic theme

docs/CHANGELOG.md, src/components/header/_header.scss, src/components/personalize/personalize.styles.js
Updated appmenu icon colors.
Closes #7303 
- Go to: 
- http://localhost:4000/components/applicationmenu/test-six-levels-icons.html
- http://localhost:4000/components/applicationmenu/example-index.html
- Appmenu hamburger should not have focus color if not focused
- Select a color theme
- Hover background should not be a tiny square
=> 7303 - Updated appmenu icon colors

app/views/components/datagrid/test-filtering-violations.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR improves the `disableClientFilter` to not re-render the grid when it is activated.
Closes #7282
- Go to http://localhost:4000/components/datagrid/test-filtering-violations
- Open the console tab in chrome developer tools
- Make sure to the `Custom Level` has `Verbose` checked. (Located in upper right section of Console Tab)
- Click on `Load Data` button
- Open multi-select drop down for `Activity` column in the filter row & select `Assemble Paint`
- Initiate filter request by pressing enter key from the `List Price` filter row cell
- It …
=> 7282 - Fix to not re-render the grid when disableClientFilter is set to true

app/views/components/lookup/example-index.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
escapeHtml is used for the dataset and replaces special characters, so a search value with a single quote and data value  with the same thing were not equal when checking for substring. Added escapeHtml on search value.
Closes #7165 
- Go to: http://localhost:4000/components/lookup/example-index.html
- Open Products lookup
- Type single quote on searchfield and enter
- Should show one result
=> 7165 - Fix in keyword search not filtering single quote

app/views/components/personalize/example-color-theme-api.html, app/views/components/personalize/example-form-landmark.html, docs/CHANGELOG.md, src/components/colors/_colors.scss, src/components/counts/_counts.scss, src/components/dropdown/_dropdown-new.scss, src/components/header/_header.scss, src/components/header/header.js, src/components/hyperlinks/_hyperlinks.scss, src/components/locale/cultures/en-US.js, src/components/personalize/_personalize.scss, src/components/personalize/personalize.js, src/components/personalize/personalize.styles.js, src/components/searchfield/_searchfield-toolbar.scss, src/components/tabs-header/_tabs-header.scss, src/components/tabs/_tabs.scss, src/components/theme/theme.js, src/components/toolbar-flex/_toolbar-flex-searchfield.scss, src/core/_config.scss, src/themes/theme-classic-contrast.scss, src/themes/theme-classic-dark.scss, src/themes/theme-new-contrast.scss, src/themes/theme-new-dark.scss, src/themes/theme-new-light.scss
This PR fixes the default color back to azure and add alabaster in personalization colors.
The focus areas of these changes, for now, are the header, masthead, and personalize components. I anticipate that some components will be affected by this revert, but we can fix those next time.
For patch `[4.80.x, 4.81.x]`
Closes #7320 
- Go to http://localhost:4000/components/header/example-index.html
- Default color should be azure
- Check the `Colors`
- Alabaster should be available
- Test all elements in different colors
- Test all example pages
- …
=> 7320 - Change default color back to azure 

docs/CHANGELOG.md, src/components/header/header.js
This PR fixes color changing doesn't add CSS class due to the selected color string contains special character in Safari
Closes #7338 
- go to http://localhost:4000/components/builder/example-builder-wizard.html?colors=default&theme=new&mode=light in **Safari**
- shrink the browser so `Sidebar Popup` is visible
- change color to alabaster and change it back to default
- see the `Sidebar Popup` is visible and has correct hover bg color
=> 7338 - Personalization Fix color changing doesn't add CSS class to the header in Safari

app/views/components/datagrid/test-paging-source-arguments.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
The issue occurs in `settings.source` function when re-assigning grid options - `pagingInfo` argument is empty, happens because we destroy pager when datagrid being updated. This PR changes it so the pager is being destroyed only if `paging` is not in updated options
Closes #6947 
- go to http://localhost:4000/components/datagrid/test-paging-source-arguments.html
- open browser's console and click `Apply` button
- see the paging info is not empty
- smoke test other paging related examples
- http://localhost:4000/components/datagrid/test-update-settings.html
- …
=> 6947 - Paging Fix source argument is empty when re-assigning grid options

docs/CHANGELOG.md, src/components/editor/_editor.scss
This PR fixes the issue with not readable links in editor by applying hyperlink styles to all links in the editor
Closes #7331
- go to http://localhost:4000/components/editor/example-customize-buttons.html?theme=new&mode=dark&colors=default
- see the link is readable and the color is consistent with other editor examples
- test modes
- test disabled, readonly, preview states
=> 7331 - Editor Fix links are not readable in dark mode

app/views/components/timeline/test-additional-height.html, docs/CHANGELOG.md, src/components/timeline/_timeline-new.scss, src/components/timeline/_timeline.scss
Style adjustments for timeline. Split the line into two, with one that starts in the second to the last node to use the height as reference for how long it should be.
Closes #7299 
- Go to: http://localhost:4000/components/timeline/test-additional-height.html
- Line should not exceend last node
=> 7299 - Fix exceeding line on adding additional elements in timeline content

docs/CHANGELOG.md, src/themes/theme-new-light.scss
This PR fixes the success state badge color in new light theme.
Closes #7353 
- Go to http://localhost:4000/components/badges/example-index.html
- Inspect the element of success badge color
- background color should be `#2AC371`
=> 7353 - Fix success badge color in new light theme

docs/CHANGELOG.md, src/components/cards/_cards.scss
This PR fixes extra scroll bar in cards with group action
Closes #7343 
- go to http://localhost:4000/components/cards/example-group-action.html
- see the only one scrollbar in the card content 
=> 7343 - Card Fix group-action unnecessary scroll bar

app/views/components/textarea/test-toggle-track-dirty.html, docs/CHANGELOG.md, src/components/textarea/textarea.js
This pull request fix track dirty when updated() method was triggered (EP).
Closes https://github.com/infor-design/enterprise-ng/issues/1429
- Go to http://localhost:4000/components/textarea/test-toggle-track-dirty.html
- Click on `Toggle Textarea Readonly`
- Enter some characters on the textarea
=> NG1429 - textarea toggle dirty

src/components/header/_header.scss
This pull request will fix the border in search field in the header in tabs module
Closes https://github.com/infor-design/enterprise/issues/7297
Closes https://github.com/infor-design/enterprise/issues/7304
- Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?theme=new&mode=light&colors=BB5500
- Check the searchfield component (it should be white)
- Hover the `Go` Button
- Switch on the Modes and Colors
=> 7297/7304 - Border on Search Field in Tabs Module Header (2)

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/themes/theme-new-light.scss
This PR fixes row background color of activated and non activated rows. Regressed on this issue https://github.com/infor-design/enterprise/issues/5913.
Closes https://github.com/infor-design/enterprise/issues/7369
Related PR https://github.com/infor-design/enterprise/pull/7341
1.)
- Go to http://localhost:4000/components/datagrid/example-editable.html
- Click any row
- Hover on other row that is not activated
- Hover background color should be different
2.)
- Go to http://localhost:4000/components/datagrid/test-selected-rows-addnew.html
- Click …
=> 7369 - Fix activated and non activated rows background color when hovering

app/views/components/datagrid/test-paging-source-arguments.html, src/components/datagrid/datagrid.js
The issue: if the datagrid initializes with `paging: false` and you trying to update it with data containing paging, not only the `source` arguments are empty but the pager appears broken. This PR fixes the issue.
Closes #6947
- go to http://localhost:4000/components/datagrid/test-paging-source-arguments.html
- click `Load Data With Paging`
- see the data with paging appears and pagination works
- see the paging argument in browser's console is not empty
~- [ ] A note to the change …
=> 6947 - Datagrid paging when updated (follow up)

docs/CHANGELOG.md, src/components/column/column.js
This PR fixes incorrect index after legend being clicked in single column chart
Closes #7199
- go to http://localhost:4000/components/column-stacked/example-singular-get-selected.html
- click on a legend item
- see the data bar is being highlighted according to the legend clicked
=> 7199 - Column Fix data chart and legend doesn't match up

docs/CHANGELOG.md, src/components/toolbar-flex/toolbar-flex.item.js
This pull request will fixredundant aria-disabled in toolbar when element is disabled.
Closes https://github.com/infor-design/enterprise/issues/6339
- Go to http://localhost:4000/components/toolbar-flex/example-index.html
- Highligh the `Gear` Icon which is disabled
- It should not have aria-disabled
=> 6339 - redundant aria disabled toolbar flex

src/components/applicationmenu/_applicationmenu-new.scss, src/components/personalize/personalize.styles.js
Additional updates for appmenu, removing color styles for appmenu icons (icons were not showing in alabaster)
Closes #7302 
Related to https://github.com/infor-design/enterprise/issues/7361
- Go to: http://localhost:4000/components/applicationmenu/test-all-chevrons.html?colors=ffffff
- Icons in appmenu should be visible
For NG:
- Use this version of IDS for IDS NG
- Go to: http://localhost:4200/ids-enterprise-ng-demo/personalize-color-api
- Check the appmenu is the same when switching to different themes and colors
=> 7302 - Removed color style for other appmenu icons

app/views/components/datagrid/test-tree-rowstatus.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Clear rowstatus for node if grid is tree.
Closes #6033 
- Go to: http://localhost:4000/components/datagrid/test-tree-rowstatus.html
- Click on Add Row Error
- Click on Remove Row Error
- Error statuses should be removed
=> 6033 - Clear rowstatus in tree node for clearRowError to work correctly

app/views/components/week-view/example-card.html, app/views/components/week-view/example-stacked.html, docs/CHANGELOG.md, src/components/datepicker/_datepicker.scss, src/components/datepicker/datepicker.js, src/components/monthview/_monthview.scss, src/components/week-view/_week-view.scss, src/components/week-view/week-view.js, src/utils/date.js, test/components/week-view/week-view-api-func-test.js
Added stacked view layout for weekview agenda variant.
Added settings for `stacked` and `showFooter`.
Added breakpoint listener to switch stacked view to one day view in phone-to-tablet widths.
Closes #7373 
1. Checkout branch, `npm install`, `npm run start`
2. Go to [stacked example](http://localhost:4000/components/week-view/example-stacked.html)
3. Check that design matches [figma](https://www.figma.com/file/BVwSQAZwE8m1swXPNw93kh/Calendar-Enhancement?type=design&node-id=0-1&t=N8POS7ZictwKHLOr-0)
4. Check that vertical scrolling works and that header/footer remain sticky
5. Check that …
=> 7373 - Weekview agenda variant

src/components/popupmenu/_popupmenu.scss
Noticed a bug in data grid menu and fixed it. Needs to be merged into 4.83.0 as well.
Fixes https://github.com/infor-design/enterprise/issues/7408
Fixes https://github.com/infor-design/enterprise/issues/7517
- open menus and submenus in http://localhost:4000/components/button/example-menubutton-submenu-icons.html
- check icons are not overlapped
- open filter menus http://localhost:4000/components/datagrid/example-filter.html
- check icons are not overlaped
=> Fix: Add regression fix for icons in menus

app/views/components/bar/example-with-zero-value.html, docs/CHANGELOG.md, src/components/bar/_bar.scss, src/components/bar/bar.js
This PR introduces a new setting called `defaultTickCount` that automatically adds ticks when there are no dataset values. 
Additionally, it includes a fix for the issue where the tick text was not being displayed when adjusting the bar height to accommodate the legend inside the card.
Closes https://github.com/infor-design/enterprise-ng/issues/1463
- Go to http://localhost:4000/components/bar/example-with-zero-value or https://1463-bar-chart-zero-bar-enterprise.demo.design.infor.com/components/bar/example-with-zero-value
- It should show `5` …
=> NG#1463 - add defaultTickCount setting to automatically add ticks when there are no dataset values

docs/CHANGELOG.md, src/components/listview/_listview.scss, src/components/pager/_pager-new.scss, src/components/searchfield/_searchfield-toolbar-new.scss
Quick fix for a few alignment issues that regressed.
Fixes #7527 
- try light classic and light new for all these
- go to http://localhost:4000/components/datagrid/example-paging.html?theme=new&mode=light&colors=default and the pager should look ok 
- http://localhost:4000/components/listview/example-paging.html?theme=new&mode=light&colors=default - the pager should look ok 
- http://localhost:4000/components/header/example-non-collapsible-searchfield.html?theme=new&mode=light&colors=default the x in the search should be aligned
- …
=> Fix: Fix icon and alignment

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, src/components/lookup/readme.md
Fixes the enter key behavior on android/ios devices for datagrid.
Fixes [#1489](https://github.com/infor-design/enterprise-ng/issues/1489)
- open http://localhost:4000/components/datagrid/example-filter.html on an android device like pixel4
- test chrome and FF
- also try an IOS device
- in the header click into it and type a few characters
- hit the enter key on the virtual keyboard
- should filter not move to next field like before
(key on bottom right)
This may be hard to test on browser stack can use link: 
=> 1489 - Android enterkeyhint

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js
showColumn was inserting another column in the datagrid for the given column, under the assumption that it's a hidden checkbox column. Added an additional check when assigning headerNodeCheckbox so that the Activity header in the example won't be inserted on the first column.
Closes #7428 
Closes #7541
- Go to: http://localhost:4000/components/datagrid/example-frozen-columns.html
- Click on Personalize Columns
- Deselect and select Activity so that the column will disappear and appear
- Columns should render correctly (Activity should not be pushed …
=> 7428 - Fix on showColumn not working properly with frozen columns

src/components/tabs/tabs.js
Supplemental fix for #7421 based on feedback. Will patch to 4.83
Addition to https://github.com/infor-design/enterprise/issues/7421
- build this branch and copy it to the NG project
- run http://localhost:4200/ids-enterprise-ng-demo/tabs-module
- click x on the first tab
- check console and should not be any error
=> 7421 - Fix tab overflow error

docs/CHANGELOG.md, src/components/textarea/textarea.js
This PR fixes the issue where the textarea was throwing an error when the `trackdirty` component is being updated. It adds more type-checking to ensure that it belongs to a specific constructor function before updating it.
Closes #7536 
N/A
=> 7536 - Fix textarea throwing error

docs/CHANGELOG.md, src/components/listview/_listview-new.scss, src/components/modal/_modal-new.scss, src/components/modal/_modal.scss, src/components/toolbar/_toolbar-new.scss, src/core/_config.scss
Fixes some reported regressions
Fixes https://github.com/infor-design/enterprise/issues/7545
Fixes https://github.com/infor-design/enterprise/issues/7544
Fixes https://github.com/infor-design/enterprise/issues/7545
- go to http://localhost:4000/components/listview/example-multiselect.html
- notice top border is back
- click an item and select
- hover the buttons and they should stay visible
- open http://localhost:4000/components/modal/test-modal-datagrid-title-overlap.html
- icon should be centered again
=> Misc - Regression fixes

docs/CHANGELOG.md, src/components/toolbar/_toolbar-new.scss
The x is misaligned on the old toolbar (not toolbar flex)
Fixes #7550 
- open http://localhost:4000/components/masthead/example-banner-detail.html
- expand the search and type
- x should be aligned ok
=> 7550 - Fix x alignment on old toolbar

docs/CHANGELOG.md, src/components/personalize/personalize.js, src/components/personalize/personalize.styles.js, src/components/searchfield/_searchfield-toolbar.scss
Adds fixes for tab selected color (regressed)
Fixes #7516
- go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
- change color (fx amber) and make sure the selected color is discernable from the no/selected color
- also fixed the shape of the category button
=> 7516 - Add fixes to tab selected color

app/views/components/locale/test-extend-messages.html, docs/CHANGELOG.md, src/components/dropdown/dropdown.js, src/components/locale/cultures/fr-CA.js, src/components/locale/cultures/pt-BR.js, src/components/locale/locale.js, test/components/locale/locale-func-test.js
Fixes two issues that have to do with locale. As explained in the steps below.
Fixes https://github.com/infor-design/enterprise/issues/7491
Fixes https://github.com/infor-design/enterprise/issues/5886
- go to http://localhost:4000/components/multiselect/example-index.html and open the dropdown. test should now say "Selection" instead of "Selected"
- also check another locale like http://localhost:4000/components/multiselect/example-index.html?locale=de-DE to see this new label is translated
- go to http://localhost:4000/components/locale/test-extend-messages.html?locale=fr-CA -> should be …
=> 7491/5886 - Add translation fixes

app/views/components/homepage/example-editable.html, docs/CHANGELOG.md, src/components/cards/_cards-new.scss, src/components/cards/_cards.scss, src/components/homepage/_homepage.scss
Fixes a pair of issues related to the card changes
Fixes #7580
Fixes #7579
- go to http://localhost:4000/components/cards/example-workspace-widgets.html
- find the back button example
- inspect the widget-content (should not expand below)
- go to http://localhost:4000/components/homepage/example-editable.html
- the X and drag icons should be visible
- try and resize and sort
=> 7580/7579 - Additional Card fixes

app/views/components/module-nav/example-hidden.html, app/views/components/module-nav/example-not-filterable.html, app/views/components/module-nav/example-six-levels-icons.html, app/views/components/module-nav/example-six-levels.html, docs/CHANGELOG.md, src/components/dropdown/dropdown.js, src/components/module-nav/module-nav.js, src/components/module-nav/module-nav.settings.scss
This PR fixes a couple issues in IDS Components related to behavior in the Angular Module Nav component wrapper:
- Fixes a bug where the `filterable` setting was always on
- Adds a new demo page with a disabled `filterable` setting
- Fixes a dropdown bug that was causing Module Nav Role Switcher to render its Dropdown wrapper element twice
- Fixes some styling bugs and consistency issues in demo examples
Related to #7386
Related to infor-design/enterprise-ng#1477
- Open https://ng1477-module-nav-patch-enterprise.demo.design.infor.com/components/module-nav/example-index.html
- Everything …
=> NG1477 - Improve some Enterprise components for better compatibility with Angular Module Nav

src/components/cards/cards.js
This PR fixes the visibility of the custom action to work with the Angular wrapper. It reduces specificity in the jQuery component to align with Angular's lifecycle. Essentially, the jQuery instance is now executed after the Angular component, ensuring that the condition is met.
N/A
- Go to NG project and get the jquery fix via copying the dist or just change directly in the node_modules -> ids-enterprise -> dist -> js ->sohoxi.js
- Go to http://localhost:4200/ids-enterprise-ng-demo/cards-workspace-widgets
- Button `more` should be visible under `Bordered with Actions` card
**Included in …
=> Card/Widget fixes in NG

docs/CHANGELOG.md, src/components/dropdown/_dropdown-new.scss
This PR fixes the dropdown icon overlapping with the multi select field in RTL.
Closes #7502
- Go to http://localhost:4000/components/multiselect/example-index.html?theme=new&mode=light&colors=default&locale=ar-SA
- Check the `Fruits (disabled)`
- Dropdown icon should not overlapping the field
=> 7502 - Fix dropdown icon overlapping the field in RTL

app/views/components/popupmenu/test-menubutton-viewport.html, docs/CHANGELOG.md, src/components/place/place.js
This pull request will fix the placement of popup when parent element is outside of viewport.
Closes https://github.com/infor-design/enterprise/issues/5018
- Go to http://localhost:4000/components/popupmenu/test-menubutton-viewport.html
- Shrink the page till the `Normal Menu` is somewhat outside of the viewport
- Click the Menu
- See the popup
=> 5018 - Popupmenu Placement when Parent Element is outside of viewport

docs/CHANGELOG.md, src/components/icons/_icons-new.scss
Fixes https://jira.infor.com/browse/IDS-1360
Fixes https://github.com/infor-design/enterprise/issues/7655
- go to http://localhost:4000/components/icons/example-empty-widgets.html
- check size is 80x780 not 65x80
- note that classic is unchanged
- check related page http://localhost:4000/components/emptymessage
=> 1360 - Fix empty message size

docs/CHANGELOG.md, src/components/toast/_toast.scss, src/core/_config.scss, src/themes/theme-classic-dark.scss, src/themes/theme-new-dark.scss
The progress bar color was incorrect. Fixed it
Fixes #7648 
- go to http://localhost:4000/components/toast/example-index.html?theme=new&mode=dark&colors=default
- click the button and check the toast color of the progress bar
- test all 6 themes
=> 7648 - Fix progress bar color

app/views/components/datagrid/test-change-show-select-all-checkbox.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/components/searchfield/_searchfield.scss
Added z-index for empty filter wrapper so that it won't overlap with checkbox.
Closes #7499 
- Go to: http://localhost:4000/components/datagrid/test-change-show-select-all-checkbox.html
- Click on Toggle Filter
- Click on Toggle Select All
- In Personalize Columns, uncheck everything except Product ID and Checked
- Hover on lower half of Select All checkbox, should be able to click
=> 7499 - Added z-index for empty filter wrapper

docs/CHANGELOG.md, src/components/accordion/accordion.js, src/components/module-nav/module-nav.common.js, src/components/module-nav/module-nav.js, src/components/module-nav/module-nav.switcher.js
This PR further improves the Module Nav API and removes gaps as reported by the Landmark team:
- Adds some settings to the Module Nav for disabling automatic initialization of child components, as well as direct settings for the child Accordion component.
- Extends the Nav Item tooltip feature to the Module Switcher component
Related to infor-design/enterprise-ng#1521
Related to infor-design/enterprise-ng#1477
Related to #7386 
- Open http://localhost:4000/components/module-nav/example-index.html
- While the Module Nav remains in collapsed mode, hover the Module Button …
=> NG1477 - Add more Module Nav API improvements

docs/CHANGELOG.md, src/components/cards/_cards.scss
Updated style for icon buttons in listviews in cards. Hover is based on a previous version (does not have a background): https://4660-enterprise.demo.design.infor.com/components/cards/example-expandable-cards.html
Closes #7636 
- Go to: http://localhost:4000/components/cards/example-expandable-cards.html
- Expand card
- Hover over > button
- Should not have a hover state that overflows
=> 7636 - Updated hover style for button in listview

docs/CHANGELOG.md, src/components/contextualactionpanel/_contextualactionpanel.scss, src/components/toolbar-flex/_toolbar-flex.scss
Add color style for toolbar flex popupmenu button
Closes #7383 
- Go to: http://localhost:4000/components/contextualactionpanel/test-complex-toolbar-flex.html
- Open Contextual Action Panel
- Open Filter popup menu
- Filter button color should be visible when open
- Check other versions and modes
=> 7383 - Updated popupmenu color styles

app/views/components/line/example-axis-ticks.html, app/views/components/line/test-axis-ticks-date-range.html
This PR fixes an error related to `d3.values` that caused the line chart to not render. In `d3 ver. 7`, `d3.values` is not supported, so it needs to be changed to `Object.values`.
N/A
- Go to http://localhost:4000/components/line/test-axis-ticks-date-range.html & http://localhost:4000/components/line/example-axis-ticks.html
- There should be no errors in the log, and the line chart should render successfully
=> N/A - Fix d3.values is not a function in line chart

docs/CHANGELOG.md, src/components/listview/_listview.scss
This pull request will fix the width of the search field in page pattern example.
Closes https://github.com/infor-design/enterprise/issues/7561
- Go to http://localhost:4000/components/page-patterns/example-list-detail-search-paging.html
- See the `searchfield`
=> 7561 - Page Pattern Search Field Full Width

app/views/kitchen-sink.html, docs/CHANGELOG.md, src/components/bar/bar.js
Fixes the legend position as it was too far down causing a scrollbar. cc @yohannahbautista check this out as i wanted to get a jump on this fix. If you see something better please let me know or update.
Fixes #7693 
- go to http://localhost:4000/
- scroll down to the chart section
- check all charts show the legend with no scrollbar and look decent
=> 7693 - Added fix for stacked legend

app/views/components/week-view/example-card.html, app/views/components/week-view/example-stacked.html, docs/CHANGELOG.md, src/components/week-view/week-view.js
Fixed bug where week view stacked/agenda variant ignored `showAllDay` option
#7700 
1. Checkout branch, `npm run build`, `npm run start`
2. Go to http://localhost:4000/components/week-view/example-card.html
3. The second example shows agenda variant with `showAllDay: false` setting
4. Open `week-view/example-stacked.html` file and add `showAllDay: false` setting
5. It should properly hide the all day row
=> 7700 - WeekView Agenda Variant hide allDay row

app/views/components/modal/example-slider.html, docs/CHANGELOG.md, src/components/modal/_modal.scss, src/components/modal/modal.js, src/core/_config.scss, src/themes/theme-classic-contrast.scss, src/themes/theme-classic-dark.scss, src/themes/theme-classic-light.scss, src/themes/theme-new-contrast.scss, src/themes/theme-new-dark.scss, src/themes/theme-new-light.scss
Refixed the modal issues by adding back the css overflow. I remove the JS sizing part and added back the css. I tested all related issues and everything seems fixed.
Do check for any uses cases i might not know. @ericangeles @yohannahbautista 
Fixes #7711 
- go to http://localhost:4000/components/modal/example-slider.html
- In dev tools select "surface duo" mobile emulator
- open Modal and content should scroll not break out
- test https://github.com/infor-design/enterprise/issues/7698 is still fixed
- test https://github.com/infor-design/enterprise/issues/7660 is still fixed
- test …
=> 7711 - Re fix for modal overflow issues

app/views/components/tooltip/test-irregular-string.html, docs/CHANGELOG.md, src/components/tooltip/tooltip.js
This pull request will fix an error in tooltip where some string is unrecognizable.
Closes https://github.com/infor-design/enterprise-ng/issues/1499
- Go to http://localhost:4000/components/tooltip/test-irregular-string.html
- Hover the button
- See the console, no errors
=> NG1499 - Tooltip Script Error

docs/CHANGELOG.md, src/components/editor/_editor.scss, src/core/_reset.scss
This PR fixes the missing borders when pasting html table inside of the editor.
Closes #7463 
- Go to http://localhost:4000/components/editor/example-index
- Click HTML from the toolbar
- Paste the html string from this file ([table-border-not-rendering.txt](https://github.com/infor-design/enterprise/files/11329042/table-border-not-rendering.txt))
- Then go back to visual
- Table should have borders
=> 7463 - Fix missing borders when pasting html table inside of the editor

app/views/components/notification/test-insert-subheader.html, docs/CHANGELOG.md, src/components/personalize/personalize.styles.js
Updated color styles when notification is in subheader
Note: Still unsure what "banner" is from the issue, but based on the screenshot of the css, it's likely subheader. When notifications (or "message" as mentioned) is in a personalizable subheader the same bug appears.
Closes #7623 
- Go to: http://localhost:4000/components/notification/test-insert-subheader.html
- Notifications should have readable text and icons
- Change Colors
- Text and icons should not be white/still be readable
=> 7623 - Updated color styles when notification is in subheader

app/views/components/module-nav/example-no-icon.html, docs/CHANGELOG.md, src/components/module-nav/module-nav.js, src/components/module-nav/module-nav.switcher.js
Added the ability to set the default icon to false. To have no icon.
Fixes #7740
- go to http://localhost:4000/components/module-nav/example-no-icon.html (no icon should show)
- go to http://localhost:4000/components/module-nav/example-icon.html (still works)
=> 7740 - Added an option to not set an initial icon

docs/CHANGELOG.md, src/components/module-nav/module-nav.js, src/components/personalize/personalize.js, src/themes/theme-new-dark.scss
Fixes dark mode issues and missing tooltip in module nav
Fixes https://github.com/infor-design/enterprise-ng/issues/1525
Fixes https://github.com/infor-design/enterprise/issues/7753
- go to http://localhost:4000/components/module-nav/example-index.html?colors=fff&theme=new&mode=dark
- make sure the search placeholder text is visible
- also updated the header (missed this on a previous PR)
- `npm run build` and copy to a ids-enterprise-ng project or npm link
- go to http://localhost:4200/ids-enterprise-ng-demo/
- collapse the menu by clicking the hamburger icon
- hover settings icon and …
=> 7753/1525 - Add module nav fixes

docs/CHANGELOG.md, src/components/week-view/week-view.js, test/components/week-view/week-view-api-func-test.js
endDate hours is also set on initialization
Closes #7684 
- Go to the ff. pages (these also had the same bug):
- http://localhost:4000/components/week-view/test-updated.html
- http://localhost:4000/components/week-view/test-ajax-events.html
- Click on next > button
- Should not have the last day of the previous week be the first day 
=> 7684 - Fixed bug where going to next didn't render the complete week

app/views/components/module-nav/example-index.html, docs/CHANGELOG.md, src/components/module-nav/module-nav.accordion.scss, src/components/module-nav/module-nav.scss, src/core/_config.scss
Reduced spacing between menu items fro 8px to 4px
Fixes #7770 
- go to http://localhost:4000/components/module-nav/example-index.html?colors=fff
- expand the menu
- notice in both collapsed and expanded states the padding is reduced from 8px to 4px
=> 7770 - Adjust padding in module nav

app/views/components/datagrid/test-filter-with-default-operator.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Fixes bug where defaultFilterOperator wasn't being honored for date and time columns.
"Closes #7766 "
1. Pull and build the code
2. Navigate to /components/datagrid/test-filter-with-default-operator.html
3. See that the filter type for Ordered Date default to less than or equals
- [x ] A note to the change log.
=> Allow defaultFilterOperator to be honored for date and time columns

app/views/components/module-nav/example-no-dropdown-search.html, docs/CHANGELOG.md, src/components/module-nav/module-nav.switcher.js
Added an example showing how to disable search in the dropdown. NOTE Will need a separate PR for the NG part...
Fixes [#1535](https://github.com/infor-design/enterprise-ng/issues/1535)
- go to http://localhost:4000/components/module-nav/example-no-dropdown-search.html?colors=fff
- interact with the dropdown icon picker on the top and see that with this option you cant filter/search
=> 1535 - Module Nav Option to disable search

app/views/components/module-nav/example-index.html, docs/CHANGELOG.md, src/components/module-nav/module-nav.js
This PR adds a setting to the Module Nav component, `enableOutsideClick`.  When enabled, a click event handler is added to the Module Nav container element that wraps both the bar and the content, and listens for clicks within the content area.  When triggered, the event will collapse or hide the Module Nav bar if it's in `expanded` display mode.  Whether the bar completely hides, or just collapses, depends on what state it was in before it was switched to `expanded` mode.
- Closes #7786
- Related to infor-design/enterprise-ng#1539
- Pull/build/run
- Open …
=> 7786 - Module Nav: Add `enableOutsideClick` setting for collapse/hide when page content is clicked

package-lock.json, package.json
This PR updates to the latest `ids-identity` version, with the purpose of adding a missing empty state icon.
Closes #7785 
- Pull/build/run
- Open http://localhost:4000/components/icons/example-empty-states.html
- Under "new empty states", compare the number of icons.  There should be one more compared to https://main-enterprise.demo.design.infor.com/components/icons/example-empty-states.html (the "no images" icon)
=> 7785 - Bump `ids-identity` version (accept new icons)

docs/CHANGELOG.md, src/components/completion-chart/_completion-chart.scss
Updated style so that focus border is fully seen
Closes #7731 
- Go to: http://localhost:4000/components/targeted-achievement/example-links-icons.html
- Click on Equipment hyperlink
- Look at focus border in Equipment
- Should be fully seen
=> 7731 - Fixed hyperlink focus style in completion chart

docs/CHANGELOG.md, src/components/header/_header-new.scss, src/components/header/_header.scss, src/components/searchfield/_searchfield.scss
Height style was meant for the case when searchfield is in subheader, so moved styling to subheader class only.
Fixes #6695 
- Go to the ff. and check both versions:
- http://localhost:4000/components/searchfield/example-go-button.html
- http://localhost:4000/components/searchfield/example-categories-and-go-button.html
- http://localhost:4000/components/header/example-searchfield-full.html
- Go button should be the same height as searchfield
=> 6695 - Adjusted height for go button

docs/CHANGELOG.md, src/components/icons/_icons-new.scss, src/components/icons/_icons.scss
Adjusted width of icons so that borders can be even. In New, width is the same as height, moved the width styling so that both New and Classic will have it
Closes #7616 
- Go to: http://localhost:4000/components/images/example-photos.html
- In both versions, the status icon borders should be aligned
=> 7616 - Adjusted width of icons

app/views/components/circlepager/example-mobile.html, docs/CHANGELOG.md
This PR fixes the circlepager being inside a card. The issue arose due to recent changes in the card's height. I've added the `auto-height` class to rectify this.
Closes #7724
- Go to http://localhost:4000/components/circlepager/example-mobile.html
- Circlepager should be inside of the card
~~- [] An e2e or functional test for the bug or feature.~~
=> 7724 - Fix circlepager inside of a card

docs/CHANGELOG.md, src/components/images/_images.scss
Some image icons (avatars) where 50x50 and should be 48x48
Fixes #7836
- go to http://localhost:4000/components/images/example-photos.html
- inspect each image / avatar and should be 48x48 now
=> 7836 - Fix image size

docs/CHANGELOG.md, src/components/personalize/personalize.styles.js, src/utils/color.js
Fix on Slate's personalization header text color
Closes #7811 
- Go to: http://localhost:4000/components/header/example-index.html?colors=606066
- Text color on header should be white
=> 7811 - Fix on Slate's personalization header text color

docs/CHANGELOG.md, src/components/popupmenu/popupmenu.js
This pull request will fix datagrid column filter not open after a series of simultaneous clicking of column filters.
Closes https://github.com/infor-design/enterprise/issues/7750
- Go to http://localhost:4000/components/datagrid/example-filter?theme=uplift&variant=light
- Start selecting the filter icon on any one of the column simultaneously.
=> 7750 - Datagrid Filter List Intermittent

app/views/components/icons/example-status-colors.html, app/views/components/listview/example-card.html, app/views/components/stats/example-index.html, docs/CHANGELOG.md, src/components/badges/_badges-new.scss, src/components/badges/_badges.scss, src/components/icons/_icons.scss, src/components/link/readme.md, src/components/stats/_stats.scss, src/components/stats/readme.md, test/components/tag/tag-puppeteer-visual-test.js
Based on design qa from https://github.com/infor-design/enterprise/pull/7817#issuecomment-1684626046 cc @talkaboutdesign
Made the status icon a feature with a seperate div. Made sure it was 24x24 and the icon is always 18x18
Fixes #7661 
-review http://localhost:4000/components/listview/example-card.html
- review http://localhost:4000/components/stats/example-index.html
- http://localhost:4000/components/icons/example-status-colors.html
- in all cases the circle is now 24x24 and the icon 18x18
- http://localhost:4000/components/tag/example-index.html  -> is now 24px height
- …
=> 7661 - Change badge size by design

app/views/components/datagrid/example-paging.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js, src/components/pager/pager.js, test/components/datagrid/datagrid-settings-func-test.js
This pull request will fix pager pagesizes default settings cannot be overridden with custom settings.
Closes https://github.com/infor-design/enterprise/issues/7629
- Go to http://localhost:4000/components/datagrid/example-paging.html
- Open Pager on the lower right bottom
- It should be `10, 50 and 100` instead of `25, 50, 75, 100`
=> 7629 - Pager Pagesizes Overwrite

docs/CHANGELOG.md, src/components/fileupload/fileupload.js
This PR fixes the file upload where the validation is not triggered after clearing the input field.
Closes #7645 
- Go to http://localhost:4000/components/fileupload/test-required.html
- Upload a file to any input field
- Click clear button
- Validation should show
=> 7645 - Trigger the validation after clearing the input field

app/views/components/icons/example-status-colors.html, docs/CHANGELOG.md, src/components/grid/_grid.scss, src/components/masthead/_masthead-new.scss, src/components/masthead/_masthead.scss
Fix height of masthead
Fixes #7747
- go to http://localhost:4000/components/masthead/example-index.html
- confirm height is 40px
- things should be centered in it
=>  7747 - Set masthead height to 40px / remove info

docs/CHANGELOG.md, src/components/tooltip/_tooltip.scss
This PR Improves the popover title style and position, excluding the 'alternate' class.
Closes #7676
- Go to http://localhost:4000/components/popover/test-nested (This example doesn't use `alternate` class in popover)
- Open the popover button
- Title and close button should be aligned properly
=> 7676 - Improve popover title

app/views/components/radios/example-hitbox.html, docs/CHANGELOG.md, src/components/radios/_radios.scss
This PR adds hitbox on radio component for mobile devices.
Closes #7659
- Go to http://localhost:4000/components/radios/example-hitbox
- Radio button and labels should have 44px height (much bigger compare to the default radio button size)
=> 7659 - Add hitbox in radio component

app/views/components/datagrid/example-expandable-row.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.formatters.js, src/components/datagrid/datagrid.js
A row will be expanded if there's an `expanded: true` in the dataset item.
Closes #7680 
- Go to: http://localhost:4000/components/datagrid/example-expandable-row.html
- First row should be expanded
=> 7680 - Added expanded default for expandable formatter

app/views/components/column-grouped/example-axis-labels.html, app/views/components/column/example-rotate.html, docs/CHANGELOG.md, src/components/cards/_cards.scss
Adjusted width for widget title to allow for full text chart title.
Closes https://github.com/infor-design/enterprise/issues/7889
- Go to: 
- http://localhost:4000/components/column/example-rotate.html
- http://localhost:4000/components/column-grouped/example-axis-labels.html
- http://localhost:4000/components/column-grouped/example-column-grouped-with-line-combined-hide-dots.html
- http://localhost:4000/components/column-grouped/example-column-grouped-with-line-combined.html
- Chart titles should not overflow.
=> 7889 - Fix chart title's width for column charts

app/views/components/cards/example-expandable.html, app/views/components/cards/test-datagrid.html, app/views/components/cards/test-full-width.html, app/views/components/cards/test-paging-datagrid.html, app/views/components/cards/test-tabs-card.html, app/views/components/homepage/example-add-widget.html, app/views/components/homepage/example-filled.html, app/views/components/homepage/example-monthviews.html, app/views/components/homepage/example-scenario-h.html, docs/CHANGELOG.md, src/components/calendar/_calendar-toolbar.scss, src/components/cards/_cards-new.scss, src/components/cards/_cards.scss, src/components/homepage/_homepage.scss, src/components/homepage/homepage.js
Fixed as noted that the widget height is a bit inconsistent. Sizes should be
- Widget Total 368
- Header 48
- Body 320 
cc @talkaboutdesign
Fixes #7896
- go to http://localhost:4000/components/cards/example-workspace-widgets.html and confirm
- test all widget and card examples http://localhost:4000/components/cards http://localhost:4000/components/widgets and http://localhost:4000/components/homepage
- looking for unneeded scrollbars or similar issue
- also check the double height widget on http://localhost:4000/components/homepage/example-scenario-h.html (widget 752, header 48, content …
=> 7896 - Fix widget sizes

docs/CHANGELOG.md, src/components/contextualactionpanel/_contextualactionpanel.scss, src/components/personalize/personalize.styles.js
Fixes wrong hover color on CAP and header. Opening this up for deeper QA. Thanks!
Fixes https://github.com/infor-design/enterprise/issues/7943
Fixes https://github.com/infor-design/enterprise/issues/7944
- go to http://localhost:4000/components/header/example-flex-toolbar.html?theme=new&mode=contrast&colors=ffffff
- hover buttons color should be blue on the icon
- test all themes ect
- go to http://localhost:4000/components/contextualactionpanel/example-index.html
- hover buttons color should be blue on the icon
- test all themes ect
=> 7944/7943 - Fix hover colors

app/views/components/homepage/example-hero-widget.html, docs/CHANGELOG.md, src/components/homepage/_homepage.scss
Changed a css class default in hero to a non white color now that its white. Also remove an un-needed class as noted on https://github.com/infor-design/enterprise/issues/7505#issuecomment-1719530088
cc @volante007
Fixes #7938 
- go to http://localhost:4000/components/homepage/example-hero-widget.html?colors=0066D4
- should work as before (no color change)
- edit the dom and insert only a label or something to test the color as attached..
=> 7938 - Add fix to color and remove class on heros

docs/CHANGELOG.md, src/components/charts/charts.js, src/components/column/column.js, src/components/personalize/personalize.styles.js, src/components/slider/_slider.scss, test/components/personalize/personalize-api-func-test.js
Fixes an odd error due to a regex not working with decimals on windows. Also fixed a slider warning in the console
Fixes #7941 
- go to http://localhost:4000/components/column-stacked/example-index?theme=uplift&variant=light
- hover the bars
- check console should be no errors or warnings
- IMPORTANT: test this on windows
- regression test slider vertical as well http://localhost:4000/components/slider/example-vertical.html
=> 7941 - Fix Column chart error

docs/CHANGELOG.md, src/components/toolbar/_toolbar.scss, src/core/_config.scss, src/themes/theme-classic-dark.scss, src/themes/theme-new-dark.scss
Added additional selectors and colors for the dropdown labels in the standalone toolbar to ensure visibility in dark mode.
Closes #7897 
- Go to: http://localhost:4000/components/toolbar/example-standalone-style.html?theme=new&mode=dark&colors=default
- Make sure dark mode is active
- Click a drop down
- Lose focus or move the cursor anywhere on the page
- Label should remain visible
=> 7897 - Fix standalone toolbar dropdown label visibility for dark mode

docs/CHANGELOG.md, src/components/editor/_editor.scss, src/components/editor/editor.js
This pull request will fix editor text not changing to other font headers in some scenarios after changing colors in Firefox.
Closes https://github.com/infor-design/enterprise/issues/7796
- Open in `Firefox`
- Go to http://localhost:4000/components/editor/example-index.html
- Select all the text inside the editor
- Change to `Header 1`
- Change the color of the text
- Change to `Normal Text`
=> 7796 - editor header firefox change

docs/CHANGELOG.md, src/components/applicationmenu/_applicationmenu-new.scss
This PR fixes the issue where the hover button background color was incorrect. 
It's weird that the button's CSS takes precedence over the appmenu's CSS.
Closes #7782 
- Go to
- http://localhost:4000/components/applicationmenu/example-menu-notification.html
- http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html
- http://localhost:4000/components/applicationmenu/example-resizable-menu.html
- Hover over on `Employee` dropdown menu button
- Hover button background color shouldn't be lighter …
=> 7782 - Fix appmenu switcher button hover background color

src/components/emptymessage/_emptymessage-new.scss, src/components/emptymessage/_emptymessage.scss, src/core/_config.scss, src/themes/theme-classic-dark.scss
Following up on a PR / comments from QA. Darkened the empty message color.
Follow up to https://github.com/infor-design/design-system/issues/518
- try http://localhost:4000/components/icons/example-empty-widgets.html?theme=new&mode=contrast&colors=default in all six themes and make sure the text doesnt look dim
=> 518 - Change color of empty message

app/views/components/popover/test-nested.html, src/components/tooltip/tooltip.js, src/utils/dom.js
This pull request provides alternative solution for the #7677 issue. It allows to use other components with event handlers, without the need to destroy them, when popover is hidden and recreate them before popover is shown.
Closes #7677 
- Go to: http://localhost:4000/components/popover/test-nested
- Click buttons to check popover
- Try typing in the text area (check the counter) or try to expand datagrid row
- Close and open again
- Try typing in the text area (check the counter) or try to expand datagrid row
- smoke test tooltip and popover …
=> 7677 - Change popover to allow components with event handlers

app/views/components/module-nav/example-with-accordion-in-page-container.html, docs/CHANGELOG.md, src/components/module-nav/module-nav.accordion.scss
This PR fixes the issue where the accordion in the page container inherited the module nav accordion styles. The fix was to isolate the styles under the `module-nav` class.
Closes #7884 
- Go to http://localhost:4000/components/module-nav/example-with-accordion-in-page-container.html?colors=fff
- When the module nav is collapsed, the accordion in the page container should not be affected by the module nav accordion styles
- Play around the module nav and accordion (compare the accordion/example-index)
~~- [ ] An …
=> 7884 - Fix accordion inherited module nav accordion styles

docs/CHANGELOG.md, src/components/spinbox/_spinbox.scss
Adjusted the sizing of the spinbox wrapper to stop the increment button from overflowing in classic version.
Closes https://github.com/infor-design/enterprise/issues/7988
- Go to http://localhost:4000/components/modal/example-spinbox.html?theme=classic&mode=light&colors=default
- Make sure that the "Classic" version is selected.
- Click "Show Modal".
- Increment button should be inline with the rest of the spinbox.
=> 7988 - Fix spinbox increment button overflow.

docs/CHANGELOG.md, src/components/place/place.js, src/components/popupmenu/popupmenu.js, src/utils/environment.js
Fixes an issue where context menu right clicking stopped working in safari. This may be due to some changes in the safari user agent.
To Fix:
- made isMac override is IOS
- changed to use touch (feature detection)
Fixes #8037 
- test http://localhost:4000/components/contextmenu/example-index.html
- need to test on every browser and devices
- on touch devices like IOS and android a longpress will open on the input will open the menu
- on mac/windows -> safari and chrome a right click will open the menu 
- run page http://localhost:4000/components/environment/example-browser-specs.html on …
=> 8037 - Fix env for safari

docs/CHANGELOG.md, src/components/tabs-vertical/_tabs-vertical-new.scss, src/components/tabs-vertical/_tabs-vertical.scss
Fixes an irregular size (250 and 100% - 251) that caused tab panes to overflow on zoom. And removed a "double" border.
Fixes #8046 
- Go to http://localhost:4000/components/tabs-vertical/example-index.html
- Zoom in (50%) on my monitor (try lots of zoom levels 40-50% min)
- Notice content will not disappear
- Test classic/other themes that the right border is still ok
=> 8047 - Fix zoom issue on windows

docs/CHANGELOG.md, src/components/popupmenu/_popupmenu.scss, src/components/tabs/_tabs-new.scss, src/components/tabs/_tabs.scss
Adjusted placement of error and dismissible icons in tabs spillover/dropdown menu.
Closes https://github.com/infor-design/enterprise/issues/7970
- Go to http://localhost:4000/components/tabs/example-enable-disable.html
- Open the "Can Have Error Icon" tab.
- Type anything in any of the required fields.
- Delete all text from required fields to trigger the error icon.
- Shrink window size/switch to responsive view until the tabs spillover/dropdown menu is shown.
- Open the dropdown menu.
- "Error" icon should be aligned. …
=> 7970 - Fix alignment of icons in tabs dropdown menu.

docs/CHANGELOG.md, src/components/button/_button-new.scss
Adjusted rule for hovered button styling in new version if the button is a primary button. Some cases would have a hovered primary button be styled as if they were a secondary button.
Closes https://github.com/infor-design/enterprise/issues/7977
- Go to:
- http://localhost:4000/components/button/example-100-percent.html
- http://localhost:4000/components/button/example-button-with-hitbox.html
- http://localhost:4000/components/button/example-as-link.html
- Hover over primary buttons.
- Primary buttons should not look like a hovered secondary …
=> 7977 - Fix primary button hover styling.

docs/CHANGELOG.md, src/components/homepage/_homepage.scss
Fixes an incorrect calc on quad width widgets. (not added patch already to 4.88)
Fixes #8056 
- go to http://localhost:4000/components/homepage/example-scenario-i.html
- also test http://localhost:4000/components/homepage/example-scenario-i.html
- in all cases widgets should line up in width
- for good measure test all scenarios http://localhost:4000/components/homepage/ (for QA)
=> 8056 - Fix quad widget width

docs/CHANGELOG.md, src/components/module-nav/module-nav.js, src/components/module-nav/module-nav.settings.scss
Fixes a bug reported by @krishollenbeck where the settings menu is hidden. Will patch to 4.84 and 4.88 when tested.
Fixes #8063 
- go to http://localhost:4000/components/module-nav/example-index.html?colors=fff
- on desktop size:
- open the menu
- click the settings menu -> settings menu should now be visible and actionable
- on mobile size:
- open the menu
- click the settings menu -> settings menu should now be visible and actionable and the menu should be on top
- should still be able to select an item in the settings menu, when it closes select a nav item and it should shut the menu on …
=> 8063 - Add fixes to keep settings menu visible

app/data/datagrid-sample-data.json, app/views/components/datagrid/example-index.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid-filtering-func-test.js
Space between text in rows are not trimmed as default
Closes #7849 
- Go to: http://localhost:4000/components/datagrid/example-index.html
- Check last row, spaces should be shown in ID and Product Name 
=> 7849 - Space between text in rows are not trimmed as default

app/views/components/tabs/example-enable-disable-individual-tabs.html, docs/CHANGELOG.md, src/components/radios/_radios.scss, src/components/tabs-header/_tabs-header-new.scss
This pull request will fix the focus state of radio button not fully shown in tabs.
Closes https://github.com/infor-design/enterprise/issues/7955
- Go to http://localhost:4000/components/tabs/example-enable-disable-individual-tabs.html
- Click one radio button
- Press arrow down or up (depending on what you radio button clicked)
- See the focus
=> 7955 - Tabs Radios Overflow

docs/CHANGELOG.md, src/components/cards/_cards-new.scss, src/components/cards/_cards.scss
Adjusted positioning of card menu button for no header to be at the upper left of the card.
CLoses https://github.com/infor-design/enterprise/issues/8081
- Go to http://localhost:4000/components/cards/example-no-header.html?theme=classic&mode=light&colors=default
- Menu button should be at the upper left of the card.
=> 8081 - Fix cards menu button positioning for no header.

src/components/counts/_counts.scss
Fixes layout issue in counts caused by missing line-height from a reset change
Fixes #8121 
- go to http://localhost:4000/components/counts/example-index.html
- text should not overlap
=> 8121 - Add fix for counts

docs/CHANGELOG.md, src/components/dropdown/_dropdown.scss
This PR fixes the issue where the dropdown text and icon were overlapping on smaller viewports.
Closes #8000
- Go to http://localhost:4000/components/dropdown/example-index
- Change to responsive viewport (toggle device toolbar)
- Resize the page to show the ellipsis on smaller viewports
- Text and dropdown icon should not overlap
=> 8000 - Fix dropdown text and icon on smaller viewports

docs/CHANGELOG.md, src/components/timepicker/timepicker.js
Remove disabled prop in trigger button on enable call
Closes https://github.com/infor-design/enterprise-ng/issues/1567
- Go to: http://localhost:4000/components/timepicker/test-states.html
- Click Disable
- Timepicker should be disabled
- Click Enable
- Timepicker should be enabled
=> NG1567 - Remove disabled prop in trigger button on enable call

app/views/components/datagrid/test-newrow-error.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js, src/components/tooltip/_tooltip.scss
Fix on new row not showing error tooltip on first cell. 
Note: Made test page based on the instructions given on the issue. Should also be able to replicate it via console to be sure as no stackblitz example was given.
Closes #8071 
- Go to: http://localhost:4000/components/datagrid/test-newrow-error.html
- Click on Add Row
- Click on Add Error
- Hover over the error icons
- Tooltip should appear
=> 8071 - Fix on new row not showing error tooltip on first cell

docs/CHANGELOG.md, src/components/personalize/personalize.styles.js
Removed background for hovered selected tab
Fixes #8088 
- go to http://localhost:4000/components/page-patterns/example-search-form.html?theme=classic&mode=contrast&colors=ffffff
- Click on 'Recent'
- Hover over it
- See there is no background
=> 8088 - Page patterns: Fix hovered selected tab background

docs/CHANGELOG.md, src/components/personalize/personalize.styles.js
Button hover color was barely visible in Alabaster. Adjusted personalize button hover color to make the hover more visible in the different color themes.
Closes https://github.com/infor-design/enterprise/issues/8035
- Go to http://localhost:4000/components/button/example-index.html?colors=ffffff&theme=new&mode=contrast
- Ensure Alabaster color is selected.
- Hover over buttons.
- Hovered buttons should be clearly indicated.
=> 8035 - Fix button hover color for different color themes.

docs/CHANGELOG.md, package-lock.json, src/components/colors/_colors.scss, src/components/theme/theme.js, src/themes/theme-new-dark.scss
Fixes some wrong colors in personalization.
Fixes #8151
Fixes #8152
- http://localhost:4000/components/personalize/example-index.html
- type the following in the console
```js
Soho.theme.personalizationColors().default
```
- default is white
- copy the class primary-bg color and put it on the header -> header should stay white
- change to dark node http://localhost:4000/components/personalize/example-index.html?colors=default&theme=new&mode=dark -> notice that the border is fixed 
=> 8151 - Added personalization color changes

docs/CHANGELOG.md, src/components/popupmenu/_popupmenu-new.scss
Icons in new theme were wrong size. Should be 18 not 14
Fixes #8175 
- go to http://localhost:4000/components/popupmenu/example-icons.html?theme=new&mode=light&colors=default
- open menus and see icon size is 18px and centers
- try also http://localhost:4000/components/popupmenu/example-icons.html?theme=classic where they are still 14
=> 8175 - Fix Icon size

docs/CHANGELOG.md, src/components/tabs-module/_tabs-module.scss
Page container padding for components when embedded causes issues in the website demo of Module Tabs. Removed padding for Module Tabs only.
Closes https://github.com/infor-design/enterprise/issues/8060
- Go to http://localhost:4000/components/tabs-module/example-index.html?theme=new&mode=light&colors=default&layout=embedded
- There should be no spacing on top of the tabs/page.
=> 8060 - Fixed padding issue for Module Tabs in website demo.

docs/CHANGELOG.md, src/components/lookup/_lookup-new.scss, src/components/lookup/_lookup.scss, src/components/toolbar/toolbar.js
This pull request will fix the searchfield size when settings has title in toolbar.
Closes https://github.com/infor-design/enterprise/issues/8025
- Go to http://localhost:4000/components/lookup/example-index.html
- Refresh the browser
- Open the lookup
- See the searchfield do not fit in the lookup
=> 8025 - Datagrid: Toolbar issue when toolbar has settings title

docs/CHANGELOG.md, src/components/cards/_cards-new.scss
After resizing the home page the animation is applied for the widgets to "shuffle". This animation animates more than the box-shadow and causes a subtle issue on hover. In order to fix it need to add !important to the hover animation so both animations can still work ok.
Fixes #8201 
- go to http://localhost:4000/components/cards/example-workspace-widgets.html
- hover the borderless cards and note the subtle border change animation 
- resize the page so the widgets "shuffle"
- retry to hover the borderless cards and note the subtle border change animation -> should look same as before …
=> 8201 - Improve hover animation

docs/CHANGELOG.md, src/components/personalize/personalize.styles.js
Changed color variable for the gradient to be the same as the header tabs background
Closes #8110 
- go to http://localhost:4000/components/tabs-header/example-index.html?theme=new&mode=dark&colors=ffffff
- resize the browser so the tabs overflow, click on a tab so tabs overflow on both sides
- see the color of the gradient is the same as bg color of the tabs
- check RTL mode http://localhost:4000/components/tabs-header/example-index.html?theme=new&mode=dark&colors=ffffff&locale=ar-SA
~- [ ] An e2e or functional test for the bug or …
=> 8110 - Header Tabs Fix personalizable overflowing gradient color

docs/CHANGELOG.md, src/components/breadcrumb/_breadcrumb.scss
Added `display` CSS property to breadcrumb's pseudo-element 
Closes #8167 
- **use Safari browser**
- go to http://localhost:4000/components/breadcrumb/example-index.html?locale=ar-SA
- see the `Fourth Item` is aligned with the rest
=> 8167 - Breadcrumb Fix misaligned item in RTL in Safari browser

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
This PR fixes the issue of the (Datagrid) drag handle's position overlapping the header text in the Firefox.
Closes #8012
- Open firefox browser and go to http://localhost:4000/components/datagrid/test-filter-custom-date.html
- Hover over any column (left-aligned text)
- Drag handle should not overlapping the header text
=> 8012 - Fix datagrid's drag handle position in firefox

docs/CHANGELOG.md, src/components/popupmenu/popupmenu.js
This pull request will fix popupmenu submenu not closing in some scenarios.
Closes https://github.com/infor-design/enterprise/issues/8043
- Go to http://localhost:4000/components/popupmenu/example-mixing-selectables.html
- Open `Partially Selectable Menu`
- Go to `Non-selectable Item #5`
- After the submenu opens, slowly move the mouse above `Non-selectable Item #4`
- Submenu should be closed
=> 8043 - Popupmenu Submenu Not Closing in some scenarios

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Added additional check when assigning the cell value.
Closes #8155 
- Click on the blank cell in Row 2, under Product Name
- Type a space
- Click in and out of the cell multiple times
- Value should be the same
=> 8155 - Fixed extra space increase on editable fields when clicking in and out of it

docs/CHANGELOG.md, src/components/personalize/personalize.styles.js
Removed box shadow on selected tabs so only focus indicator has it
Closes #8086
- go to http://localhost:4000/components/personalize/example-form-landmark2-horizontal.html?theme=new&mode=contrast&colors=ffffff
- click on a tab
- see there is no box shadow
- focus a tab
- see the box shadow
=> 8086 - Personalization Remove box shadow on selected tabs

docs/CHANGELOG.md, src/components/dropdown/dropdown.js, src/components/modal/modal.js
Added a check to ensure that the sub scrollable section in the datagrid is scrollable before attaching a scroll event to it
Closes #8127
- pull and build 
- go to http://localhost:4000/components/datagrid/test-dropdown-scroll.html
- open the modal and open any of action dropdowns
- scroll outside the dropdown options within the table
- see the dropdown has been closed
- open any of action dropdowns again and click on close (x) button
- see the dropdown has been closed
=> 8127 - Datagrid Fix dropdown remains open when scrolling in modal

app/views/components/datagrid/test-datagrid-tab-navigation.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js
This pull request will fix tab key navigation when using actionable mode when having editor and formatter.
Closes https://github.com/infor-design/enterprise/issues/8141
Closes https://github.com/infor-design/enterprise/issues/8245
- Go to http://localhost:4000/components/datagrid/test-datagrid-tab-navigation.html
- Click `Add Row`
- Click on the cell under column `Source Value`
- Press `1` and then press `Tab`
- it should go to the next column.
- Press `2` and then press `Tab`
- It should go to the next column. …
=> 8141 - Datagrid Actional Mode Navigation

docs/CHANGELOG.md, src/components/cards/_cards-new.scss
This PR fixes the detail title position in cards/widget.
Closes #8235
- Go to `Back Button` card/widget
- Click the button `Click to open the detail view`
- `Detail View` title should be aligned correctly
=> 8235 - Fix detail title vertical alignment

app/views/components/module-nav/example-hide-show-sections.html, app/views/components/module-nav/example-index.html, app/views/components/module-nav/example-one-pane.html, app/views/components/module-nav/example-with-accordion-in-page-container.html, docs/CHANGELOG.md, src/components/accordion/_accordion.scss, src/components/dropdown/_dropdown.scss, src/components/module-nav/module-nav.accordion.scss, src/components/module-nav/module-nav.dropdown.scss, src/components/module-nav/module-nav.guest.scss, src/components/module-nav/module-nav.js, src/components/module-nav/module-nav.searchfield.scss, src/components/module-nav/module-nav.switcher.scss, src/components/personalize/personalize.js, src/components/popupmenu/popupmenu.js, src/core/_config.scss, src/core/_controls-new.scss, src/core/_controls.scss, src/themes/theme-new-contrast.scss, src/themes/theme-new-dark.scss, src/utils/utils.js
Adds two new features to module nav. One is a guest section at the bottom, and the second is the ability to hide and show the search and switcher section. Additionally fixed a couple bugs.
- the utils.mergesettings worked odd and didnt properly merger. made a new function in utils
- fixed the dark mode header border it was too light
- fixed a bug in menu button that clicking when open did not toggle the menu button
**Design Review Questions**
See: https://8232-external-settings-enterprise.demo.design.infor.com/components/module-nav/example-hide-show-sections.html?colors=fff
- is guest section optionally clickable
- i made guest section a bit more compact
@krishollenbeck -> can you see if …
=> 8232 - Add External settings and hide show sections to module nav

docs/CHANGELOG.md, src/themes/theme-new-contrast.scss, src/themes/theme-new-dark.scss, src/themes/theme-new-light.scss
Fixes the wrong colored icon in datagrid for required columns.
Fixes #8260 
- test page http://localhost:4000/components/datagrid/example-editable.html and make sure the icon is visible
- try all 6 theme/modes
=> 8260 - Fix required icon color

app/views/components/datagrid/test-contentwidth.html, app/views/components/datagrid/test-form-buttons.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.formatters.js, src/components/datagrid/datagrid.js
Added contentWidth column setting to set width in formatters. Currently only used in button formatter
Closes #8132 
- Go to: http://localhost:4000/components/datagrid/test-contentwidth
- Adjust column width of button column
- Should stay in 100% and adjust accordingly
=> 8132 - Added contentWidth column setting to set width in formatters

docs/CHANGELOG.md, src/components/breadcrumb/breadcrumb.js
Trigger click on `li` element instead of `a` when overflowed menu `selected` event fires. Added `href` to overflowed menu items `a` so it's linkable
#8154 
- go to http://localhost:4000/components/breadcrumb/example-add-remove.html
- click on the Add button to create enough crumbs that there is an overflow
- open the overflow and click one
- notice when clicking an overflow item that the callback is executed (text in Last-Clicked Breadcrumb Contents and toast message)
=> 8154 - Breadcrumb Fix overflow menu items don't fire a callback function

docs/CHANGELOG.md, src/components/modal/_modal.scss
Fixed success icon alignment in message header
Closes #8240 
- In Safari, go to: http://localhost:4000/components/message/example-index.html
- Open Success Example
- Icon should be centered 
=> 8240 - Fixed success icon alignment in message header

app/views/components/module-nav/example-index.html, docs/CHANGELOG.md, src/components/module-nav/module-nav.switcher.js
This PR adds `attributes` setting to add automation id in the module nav switcher only.
Closes #8270
- Go to http://localhost:4000/components/module-nav/example-index.html?colors=fff
- Click the hamburger menu to open the nav switcher
- Click the nav switcher
- Inspect the list
- It should have automation-id and id attributes e.g., `data-automation-id="switcher-automation-id-option-x"`
=> 8270 - Add attributes setting for automation id in module nav switcher

app/views/components/datepicker/test-two-digit-year.html, docs/CHANGELOG.md, src/components/locale/locale.js, src/components/locale/readme.md, test/components/locale/locale-func-test.js
This PR lets you configure the two digit year switchover to a different year than the default which is `39`
Fixes #8061 
- go to http://localhost:4000/components/datepicker/test-two-digit-year.html
- note the switcher is changed to 75 (2075)
- open the first picker and it should show 1977 as the year
- try selecting and opening for different years close anove and below 2075
=> 8061 - Add setting for two digit year cutover

docs/CHANGELOG.md, src/components/button/_button.scss, src/components/datagrid/_datagrid.scss
Moved hover color to datagrid expand button as it seems to be for that only.
Closes #8220 
- Go to: http://localhost:4000/components/button/example-100-percent.html
- Hover on buttons
- Hover color should be correct
=> 8220 - Fixed wrong hover color on button

docs/CHANGELOG.md, src/components/module-nav/readme.md
Removed usage guidance from Module Nav readme. Usage will display in separate tab within component page on design.infor.com.
- Closes #8282 
- Closes [Jira IDS-1804](https://jira.infor.com/browse/IDS-1804)
- View `src/components/module-nav/readme.md`
=> Remove usage from Module Nav readme

docs/CHANGELOG.md, src/components/datagrid/_datagrid-new.scss, src/components/datagrid/_datagrid.scss, src/components/dropdown/_dropdown-new.scss
Fixed dropdown icon misalignment in extra small rowheight
Closes #8216 
- Go to: http://localhost:4000/components/datagrid/example-editable.html?theme=new&mode=light&colors=default&locale=ar-SA
- Hover over dropdown cells
- Arrow icon should be seen
=> 8216 - Fixed dropdown icon misalignment in extra small rowheight

app/views/components/modal/example-with-switch.html, docs/CHANGELOG.md, src/components/switch/_switch.scss
This PR fixes a bug where the modal would shift up when toggling a switch inside of it.
Closes #8018 
- Go to http://localhost:4000/components/modal/example-with-switch
- Open the modal
- Find `EmployeeAppraisal` switch and toggle it
- Modal should not shift up after toggle
=> 8018 - fix modal shifting up when toggling switch inside of it

docs/CHANGELOG.md, src/components/personalize/personalize.styles.js
This pull request will fix focus border not visible in classic contrast alabaster.
Closes https://github.com/infor-design/enterprise/issues/8265
- Go to http://localhost:4000/components/tabs-header/example-alternate.html?theme=classic&mode=contrast&colors=ffffff
- Click one of the tabs header
- Active Tab should be visible
=> 8265 - Tabs Header Contrast Classic

docs/CHANGELOG.md, src/components/toolbar/_toolbar-new.scss, src/components/toolbar/_toolbar.scss
Fixed alignments of searchfield icons in RTL
Closes #8208 
- Go to: http://localhost:4000/components/toolbarsearchfield/example-inside-contextual-panel.html?locale=ar-SA
- Open Contextual Action Panel
- Searchfield icon placeholder text should not be shown
- Type in searchfield and unfocus
- Text and icon should be aligned
=> 8208 - Fixed alignments of searchfield icons in RTL

app/views/components/header/example-hamburger-back.html, app/views/includes/header-appmenu-back.html, docs/CHANGELOG.md
Added a new example showing both a back and hamburger button. This was sort of already possible so just added a new example.
Fixes #8327 
- go to http://localhost:4000/components/header/example-hamburger-back.html?colors=ffffff
- clicking the burger icon will operate the menu
- clicking the back will show a toast for example purposes
=> 8327 - Added example with back button

src/components/datagrid/datagrid.js
When is reorder columns in the grid does not have trigger with indexfrom and indexTo.
For requirement I need these information to reorder my internal model to be synchronized with IDS model.
1- Move column index 0 to index 3.
2- Result : Give me indexFrom =0 and indexTo =3.
Added columns also just for test purpose to verify.
=> Added trigger for column reorder.

docs/CHANGELOG.md, src/components/cards/_cards-new.scss
This pull request will fix title alignment for bordered and borderless
Closes https://github.com/infor-design/enterprise/issues/8212
- Try to highlight the widget header for both bordered and borderless
- It should 360px both
=> 8212 - Cards Title Widget Alignment

app/views/components/datagrid/example-editable.html, docs/CHANGELOG.md
Replaced toolbar to flex toolbar on datagrid example editable
Closes #8093 
- check mobile viewport
- see the header title is not overlapping with other toolbar elements
=> 8093 - Change datagrid example editable toolbar to flex toolbar

docs/CHANGELOG.md, src/components/datagrid/datagrid.formatters.js
This PR evaluates the column cssClass callback for usage in the hyperlink class, previously it is just using the callback as is in a text format to the class
Provide a cssClass callback that returns a string on a SohoDatagridColumn, and use a Soho.Formatters.Hyperlink on the formatter definition
This PR solves:
Fixes https://github.com/infor-design/enterprise/issues/8340
=> evaluate column cssClass and use it properly on the hyperlink formatter string template

docs/CHANGELOG.md, src/components/modal/_modal.scss
Removed 100% width style in textarea
Closes #8125 
- Go to: http://localhost:4000/components/modal/test-validation-error-tooltip.html
- Size screen to be slightly less than 400px
- Open modal
- Check textarea width
=> 8125 - Fixed a bug where textarea field is bigger than other fields on screen widths less that 400px

app/views/components/datagrid/test-disable-tooltip-column.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Added option to disable tooltip in columns
Closes #8252
- Go to: http://localhost:4000/components/datagrid/test-disable-tooltip-column.html
- Open modal
- Hover over cells
- Del Date cells should not have tooltip
=> 8252 - Added option to disable tooltip in columns

app/views/components/datagrid/test-contextual-toolbar-hide.html, docs/CHANGELOG.md, src/components/cards/_cards-new.scss, src/components/datagrid/datagrid.js
This pull request will fix contextual toolbar auto hide when performing action.
Closes #8352 
Related https://github.com/infor-design/enterprise-ng/issues/1580
- Go to http://localhost:4000/components/datagrid/test-contextual-toolbar-hide.html
- Click one checkbox to show the toolbar
- Click `Perform Action`
- Toolbar should not hide
- Click `Hide Action`
- Toolbar should hide
- Click one checkbox to show the toolbar
- Deselect the checkbox selected to hide the toolbar
- Click the select all to show the toolbar
- …
=> 8352 - [Preview] Datagrid Contextual Toolbar Hide Function

docs/CHANGELOG.md, src/components/cards/_cards-new.scss
This pull request will fix widget header alignment with the parent.
Closes https://github.com/infor-design/enterprise/issues/8351
Relates https://github.com/infor-design/enterprise/issues/8212
- Go to http://localhost:4000/components/homepage/example-index.html
- Check widget header are align to the width of the paren
- Try to highlight the widget header for both bordered and borderless
- It should 360px both …
=> 8351 - [Preview] Cards Widget Header

docs/CHANGELOG.md, src/components/mask/mask-api.js
Included an additional check when `instanceof RegExp` fails that leverages `Object.prototype.toString` as an extended `typeof` and an alternative for `instanceof` (see https://javascript.info/instanceof#bonus-object-prototype-tostring-for-the-type).
This resolves an issue that is deemed to be occurring when creating a RegExp object in an older version of ECMA Script, GWT does not compile against ECMA Script 6, and passing to the IDS JavaScript which is using the new modern standard.
Fixes https://github.com/infor-design/enterprise/issues/8365
Difficult to test unless using GWT and calling …
=> #8365 - RegExp instanceof check in Mask component unreliable

app/views/components/datagrid/test-frozen-columns.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This pull request will fix frozen columns getting out of sync when columnReorder is set to true.
Closes https://github.com/infor-design/enterprise/issues/8198
- Go to http://localhost:4000/components/datagrid/test-frozen-columns.html
- Open `...` on the header of the datagrid
- Click `Personalize Columns`
- See the order and click `Close`
- Try dragging `Product Id` column, it shouldn't be allowed
- Try dragging `Quantity` column to `Product Id` column, nothing happens
- Open `...` on the header of the datagrid
- Click `Personalize …
=> 8198 - Datagrid Frozen Column Prevent Reorder

docs/CHANGELOG.md, src/components/homepage/_homepage.scss, src/components/homepage/homepage.js, src/components/tabs-vertical/_tabs-vertical.scss, test/components/button/button-puppeteer-visual-test.js
Fixed the top and bottom padding of the homepage component so there is a 16px gap on top and bottom. Had to use JS to do this. If someone has a better idea do let me know (was tricky due to position absolute elements).
Fixes #8362 
- check pages in http://localhost:4000/components/homepage
- like for example http://localhost:4000/components/homepage/example-four-column.html
- there should be a 16px gutter on top and bottom of the widgets in the home page
- smoke test http://localhost:4000/components/tabs-vertical/example-index.html
=> 8362 - Adjust top and bottom padding on home pages

docs/CHANGELOG.md, src/components/masthead/_masthead-new.scss, src/components/masthead/_masthead.scss
Fixes wrong color on hover.
Fixes #8391 
- go to http://localhost:4000/components/masthead/example-index.html
- hover the buttons -> should be white
=> 8391 - Fix incorrect color on hover

docs/CHANGELOG.md, src/components/datagrid/_datagrid-new.scss, src/components/datagrid/_datagrid.scss, src/components/datagrid/datagrid.js, test/components/datagrid/datagrid-puppeteer-test.js, test/components/datagrid/datagrid-puppeteer-visual-test.js
This pull request will fix cell editable not getting focused on click.
Closes https://github.com/infor-design/enterprise/issues/8408
- Go to http://localhost:4000/components/datagrid/test-editable-datetime.html
- Click on the first cell under Order Date Two
- The text should be highlighted
=> 8408 - Datagrid Datepicker Focus

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This PR adds a data automation ID to the grid tooltip, which is based on it's ID. It is added to both the grid tooltip and the tooltip content.
FYI: This applies not only to the filter button but also to all tooltips in the grid.
Closes https://github.com/infor-design/enterprise/issues/8372
- Go to http://localhost:4000/components/datagrid/test-filter-with-tooltip.html
- Hover on button filter
- Open the dev tools and check the tooltip element
- There should be `data-automation-id` in the grid tooltip
- There should also be a `data-automation-id` …
=> 8372 - Add data automation id in grid tooltip

docs/CHANGELOG.md, src/components/masthead/_masthead.scss
Fixes a bug where audible spans became visible.
Fixes #8422 
- go to http://localhost:4000/components/masthead/example-index.html
- audible spans should be invisible like before https://4910-enterprise.demo.design.infor.com/components/masthead/example-index.html and not https://main-enterprise.demo.design.infor.com/components/masthead/example-index.html which was incorrect
=> 8422 - Fix audible spans in masthead

docs/CHANGELOG.md, src/components/badges/_badges-new.scss, src/components/badges/_badges.scss, src/components/button/_button-new.scss, src/components/button/_button.scss, src/components/dropdown/_dropdown-new.scss, src/components/dropdown/_dropdown.scss
Fixes tags close button alignment
Fixes #8421 
- review the x on http://localhost:4000/components/multiselect/example-compact.html it should be aligned in classic and new theme
- review the x on http://localhost:4000/components/tag/example-index.html it should be aligned in classic and new theme
=> 8421 - Fix tags close button alignment

docs/CHANGELOG.md, src/themes/theme-new-dark.scss
This PR fixes slider ticks visibility inside of a modal in dark mode.
Closes #8397
- Go to http://localhost:4000/components/modal/example-slider.html?theme=new&mode=dark&colors=default
- Open the modal
- Slider ticks should be more visible in dark mode
=> 8397 - Fix slider ticks visibility inside of a modal

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This pull request will fix wrong cell focus on blur in tree grid.
Closes https://github.com/infor-design/enterprise-ng/issues/1616
- Go to http://localhost:4000/components/datagrid/test-tree-editable.html
- Navigate to "Description" column of Row with Id=5
- Change the text to some random and press Enter
- Notice the location of the focus cell should be the same
=> NG1616 - Selection Focus Tree Grid after Change/Blur

docs/CHANGELOG.md, src/components/locale/cultures/af-ZA.js, src/components/locale/cultures/ar-EG.js, src/components/locale/cultures/ar-SA.js, src/components/locale/cultures/bg-BG.js, src/components/locale/cultures/cs-CZ.js, src/components/locale/cultures/da-DK.js, src/components/locale/cultures/de-DE.js, src/components/locale/cultures/el-GR.js, src/components/locale/cultures/en-AU.js, src/components/locale/cultures/en-GB.js, src/components/locale/cultures/en-IN.js, src/components/locale/cultures/en-NZ.js, src/components/locale/cultures/en-US.js, src/components/locale/cultures/en-ZA.js, src/components/locale/cultures/es-419.js, src/components/locale/cultures/es-AR.js, src/components/locale/cultures/es-ES.js, src/components/locale/cultures/fr-CA.js, src/components/locale/cultures/lt-LT.js, src/components/locale/cultures/sv-SE.js, src/components/locale/locale.js
This PR adds `dateTimestamp` date format.
Closes #8373
- Go to http://localhost:4000/components/datepicker/example-index.html
- Open developer tool console and run this code `Soho.Locale.formatDate(new Date(2000, 10, 8, 13, 40, 30, 999), { date: 'dateTimestamp' })`
- Output should be `'2000-11-08 13:40:30'`
=> 8373 - Add `dateTimestamp` date format

docs/CHANGELOG.md, src/components/charts/_charts.scss, src/components/charts/charts.js, src/components/pie/pie.js, src/components/popupmenu/popupmenu.js, src/components/tabs/tabs.js, src/components/tooltip/_tooltip.scss
Fixes a regression in popupmenu where some items that should be checked are not checked.
This was caused be https://github.com/infor-design/enterprise/pull/8124
@tjamesallen15 can you test this PR since i see you added those lines?
Fixes https://github.com/infor-design/enterprise-ng/issues/1620
- get the latest  https://github.com/infor-design/enterprise-ng as an example was added
- `npm run build` then copy to  https://github.com/infor-design/enterprise-ng and run 
- run http://localhost:4200/ids-enterprise-ng-demo/popupmenu
- open the "Menu For Loop" example and try and toggle between …
=> 1620 - Fix popup selection bug 

app/views/components/tooltip/test-tooltip-number-sign.html, docs/CHANGELOG.md, src/components/tooltip/tooltip.js
This pull request will fix wrong cell focus on blur in tree grid.
Closes https://github.com/infor-design/enterprise-ng/issues/1614
- Go to http://localhost:4000/components/tooltip/test-tooltip-number-sign.html
- Hover to the button
- Tooltip should be shown `#10 - 24# WHITE`
=> NG1614 - Tooltip Special Characters

docs/CHANGELOG.md, src/themes/theme-new-dark.scss
This PR fixes readonly cell background color in dark mode.
Closes #8459 
- Go to http://localhost:4000/components/datagrid/example-editable.html?theme=new&mode=dark&colors=default
- Check the readonly cell
- It should be noticeable as readonly cell
=> 8459 - Fix cell readonly background color in dark mode

docs/CHANGELOG.md, src/components/lookup/_lookup-new.scss, src/components/lookup/_lookup.scss
This PR fixes the close icon button in lookup modal in RTL.
Closes #8303 
- Go to http://localhost:4000/components/lookup/example-index.html?theme=new&mode=light&colors=default&locale=ar-SA
- Open lookup in `Products`
- Type anything in search bar
- Close icon should be aligned correctly
=> 8303 - Fix close icon lookup modal in RTL

docs/CHANGELOG.md, src/components/spinbox/_spinbox.scss
This PR fixes the number/value position in RTL mode.
Closes #8307
- Go to http://localhost:4000/components/spinbox/example-index.html?theme=new&mode=light&colors=default&locale=ar-SA
- Click +/- or enter number
- Number should center
=> 8307 - Fix spinbox value position in RTL mode

docs/CHANGELOG.md, src/components/datepicker/_datepicker.scss
This PR Fixes datepicker's popover footer button position in RTL mode.
Closes #8400
Closes #8304
- Go to http://localhost:4000/components/datepicker/example-index.html?locale=ar-SA
- Open a datepicker
- Check the footer button
- It should align correctly
=> 8400 - Fix datepicker popover footer button position in RTL mode

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
This PR fixes the text moves upward when the cell is focused.
Closes #8472 
- Go to http://localhost:4000/components/datagrid/example-books.html?theme=new&mode=light&colors=default
- Click any cell from `Book Currency` to `Deprecation History`
- Text should not move
=> 8472 - Fix text moves upward when focused

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This pull request will a bug unable to use the left/right arrow keys on the text in an editable cell.
Closes https://github.com/infor-design/enterprise/issues/8457
- Go to http://localhost:4000/components/datagrid/example-editable?theme=uplift&variant=light&layout=embedded
- Click on an editable cell (e.g. Assemble Paint)
- Set the cursor at letter "m" in the word "Assemble" and press the left arrow key.
- Verify it sets focus on the left cell beside the editable cell.
- Press the right arrow key to go back to the editable cell.
- Press …
=> 8457 - Datagrid Editable Left Right Transfer Cells

app/views/components/cards/test-datagrid-custom-height.html, app/views/components/cards/test-datagrid.html, docs/CHANGELOG.md, package-lock.json, src/components/cards/_cards.scss, src/components/cards/cards.js, src/components/datagrid/_datagrid.scss, src/components/pager/_pager-new.scss, src/components/pager/pager.js
Changed the pager to not append itself to the footer when a card contains a pager. This gives greater control.
Fixes #8496
- go to http://localhost:4000/components/cards/test-datagrid.html
- card should scroll and pager should be fixed below in a nice size
- go to http://localhost:4000/components/cards/test-datagrid-custom-height.html and see it with a custom size
- test http://localhost:4000/components/listview/test-paging-pagesize.html pager should now be visible
- test http://localhost:4000/components/listview/test-listview-set-page.html
=> 8496 - Change card datagrid pager logic

app/views/components/modal/test-nested.html, docs/CHANGELOG.md, src/components/modal/modal.manager.js
Should only check active modals when close api is called
Closes https://github.com/infor-design/enterprise-ng/issues/1639
- Go to: http://localhost:4000/components/modal/test-nested.html
- Open modal 
- Open Tabs modal
- Press escape key
- Only Tabs modal should close
=> NG1639 - Fixed a bug where parent modal closes instead of currently active modal when pressing the escape key

app/views/components/datagrid/example-editable.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Removed escaping HTML for cell nodes. Any special character and tag will be accepted as is.
Closes #8516 
- Update a cell with `related[BALMAS1("TX60:\{IndexList_Items.TX60}")]`
- Should accept it as is
- Check console logs
- Object printed should have the same values
=> 8516 - Removed escaping HTML for cell nodes

app/views/components/images/example-avatar.html, app/views/components/module-nav/example-icon.html, app/views/components/module-nav/example-set-role-from-data.html, docs/CHANGELOG.md, src/components/images/_images.scss
Previously when adding new avatar css we accidentally made the default not round. Reverted this and will patch to 4.92.0
Fixes #8539 
- go to http://localhost:4000/components/images/example-avatar
- the first two should not be round
=> 8539 - Make avatar not round

app/views/components/tabs/example-activated-event.html, docs/CHANGELOG.md, src/components/tabs/tabs.js
This pull request will fix `beforeactivated` event not cancelling activation of tabs properly.
Closes https://github.com/infor-design/enterprise-ng/issues/1578
- Go to http://localhost:4000/components/tabs/example-activated-event.html
- The vetoable tabs are `Opportunities` and `Notes`
- Try to click these two, it should block tab activation
=> NG1578 - Tabs Vetoable

docs/CHANGELOG.md, src/components/about/_about.scss, src/components/about/about.js, src/components/locale/cultures/en-US.js, src/utils/utils.js
Adds a copy button to the about page.
Fixes #8438 
- go to http://localhost:4000/components/about/example-index.html
- click the button to open the moda
- click the button at the bottom to copy to clipboard
- paste the output in a file to check it
=> 8438 - Added copy to clipboard button to about page

docs/CHANGELOG.md, src/components/datagrid/_datagrid-new.scss, src/components/datagrid/_datagrid.scss, src/components/dropdown/_dropdown-new.scss
Fixed search icon misalignment in dropdown cells
Closes #8515 
- Check dropdown cell (Action) in all sizes. Type on cell to show search icon
=> 8515 - Fixed search icon misalignment in dropdown cells

docs/CHANGELOG.md, src/components/tabs/tabs.js
Fixes a bug introduced with a recent fix. The problem was the new logic when it related to disabled items.
Fixes #8596 
- go to http://localhost:4000/components/tabs-vertical/example-index.html#kpis
- open device tools and pick a mobile device
- try to use the overflow menu -> should work now and have no errors in the console
=> 8596 - Fix tab errors

docs/CHANGELOG.md, src/components/homepage/homepage.js
When home page has no widgets and you resize an error occured. This is a fix for this.
cc @anhallbe (does this need a patch on 4.94?)
Fixes #8611 
- retest https://github.com/infor-design/enterprise/pull/8544
- go to http://localhost:4000/components/homepage/test-add-remove-widget.html
- remove all widgets with the remove button
- check the console
- resize the page
- should be no errors with or without widgets
=> 8611 - Add fix for error with no widgets

app/views/components/button/example-index.html, docs/CHANGELOG.md, src/components/button/button.js
Fixes a bug that `startAnimation` times out after 5 seconds.
Fixes #8541 
- go to http://localhost:4000/components/button/example-index.html
- click the gen AI button
- animation should start and never stop in the example (unless you call the following function)
- call `$('#btn-generate-ai-1').data('button').stopAnimation()` in the console to stop it
=> 8541 - Fix uneeded timeouts on gen-ai

app/views/components/header/example-wc-breadcrumb.html, app/views/components/header/test-no-personalize.html, app/views/includes/head.html, docs/CHANGELOG.md, src/components/header/_header.scss, src/components/personalize/personalize.js, src/components/personalize/personalize.styles.js, src/core/_config.scss, src/themes/theme-classic-contrast.scss, src/themes/theme-classic-dark.scss, src/themes/theme-new-contrast.scss, src/themes/theme-new-dark.scss
Added a fix to support using new ids-breadcrumb inside of legacy header. Also found that if you take is-personalization class off 
Closes https://github.com/infor-design/enterprise-wc/issues/2178
- go to http://localhost:4000/components/header/test-no-personalize.html -> should be alabaster
- go to http://localhost:4000/components/header/example-wc-breadcrumb.html
- a) dropdown should open when resized and show overflowed items
- b) should be centered in the header
- c) go to http://localhost:4000/components/header/example-wc-breadcrumb.html?colors=1C86EF and try states and personalization …
=> 2178 - Add support for ids-breadcrumb

app/views/components/datagrid/test-tree-serializer.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js, src/components/datagrid/readme.md
Fixed and documented the `serialize` callback in datagrid which was accidentally removed.
Fixes #8663
- go to http://localhost:4000/components/datagrid/test-tree-serializer.html
- edit the last column (description)
- anything you edit will be changed to upper case
=> 8663 - Fix serializer function for tree datagrid

docs/CHANGELOG.md, src/components/homepage/homepage.js
This PR fixes a bug where the homepage contents gets cutoff at the bottom of the page.
Closes #8640
- Scroll at the bottom of the page
- Cards/Widgets at the bottom should not cut off
- Test on resize as well
=> 8640 - Fix incorrect height of homepage

docs/CHANGELOG.md, src/components/monthview/monthview.js
This pull request will fix focus date not properly assigned when calendar is used as datepicker.
Closes https://github.com/infor-design/enterprise/issues/8585
- Go to http://localhost:4000/components/datepicker/example-legend.html
- Open datepicker and Click on date with legend
- Open datepicker again
- Use arrow key to navigate. (i.e., left key)
=> 8585 - Datepicker Arrow Keys not working properly

app/views/components/datagrid/test-addrow-alternate.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This pull request will fix add row not triggering after cell commit.
Closes https://github.com/infor-design/enterprise/issues/8624
- Go to http://localhost:4000/components/datagrid/test-addrow-alternate.html
- Add set of records until you have to scroll to see `Add Row` button (Refer the video from original ticket)
- Then click Add and edit cell `Product Name`. Add Anything.
- Use the scroll of the mouse to the `Add Row` and keep cell in edit mode.
- Click the `Add Row` again.
- Should have another row next to the last row below
**Included …
=> 8624 - Add Row Alternate

docs/CHANGELOG.md, src/components/popupmenu/popupmenu.js
This pull request will fix autocomplete not properly highlighted on key down.
Closes https://github.com/infor-design/enterprise/issues/8618
- Go to http://localhost:4000/components/autocomplete/example-index.html
- In the input field, type "ne" and wait for the results to appear.
- Hit the down arrow to nav down the list (notice the highlighted record is BLUE and FOCUS remains in the input field, which is correct behavior)
- Start over (clear the field or refresh the page)
- In the input field, type "ne" and WAIT for the results to appear …
=> 8618 - Autocomplete Keydown

app/views/components/bar-stacked/test-many-records.html, app/views/components/column-stacked/test-many-records.html, docs/CHANGELOG.md, src/components/charts/charts.js
This pull request will fix an error encountered when having many records inside the graph.
Closes https://github.com/infor-design/enterprise-ng/issues/1675
Related #8367 
- Go to http://localhost:4000/components/bar-stacked/test-many-records.html
- See no errors
- Go to http://localhost:4000/components/column-stacked/test-many-records.html
- See no errors
=> NG1675 - BarStacked/ColumnStacked Many Records

src/components/applicationmenu/_applicationmenu-new.scss, src/components/applicationmenu/_applicationmenu.scss, src/components/button/_button-new.scss, src/components/module-nav/module-nav.accordion.scss, src/themes/theme-classic-contrast.scss
I found the hover state on app menu buttons looked bad.
Fixes https://github.com/infor-design/enterprise/issues/8707
- go to http://localhost:4000/components/applicationmenu/example-filterable.html
- open app menu
- hover all buttons in it
- type in search and hover the x
- on http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html hover the buttons
=> Chore: Fix app menu buttons

app/views/components/dropdown/test-field-tag.html, docs/CHANGELOG.md, src/components/dropdown/_dropdown-new.scss, src/components/dropdown/_dropdown.scss
Fixed dropdown height when showTags is set to true
Closes #8566 
- Go to: http://localhost:4000/components/dropdown/test-field-tag.html
- Height should be the same for both dropdowns
=> 8566 - Fixed dropdown height when showTags is set to true

docs/CHANGELOG.md, src/components/popupmenu/_popupmenu.scss
Z-index for app menu on mobile is 7001, so updated z-index for popupmenu
Closes #8582 
- In mobile, go to: http://localhost:4000/components/applicationmenu/example-menubutton.html
- Click on Add Item
- Popup should be in front
=> 8582 - Fixed bug on popupmenu showing behind app menu on mobile

app/views/components/lookup/test-beforeshow.html, docs/CHANGELOG.md, src/components/lookup/lookup.js
When you set up a tooltip in a lookup, it does not show after selecting an item or after closing the lookup modal. There is a method for setting up a tooltip that is only intended for multiple selections in a lookup. This also affects the `beforeShow` setting, causing it to be called when hovering over the input field. This PR fixes those issues.
Closes https://github.com/infor-design/enterprise-ng/issues/1646
1. Pull this branch, build, and run the app.
2. Go to [http://localhost:4000/components/lookup/test-beforeshow.html](http://localhost:4000/components/lookup/test-beforeshow.html).
3. …
=> NG1646 - fix tooltip not showing after selecting item in lookup

app/views/components/datagrid/test-frozen-cell-shift.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
Removes a 9 year old style fix that was probably there for IE 8/9/10. To solve an issue with the cell collapsing
Fixes #8728 
- go to http://localhost:4000/components/datagrid/test-frozen-cell-shift
- click in the second cell and edit - should look normal
- test editing on http://localhost:4000/components/datagrid/example-editable.html on all 4 row heights and see it looks normal as well
=> 8728 - Add fix for editing frozen columns and one column

app/views/components/module-nav/test-six-columns.html, docs/CHANGELOG.md, src/components/grid/_grid.scss
Looking into it, this was more an issue on responsive width. If you put a similar setup on a page without the module nav (like in IDS stackblitz) or without the module nav expanded by default (like in IDS NG stackblitz), this bug doesn't appear as the expected behavior is that the width is automatically adjusted to avoid that squished appearance. 
In so far, the bug only appeared when a module nav is present and when its expanded. If this isn't the case, comments will be appreciated and preferably a more detailed example page. 
Closes #8485 
- Go …
=> 8485. Adjusted width

docs/CHANGELOG.md, src/components/tabs/tabs.js
This PR fixes the focus state (border bottom) being cut off in horizontal tabs. Adjusted the height by 1px when the focus state is on a tab that is not selected.
Closes #8644 
- Go to http://localhost:4000/components/personalize/example-form-landmark.html
- Select a tab
- Then press left or right key to focus on other tab
- The border bottom of focus state should be visible
=> 8644 - Fix focus state border bottom being cut off

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, src/components/dropdown/dropdown.js
This pull request will fix dropdown keys not properly triggering when using keyboard.
Closes https://github.com/infor-design/enterprise/issues/8745
- Go to http://localhost:4000/components/datagrid/example-filter.html
- Place focus in Product Name cell on the filter row
- Hit the Tab key to tab into Activity cell on the filter row
- Hit the Enter or Space Bar key to open the dropdown
- Hit the Up/Down keys to navigate the options in the dropdown
=> 8745 - Datagrid Dropdown Filter Keys

docs/CHANGELOG.md, src/components/popupmenu/popupmenu.js
Added check on when to close popupmenu
Closes #8637 
- Go to: http://localhost:4000/components/contextmenu/example-index.html
- Right click on field
- Right click again
- Popupmenu should appear on where pointer is
=> 8637 - Fixed bug on popupmenu not opening on second right click

docs/CHANGELOG.md, src/components/accordion/accordion.js, src/components/module-nav/module-nav.js
Save selected element in module nav then added check in accordion if it should select latest expanded header or not
Closes #8527 
- Go to: http://localhost:4000/components/module-nav/example-no-dropdown-search.html
- Open module nav
- Expand two headers
- Select a label
- Close module nav
- Open module nav
- Label should still be selected
=> 8527. Fixed module nav refreshing selected in accordion when closing then opening

app/views/components/datagrid/test-focusout-lookup.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
The error occurs when updated is called, specifically when render is called (it might be that the dropdown element is deleted and that's when the undefined exception happens). If rendering needs to be done, it might be better to do it after the cellchange event.
Closes https://github.com/infor-design/enterprise-ng/issues/1644
- Go to: http://localhost:4000/components/datagrid/test-focusout-lookup.html
- Add new row
- Select a Product Id
- Go to Action dropdown after
- No error should appear in console
=> NG1644 - Fixed an error that occurred when clicking on a dropdown cell

docs/CHANGELOG.md, src/components/calendar/_calendar.scss
This pull request will fix calendar event popup render in mobile view.
Closes https://github.com/infor-design/enterprise/issues/8675
- Go to http://localhost:4000/components/calendar/test-start-end-hour.html
- Toggle mobile view
- Click on any events
=> 8675 - Calendar Event Popup Mobile View

app/views/components/datagrid/test-filter-with-default-operator.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js, src/components/tooltip/tooltip.js
Adds a fix to refresh possibly cached tooltip in prod mode. (Hard to test) @claudenbach can you test on your end.
Fixes #8773 
- go to http://localhost:4000/components/datagrid/test-filter-with-default-operator.html
- hover each button the filter row and see that the tooltip matches
- select different items and make sure it changes for the tooltip
- try another language http://localhost:4000/components/datagrid/test-filter-with-default-operator.html?locale=de-DE
=> 8773 - Add fix to refresh tooltip

app/views/components/tabs/test-prevent-dismissible.html, docs/CHANGELOG.md
Updated example page. The issue was the check, it would have never returned false. The element passed on the beforeclose event is already the hyperlink and not the list item, so finding the child hyperlink leads to nothing (and therefore leads to undefined which leads to the if statement on the example page never being executed).
> Add ability to disable the x button
> Check the dismissible attribute is working (this one hides the x)
I'm also not sure if disabling /hidingthe close icon when a tag has the "dismissible" class is what it should be for because the "Dismissible" tag has the same class in the example
https://github.com/infor-design/enterprise/blob/main/app/views/components/tabs/t …
=> NG1697 - Fixed example page for disabling dismissible tags

app/views/components/week-view/example-card.html, app/views/components/week-view/example-stacked.html, docs/CHANGELOG.md, src/components/week-view/week-view.js
Added new settings for overnight days
Closes #8630 
- Pull this branch, build and run the branch
- Go to: http://localhost:4000/components/week-view/example-stacked.html
- Overnight should only be in one day column
- Go to: http://localhost:4000/components/week-view/example-card.html
- On "Stacked Week View"
- Overnight should show in both days
- Label should be "Vacation"
- On "Stacked Week View (Hidden Toolbar/Footer)"
- Should have no Overnight label
- Should only show in one day
=> 8630 - Added new settings for overnight days

docs/CHANGELOG.md, src/components/grid/_grid.scss
Refixes the issue https://github.com/infor-design/enterprise/pull/8738 with a different fix that doesnt break the grid.
Fixes #8828
- go to http://localhost:4000/components/module-nav/test-six-columns.html?colors=fff
- resize the page around the size of the attached screen shot and smaller/bigger and make sure the fields dont touch
- go to http://localhost:4000/components/module-nav/example-index.html?colors=fff
- and inspect the .columns element and make sure the module nav doesnt add styles to it
**Screen Shots**
=> 8828 - Refix grid issue

app/views/components/datagrid/test-grid-input-lost-focus.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This pull request will fix a bug where button gets focus always during editing of lookup field.
Closes https://github.com/infor-design/enterprise/issues/8758
- Go to http://localhost:4000/components/datagrid/test-grid-input-lost-focus.html
- Input `333` to the `Product Name` grid and then click the current input area again and again.
- Focus should still be in the input box not in the button
=> 8758 - Datagrid Focus With Button (Lookup)

docs/CHANGELOG.md
Note: See commit diff https://github.com/infor-design/enterprise/commit/82b803a5e89e61d4b6df0e45470f029778827aae
Fixes #8817
- go to http://localhost:4000/components/module-nav/example-datagrid.html?colors=fff
- make page tablet size
- open menu to collapsed mode
- make sure the headers in the grid dont stick out
- NOTE: You can still click out on the overlay  to close it
=> 8817 - Fixed zindex on module nav

app/views/components/datagrid/test-filter-with-default-operator.html, src/components/datagrid/datagrid.js
Fixes an additional case on #8773 noted when changing the filter row button with the API
Fixes #8773
- go to http://localhost:4000/components/datagrid/test-filter-with-default-operator.html
- hover the filter buttons and make sure the tooltip is correct and matches
- click the "Set Filter Conditions" button to set it with an API
- see that the filter condition and tooltip are both updated
- try in a language http://localhost:4000/components/datagrid/test-filter-with-default-operator.html?locale=de-DE
No change log as added for the original issue
=> 8773 - Add fix for new case on missing tooltip

app/views/components/calendar/example-only-calendar.html, docs/CHANGELOG.md, src/components/calendar/calendar.js, src/components/monthview/monthview.js
Fixed selectDay being called twice on clicking events
Closes #8769 
I'm not sure how to make an example page for this. What I did was add a console log in selectDay itself to see how many times it was called, the ticket doesn't give a specific example (no stackblitz or similar) too.
I used this page to test it: http://localhost:4000/components/calendar/example-only-calendar.html
Change the month and year to August 2018 for events that overflow in a day and have the +2 More tag appear
=> 8769 - Fixed selectDay being called twice on clicking events

app/views/components/datagrid/example-editable.html, app/views/components/datagrid/test-ellipsis.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss
Fixed asterisk being cut off when textOverflow is set to ellipsis
Closes https://github.com/infor-design/enterprise-ng/issues/1651
- Go to
- http://localhost:4000/components/datagrid/example-editable.html
- http://localhost:4000/components/datagrid/test-ellipsis.html
- Required columns should have asterisk (*) fully viewable
- Minimize columns
- Ellipsis should still appear
=> NG1651 - Fixed asterisk being cut off when textOverflow is set to ellipsis

src/components/datagrid/datagrid.js
Explain the details for making this change. What existing problem does the pull request solve?
On commitCellEditUtil function:
https://github.com/infor-design/enterprise/pull/8838 combined with https://github.com/infor-design/enterprise/pull/8833 has issues where we encountered errors in this.actualRowIndex(cellNode.parent()) being NaN. This is a proposed PR to mitigate having console log errors.
Related github/jira issue (required):
https://inforwiki.atlassian.net/browse/MUA-14253
Fixes https://github.com/infor-design/enterprise/issues/8850
Steps necessary to review your pull request (required):
test scenarios:
In M3 Angular application:
Original Issue:
Open MMS300 Application -> Go to Data with valid editable cell.
Edit First Editable cell on first row then edit second row as well on …
=> Chore: Fix incorrect updates in commitCellEditUtil - Additional changes

docs/CHANGELOG.md, src/components/switch/_switch.scss
Fixes the switch so you can click the label. Also updated the text to be more centered
Fixes #8896
- go to http://localhost:4000/components/switch/example-index.html
- click both the label and the switch -> should now work in both cases
=> 8896 - Added fix for switch click event

app/views/components/mask/test-allow-trailing-decimals.html, docs/CHANGELOG.md, src/components/mask/mask-input.js, src/components/mask/masks.js
This pull request will add setting `allowTrailingDecimalZeros` to always display decimals in input mask.
Closes https://github.com/infor-design/enterprise-ng/issues/1715
- Go to http://localhost:4000/components/mask/test-allow-trailing-decimals.html
- Try to put a number in it.
=> NG1715 - Allow Trailing Decimal Zeros

docs/CHANGELOG.md, src/components/switch/_switch.scss
Recent fixes broke the layout of the switch in the personalization dialog.
Fixes #8913 
- go to http://localhost:4000/components/datagrid/example-index.html
- click ...
- open personalization and review the switch styles 
=> 8913 - Fix switch layout issue in Datagrid Personalization

app/views/components/cards/example-workspace-widgets.html, docs/CHANGELOG.md, src/components/button/_button-new.scss, src/components/button/_button.scss, src/components/cards/_cards-new.scss, src/components/cards/_cards.scss, src/core/_config.scss
This pull request will fix a bug where disabled button are not properly rendered in widgets.
Closes https://github.com/infor-design/enterprise/issues/8893
- Look for `Badge (5)` Widget
- See the search button is now properly disabled
=> 8893 - Widget Button Disabled

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
Updated index used to get row data on select event. Updated dataset used when unselecting rows to sync correctly (dataset used to check if a row is selected or not was different with the dataset updated when deselecting rows, which is why row couldn't be selected a second time)
Closes https://github.com/infor-design/enterprise-ng/issues/1740
- Go to: http://localhost:4000/components/datagrid/example-grouping-multiselect.html
- For row with Customer ID 7:
- Select row. Should have correct row data in console
- Deselect
- Select again. Checkbox …
=> NG1740 - Fixes on select row in group

app/views/components/datagrid/test-editable-with-inline-editor.html, docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This pull request will fix selecting issue on inline editor by adding `selectOnEdit` setting.
Closes https://github.com/infor-design/enterprise/issues/8870
- Go to http://localhost:4000/components/datagrid/test-editable-with-inline-editor.html
- Click the value inside the inline editor
- It should not be select on click
=> 8870 - Datagrid Inline Editor SelectOnEdit

app/views/components/datagrid/example-disabled-selection-checkbox.html, app/views/components/datagrid/example-index.html, app/views/components/datagrid/example-tree-disabled-selection-checkbox.html, docs/CHANGELOG.md, src/components/datagrid/_datagrid-new.scss, src/components/datagrid/datagrid.formatters.js, src/components/datagrid/datagrid.js, src/components/switch/_switch.scss
Adds to a previous issue so checkboxes can be disabled and have it work with tree view.
Fixes the example page to show dragging
Fixes https://github.com/infor-design/enterprise/issues/8915
Fixes https://github.com/infor-design/enterprise/issues/8920
Fixes https://github.com/infor-design/enterprise/issues/8925
- go to http://localhost:4000/components/datagrid/example-tree-disabled-selection-checkbox.html
- try to select the disabled rows (should not able to)
- try to click a parent row where children are disabled (child rows should not be selected)
- go to …
=> Misc - Fix child selection and demo app example

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
On calculateTextWidth, code was introduced that had selectors that were specific to M3 in PR: https://github.com/infor-design/enterprise/pull/8833. Leading to calculated text width to not run causing issues in other applications that do not have the selector in the container.
**Related github/jira issue (required)**: https://inforwiki.atlassian.net/browse/MUA-14629 / https://github.com/infor-design/enterprise/issues/8938
1) Open http://localhost:4000/components/datagrid/example-full-width.html
2) Make sure to resize the code to a size similar below:
With Fix:
=> Remove modification in calculateTextWidth that had incorrect selectors

docs/CHANGELOG.md, src/components/module-nav/module-nav.js
This pull request will fix tooltip not showing on render if set collapsed by default.
Closes https://github.com/infor-design/enterprise-ng/issues/1678
- Go to http://localhost:4000/components/module-nav/example-index.html?colors=fff
- Hover `Em`
- Tooltip should show
=> NG1678 - ModuleNav Collapsed Tooltip

docs/CHANGELOG.md, src/components/datagrid/_datagrid.scss, tests/datagrid/datagrid.spec.js
This PR adjusts the padding of detail row on different row heights.
`Normal/Large: 30px`
`Medium: 25px`
`Small: 20px`
`Extra Small: 15px`
Closes #8950
- Go to http://localhost:4000/components/datagrid/example-expandable-row.html
- Check the `datagrid-row-detail-padding` element
- Navigate to different row heights
- Normal/Large should have `30px`
- Medium should have `25px`
- Small should have `20px`
- Extra small should have: `15px`
=> 8950 - Adjust detail row padding in datagrid

docs/CHANGELOG.md, src/components/button/_button.scss, src/components/toolbar/_toolbar.scss, tests/datagrid/datagrid.spec.js
This pull request will fix datagrid hover color for contextual toolbar when a row is selected.
Closes https://github.com/infor-design/enterprise/issues/8980
- Go to http://localhost:4000/components/datagrid/example-mixed-selection.html
- Click one row for the toolbar to show up
- Hover the contextual toolbar button `Example 1`
- It should not be all white
=> 8980 - Datagrid Contextual Toolbar Hover

docs/CHANGELOG.md, src/components/datagrid/datagrid.js, tests/datagrid/datagrid.spec.js
Fixed selected filters being cleared when changing row size
Closes https://github.com/infor-design/enterprise-ng/issues/1759
- Go to: http://localhost:4000/components/datagrid/example-filter.html
- Use filters and change row height
- Filters on header should not be cleared
=> NG1759 - Fixed selected filters being cleared when changing row size

docs/CHANGELOG.md, src/components/datagrid/datagrid.js
This fixes the filterWhenTyping feature in the datagrid search, so that any input change (including backspace or cut and paste which previously did nothing) will update the search results
https://github.com/infor-design/enterprise/issues/9007
=> Update Datagrid Search on Input Change

docs/CHANGELOG.md, src/components/applicationmenu/_applicationmenu-new.scss, src/components/applicationmenu/_applicationmenu.scss, src/core/_config.scss, tests/applicationmenu/applicationmenu.spec.js
This PR updates the selected states in the application menu.
Closes #8785 
- Go to http://localhost:4000/components/applicationmenu/example-index
- Compare http://localhost:4000/components/applicationmenu/example-index to https://main.wc.design.infor.com/ids-app-menu/example.html
- Selected states should be the same as in the WC
=> 8785 - Update the new selected states in appmenu

docs/CHANGELOG.md, src/components/tabs/tabs.js, tests/toolbar/toolbar.spec.js
- Removed previous behavior where selected tab in the overflow menu will be moved to the next visible space
- Added additional check on the isTabOverflowed method as the check didn't include overflow tabs on the left (which should update the overflow menu to include left overflow tabs now)
Closes #9004 
- Go to: http://localhost:4000/components/tabs-header/example-index.html
- Select a tab in the overflow menu
- Should scroll to that tab
=> 9004 - Selected tab in overflow menu change
