infor-design/enterprise

.eslintrc.js
app/app.js
app/data.js
app/src/js/getJSONFile.js
app/src/js/getJunkDropdownData.js
docs/TESTING.md
src/components/toast/toast.js
test/components/button/button.func-spec.js
test/components/dropdown/dropdown.func-spec.js
test/components/multiselect/multiselect.func-spec.js
test/components/popupmenu/popupmenu.func-spec.js
test/protractor.browserstack.conf.js
test/protractor.conf.js

Restore Protractor functionality
* Some tests are failing because mock/junk is throwing an error on GET
```sh
Error: Cannot find module '/Users/username/project-hardcore/src/js/getJunkDropdownData'
```

Restore running of func tests, update docs

---

src/components/bar/_bar.scss
src/components/bar/bar.js
src/components/charts/charts.js

SOHO-5196 - Fixed RTL style was not working with Bar Charts
http://localhost:4000/components/bar/example-index?locale=ar-EG

SOHO-5196 - Fixed RTL style was not working with Bar Charts

---

publish/package.json

I am bumping the version so we can get 2 more manual nightly builds up to npm for testing with NG and ng-quickstart.

This is a package for today (manual "nightly" build)

---

app/app.js
app/src/js/custom-route-options.js
app/src/js/middleware/error-handler.js
app/src/js/routes/general.js
app/views/error.html
app/views/includes/header-docs.html
app/views/includes/header-openlarge.html
app/views/includes/header.html
docs/templates/hbs/partials/toc-blocks.hbs

- fixes some duplicate route matching that was happening with the general routes
- adds an option for removing the Hamburger menu from views (generally keeps it hidden)
- more demoapp code cleanup
https://jira.infor.com/browse/SOHO-7803
Build the documentation, run the demoapp and check:
- http://localhost:4000/components/ (should be documentation)
- http://localhost:4000/patterns/ (should redirect to the list)
- http://localhost:4000/kitchen-sink (should load completely, and shouldn't cause any stack traces containing "Error: Can't set headers after they are sent." messages.
Also, no component …

SOHO-7803 demoapp paths

---

publish/package.json

We liked @tmcconechy 's idea to use the 4 digit year so its more "date recognizable"

Update semver to reflect better date syntax

---

package-lock.json
package.json
test/components/button/button.e2e-spec.js
test/components/dropdown/dropdown.e2e-spec.js
test/components/listview/listview.e2e-spec.js
test/components/multiselect/multiselect.e2e-spec.js
test/components/popupmenu/popupmenu.e2e-spec.js
test/helpers/axe-page-objects.js
test/helpers/default-axe-options.js
test/kitchen-sink.e2e-spec.js
test/protractor.ci.conf.js
test/protractor.conf.js

Reduces accessibility tests call to a 1 liner, upgrades dependencies, specify logging levels, and unskips failing WCAG2AA tests for fixing.
https://jira.infor.com/browse/SOHO-7938
https://jira.infor.com/browse/SOHO-7937
https://jira.infor.com/browse/SOHO-7331
`npm run e2e:local`

SOHO-7331 - Use page object for axe, unskip WCAG2* tests

---

src/components/modal/modal.js
test/components/modal/modal.e2e-spec.js

Add some basic tests for the modal component, fix aria typo
https://jira.infor.com/browse/SOHO-7331
Isolate tests, and run `npm run e2e:local`

Fix aria-labelledby typo, add base modal tests

---

.travis.yml
scripts/bump-nightly.sh
scripts/publish-nightly.sh

Publishes a `.YYYYMMDD` pre-release from the current version in `package.json` when triggered nightly by cron in Travis.

Build nightlies

---

.travis.yml
scripts/publish-nightly.sh

Another attempt to get the nightly dev build going. Simple check to `npmjs.com` first to see if a version of the same name has already been published.

Build nightly

---

scripts/publish-nightly.sh

`npm install` from within `deploy` script.

npm install again

---

scripts/publish-nightly.sh

Try a better way of authenticating with `npm`.

Set npm auth token

---

components/button/_button.scss
components/button/button.js
components/popupmenu/_popupmenu.scss
components/popupmenu/test-empty-items.html
components/toolbar/test-tooltips-populating-more-actions.html
components/toolbar/toolbar.js
package.json
publish/package.json

Patching soho7942 for landmark on to a 4.6.1
https://jira.infor.com/browse/SOHO-7942
Steps on https://jira.infor.com/browse/SOHO-7942
Compare sources
NOTE: @clepore please run the script to sync it back to BB

Merging Fix on SOHO-7942 onto 4.6.1

---

.travis.yml

A nightly build like [this](https://travis-ci.com/infor-design/enterprise/builds/73768298) generates extensive logs when trying to clean up after deploy and can risk breaking the build of the log grows too big.

Skip cleanup to fix logging

---

app/src/js/routes/general.js
app/src/js/utils.js
docs/templates/hbs/partials/toc-blocks.hbs

The demoapp was very broken for developers on Windows after the changes made for SOHO-7803.  These changes should resolve that problem and provide support for all platforms
https://jira.infor.com/browse/SOHO-7803
- pull the branch on a Windows machine, npm install, and attempt to run the demoapp
- hit various URLS such as http://localhost:4000/components and http://localhost:4000/components/datagrid/example-index

Fix demoapp paths for Windows support

---

src/components/alerts/readme.md

Removes link to Badges example in front matter and replaces with link in body copy.
https://github.com/infor-design/website/issues/540
Closes infor-design/website#540

Update Alerts docs

---

src/components/datagrid/datagrid.js
src/components/lookup/lookup.js

Fixed bug when selecting multiple times on lookup.
soho-7971
http://localhost:4000/components/lookup/example-index.html
- reopen and select repeatedly

Fixed errors when reopening lookup with pager.

---

src/components/mask/mask-input.js

Fixes an error noted by a user since the setting is wrong.

Fixed wrong setting name noted on soho-7982

---

app/views/components/validation/test-alert-types.html
app/views/components/validation/test-message-types-landmark.html
src/components/input/_input.scss
src/components/validation/validation.jquery.js
src/components/validation/validation.js
src/components/validation/validator.js

http://localhost:4000/components/validation/test-message-types-landmark

SOHO-7225 - Added support to alert type icon with Validation

---

src/components/initialize/initialize.js

Properly included the JS-based scaffolding for Patterns in the initializer (wasn't working after we split these into separate index files).  We're now pulling in `components.jquery.js` and `patterns.jquery.js` in the initializer.
I was notified of this one by @pwpatton
- run `npx grunt` to build
- run `npm start` to get the demoapp running
- open any demoapp page (http://localhost:4000/kitchen-sink), open a dev tools console, and check that the reference to `$.fn.listdetail` is a function.

Properly import pattern JS scaffolding

---

app/views/components/validation/test-message-types.html

Fixed some script errors and CSP errors found in the sample we just pushed for SOHO-7225
https://jira.infor.com/browse/SOHO-7225
Check for JS console errors on http://localhost:4000/components/validation/test-message-types.html

fixed CSP errors in the sample for soho-7225

---

.travis.yml

Adds a clearer explanation of what's going on with Travis.

Adds comments to travis config

---

app/app.js
app/src/js/middleware/basepath-handler.js
app/src/js/routes/general.js
app/src/sass/_directory.scss
docs/INDEX.md
scripts/configs/clean.js
src/components/locale/cultures/ar-EG.js

Fix components link
Fix assets link on https
Minor text and color changes
NA
Once merged and deployed test
https://master-enterprise.demo.design.infor.com/
https://master-enterprise.demo.design.infor.com/components

Demoapp fixes

---

app/views/components/hierarchy/example-lazy-load.html
app/views/components/hierarchy/example-single.html

QA raised an issue on an earlier fix pushing an update.
soho-7992
http://localhost:4000/components/hierarchy/example-single.html
- expand last node (this was requiring an extra click before)

Fixed follow up QA issue with sample 7992

---

app/views/components/lookup/test-delimiter.html
src/components/datagrid/datagrid.js
src/components/listview/listview.js
src/components/lookup/lookup.js

- Added new delimiter option in settings
- http://localhost:4000/components/lookup/test-delimiter.html
- Page should still be working correctly after delimiter option is set
- Upon selected items in lookup, selected values should now be separated by '/' instead of ','

Soho 4695 make lookup delimiter configurable

---

app/src/js/middleware/option-handler.js

Adds CSP exceptions to allow proxy of app in `design.infor.com`.

Adds exceptions for google fonts and *.design.infor.com

---

src/components/datagrid/datagrid.js

http://localhost:4000/components/datagrid/example-expandable-row

SOHO-7861 - Fixed error was causing while click on +/- icon Datagrid

---

app/views/components/popupmenu/example-icons.html
src/components/popupmenu/popupmenu.js
test/components/popupmenu/popupmenu.func-spec.js

Padding was off on popups with icons
soho-8006
Compare
http://localhost:4000/components/popupmenu/example-index.html
to
http://localhost:4000/components/popupmenu/example-icons.html

Added fix and test for soho-8006

---

app/views/components/datepicker/test-with-time-cs-CZ.html
src/components/validation/validation.js

http://localhost:4000/components/datepicker/test-with-time-cs-CZ

SOHO-7772 - Fixed disabled dates were not working cs-CZ and Datepicker

---

app/data/compressors.js
app/views/components/datagrid/example-filter.html
app/views/components/datagrid/example-grouping.html
app/views/components/datagrid/example-nested-objects.html
app/views/components/datagrid/example-paging.html
src/components/datagrid/datagrid.js

Fixed sorting on sample app soho-8013
Fixed click event data on grouped grid soho-8023
Fixed example that showed resize issues soho-8019
Clean up examples
soho-8013 soho-8023 and soho-8019
Follow the steps on those 3 issues effectively testing:
http://localhost:4000/components/datagrid/example-paging-indeterminate.html
http://localhost:4000/components/datagrid/example-nested-objects.html
http://localhost:4000/components/datagrid/example-grouping.html (watch console data when drilling)

Qa datagrid fixes

---

README.md
docs/INDEX.md
scripts/deploy-documentation.js

Some informative updates with the deploy script

---

scripts/publish-nightly.sh

The changes in infor-design/enterprise#84 broke the nightly script. This fixes it.
infor-design/enterprise#84

Fix package.json location in nightly script

---

ids-enterprise/package.json

We never updated this `package.json` with the appropriate license so it's still showing incorrectly on https://www.npmjs.com/package/ids-enterprise

Updates package.json to proper license

---

ids-enterprise/package.json

Same as infor-design/enterprise#106, just a patch on the release branch.

Update npm license reference in release branch

---

app/views/components/grid/example-nesting-no-margins.html
src/components/grid/_grid.scss

Added a no-margins class for better 1 level grid nesting.
SOHO-7495
http://localhost:4000/components/grid/example-nesting-no-margins.html
http://localhost:4000/components/grid/example-index.html
- test these pages at all 3 sizes

Soho 7495 grid no margins

---

app/data/nav-items.js
app/src/js/middleware/option-handler.js
package.json

Fixed Csp Issue
Fixed issue on accordion sample page
Add watch to npm command list
Fixed sample page:
http://localhost:4000/components/accordion/example-ajax.html
https://jira.infor.com/browse/SOHO-8046

Added watch command

---

src/patterns/stepprocess/stepprocess.js

allow callOnBeforeSelect on last step

---

scripts/jenkins-deploy.sh

Update the jenkins script to use the urls and PW that Artem just set up.

Update jenkins u/p and url

---

test/components/listview/listview-api-multiselect.func-spec.js
test/components/locale/locale.func-spec.js

One test failed which did not run on (non EST) timezones
One skipped test added. Left the final last skipped test.
Run functional tests

Cleanup some tests

---

src/components/hierarchy/hierarchy.js
yarn.lock

> Explain the **details** for making this change. What existing problem does the pull request solve? 
Hierarchy paging example throws an error when expanding child nodes.
`ERROR TypeError: Cannot read property 'children' of undefined
at Hierarchy.isSingleChildWithChildren (sohoxi.js:35754)`
Also added event info for paging forward.
1. To reproduce run Angular components wrapper with the latest. 
2. Navigate to http://localhost:4203/hierarchy-paging
3. Expand node. Notice the error mentioned above is thrown in the console.
4. Add change from PR, the error should go away and the example will work as expected.

Safety check for isSingleChildWithChildren

---

app/views/components/datagrid/example-editable.html

- Updated the settings to not include the "source" option
- Source option is being validated on the data grid component and "function() {}" is still considered true
- http://localhost:4000/components/datagrid/example-editable.html
- Pager should be working fine now

SOHO-8016 Fixed issue regarding pager in datagrid

---

app/data/turkish.json
app/views/components/autocomplete/test-turkish-filters.html

A pre-existing test was failing due to a missing data route, which most likely went missing during 4.7.0's demoapp reorganization
https://jira.infor.com/browse/SOHO-8095
- open http://localhost:4000/api/turkish
- ensure the route passes back data
AND
- open http://localhost:4000/components/autocomplete/test-turkish-filters.html
- type any letter into the searchfield
- ensure a list populates with any content
closes SOHO-8095

SOHO-8095 - Fixed API data route for Turkish filters test (against master)

---

.travis.yml
README.md
test/protractor.ci.bs.conf.js

Add back cron nightly test on deployed master branch, adds Browserstack status badge to README.md
https://jira.infor.com/browse/SOHO-8096
This should have ran last night on branch check? If not, check tonight? Check badge, go to badge status page. I ran it around 5pm manually.
https://www.browserstack.com/automate/public-build/MmgvZ2tsa3pydTRlTklvNG9HZGYvMVlwdWRzWklWVWtXNEFFeVJXSG1raz0tLTZuR0J1Nllxd1pOTVJKaE4zRFVYUkE9PQ==--628ff7dc2ecde8982f3a89ad70cdcf252bdd8fba

SOHO-8096 - Restore nightly e2e BrowserStack

---

app/views/components/counts/example-object-count.html
app/views/components/datagrid/test-on-tab.html
app/views/components/datagrid/test-on-vertical-tab.html
app/views/components/datagrid/test-within-tabs.html
app/views/components/datepicker/test-scrollable.html
app/views/components/form/example-labels.html
app/views/components/splitter/test-tabs.html
app/views/components/tabs-header/example-add-tab-button.html
app/views/components/tabs-header/test-contains-vertical-tabs.html
app/views/components/tabs-multi/example-index.html
app/views/components/tabs-multi/test-masthead.html
app/views/components/tabs-multi/test-side-by-side.html
app/views/components/tabs/example-activated-event.html
app/views/components/tabs/example-beforeactivate-callback.html
app/views/components/tabs/example-index.html
app/views/components/tabs/test-angular-click-trigger.html
app/views/components/tabs/test-angular-href.html
app/views/components/tabs/test-datepicker-in-panel.html
app/views/components/tabs/test-disabled-change-tab.html
app/views/components/tabs/test-separators.html
app/views/components/validation/test-error-on-tab.html
app/views/components/validation/test-manual-validation-triggers.html
app/views/examples/landmark/list-with-detail-sections.html
app/views/patterns/360-overview.html
app/views/patterns/vertical-tabs.html
app/views/tests/destroy/on-container.html
test/components/tabs/tabs.e2e-spec.js

Setup basic tests for e2e w/o QA support yet. This is just a starting point. First test to resize browser FYI.
https://jira.infor.com/browse/SOHO-8097
https://jira.infor.com/browse/SOHO-7331
After `npm start`
`npm run e2e:ci`, and deep dive with `npm run e2e:local:debug` or deeper dive with `npx -n=--inspect-brk protractor test/protractor.local.debug.conf.js
`

SOHO-7331 Basic e2e tabs test

---

app/views/components/rating/example-decimals.html
app/views/components/rating/example-readonly.html
src/components/rating/rating.js
src/components/rating/readme.md

Added support for decimals on the rating component.
https://jira.infor.com/browse/SOHO-8063
Run http://localhost:4000/components/rating/example-decimals.html
This PR was submitted by Xiuwen Gui <Xiuwen.Gui@infor.com>

Added support for decimals in rating api

---

src/components/validation/validation.js
src/components/validation/validator.js

Need to fix for the Submit Buttion Enable and Disable Validation
https://jira.infor.com/browse/SOHO-8042
http://localhost:4000/components/modal/example-validation.html
Fill up the required fields.
See if the Submit Button is now enabled.

Soho 8042 submit button validation

---

.travis.yml

Corrects Browserstack CI cron job as it was referencing the wrong script hence the resulting failing build.
Confirm script in package.json is the same as the one referenced in .travis.yml

SOHO-8061 - Correct BrowserStack CI command for cron job

---

docs/CHANGELOG.md
ids-enterprise/package.json

Use git standard template for change log, added notes for 4.7.0
SOHO-8114

Release notes

---

README.md
docs/CONTRIBUTING.md
docs/DEVELOPER.md
docs/GIT-WORKFLOW.md
docs/PUBLISH.md

Changing the documentation to refer people to submit github issues instead of Jira tickets.
n/a
n/a
n/a

Update documentation to use github issues

---

src/components/tabs/tabs.js

Fixes issue in https://jira.infor.com/browse/SOHO-7511
https://jira.infor.com/browse/SOHO-7511
In my case, I could not open a new tab which is hosting a an Angular component.

SOHO-7511: Comment out possibly no needed case

---

src/components/colorpicker/_colorpicker.scss

https://jira.infor.com/browse/SOHO-8030
http://localhost:4000/components/colorpicker/example-show-label

SOHO-8030 Fix cursor tracker showing.

---

app/views/components/field-filter/example-index.html
src/components/field-filter/_field-filter.scss
src/components/field-filter/field-filter.js

Fixing the field filter wrapper for dropdowns
[https://github.com/infor-design/enterprise/issues/179](https://github.com/infor-design/enterprise/issues/179)
Navigating to the example-index.html in field filter should now look like:
`closes #179`

Fixing field filter wrapper on dropdown fields

---

.release-it.json
docs/PUBLISH.md

Updating the publish doc and changing the release-it `dry-run` property
na
na

Updates to documentation for releasing

---

test/components/textarea/textarea.e2e-spec.js

This test failed on CI, so improved it...

Improve test for CI

---

src/components/tabs/tabs.js
test/components/tabs/tabs-api.func-spec.js
test/karma.conf.js

Add tests for the Tabs API, improves source (remove unneeded methods), add clarity to documentation
https://jira.infor.com/browse/SOHO-8097
Review code, checks have passed on CI, but check again anyways w/`npm run all-checks`

SOHO-8097 - Add Functional Tabs API tests; Improve/Correct src err & docs

---

README.md
docs/TESTING.md
test/helpers/browserstack-error-reporter.js
test/protractor.ci.bs.conf.js
test/protractor.local.bs.conf.js

It's BROWSERSTACK, not BROWSER_STACK
N/A
Proofread, update your BROWSERSTACK envs

Update testing docs

---

package-lock.json

The build failed because packages were updated, but the `package-lock.json` file wasn't. 
When travis did `npm install`, the `package-lock.json` file was updated dirtying the working directory, and therefore wouldn't publish.
n/a
[The Travis build](https://travis-ci.com/infor-design/enterprise/builds/76881216) points to [this commit](https://github.com/infor-design/enterprise/commit/a08f23257a7fb07ccbf06fefb7c850ffd78b39d6).

Packagelock broke the nightly

---

app/views/components/datagrid/test-editable-validation.html
src/components/datagrid/datagrid.js

Test page: http://localhost:4000/components/datagrid/test-editable-validation.html
Test: enter either "1" or "" into the Product ID to cause the async rule to fail.

SOHO-7943 - Async rules on a datagrid

---

src/components/initialize/initialize.js
src/components/validation/validation.jquery.js
src/components/validation/validator.js

Fixes severe performance issues.
SOHO-8155
http://localhost:4000/components/dropdown/example-validation.html
- open and close the dropdown until you get bored of it.. should be no performance issues / browser slowdown
http://localhost:4000/components/rating/example-index.html
- click stars you get bored of it.. should be no performance issues / browser slowdown
For good measure review some of these examples
http://localhost:4000/components/validation/list

Fix memory leaks / event doubling soho-8155

---

package-lock.json
package.json
test/components/locale/locale.func-spec.js

Fix warnings
Bump karma version due to https://github.com/karma-runner/karma/issues/3052
NA
npm run test

Bump karma

---

src/components/locale/locale.js

Fixes failed tests on https://github.com/infor-design/enterprise-ng/pull/111

Fix the build errors

---

docs/PUBLISH.md

A code fence was claiming `yml` syntax, but `yml` is just an extension. The real language is `yaml`.
Fixes https://github.com/infor-design/enterprise/issues/215
1. `node ./scripts/deploy-documentation.js --test-mode` (use test-mode to make it faster for this instance)
1. Builds as described w/o errors.

Markdown code fences need language specified as "yaml"

---

app/views/components/datagrid/test-editable-onkeydown.html
src/components/datagrid/datagrid.js

- Added onKeyDown setting
- Enabled firing of other key down events via onKeyDown setting
- http://localhost:4000/components/datagrid/test-editable-onkeydown.html
- Click on editable cell
- Hit tab button
- There should be a log in console and currently selected editable cell should not be unselected

SOHO-8128 Added onKeyDown setting

---

package-lock.json
package.json
src/components/colors/_colorpalette.scss
src/core/_config.scss

Start using tokens (as sass) inside of Enterprise's variables. You will notice that some variables were _completely removed_, that is because there was an exact token equivalent.
https://github.com/infor-design/design-system/issues/158
1. `npm start`
1. Verify
-  It should build successfully
- Make sure everything looks as it always did
1.  Discuss in slack - We do *NOT* need to merge this immediately.
1. Then follow through with changes or approval.
Doesn't fully close any issues, yet, but relates to the issue mentioned above.

Setting up and using IDS token sass

---

test/components/tabs/tabs-events.func-spec.js
test/components/tabs/tabs-settings.func-spec.js

Add coverage for events, skips `afteractivated` event test for the time being as similarly written `activate` test is not passing
#239 
`npm run functional:ci`

Add Events & Settings Tabs Functional Tests

---

test/components/tabs/tabs-header.e2e-spec.js

Provides basic checks for header tabs functionality
#239 
`npm start && npm run e2e:ci`

Add basic header tabs e2e tests

---

test/protractor.ci.bs.conf.js

https://jira.infor.com/browse/SOHO-7331
Review nightly cron, or if you must run `env TRAVIS_BUILD_NUMBER='9999' npx -n=--inspect-brk protractor test/protractor.ci.bs.conf.js` with a debugger statement in the config, and delete the build carefully
`

Remove unneeded assignment; display Travis build no. on BS

---

test/components/tabs/tabs-vertical.e2e-spec.js

Add basic coverage for vertical tabs
https://github.com/infor-design/enterprise/issues/239
Closes #239 for now
`npm start && npm run e2e:ci`

239 e2e basic tabs vertical tests

---

docs/CHANGELOG.md

Added release notes for 4.8.0

---

docs/CHANGELOG.md

The changelog had some links which 404'd. Fixed the ones that are fixable and removed the old ones that had no external data.
Closes #289

Remove invalid links

---

app/views/components/toast/test-allow-links.html
src/components/toast/toast.js

Added settings for enabling links inside the toast.
Added a file for testing.
https://github.com/infor-design/enterprise/issues/247

247 - Toast with links

---

test/components/searchfield/searchfield.e2e-spec.js

Disable flaky visual regression test as we investigate this issue

Disable Open Searchfield Visual Regression Test

---

test/components/toast/toast-api.func-spec.js
test/components/toast/toast.e2e-spec.js

API and E2E Test for Toast Component.
https://github.com/infor-design/enterprise/issues/232

232 - E2E and API Test

---

CODE_OF_CONDUCT.md
docs/TEAMS.md
src/components/dropdown/dropdown.js

- Removed personal email addresses from current commits now that its open source
- Re-formatted for consistency
n/a
- Make sure the table is consistent and all of the columns contain the proper type of data

Remove personal emails and formatting

---

package-lock.json
package.json
src/core/_config.scss
src/themes/dark-theme.scss
src/themes/high-contrast-theme.scss

Replaces sass vars with the tokens from ids-identity (soho theme, soho dark theme, soho high contrast theme) 
Tokenized vars:
- input
- buttons
- checkbox
- radio
- dropdown
- notifications (fka toast/popovers)
- alerts / pill / tag (fka badges/tags)
related to https://github.com/infor-design/design-system/issues/158
1. pull branch
2. `npm install` to get latest `ids-identity` (1.1.0)

Implement tokens

---

src/components/datagrid/datagrid.js

Fixes an alignment issue in the datagrid with a colspan function provided.
[Closes #365](https://github.com/infor-design/enterprise/issues/365)

Fix for skip columns issue.

---

src/utils/excel.js

When copy a lot of rows and pasting in the grid performance was slow.
Closes #240
See https://github.com/infor-design/enterprise/issues/240 for test document and steps

240 - Fix Grid Freezes when Copied a 1000 rows

---

app/views/components/scatterplot/example-animation.html
app/views/components/scatterplot/example-get-selected.html
app/views/components/scatterplot/example-index.html
app/views/components/scatterplot/example-selected.html
app/views/components/scatterplot/example-set-selected.html
app/views/components/scatterplot/test-empty.html
app/views/components/scatterplot/test-three-lines.html
app/views/kitchen-sink.html
src/components/charts/charts.jquery.js
src/components/charts/charts.js
src/components/line/_line.scss
src/components/line/line.js
src/components/scatterplot/readme.md
test/components/scatterplot/scatterplot-api.func-spec.js

Added scatter plot chart as per https://jira.infor.com/browse/SOHO-3182
(Basically this is a variation on bubble with shapes instead).
Closes #260 
Review Samples...
http://localhost:4000/components/scatterplot/list

Added scatter plot chart

---

app/views/components/checkboxes/example-checkbox-groups.html

- Removed dirty tracking attribute from last checkbox
- http://localhost:4000/components/checkboxes/example-checkbox-groups.html
- Uncheck last checkbox from the group
- Dirty tracking should no longer appear
Closes #301

301 Removed dirty tracking attribute from last checkbox

---

test/components/datepicker/datepicker.e2e-spec.js
test/components/dropdown/dropdown.e2e-spec.js
test/components/multiselect/multiselect.e2e-spec.js

Some tests where unstable on master. Also added a new dropdown test for selecting an element.
`npm run e2e:ci`

Fixed some tests

---

test/components/blockgrid/blockgrid.e2e-spec.js
test/components/datepicker/datepicker.e2e-spec.js

Fixes failing click test on Blockgrid
#234 
`npm run e2e:ci`

234 - Hotfix for Blockgrid E2E - Add wait for UI update then test

---

src/components/fileupload/_fileupload.scss

fixes regressiong introduced by tokens. modifies fileupload enabled to `#1a1a1a` and disabled to `#999999`
closes #485

File upload color

---

src/components/mask/mask-input.js

Pressing Backspace on http://localhost:4000/components/mask/test-new-mask-prefix-suffix.html
will remove the % sign.
https://github.com/infor-design/enterprise/issues/433

Fix for backspace percentage

---

test/components/lookup/lookup-api.func-spec.js
test/components/lookup/lookup.e2e-spec.js
test/components/toast/toast-api.func-spec.js
test/components/toast/toast.e2e-spec.js

Adding API and E2E Test for Lookup Component
Closes #344
npm run functional:ci
npm run e2e:ci

344 - Lookup API and E2E Tests

---

.travis.yml
package-lock.json
package.json
scripts/configs/sass.js
test/components/datepicker/datepicker.e2e-spec.js
test/protractor.local.bs.conf.js

Fixes security vulnerability, and updates test dependencies that restore Firefox BrowserStack local debugging, update package-lock.json for nightlies, upgrade to node 10, fix randomly failing datepicker test.

Hotfix for npm audit feedback, nightlies & update test dependencies

---

test/components/colorpicker/colorpicker.e2e-spec.js

Adds additional coverage based on feedback from QA
Relates to #333 
Isolate tests, and run `npm run e2e:local:debug` and/or `npm run e2e:ci`

333 - Colorpicker Modal e2e click tests

---

.travis.yml
package.json

Reduces build time by ~5 minutes or so by running builds in parallel 
Creates more specific logs (less scrolling)
Closes #348 
Rerun this PR build(s), view logs. Once pulled in, check CRON job logs

348 - Optimize travis builds

---

src/components/editor/editor.js
src/components/trackdirty/trackdirty.js
test/components/editor/editor.e2e-spec.js

As noted on #478 you cannot edit the html source view anymore...This fixes that and adds a test
Closes #478 
http://localhost:4000/components/editor/example-index.html
- click html
- type <b>test</b> at the bottom..
- switch back.. 
ect..

Added fix for #478 and a test

---

docs/CHANGELOG.md
docs/TEAMS.md
test/components/dropdown/dropdown.e2e-spec.js
test/components/editor/editor.e2e-spec.js
test/components/tabs/tabs-api.func-spec.js
test/components/validation/validation.e2e-spec.js

Updated release notes for the 4.9.0 release
Closes #525
Read the notes
Run the tests

Fixes #312 Added release notes

---

package-lock.json
package.json
src/components/busyindicator/_busyindicator.scss
src/components/button/_button.scss
src/components/cards/_cards.scss
src/components/datagrid/_datagrid.scss
src/components/header/_header.scss
src/components/icons/_icons.scss
src/components/modal/_modal.scss
src/components/searchfield/_searchfield-toolbar.scss
src/components/searchfield/_searchfield.scss
src/core/_config.scss
src/themes/dark-theme.scss
src/themes/high-contrast-theme.scss

- Replaces old vars with ids-identity vars. 
- Removed unneeded vars from config and used ids-identity vars in component specific `scss` files. 
- This PR only relates to buttons. (primary, default and link)
related #354
- `npm install` to get `ids-identity@v1.2.0`

Refactor old vars with corresponding tokens (buttons)

---

.travis.yml

Prevents the unneeded download, and installation of Chrome on deploy
https://travis-ci.com/infor-design/enterprise/jobs/137476350#L47
Relates to #348 
Rerun this PR build(s), view logs. Once pulled in, check CRON job logs (for a successful deploy(s), npm site)

Remove unneeded download, and installation of latest Chrome on deploy, and lint

---

app/views/components/popupmenu/example-context-menu-behavior.html

A contextmenu test page in the demoapp that linked to another page in the demoapp wasn't correctly linked.  This PR fixes the link.
Closes #507 
- Open http://localhost:4000/components/popupmenu/example-context-menu-behavior.html
- There should be two input fields present, and no blank page.

507 - Fixed bad test page routing

---

test/components/dropdown/dropdown.e2e-spec.js

Temporarily skipping dropdown tests that are failing on the nightly cron job
#570

570 - Hotfix - Skipped dropdown tests that are failing on cron

---

app/views/components/dropdown/example-updating.html

Added an id on the updatable button and change the script instead of targeting just the button, we should add a unique id to isolate to that event.
```
<button id="update-button" type="button" class="btn-secondary">Update</button>
```
```
$('#update-button').on('click', function () {
$('#updatable').empty().append('<option value="1" selected>Option One</option><option value="4" >Option Three</option>').trigger('updated');
});
```
Closes #309
Related/Deleted PR: https://github.com/infor-design/enterprise/pull/552
- Run http://localhost:4000/components/dropdown/test-update.html
- Select …

309 - fixes updatable dropdown value when changing theme

---

.eslintrc.js
docs/TESTING.md

Added some guidance on test names.
Added a config to allow the same name when in different describes.
none
- see if the guidance needs anything more?
- test two same named tests in a different described in an ETA test

Test naming conventions

---

src/components/tree/tree.js
test/components/tree/tree-api.func-spec.js
test/components/tree/tree-events.func-spec.js
test/components/tree/tree.e2e-spec.js
test/components/tree/tree.func-spec.js

Added functional and e2e tests for Tree
Closes #264 (formerly) https://jira.infor.com/browse/SOHO-8165
E2E
`env PROTRACTOR_SPECS=‘components/tree/tree.e2e-spec.js' npm run e2e:local:debug`
`env npm run e2e:local:debug`
FUNCTIONAL
`npm run functional:local`

264 - Added functional and e2e tests for Tree

---

app/views/components/form/test-compound-checkboxes-alignment.html
src/components/form/_form.scss

Added a media query to fix the checkbox alignment above 1280 width
Closes #419
http://localhost:4000/components/form/test-compound-checkboxes-alignment.html
- open link above. Once the page is completely loaded
- Group of checkboxes should be vertically aligned with the input field.

419 - fix compound checkbox alignment above 1280 width

---

app/views/components/hierarchy/example-index.html
src/components/hierarchy/hierarchy.js

Add double click event to hierarchy control.
Closes #589
- Grab code from PR
- Navigate to http://localhost:4000/components/hierarchy/example-index.html
- Verify double click is logged to the console

Added double click event and updated example

---

app/data/orgstructure.json
app/views/components/hierarchy/example-context-menu-with-details.html
src/components/hierarchy/hierarchy.js

**Explain the _details_ for making this change. What existing problem does the pull request solve?
Implement action event for Hierarchy actions menu
Closes #598
- Pull code from PR
- Navigate to http://localhost:4000/components/hierarchy/example-context-menu-with-details.html
- Click actions button under "Kaylee Edwards"
- Click profile (Alert should prompt with action info)

Fix for Implement action event for Hierarchy actions menu #598

---

app/views/components/listview/test-search-disabled.html
src/components/listview/_listview.scss
src/core/_config.scss
src/themes/dark-theme.scss
src/themes/high-contrast-theme.scss

This fix is isolated only in list view component.
`_listview.scss` (L#634)
```
&[disabled] {
opacity: $listview-search-disabled-opacity;
color: $listview-search-disabled-color;
-webkit-text-fill-color: $listview-search-disabled-color;
&:hover {
border-color: $listview-search-disabled-border-color;
}
~ svg.icon {
fill: $listview-search-disabled-icon-color;
}
}
```
**Created new variables across all the themes** and created a test template _test-search-disabled.html_
`dark-theme.scss` (L#197) 
```
$listview-search-disabled-color: $slate04;
$listview-search-disabled-opacity: 0.5;
$listview-search-disabled-border-color: $slate05;
$listview-search-disabled-icon-color: $slate05;
``` …

422 - Fixes disabled searchfield in listview component only

---

app/views/components/dropdown/test-tooltips.html

Adding the test provided in #633 to our visual tests suite

633 - Added Dropdown visual test

---

app/views/components/datagrid/test-paging-select-clientside-multiple.html
app/views/components/datagrid/test-paging-select-clientside-single.html
app/views/components/datagrid/test-paging-select-indeterminate-multiple.html
app/views/components/datagrid/test-paging-select-indeterminate-single.html
app/views/components/datagrid/test-paging-select-serverside-multiple.html
app/views/components/datagrid/test-paging-select-serverside-single.html
src/components/datagrid/datagrid.js
src/components/pager/pager.js
test/components/datagrid/datagrid-selection.func-spec.js

When using paging client-side, server-side, or indeterminate settings selectRow(), selectRows() methods were not working and throwing errors, this PR fixes all those issues.
Closes #373 (formerly) https://jira.infor.com/browse/SOHO-8173
**Test One**
http://localhost:4000/components/datagrid/test-paging-select-clientside-single
- Type in console window
- $('#datagrid').data('datagrid').selectRows([1,2,3]);
- It should only select 2nd row from top (column row Id: 1)
- Now type in console window
- $('#datagrid').data('datagrid').selectRow(4);
- It …

373 - Fixed selectRow() and selectRows() methods with Datagrid

---

test/components/datepicker/datepicker.e2e-spec.js
test/components/listview/listview.e2e-spec.js
test/components/textarea/textarea.e2e-spec.js
test/components/timepicker/timepicker.e2e-spec.js

Hardening some tests that are failing on Browser Stack nightlies.
- Checks should pass
- Watch tonights CRON once this is merged

Fix Cron BrowserStack Nightly tests

---

test/components/popupmenu/popupmenu.e2e-spec.js

Attempting to fix a test introduced in a previous PR that continues to fail on CI.  Added specific window size dimensions to this e2e test that includes mouse coordinates.
#647
Pull this branch and run the e2e tests.  The real test will be making sure this passes on the nightly cron job.

647 - Fixed Popupmenu e2e test

---

docs/TESTING.md

Updates testing documentation. Adds clarity.
Proofread TESTING.md please, pretty please.

Added testing doc changes

---

test/components/accordion/accordion-api.func-spec.js
test/components/accordion/accordion.e2e-spec.js

https://github.com/infor-design/enterprise/issues/516
npm run functional:ci
npm run e2e:ci

516 - Accordion Functional and E2E Tests

---

docs/CONTRIBUTING.md

Updating some instruction on how to collaborate and contribute to enterprise.
n/a
- Read through the changes in the md file
- `npm run mdlint:docs`

Updating contrib info

---

src/components/header/header.js
test/components/header/header-api.func-spec.js

Public function to manually remove the go-back style from the application menu button.
https://github.com/infor-design/enterprise/issues/696
Test via new functional test.

Fix for Need to remove the go-back arrow in a SPA context #696

---

src/components/datepicker/datepicker.js
test/components/datepicker/datepicker-api.func-spec.js

Recent changed to datepicker broke todat functionality if a value was already in the field.
Closes #699
http://localhost:4000/components/datepicker/example-index.html
- select a value other than today
- select today from the picker
Should show todays date but it wasnt if one was already in the field

Added fix for today button not working

---

docs/CHANGELOG.md

Added release notes

---

src/components/datepicker/datepicker.js
test/components/calendar/calendar.e2e-spec.js
test/components/datepicker/datepicker.e2e-spec.js

Fixing an issue with keyboard on datepicker
Closes #728
Go to http://localhost:4000/components/datepicker/example-index.html
- Hit down arrow to open
- Hit down again to go to sept 7th
- Hit up..
- At this point month should be august. And be highlighted

728  - Add fix for up key

---

README.md
docs/DEVELOPER.md
docs/INDEX.md
docs/QA.md

Making some updates to (and cleaning up) the project documentation.
#721
Pull this branch and read the docs

721 - Updating development docs

---

src/components/dropdown/_dropdown.scss
src/components/locale/readme.md

Fixes a 404 error on https://design.infor.com/code/ids-enterprise/latest/locale
Closes infor-design/website#649
- check if what i changed make sense, wait for next deploy.

649 - updated a link

---

app/views/components/fileupload/test-cap.html

- Added a close button on example page
- http://localhost:4000/components/fileupload/test-cap.html
Closes #741 
- Click "Contextual Action Panel" button
- CAP should now have a close button

741 Added close button for CAP

---

app/views/components/validation/test-dynamic-message.html
src/components/validation/validator.js
test/components/toast/toast-api.func-spec.js
test/components/toast/toast-xss.func-spec.js

When a validation message is dynamically changed the on screen message is not being updated correctly.
Closes #640
- go to http://localhost:4000/components/validation/test-dynamic-message.html
- Change the dropdown to any value other than Hawaii and focus out of the control to trigger the validation
- The validation then contains the dynamic message including the current value.
- select hawaii for a valid value
@marknolaninfor

640 - Dynamic validation messages do not update the displayed value

---

app/views/components/modal/example-accordion-modal.html
src/components/accordion/accordion.js
src/components/dropdown/_dropdown.scss
src/components/modal/_modal.scss
src/components/trackdirty/trackdirty.js

Added the modal container in triggering a document click to close any open menus and popups in the clickInterceptor function.
I also created a separate example template for this. 
http://localhost:4000/components/modal/example-accordion-modal.html
Closes https://github.com/infor-design/enterprise/issues/747
- Run http://localhost:4000/components/modal/example-accordion-modal.html
- Click 'Open Modal' button
- Click the accordion
- Accordion should not close the modal

747 - modal closes on accordion

---

app/views/components/datepicker/test-updated.html
src/components/mask/mask-input.js

Additional condition under the mask. Seems that for some reason the format and mask is not updating in updated method.
Closes https://github.com/infor-design/enterprise/issues/305
- Run http://localhost:4000/components/datepicker/test-updated.html
- Click update
- Selecting a date and set time in the picker.
- Click to select a different time / date.

305 - datepicker time options

---

src/components/wizard/wizard.js

Some jsdoc information was not formatting properly
Fixes #824
View the fixed documentation [here on staging](https://staging.design.infor.com/code/ids-enterprise/latest/wizard)

Fix some jsdoc comment inconsistencies

---

src/components/tree/tree.js

After drag and drop it would be nice have event give me updated model and the node I drag.
Add new event for "drag.start" and syncDataset function #801

Add new event for "drag.start" and syncDataset function

---

app/views/components/tabs/example-activated-event.html
test/components/tabs/tabs.e2e-spec.js

Added some additional e2e spec test just to cover some verification of the callbacks
Closes #426 

Added some test in e2e for verification

---

app/views/components/editor/test-html-view.html
src/components/editor/editor.js

- Added config for HTML view
- Added sample page for new config
- http://localhost:4000/components/editor/test-html-view.html
Closes #471 
- On initialization of page, editor should be on HTML view

Added config for html view

---

test/components/tabs/tabs-vertical.e2e-spec.js
test/components/tabs/tabs.e2e-spec.js

Trying to get another tab test that's sporadically failing to pass.
#753 (sporadic failures) and #858 (where the test suddenly started failing)
Make sure this branch passes the Travis checks before merging

753 - Fix another tab test

---

docs/CONTRIBUTING.md

I wrote some details on how to format a pull request title.
Fixes #875
Proofread the changes in the file.

Update pull request title format preferences

---

src/components/datagrid/datagrid.editors.js
src/components/dropdown/dropdown.js
src/components/editor/editor.js
src/components/field-filter/field-filter.js
src/components/fileupload-advanced/fileupload-advanced.js
src/components/modal/modal.js
src/components/searchfield/searchfield.js
src/components/splitter/splitter.js
src/components/tabs/tabs.js
src/components/timepicker/timepicker.js
src/components/toolbarsearchfield/toolbarsearchfield.js
src/utils/utils.js

Removed fn.uniqueId entirely to avoid conflicts, and refactored places that use it to use utils.
Closes #868
Smoke Test Components in this PR
Test while running jQueryUI
@PilotBob can you test this branch against your stuff?

868 - uniqueid conflicts  [v4.11.x]

---

src/components/datepicker/_datepicker.scss

A stray padding caused the datepicker alignment to break.
Closes #871
http://localhost:4000/components/datepicker/example-index.html
- open the picker
- make sure it looks good...

871 - Added a fix for datepicker alignment [v4.11.x]

---

app/views/includes/applicationmenu-many-items.html

A file was incorrectly deleted.
Closes #877 
Run http://localhost:4000/components/applicationmenu/test-filterable-many-items.html

877 - Brought back incorrectly dropped file [v4.11.x]

---

app/views/components/popupmenu/test-multiple.html
app/views/patterns/stepprocess-markup.html
src/components/hierarchy/_hierarchy.scss
src/components/hierarchy/hierarchy.js

Ran the veracode scanner for 4.11.0 and fixed some of the errors reported. Sent a second scan with the changes up, may post an update if anything else comes back.
Fixed a messed up icon on the changed area. Added a test page for an issue.
Closes #870 
Simply review code changes, run hierarchy component.

870 - Fixed a few scan errors for veracode [v4.11.x]

---

src/components/datagrid/datagrid.js

- Fired the clearFilter function when triggering reset to default
- http://localhost:4000/components/datagrid/test-save-settings.html
Closes #847 
- Type any condition that filters
- Reload the page
- Under the ... menu - select reset to default
- Filters should now be reset

847 - Added clearFilter when triggering reset to default

---

app/views/components/drag/example-index.html

- Realigned elements
- Code cleanup
- http://localhost:4000/components/drag/example-index.html
Closes #888 
- Upon loading of page, draggable elements should not overlap the title of each example

888 - Realigned elements, Code cleanup

---

app/views/components/tree/test-json-child-nodes.html
src/components/tree/tree.js

Last child node was duplicating when dataset used along parent key with Tree.
Closes #916
http://localhost:4000/components/tree/test-json-child-nodes.html
- See there should be only 4 items in tree.
- And each item should have one child only as:
```
-System Menu
--Applications
---Batch
----Lapsed/Expired Report Control
```

916 - Fixed duplicating child node with Tree [v4.11.x]

---

scripts/deploy-documentation.js
src/components/multiselect/multiselect.js
src/components/multiselect/readme.md

Reference dropdown component in multiselect component readme.
References #843 
Review readme of multiselect to see if makes sense.

Multiselect link to dropdown events

---

app/data/names.json
app/views/components/listview/example-search.html
app/views/components/listview/test-listview-performance-paging.html
app/views/components/listview/test-listview-performance.html
src/components/listview/_listview.scss
src/components/listview/listview.js

We tag teamed this issue to get a few fixes for performance.
- change filtering to limit min 2 chars
- optimize tabindex code
- optimize duplicate filter code
- added a highlight: false setting so that can be optional
- added a paging example (which will optimize on a separate ticket)
- removed some selectors that caused slow down
Its still not going to totally work great with this many on IE11, so reccomending a max of 1000 there.
Closes #430
test performance on http://localhost:4000/components/listview/test-listview-performance.html

430 - listview performance fixes

---

src/utils/environment.js

All pages were erring when loaded on IE 11
Closes #1004
- open any page like:
http://localhost:4000/components/editor/test-modal.html
Should have no error in the console

1004- Fix IE errors

---

app/data/orgstructure.json
src/components/hierarchy/_hierarchy.scss
src/components/hierarchy/hierarchy.js

Adds support for disabling action menu items.
Adds support for creating sub action menus.
https://github.com/infor-design/enterprise/issues/1044
1 . Apply code change and Navigate to http://localhost:4000/components/hierarchy/example-context-menu-with-details.html
2. Click the '...' button. Notice one of the actions is now disabled and options has a sub menu.

Support disabling action menu items & add support for sub menus.

---

app/data/orgstructure.json
src/components/hierarchy/_hierarchy.scss

Sub menus are clipped when using actions button on a card a few levels deep.
https://github.com/infor-design/enterprise/issues/1073
1. Apply code from PR
2. Go to http://localhost:4000/components/hierarchy/example-context-menu-with-details.html
3. Click on "Katie Olland" card action menu button.
4. Hover over options. Notice the sub menu is not displayed and forces a horizontal overflow.

1073 - Hierarchy actions menus sub menu is sometimes clipped

---

app/views/components/searchfield/example-index.html
package.json
src/components/autocomplete/autocomplete.js
test/components/searchfield/searchfield.e2e-spec.js

Removed the need for a specific chrome driver version, as the bug was really the input selecting the value in a timeout.
Closes #1028 
- test out http://localhost:4000/components/searchfield/list and http://localhost:4000/components/autocomplete/list a bit
- ensure tests run on CI

1028 - remove need for specific chromedriver

---

app/views/components/listview/example-footer-navigation.html
app/views/components/listview/example-paging-clientside.html
app/views/components/listview/example-paging.html
app/views/components/listview/test-listview-set-page.html
app/views/components/listview/test-paging-indeterminate.html
app/views/components/listview/test-paging-pagesize.html
app/views/patterns/list-detail-paging-indeterminate.html
src/components/listview/_listview.scss
src/components/listview/listview.js
src/components/pager/pager.js
test/components/accordion/accordion.e2e-spec.js
test/components/busyindicator/busyindicator.e2e-spec.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/listview/listview.e2e-spec.js
test/components/lookup/lookup.e2e-spec.js
test/components/validation/validation.e2e-spec.js

Fix some followup issues on #250 that were introduced.
Cleaned up some unneeded inline styles.
Added more tests for the cases, fixed a missing await.
Closes #250 
http://localhost:4000/components/pager/example-datagrid.html
- attempt to type 200 in the pager number field
- should reset to max no pages and not all
http://localhost:4000/components/pager/example-listview.html
- should be 10 records
- scroll down and all records can be scrolled to

250 - Fixed some paging issues [v4.12.x]

---

app/views/components/lookup/example-multiselect-paging-serverside.html
app/views/components/lookup/test-update-dataset.html
src/components/datagrid/datagrid.js
src/components/lookup/lookup.js
test/components/lookup/lookup-api.func-spec.js

Fixed an error when dataset is [] that showed up in angular.
Added a method to updateDataset whether open or closed (to be used in angular as well)
Removed an uneeded timeout
Closes #1080 
http://localhost:4000/components/lookup/test-update-dataset.html
- open and see data
- press update while open (data changes)
- reload page
- click update before opening
- open and see updated data
http://localhost:4000/components/lookup/example-multiselect-paging-serverside.html
- open
- pick record
- hit apply, should be no errors
Tests pass (of course)

1080 - Fixed lookup error and added new update function [v4.12.x]

---

src/components/pager/pager.js

Simple change, I moved event trigger out of if so it will fire if the setting is not set.
Closes #1100

1100 -  Fix for pagesize change event [v4.12.x]

---

app/views/components/breadcrumb/example-current-as-link.html
app/views/components/breadcrumb/example-index.html
app/views/components/breadcrumb/example-navigation-breadcrumbs-alternate.html
app/views/components/breadcrumb/example-navigation-breadcrumbs.html
app/views/components/breadcrumb/layout.html
app/views/components/personalize/example-index.html
app/views/components/personalize/layout.html
app/views/components/signin/example-forgotpassword-sent.html
app/views/components/signin/example-forgotpassword.html
app/views/components/signin/example-index.html
app/views/components/signin/example-remember-me.html
app/views/components/signin/test-custom.html
app/views/components/signin/test-dropdown.html
app/views/components/signin/test-fields.html
app/views/components/signin/test-hidden.html
app/views/patterns/sticky-footer.html
src/components/area/readme.md
src/components/breadcrumb/readme.md
src/components/bubble/readme.md
src/components/column-grouped/readme.md
src/components/datagrid/readme.md
src/components/donut/readme.md
src/components/input/readme.md
src/components/listview/readme.md
src/components/mask/readme.md
src/components/personalize/readme.md
src/components/popupmenu/readme.md
src/components/scatterplot/readme.md
src/components/signin/readme.md
src/components/tabs-multi/readme.md

Found a few more links that were failing so moved some things around and fixed the incorrect links.
Closes #1034 (again)
Closes #1108 (also)
Review my changes, cant really test until deployed.

1034 - Fix some more links [v4.12.x]

---

src/components/dropdown/dropdown.js

Just a follow-up fix for the QA Test fail issue.
Closes #1011 

1011 - undefined issue in dropdown fail [v4.12.x]

---

src/components/dropdown/_dropdown.scss

Follow-up fix for Failure of 945 in QA Testing
Closes #945 

945 - Dropdown Color in Low Contrast Fail [v4.12.x]

---

app/views/components/alerts/example-index.html
app/views/components/menubutton/test-focus-click.html
app/views/components/menubutton/test-on-toolbar.html
src/components/listbuilder/_listbuilder.scss
src/components/popupmenu/popupmenu.js
src/components/searchfield/_searchfield.scss
src/components/textarea/textarea.js
src/components/toolbar/toolbar.js

Fixed a few minor issues for 4.12
Closes #1112 
Closes #1107 
Closes #1096 
Closes #1067 
Closes #1065 
Closes #1077 
1112
http://localhost:4000/components/datagrid/example-list.html
- click on the .. and open the menu
- click into the search next to it (should stay focused)
1107
http://localhost:4000/components/searchfield/test-categories.html#
- open all the menus
- blue check should not overlap text
1096
http://localhost:4000/components/menubutton/test-on-toolbar.html
- open all the menu buttons
- blue check should not overlap text
1067 …

412 - bug six pack [v4.12.x]

---

app/views/components/editor/example-dirty-tracking.html
src/components/editor/editor.js

When using dirty tracking and calling 'updated'. The editor will error out when typed in .
Closes #1114 
http://localhost:4000/components/editor/example-dirty-tracking.html
- type in the editor
- should show dirty tick and no errors in console.

1114 - Fix Editor error after calling updated [v4.12.x]

---

app/views/patterns/list-detail-mixed-selection.html
src/components/listview/listview.js

Clicking checkboxes in the list view will make the listview pattern drill in. So it wasnt possible to select without drilling
Closes #1152
http://localhost:4000/patterns/list-detail-mixed-selection.html
- click the checkboxes and test they work
- resize the page to less than 750px so that just the listview shows
- press the checkboxes to select (should not drill in)
- click the rest of the list area (should drill in)

1152 - Listview selection issue [v4.12.x]

---

test/components/datagrid/datagrid.e2e-spec.js

Fix paging test

---

src/components/toolbar/toolbar.js

When clicked on toolbar button was showing jserror
Closes #1177
Not really possible to test its in their app

1177 - Fixed js error was showing with toolbar

---

scripts/generate-bundle-banner.js
src/components/circlepager/circlepager.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/datepicker/datepicker-api.func-spec.js

Test Error Tweaks

---

test/components/monthview/monthview-api.func-spec.js

Similar to yesterday, these tests should be fixed on a future PR. To be added back on https://github.com/infor-design/enterprise/issues/1189

1189 - Skip two tests for now.

---

app/views/components/contextualactionpanel/test-contextual-accordion.html
src/components/accordion/accordion.js

Fix Auto Close on Accordion Click inside Contextual Action Panel
Closes #1138 
Visit
http://localhost:4000/components/contextualactionpanel/test-contextual-accordion
Try to click the accordion.

1138 - Fix for Contextual Action Panel: Clicking an item in an accordion closes the contextual action panel

---

app/views/components/accordion/test-with-contextmenu.html
src/components/accordion/accordion.js

- Fixed issue regarding expand and collapse of accordion with context menu
- http://localhost:4000/components/accordion/test-with-contextmenu.html
- Closes #639
- Check if first accordion is abke to expand and collapse
- Check if context menu is enabled

639 - Fixed issue regarding expand and collapse of accordion with context menu

---

src/components/popupmenu/popupmenu.js

- Fixed issue regarding arrow up and down on disabled placeholder
- http://localhost:4000/components/searchfield/example-clearable.html
Closes #329
- Type "asd" on searchfield to display "No Results" placeholder
- Press Up and Down keys
- "No Results" placeholder should not be selectable

329 - Fixed issue regarding arrow up and down on disabled placeholder

---

app/views/components/lookup/test-tabs.html
src/components/datepicker/datepicker.js
src/components/lookup/lookup.js
test/components/datepicker/datepicker-api.func-spec.js
test/components/lookup/lookup-api.func-spec.js

- Fixed issues regarding lookup being hidden on tabs
- Added same fix on date picker
- Added test page
- http://localhost:4000/components/lookup/test-tabs.html
Closes #1238 
- Click on first tab to display content with lookup
- Lookup icon should now be visible and working correctly

1238 - Fixed issues regarding lookup being hidden on tabs [v4.13.x]

---

app/views/components/datagrid/test-filter-editable.html
src/components/datagrid/datagrid.js

Corrected the logic on applyfilter to return the correct rowValue.
Closes #1269 
Goto 'http://localhost:4000/components/datagrid/test-filter-editable.html'
Filter on Price, Quantity, or Order Date.

1269 -  Datagrid applyfilter does not work with related datafields

---

docs/CHANGELOG.md
test/components/datepicker/datepicker.e2e-spec.js

Added a few updated release notes for things added after the first draft. Fixed some typos

NA - Updated Release Notes [v4.13.x]

---

src/components/accordion/accordion.js

Fixed an additional issue on #639
Fixes #639 (Additional)
http://localhost:4000/components/accordion/test-with-contextmenu.html
- right click any header
- click on the header part to close (or any place in the form)
- right click any header
- click on the header < and > arrow part to close (or any place in the form)

639 - Add fix for non-closing context menu [v4.13.x]

---

src/components/swaplist/swaplist.js

- Fixed issue regarding swaplist drag and drop items being lost
- http://localhost:4000/components/swaplist/example-index.html
Closes #1195
- Select multiple items from the swaplist
- Drag them over in a fast manner to the next one
- The other items should now be shown

1195 - Fixed issue regarding swaplist drag and drop items being lost

---

src/components/datagrid/datagrid.js
test/components/calendar/calendar.e2e-spec.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/monthview/monthview-api.func-spec.js

Some tests failed on nightly, stabilizing them.

NA - Fix tests for nightly

---

app/data/compressors.js

- Fixed issue regarding incorrect filtering on datagrid
- Updated filtering of data on compressors.js
- http://localhost:4000/components/datagrid/example-paging.html
Closes #396 
- For Product Name enter the number "0" and click on the enter key
- There should now be filtered data displayed

396 - Fixed issue regarding incorrect filtering on datagrid

---

test/components/datepicker/datepicker.e2e-spec.js

Trying to fix on test that has problems on the nightly.

NA - Fix browserstack test

---

test/components/datepicker/datepicker.e2e-spec.js

Fix a BS test

---

app/views/components/datagrid/test-dropdown-window-size.html
src/components/dropdown/dropdown.js

Correct the issue of a short dropdown list not displaying correct.
Closes #1298 
Open http://localhost:4000/components/datagrid/test-dropdown-window-size.html
open the action dropdown
#909 needs to also be tested with the fix.

1298 - Datagrid Dropdown Editor - dropdown window is to small

---

docs/DEVELOPER.md
src/components/donut/readme.md
src/components/input/readme.md
src/components/pie/readme.md
src/components/timepicker/readme.md
src/components/toolbarsearchfield/readme.md
src/components/tooltip/readme.md
src/components/typography/readme.md

Fixes some relative URLs based on newly written documentation and bug fixes on `website`. Some additional links may still need to be updated.
Requires infor-design/website#718 to be deployed
1. Go to https://staging.design.infor.com/code/ids-enterprise/latest/tooltip
2. `popover` link goes to component page without reloading the whole page
3. Check the "The code above is demoed..." links to make sure they open in a new tab

718 - Demo link examples

---

app/views/components/toolbar-flex/test-gauntlet.html
docs/CHANGELOG.md
src/components/popupmenu/popupmenu.js
src/components/slider/slider.js

Added release notes and did Veracode scan and fixed a few flaws.
NA
- Review notes
- http://localhost:4000/components/toolbar-flex/test-gauntlet.html
- quick test slider and popupmenu destroy

Added release notes and did Veracode scan [v4.14.x]

---

package.json

`npm run watch` was not working for development locally.
n/a
- Run `npm run watch` and see that it actually watches for changes

NPM - Update the npm watch script

---

test/components/button/button.e2e-spec.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/datepicker/datepicker.e2e-spec.js
test/components/dropdown/dropdown.e2e-spec.js
test/components/listview/listview.e2e-spec.js
test/components/monthview/monthview.e2e-spec.js
test/components/personalize/personalize.e2e-spec.js
test/components/tabs/tabs.e2e-spec.js

Saw some tests failing occasionally on master.
Let it run on CI

NA - Stablize a Couple Tests

---

app/views/components/circlepager/example-tabs.html
src/components/cards/_cards.scss
src/components/circlepager/_circlepager.scss
src/components/circlepager/circlepager.js

Tabs not in the middle.
Closes #1284 
Check it on http://localhost:4000/components/circlepager/example-tabs.html

1284 - Fix on Similar Tabs not in the middle.

---

.github/CODEOWNERS

Requesting to be added in the code owners so I can check and/or code review the work of the Manila Dev team. Sometimes, they forgot to add me on their PR

Requesting to be added in the code owners

---

app/views/components/swaplist/example-search.html
src/components/swaplist/swaplist.js

Typing "Shift + M" in the Swaplist search field was not working.
Closes #1408
http://localhost:4000/components/swaplist/example-search.html
- It should let type in search field "Shift + M"

1408 - Fixed shift+m key was not woking with swaplist

---

src/components/calendar/calendar.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/dropdown/dropdown-updates-events.func-spec.js
test/components/personalize/personalize.e2e-spec.js

Looked through last few nightly and master logs and fixed a few tests.
- Make sure this build passes

NA - Fix a few unstable tests

---

app/views/components/datagrid/test-card-cell-with-islist.html
app/views/components/datagrid/test-card-cell.html
src/components/datagrid/_datagrid.scss
src/core/_config.scss
src/themes/dark-theme.scss
src/themes/high-contrast-theme.scss

Datagrid: It has a strange style on hovering the card cell row when setting up `isList: true`.
I created a new test page for this http://localhost:4000/components/datagrid/test-card-cell-with-islist.html, and it seems that the `test-card-cell.html` prompted a lot of style lint so I fixed it also.
Closes https://github.com/infor-design/enterprise/issues/1490
- Open http://localhost:4000/components/datagrid/test-card-cell-with-islist.html
- Click anywhere in the row to activate it
- Play it around by clicking anywhere and observe the hover state
- Hover background …

1490 - Added fix for datagrid hover in cardview cell

---

docs/CHANGELOG.md

Added nots for version 4.15
Check for edits / anything you might know i missed.

415 - Added release notes [v4.15.x]

---

src/components/tabs/tabs.js
src/utils/xss.js
test/components/tabs/tabs-api.func-spec.js
test/components/utils/xss.func-spec.js

The previous fix had a hole on nested tags which is addressed. But changed the addTabs api to strip the name instead so text like `<online>` would work.
Closes #1462 
- Ensure the tests run ok the cases are covered there.

1462 - Change and Harden the add Tabs Xss Fix [v.4.15.x]

---

.github/PULL_REQUEST_TEMPLATE.md
docs/CHANGELOG.md
docs/CONTRIBUTING.md
test/components/dropdown/dropdown-updates-events.func-spec.js

From now on we want folks to add their own notes to the change log. I made a note in the contributing notes and in the PR template. Added notes so far. Also try and fix one test (again).
None
Feel free to suggest edits. Wasn't really sure on the PR template.

Update Changelog and Add Notes to Developers about it

---

test/components/dropdown/dropdown-updates-events.func-spec.js

One more attempt to fix this test before we `xit` it.

NA - Fix Dropdown Random Failing Test

---

test/components/editor/editor-api.func-spec.js
test/components/hierarchy/hierarchy-stacked-api.func-spec.js
test/components/hierarchy/hierarchy.func-spec.js

Some recent tests are a bit flaky. Trying to fix

Improve Hierarchy and Editor Tests

---

docs/CHANGELOG.md

Checked all items are added. Added counts and minor fixes.

Update Change log for 4.16.0

---

test/components/datagrid/datagrid.e2e-spec.js
test/components/dropdown/dropdown.e2e-spec.js
test/components/listview/listview.e2e-spec.js
test/components/lookup/lookup.e2e-spec.js

These tests failed the nightly CRON. Hoping this fixes for next time

NA - Slow down a couple tests

---

app/views/components/swaplist/example-search.html
docs/CHANGELOG.md
src/components/listview/listview.js
src/components/swaplist/swaplist.js

Items were not able to drag anymore after make the search with swaplist
Closes #1703
http://localhost:4000/components/swaplist/example-search.html
- Drag "Option AA" from 'Available' to 'Selected'
- Type "BB" in the search field of 'Available'
- Try to Drag "Option BB" from 'Available' to 'Selected'
- It should work fine

1703 - Fixed drag was not working after search with swaplist [4.16.x]

---

src/components/locale/locale.js
test/components/datagrid/datagrid-validation.func-spec.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/locale/locale.func-spec.js

After one of the last PR's some fits got left in we didnt notice. Removing these so all tests run
NA
- Build tests should pass

NA - Remove tests with fit

---

test/components/datagrid/datagrid.e2e-spec.js
test/components/locale/locale.func-spec.js
test/components/lookup/lookup.e2e-spec.js

Some tests are labeled to check for standard timezone, but this changed, so tests are failing. Made this work on either timezone.
NA - But from #592 
- If Tests pass on the PR its good.

NA - Fix timezone tests

---

src/components/datagrid/datagrid.js

Hot fixes an issue arising from the big fix for #1608.
Comment documenting the hotfix here: https://github.com/infor-design/enterprise/issues/1608#issuecomment-471980574
Related to #1608.
- Pull branch
- Run app
- Browse to http://localhost:4000/components/datagrid/test-editable-actionable-mode.html
- Ensure tabbing works as expected when `actionableMode=true` as on this test page.

1608 - Datagrid tabbing into editable cells HOTFIX

---

app/views/components/datagrid/example-tooltips.html
app/views/components/datagrid/test-ellipsis.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-api.func-spec.js
test/components/datagrid/datagrid.e2e-spec.js

Added support for ellipsis to header text with datagrid.
Closes #842
http://localhost:4000/components/datagrid/test-ellipsis.html
- Resize the column width to small for "Formatter Ellipsis"
- See header text should show "..." ellipsis if width smaller then available width

842 - Added support for ellipsis to header text with datagrid

---

app/app.js
app/src/js/routes/data.js
src/components/dropdown/dropdown.js
src/components/hierarchy/_hierarchy-base.scss
src/components/hierarchy/_hierarchy-stacked.scss
src/components/hierarchy/hierarchy.js
src/components/tabs/tabs.js

Ran scans for dynamic and static. Fixed a few errors. In addition fixed a bug on the icons on the hierarchy i spotted (too big).
@EdwardCoyle - After you review this can you go in to the latest scans in veracode and mitagate?
Closes #1723 
- Test out dropdown (labels), hierarchy, tabs (add) a bit
- Check httpOnly setting on demo app.

1723 - Fixed a few veracode scan errors

---

test/components/datagrid/datagrid.e2e-spec.js
test/components/listview/listview.e2e-spec.js
test/helpers/e2e-config.js

More test cleanup and stability / flakiness fixes.
None - just jotted down some recent fails.
- both builds should be green

na -  Fix more tests [v4.17.x]

---

src/components/grid/readme.md

Fixed a broken link in the docs.
Fixes #1836
- deploy to docs
- Go to https://design.infor.com/code/ids-enterprise/latest/grid (or staging)
- Scroll down to 'Breakpoints'
- Click on 'Grid & Breakpoints guidelines' link which should work once this is merged/deployed

1836 - Fix a broken link in the grid page [v4.17.x]

---

docs/CHANGELOG.md
test/components/datepicker/datepicker.e2e-spec.js

This PR fixes a test that was failing when on the zero minute by chance on the PR. Added an empty change log to add to.
NA
**How to Test**:
- tests pass, lint passes

NA - Fixes and test and adds an empty changelog

---

app/src/js/custom-route-options.js

Some demo pages were having issues (icons) due to  the `embedded=true` query parameter.
#1889 
1. `npm start`
1. Go to the following and make sure you see the icons
- http://localhost:4000/components/icons/example-index
- http://localhost:4000/components/icons/example-index?layout=embedded
Not needed:
- 🚫  An e2e or functional test for the bug or feature.
- 🚫   A note to the change log.

1889 - Set custom route layouts with common, safeguarded function [4.17.x]

---

.gitattributes

Since we are now having each PR add to the changelog, conflicts are arising even with using an alphabetical sort.
n/a
- We'll see next time there might be conflicts and monitor it throughout  the `4.18.x` sprint.

Use gitattributes file to remove some changelog conflicts

---

app/src/js/custom-route-options.js
app/views/components/busyindicator/test-busyindicator-on-body.html
docs/CHANGELOG.md
src/components/busyindicator/busyindicator.js

Fixed when busyindicator use on body it was generating javascript error.
Closes #1918
http://localhost:4000/components/busyindicator/test-busyindicator-on-body.html
- See console there should not be any error
- Click on button "Start Busy Indicator"
- See console there should not be any error

1918 - Fixed busyindicator was getting javascript error

---

app/views/components/pager/example-standalone.html

Did this months scan and found 8 flaws (mostly false positive but fixed to reduce the flaw count) on this page, which i fixed by changing console.log's to toasts.
Closes #1927
- run the http://localhost:4000/components/pager/example-standalone.html example
- click the buttons
- now its a toast and not a console.log

1927 - Mitigates some veracode flaws

---

app/views/components/tabs/example-enable-disable-individual-tabs-with-keydown.html
docs/CHANGELOG.md
src/components/tabs/tabs.js
test/components/tabs/tabs.e2e-spec.js

Fixed focus was changed after enable/disable Tabs.
Closes #1934
http://localhost:4000/components/tabs/example-enable-disable-individual-tabs-with-keydown.html
- Click on input field (Disable "Form Elements" tab on keydown)
- Press down arrow key
- Tab "Form Elements" should disable
- Focus should stay in the input field

1934 - Fixed focus was changed after enable/disable tabs

---

app/views/components/tabs/example-activated-event.html
test/components/tabs/tabs-api.func-spec.js

Adjusting functional tab tests to fix random failures
closes #1979 

1979 - Fix functional tab tests [4.18.x]

---

app/views/components/contextualactionpanel/example-centered.html
app/views/components/contextualactionpanel/test-nested.html
docs/CHANGELOG.md
src/components/contextualactionpanel/contextualactionpanel.js
src/components/modal/modal.js

Fixed an issue where cap modal was open only one time.
Closes #1993
http://localhost:4000/components/contextualactionpanel/example-centered.html
- Click on the "Open Contextual Action Panel" button
- Click the "X" button to close the panel
- Click on the "Open Contextual Action Panel" button again
- It should open/close as many times need
http://localhost:4000/components/contextualactionpanel/test-nested.html
- Click on the "Contextual Action Panel" button
- Click on the "Show Nested Modal" button
- Click on the "Close" button to close the nested modal
- …

1993 - Fixed an issue where cap modal was open only one time [4.18.x]

---

app/views/components/hierarchy/example-stacked.html
app/views/components/hierarchy/test-multi-root.html
app/views/examples/landmark/example-orgchart.html
src/components/toolbar-flex/toolbar-flex.item.js
test/components/hierarchy/hierarchy-stacked-api.func-spec.js
test/components/hierarchy/hierarchy.func-spec.js

The hiearchy stacked example used some stuff in the sample that didnt work in IE. Also fixed a variable name style.
Fixes #2010 
- pull branch and build
- load http://localhost:4000/components/hierarchy/example-stacked.html in IE11 and ensure it loads
- try some other browsers and hierarchy examples for good measure

2010 - Hierarchy Demo Not Working in IE [v4.18.x]

---

app/views/components/dropdown/example-no-search-lsf.html
test/components/dropdown/dropdown-api.func-spec.js
test/components/dropdown/dropdown-nosearch-api.func-spec.js
test/components/dropdown/dropdown-updates-events.func-spec.js
test/components/multiselect/multiselect-api.func-spec.js

Adds cleanup for dropdown func tests, based on random failures seen on the previous 2010 PR
- Tests on Ci should pass.

2010 - Adds cleanup for dropdown func tests [v4.18.x]

---

src/components/applicationmenu/applicationmenu.js

Fixes #2044 
- Build this branch
- copy over to the NG project or use npm link
- open http://localhost:4200
- make sure the menu can be toggled
See also https://github.com/infor-design/enterprise-ng/pull/456/files

2044 - Better fix for 2044 [v4.18.x]

---

README.md

The badge for browser stack wasnt working.
**How to test**:
Examine the badge on the branch https://github.com/infor-design/enterprise/tree/fix-browser-stack-key
Fixes #1975

1975  - Update README.md to fix browser stack badge

---

docs/CHANGELOG.md

This PR simply adds blank headings for 4.19.0 in CHANGLOG.md, and fixes a typo.
N/A
Double check the accuracy of the changes in CHANGELOG.md
**Included in this PR:**

N/A - Adds blank headings for 4.19.0 in CHANGLOG.md

---

docs/PUBLISH.md
package.json
scripts/publish-nightly-manual.js

Since cron job testing is very unstable and we are having to manually deploy dev/nightly's again, I made a quick script.
n/a
1. Review the code
1. I tested this for a 20190502 dev release (on npm)
🚫 An e2e or functional test for the bug or feature.
🚫 A note to the change log.

Add a script for dev releases

---

app/views/components/applicationmenu/test-personalized-role-switcher-long-title.html
app/views/includes/applicationmenu-personalized-role-switcher-long-title.html
docs/CHANGELOG.md
src/components/applicationmenu/_applicationmenu.scss
test/components/applicationmenu/applicationmenu.e2e-spec.js

Fixed role switcher with long title was not clickable for application menu.
Closes #2060
http://localhost:4000/components/applicationmenu/test-personalized-role-switcher-long-title.html
- Role switcher should clickable
- And it should be able to expand and collapse switcher panel area

2060 - Fixed role switcher with long title for application menu

---

test/components/applicationmenu/applicationmenu.e2e-spec.js
test/components/lookup/lookup.e2e-spec.js
test/components/personalize/personalize.e2e-spec.js
test/components/radios/radios.e2e-spec.js
test/components/toolbar-flex/toolbar-flex-api.func-spec.js
test/components/toolbar-flex/toolbar-flex.e2e-spec.js
test/protractor.ci.bs.conf.js
test/protractor.ci.conf.js
test/protractor.ci.debug.conf.js
test/protractor.local.bs.conf.js
test/protractor.local.debug.conf.js

Adjusts a few tests that had been randomly failing. Also changed the config so protractor-flake will not re-run everything
- tests pass on the branch and PR
- if something fails on the log it will only restart part

NA- Attempts to fix some tests failing on Cron

---

docs/CHANGELOG.md
src/components/input/readme.md
src/components/listfilter/readme.md
src/components/mask/readme.md
src/components/menubutton/readme.md
src/components/multiselect/readme.md
src/components/popover/readme.md
src/components/popupmenu/readme.md
src/components/scatterplot/readme.md
src/components/searchfield/readme.md
src/components/switch/readme.md
src/components/tabs-header/readme.md
src/components/tabs-module/readme.md
src/components/tabs-multi/readme.md
src/components/tabs-vertical/readme.md
src/components/tabs/readme.md
src/components/toolbarsearchfield/readme.md
src/components/tooltip/readme.md

Some of the relative links were defined incorrectly in the markdown files. 
closes #2155 
- Pull branch
- `npm run documentation -- --site=staging`
- Run the IDS website locally and go to https://localhost/code/ids-enterprise/latest/input
- Go to the link that says “Masking” and make sure it works when opening in a new tab.

2155 - Some doc links failing on the IDS Website

---

src/components/personalize/personalize.js

Some newer code uses some functions not available in IE11. So i reverted to IE compatible versions
Fixes #2183 
- open datepicker in IE 11
- test theme changing and color changing

2183 - Fixes some components that have errors on IE 11

---

app/views/components/hierarchy/test-multiple-charts.html

A new hierarchy example failed QA as it wouldnt load on IE. Fixed this.
Fixes #2205 
http://localhost:4000/components/hierarchy/test-multiple-charts.html
- open this page in IE and click the tabs

2205 - Fix an IE issue on a hierarchy example [v4.19.x]

---

app/views/components/datagrid/test-filter-applyfilter.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/hyperlinks/_hyperlinks.scss

This PR repushes https://github.com/infor-design/enterprise/pull/2213 to 4.19.x as it fixes an important regression.
Closes #1879
Closes #2231
http://localhost:4000/components/datagrid/example-reorder.html
- reorder columns and they should stick
- try it as well on page 2/3 ect
http://localhost:4000/components/datagrid/test-filter-applyfilter.html
- set the activity filter to "number 1"
- click on the clear filter button
- play with the activity filter 
cc @marknolaninfor

2231 - Column reorder and Filtering [v4.19.x]

---

app/views/components/datagrid/example-modal-datagrid.html
docs/CHANGELOG.md

Select all header checkbox is not selecting all checkboxes.
Closes #2225.
- Visit http://localhost:4000/components/datagrid/example-modal-datagrid.html
- Ensure Select all checkbox properly selects all checkboxes

2225 - Modal Datagrid select all not working [v4.19.x]

---

test/components/bar/bar-grouped.e2e-spec.js
test/components/bar/bar-stacked.e2e-spec.js
test/components/datagrid/datagrid.e2e-spec.js

Saw some of these tests failing try to stabilize them. One i am skipping on CI because it uses browser caching and that doesn't seem to be working on CI.

Fix up some tests failing on the CRON

---

app/views/components/personalize/example-color-theme-api.html

This PR switches the function syntax used in a test page from an arrow function to a regular function. This fixes IE11 compatibility and makes the test work.
Closes #2216
- Open http://localhost:4000/components/personalize/example-color-theme-api.html?locale=de-DE in IE11
- Everything should render and function properly, and there should be no console errors.

2216 - Fix test page for IE11 compatibility [v4.19.x]

---

app/views/components/datagrid/test-filter-datetime-client-side.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Filter times on the filter row was not working.
Closes #2281 
1. Go to 'http://localhost:4000/components/datagrid/test-filter-datetime-client-side.html'
2. Filter by the time field, eg greater than 1:00 AM, 1:00 PM

2281 - Fix a datagrid filter issue on time  [v4.19.x]

---

test/components/datagrid/datagrid.e2e-spec.js
test/components/locale/locale.func-spec.js

Some tests became unstable on CI so ignore them for the CI run or fix them to use alternative time labels.
N/A
- Let tests run on CI

CI - Fix timezones [v4.19.x]

---

src/components/locale/locale.js

Sometimes http://localhost:4000/components/personalize/example-color-theme-api.html?locale=en-GB would not load in IE11 fixed this.
Fixes #2216 
http://localhost:4000/components/personalize/example-color-theme-api.html?locale=en-GB
- open that page in IE11
- open the console
- page should always load with dropdowns showing
- try it several times as the issue was intermittent
- try RTL for good measure http://localhost:4000/components/personalize/example-color-theme-api.html?locale=ar-SA

2216 - Fix slow loading IE11 issue [v4.19.x]

---

test/components/locale/locale.func-spec.js

This test was failing and i do not know why (only on CI). Tried to make it very tolerant rather than xit out.
NA
- builds pass
- nightly passes (have to merge an see?)

Makes a test more tolerant on CI

---

app/views/components/datagrid/test-export-performance.html
docs/CHANGELOG.md
src/utils/excel.js
test/components/datagrid/datagrid-api.func-spec.js

Fixed performance for export methods with datagrid.
Closes #2291
- Navigate to http://localhost:4000/components/datagrid/test-export-performance.html
- Click on button `Export to Excel` or `Export to CSV`
- It should not take too much longer time to export/download the file
**Other Details**

2291 - Fix performance for export methods with datagrid

---

app/views/components/datagrid/test-contextmenu-firstclick.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed datagrid contextmenu was not opening with first click
Closes #2398
- Navigate to http://localhost:4000/components/datagrid/test-contextmenu-firstclick.html
- Right click on one of the rows
- Context menu should pops correctly on the first try
- See console should not be any js error

2398 - Fix datagrid contextmenu first click [v4.19.x]

---

docs/CHANGELOG.md

Adds a missing change log entry
#2403

Add a change log entry for the tooltip undefined fix

---

src/components/colors/_colorpalette.scss
src/components/datagrid/_datagrid.scss
test/components/datagrid/datagrid-api.func-spec.js

Changes to https://github.com/infor-design/enterprise/pull/2353 introduced an issue in datagrid cell validation where the cell would get a solid fill.
Fixes #2397 
- go to http://localhost:4000/components/datagrid/test-editable-validation
- blank out a cell in the order date column
- styles should be the same again as 4.19 (not solid red)

2397 - Fix wrong validation styles in datagrid

---

app/data/compressors.js
app/views/components/datagrid/test-filter-datetime-client-side.html
app/views/components/datagrid/test-save-settings-serverside.html

Fixes two minor field qa issues.
Fixes #2281 
Fixes a comment on https://github.com/infor-design/enterprise/issues/2301?email_source=notifications&email_token=AAGGZS5AYZLMH3HQKEGG2VTP3IA4JA5CNFSM4HS4SEV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYBMIVQ#issuecomment-503497814
- in the console type `localStorage.clear()` and hit enter and then reload the page
- go to http://localhost:4000/components/datagrid/test-save-settings-serverside.html
- type 1.5 the quantity field (decimal will be allowed)
- go to http://localhost:4000/components/datagrid/test-filter-datetime-client- …

2281 - Fix some demo app issues with sorting

---

app/views/components/datagrid/test-editor-dropdown-source.html
src/components/locale/locale.js

Fix for some pages not loading in IE(s) based on incompatible commands.
Fixes #2444 
- load this page in IE Edge http://localhost:4000/components/datagrid/test-timezone-formats?layout=nofrills&locale=nl-NL
- load this page in IE 11 http://localhost:4000/components/datagrid/test-editor-dropdown-source

2444 - Fix some ie compatibility issues [v4.19.x]

---

app/views/components/calendar/example-index.html
docs/CHANGELOG.md
src/components/calendar/calendar.js
src/components/input/_input.scss
src/components/tooltip/_tooltip.scss
src/components/validation/validator.js

Allow Validation when entering or modifying a calendar event. 
Closes #1742 
1. Goto 'http://localhost:4000/components/calendar/example-index.html'
2. Double Click on a date to add an event 
3. type an invalid date in to the datepicker eg 33/33/3333
Also re-test 'http://localhost:4000/components/modal/example-validation.html'

1742 - Calendar: missing field validation 

---

app/views/components/popdown/test-contains-dropdown.html
docs/CHANGELOG.md
src/components/popdown/_popdown.scss
src/components/popdown/popdown.js
test/components/popdown/popdown.e2e-spec.js

This PR improves usability on the Popdown component when it contains Dropdown/Multiselects. There was previously an issue where the Popdown component would unexpectedly close when trying to use its child components.  These issues have been resolved.
Closes #2092
- Open http://localhost:4000/components/popdown/test-contains-dropdown.html
- Click the "Choose an Option" button to open the Popdown
- Click the Dropdown List to open it.
- Ensure that the Popdown hasn't closed.
- Choose an option from the Dropdown List.  It should close.
- Ensure that the Popdown still …

2092 - Fix Popdown/Dropdown Compatibility

---

test/components/datagrid/datagrid.e2e-spec.js

This PR temporarily skips a Datagrid e2e test, in order to get the nightly CRON job running.
n/a
- Pull branch
- Run app
- Run e2e tests
----
paging @pwpatton

Skip test to fix nightly

---

test/components/datagrid/datagrid.e2e-spec.js

Moved the localstoarge test to not run on CI since it was flaky. Could not reproduce the Visual regression failure could be random.
NA
- tests pass on branch

NA - Improve CRON tests

---

test/components/toast/toast.e2e-spec.js

Removed an e2e test because it covered by functional test for toast
N/A
The e2e tests should pass with no issue.

N/A - Remove an e2e test for toast

---

docs/CHANGELOG.md
src/components/personalize/personalize.js

Force to be light text on custom colors with Personalization.
Closes #2476
- Navigate to http://localhost:4000/components/homepage/example-hero-widget.html
- Click top right `...` action button to change theme/colors
- Inspect the text color should be easy readable

2476 - Fix light text on custom colors with personalization

---

app/views/components/datagrid/test-selected-rows-addnew.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed method selectedRows() was returning incorrect information when new row added via addRow() with datagrid.
Closes #1794
- Navigate to http://localhost:4000/components/datagrid/test-selected-rows-addnew.html
- Select row with id `3`
- Click on `Show Selected Rows`
- See console log
- Selected Rows Indexes [2]
- And check `Selected Rows` data 
- Click on `Add Row`
- Click on `Show Selected Rows`
- See console log again and now
- Selected Rows Indexes [3]
- Check `Selected Rows` data should be updated

1794 - Fix selection rows after add new row with datagrid

---

app/views/components/header/test-header-gauntlet.html
src/components/checkboxes/_checkboxes-uplift.scss
src/components/fileupload/_fileupload-uplift.scss

This PR fixes a few items flagged by Q/A related to the Uplift Theme changes.
Closes #2318 
Pull this branch, build, then run the demoapp
_To test the Fileupload changes:_
- open http://localhost:4000/components/fileupload-advanced/example-index.html?theme=uplift
- drag any file to the uploader area
- ensure that the "X" icon next to the filename appears centered against the filename text.
_To test the checkbox alignment on cards:_
- open http://localhost:4000/components/cards/example-group-action.html?theme=uplift
- scroll to the bottom of the list where checkboxes are lined up against …

2318 - More Uplift changes [v4.20.x]

---

app/views/components/bar/example-colors.html
app/views/components/bar/test-selected.html
src/components/datepicker/datepicker.js
src/components/listview/listview.js
src/components/locale/locale.js
test/components/bar/bar-grouped.e2e-spec.js
test/components/bar/bar-stacked.e2e-spec.js
test/components/bar/bar.e2e-spec.js
test/components/datagrid/datagrid-api.func-spec.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/datepicker/datepicker.e2e-spec.js
test/components/timepicker/timepicker.e2e-spec.js
test/components/validation/validation.e2e-spec.js
test/helpers/e2e-utils.js
test/protractor.ci.bs.conf.js
test/protractor.ci.conf.js
test/protractor.local.bs.conf.js

This PR improves the BS build process.
- Added sleep for one test
- Changed params to be correct on the url with variant and theme
- Removed sharding (as its easier to debug and more stable) the test runs at night anyways
- Change the chrome version to run latest
- NA
- tests pass, then we merge and see tonight

NA - Improve some browser stack tests

---

app/views/components/homepage/example-add-widget.html
docs/CHANGELOG.md
src/components/homepage/homepage.js

Fixed dynamically added widget was not positioning correctly with Homepage.
Closes #2425
- Navigate to http://localhost:4000/components/homepage/example-add-widget.html
- Click the button `Append Business Insight`
- See new widget should added to the end of the page

2425 - Fix dynamically added widget position with homepage

---

.travis.yml

The current Cron jobs are running both regular e2e tests and Browserstack e2e tests, making the run time super long.
n/a
1. Review the Travis config file. I cleaned it up and re-organized the if-statements so they make a little more sense and are at least in a logical order.
1. Look into the test logs and make sure there are not Travis errors on syntax. Note that you will not see the github "clone" stuff as I turned that logging to "quiet" to lessen our log length.
🚫  e2e or functional test for the bug or feature.
🚫  A note to the change log.

Travis ci updates

---

src/components/datepicker/datepicker.js
src/components/monthview/monthview.js

Fix a QA noticed on the new datepicker as explained in the steps.
Fixes #2557 
Issue 1
- go to  On http://localhost:4000/components/datepicker/example-index.html,
- Open date picker
- Open Month and Year dropdown, select any month and year, then click Select button, dropdown will close
-  Now click the Select button for the entire date picker. This is fixed it didnt close here
Issue 2
- go to http://localhost:4000/components/components/datepicker/example-range.html#
- Open date picker in "Range - No Initial value"
- Open Month and Year dropdown, select any month and year, click Select …

2557 - Fix select button [v4.21.x]

---

app/views/components/button/test-updated.html
docs/CHANGELOG.md
src/components/button/button.js
test/components/button/button-api.func-spec.js

Fixed updated method did not teardown and re-init with button control.
Closes #2304
- Navigate to http://localhost:4000/components/button/test-updated.html
- There should be an arrow icon with button `Normal Menu`
- Click on button `Update`
- Now it updates the api settings and should hide the arrow

2304 - Fix updated method with button control

---

src/components/datagrid/_datagrid.scss

Disabled, but selected row can be unselected though it is disabled
https://github.com/infor-design/enterprise/issues/1614
1. Create a datagrid which selectable entries
2. Make some of rows disabled, but selected
3. Deselecting rows which are disabled is possible but should not.

Adds pointer-event 'none' on disabled datagrid rows

---

app/data/events.json
app/src/sass/_grid.scss
app/views/components/datagrid/test-codeblock.html
app/views/components/signin/test-custom.html
src/components/applicationmenu/_applicationmenu.scss
src/components/calendar/_calendar.scss
src/components/datagrid/_datagrid.scss
src/components/dropdown/_dropdown.scss
src/components/input/_input.scss
src/components/listview/_listview.scss
src/components/listview/listview.js
src/components/monthview/_monthview.scss
src/components/skiplink/_skiplink.scss
src/components/toast/_toast.scss
src/components/toolbar/_toolbar.scss
src/components/tooltip/_tooltip.scss
src/layouts/_layouts.scss
src/patterns/stepprocess/_stepprocess.scss

Fixes an IE issue on #2719 
Also removed all `css-prop: initial` and retested them.
Fixed a regression in listview that the locale wont actually work.
Fixes #21719 
- in IE and Chrome: go to http://localhost:4000/components/datagrid/example-modal-datagrid.html 
-open the modal and ensure the select all checkbox is centered in the header
- in IE and Chrome: go to http://localhost:4000/components/datagrid/example-mixed-selection?theme=uplift&variant=light&colors=0563C2
- ensure the select all checkbox is centered in the header
- in IE and Chrome: 
- ensure …

2719 - Fix some IE issues and remove all of the css initial [v4.21.x]

---

src/components/dropdown/_dropdown.scss
test/components/icons/icons.e2e-spec.js

Fixes a qa issue on multiselect, because of i change i made some browser workarounds can be removed.
Fixes #2793 
- go to http://localhost:4000/components/multiselect/example-index.html
- open the list and select a few items, noting the checkbox layout
- test all browsers (IE, Edge, Firefox, Chrome, Safari)

2793 - Fix layout issues on multiselect [v4.21.x]

---

app/views/components/bar-grouped/test-selected.html
test/components/listbuilder/listbuilder.e2e-spec.js
test/components/personalize/personalize.e2e-spec.js
test/components/tabs/tabs-multi.e2e-spec.js

Saw some tests fail on cron, this addresses these issues.
N/A
- Tests on the checks pass

Improve a few tests

---

test/components/datepicker/datepicker.e2e-spec.js
test/components/tabs/tabs-multi.e2e-spec.js
test/protractor.ci.bs.conf.js

Change to more stable config and fix a couple unstable tests.

NA - Fix cron

---

src/components/locale/locale.js

Fixes a bug in regexp, missed an escape character
https://github.com/infor-design/enterprise/issues/2844
Put sohoxi.js in a folder structure looking something like this /../sohoxi/js/../sohoxi.js

2844: Adds a missing escape in regexp

---

app/views/components/contextualactionpanel/test-locale.html
app/views/components/datagrid/test-actions-reload.html
docs/CHANGELOG.md
src/behaviors/initialize/initialize.js
src/components/datagrid/datagrid.formatters.js
src/components/popupmenu/popupmenu.js
test/components/contextualactionpanel/contextualactionpanel.e2e-spec.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/editor/editor.e2e-spec.js

Patching:
https://github.com/infor-design/enterprise/issues/2876
https://github.com/infor-design/enterprise/issues/2873
Into a 4.21.2 to make homepages code cut.
Changes should be similar as before except the change log and merges

NA - Making a 4.21.2 patch release [v4.21.x]

---

app/views/components/datagrid/test-ellipsis.html

Fixed example page for text overflow ellipsis to date formatter with Datagrid.
Closes #2853
- Navigate to http://localhost:4000/components/datagrid/test-ellipsis.html
- Resize the column `Order Date`
- Should see ellipsis if the text overflow

2853 - Fix example for ellipsis to date formatter with datagrid

---

app/views/components/datagrid/test-expandable-row-custom-formatter.html

Added an example for 3054 to show it working.
Fixes #3054 
- checkout http://localhost:4000/components/datagrid/test-expandable-row-custom-formatter.html

3054 - Add a custom formatter example for expandable rows

---

app/views/components/toast/example-draggable.html
docs/CHANGELOG.md
src/components/toast/toast.js

Fixed saved position was not working for whole app with Toast.
Closes #3025
- Navigate to http://localhost:4000/components/toast/example-draggable.html
- Click on each button to show the toast message
- Drag and drop to different positions each
- Close and open page again, then open each toast message
- See each message should remain the saved position

3025 - Fix saved position with toast

---

src/components/dropdown/dropdown.js

Yet more fixes to 650 as the " could not be selected with the arrow.
Fixes #650 
- go to http://localhost:4000/components/dropdown/test-xss.html
- type "
- arrow down and select and this should work
NOTE: Some special characters like " and <> will not show highlighted. Cant seem to fix this without allowing xss to be injected so we will live with it not highlighting

650 - Fix selection of items with &quot [v4.23.x]

---

docs/CHANGELOG.md
src/components/datepicker/datepicker.js
src/components/monthview/monthview.js

Fixed selected date was getting cleared and creating js error after changing month or year in Umalqura date and Calendar with Datepicker.
Closes #3093
http://localhost:4000/components/datepicker/example-umalqura.html
http://localhost:4000/components/calendar/example-index.html
- Open date picker
- Open month and year dropdown, then select any year or month
- Click Apply button
- See in console, should not show any error

3093 - Fix selected date with datepicker [v4.23.x]

---

src/components/monthview/monthview.js

Fixed first day was always selected in umalqura date with Datepicker.
Closes #3093
- Navigate to http://localhost:4000/components/datepicker/example-umalqura.html
- Open date picker
- Only one date should be selected

3093 - Fix umalqura selected date with datepicker [v4.23.x]

---

docs/CHANGELOG.md
src/components/locale/cultures/fi-FI.js
test/components/locale/locale.func-spec.js

Some strings for dates in the fi-FI locale incorrectly had a one digit year (which doesnt work).
This fixes the issue
Fixes #3019 
- this is covered entirely by tests

3019 - Fix single digit dates

---

src/components/modal/_modal.scss

Fixed 2864 again so it works on IE edge / Uplift. Putting this here instead of 4.23 so as not to delay release for a minor cosmetic issue.
Fixes #2964 
- go to http://localhost:4000/components/message/example-index.html
- click success
- should be no scroll bar

2964 - Fix additional issue

---

app/data/events.json
app/views/components/accordion/example-accordion-panels.html
app/views/components/accordion/example-disabled.html
app/views/components/accordion/test-accordion-inner-pane-icon.html
app/views/components/tabs/test-expandables-inside.html
docs/CHANGELOG.md
src/components/accordion/readme.md
src/components/calendar/calendar-shared.js
src/components/calendar/calendar.js
src/components/datagrid/datagrid.editors.js
src/components/dropdown/dropdown.js
src/components/week-view/week-view.js
src/utils/xss.js
test/components/calendar/calendar.e2e-spec.js

This PR fixes the remained of QA issues. Also added a fix to remove an incorrect (deprecated icon). And merged an important dropdown fix that was added in master (this was erroring making dropdowns unusable in datagrid). This holds the remainder of 4.23 bugs.
Fixes #3154 
Fixes #3152 
Fixes #3126
Fixes #3153  
Fixes #2919  
**Issue 3154**
- open http://localhost:4000/components/datagrid/example-editable.html on IE 11
- press "Add Row Status"
- Should be no errors in the console and all status should show (not just the first when it errored out)
**Issue 3152**
- go to …

MISC - Remaining 4.23 issues [v4.23.x]

---

app/views/components/emptymessage/test-button-click.html
test/components/calendar/calendar.e2e-spec.js
test/components/week-view/week-view-api.func-spec.js

Fixes some tests that are changing on a week change to make them more stable.
Also adds a fix for #3140 since it wont load on IE 11
Just review contents, and tests should pass.
Fixes ##3140

3140 - Fix tests and IE bug

---

docs/CHANGELOG.md
src/components/applicationmenu/_applicationmenu-uplift.scss

This PR fixes the visible scrollbar in application menu even it's not needed in uplift theme.
Closes https://github.com/infor-design/enterprise/issues/3134
- Navigate to http://localhost:4000/components/applicationmenu/example-open-on-large.html?theme=uplift&variant=dark&colors=0563C2
- Application menu should not have scrollbar

3134 - Application Menu: Fix visible scrollbar when not needed

---

app/views/components/popover/example-extra-css-class.html

Small and quick fix for a minor demo app issue.
Fixes #3242
- go to http://localhost:4000/components/popover/example-extra-css-class.html?theme=uplift&variant=dark
- click the button
- text should be visible in the tooltip

3242 - Fix demo app issue

---

app/views/components/datagrid/test-group-editable-addrow.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed add row and load new data for grouping was not working with Datagrid.
Closes #2801
- Navigate to http://localhost:4000/components/datagrid/test-group-editable-addrow.html
- Select any row and click on toolbar button `Add Row` then try all options
- Should add new row fine
- And click on toolbar button `Load new Data`
- Should load new dataset

2801 - Fix add row or load new data for grouping with datagrid

---

docs/CHANGELOG.md
src/components/accordion/_accordion.scss

This PR fixes the inconsistency style of focus element after clicking on a certain dropdown.
Closes https://github.com/infor-design/enterprise/issues/3082
- Navigate to http://localhost:4000/components/accordion/example-index.html
- Click each accordion headers repeatedly.
- Focus style should be consistent and not blurry.

3082 - Fix focus style element 

---

docs/CHANGELOG.md
src/components/popupmenu/popupmenu.js

Fixed selected event was not firing when its parent partially overflowing with Autocomplete.
Closes #3072
- Navigate to http://localhost:4000/components/autocomplete/example-templates.html
- Open developer tools (make sure its dock to bottom)
- Enlarge developer tools so that the demo view is very small height and autocomplete partially hidden
- Search for `q` and select the option
- See console event should fire

3072 - Fix selected event with autocomplete

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.e2e-spec.js

Fixed converting circular structure to JSON was throwing error with Datagrid.
Closes #3309
- Navigate to http://localhost:4000/components/datagrid/test-save-settings.html
- Resize any column
- Reload Page
- Click on action button `...` in grid toolbar
- Choose `Reset to Default` in the menu
- It should reset the columns to original state
- And see console should not any error

3309 - Fix circular structure to json error with datagrid

---

app/views/components/datagrid/test-dropdown-empty-value.html
src/components/datagrid/datagrid.editors.js

Allow the dropdown value to be any falsy value, eg 0, '', null 
Closes #3313 
1. goto 'http://localhost:4000/components/datagrid/test-dropdown-empty-value.html'
2. change the dropdown value to the empty value 
Also retest #3137 , as this change was removed but I was unable to replicate the issue.

3313 - Datagrid Dropdown select empty value

---

docs/CHANGELOG.md
src/components/pie/pie.js

Fixed initial selection was getting error with Pie Chart.
Closes #3157
- Navigate to http://localhost:4000/components/pie/test-selected.html
- On page load, 2nd slice `After-tax Deductions (11%)` should be selected
- See on console make sure there is no errors

3157 - Fix initial selection error with pie

---

test/components/locale/locale.func-spec.js

Added a test for 2658 - which was found to now be working.
Fixes #2658 
- tests pass

2658 - Add a slovak test to prove its working

---

src/components/datepicker/datepicker.js
src/components/locale/locale.js
test/components/bar/bar.e2e-spec.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/listview/listview.e2e-spec.js
test/components/monthview/monthview.e2e-spec.js
test/components/popdown/popdown.e2e-spec.js
test/components/toolbar-flex/toolbar-flex-api.func-spec.js

Fixes a few leap year bugs and attempts to stabilize a few tests failing on master. If this passed OK, Good to go.

Fix and stabilze some tests and date bugs

---

package.json

Added icons for playing videos `icon-play, icon-record, icon-stop, icon-pause`. 
Change log entry was there when i first tried to fix this https://github.com/infor-design/enterprise/blob/master/docs/CHANGELOG.md#v4260-features
Closes #437
- see new icons on http://localhost:4000/components/icons/example-index.html

Add new "VCR" icons

---

app/views/patterns/module-tabs.html

**Failed QA** Removing additional theme switcher.
Closes https://github.com/infor-design/enterprise/issues/3312
Related PR https://github.com/infor-design/enterprise/pull/3409
- Navigate to http://localhost:4000/patterns/module-tabs.html
- Go to different module tabs.
- The two tabs should not have theme switcher

Failed QA/3312 - Remove additional theme switcher

---

src/components/calendar/calendar-shared.js

Fixed duration was not working when event for more than one day and all day checked with Calendar.
Fixes #3222
- Navigate to http://localhost:4000/components/calendar/example-index.html
- Change to `December 2019`
- Double click on day `23`
- Make sure `All Day` should be checked
- From: `12/23/2019` To: `12/25/2019`
- Click on button `Submit` to create new event
- See on side in event info window duration should be `3 Days`

3222 - Fix duration for all day with calendar

---

app/views/components/popover/example-index.html
src/components/datagrid/_datagrid.scss

Quick fix
NA
- go to http://localhost:4000/components/datagrid/example-multiselect.html
- select one row
- the header partial checkbox should not be off 1px

Quick fix to datagrid header partial checkbox

---

package.json
src/components/checkboxes/_checkboxes-uplift.scss
src/components/checkboxes/_checkboxes.scss

Added fixes for #3511 and #3507 
Fixes #3511
Fixes #3507 
- go to http://localhost:4000/components/radios/example-index.html?theme=uplift&variant=dark
- the disabled option should not be a white blob
- go to http://localhost:4000/components/checkboxes/example-horizontal.html
- check the last checkbox
- dirty indicator should be aligned

Quick bug fixes

---

app/views/components/textarea/example-autogrow.html

QA found an issue in the textarea autogrow but it turned out simple.
Fixes #3504 
- go to http://localhost:4000/components/textarea/example-autogrow.html?theme=soho&variant=dark
- change theme
- the scroll bar should stay 
(Actual problem was the button was wired to fire on any button click)

3514 - Fix a demo app issue

---

src/components/datagrid/datagrid.js

Fixed expandable row height was not aligning if row height changed while expandable row opened to frozen columns with datagrid.
Closes #3516
http://localhost:4000/components/datagrid/test-expandable-row-frozen-expandrow-all-cells.html
http://localhost:4000/components/datagrid/test-expandable-row-frozen-columns-bothsides.html
- Expand the any row by clicking `+` button
- Expanded row should not be misaligned
- Try changing small or medium row height, while expandable row opened

3516 - Fix expandable row height to frozen columns with datagrid [v4.26.x]

---

docs/CHANGELOG.md
src/components/spinbox/spinbox.js
test/components/spinbox/spinbox-api.func-spec.js

When calling spinbox enable. The readonly attribute wasn't removed.
Fixes #3536
- covered by tests

3536 - Fix enable in spinbox

---

app/views/components/bar-grouped/test-single-group.html
src/components/bar/bar.js
test/components/popupmenu/popupmenu.e2e-spec.js

Fixed if the dataset length is one, the bar grouped chart was generating script error.
Closes #3505
- Navigate to http://localhost:4000/components/bar-grouped/test-single-group.html
- See chart should render fine
- See console there should not be any error

3505 - Fix bar grouped chart render [v4.25.x]

---

app/views/components/homepage/example-editable.html
src/components/homepage/homepage.js

Closes #3531 
Test functionality in IE11
Previously submitted

3531 - Fixed IE11 issues

---

test/components/message/message.e2e-spec.js
test/components/tabs/tabs.e2e-spec.js
test/components/tag/tag.e2e-spec.js
test/components/timepicker/timepicker.e2e-spec.js

Trying to stabilize the cron. Still.
- if this passes we can merge

Fix more cron tests

---

app/views/components/swaplist/example-index.html
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js
src/components/lookup/lookup.js
test/components/datagrid/datagrid.e2e-spec.js
test/components/swaplist/swaplist-beforeswap.func-spec.js

FIxed two QA bugs, one was a regression the other i thought was but turned out it wasnt but fix was easy anyways.
Fixes #3678
Fixes #3677 
**Issue 3678**
- Go to http://localhost:4000/components/datagrid/example-paging.html
- Try to filter on contains "Product Id" : "9" -> should work again
**Issue 3678 - RETEST 3624**
- pull and build this branch
- copy it to master of enterprise-ng
- go to http://localhost:4200/ids-enterprise-ng-demo/lookup
- in the last input (Products (Async Results) Multi Select) open the lookup
- pick something on the first page and something on the second
- hit …

3678 - Fix datagrid QA issues [v4.27.x]

---

src/components/field-filter/_field-filter-uplift.scss

Fixed fields were unaligned in Uplift theme with Field Filter.
Closes #3687
- Navigate to http://localhost:4000/components/field-filter/test-initially-hidden.html?theme=uplift&variant=light
- See all the fields, should be aligned

3687 - Fix unaligned fields with field filter [v4.27.x]

---

app/views/components/contextualactionpanel/example-jquery.html
app/views/components/contextualactionpanel/example-markup.html
src/components/calendar/calendar.js
src/components/datepicker/datepicker.js
src/components/place/place.js
src/components/toolbar/_toolbar.scss
src/components/tooltip/tooltip.js

This PR fixes a few QA items added in the syncle.
Fixes #3701
Fixes #3700
Fixes #3699
Fixes #3598
Fixes #3696
**Issue 3701**
* go to http://localhost:4000/components/calendar/example-index.html
* open and pick a date from the top toolbar 's date picker -> should select this date
* try this again
* do that more times (fix is it only worked first time)
**Issue 3700**
* go to http://localhost:4000/components/contextualactionpanel/example-markup.html?theme=soho&variant=contrast and also http://localhost:4000/components/contextualactionpanel/example-jquery.html?theme=uplift&variant=contrast
* …

MISC- Add calendar and one CAP qa fixes [v4.27.x]

---

app/data/orgstructure-children.js
app/data/orgstructure-large.js
app/data/orgstructure-lazy.js
app/data/orgstructure-paging.js
app/views/components/blockgrid/example-mixed-selection.html
app/views/components/blockgrid/example-multiselect.html
app/views/components/blockgrid/example-paging.html
app/views/components/blockgrid/example-singleselect.html
app/views/components/datagrid/test-iconfile-buttons.html
app/views/components/datagrid/test-images.html
app/views/components/hierarchy/example-single.html
app/views/components/hierarchy/test-two-children-lazy.html
app/views/components/hierarchy/test-two-children-org.html
app/views/components/hierarchy/test-two.html
app/views/components/images/example-photos.html
app/views/components/personalize/example-form2.html
app/views/components/personalize/test-form2-short.html
app/views/includes/applicationmenu-all-chevrons.html
app/views/includes/applicationmenu-all-plusminus.html
app/views/includes/applicationmenu-hcm-icons.html
app/views/includes/applicationmenu-hcm.html
app/views/includes/applicationmenu-personalized-role-switcher-long-title.html
app/views/includes/applicationmenu-personalized-role-switcher.html
app/views/includes/applicationmenu-personalized-roles.html
app/views/includes/applicationmenu-personalized.html

Adds a basepath to some images so that on all the sites images will load.
Fixes #2601
- look for missing images on the following pages (or trust me)
http://localhost:4000/components/blockgrid
http://localhost:4000/components/hierarchy
http://localhost:4000/components/applicationmenu

2601 - Fix missing demo app links

---

docs/CHANGELOG.md
package.json

Added new locked/unlocked icons to `ids-identity`. This PR updates the `ids-identity` package in EP
closes #3732 
- Pull branch
- `npm install`
- Check http://localhost:4000/components/icons/example-index.html?theme=uplift&variant=light and http://localhost:4000/components/icons/example-index.html
- Make sure the locked/unlocked icons match the icons linked to in #3732 

3237 - Update ids-identity

---

app/views/components/tree/test-update-node-with-children.html
docs/CHANGELOG.md
src/components/tree/tree.js
test/components/tree/tree.e2e-spec.js

Fixed where use `UpdateNode()` method the data was not sync with Tree.
Closes #3724
- Navigate to http://localhost:4000/components/tree/test-update-node-with-children.html
- Use top buttons `updateNode()` and `removeNode()` to see in action
- See last node in tree, console log
- go to http://localhost:4000/components/tree/example-sortable.html
- try and drag items and should be no errors now.

3724 - Fix data sync for update node with tree

---

app/views/components/datagrid/test-tree-serializer.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixed row data was not available for serializer with Treegrid Datagrid.
Closes #3663
- Navigate to http://localhost:4000/components/datagrid/test-tree-serializer.html
- Click on any cell in column `Description` to get in edit mode
- Press `Enter` key or click somewhere else to go out from edit mode
- See the cell content become `Uppercase` (edit content will not update, it always use original content)

3663 - Fix serializer row data with treegrid datagrid

---

app/views/components/tree/test-children-data-select-multiple.html
app/views/components/tree/test-children-data.html
docs/CHANGELOG.md
src/components/tree/tree.js

Fixed data was not in sync for children property with Tree.
Closes #1690
- Navigate to:
- http://localhost:4000/components/tree/test-children-data.html
- http://localhost:4000/components/tree/test-children-data-select-multiple.html
- Click `Node 2` to toggle node
- Click on button `Show Data`
- See console in `Data` for `children` property should not be removed

1690 - Fix data sync for children property with tree

---

docs/CHANGELOG.md
src/components/notification/_notification.scss

Fixes an issue where the icon position was lagging in the notification animation. This PR converts the layout of notification to flex box and removes the need to use position absolute on the icons.
closes #2099 
- pull this branch, run and build
1).
- go to http://localhost:4000/components/notification/example-index.html
- refresh page and make sure the icon position doesn't lag when the notifications animate in.
2).
- npm link this branch in the ng repo
- go to http://localhost:4200/ids-enterprise-ng-demo/notification
- click the "Show Notification Alert" button
- make sure the icon …

2099 - Fix Notification icon animation lag

---

src/components/modal/_modal-uplift.scss
src/components/switch/_switch.scss

Fixed two minor regression issues.
Fixes #3868
Fixes #3867
- go to http://localhost:4000/components/message/example-index.html?theme=uplift&variant=light
- click each button. the icon and test should look more balanced now and not be cut off
- go to http://localhost:4000/components/switch/example-index.html in IE11
- the switch should not show an extra element inline at the end of the text

3867 - Fix tag and switch issue [v4.28.x]

---

app/views/components/calendar/example-index.html
src/components/calendar/calendar.js

Fixes a couple regressions on the calendar after adding a mobile view.
Fixes #3874
Fixes #3875
- click on a day to see the popup -> the buttons should look ok and not be scrolled down
- click on + and then click Add Event (API) -> a event should again be shown.

3874 - Fix templating and rendering issues [v4.28.x]

---

docs/CHANGELOG.md
src/components/form/readme.md
src/components/input/readme.md

Fixes incorrect relative links in the form readme.md file. This is part of an issue in the [website](https://github.com/infor-design/website/issues/818).
related to website[#818](https://github.com/infor-design/website/issues/818)
- pull branch
- open `src/components/form/readme.md` and make sure the relative links in the "Layout Classes" section begin with `./demo/components/`

Fix form readme links

---

docs/CHANGELOG.md
src/components/splitter/_splitter-uplift.scss
src/components/splitter/_splitter.scss
src/components/splitter/splitter.js
src/themes/theme-soho-contrast.scss
src/themes/theme-uplift-contrast.scss

Fixes an issue where the drag handle characters sometime render incorrectly. Changes the drag handle to an svg icon.
closes #1458 
- pull and build branch
- go to http://localhost:4000/components/splitter and check the examples. Make sure the drag handle is rendering properly.

1458 - Splitter drag handle icon

---

app/src/sass/layouts/_embedded.scss
docs/CHANGELOG.md
src/components/personalize/readme.md

The design site had some issues in the iframes with height. This fixes it.
Fixes #878
- try pages in embedded mode and look for issues like:
http://localhost:4000/components/homepage/example-index.html?theme=uplift&variant=light&layout=embedded
http://localhost:4000/components/form/example-forms.html?theme=uplift&variant=light&layout=embedded
http://localhost:4000/components/dropdown/example-index.html?theme=uplift&variant=light&layout=embedded
- try some other random pages

878  - Fix demo app issues

---

docs/CHANGELOG.md

As per https://github.com/infor-design/enterprise/issues/3756 just added a note on ending IE 11 support. Have a look for any corrections, plz

3756  - Add IE 11 heads up to change log

---

app/views/components/splitter/example-splitter-right-custom-width.html
app/views/components/splitter/test-fixed-size-parent.html
app/views/components/splitter/test-iframes.html
docs/CHANGELOG.md
src/components/splitter/_splitter.scss
src/components/splitter/splitter.js

Fixed dragging for RTL direction was not working with Splitter.
Closes #1813
- Navigate to: http://localhost:4000/components/splitter/example-index.html?locale=ar-SA
- Splitter should drag the proper direction
- Fixed iframe example
- Should drag fine http://localhost:4000/components/splitter/test-iframes.html
- Also see other examples here: http://localhost:4000/components/splitter

1813 - Fix splitter for rtl direction

---

app/data/events.json
app/views/components/calendar/test-allow-single-pane.html
app/views/components/calendar/test-overlaping-events.html
docs/CHANGELOG.md
src/components/calendar/_calendar.scss
src/components/calendar/calendar.js
test/components/calendar/calendar.e2e-spec.js

Made a fix for #3773 and then added a couple other fixes as well. The fixes are detailed in the steps.
Fixes #3773
Fixes #2779
Fixes #1725
**Issue 3773**
- go to http://localhost:4000/components/calendar/test-allow-single-pane.html
- this example is set so that the active event has a bunch of events
- in the event section on the right you can be setting only expand one at a time. try and toggle sections and the other should close as per default accordion functionality
- (note this is optional and only enabled on this example)
**Issue 2779**
- go to …

3773 / Misc - Add several calendar fixes

---

app/views/components/column/test-axis-y-format-integer.html
docs/sitemap.yml
src/components/lookup/lookup.js

- Changed an example to show locale/formatting
- Removed a prop that made no sense
- Made all docs components not "unclassified"
None
- just review PR content

Misc - Add new examples and docs cleanup

---

src/components/dropdown/_dropdown-uplift.scss
src/components/dropdown/_dropdown.scss

Fixes Multiselect compact mode issues found in QA
closes #4139 
- Go to http://localhost:4000/components/multiselect/example-compact.html
- Make sure the fields with tags are rendering properly in compact mode in both themes
- Should longer see any of the arrow/close button alignment issues found here https://github.com/infor-design/enterprise/issues/4139#issuecomment-661693677

4139 - Multiselect compact mode QA fixes

---

app/views/components/datepicker/test-modal-no-autofocus.html
test/components/datepicker/datepicker.e2e-spec.js

Adds a test as promised for a case that broke in LM.
Fixes #4090
- review the test
- ensure it passed

4090 - Add scrolling test

---

app/views/components/contextualactionpanel/example-workspaces.html

Recent cap changes "broke" this example so changed it around to work.
Fixes #4187
- go to http://localhost:4000/components/contextualactionpanel/example-workspaces.html
- click in chrome dev tools and make it a mobile device like Moto G4
- click the button to open
- button text should be visible
- clicking buttons should close

4187 - Fix demo app bug

---

app/src/js/routes/directory-list.js
app/views/components/datagrid/test-columnsizing-header-small.html
src/components/datagrid/datagrid.js

Fixed two issues as follow up from previous PRs
NA
- pull and restart the demo app
- go to http://localhost:4000/components -> page should have a page-layouts folder
- go to http://localhost:4000/components/page-patterns -> page should not show the layouts folder
- go to http://localhost:4000/components/datagrid/test-columnsizing-header-small
- i found that using ellipsis text on the header needed a few pixels or header or all column sizing will cut off prematurely. this example page should look ok now

Misc - Add fix for datagrid header and layout folders

---

app/data/events.json
app/views/components/calendar/test-event-color-override.html
app/views/components/datepicker/example-legend.html
docs/CHANGELOG.md
src/components/calendar/calendar-shared.js
src/components/calendar/calendar.js
src/components/calendar/readme.md
test/components/calendar/calendar.e2e-spec.js

Added some color customization settings to calendar.
Fixes #3923
Fixes #3893
- go to http://localhost:4000/components/calendar/test-event-color-override.html
- the two events have custom colors outside of the legend colors...
- 4 days have custom background colors
- the weekends are disabled

3923/3893 - Added color override settings

---

app/views/components/validation/test-error-on-tab-vertical.html
docs/CHANGELOG.md
src/components/tabs-vertical/_tabs-vertical.scss
src/components/tabs/tabs.js

Fixed the error icon was misaligning with Vertical Tabs.
Closes infor-design/enterprise-ng#873
- Navigate to: http://localhost:4000/components/validation/test-error-on-tab-vertical.html
- Go to each tab (`Test Information`, `KPIs`, `Excluded Vendors`).
- Find the Field `Email Address` and make validation error on it.
- See the validation indicator on tabs, should be aligned properly.

873 - Fix misaligned error icon with vertical tabs

---

docs/CHANGELOG.md
src/components/dropdown/dropdown.js

This in combination with a NG PR (to follow) fixes an issue as noted in https://github.com/infor-design/enterprise-ng/issues/885
Fixes https://github.com/infor-design/enterprise-ng/issues/885
- follow steps on NG PR
- smoke test dropdown and multiselect pages (ajax particularly and updates)

885 - Fix dropdown selection issue in NG [v4.31.x]

---

src/components/datepicker/_datepicker.scss

Fixes IPhone Pro QA issues
Fixes #4169
Fixes #4238
Fixes #4168
- go to http://localhost:4000/components/datepicker/example-index.html on browser stack iphone pro
- open picker and dates should look nice
- open date / year panel and should be aligned
- open http://localhost:4000/components/datepicker/example-range.html
- colors should look ok

Misc - Datepicker fixes [v4.31.x]

---

docs/CHANGELOG.md

Looks like there were some duplicate changelog comments and they were our of order. This PR gets the changelog in order
n/a
- Check the changelog for any mistakes that might have occured

Fix Changelog (v4.32.0 Fixes)

---

docs/CHANGELOG.md
src/components/locale/cultures/he-IL.js
src/components/locale/cultures/hi-IN.js
src/components/locale/cultures/hr-HR.js
src/components/locale/cultures/it-IT.js
src/components/locale/cultures/la-IT.js
src/components/locale/cultures/zh-Hant.js
src/components/locale/cultures/zh-TW.js
src/components/locale/locale.js
test/components/locale/locale.func-spec.js

Some datetime and timezone formats did not match the short portion of the format. While testing also fixed an issue with some timezones not formatting properly. This can only be review by reviewing the passing tests.
Fixes #4297
- tests pass
- manually check PR - expected output is as expected

4297 - Fixed issues with some datetime and timezone formats

---

app/views/components/colorpicker/example-sizes.html
docs/CHANGELOG.md
src/components/colorpicker/_colorpicker-uplift.scss
src/components/colorpicker/_colorpicker.scss

Noticed the color picker could not be 300px and the sizes were off. So added a fix.
Fixes #4310 
- go to http://localhost:4000/components/colorpicker/example-sizes.html
- compare widths to http://localhost:4000/components/dropdown/test-sizes.html
- also test uplift

4310 - Fix color picker sizes

---

app/views/components/page-patterns/test-stepprocess.html
docs/CHANGELOG.md
src/components/stepprocess/_stepprocess.scss

Restored the step process as a hidden test page with no references or docs any place. Doing so i fixed two bugs in it. 
Fixes #4249
Fixes #4248
- go to http://localhost:4000/components/page-patterns/test-stepprocess.html
- ensure the left "tree" looks ok without 20px padding
- size the page shorter - make sure you can now scroll both sides

4249 - Add step process fixes

---

docs/CHANGELOG.md
src/components/calendar/calendar.js

Fixes #4439 
- click an event to open the add event dialog
- pick admin or any non default type (try all 4)
- hit enter
- see the the event color matches the legend as selected

4439 - Fix Event color [v4.33.x]

---

app/views/components/wizard/example-index.html
docs/AUTOMATION.md
docs/CHANGELOG.md
src/components/wizard/readme.md

Added the ids to wizard (since it has its links exposed it just needed an example)
Part of #4498
- just review the PR contents

4498 - Add ids for wizard

---

.github/workflows/ci.yml
docs/CHANGELOG.md
src/components/badges/_badges-uplift.scss
test/components/modal/modal.func-spec.js
test/helpers/e2e-config.js

Fixed alignment issues in badges. Also testing the new build checks with a simple PR.
Fixes #4578
- http://localhost:4000/components/badges/example-index.html
- test the text alignment is roughly centered
- check in uplift, soho theme and all 3 modes/variantes

4578 - Added alignment fixes to badges

---

src/components/locale/cultures/fi-FI.js

Was told by a finish user the months names are off so fixed them.
- review PR

NA - Fix finish dates

---

README.md

Adding some comments to test PR and merge

IGNORE: Adding some comments to test PR

---

docs/ACCESSIBILITY.MD
docs/AUTOMATION.md

Check pr merge

---

app/views/components/tree/example-ajax.html
docs/CHANGELOG.md
src/components/tree/tree.js

Fixed character entity references were render differently for parent and child levels with Tree.
Closes #4512
- Navigate to: http://localhost:4000/components/tree/example-ajax.html
- See 1st node text (should have less than sign)
- Click on 2nd node to open folder
- See 1st node text in that folder (should have less than sign) too

4512 - Fix character entity references with tree

---

app/views/components/fileupload-advanced/example-index.html
src/components/fileupload-advanced/fileupload-advanced.js
test/components/applicationmenu/applicationmenu.e2e-spec.js
test/components/homepage/homepage.e2e-spec.js

The file upload example init'd twice.
Fixes #4657
- go to http://localhost:4000/components/fileupload-advanced/example-index.html
- should only be one file upload on this page

4657 - Fix file upload example

---

src/components/colorpicker/colorpicker.js
test/components/applicationmenu/applicationmenu.e2e-spec.js
test/components/toolbar/toolbar-searchfield.e2e-spec.js

The editor color picker was throwing an error. This is a fix which i will also put on 4.35.x
Fixes #4658
http://localhost:4000/components/editor/example-index.html#
- select some text
- try and change the color with the picker
- should not error in the console and should work

4658 - Fix color picker editor bug (4.35.x)

---

app/src/js/middleware/cmd-params-handler.js
app/src/js/middleware/option-handler.js
app/views/includes/head.html
docs/CHANGELOG.md
src/components/locale/locale.js
test/components/locale/locale.e2e-spec.js

Fixes #4668
Should be able to use Locale.set() whether d3.js is included or not

4668 - Check for existence of d3 before attempting to use it to set locale

---

app/views/components/datagrid/test-lookup-filter-click-clear.html
docs/CHANGELOG.md
src/components/lookup/lookup.js
test/components/datepicker/datepicker.e2e-spec.js

Fixes #4693
- go to http://localhost:4000/components/datagrid/test-lookup-filter-click-clear
- click on the lookup -> it will populate the lookup field and show the X (no filtering will happen as this wasnt the point)
- click on the clear X 
- check the console and you can see that the clear callback was called

4693 - Add new clear callback to lookup

---

app/views/components/homepage/example-six-column.html
app/views/components/homepage/test-add-remove-widget.html
app/views/components/homepage/test-small-add-remove-widget.html
app/views/components/homepage/test-small-column-five.html
app/views/components/homepage/test-small-column-six.html
app/views/components/homepage/test-small-editable.html
app/views/components/homepage/test-small-scenario-d.html
app/views/components/homepage/test-small-scenario-f.html
app/views/components/homepage/test-small-scenario-l.html
docs/CHANGELOG.md
src/components/cards/_cards-uplift.scss
src/components/cards/_cards.scss
src/components/homepage/_homepage.scss
src/components/homepage/homepage.js

Added support for small size (260x260) widgets and six columns with Homepage.
Closes #4663
Closes #4686
Examples added for small widgets (260x260)
- http://localhost:4000/components/homepage/test-small-add-remove-widget.html
- http://localhost:4000/components/homepage/test-small-column-five.html
- http://localhost:4000/components/homepage/test-small-column-six.html
- http://localhost:4000/components/homepage/test-small-editable.html
- http://localhost:4000/components/homepage/test-small-scenario-d.html
- …

4663 - Add support for small widgets and six columns with homepage

---

docs/CHANGELOG.md
src/components/wizard/_wizard.scss
test/components/input/input.e2e-spec.js

Adds a fix as noted on #4714 to fix a layout issue in RTL
Fixes #4714
- go to http://localhost:4000/components/wizard/example-index.html?locale=he-IL
- active step's double border should be aligned

4714 - Fix a layout issue in RTL

---

app/views/components/datagrid/test-lookup-filter.html
src/components/datagrid/_datagrid-uplift.scss

Adds yet additional fix for 4693
Fixes #4693
- go to http://localhost:4000/components/datagrid/test-lookup-filter
- check X alignment in header
- test in uplift mode
- test in uplift mode on safari and in "Responsive Design Mode" -> iphone 8 plus

4693 - Add fix for uplift mode

---

app/views/components/tabs/test-info-message-and-icon.html
docs/CHANGELOG.md
src/components/modal/_modal-uplift.scss
src/components/tabs/_tabs-horizontal.scss
src/components/tabs/_tabs-uplift.scss
src/components/tabs/_tabs.scss

Fixes the info icon and info message in tabs component.
Issues:
- info icon is overlapping on tab
- Info message is not visible
Closes https://github.com/infor-design/enterprise/issues/4711
- Go to http://localhost:4000/components/tabs/test-info-message-and-icon.html
- Click `Add Context` button
- In the input field, type `Test` to trigger the info message and icon (In this test page, I already included the custom script to show those)
- Test this also on uplift
- `info icon` should perfectly align with the tab
- `info message` should be visible …

4711 - Fix tab info icon and info message

---

app/views/components/bar-grouped/test-custom-tooltip.html
app/views/components/column-grouped/example-custom-tooltip.html
docs/CHANGELOG.md
src/components/bar/bar.js
src/components/column/column.js

Fixed custom tooltip data with bar grouped and column grouped chart.
Closes #4548
- Navigate to:
- http://localhost:4000/components/bar-grouped/test-custom-tooltip.html
- http://localhost:4000/components/column-grouped/example-custom-tooltip.html
- Hover on any bar in chart
- See in console for data info
- Should have right data in tooltip
- Hover over few times on each bar and each group
- It should have right data log in console and tooltip every time

4548 - Fix custom tooltip data with bar grouped and column grouped chart

---

app/views/components/line/test-reduce-axis-points.html
package.json
src/components/searchfield/_searchfield-uplift.scss
src/components/searchfield/searchfield.js
test/components/hierarchy/hierarchy.e2e-spec.js
test/components/icons/icons.e2e-spec.js
test/components/tooltip/tooltip.func-spec.js

Fixes a follow up issue with the search field tabbable setting added recently. The issue is it wont work for collapsible search so QA found a place i needed to disable it on.
Also added a approved and approved-filled icon from design by bumping the ids-design version
Fixes #4835
Fixes #4775
- http://localhost:4000/components/datagrid/example-custom-toolbar-flex.html
- tab in and click in the search field
- tab out
- x will not get focus on tab and should look aligned.

4835 - Follow up qa fix to tabbable

---

docs/CHANGELOG.md
src/components/emptymessage/emptymessage.js

Added an off to clear out any existing event handlers on the buttons in empty message
Fixes #4889
- you cant test this its only in landmark 

4889 - Fix double event handlers

---

README.md
scripts/build.js
test/components/dropdown/dropdown-updates-events.func-spec.js

- Testing actions with a simple PR adding a section to the docs.
- Also remove some clutter from the build log
- And attempt to fix dropdown tests

Misc: Fix dropdown tests and clutter

---

app/views/components/datagrid/test-frozen-columns-flex.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss

Fixes an issue of a missing scrollbar when the grid is in a scroll-flex type container
Fixes #4912
- go to http://localhost:4000/components/datagrid/test-frozen-columns-flex
- resize the page so scrollbars appear
- Y scrollbar should not be missing

4912 - Add fix for scrolling in a scroll flex

---

docs/CHANGELOG.md
src/utils/environment.js

When performing the checks on **Class-based detection for IE** the regular expression search criteria was not correct. Once updated from **Edge** to **Edg** it's now showing the proper details for MS Edge. Also, the version offset needed to be adjusted from +5 to +4 to return the correct version number. 
Fixes #4603
Include:
- Navigate to the following URL (http://localhost:4000/components/environment/example-browser-specs.html)
- Once the browser spec page loads you can now see the given environment details. 
- Screen shots from browserstack.com testing fixed issues. The OS and version …

4603 environment edge is not detected

---

src/components/datagrid/datagrid.js

Updated some docs on the saveUserSetting in datagrid as mentioned on #4969
Closes #4969
- review the content for errors

4969 - Update the docs for save user settings

---

app/views/components/bar-grouped/test-double-click.html
app/views/components/bar-stacked/test-double-click.html
app/views/components/bar/test-double-click.html
docs/CHANGELOG.md
src/components/bar/bar.js
src/components/charts/charts.js
test/components/bar/bar-api.func-spec.js
test/components/bar/bar-stacked.e2e-spec.js
test/components/bar/bar.e2e-spec.js

Added support for double click with Bar, Bar Grouped, Bar Stacked.
Fixes #3229
- Navigate to:
- http://localhost:4000/components/bar/test-double-click.html
- http://localhost:4000/components/bar-grouped/test-double-click.html
- http://localhost:4000/components/bar-stacked/test-double-click.html
- Click single/double on any bar
- See logs in console
- Single click `selected` and double `double clicked` event

3229 - Add support for double click with Bar, Bar Grouped, Bar Stacked

---

app/views/components/pie/example-index.html
docs/CHANGELOG.md
src/components/bar/bar.js
src/components/charts/charts.js
src/components/datagrid/datagrid.js
src/components/line/line.js
src/components/pie/pie.js

I added a destroy method inside of the charts objects that will check the type of chart being used and adjust the class name based on it. This method will run right before the **this.init()** that contains the chart build logic.
Fixed https://github.com/infor-design/enterprise/issues/3144
Include:
- Navigate to the any of the chart components, for this sample I have used the pie chart.
(http://localhost:4000/components/pie/example-index.html)
- Right click and select the inspect, then navigate to the console.  
- Paste in the follow code snippet inside the console to change the chart as …

439 changing the chart type doesnt remove old class name issue 3144

---

docs/CHANGELOG.md
src/components/editor/_editor.scss
src/components/popupmenu/popupmenu.js

Fixed the wrapping in editor of links as it was easy and saw it during triage. Also fixed on part of https://github.com/infor-design/enterprise/issues/5117 in order to test it
Fixes #5145 
- go to http://localhost:4000/components/editor/example-index.html 
- select all the second or first paragraph
- click the link button to make it a link and hit apply -> it should now wrap
- also resize the page shorter so the toolbar goes into overflow mode and shows the ... menu

5145 - Fix anchor wrapping and popup

---

app/views/components/datagrid/test-frozen-columns-resizable-with-colspan.html

Adds a new test case for #5115 but wasnt able to reproduce.
Fixes #5115

5115 - Adds a new example for 5115

---

docs/DEVELOPER.md

Minor addition in documentation: instructions to auto launch and close demo and app servers with `enterprise` as that requires two CMD windows or background daemon otherwise, which is tedious to manage switching between `enterprise-wc` for some users (such as myself)
(+ had stashed for a while, just thought useful to push this before forgetting)
N/A
- Open VSCode => DEVELOPER.md file
- preview and see it's not formatted terribly
- (Optional) `Command + Shift + P` (Mac) => Type "Tasks: Allow Automatic Tasks in Folder" and Click the option to allow auto running tasks
- (Optional) reset IDE …

doc: DEVELOPER.md/ auto running env in VSC section + tweak header

---

app/views/components/form/example-compact-mode.html

Woops , i broke the compact form example. We had put in a better fix for it submitting so put this back as it was so the demo works.
Fixes #5155 
- go to http://localhost:4000/components/form/example-compact-mode.html
- click the toggler button
- the inputs should toggle to larger mode

5155 - Add fix to the compact form example

---

app/views/components/datagrid/test-change-selectable-with-frozen-columns.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This PR fixes changing the selection mode between single and mixed on a Datagrid with frozen columns were not properly rendered on UI.
Closes https://github.com/infor-design/enterprise/issues/5067
- Go to http://localhost:4000/components/datagrid/test-change-selectable-with-frozen-columns.html
- Click `Switch Select Mode`
- Datagrid should render the UI correctly

5067 - Fix changing selectable setting when have frozen columns

---

.eslintrc.js
.github/workflows/ci.yml
src/components/colorpicker/colorpicker.js
src/components/list-detail/list-detail.js
src/components/modal/modal.js
src/utils/renderloop.js
test/components/breadcrumb/breadcrumb.e2e-spec.js
test/components/button/button.e2e-spec.js
test/components/datagrid/datagrid.e2e-spec.js

This pr fixes some lint issues that cropped up with new eslint released
NA
- build should pass all checks

Misc: Fix lint issues

---

package.json
src/components/field-options/_field-options-new.scss
src/components/field-options/_field-options.scss

Follow up fix for close trigger in fileupload with field options.
Closes https://github.com/infor-design/enterprise/issues/5138
- Go to http://localhost:4000/components/field-options/example-index
- go to fileupload section
- Open fileupload and select anything
- Click the fileupload to check the alignment with the field
- Close icon and field options should align correctly
- Test on Compact Mode

5138 - followup fix for UI issues with field options

---

src/components/cards/_cards-new.scss
src/components/cards/_cards.scss

This PR is a follow update on Card Variations and Hitboxes
Closes https://github.com/infor-design/enterprise/issues/5250
- Go to http://localhost:4000/components/cards/example-variations-hitboxes.html
- Check the cards

5250 - Fix Button Focus Issue on Card Classic Theme

---

docs/CHANGELOG.md
src/components/slider/slider.js

This PR fixes the NaN value showing on tooltip in sliders.
Closes https://github.com/infor-design/enterprise/issues/5336
- Go to http://localhost:4000/components/slider/example-range.html
- Play around the slider

5336 - Fix on nan value in sliders

---

src/themes/theme-classic-dark.scss
src/themes/theme-new-dark.scss

This PR focuses on handling color design for Dark Version for the WFM Cards.
Closes https://github.com/infor-design/enterprise/issues/5250
- Go to http://localhost:4000/components/cards/example-variations-hitboxes.html
- Change the color to Dark Theme and check the cards

5250 - Added Dark Theme Color Handling or Card WFM

---

README.md

minor tweak; a recent doc iteration PR I pushed had awkward spacing on warning symbol due to markdown spacing quirk. Needed an HTML snippet.
N/A
Glance at the README.md on this branch under contribution section.
⚠️ shouldn't be touching the next word (as it is here in this PR comment on Github.com...).
**Included in this Pull Request**: N/A

minor README tweak

---

docs/CHANGELOG.md
src/components/locale/cultures/fi-FI.js

The finish locale was incorrect
#5447
- tests pass
- [x ] A note to the change log.

Change locale

---

docs/CHANGELOG.md
src/components/field-options/_field-options-new.scss

This PR fixes a bug where field option is not rendered properly on mobile
Closes https://github.com/infor-design/enterprise/issues/5335
- Go to http://localhost:4000/components/contextmenu/example-field-options.html
- Click on FieldOptions

5335 - Fix Field Option on Context Menu in Mobile

---

app/views/components/homepage/example-hero-widget.html
docs/CHANGELOG.md
src/components/charts/charts.js
src/components/homepage/_homepage.scss

Width is smaller when screen changes for mobile, there are minor adjustments to height and margin to center it.
Closes #5425 
- Go to : http://localhost:4000/components/homepage/example-hero-widget.html?theme=classic&mode=contrast&colors=133c59
- Switch to mobile

5425 - Size adjustments in homepage charts

---

app/views/components/datagrid/test-xss-prevention.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This change strips/sanitizes HTML added inside the name property of the columns array.
Closes #5428 
- Pull branch
- Run app
- Visit http://localhost:4000/components/datagrid/test-xss-prevention.html
- Notice no code is executed when placed inside columns array as value for name property.

5428 - Datagrid: Title XSS Vulnerability

---

docs/CHANGELOG.md
src/components/hierarchy/_hierarchy-rtl.scss

Updated rtl css to align icon and lines in hierarchy.
Closes #5544 
- Go to: http://localhost:4000/components/hierarchy/example-single.html?locale=ar-sa
- Buttons and lines should be laid out correctly

5544 - Changed line and icon alignment in hierarchy

---

app/views/components/dropdown/test-disabling-function-keys.html
docs/CHANGELOG.md
src/components/dropdown/dropdown.js
test/components/dropdown/dropdown.puppeteer-spec.js

This PR adds disabling of function keys F1 to F12. 
Closes https://github.com/infor-design/enterprise/issues/4976
- Go to http://localhost:4000/components/dropdown/test-disabling-function-keys
- Tab to dropdown field
- Hit the F1 key, it should do nothing
- Test F2 up to F12 keys, it should do nothing too

4976  - Disabling function keys F1 to F12

---

test/components/datagrid/datagrid.puppeteer-spec.js

Added puppeteer tests for datagrid in date filter.
Related to #4864 
- Run tests

4864 - Added puppeteer tests for datagrid date filter

---

app/views/components/locale/test-format-number-15-decimal.html
test/components/locale/locale.func-spec.js

Added one more test and updated the example page. (didnt need to do a fix after all but wanted to push the example/test)
NA
- all tests should pass

Chore: Fix another test

---

src/components/datepicker/_datepicker.scss

This PR fixes a bug for both lookup, timepicker, datepicker for short field and its icons not rendering properly.
It will also fix the box-shadow in spinbox-sm. (Follow up fix)
Closes https://github.com/infor-design/enterprise/issues/5541
Closes https://github.com/infor-design/enterprise/issues/5558
- Go to http://localhost:4000/components/form/example-compact-mode.html using **Safari**
- Check on the `datepicker` and buttons/icons

5541 - Follow up Fix (Datepicker)

---

app/views/components/tabs/test-scaled-down-tabs.html
docs/CHANGELOG.md
src/components/tabs/tabs.js

This PR will fix the following bugs:
- Fix a bug where tabs indicator is not aligned when scaled down (5164)
- Fix a bug where tabs indicator is not aligned on RTL. (5554)
Closes https://github.com/infor-design/enterprise/issues/5554
Closes https://github.com/infor-design/enterprise/issues/5164
**5554**
- http://localhost:4000/components/tabs/example-composite-form-on-side.html?locale=ar-sa#composite-form-messages
- Click on the tabs to see the tab indicator
**5164**
- http://localhost:4000/components/tabs/test-scaled-down-tabs.html
- Click on the …

5164/5554 - Fixed on Tabs Indicator

---

docs/CHANGELOG.md
src/components/searchfield/_searchfield-new.scss

Increased height in searchfield when in Firefox to keep it aligned.
Closes #5620 
- In a Firefox browser, go to: http://localhost:4000/components/header/example-searchfield-full

5620 - Adjusted searchfield height for Firefox

---

app/views/components/datagrid/test-tree-rowstatus.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This PR fixes a bug where row status is not properly rendered on Tree List.
Closes https://github.com/infor-design/enterprise/issues/5552
- Go to http://localhost:4000/components/datagrid/test-tree-rowstatus.html
- Expand the Tree Grid
- Click `Add Row Status`
- Click `Add Status`

5552 - Fix on Row Status not showing on Tree Grid

---

test/components/popdown/popdown.puppeteer.spec.js
test/helpers/e2e-utils.js

✓ Created puppeteer scripts for (Enhancement) #3618
✓ Added all other example pages
✓ Added convenience functions
✓ Remove false postives. Line 128
✓ Added Percy Test
✓ Added jest-image snapshot test
Closes #3618
3. run `npm run e2e:puppeteer popdown`

Popdown: Created and converted test scripts to puppeteer

---

app/views/components/datagrid/test-images-error.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js

This PR adds fallback images when images cannot be loaded on datagrid.
Closes https://github.com/infor-design/enterprise/issues/5442
- Go to http://localhost:4000/components/datagrid/test-images-error.html
- See the placeholder

5442 - Datagrid Fallback Image when images cannot be loaded

---

src/components/tabs-vertical/_tabs-vertical.scss

This PR is a follow up fix for Caps Tabs Vertical Scroll.
Closes https://github.com/infor-design/enterprise/issues/5565
- Go to http://localhost:4000/components/contextualactionpanel/example-cap-tabs-vertical-scroll.html
- Scroll the sidebar

5565 - Follow up fix for Caps Tabs Vertical Scroll

---

app/views/components/column/example-rotate.html
docs/CHANGELOG.md
src/components/column/column.js

This PR will add a rotate option in Column Chart.
Closes https://github.com/infor-design/enterprise/issues/5773
- Go to http://localhost:4000/components/column/example-rotate.html

5773 - Column Chart Rotate Option

---

test/components/tabs/tabs-module.puppeteer-spec.js

Tabs  puppeteer test for #5756 
Closes #5756 
Related Issue #4520 
3. run npm run e2e:puppeteer tabs-module

5756 - Tabs enhancement puppeteer script 

---

src/components/accordion/accordion.js

This PR is a fix for Notification Badge NG Implementation
Closes https://github.com/infor-design/enterprise-ng/issues/1169
- No steps for this one
- [] A note to the change log.

1169 - Follow up fix for Notification Badge NG Implementation

---

docs/CHANGELOG.md
test/components/accordion/accordion.puppeteer-spec.js

Converted protractor test cases to puppeteer.
Closes #5836 

5836 - Accordion protractor to puppeteer tests

---

test/components/message/message.puppeteer-spec.js

Message puppeteer test for #5567 
Closes #5856 
Related Issue #5567 
3. run `npm run e2e:puppeteer message`
Given I'm on PC 
And I go to http://localhost:4000/components/message/example-index.html#
Then I click Error Example button to trigger the modal
Then I inspect the element of modal-body-wrapper
Then the modal-body-wrapper should have 16px left and right padding, and 32px top and bottom padding
And when I inspect the modal-header
Then the modal-header should have 24px top padding, 16px left and right padding, and 0 bottom …

5856 - Message Puppeteer Test

---

test/components/accordion/accordion.puppeteer-spec.js

Added changes in accordion puppeteer tests
Addresses build issues in tests: #5836 

5836  - Added changes in accordion puppeteer tests

---

app/views/components/column/example-legend-colors.html
docs/CHANGELOG.md

Added example page to show how to assign custom legend colors.
Closes #5761 
- Go to: http://localhost:4000/components/column/example-legend-colors.html
- Select color in colorpicker
- Click Change Color
- Bars and legend should change color

5761 - Added example page for column chart legend colors

---

docs/CHANGELOG.md
test/components/actionsheet/actionsheet.puppeteer-spec.js

Added actionsheet puppeteer tests.
Closes #5832 

5832 - Added actionsheet puppeteer tests

---

app/views/components/datagrid/example-expandable-row.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/locale/cultures/en-US.js

Added export to CSV option in datagrid toolbar.
Close #5786 
- Go to: http://localhost:4000/components/datagrid/example-expandable-row.html
- Export to CSV should be an option in toolbar popup menu

5786 - Added export to CSV option in datagrid toolbar

---

app/views/components/header/example-toolbar-flex-with-basic-searchfield.html
app/views/components/header/example-toolbar-flex-with-categories.html
app/views/components/toolbar-flex/example-toolbar-flex-with-searchfield-in-center.html
docs/CHANGELOG.md
src/components/header/_header-new.scss
src/components/header/_header.scss
src/components/searchfield/_searchfield-toolbar.scss
src/components/toolbar-flex/_toolbar-flex-searchfield-new.scss
src/components/toolbar-flex/_toolbar-flex.scss

This PR addresses responsive design issues when using Searchfield with categories (position in the middle). Also added the basic search field in toolbar-flex and in the header component.
It only adjusts some CSS stylings and its responsiveness. It does not change the behavior of the searchfield.
- Closes https://github.com/infor-design/enterprise/issues/5619
1.) Toolbar-flex with basic searchfield in the middle
- Go to http://localhost:4000/components/toolbar-flex/example-toolbar-flex-with-searchfield-in-center.html
- Searchfield should have more …

5619 - fix responsive design/layout of toolbar flex with searchfield with categories

---

app/views/components/busyindicator/example-stop-event.html
docs/CHANGELOG.md
src/components/busyindicator/busyindicator.js

This PR will add a hide event in Busy Indicator Component.
Closes https://github.com/infor-design/enterprise/issues/5794
- Go to http://localhost:4000/components/busyindicator/example-stop-event.html
- Click `Start` Button
- Click `Stop` Button
- See `Console`

5794 - Added Busy Indicator Hide Event

---

app/views/components/datagrid/example-filter.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This PR will add new event filterOperatorChanged to datagrid.
Closes https://github.com/infor-design/enterprise/issues/5899
- Go to http://localhost:4000/components/datagrid/example-filter.html
- Try changing the filter
- See `Console Logs`

5899 - Datagrid Filter Change Event

---

test/jest.config.js

This PR fixes the detecting of test files when testing the unit testing script. Our QA encountered this issue so it's a blocker on their end.
Thought that it's a node version issue but when digging further, I found out that it might mistakenly change when debugging.
N/A
- Run `npm run e2e:puppeteer {component}`
- It should run the script

N/A - Fix jest detecting test files

---

app/views/components/datagrid/test-multiple-grids.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This PR will fix the issue in personalizing columns in the datagrid.
Closes https://github.com/infor-design/enterprise/issues/5859
- Go to http://localhost:4000/components/datagrid/test-multiple-grids.html
- Check the `Activity - Checkbox` inside the Personalize Columns Menu
- Check the `Activity - Checkbox` of the datagrid below the first datagrid

5859 - Personalize Columns Datagrid

---

src/components/fileupload-advanced/fileupload-advanced.js

Fixed an issue where another file was not able to upload if one file got error and or cleared when use api setting `maxFilesInProcess: '1'`.
Closes #5598
- Navigate to: http://localhost:4000/components/fileupload-advanced/example-add-files-after-clearing-a-file.html
- Click and select file to upload (use small file for fast uploading)
- Then select another file to trigger the error message (while first one in process)
- Remove (or leave as-is) the error message via clicking the close icon (left section)
- Remove (or leave as-is) also the …

5598 - Fix file was not uploading after clear one with fileupload-advanced

---

package.json

Updating the Chrome Driver. This will fix failing issues in the build.
N/A
- All tests should pass

Chore - Update Chrome Driver

---

docs/CHANGELOG.md
test/components/modal/modal.puppeteer-spec.js

This PR improves the unit testing scripts.
- Removed the waitForTimeout and use the then method for returning Promise
- Improved code quality and simplicity, standardized the baseUrl reusability, code structure, etc.
N/A
- Do a code review
- Run the puppeteer test by doing `npm run e2e: modal`
Open for other suggestions.

Chore: Code Refactoring Puppeteer (Modal Component)

---

app/views/components/contextualactionpanel/test-close-button-updated.html
docs/CHANGELOG.md
src/components/button/_button.scss
src/components/button/button.js
src/components/contextualactionpanel/_contextualactionpanel.scss

This PR will fix a bug where updated settings not properly rendering disabled state
Closes https://github.com/infor-design/enterprise/issues/5928
- Go to http://localhost:4000/components/contextualactionpanel/test-close-button-updated.html
- Open Panel
- Type in the input field

5928 - Button Disabled State

---

docs/CHANGELOG.md
test/components/tooltip/tooltip.puppeteer-spec.js

This PR will add puppeteer test for tooltip component
Closes https://github.com/infor-design/enterprise/issues/5830
- Run in terminal `npm run e2e:puppeteer`

5830 - Tooltip Puppeteer Test

---

docs/CHANGELOG.md
test/components/fileupload/fileupload-advanced.puppeteer-spec.js

Added puppeteer test case to check that progress bar should show.
Closes #5808 

5808 - Added puppeteer test case for progress bar in fileupload

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/datagrid/readme.md

This PR will add a setting in column to toggle the clearing of cells.
Closes https://github.com/infor-design/enterprise/issues/5849
- No Test Page Available

5849 - Datagrid Control To Empty Column Cell

---

docs/CHANGELOG.md
test/components/applicationmenu/applicationmenu.puppeteer-spec.js

Added puppeteer tests for resizable application menu
Closes #5755 

5755 - Added puppeteer tests for resizable application menu

---

docs/CHANGELOG.md
src/components/dropdown/dropdown.js

This PR fixes a regression bug where pressing function keys (F1 to F9) while the dropdown has focus causes letters to be typed.
Closes https://github.com/infor-design/enterprise/issues/4976
- Go to http://localhost:4000/components/dropdown/test-2000-items.html
- Navigate to the dropdown via keyboard
- Click any of the function keys (F7, F8, F9 etc.)
- Nothing should happen when clicking any of the function keys

4976 - Fix pressing function keys causes letters to be typed

---

docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/timepicker/timepicker.js
test/components/timepicker/timepicker.e2e-spec.js

This PR will fix a bug in timepicker where hours reset to 1 when changing period.
Closes https://github.com/infor-design/enterprise/issues/6049
Closes https://github.com/infor-design/enterprise/issues/6104
- Go to http://localhost:4000/components/timepicker/example-index.html
- Click the Timepicker Button
- Select an hour from the dropdown
- Select PM on the AM/PM dropdown

6104 - timepicker value changes ampm

---

docs/CHANGELOG.md
src/components/cards/cards.js

Some card events were not released no destroy. Fixed this.
Note: OP can test https://unpkg.com/ids-enterprise@4.60.0-dev.20220228/dist/js/sohoxi.js as well.
Fixes #6155 
- go to https://stackblitz.com/edit/ids-quick-start-1311-wom6fk?file=src%2Findex.html
- press reload a few times
- inspect the body tag -> look at event handlers. Should be way less that before

6155 - Release events on destroy

---

app/views/components/contextualactionpanel/example-markup.html
docs/CHANGELOG.md

The example needed cleaning up and the removal of a script tag parent container.
Resolves #6065 
- Visit http://localhost:4000/components/contextualactionpanel/example-markup.html
- Everything should work and look as expected.

6065 - CAP Fix Example Markup

---

app/views/components/listview/example-footer-navigation.html
docs/CHANGELOG.md
package.json

Fixes #6144 
- go to http://localhost:4000/components/listview/example-footer-navigation.html
- text on the footers is in sentence case and centered
- icon-mobile is updated (less fat and more phone like)

6144 - Fix icons and text

---

src/components/trackdirty/trackdirty.js

Changes on https://github.com/infor-design/enterprise/issues/6032 need a type check or the dirty tracker doesnt work on some components.
Fixes #6186 
- go to http://localhost:4000/components/checkboxes/example-index.html
- toggle the dirty check box -> second click should reset
N/A

6186 - Fix regression on dirty tracker

---

.github/workflows/ci.yml
docs/PUBLISH.md
package.json
test/components/timepicker/timepicker-api.func-spec.js

Try to fix chrome driver errors.
NA
All PR's fail now

Chore: Fix Chrome Driver (again :)

---

app/views/components/masthead/example-banner-detail.html
docs/CHANGELOG.md

Color change of header is not wired up but not needed for example so removed the action buttons on the header.
Resolves #5959 
- Visit http://localhost:4000/components/masthead/example-banner-detail.html
- Notice action button no longer exists on far right of header

5959 - Masthead: Changing Colors From More Actions Not Working

---

docs/CHANGELOG.md
src/components/tabs/tabs.js

This PR will fix the tabs indicator alignment in RTL.
Closes #6068
- Go to http://localhost:4000/components/tabs/example-desktop-breakpoint.html?locale=ar-SA

6068 - Fix for Tabs Indicator not properly aligned in RTL

---

app/views/components/modal/example-validation.html
docs/CHANGELOG.md

Clicking in and out of the email field does not trigger validation.
Resolves #5571 
- Visit http://localhost:4000/components/modal/example-validation.html
- Click in and out of email field
- Validation should trigger and "Required" label should show

5571 - Modal: Email Required Validation not Working

---

docs/CHANGELOG.md
src/components/locale/cultures/fr-FR.js
test/components/locale/locale.func-spec.js

Fix a missing link in french locale. Also notified translation team
Fixes #6226
- pull, build, run
- go to http://localhost:4000/components/fileupload-advanced/example-index.html?locale=fr-FR 
- should NOT be missing a link like https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?locale=fr-FR

6226 - Fix translation issue

---

app/views/components/datepicker/test-legend-loaded.html
docs/CHANGELOG.md
src/components/datepicker/datepicker.js

This PR will add legend load for datepicker. This will partially fix the issue in NG but it still needs to be applied in NG after this this one is packaged.
Closes https://github.com/infor-design/enterprise-ng/issues/1261
- Go to http://localhost:4000/components/datepicker/test-legend-loaded.html
- Open datepicker
- Change the month to `February`

NG1261 - Added legend load for datepicker

---

app/views/components/lookup/example-filter-row.html
docs/CHANGELOG.md

Removes an unnecessary filter from an example page.
Resolves #5677 
- Visit http://localhost:4000/components/lookup/example-filter-row.html
- Open lookup modal from first field by clicking on magnifying glass
- Pull down filter options on ProductId Column and notice range is not present

5677 - Lookup: Range filter is not working as expected

---

app/views/components/datagrid/test-images-error.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-settings.func-spec.js

Added tooltip in fallback image, added default size for fallback image.
Closes #6178 
- Go to: http://localhost:4000/components/datagrid/test-images-error.html
- Hover over the image
- Tooltip should appear

6178 - Added tooltip for fallback image

---

app/views/components/validation/example-validate-on-submit.html
docs/CHANGELOG.md

Email validation events were not in place for example. Added to round out example.
Resolves #6296 
- Visit http://localhost:4000/components/validation/example-validate-on-submit.html
- Remove value from email field and attempt submit.

6296 - Validation: Validate on submit is not working as expected

---

app/views/components/modal/example-slider.html
docs/CHANGELOG.md
src/components/modal/_modal-new.scss

Background color of slider is not visible in modal as it is the same color as the modal background in theme new dark mode.
Resolves #6211 
- Visit http://localhost:4000/components/modal/example-slider.html?theme=new&mode=dark&colors=db7726
- Open modal
- Ensure slider background is visible
- Test in other themes (though this theme is specifically targeted)

6211 - Slider: Bar is not visible on a modal

---

docs/CHANGELOG.md
src/components/form-compact/_form-compact-new.scss
src/components/form-compact/_form-compact.scss

This PR fixes alignment of Field 16 and Field 18 in Safari.
Closes https://github.com/infor-design/enterprise/issues/6345
- Go to http://localhost:4000/components/form-compact/example-list-detail.html & http://localhost:4000/components/form-compact/example-index.html
- Scroll down to 'Field 16' and 'Field 18'

6345 - Form Compact: Field alignment issue

---

src/components/header/header.js
src/components/toolbar-flex/toolbar-flex.item.js
src/components/tooltip/tooltip.js
src/utils/behaviors.js

Attempt to fix some memory leaks.
Fixes https://github.com/infor-design/enterprise-ng/issues/1279
- make sure all checks pass

Chore: Fix memory leaks

---

app/views/components/datagrid/test-contextmenu-alignment.html
docs/CHANGELOG.md
src/components/popupmenu/_popupmenu.scss
src/components/popupmenu/popupmenu.js

This PR will fix a bug in context menu where it is not indented properly.
Closes https://github.com/infor-design/enterprise/issues/6223
- Go to http://localhost:4000/components/datagrid/test-contextmenu-alignment.html
- Open the context menu for a datagrid row

6223 - context menu left alignment issue

---

docs/CHANGELOG.md
src/components/tree/tree.js

This fixes a secondary issue with : https://github.com/infor-design/enterprise-ng/pull/1295
Related to https://github.com/infor-design/enterprise-ng/issues/1294
- pull this branch and build
- pull the ng branch https://github.com/infor-design/enterprise-ng/pull/1295 and put this in node_modules
- run the NG app 
- go to http://localhost:4200/ids-enterprise-ng-demo/tree-source
- expand the node and watch the console (should see exanded / collapsed fire)

1294 - Add fix for nont firing expanded event

---

src/components/toolbar-flex/toolbar-flex.item.jquery.js
src/components/toolbar-flex/toolbar-flex.item.js
src/components/toolbar-flex/toolbar-flex.jquery.js
src/components/tooltip/tooltip.js
src/utils/behaviors.js

Fix memory leak issues, this.element retaining HTML elements

Move this.element deinitialization to jquery destroy

---

src/components/bar/bar.js

This PR changes the format of the "Value" in the tooltip to not bold. 
Closes https://github.com/infor-design/enterprise/issues/6326
- Go to http://localhost:4000/components/bar-stacked/example-stacked-100
- Hover over the 2014 bar

6326 - Changed value to not bold

---

src/components/monthview/_monthview.scss

This PR removes the unnecessary scrollbar. 
Closes https://github.com/infor-design/enterprise/issues/6246
- Go to http://localhost:4000/components/monthview/example-index.html

6246 - Calendar: Removed unnecessary scrollbar 

---

app/views/components/datagrid/test-datagrid-tooltip-options.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This PR will add a tooltipOptions setting for columns.
Closes https://github.com/infor-design/enterprise/issues/6361
- Go to http://localhost:4000/components/datagrid/test-datagrid-tooltip-options.html
- Focus on the headers and rows

6361 - datagrid header tooltip options

---

src/components/monthview/monthview.js

Added checks for the case that legends are undefined. An error occurs on initialization when there's a delay in input values in Angular.
Additional changes for https://github.com/infor-design/enterprise-ng/issues/1305
- Pull this branch, build the app
- Go to: http://localhost:4000/components/monthview/test-legend-loaded.html
- Legends should still update

NG1305 - Added undefined checks for legend

---

test/components/popdown/popdown.puppeteer-spec.js

Skipping the popdown puppeteer as it's a flaking test in the build and all current PRs as well. Planning to refactor the tests anytime soon.
N/A
- Al tests should passed

Chore - Skipping popdown puppeteer

---

app/views/components/datagrid/test-change-show-select-all-checkbox.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Datagrid header is rendered when calling updated to render select all checkbox, also added paging info settings on update to have the option to preserve selected rows.
Closes #6476 
- Go to: http://localhost:4000/components/datagrid/test-change-show-select-all-checkbox.html
- Click on Toggle Select All
- Select All checkbox should appear on the header

6476 - Fix on select all checkbox not showing when datagrid settings are updated

---

src/components/applicationmenu/_applicationmenu.scss

This PR is a follow up fix only.
Closes https://github.com/infor-design/enterprise-ng/issues/1273
- Go to http://localhost:4000/components/datepicker/test-datepicker-french.html
- Open `Datepicker`

NG1273 - Follow up fix for scroll issue

---

app/views/components/input/example-password.html
docs/CHANGELOG.md
src/components/form/form.js

This PR fixes the bug where the password does not show or hide in firefox
Closes https://github.com/infor-design/enterprise/issues/6481
- Go to http://localhost:4000/components/input/example-password.html
- Click on 'hide' or 'show' button in password fields.

Input: The password does not show or hide 

---

docs/CHANGELOG.md
test/components/datagrid/datagrid.puppeteer-spec.js

closes #6552 
related to #6338 
3. run npm run e2e:puppeteer datagrid

6552 - Datagrid cell editable pptr test

---

docs/CHANGELOG.md
src/components/applicationmenu/_applicationmenu.scss
src/components/personalize/personalize.styles.js
src/components/searchfield/_searchfield.scss
src/components/tabs-module/_tabs-module-new.scss
src/components/tabs-module/_tabs-module.scss
src/components/toolbar/_toolbar.scss
src/themes/theme-classic-dark.scss
src/themes/theme-new-dark.scss

This PR fixes multiple UI issues of searchfield toolbar in tabs module.
Closes
- #6526 
1.) Category Searchfield
- Go to  http://localhost:4000/components/tabs-module/example-category-searchfield
- Category button and searchfield should be properly aligned
- Change to classic
- It should be properly aligned too
2.) Sortable with App menu
- Go to http://localhost:4000/components/tabs-module/example-sortable.html
- Click the app menu
- Resize the page down to 766px or below
- Tabs should not be overlapping with the app menu
3.) Toolbar with …

6526 - fix multiple ui issues of searchfield with toolbar in tabs module

---

docs/CHANGELOG.md
test/components/datagrid/datagrid.puppeteer-spec.js

6644 - Datagrid test for Add row function
Closes #6644 
pull this branch
build and run the app
run `npm run e2e:puppeteer datagrid`
It should pass.

6644 - Datagrid test for Add row function

---

.release-it.json
scripts/deploy/.gitconfig
scripts/deploy/Makefile
scripts/deploy/k8s/README.md
scripts/deploy/k8s/task-definition.yaml
scripts/deploy/run.sh

- Handle github warnings with .gitconfig
- Job fail limit to 1
- Minor image updates 
https://jira.infor.com/browse/HLO-298
I have tested in dry-run mode, but we need to run a release.

fix: prevent all operations in .release-it.json, secrets, minor image updates

---

docs/CHANGELOG.md
src/components/button/_button.scss
src/core/_config.scss
src/themes/theme-classic-dark.scss
src/themes/theme-new-dark.scss

Updated button colors to fit dark theme
Closes #6512 
- Go to: http://localhost:4000/components/button/example-index.html?theme=new&mode=dark
- Button colors should be gray
- Hover on buttons, colors should be gray

6512 - Updated button colors for dark theme

---

package.json

This PR updates the chrome version from 102 to 104.
N/A
- It should be passed all the tests

Chore - update chrome version

---

app/views/components/listview/test-listview-zero.html
docs/CHANGELOG.md
src/components/tmpl/tmpl.js

This PR will fix a bug where listview is not rendering properly when dataset has zero integer value.
Closes https://github.com/infor-design/enterprise/issues/6640
- Go to http://localhost:4000/components/listview/test-listview-zero.html

6640 - Listview Bind Zero

---

app/views/components/datagrid/test-frozen-columns-text-overflow.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid-new.scss
src/components/datagrid/_datagrid.scss

Updated css for datagrid header height to fix the uneven headers in frozen columns
Closes #6697 
- Go to: http://localhost:4000/components/datagrid/test-frozen-columns-text-overflow.html
- Minimize screen if needed to show scroll
- Change the row heights, check each size
- Header height should be even

6697 - Updated datagrid header CSS height

---

docs/CHANGELOG.md
test/components/searchfield/searchfield.puppeteer-spec.js

Closes #6723 
Related to #6453 
3. run npm run e2e:puppeteer Searchfield

6723 - Searchfield: additional icon

---

docs/CHANGELOG.md
test/components/listview/listview.puppeteer-spec.js

Closes #6281 
Related to #6007 
3. run npm run e2e:puppeteer list view

6281 - Searchfield filter sort icon

---

app/views/components/button/example-badge.html
docs/CHANGELOG.md
src/components/button/_button.scss
src/components/notification-badge/notification-badge.js

This PR will add notification badges for buttons with labels.
Closes https://github.com/infor-design/enterprise-ng/issues/1347
- Go to http://localhost:4000/components/button/example-badge.html

NG1347 - badges for buttons with label

---

docs/CHANGELOG.md
test/components/datagrid/datagrid.puppeteer-spec.js

closes #6738 
related to #6490 
3. run npm run e2e:puppeteer datagrid

6738 - Datagrid header icon with tooltip

---

docs/CHANGELOG.md
docs/PUBLISH.md
test/components/datagrid/datagrid.e2e-spec.js
test/components/listview/listview.e2e-spec.js

This PR is intended to add a note not to use the CDN anymore. And see the state of the tests. If any are unstable will fix or skip them.
NA
NA - Will merge when this passes

Chore: Deprecate CDN and Check Test State

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Find method can still return an empty JQuery object so changed it to check the number of expand buttons existing instead of its truthy value.
Closes #6756 
- Go to: http://localhost:4000/components/datagrid/example-editable
- Update one of the "Activity" cells with spaces
- Spaces should be accepted

6756 - Updated space key check in expand button

---

app/views/components/button/example-badge.html
src/components/notification-badge/notification-badge.js

This PR will add notification badges for buttons with labels.
Closes https://github.com/infor-design/enterprise-ng/issues/1347
- Go to http://localhost:4000/components/button/example-badge.html

NG1347 - Follow up fix for Toolbar Flex Nav Buttons

---

app/views/components/datagrid/example-editable-group-headers.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

A recent change / bug fix caused an error editing when your in a datagrid with grouped headers.
Fixes #6759 
- go to http://localhost:4000/components/datagrid/example-editable-group-headers
- click in the price column and edit it
- check the console -> should no longer be any errors

6759 - Fix an error editing with grouped columns

---

app/views/components/calendar/layout.html
app/views/components/calendar/test-hide-legend.html
docs/CHANGELOG.md
src/components/calendar/calendar.js

This PR will add a setting that will show and hide the calendar legend below
Closes https://github.com/infor-design/enterprise/issues/6533
- Go to http://localhost:4000/components/calendar/test-hide-legend.html
- Resize the window until `967px` width
- Toggle the Legend using the Eye button on the upper right corner of the example page.

6533 - calendar show/hide legend

---

test/components/dropdown/dropdown.e2e-spec.js

Testing the tests out, skipping one i have seen fail a lot.
NA
- i will merge if this all passes

Chore: Skip a flaky test for now

---

app/views/components/datagrid/test-addrow-with-is-editable.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.puppeteer-spec.js

This PR will fix bug in datagrid where isEditable is not returning row correctly.
Closes https://github.com/infor-design/enterprise/issues/6746
- Go to http://localhost:4000/components/datagrid/test-addrow-with-is-editable.html
- Click `Add Row`
- See the `Console`

6746 - datagrid is editable render row

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This PR will fix a bug in datagrid inside a modal where the column is rendering wider than normal.
Closes https://github.com/infor-design/enterprise/issues/6782
- Cannot reproduce the issue in EP side

6782 - Modal Datagrid Wide Column

---

docs/CHANGELOG.md
src/components/editor/editor.js

This PR will fix bug in editor where background color is not rendering properly
Closes https://github.com/infor-design/enterprise/issues/6685
- Go to http://localhost:4000/components/editor/example-with-backcolor.html
- Select some text and hit backcolor and pick a color
- Deselect the highlighted text

6685 - Fix for Editor Background Color

---

docs/CHANGELOG.md
src/components/accordion/accordion.js

Adds a quick safety check as per #6789 
Fixes #6789 
- tests and checks pass

6789 - Add safety check

---

docs/CHANGELOG.md
package.json

Package version update and changelog format.
N/A
- Check the package.json version
- It should be `4.68.0-dev`
- Check the `CHANGELOG.md`
- It should have `4.68.0` format

Chore - Update package version and changelog format

---

scripts/publish-docs/Dockerfile
scripts/publish-docs/Makefile
scripts/publish-docs/README.md
scripts/publish-docs/job.yaml
scripts/publish-docs/run.sh
scripts/publish-docs/secrets.sh
scripts/publish-docs/secrets/docs-api-key.yaml
scripts/publish-docs/secrets/github-acccess-token.yaml
scripts/publish-docs/workflow.yaml

Containerized enterprise docs deployment.
https://jira.infor.com/browse/HLO-293

HLO-293 - docs publisher worker

---

.github/workflows/env-deploy.yml
scripts/deploy-environment/Makefile
scripts/deploy-environment/job.yaml
scripts/deploy-environment/run-workflow.sh
scripts/deploy-environment/run.sh
scripts/deploy-environment/workflow.yaml

New input for subdomain name. Optional.
https://jira.infor.com/browse/HLO-305
Just needs a branch push.

cd: add subdomain parameter

---

docs/CHANGELOG.md
src/components/datepicker/datepicker.js

Added a missing doc and a change note on the "breaking" change. And added a new settings, missing description.
https://github.com/infor-design/enterprise/pull/6648
https://github.com/infor-design/enterprise/issues/6653
- if checks pass is good to go

Chore: Update docs

---

docs/CHANGELOG.md
test/components/calendar/calendar.puppeteer-spec.js

closes #6810 
related to #6533 
3. run npm run e2e:puppeteer calendar

6810 - calendar: show/hide legend test

---

scripts/release/Makefile
scripts/release/job.yaml
scripts/release/run.sh
scripts/release/workflow.yaml

Add variable for repo owner and name. Cleanup unused variables. Add a function to check missing required env vars.
https://jira.infor.com/browse/HLO-300

cd: add repo owner/name var, cleanup

---

docs/CHANGELOG.md
src/themes/theme-classic-dark.scss
src/themes/theme-new-dark.scss

Updated text link color in dark mode
Closes #6807 
- Go to http://localhost:4000/components/typography/example-index.html?theme=new&mode=dark&colors=0066D4
- Under `Typographic Characteristics (class)` find `Link Text (text-link)`
- Font color should be `#0072ED`

6807 - Updated text link color in dark mode

---

app/views/components/datagrid/test-multiple-grids-in-tab.html
docs/CHANGELOG.md
src/components/dropdown/dropdown.js

Closes https://github.com/infor-design/enterprise/issues/6834
- Go to http://localhost:4000/components/datagrid/test-multiple-grids-in-tab.html

6834 - datagrid filter row incorrect

---

test/components/datagrid/datagrid.puppeteer-spec.js
test/components/datagrid/test.txt

closes #6849 
related to #6821 
3. run npm run e2e:puppetee datagrid

6849 - datagrid upload enhancement script

---

app/views/components/datagrid/example-header-icon-with-tooltip.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This PR will add additional setting in datagrid header for tooltip extra class.
Closes https://github.com/infor-design/enterprise/issues/6802
- Go to http://localhost:4000/components/datagrid/example-header-icon-with-tooltip
- Hover `Product Name` Header

6802 - datagrid extra class tooltip

---

app/views/components/datagrid/test-multiple-grids-in-tab.html
src/components/datagrid/_datagrid.scss
src/components/dropdown/_dropdown.scss

Closes https://github.com/infor-design/enterprise/issues/6834
- Go to http://localhost:4000/components/datagrid/test-multiple-grids-in-tab.html

6834 - datagrid filter row incorrect (2)

---

app/views/components/lookup/example-dblclick.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/lookup/lookup.js
test/components/datagrid/datagrid-settings.func-spec.js

This PR will add `dblClickApply` setting in lookup for selection of item.
Closes https://github.com/infor-design/enterprise/issues/6546
- Go to http://localhost:4000/components/lookup/example-dblclick.html
- Open `Lookup` for `Product`
- Double Click an item to select.

6546 - lookup dblclick

---

package-lock.json
package.json

Updates chrome version to 105.
N/A
- All tests should pass

Chore - Update chrome version to 105

---

.github/workflows/env-deploy.yml
scripts/deploy-environment/Makefile
scripts/deploy-environment/run-workflow.sh
scripts/deploy-environment/workflow.yaml
scripts/publish-docs/Makefile
scripts/publish-docs/job.yaml
scripts/publish-docs/run.sh
scripts/publish-docs/workflow.yaml

Add docs deployment to the end of the CD workflow.
https://jira.infor.com/browse/HLO-292
https://jira.infor.com/browse/HLO-291
PR or merge

cd: deploy docs as part of the cd workflow

---

docs/CHANGELOG.md
src/components/dropdown/dropdown.js

This PR will fix a bug in datagrid where multiselect filter is not rendering properly.
Closes https://github.com/infor-design/enterprise/issues/6846
- Go to http://localhost:4000/components/datagrid/test-filter-zero-as-text.html
- Change the Status Filter to `Error`

6834 - multiselect filter

---

app/views/components/datagrid/test-editable-with-inline-editor.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid.puppeteer-spec.js

This PR will fix a bug in datagrid where inline editor input text is not being selected upon clicking.
Closes https://github.com/infor-design/enterprise-ng/issues/1365
- Go to http://localhost:4000/components/datagrid/test-editable-with-inline-editor.html
- Click on one of the input fields under Column Activity
- Text should be highlighted

NG1365 datagrid value input field inline editor

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/searchfield/_searchfield-toolbar.scss

Fix on searchfield go button in classic theme
Addresses comments in #6686 
- Go to: 
- http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
- http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?theme=classic&mode=light&colors=2578a9
On uneven searchfield height:
- Click on the searchfield to focus it
- Click anywhere else on the page
On cut off go button:
- Resize the window to around mobile width
- Expand the window with the maximize button …

6686 - Searchfield visual fix in classic

---

src/components/datagrid/_datagrid.scss

This PR will fix a bug in datagrid where row shading is not rendered properly.
Closes https://github.com/infor-design/enterprise/issues/6850
- Go to http://localhost:4000/components/datagrid/test-alternate-row-shading.html
- Click on a cell with shading

6850 - datagrid alternate row shading (2)

---

scripts/deploy-environment/build_push_image.yaml
scripts/deploy-environment/workflow.yaml

forgot to add missing image version env var

add missing image version

---

app/views/components/datagrid/test-addrow-with-frozen-columns.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js

This PR will fix a bug in datagrid where add row is not working properly when using frozen columns.
Closes https://github.com/infor-design/enterprise/issues/6918
- Go to http://localhost:4000/components/datagrid/test-addrow-with-frozen-columns
- Click on `Add Row`
- Enter a value for Product Name on the added row
- Click on the lookup icon for Product Id on the added row
- Choose a Product and Click Apply

6918 - datagrid add row frozen columns

---

src/components/icons/_icons.scss
src/components/tabs/_tabs-new.scss
src/components/tabs/_tabs.scss
test/components/datagrid/datagrid.puppeteer-spec.js

Some fixes for failed qa comments no #6868 
Fixes #6868 
- go to http://localhost:4000/components//validation/test-error-on-tab.html
- go to opportunities tab - clear out the field so an error comes
- check the alignment
- test this in RTL mode and in classic and new theme
- go to http://localhost:4000/components/validation/test-legacy-tooltip.html
- clear out the dropdown (tab through without select a value)
- test this in classic and new theme

6868 - Additional icon fixes

---

app/views/components/datagrid/test-update-toolbar.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/toolbar/toolbar.js

On datagrid update method, if new settings have changes in toolbar, update toolbar.
Closes https://github.com/infor-design/enterprise-ng/issues/1357
- Go to: http://localhost:4000/components/datagrid/test-update-toolbar
- Edit the toolbar options in updater
- Click Update
- Toolbar should update

NG1357 - Added toolbar update on datagrid update

---

app/views/components/datagrid/example-expandable-row-editable.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This PR will fix a bug in datagrid where expandable row input cannot edit the value.
Closes https://github.com/infor-design/enterprise/issues/6781
- Go to http://localhost:4000/components/datagrid/example-expandable-row-editable.html
- Click on one of the + icons and edit the value in the expanded row.
- Now click on either Quantity or Price and now try to edit the value in the expanded row.

6781 - datagrid expanded row editable

---

app/views/components/datagrid/test-multiple-grids-in-tab-with-dropdown.html
docs/CHANGELOG.md
src/components/dropdown/dropdown.js

Closes https://github.com/infor-design/enterprise/issues/7006
- Go to http://localhost:4000/components/datagrid/test-multiple-grids-in-tab-with-dropdown.html

7006 - datagrid dropdown filter row

---

app/views/components/datagrid/test-multiple-grids-in-tab-with-dropdown.html
docs/CHANGELOG.md
src/components/dropdown/dropdown.js

Closes https://github.com/infor-design/enterprise/issues/7006
- Go to http://localhost:4000/components/datagrid/test-multiple-grids-in-tab-with-dropdown.html

7006 - datagrid dropdown filter row 4.68.x

---

app/views/components/datagrid/test-multiple-grids-in-tab-with-dropdown.html
docs/CHANGELOG.md
src/components/dropdown/dropdown.js

Closes https://github.com/infor-design/enterprise/issues/7006
- Go to http://localhost:4000/components/datagrid/test-multiple-grids-in-tab-with-dropdown.html

7006 - datagrid dropdown filter row 4.67.x

---

docs/CHANGELOG.md
test/components/datagrid/datagrid.e2e-spec.js
test/components/tabs/tabs.puppeteer-spec.js

closes #7003 
related to #6902 
3. run npm run e2e:puppeteer tabs

7003 - Tabs added tooltip title test

---

app/views/components/datagrid/test-card-cell.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss

This PR will fix a bug in datagrid where the icon cause clipping issues.
Closes https://github.com/infor-design/enterprise/issues/7000
- Go to http://localhost:4000/components/datagrid/test-card-cell.html
- Select the row or any button inside the row

7000 - Datagrid Icon Clipping Issues

---

app/views/components/lookup/example-index.html
docs/CHANGELOG.md
src/components/lookup/lookup.js

Added modal settings to lookup
Closes #4319 
- Go to: http://localhost:4000/components/lookup/example-index.html
- Minimize screen width to around 767px or lower
- Open lookup
- Should be full size 

4319 - Added modal settings to lookup

---

docs/CHANGELOG.md
package-lock.json
package.json
src/components/images/_images.scss
test/components/icons/icons.e2e-spec.js

Added 3 new system icons. And fixed the strokes on the user status icons.
Fixes #7040 
- should be 3 new icons `icon-paint-brush, icon-psych-precaution, icon-observation-precaution`
- go to http://localhost:4000/components/images/example-photos.html
- see the status icons have an outer stroke and a background fill. 
- change themes

7040 - Ids identity upgrade

---

src/components/textarea/textarea.js

Added check if text is selected on paste event
Addresses issue found in comment: https://github.com/infor-design/enterprise-ng/issues/1401#issuecomment-1371825612
- Copy text:
```
Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Donec
rutrum hendrerit nunc sed mollis...
```
- Select all text in "Notes (maxlength)"
- Paste
- Take note of ending characters
- Select all and paste again
- Should be the same

NG1401 - Additional check for selection

---

src/components/textarea/textarea.js

Additional fix on paste event
Addresses comment: https://github.com/infor-design/enterprise-ng/issues/1401#issuecomment-1373076499
- Go to: http://localhost:4000/components/textarea/example-index
- Select all, copy-paste text:
```
Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Donec
rutrum hendrerit nunc sed mollis...
```
- Select last line and copy paste text

NG1401 - Fix on paste event

---

app/views/components/compositeform/_header.html
app/views/components/compositeform/test-with-tab-headers.html
src/components/personalize/_personalize.scss
src/components/personalize/personalize.styles.js
src/components/searchfield/searchfield.js
src/components/tabs-header/_tabs-header-new.scss
src/components/tabs/tabs.js

This PR will fix the visibility of primary button on new design.
Closes https://github.com/infor-design/enterprise/issues/7085
- Go to http://localhost:4000/components/tabs-header/example-index.html
- Select a tab and see the focus
- Go to http://localhost:4000/components/compositeform/test-with-tab-headers.html
- Select a tab and see the focus
- Make a screen smaller and check the fade out aligned in the more button

7085 - Tabs: White Theme Issues

---

app/views/components/splitter/example-index.html
docs/CHANGELOG.md
src/components/splitter/splitter.js

Store location in local only when save setting is true.
Closes #7045 
- Go to: http://localhost:4000/components/splitter/example-index.html
- Inspect and check local storage
- Drag splitter
- Should not have any entry

7045 - Store location only when save setting is set to true

---

app/views/components/line/example-contextmenu.html
app/views/components/line/test-fit-height.html
package.json
test/components/hierarchy/hierarchy.e2e-spec.js
test/components/line/line-api.func-spec.js

Some data in the chart examples didnt match up
Fixes #7121
- go to http://localhost:4000/components/line/example-contextmenu.html
- resize to mobile
- should be A, B, C in the legend

7121 - Fix chart data

---

docs/CHANGELOG.md
src/components/button/_button.scss
src/components/toolbar-flex/_toolbar-flex.scss
src/themes/theme-classic-dark.scss
src/themes/theme-new-dark.scss

Adjustments on icons in classic
Closes #7134 
- Go to: http://localhost:4000/components/searchfield/example-buttons.html?theme=classic
- Icons in searchfield should be aligned
- Type in searchfield
- Icons in searchfield should be aligned

7134 - Searchfield icon placement fixes in classic

---

app/views/components/header/example-toolbar-flex-with-categories.html
docs/CHANGELOG.md
src/components/header/_header-new.scss
src/components/header/_header.scss
src/components/personalize/personalize.styles.js
src/components/searchfield/_searchfield-toolbar.scss

Adjustments in searchfield category.
Addressing comments: https://github.com/infor-design/enterprise/issues/7110#issuecomment-1408809800
- Go to: http://localhost:4000/components/header/example-toolbar-flex-with-categories.html
- Should have border in default 

7110 - Border and color adjustments in searchfield category

---

scripts/deploy-environment/build_push_image.sh
scripts/deploy-environment/manifests/deployment.yaml
scripts/deploy-environment/workflow.yaml
scripts/release/run.sh

Minor fixes to the CI/CD scripts.
https://jira.infor.com/browse/HLO-327
Branch merge

minor tweaks to deployment scripts

---

.vscode/spellright.dict
app/views/components/datagrid/example-header-background-color.html
app/views/components/datagrid/test-lookup-filter-background-color.html
app/views/components/header/example-flex-toolbar.html
docs/CHANGELOG.md
package-lock.json
src/components/datagrid/_datagrid-new.scss
src/components/datagrid/_datagrid.scss
src/components/personalize/personalize.styles.js

This PR contains the following..
- fix to an example page that broke during merge of dependency updates
- update package lock since it was out of sync with node 18 for some reason
- 7184/7176 
Fixes #7185 
Fixes #7176
- go to http://localhost:4000/components/header/example-flex-toolbar.html?colors=0066D4
- click the menu button then hover menu items -> button should look ok
- go to http://localhost:4000/components/datagrid/example-header-background-color.html
- page should load with no errors
- go to http://localhost:4000/components/datagrid/test-lookup-filter-background-color
- colors …

7184/7176 - Add fixes for color issues

---

app/views/components/applicationmenu/test-accordion-card.html
docs/CHANGELOG.md
src/utils/lifecycle/lifecycle.jquery.js

Added expandable card in close children exclusion list
Addresses comment: https://github.com/infor-design/enterprise/issues/6820#issuecomment-1422885185
- Go to: http://localhost:4000/components/applicationmenu/test-accordion-card.html?layout=nofrills
- Click on "Dates of Service"
- Accordion should expand, cards should not collapse

6820 - Additional fix in accordion collapsing cards on expand bug

---

docs/CHANGELOG.md
src/components/colors/_colors.scss
src/components/theme/theme.js
test/components/popdown/popdown-e2e-test.js
test/components/popdown/popdown-puppeteer-test.js

Fixes the personalization api to have the correct new values
Fixes #7167 
- go to http://localhost:4000/components/personalize/example-color-theme-api.html
- in the console type: `Soho.theme.personalizationColors().default.value` and check the color matches the swatch/header
- in the dropdown pick the other 5 combinations of mode/version

7167 - Add fixes to theme api

---

app/views/components/header/example-index.html
app/views/components/header/example-subheader.html
app/views/components/header/header-with-subheader.html
app/views/includes/header-actionbutton.html
app/views/includes/header-appmenu-trigger.html
docs/CHANGELOG.md
src/components/header/_header.scss
src/components/personalize/_personalize.scss
src/components/personalize/personalize.js
src/components/personalize/personalize.styles.js

This pull request will fix a bug in subheader where the color its not appropriate on default theme.
Closes https://github.com/infor-design/enterprise/issues/7173
- Go to http://localhost:4000/components/header/example-subheader.html
- Change colors and theme
- After change the colors run `Soho.personalization.setColors("")` should revert back
- Go to http://localhost:4000/components/components/slider/example-tooltip-position.html -> h1 should be visible

7173 - Header with subheader

---

app/views/components/datepicker/test-show-week-number.html
docs/CHANGELOG.md
src/components/datepicker/datepicker.js
src/components/locale/cultures/en-US.js
src/components/monthview/_monthview.scss
src/components/monthview/monthview.js
src/core/_config.scss
src/themes/theme-classic-dark.scss
src/themes/theme-new-dark.scss

This pull request will add weekview number on the monthview in datepicker. Use `showWeekNumber` to enable it.
Closes https://github.com/infor-design/enterprise/issues/5785
- Go to http://localhost:4000/components/datepicker/test-show-week-number.html
- Open datepicker
- See the week number beside

5785 - calendar week number

---

docs/CHANGELOG.md
src/components/typography/readme.md

This fixes inconsistency in docs by removing differing guidance and pointing users toward the broader usage recommendations.
Closes #7187 and resolves Jira [IDS-654](https://jira.infor.com/browse/IDS-654)

7187 - Typography documentation

---

docs/CHANGELOG.md
src/components/actionsheet/_actionsheet-new.scss
src/components/actionsheet/_actionsheet.scss
src/components/button/_button.scss
src/core/_config.scss
src/themes/theme-classic-dark.scss
src/themes/theme-new-contrast.scss
src/themes/theme-new-dark.scss
src/themes/theme-new-light.scss

Updated colors in actionsheet
Closes #7012 
- Minimize screen to be smaller than 700px (or switch to mobile)
- Go to: http://localhost:4000/components/actionsheet/example-index.html
- Click on more button to pop up actionsheet
- Text and icons in options should be visible
- Hover over options, text and icons should be visible
- Test on every version and mode

7012 - Updated font and icon colors for actionsheet

---

docs/CHANGELOG.md
src/components/searchfield/_searchfield.scss
src/components/searchfield/searchfield.js
src/components/toolbar-flex/_toolbar-flex-searchfield.scss
src/components/toolbar-flex/_toolbar-flex.scss
src/components/toolbar-flex/toolbar-flex.js

Additional adjustments in custom button for mobile screen width.
Addresses comment: https://github.com/infor-design/enterprise/issues/7134#issuecomment-1409795239
- Change screen width to mobile
- Go to: http://localhost:4000/components/searchfield/example-buttons.html?theme=classic&mode=light
- Click on searchfield
- Type on searchfield
- Check that icons are aligned

7134 - Custom button adjustments in mobile

---

docs/CHANGELOG.md
docs/sitemap.yml

Adds action sheet so it will be available on the design.infor.com site next release. (It wont until then)
Fixes #7230 
- not possible to review

Chore - Add missing component

---

docs/CHANGELOG.md
src/components/listview/listview.js

This pull request will fix overflow in listview when there is a search bar included.
Closes https://github.com/infor-design/enterprise/issues/7015
- Go to http://localhost:4000/components/listview/example-search.html
- It should only have one scroll bar

7015 - Listview Overflow Error when having a Searchfield

---

src/components/toolbar-flex/_toolbar-flex-searchfield.scss

Width adjustments for QA comments mentioned
Closes #7164 
- Switch to mobile
- Go to: http://localhost:4000/components/toolbar-flex/example-centered-content.html
- Click on searchfield, collapse button should be seen, button borders should be visible
- Check all versions and modes

7164 - Searchfield width adjustments

---

docs/CHANGELOG.md
src/components/personalize/personalize.js

This pull request will ...
Closes https://github.com/infor-design/enterprise/issues/7171
Closes https://github.com/infor-design/enterprise/issues/7073
- Go to http://localhost:4000/components/personalize/example-classes.html
[#7073](https://github.com/infor-design/enterprise/issues/7073)
- Open `Console`
- Type in $('html').personalize({ colors:  'amber' });
- Color should change in the UI
[#7171](https://github.com/infor-design/enterprise/issues/7171)
- Change the version and mode
- Refresh the page
- Shoule be the same as before prior the to the …

7171/7073 - Personalization Colors

---

.github/stale.yml

Adds stale bot to close out some issues.
NA
- build will pass
- im not sure how this works will have to watch when merged

Chore - Add stale bot

---

src/components/listview/_listview.scss

This pull request will fix overflow in listview when there is a search bar included.
Closes https://github.com/infor-design/enterprise/issues/7015
- Go to http://localhost:4000/components/listview/example-search.html
- It should only have one scroll bar
- it shouldn't have an overflow

7015 - Listview Overflow Error when having a Searchfield (2)

---

docs/CHANGELOG.md
src/components/fileupload/_fileupload-new.scss
src/components/fileupload/_fileupload.scss

Adjusted error icon
Closes #7265 
- Go to: http://localhost:4000/components/fileupload-advanced/example-failed.html
- Upload a file and click Set Failed
- Error icon should look okay
- Check both classic and new

7265 - Adjusted error icon in file error

---

app/views/components/personalize/example-form2.html
docs/CHANGELOG.md
src/components/personalize/_personalize.scss

Checking http://localhost:4000/components/icons/example-index.html and looks like the phone icon name changed to phone-linear, so added linear in the name.
Closes #7269 
- Go to: http://localhost:4000/components/personalize/example-form2.html
- Phone icon should be visible
- Check in other modes

7269 - Updated icon name in example page

---

app/views/components/personalize/example-form-landmark2-horizontal.html
docs/CHANGELOG.md
src/components/personalize/personalize.styles.js
src/components/tabs/_tabs-horizontal-new.scss
src/components/tabs/_tabs-horizontal.scss

This PR fixes incorrect fade out color in horizontal header tabs
Closes #7244 
- go to http://localhost:4000/components/personalize/example-form-landmark2-horizontal.html
- select theme classic and colors default, any mode
- see the left/right fade out colors have correct color
- select theme new and colors default, any mode
- see the left/right fade out colors have correct color

7244 - Tabs Fix incorrect fade out color in horizontal header tabs

---

docs/CHANGELOG.md
src/components/button/_button-new.scss

Updated colors for secondary menu buttons
Closes #7221 
- Go to: http://localhost:4000/components/button/example-as-link.html
- Check all modes
- Button text should be readable

7221 - Button adjustments for secondary menu in dark and contrast mode

---

docs/CHANGELOG.md
src/themes/theme-new-contrast.scss

Changed primary bg color for high contrast to slate 1.
Closes #7261 
- Go to: http://localhost:4000/components/header/example-index.html?theme=new&mode=contrast&colors=default
- Inspect body
- Color should be slate 1

7261 - Updated default background color in high contrast

---

docs/CHANGELOG.md
src/components/tabs/tabs.js

This pull request will fix the alignment of focus in RTL view.
Closes https://github.com/infor-design/enterprise/issues/6992
- Go to http://localhost:4000/components/tabs-header/example-index.html?locale=ar-SA
- Go to http://localhost:4000/components/compositeform/test-with-tab-headers-horizontal.html?locale=ar-SA
- Go to http://localhost:4000/components/header/example-tabs-alternate.html?locale=ar-SA
- Go to http://localhost:4000/components/header/example-tabs-alternate.html?theme=new&mode=contrast&colors=0066D4&locale=ar-SA
- Go to …

6992 - Tabs Regression RTL (2)

---

app/views/components/counts/example-header.html
src/components/personalize/_personalize.scss
src/core/_config.scss
src/themes/theme-classic-contrast.scss
src/themes/theme-classic-dark.scss
src/themes/theme-new-dark.scss

Updated colors in count text and example page to make it more readable in header
Addresses https://github.com/infor-design/enterprise/pull/7296#issuecomment-1460503666
- Go to: http://localhost:4000/components/counts/example-header.html
- Check counts in all modes and versions

7234 - Updated colors in count

---

src/themes/theme-new-contrast.scss

Updated searchfield text color
Addresses https://github.com/infor-design/enterprise/pull/7301#issuecomment-1459773398
- Go to: http://localhost:4000/components/header/example-index.html?theme=new&mode=contrast&colors=default
- Type on searchfield
- Unfocus searchfield
- Text should be seen

7261 - Updated searchfield header text color

---

src/components/toolbar-flex/_toolbar-flex-searchfield.scss

Close icon adjustments
https://github.com/infor-design/enterprise/issues/6014#issuecomment-1461680276
- Pull this branch, buiold and run the app
- Set to mobile, width 740px
- Go to: http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html?theme=classic&mode=light&colors=default
- Open searchfields

6014 - Close icon adjustments

---

src/components/personalize/_personalize.scss
src/components/tabs-header/_tabs-header.scss
src/components/tabs/_tabs.scss
src/core/_config.scss
src/themes/theme-classic-contrast.scss
src/themes/theme-classic-dark.scss
src/themes/theme-classic-light.scss

This pull request will fix the alignment of focus in RTL view.
Closes https://github.com/infor-design/enterprise/issues/6992
- Go to http://localhost:4000/components/tabs-header/example-index.html?locale=ar-SA
- Go to http://localhost:4000/components/compositeform/test-with-tab-headers-horizontal.html?locale=ar-SA
- Go to http://localhost:4000/components/header/example-tabs-alternate.html?locale=ar-SA
- Go to http://localhost:4000/components/header/example-tabs-alternate.html?theme=new&mode=contrast&colors=0066D4&locale=ar-SA
- Go to …

6992 - Tabs Regression RTL (3)

---

app/views/components/tabs-header/example-add-tab-button.html
docs/CHANGELOG.md
src/components/tabs-header/_tabs-header-new.scss
src/components/tabs/tabs.js

This pull request will fix the alignment and color of close button.
Closes https://github.com/infor-design/enterprise/issues/7273
- Go to http://localhost:4000/components/tabs-header/example-add-tab-button.html
- Hover the tabs with close button

7273 - tabs header close button

---

app/views/components/timeline/test-on-card.html
docs/CHANGELOG.md
src/components/timeline/_timeline.scss

Added styles for when timeline is in a card in one-third column. Edited example page as it was missing several div classes based on what was mentioned in the issue.
Closes #7278 
- Go to: http://localhost:4000/components/timeline/test-on-card.html
- Both timelines in the cards should have correct alignment

7278 - Fixed the alignment when timeline is inside a card

---

app/views/components/header/example-subheader.html
app/views/components/homepage/example-hero-widget.html
app/views/components/homepage/example-widget-two-column.html
app/views/components/homepage/test-hero-widget-calculate-height.html
src/components/header/_header.scss
src/components/header/header.js
src/components/homepage/_homepage.scss
src/components/personalize/_personalize.scss
src/components/personalize/personalize.js
src/components/personalize/personalize.styles.js
src/core/_config.scss
src/themes/theme-classic-contrast.scss
src/themes/theme-new-contrast.scss
src/themes/theme-new-light.scss
test/components/breadcrumb/breadcrumb-puppeteer-test.js
test/components/textarea/textarea-puppeteer-test.js

Adds a few more fixes for 7320
Fixes #7320
- test http://localhost:4000/components/header/example-subheader.html
- test all colors and themes
- set a color and then do `$('html').personalize({ colors:  '' });` and it should set it back
- go to http://localhost:4000/components/homepage/example-hero-widget.html -> hero should be dark

7320 - Additional fixes

---

app/views/components/cards/test-borderless.html
docs/CHANGELOG.md
src/components/cards/_cards.scss

Added border-less class to remove borders in cards if needed.
Addresses https://github.com/infor-design/enterprise-wc/issues/1169
- Go to: http://localhost:4000/components/cards/test-borderless.html
- Cards should have no border

WC1169 - Added borderless class for cards

---

docs/CHANGELOG.md
src/components/header/_header-new.scss
src/components/typography/_typography-new.scss
test/components/textarea/textarea-puppeteer-test.js

This pull request will fix the alignments and font sizes in header
Closes https://github.com/infor-design/enterprise/issues/7317
- Go to http://localhost:4000/components/header/example-index.html
- Check the figma for comparison https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/branch/LfuOgmyF88ayXKO5fx9p0t/IDS-(SoHo)-Component-Library-v4.5?node-id=26118-54982&t=XNA7rpafSDZczQKN-0

7317 - Header Design Changes

---

app/views/components/tabs-module/example-category-searchfield-go-button-home.html
docs/CHANGELOG.md
src/components/header/_header-new.scss
src/components/header/_header.scss
src/components/personalize/personalize.styles.js
src/components/searchfield/_searchfield-toolbar.scss
src/core/_config.scss
test/components/textarea/textarea-puppeteer-test.js

This pull request will fix the border in search field in the header in tabs module
Closes https://github.com/infor-design/enterprise/issues/7297
Closes https://github.com/infor-design/enterprise/issues/7304
- Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?theme=new&mode=light&colors=BB5500
- Check the searchfield component (it should be white)
- Hover the `Go` Button
- Switch on the Modes and Colors

7297/7304 - Border on Search Field in Tabs Module Header

---

app/views/components/datagrid/test-selected-rows-addnew.html
docs/CHANGELOG.md
package-lock.json
src/components/datagrid/_datagrid.scss
src/themes/theme-new-light.scss

Updated styling on datagrid icon. 
Closes https://github.com/infor-design/enterprise/issues/5913
- Go to: http://localhost:4000/components/datagrid/test-selected-rows-addnew.html
- Add row
- Row status icon should be shown right

NG5913 - Fix on styling in row status icon when first column is not a select column

---

app/views/components/datagrid/example-header-icon.html
app/views/components/datagrid/test-empty-header-icon-with-tooltip.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This pull request will fix header icon tooltip showing when undefined.
Closes https://github.com/infor-design/enterprise/issues/6929
- Go to http://localhost:4000/components/datagrid/test-empty-header-icon.html
- Header Icon tooltip should not be shown

6929 - datagrid undefined headicon

---

app/views/components/modal/test-modal-field-filter.html
docs/CHANGELOG.md
src/components/modal/_modal.scss

This pull request will fix a bug in field filter where the design is not properly aligned on Modal.
Closes https://github.com/infor-design/enterprise/issues/7358
- Go to http://localhost:4000/components/modal/test-modal-field-filter.html
- Open `Modal`
- Check the alignment of the input boxes.

7358 - field filter alignment

---

app/views/components/breadcrumb/example-navigation-breadcrumbs.html
docs/CHANGELOG.md
src/components/breadcrumb/_breadcrumb.scss
src/components/personalize/personalize.styles.js
src/core/_config.scss
src/themes/theme-new-contrast.scss

Updated breadcrumb colors.
Closes #7337 
- Go to: http://localhost:4000/components/breadcrumb/example-navigation-breadcrumbs.html
- Text on breadcrumb should be readable
- Hover
- Text should be readable

7337 - Updated breadcrumb hover color

---

docs/CHANGELOG.md
src/components/dropdown/dropdown.js
src/components/tooltip/tooltip.js

This pull request fix tooltip not on top of all elements when shown and manually moved.
Closes https://github.com/infor-design/enterprise/issues/7130
- Go to http://localhost:4000/components/dropdown/example-tooltips.html?colors=0066D4
- Click an item in the dropdown
- Hover the dropdown component
- See the tooltip appended to the body

7130 - tooltip header placements

---

docs/CHANGELOG.md
src/components/searchfield/searchfield.js

Adds some guards to avoid undefined errors.
Fixes #7402 
- not possible to easily test. Just a guard

7402 - Add fix for undefined error

---

docs/CHANGELOG.md
src/components/listbuilder/_listbuilder-new.scss

Update margins in listbuilder toolbar icons so that it's centered
Closes #7397 
- Go to: http://localhost:4000/components/listbuilder/example-index.html
- Tab focus on the listbuilder buttons
- Icon should be centered

7397 - Fixed icon alignment on toolbar so that it's centered on focused

---

src/components/datagrid/datagrid.js

Addition to https://github.com/infor-design/enterprise/pull/7409 after failing tests. Added checks if settings are empty in datagrid updated
Closes #7398
PR https://github.com/infor-design/enterprise/pull/7409
- tests pass

7398 - Datagrid: addition to PR#7409

---

app/views/components/popupmenu/example-icons.html
app/views/components/popupmenu/example-show-arrow.html
docs/CHANGELOG.md
src/components/popupmenu/popupmenu.js

Fix on popupmenu arrow not appearing when showArrow is true
Closes #5061 
- Go to: http://localhost:4000/components/popupmenu/example-show-arrow
- Click on right star, should have arrow
- Click on left, should have no arrow

5061. Fix on popupmenu arrow not appearing when showArrow is true

---

docs/CHANGELOG.md
src/components/page-patterns/_builder.scss

This pull request will fix subtitle text not shown properly.
Closes https://github.com/infor-design/enterprise/issues/7207
- Go to http://localhost:4000/components/builder/example-builder-subtitle-test.html
- Check the subheader (should be visibly shown properly)

7207 - builder subtitle text not visible

---

src/components/toolbar-flex/toolbar-flex.js

https://github.com/infor-design/enterprise/issues/7438

#7438: Adds check for add-button-link data existance

---

docs/CHANGELOG.md
src/components/personalize/personalize.styles.js
test/components/applicationmenu/applicationmenu-puppeteer-test.js
test/components/bar/bar-puppeteer-visual-test.js
test/components/message/message-puppeteer-test.js

Trying to fix some test errors. Will merge if this works.

Chore: Fix tests

---

src/components/searchfield/_searchfield.scss

Aligment adjustment for clear icon
Addresses comment in #7382 
- Go to: http://localhost:4000/components/searchfield/test-categories.html
- In "Category Searches in Toolbars" type in searchfields, tab to focus on clear icon
- Should be centered

7382 - Clear icon adjustment

---

scripts/deploy-environment/Dockerfile
scripts/deploy-environment/build_push_image.sh
scripts/deploy-environment/utils.sh
scripts/publish-docs/job.yaml
scripts/release/job.yaml

This is the last PR for https://jira.infor.com/browse/HLO-329. This fixes the old workflow, which is currently disabled. I did this for historical reference.

minor cleanup

---

src/components/personalize/personalize.styles.js

Changes based on comments
#7234 
- Pull thsi branch build and run the app
- Go to: http://localhost:4000/components/counts/example-hero.html
- Check all themes/modes/etc

7234 - Style change

---

docs/CHANGELOG.md
src/components/popupmenu/_popupmenu.scss

Adjusted alignment for popupmenu icon buttons
Closes #7408 
- Go to: http://localhost:4000/components/button/example-menubutton-submenu-icons.html
- Open menu button
- Open Actions
- Icons should be aligned

7408 - Adjusted alignment for popupmenu icon buttons

---

docs/CHANGELOG.md
src/components/personalize/personalize.styles.js

Basing colors on a previous version: https://4680-enterprise.demo.design.infor.com/components/header/example-tabs-alternate.html
Closes #7466 
- In different modes, colors, and versions, check the following to see if tabs are viewable:
- http://localhost:4000/components/header/example-tabs-alternate.html
- http://localhost:4000/components/personalize/example-tabs.html

7466 - Fix on header text not being readable due to color styles

---

app/views/components/line/test-long-labels.html
docs/CHANGELOG.md
src/components/line/line.js

Added short and abbreviated name options for the data
Closes #5906 
- Go to: http://localhost:4000/components/line/test-long-labels
- Chart should use abbreviated/short names 

5906 - Added short and abbreviated name options for the data

---

app/views/components/cards/example-workspace-widgets.html
src/components/listview/_listview-new.scss
src/components/typography/_typography.scss
src/core/_config.scss
src/themes/theme-new-contrast.scss

A few more tweaks to cards https://www.figma.com/file/PwVwlrnn6iAEoQkkmY2zux/New-Widgets---UI-Implementation-QA?type=design&node-id=0-1&t=J19gSGOarnOUek3S-0
Fixes #7379 
- on http://localhost:4000/components/cards/example-workspace-widgets.html
- check border radius on search
- padding on borderless widgets is now 16 not 20
- fix search being to dark in contrast mode

Chore: More widget fixes

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixes #7362 
- go to http://localhost:4000/components/datagrid/test-editable-colorpicker.html
- click the color picker cell to open it
- click to close it again

7362 - Add fix to close colorpicker

---

app/views/components/module-nav/example-empty-state.html
app/views/components/module-nav/example-hidden.html
app/views/components/module-nav/example-index.html
app/views/components/module-nav/example-six-levels-icons.html
app/views/components/module-nav/example-six-levels.html
docs/CHANGELOG.md
src/components/accordion/accordion.js
src/components/module-nav/module-nav.accordion.scss
src/components/module-nav/module-nav.dropdown.scss
src/components/module-nav/module-nav.js
src/components/module-nav/module-nav.scss
src/components/module-nav/module-nav.searchfield.scss
src/components/toolbar/_toolbar-new.scss
src/core/_config.scss

Fixes focus clicking issue and a few QA points on https://www.figma.com/file/bL4EBYtWjgfBsvTVI9seXU/branch/eHul2nKNMdypFLSb55ZwR1/Application-Menu?type=design&node-id=4467-75383&t=kLxpSZ01jIHG2rni-0#446923638
Fixes:
- Point 2 and 4 (Seem to be the same thing or the colors are already fixed)
- Point 6 (is now to the side in collapsed mode)
- Point 13 (improved text/icon alignment but its tougher than you would think)
- Point 16 (when clicking in to focus its now white when typing)
Some of #7568 (point one only - the rest was from the figma QA doc)
- go to …

7568 - More module nav QA fixes

---

app/views/components/datagrid/test-selected-rows-addnew.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-puppeteer-test.js

Include page if active page isn't one when updating rows.
Closes #7486 
- Go to: http://localhost:4000/components/datagrid/test-selected-rows-addnew.html
- In More menu, select "Add Row (Bottom)"
- Edit on any editable cell in the new row
- Should not get data from previous rows
- Enter new edits, should update
- Check console and the "Cell change" logs. Row in event and dataRow in active cell should be correct

7486 - Fix on incorrect row updates on adding a new row to the next page

---

app/views/components/stats/example-index.html
docs/CHANGELOG.md
scripts/data/expected-files.json
src/components/cards/_cards-new.scss
src/components/cards/_cards.scss
src/components/cards/cards.js
src/components/stats/_stats.scss
src/core/_config.scss
src/core/_controls-new.scss
src/core/_controls.scss
src/themes/theme-classic-dark.scss
src/themes/theme-new-contrast.scss
src/themes/theme-new-dark.scss
src/themes/theme-new-light.scss
src/utils/selectable.jquery.js

This pull request will add a new component called stats.
Closes https://github.com/infor-design/enterprise/issues/7506
Closes #7596 
- Go to http://localhost:4000/components/stats/example-index.html
Figma Reference: https://www.figma.com/file/vFSHOqtgm9ypxOtOTHoBjF/List-View-Cards?type=design&node-id=0-1&t=Op6UQdJJNZyGldN1-0

7506 - stats component

---

app/views/components/lookup/test-lookup-overflow.html
docs/CHANGELOG.md
src/components/lookup/_lookup.scss
src/components/searchfield/_searchfield.scss

This pull request will fix a bug in lookup width not responsive in grid system.
Closes https://github.com/infor-design/enterprise/issues/7205
- Go to http://localhost:4000/components/lookup/test-lookup-overflow.html
- Resize the window
For Older Issue: https://github.com/infor-design/enterprise/issues/6924
- Go to http://localhost:4000/components/lookup/example-clearable.html
- Open Lookup
- Select a single item
- Field should not change size
- Open Lookup
- Select a multiple item
- Field should not change size

7205 - lookup width constraint

---

docs/CHANGELOG.md
src/components/modal/modal.js

This pull request will fix the overflow issue in mobile view
Closes https://github.com/infor-design/enterprise/issues/7585
- Go to http://localhost:4000/components/contextualactionpanel/example-index.html
- Transform into `Mobile View - Responsive`
- See the fix

7585 - CAP Overflow

---

app/views/components/module-nav/example-index.html
docs/CHANGELOG.md
src/components/accordion/accordion.js
src/components/module-nav/module-nav.common.js
src/components/module-nav/module-nav.js
src/components/module-nav/module-nav.switcher.js
src/components/module-nav/module-nav.switcher.scss

This PR improves the Module Nav Switcher component's API:
- Some adjustments have been made to better accommodate the Angular component wrappers' lifecycle, such as on-demand refs to child/parent components where needed.
- Some settings have been added for customization of both the role button's hidden text content, and the role dropdown's hidden label text content
Related to #7386 
Related to infor-design/enterprise-ng#1477
Review http://localhost:4000/components/module-nav/example-index.html to make sure all component features work as expected (no visible changes should have occurred) …

NG1477 - Module Nav Switcher: API improvements

---

docs/CHANGELOG.md
src/components/personalize/personalize.styles.js

This pull request will fix menu items cannot be seen properly when using alabaster
Closes https://github.com/infor-design/enterprise/issues/7609
- Go to http://localhost:4000/components/applicationmenu/example-index.html?colors=ffffff
- Open the menu on the side, click an item. It should be visible

7609 - menu items alabaster

---

docs/CHANGELOG.md
src/components/modal/_modal.scss

Fixed icon alignment in the title.
Fixes #7639 
- go to http://localhost:4000/components/modal/example-title-with-icon.html
- click the button
- check icon alignment

7639 - Add alignment fix for icons

---

docs/CHANGELOG.md
src/components/searchfield/_searchfield.scss

This PR fixes the search icon position in classic toolbar.
Closes #7642 
- Go to http://localhost:4000/components/toolbar/example-index.html?theme=classic&mode=light&colors=default
- Search icon should vertically aligned with the search toolbar

7642 - Fix search icon position in toolbar

---

app/views/components/donut/test-force-legend-bottom-popup.html
docs/CHANGELOG.md
src/components/charts/_charts.scss
src/components/charts/charts.js
src/components/pie/pie.js

This pull request will add a setting for chart to force legend popup.
Closes https://github.com/infor-design/enterprise/issues/7453
- Go to http://localhost:4000/components/donut/test-force-legend-bottom-popup.html
- See the legend

7453 - charts force legend overflow

---

src/components/pie/pie.js

This pull request will just add documentation for the new setting in pie.
Closes https://github.com/infor-design/enterprise/issues/7453
- No test needed

7453 - Added documentation for forceLegendPopup

---

app/views/components/pager/example-standalone.html
app/views/components/stats/example-index.html
src/components/cards/_cards-new.scss
src/components/homepage/homepage.js
src/components/place/place.js
src/components/stats/_stats.scss

Fixes
- a stray console log
- missing event in example
- add sentence case to the new stat example
- fix card box shadow
NOTE: Already has a change log for stats. This is just an update
Fixes #7657
- go to http://localhost:4000/components/stats/example-index.html
- ensure all text other than titles is in sentence case
- see that the stat card and normal card have same box shadow now
- be on the lookout for this in future examples you touch

7657 - Change to title case and remove console log

---

docs/CHANGELOG.md
src/components/applicationmenu/_applicationmenu-new.scss
src/core/_config.scss

This pull request will fix bottom border color cannot be seen properly.
Closes https://github.com/infor-design/enterprise/issues/7565
- Go to http://localhost:4000/components/applicationmenu/example-personalized-roles.html
- Open the navigation menu, see the borders

7565 - border color accordion header

---

docs/CHANGELOG.md
src/components/button/_button-new.scss
src/themes/theme-classic-dark.scss
src/themes/theme-classic-light.scss

Updated hover style
Closes #7611 
- Go to: http://localhost:4000/components/datagrid/test-icon-buttons.html
- Hover on the disabled buttons
- Should not have hover color

7611 - Fixed a bug where disabled buttons in cells were hoverable

---

docs/CHANGELOG.md
src/components/column/column.js

This PR fixes the issue where the column-stacked chart does not render correctly when there are no x-axis labels.
This is related to this PR https://github.com/infor-design/enterprise/pull/7630
Closes  #7644 
- Go to http://localhost:4000/components/column-stacked/example-singular-set-selected.html
- Check the console
- There should be no errors

7644 - Fix errors in column-stacked if there are no x-axis labels

---

src/components/column/column.js

Sinke page had an error. Adds a quard to it. No change log as its a patch/quick fix
Fixes #7696
- go to http://localhost:4000/
- check console is clean of errors
- see all charts load
- NOTE: https://github.com/infor-design/enterprise/issues/7693 is a seperate issue to be fixed if you see that in the charts but will deal with that later

7696 - Added a guard for page error

---

app/views/components/message/test-nested.html
docs/CHANGELOG.md
src/components/message/message.js
src/components/modal/modal.js

Added ID check in event triggers. Added id attribute in message if custom id exists in settings.
Closes #7475 
- Go to: http://localhost:4000/components/message/test-nested
- Click on Show Message Dialogs
- Close Message 2
- Events triggered (shown via toast and console logs) should be for message 2
- Close Message 1
- Events should be for message 1

7475 - Added ID check in event triggers

---

docs/CHANGELOG.md
src/components/popupmenu/_popupmenu.scss

This PR fixes the issue of misaligned submenu icons.
Closes #7626
- Go to http://localhost:4000/components/button/example-menubutton-submenu-icons.html
- Open the submenu
- Icons should be aligned correctly

7626 - Fix misalignment of submenu icons

---

docs/CHANGELOG.md
src/components/accordion/_accordion.scss
src/components/module-nav/module-nav.scss

Fixes rounding and a zindex issue in module nav
Fixes #7687 
- go to http://localhost:4000/components/module-nav/example-index.html
- resize the page so that when expended the module nav would open over the text and dropdown for the example
- set to expanded
- the text should be under the module nav
- click the caret icons -> should be not fully round

7654 - Fix rounding and zindex issue

---

app/views/components/module-nav/example-icon.html
app/views/components/module-nav/example-one-pane.html
src/components/module-nav/module-nav.common.js
src/components/module-nav/module-nav.js
src/components/module-nav/module-nav.switcher.js
src/utils/string.js

This PR fixes a handful of issues
- Related to infor-design/enterprise-ng#1477
- Related to infor-design/enterprise-ng#1523
- Fixes #7694 
- Open http://localhost:4000/components/module-nav/example-icon.html.  Try the different icon settings and make sure they work as expected
- Open http://localhost:4000/components/module-nav/example-one-pane.html.  Test the accordion to make sure only one pane opens at a time (clicking another pane should close any others currently open).  Filtering the accordion is the only case where multiple panes are allowed (clearing the filter …

NG1477 - Fix remaining lifecycle/settings issues

---

app/views/components/datagrid/test-filter-with-default-operator.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This pull request will fix a bug in datagrid where default operator for lookup is not rendered properly.
Closes https://github.com/infor-design/enterprise/issues/7530
- Go to http://localhost:4000/components/datagrid/test-filter-with-default-operator.html
- See the Default Operator for the `Product Id`

7530 - Datagrid Default Operator For Lookup

---

docs/CHANGELOG.md
src/components/fileupload/_fileupload-new.scss
src/components/fileupload/_fileupload.scss
src/components/fileupload/fileupload.js
src/themes/theme-classic-dark.scss
src/themes/theme-new-dark.scss

This pull request will fix the alignment of the close button and file icon button.
Closes https://github.com/infor-design/enterprise/issues/7570
- Go to http://localhost:4000/components/fileupload/example-index.html
- Upload a file
- Hover `x` icon

7570 - Fileupload Icon Alignment

---

app/views/components/tabs-module/test-updated.html
docs/CHANGELOG.md
src/components/tabs/tabs.js

This pull request will fix an error in tabs where it is not sortable in NG.
Closes https://github.com/infor-design/enterprise-ng/issues/1480
- Go to http://localhost:4000/components/tabs-module/test-updated.html
- Try dragging the tabs back and forth

NG1480 - Tab Item Sortable

---

docs/CHANGELOG.md
src/components/field-filter/_field-filter-new.scss

This pull request will fix Dropdown border not rendered properly.
Closes https://github.com/infor-design/enterprise/issues/7600
- Go to http://localhost:4000/components/field-filter/example-short.html
- Hover over dropdown

7600 - Field Filter Dropdown Border

---

app/views/components/link/example-index.html
src/components/listview/_listview.scss
src/components/listview/listview.js

Updated styles for classic and added tooltip for list items when text overflows
Addressing QA comments: https://github.com/infor-design/enterprise/pull/7732#pullrequestreview-1560868906
- Go to: http://localhost:4000/components/link/example-index.html?theme=classic
- Icons should be viewable and text should align well

7628. Style adjustments for classic and adding tooltip on list when text overflows

---

docs/sitemap.yml
src/components/link/readme.md
src/components/stats/readme.md

Adds Docs for the site for the new components (We forgot). 
NA
- check content and feel free to suggest additions

Add new docs

---

app/views/components/css-utilities/example-index.html
docs/CHANGELOG.md
src/core/_css-utilities.scss

Added text-wrap class
Closes #7497 
- Go to: http://localhost:4000/components/css-utilities/example-index.html
- Check the sixth block in the Text area
- Text should wrap around block

7497 - Added text-wrap class

---

docs/CHANGELOG.md
src/components/monthview/monthview.js

This pull request will fix where date range selected is not properly rendered in some scenarios.
Closes https://github.com/infor-design/enterprise/issues/7528
- Go to http://localhost:4000/components/datepicker/example-range.html
- Use `Range - No Initial value` Input Field
- Open `Datepicker`
- Go to `December`
- Select a Range
- Open again `Datepicker`
- Go to `January`

7528 - Datepicker Range December

---

docs/CHANGELOG.md
src/components/dropdown/_dropdown-new.scss
src/components/dropdown/_dropdown.scss

Adjusted dropdown text in Firefox
Closes #7763 
- In Firefox, go to the ff. (bug also appears in these example pages):
- http://localhost:4000/components/dropdown/example-index.html
- http://localhost:4000/components/multiselect/example-index.html
- See that text is aligned

7763 - Adjusted dropdown text in Firefox

---

docs/CHANGELOG.md
src/utils/number.js

Added additional check for formatNumber
Closes #7752 
- Go to: http://localhost:4000/components/locale/test-format-number-15-decimal.html
- Put `430,000,000,000` on the input field and enter
- Value should be the same but with additional 15 decimal places

7752 - Added additional check for formatNumber

---

docs/CHANGELOG.md
src/components/charts/_charts.scss

This PR fixes the alignment position of legends and labels.
Closes #7722 
Closes 
- Go to http://localhost:4000/components/column-stacked/example-selected.html
- Check legends and labels position
- It should be aligned together
- alos test http://localhost:4000/components/column-stacked/components/bubble/example-index.html
~~- [] An e2e or functional test for the bug or feature.~~

7722 - fix legend and labels position in column stacked

---

docs/CHANGELOG.md
src/components/calendar/calendar-toolbar.js

Adds a guard to fix an uncaught error
Fixes #7818 
- not possible to test unless using cordova

7818 - Fix uncaught error

---

src/components/homepage/_homepage.scss
src/components/personalize/personalize.styles.js
src/core/_config.scss
src/themes/theme-classic-contrast.scss
src/themes/theme-classic-dark.scss
src/themes/theme-new-contrast.scss
src/themes/theme-new-dark.scss

This pull request will fix Dropdown border not rendered properly.
Closes https://github.com/infor-design/enterprise/issues/7505
- Go to http://localhost:4000/components/homepage/example-hero-widget.html
- Check the colors on personalization are not changed when changing color
- Confirm on all 6 themes (mode/version)
- For more steps for testing follow through the issue link

7505 - Hero Widget Alabaster

---

docs/CHANGELOG.md
src/components/homepage/homepage.js

Changes the selector so that if there is more than one homepage component it will work.
Fixes #7819
- go to http://localhost:4000/components/homepage/example-hero-widget.html
- ensure works fine like before

7819 - Use a different selector in homepage

---

docs/CHANGELOG.md
src/components/listview/_listview.scss

Adds back an underline on links in list view
Fixes #7838
- go to http://localhost:4000/components/listview/example-list-view-classes.html
- should have underline on the link

7838 - Fix listview links

---

app/views/components/contextualactionpanel/example-cap-tabs-vertical-scroll.html
docs/CHANGELOG.md
src/components/badges/_badges.scss
test/components/contextualactionpanel/contextualactionpanel-puppeteer-test.js

Changes border radius to 12px
Fixes https://github.com/infor-design/enterprise/issues/7862
- inspect border radius on non round badges http://localhost:4000/components/badges/example-index.html
- and tags http://localhost:4000/components/tags/example-index.html
- should be 12px

7862 - Change radius to 12px

---

docs/CHANGELOG.md
src/components/week-view/week-view.js

This pull request will fix the response of render on breakpoint in week view.
Closes https://github.com/infor-design/enterprise/issues/7727
- Go to http://localhost:4000/components/week-view/example-stacked.html
- Slowly size the screen width down until one day shows - take notice of where it goes down to one day
- Wait a second then slowly size the screen width back

7727 - weekview resize issue

---

app/views/components/header/example-long-title-with-button.html
app/views/components/header/example-searchfield-large.html
docs/CHANGELOG.md

This pull request will fix the response of render on breakpoint in week view.
Closes https://github.com/infor-design/enterprise/issues/7479
- Go to http://localhost:4000/components/header/example-no-title-button.html
- Open `Developer Tools`
- See if the header uses `flex`
- Do the same with the links below
- Go to http://localhost:4000/components/header/example-long-title-with-button.html
- Go to http://localhost:4000/components/header/example-searchfield-large.html

7479 - Header Flex

---

src/components/datagrid/readme.md
src/components/monthview/monthview.js
src/components/personalize/personalize.js
src/components/tabs-module/_tabs-module.scss
src/themes/theme-classic-dark.scss

A few more QA fixes from https://github.com/infor-design/enterprise/pull/7809
Fixes #7881
In all of these links the text and icon color should look ok
- http://localhost:4000/components/tabs-multi/example-index.html?theme=classic&mode=dark&colors=ffffff
- http://localhost:4000/components/tabs-vertical/example-index.html?theme=classic&mode=dark&colors=ffffff
- http://localhost:4000/components/tabs-module/example-index.html?theme=classic&mode=dark&colors=ffffff
~ A note to the change log. ~ Does not need a new change log. Additional fixes

7881 - Add more tab fixes

---

docs/CHANGELOG.md
src/components/editor/editor.js
src/utils/xss.js

Refixes the editor issue on https://jira.infor.com/browse/ISO-9120 (new test string). Also removed "character count text".
Fixes #7590 
- go to http://localhost:4000/components/editor/example-index.html
- switch to html view (should not have a character count text)
- in html view try all the various strings mentioned on https://jira.infor.com/browse/ISO-9120  (not mentioned publicly for safety)
- should be no alerts with cookies and such in them

7590 - Refix issues in editor

---

docs/CHANGELOG.md
src/components/tabs/tabs.js

This pull request will fix the focus alignment in tabs for RTL.
Closes https://github.com/infor-design/enterprise/issues/7772
- Go to http://localhost:4000/components/tabs/example-index?theme=uplift&variant=light&locale=he-IL
- Use arrow keys `left` or `right` to check the focus alignment

7772 - Tabs focus border RTL

---

docs/CHANGELOG.md
src/components/header/_header.scss
src/components/personalize/personalize.styles.js
src/themes/theme-new-dark.scss

Added additional selector for breadcrumb in header.
Closes #7801 
- Go to: http://localhost:4000/components/header/example-breadcrumbs.html
- Hover over breadcrumb items
- Hover color should not be dark

7801 - Updated hover color for breadcrumb in header

---

docs/CHANGELOG.md
src/components/lookup/_lookup.scss

Fix broken text layout on lookup
Fixes #7905 
- check http://localhost:4000/components/lookup/example-index.html and http://localhost:4000/components/lookup/example-custom-toolbar.html
- in both cases open the lookup and make sure the (n Results) text seems lined up OK

7905 - Fix lookup text positioning

---

docs/CHANGELOG.md
src/components/editor/editor.js

This pull request will fix editor text not changing to other font headers after changing colors.
Closes https://github.com/infor-design/enterprise/issues/7793
- Go to http://localhost:4000/components/editor/example-index.html
- Select all the text inside the editor
- Change to `Header 1`
- Change the color of the text
- Change to `Normal Text`

7793 - Editor Text Header and Color

---

app/views/components/datagrid/example-placeholder.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.formatters.js

This pull request will add Placeholder for Datagrid Date Field.
Closes https://github.com/infor-design/enterprise-ng/issues/1531
- Go to http://localhost:4000/components/datagrid/example-placeholder.html
- See the `Order Date` column
- See the first row has placeholder
- Try clearing other rows to see the placeholder

1531 - Placeholder Datagrid

---

docs/CHANGELOG.md
src/components/searchfield/_searchfield-toolbar.scss
src/components/toolbar-flex/_toolbar-flex.scss

Fix on go button misalignment in toolbar
Closes #7910 
- Go to: http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
- Last toolbar should have aligned searchfield

7910 - Fix on go button misalignment

---

app/views/components/dropdown/example-dropdown-wide-width.html
docs/CHANGELOG.md
src/components/dropdown/dropdown.js

This pull request will fix dropdown position when expanded on corners.
Closes https://github.com/infor-design/enterprise-ng/issues/1541
- Go to http://localhost:4000/components/dropdown/example-dropdown-wide-width.html
- Open the dropdown
- It should expand to the left

1541 - dropdown maxwidth expand

---

docs/CHANGELOG.md
src/components/datepicker/_datepicker.scss
src/components/week-view/_week-view.scss

Centered the positioning of text inside the Week view footer-cell.
Closes https://github.com/infor-design/enterprise/issues/7926
- Go to: http://localhost:4000/components/week-view/example-stacked.html?theme=classic&mode=dark&colors=default
- Make sure classic theme is selected.
- Text within footer cell should be centered.

7926 - Adjusted positioning of text inside Weekview footer cell.

---

docs/CHANGELOG.md
src/components/dropdown/_dropdown.scss
src/components/dropdown/dropdown.js

Fix on dropdown not focusing in mobile
Closes #7815 
- In mobile, go to: http://localhost:4000/components/dropdown/example-index.html
- Select an item in dropdown
- Focus should still be present

7815 - Fix on dropdown not focusing in mobile

---

docs/CHANGELOG.md
src/components/cards/_cards-new.scss

This pull request will fix bottom spacing issue in RTL.
Closes https://github.com/infor-design/enterprise/issues/7776
- Go to http://localhost:4000/components/line/example-localize.html?locale=ar-SA
- See the bottom spacing

7776 - line localize bottom spacing rtl

---

app/views/components/cards/test-tabs-card.html
docs/CHANGELOG.md
src/components/cards/cards.js

This pull request will fix issues when using both card and tabs component.
Closes https://github.com/infor-design/enterprise/issues/7915
- Go to http://localhost:4000/components/cards/test-tabs-card.html
- Click the `Attachments`

7915 - card is selected trigger tabs

---

docs/CHANGELOG.md
src/components/dropdown/dropdown.js

This pull request will fix display render when the option has no icon.
Closes https://github.com/infor-design/enterprise/issues/7813
- Go to http://localhost:4000/components/dropdown/test-icons-color.html
- Open dropdown
- Select the options with no icons in the list

7813 - dropdown empty icons

---

app/views/components/emptymessage/example-widgets.html
app/views/components/emptymessage/test-centered-content.html
app/views/components/icons/example-empty-widgets.html
src/components/emptymessage/readme.md

I missed a point on https://github.com/infor-design/design-system/issues/518#issuecomment-1740221536 where we should make the text title case. Adding it now
https://github.com/infor-design/design-system/issues/518#issuecomment-1740221536
- go to http://localhost:4000/components/icons/example-empty-widgets.html
- title is title case / text is sentence case

518 - Add title case

---

app/views/components/datagrid/test-emptymessage-no-icon.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/emptymessage/emptymessage.js

This pull request will fix no results text should not be selected.
Closes https://github.com/infor-design/enterprise/issues/7854
- Go to http://localhost:4000/components/datagrid/test-emptymessage-no-icon.html
- Select all of the items then click `Remove`
- See the empty message

7854 - empty message alignment

---

src/components/actionsheet/readme.md
src/components/bar-stacked/readme.md
src/components/bubble/readme.md
src/components/button/readme.md
src/components/cards/readme.md
src/components/column-grouped/readme.md
src/components/column/readme.md
src/components/datepicker/readme.md
src/components/form/readme.md
src/components/grid/readme.md
src/components/hierarchy/readme.md
src/components/monthview/readme.md
src/components/page-patterns/readme.md
src/components/pager/readme.md
src/components/searchfield/readme.md
src/components/slider/readme.md
src/components/toast/readme.md
src/components/toolbar-flex/readme.md
src/components/toolbar/readme.md
src/components/trackdirty/readme.md
src/components/tree/readme.md
src/components/validation/readme.md

Fixes links with typos / broken or moved.
Fixes #8073
- cant really test this until we release. just check if anything out of ordinary when scanning

8073 - Fix broken links

---

docs/CHANGELOG.md
src/components/toolbar/_toolbar.scss
src/themes/theme-classic-contrast.scss
src/themes/theme-new-contrast.scss

Fixes to colors on the contextual action toolbar.,
Fixes #8084 
- click to select a row
- test the hover states on the buttons

8084 - Fix contextual toolbar styles

---

app/views/components/tabs/example-enable-disable-individual-tabs.html

This pull request will add switch component in the example page.
Closes https://github.com/infor-design/enterprise/issues/7955
- Go to http://localhost:4000/components/tabs/example-enable-disable-individual-tabs.html
- See the switch component

7955 - Tabs Items Overflow

---

src/components/modal/modal.js

Fixes a minor issue with the class path. When being used in an xpath script the extra space caused some customer scripts to fail.
Something else to be aware of on code reviews
https://jira.infor.com/browse/LMWEB-18630
- go to http://localhost:4000/components/modal/example-index.html
- inspect this element and should not have a space in the name

Bug - Add modal fix

---

src/components/calendar/_calendar-toolbar.scss
src/components/datepicker/_datepicker.scss
src/components/monthview/_monthview.scss

When testing i noticed a problem on the calendar page fixing but please review @RJ-Csc @ericangeles @tjamesallen15
https://github.com/infor-design/enterprise/pull/8011/files caused an issue with the calendar/popup sizes.
https://github.com/infor-design/enterprise/pull/8011
- go to http://localhost:4000/components/calendar/example-index.html and calendar should not look like https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html
- on the same page open the picker by clicking the calendar icon next to Oct should not look like …

NA - Fix calendar issues

---

docs/CHANGELOG.md
src/components/treemap/_treemap.scss

Adjusted label styling to not get cut off in RTL.
Closes https://github.com/infor-design/enterprise/issues/6891
- Go to http://localhost:4000/components/treemap/example-index.html?locale=ar-sA
- Tree map labels should be properly visible in RTL.

6891 - Fix Tree Map label styling in RTL.

---

docs/CHANGELOG.md
src/components/charts/charts.js

This pull request will fix the following:
- A bug in clicking legends causing to change whole list to the last clicked legend name. (8139)
- A bug in where legends can be clicked if selectable settings set to false. (8140)
Closes https://github.com/infor-design/enterprise/issues/8139
Closes https://github.com/infor-design/enterprise/issues/8140
- Go to http://localhost:4000/components/donut/example-alerts.html
- Click on any legend, the legend list should not change to the selected item
- Go to …

Charts - Added additional validation and changelog

---

docs/CHANGELOG.md
src/components/fileupload/fileupload.js

Pressing backspace on a Read Only field removes the file. Added condition to not allow for input clearing for Read Only and Disabled fields.
Closes https://github.com/infor-design/enterprise/issues/8024
- Go to http://localhost:4000/components/fileupload/example-index.html
- Select the Read Only field.
- Press backspace.
- Field should not be cleared.

8024 - Fix file clearing for Read Only Field.

---

docs/CHANGELOG.md
src/components/badges/_badges-new.scss
src/components/badges/_badges.scss
src/components/dropdown/_dropdown.scss
src/core/_config.scss
src/themes/theme-classic-dark.scss
src/themes/theme-new-contrast.scss
src/themes/theme-new-light.scss

Color for the dismissible or "X" icon in the tags of the disabled multiselect dropdown component did not match the text color. Adjusted styling to match the color as well as some adjustments to the positioning of the button.
Closes https://github.com/infor-design/enterprise/issues/8036
- Go to http://localhost:4000/components/multiselect/example-index.html?theme=new&mode=contrast&colors=default
- Dismissible or "X" icon color should match the text color for the disabled multiselect.

8036 - Adjusted dismissible icon for multiselect dropdown tags.

---

docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js

Added additional check for when setting focus on editor
Closes #8021 
- Click on a date cell with value
- Date should be seen

8021 - Fixed misalignment on date cells when selected

---

app/views/components/busyindicator/test-updated-escape.html
docs/CHANGELOG.md
src/components/busyindicator/busyindicator.js

This pull request will fix unescaped html strings not rendering properly.
Closes https://github.com/infor-design/enterprise/issues/8189
- Go to http://localhost:4000/components/busyindicator/test-updated-escape.html
- Click `Start Busy Indicator`
- See no errors

8189 - Busy Indicator Apostrophe

---

docs/CHANGELOG.md
src/components/about/about.js

Removed operating system field.
Closes #8118 
- Go to: http://localhost:4000/components/about/example-index
- Open about 
- Should not have operating system field

8118 - Removed operating system field

---

app/views/components/dropdown/test-icons-color.html
docs/CHANGELOG.md
src/components/dropdown/dropdown.js

This pull request will fix a bug where list is broken when empty icon is in the first option.
Closes https://github.com/infor-design/enterprise/issues/8105
- Go to http://localhost:4000/components/dropdown/test-icons-color.html
- Open the dropdown, see no errors

8105 - Dropdown Empty Icon

---

docs/CHANGELOG.md
src/components/pager/pager.js

Updated lastValue (previous page number) so that this check works: https://github.com/infor-design/enterprise/blob/main/src/components/pager/pager.js#L1033
Closes #8156 
- Go to: http://localhost:4000/components/datagrid/example-paging
- Inspect page and go to network
- Enter a page number in pager
- API call should only appear once

8156 - Fixed double call on update pager when using keydown

---

docs/CHANGELOG.md
src/components/searchfield/_searchfield-toolbar.scss
src/components/toolbar-flex/_toolbar-flex-searchfield-new.scss
src/components/toolbar-flex/_toolbar-flex-searchfield.scss
src/components/toolbar-flex/_toolbar-flex.scss

Fixed styling issues in RTL for searchfield
Closes #6982 
- go to:
- new theme RTL http://localhost:4000/components/searchfield/example-buttons.html?locale=ar-SA
- classic theme RTL http://localhost:4000/components/searchfield/example-buttons.html?theme=classic&mode=light&colors=default&locale=ar-SA
- see that the issues listed in #6982 have been fixed

6982 - Searchfield Fix styling issues in RTL

---

docs/CHANGELOG.md
src/components/circlepager/_circlepager.scss

Fixed the positioning of the next and previous buttons
Closes #8266 
- Go to: http://localhost:4000/components/circlepager/example-mobile.html?locale=ar-SA
- Next and previous should be pointing correctly

8266 - Fixed the positioning of the next and previous buttons

---

app/views/components/donut/test-bordered.html
docs/CHANGELOG.md
src/components/charts/_charts.scss
src/components/charts/charts.js
src/components/pie/pie.js

This pull request will fix rendering issues when having bordered class in the widget.
Closes https://github.com/infor-design/enterprise/issues/8164
- Go to http://localhost:4000/components/donut/test-bordered.html
- See the donut chart looking fine

8164 - Pie with Bordered Class

---

app/views/components/busyindicator/test-update.html
docs/CHANGELOG.md
src/components/busyindicator/busyindicator.js

This pull request will fix the updated method of busy indicator throwing error when calling with no parameters.
Closes https://github.com/infor-design/enterprise/issues/8257
- Go to http://localhost:4000/components/busyindicator/test-update
- Click `Submit (Update No Arguments)`
- Should have no errors on console.

8257 - Busy Indicator Updated Method No Arguments

---

app/views/components/datagrid/test-editable-colorpicker.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss

Fixed disabled color for colorpicker
Closes #8218 
- Go to: http://localhost:4000/components/datagrid/test-editable-colorpicker.html
- Last row should have colorpicker in disabled color

8218 - Fixed disabled color for colorpicker

---

docs/CHANGELOG.md
src/components/processindicator/_processindicator-new.scss
src/components/processindicator/_processindicator.scss

Adjusted alignment of icon in compact process indicator
Closes #8241 
- Go to: http://localhost:4000/components/processindicator/example-index.html
- X in `Process Indicator - Small Size` should be centered

8241 - Adjusted alignment of icon in compact process indicator

---

docs/CHANGELOG.md
src/components/personalize/personalize.styles.js

This pull request will fix more button not visible in alabaster.
Closes https://github.com/infor-design/enterprise/issues/8271
- Go to http://localhost:4000/components/tabs-module/example-toolbar-with-spillover.html?theme=new&mode=contrast&colors=ffffff
- Notice the '...' next to search field should be visible

8271 - Tabs Module More Button

---

docs/CHANGELOG.md
package-lock.json
src/components/locale/cultures/zh-CN.js
src/components/locale/cultures/zh-Hans.js
src/components/locale/cultures/zh-Hant.js
src/components/locale/cultures/zh-TW.js
test/components/locale/locale-func-test.js
test/components/timepicker/timepicker-puppeteer-test.js

Due to feeback from native speakers, changes the chinese time formats from AM/PM to 24hr.
NOTE: Package.json was out of sync i updated it
Fixes #8313 
- smoke test time and datepicker
- tests pass

8313 - Change chinese locale

---

app/views/components/datagrid/test-show-and-hide-pager.html
docs/CHANGELOG.md
src/components/pager/pager.js

This PR introduces the methods `showPager` and `hidePager` to respectively display and conceal the pager bar.
Close #8094
- Go to http://localhost:4000/components/datagrid/test-show-and-hide-pager
- Click `Hides the pager bar` 
- It should hide the pager
- Click `Shows the pager`
- It should show the pager

8094 - add `showPager` and `hidePager` methods

---

docs/CHANGELOG.md
src/components/personalize/_personalize.scss
src/components/searchfield/_searchfield-new.scss
src/themes/theme-classic-dark.scss

Updated hover color for header searchfield clear icon
Closes #8223 
- Go to: http://localhost:4000/components/header/example-searchfield-full
- Type in searchfield and hover over clear icon
- Check all versions and modes

8223 - Updated hover color for header searchfield clear icon

---

docs/CHANGELOG.md
src/components/dropdown/dropdown.js

This pull request will fix handling for null, undefined objects passed to updateItemIcon method.
Closes https://github.com/infor-design/enterprise/issues/8353
Relates https://github.com/infor-design/enterprise/issues/8105
- Go to http://localhost:4000/components/dropdown/test-icons-color.html
- Open the dropdown, see no errors

8353 - [Preview] Dropdown with Icon

---

app/views/components/tabs-vertical/example-index.html
docs/CHANGELOG.md
src/components/validation/validator.js

Added setting to disable error icon in validation
Closes #8254
- Go to: http://localhost:4000/components/tabs-vertical/example-index.html
- Go to `Datagrid Test`
- Select a date in date columns to get an error (do it two times)
- Error icon should not appear on tab

8254 - Added setting to disable error icon in validation

---

docs/CHANGELOG.md
src/components/checkboxes/_checkboxes.scss
src/components/radios/_radios.scss
src/core/_config.scss

Fixed focus border style
Closes #8015 
- Go to: http://localhost:4000/components/checkboxes/example-index.html
- Focus on checkboxes
- Should have similar style to: http://localhost:4000/components/radios/example-index.html

8015 - Fixed focus border style

---

app/views/components/lookup/test-custom-css.html
docs/CHANGELOG.md
src/components/lookup/lookup.js

Added css setting for lookup.
Closes #8206 
- Go to: http://localhost:4000/components/lookup/test-custom-css.html
- Open lookup
- Header should be red text

8206 - Added css setting for lookup

---

docs/CHANGELOG.md
src/components/button/_button-new.scss
src/components/cards/_cards.scss
src/components/datagrid/_datagrid-new.scss
src/components/datagrid/_datagrid.scss
src/components/dropdown/_dropdown-new.scss
src/components/tabs/_tabs-horizontal-new.scss
src/components/tabs/_tabs-new.scss
src/components/tabs/tabs.js
src/themes/theme-new-light.scss

- Fixes tab counts (badly broken)
- Fixes layouts in datagrid editor triggers
- Fixes subtle border issue
Please make new issue for any test issues and we decide if it makes the beta.
Fixes #8385 
Fixes #8380
Fixes #8379 
- in all row heights click in the dropdown and datepicker and make sure the icons dont look wierd
- go to http://localhost:4000/components/cards/example-workspace-widgets.html
- check the border is gone on the borderless wizard (was invisible so hard to see)
- test …

Misc - Add more fixes for beta

---

app/views/components/lookup/test-lookup-source-async.html
docs/CHANGELOG.md
src/components/lookup/lookup.js

This pull request will add setting `maxWidth` for tabs for long titles.
Closes https://github.com/infor-design/enterprise-ng/issues/1635
- Go to http://localhost:4000/components/lookup/test-lookup-source-async.html
- Open the lookup under the label of `Lookup with async source (Single)`
- Select and click row 3, with Product Id `2342203`
- Type in another option directly into the input field, e.g. `2142201'
- Open the lookup again
- Selection should be the row with Product Id `2142201` only.

NG1635 - Lookup Manual Input Selection

---

app/views/components/donut/example-legend-with-title.html
app/views/components/pie/example-legend-with-title.html
docs/CHANGELOG.md
src/components/charts/_charts-new.scss
src/components/charts/_charts.scss
src/components/charts/charts.js
src/components/donut/readme.md
src/core/_config.scss
src/themes/theme-classic-dark.scss
src/themes/theme-new-dark.scss

This PR introduces a feature legend title in donut and pie charts. This will only support the `right` legend position.
Closes #7933
- Go to 
- http://localhost:4000/components/donut/example-legend-with-title (Donut)
- http://localhost:4000/components/pie/example-legend-with-title (Pie)
- Both examples should have a legend title
~~- [] An e2e or functional test for the bug or feature.~~

7933 - Add legend title in donut and pie charts

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/personalize/readme.md
test/components/datagrid/datagrid-puppeteer-test.js

Fixed cell value replacing special characters on cell change
Closes #8285 
- Enter `c:\windows\temp` in a cell
- Value should stay the same

8285 - Fixed cell value replacing special characters on cell change

---

app/views/components/tabs-header/test-max-width.html
docs/CHANGELOG.md
src/components/tabs-header/_tabs-header-new.scss
src/components/tabs/tabs.js

This pull request will add setting `maxWidth` for header tabs for long titles.
Closes https://github.com/infor-design/enterprise/issues/8434
- Go to http://localhost:4000/components/tabs-header/test-max-width.html
- See the long titles on ellipsis

8434 - Header Tabs Max Width

---

app/views/components/datagrid/example-editable-with-row-status.html
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-puppeteer-test.js

Adds a new fix by reverting some previous changes and using innerText instead of html()
Closes https://github.com/infor-design/enterprise/issues/8444
Closes https://github.com/infor-design/enterprise/issues/8285
- in both the hyperlink and text cell enter special chars like `&<>`
- hit enter to commit
- go back and forth a page
- try to paste `<script>alert("Hello World!")</script>` in a cell and it should not alert
- try to paste `related:[BALMAS1("TX60:\{IndexList_Items.TX60}")]` in a cell and it should stay in tact …

Misc - Added an alternative fix for XSS vulnerability

---

docs/CHANGELOG.md
src/components/checkboxes/_checkboxes.scss

This pull request will fix RTL alignment for dirty tracker and required label.
Closes https://github.com/infor-design/enterprise/issues/8308
- Go to http://localhost:4000/components/checkboxes/example-index.html?locale=ar-SA
- Scroll down to Checkboxes
- Tick the `Dirty Tracking` checkbox
- Notice the `Required` checkbox

8308 - RTL Checkbox Dirty

---

docs/templates/documentationjs/theme-ids-website/section._
docs/templates/hbs/page.hbs
scripts/deploy-documentation.js

This PR modifies the docjs template to remove redundant h2s
n/a
n/a

Update docjs template

---

docs/CHANGELOG.md

This pull request will fix changelog inconsistencies
None

Chore - Fix Changelog Inconsistencies

---

app/views/components/datagrid/test-date-parsing.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixes an issue with date editors, where some date formats are incorrectly parsed thus the value is not saved.
Fixes #8479
- go to http://localhost:4000/components/datagrid/test-date-parsing.html
- In the second column try to edit and pick a value with the day over 12 and make sure it works again
- try picking and editing various dates

8479 - Fix date parsing issue

---

docs/CHANGELOG.md
src/components/personalize/_personalize.scss
src/components/personalize/personalize.js
src/components/personalize/personalize.styles.js
src/components/tabs-header/_tabs-header-new.scss
src/components/tabs-module/_tabs-module-new.scss
src/components/tabs-module/_tabs-module.scss
src/components/tabs/_tabs.scss
src/core/_config.scss
src/themes/theme-new-contrast.scss
src/themes/theme-new-dark.scss
src/themes/theme-new-light.scss

This pull request will fix alabaster in tabs module.
Closes https://github.com/infor-design/enterprise/issues/8404
Closes https://github.com/infor-design/enterprise/issues/8298
- Go to http://localhost:4000/components/tabs-module/example-toolbar-with-spillover
- Check the UI

8404 - Tabs Module Spillover Alabaster

---

docs/CHANGELOG.md
src/components/tabs/_tabs-horizontal-new.scss
src/components/tabs/_tabs-horizontal.scss
src/components/tabs/_tabs-new.scss
src/components/tabs/_tabs.scss
src/components/tabs/tabs.js

This pull request will fix add tab button focus.
Closes https://github.com/infor-design/enterprise/issues/8294
- Go to http://localhost:4000/components/tabs/example-add-tab-button.html
- Click on `+` icon
- See the focus

8294 - Tabs Add Tab Button Focus

---

app/views/components/contextualactionpanel/test-back-button.html
docs/CHANGELOG.md
src/components/cards/cards.js
src/components/contextualactionpanel/_contextualactionpanel-new.scss
src/components/contextualactionpanel/_contextualactionpanel.scss
src/components/contextualactionpanel/contextualactionpanel.js
src/components/toolbar/_toolbar.scss

This pull request will add content details and back button arrow.
Closes https://github.com/infor-design/enterprise/issues/8112
- Go to http://localhost:4000/components/contextualactionpanel/test-back-button.html
- Press the button `Additional Information`
- See the next set of fields
- Press the back button on the header to go back to the main fieldsets.

8112 - CAP Back Arrow

---

app/views/components/pie/test-many-records.html
docs/CHANGELOG.md
src/components/charts/charts.js
src/components/pie/pie.js

This pull request will fix an error encountered when having many records inside the graph.
Closes https://github.com/infor-design/enterprise/issues/8367
- Go to http://localhost:4000/components/pie/test-many-records.html
- See no errors

8367 - Graph Many Records

---

app/views/components/datagrid/test-filter-date-hide-days.html
docs/CHANGELOG.md
src/components/datepicker/datepicker.js

Increment/decrement and today keys should not be used when datepicker is in range mode
Closes #8363 
- Go to: http://localhost:4000/components/datagrid/test-filter-date-hide-days.html
- Switch to range in date filter and type a date range
- When typing "-", "+', or "t" the date shouldn't change

8363 - Fixed increment/decrement and today key being activated in range mode

---

app/views/components/tree/test-escape-node.html
docs/CHANGELOG.md
src/components/tree/tree.js

Added escape HTML in updateNode
Closes #8427 
- Go to: http://localhost:4000/components/tree/test-escape-node.html
- Check all three nodes in the tree

8427 - Added escape HTML in updateNode

---

app/views/components/datagrid/example-editable.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid-new.scss
src/components/datagrid/_datagrid.scss

This pull request will fix RTL alignment for color picker.
Closes https://github.com/infor-design/enterprise/issues/8293
- Go to http://localhost:4000/components/datagrid/example-editable.html?theme=new&mode=light&colors=default&locale=ar-SA
- Change the row height to Extra Small
- Check alignments of the required icons on the activity column
- For extra steps visit the ticket issue

8293 - RTL Datagrid Small Row Height

---

app/views/components/calendar/test-all-colors.html
docs/CHANGELOG.md
src/components/calendar/calendar-shared.js

This pull request will fix incosistencies in border colors of events in calendar.
Closes https://github.com/infor-design/enterprise/issues/8452
- Go to http://localhost:4000/components/calendar/test-all-colors.html
- See all the colors and border colors

8452 - Calendar Turqoise

---

docs/CHANGELOG.md
src/components/radios/_radios.scss

Fixed alignment in short form of radio button
Closes #8193 
- Go to: http://localhost:4000/components/radios/example-short.html
- Check that buttons are aligned

8193 - Fixed alignment in short form of radio button

---

docs/CHANGELOG.md
src/components/button/_button-new.scss
src/components/button/_button.scss
src/components/searchfield/_searchfield-new.scss
src/components/searchfield/_searchfield.scss

Adjusted clear icon
Closes #8399
- Go to: http://localhost:4000/components/searchfield/example-index
- Type a text
- Press tab to focus in x icon

8399 - Fixed alignment issues in clear button

---

app/views/components/homepage/example-height.html
docs/CHANGELOG.md
src/components/homepage/_homepage.scss
src/components/homepage/homepage.js

Added row height style classes for widgets
Closes #8211 
- Go to: http://localhost:4000/components/homepage/example-height.html
- Check the heights of the widgets

8211 - Added row height style classes for widgets

---

app/views/components/datagrid/test-resize-handle-singleline.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This pull request will fix datagrid unable to have resize handle when using different column structure such as single lines.
Closes https://github.com/infor-design/enterprise/issues/8417
- Go to http://localhost:4000/components/datagrid/test-resize-handle-singleline.html
- Try to use the handle bars

8417 - Datagrid Singleline Resize Handle

---

docs/CHANGELOG.md
src/components/locale/cultures/en-US.js
src/components/textarea/textarea.js
test/components/textarea/textarea-settings-func-test.js

This PR fixes the character count message in textarea.
Closes #8449 
- Go to http://localhost:4000/components/textarea/example-index.html
- In the first textarea, populate it so it will show the character count message
- The message should be: `Character count of 90 exceeded.`

8449 - Fix character count message

---

app/views/components/datagrid/test-icon-always-on.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid-new.scss
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js
src/components/place/place.js
src/core/_config.scss
src/themes/theme-new-light.scss
test/components/datagrid/datagrid-settings-func-test.js

This pull request will add setting `showEditorIcons` to always display icon without hover.
Closes https://github.com/infor-design/enterprise/issues/8439
- Go to http://localhost:4000/components/datagrid/test-icon-always-on.html
- Icon should always display

8439 - Datagrid Always on Icons

---

app/views/components/lookup/example-filter-lookup.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
src/components/searchfield/searchfield.js
src/components/toolbar/toolbar.js

Added placeholder setting in toolbar
Closes #8416 
- Go to: http://localhost:4000/components/lookup/example-filter-lookup.html
- Open first lookup
- Placeholder text should be `Type keywords here!`

8416 - Added placeholder setting in toolbar

---

app/views/components/datagrid/test-frozen-only.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js

Colgroups weren't inserted when the datagrid is only frozen columns (which resulted in the headers not being inserted because colgroup didn't exist). Added colgroups in rendering
Closes https://github.com/infor-design/enterprise-ng/issues/1590
- Go to: http://localhost:4000/components/datagrid/test-frozen-only.html
- Headers should exist

NG1590 - Fixed missing headers in frozen columns

---

docs/CHANGELOG.md
src/components/cards/_cards-new.scss
src/components/cards/_cards.scss
src/components/cards/cards.js

Fixed misalignment in card header icon
Closes #8448 
- Go to: http://localhost:4000/components/counts/example-widget-count.html
- Check icons

8448 - Fixed misalignment in card header icon

---

app/views/components/button/example-index.html
app/views/components/button/test-generative-start-stop.html
docs/CHANGELOG.md
src/components/button/button.js

This pull request will add start and stop methods for generative timeout.
Closes https://github.com/infor-design/enterprise/issues/8541
- Go to http://localhost:4000/components/button/test-generative-start-stop.html
- Click `Start`
- Click `Stop`

8541 - GenAiButton Start Stop

---

app/views/components/toolbar-flex/example-searchfield-collapsible.html
docs/CHANGELOG.md
src/components/toolbar-flex/_toolbar-flex-searchfield-new.scss

Fixed clear button misalignment in RTL
Closes #8342 
- Go to: http://localhost:4000/components/toolbar-flex/example-searchfield-collapsible.html?locale=ar-SA
- Type in searchfield
- Clear button should be aligned

8342 - Fixed clear button misalignment in RTL

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Added checks. Don't focus/select the cell when hyperlink is clicked
Closes #8498
- Go to: http://localhost:4000/components/datagrid/example-key-row-select.html
- Click on hyperlink
- Row should not be selected

8498 - Select event is not triggered when clicking a hyperlink

---

docs/CHANGELOG.md
src/components/hierarchy/_hierarchy-base.scss

Fixes the broken avatar shape introduced to the hierarchy component.
Fixes #8584
- go to http://localhost:4000/components/hierarchy/example-stacked.html
- note that the avatars (green ones) are round again and centered

8584 - Fix avatar shape on hierarchy

---

src/components/arrange/arrange.js
src/components/drag/_drag.scss

Fix on error popping up on dragging
Closes #8462 
- In mobile, go to: http://localhost:4000/components/arrange/example-index.html
- Drag item
- In console, error should not pop up

8462 - Fix on error popping up on dragging

---

docs/CHANGELOG.md
src/components/cards/_cards-new.scss
src/components/cards/_cards.scss

Fixes #8602 
- check title and buttons on http://localhost:4000/components/listview/example-index.html
- also check http://localhost:4000/components/cards/example-index.html
- and a few card examples http://localhost:4000/components/cards

8602 - Fix button layout regression

---

.github/workflows/ci.yml
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js

Fixed an error commiting dates in certain formats (day value greater than 12 in german as an example)
Fixes #8627 
- go to http://localhost:4000/components/datagrid/example-editable.html and try to edit all columns and make sure they save
- go to http://localhost:4000/components/datagrid/example-editable.html?locale=de-DE and try
- in particular in the order date column try and select a day of the week before and after 15 
- try other examples in the list that say "editor" in the name http://localhost:4000/components/datagrid

8627 - Fixed error parsing some dates

---

app/views/components/field-filter/example-default-filter-type.html
docs/CHANGELOG.md

This pull request will add Default Field Filter Reset example page.
Closes https://github.com/infor-design/enterprise-ng/issues/1641
- Go to http://localhost:4000/components/field-filter/example-default-filter-type.html
- Change the filter type of `Filterable` to `>`
- Click the `Reset Default`
- It should go back to `=`

NG1641 - Field Filter Reset Field

---

docs/CHANGELOG.md
src/components/tabs/tabs.js

This pull request will fix change hash not working in more button.
Closes https://github.com/infor-design/enterprise/issues/8536
- Go to http://localhost:4000/components/tabs/test-forward-slashes.html#/home/contracts
- Go to `Responsive View` until more button appears
- Try to click more button
- Check the URL if it changes

8536 - Tabs Change Hash More Button

---

docs/CHANGELOG.md
src/themes/theme-new-dark.scss

This PR fixes selected row color in dark theme.
Closes #8467
- Go to http://localhost:4000/components/datagrid/example-multiselect.html?theme=new&mode=dark&colors=default
- Select any row in the grid
- Selected row should be on Slate color

8467 - Fix selected row color in dark theme

---

docs/CHANGELOG.md
src/components/tabs/tabs.js

This pull request will fix error of undefined handling in tabs activate.
Closes https://github.com/infor-design/enterprise-ng/issues/1615
- No test for this build

NG1615 - First Tabs Highlight

---

docs/CHANGELOG.md
src/components/applicationmenu/_applicationmenu.scss

Addition button fix for the app menu. The menu button is off
Fixes https://github.com/infor-design/enterprise/issues/8723
- go to http://localhost:4000/components/applicationmenu/example-menubutton.html
- hover the menu button, this should look ok
- try themes

8723 - Added fix for menu button

---

app/views/components/datagrid/test-cell-changed.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This pull request will fix cell changed trigger event on number and string comparison.
Closes https://github.com/infor-design/enterprise/issues/8719
- Go to http://localhost:4000/components/datagrid/test-cell-changed.html
- Click on Product Id cell to enter edit mode
- Tab out of the cell without changing the value

8719 - Datagrid Cell Changed Trigger

---

app/views/components/datagrid/test-format-number.html
docs/CHANGELOG.md
src/components/locale/locale.js

Fixes conversion to work better on big numbers.
Fixes #8737 
- go to http://localhost:4000/components/datagrid/test-format-number.html
- compare the numbers in the first cell and they should match:
```
Row 1: 2345678901234567
Row 2: 19030114370254879
Row 5: 190301143702548792
```

8737 - Add fixes for big ints

---

.github/workflows/ci.yml
test/components/locale/locale-func-test.js

GitRunner was running `macos` this was just a test but got left in. Need to run linux to aid gitlab migration.
- if it all passes will merge

Chore - Switch to ubuntu

---

app/views/components/spinbox/example-range-limits.html
docs/CHANGELOG.md
src/components/spinbox/spinbox.js

updateVal has min/max check and changes new value accordingly
Closes https://github.com/infor-design/enterprise-ng/issues/1681
- Go to: http://localhost:4000/components/spinbox/example-range-limits.html
- Click on buttons
- Should not go above/below max/min

NG1681 - Fix on updateVal

---

app/data/custom-events.json
app/data/events.json
app/views/components/calendar/test-event-tooltips.html
docs/CHANGELOG.md
src/components/calendar/calendar.js
src/components/tooltip/tooltip.js
src/components/week-view/week-view.js
test/components/button/button-puppeteer-test.js

This pull request will add new setting `showTooltip` and `tooltipSettings` to display event information on event hover.
Closes https://github.com/infor-design/enterprise/issues/8453
- Go to http://localhost:4000/components/calendar/test-event-tooltips.html
- Hover one of the events

8453 - Calendar Event Tooltips

---

app/views/components/datagrid/test-cell-click-args.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This pull request will fix cell value from argument passed on hyperlink click.
Closes https://github.com/infor-design/enterprise/issues/8762
- Go to http://localhost:4000/components/datagrid/test-cell-click-args.html
- Click hyperlink, check the cell value from object in the console (should be 2)
- Click approval button, check the cell from the object in console (should be 12)

8762 - Cell Value Hyperlink Click

---

docs/CHANGELOG.md
src/components/dropdown/dropdown.js

This pull request will fix  no results text still displaying after removing filter text.
Closes https://github.com/infor-design/enterprise/issues/8768
- Go to http://localhost:4000/components/datagrid/example-editable.html
- Open dropdown action
- Type something to see the no results text
- Clear it all

8768 - Dropdown No Results

---

docs/CHANGELOG.md
src/components/datepicker/_datepicker.scss
src/components/monthview/_monthview.scss

This pull request will fix buttons truncated when using other languages.
Closes https://github.com/infor-design/enterprise/issues/8787
- Go to http://localhost:4000/components/datepicker/example-month-year-format.html?locale=de-DE
- Open `Datepicker`
- See the Apply Button translated to other languages

8787 - Truncated Apply Buttons

---

app/views/components/datagrid/example-expandable-row-no-layout.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js
test/components/datagrid/datagrid-settings-func-test.js

This pull request will fix bug with week numbers not aligned properly with first day of week.
Closes https://github.com/infor-design/enterprise-ng/issues/1524
- Go to http://localhost:4000/components/datagrid/example-expandable-row-no-layout.html
- Open an expandable row
- Inspect the elements inside it, the outer parent shouldn't have `datagrid-cell-layout`

NG1524 - Expandable Rows Remove Custom Width

---

docs/CHANGELOG.md
src/components/autocomplete/autocomplete.js
src/components/popupmenu/popupmenu.js

This pull request will fix autocomplete losing focus on keydown.
Closes https://github.com/infor-design/enterprise/issues/8618
- Go to http://localhost:4000/components/autocomplete/example-index.html
- In the input field, type "ne" and wait for the results to appear.
- Hit the down arrow to nav down the list
- The focus should still be on the input box

8618 - Autocomplete Keydown

---

app/views/components/datagrid/test-mask-options-with-text-overflow.html
src/components/datagrid/_datagrid.scss
src/components/datagrid/datagrid.js

An additional fix for 4.95.x for the text-ellipsis feature. @claudenbach 
Its a tough one with that custom formatter. 
I had to rename the formatter from customFormatter to tag because it adds a class to the parent to get rid of the dot. I dont want to risk turning off textEllipsis for all formatters. (May also be solvable by some custom css)
Fixes #8824
- go to http://localhost:4000/components/datagrid/test-mask-options-with-text-overflow.html
- go to http://localhost:4000/components/datagrid/test-alerts
- check the tag and it should not show a visual artifact
- click into the quantity …

8824 - Added more fixes to the ellipsis extra .

---

docs/CHANGELOG.md
src/components/popupmenu/popupmenu.js
src/components/toolbar-flex/toolbar-flex.item.js

Additional checks to avoid null/undefined exceptions
Closes https://github.com/infor-design/enterprise-ng/issues/1700
Follow instructions here: https://github.com/infor-design/enterprise-ng/pull/1725

NG1700 - Fixed bug in popupmenu when heading element is added in NG

---

app/views/components/monthview/test-add-day.html
src/components/monthview/monthview.js

This pull request will fix bug triggers being not called after calling the update method().
Closes https://github.com/infor-design/enterprise-ng/issues/1660
- Go to http://localhost:4000/components/monthview/test-add-day.html
- Click a day in calendar, `Selected event` should show in the log
- Click `Add Day`
- Click again a day in calendar, `Selected event` should show in the log

NG1660 - Trigger Events

---

app/views/components/datagrid/example-custom-toolbar-flex.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Added searched event. Will add in NG once this is approved to be sure.
Closes #8814 
- Go to: http://localhost:4000/components/datagrid/example-custom-toolbar-flex.html
- Inspect console
- Type on toolbar search
- Console should print searched and the filtered rows

8814 - Added searched event

---

app/views/components/tabs-module/example-sortable.html
docs/CHANGELOG.md
src/components/tabs-header/_tabs-header-new.scss
src/components/tabs-module/_tabs-module.scss
src/components/tabs/_tabs.scss
src/components/tabs/tabs.js
src/core/_config.scss

Enhancement and bugfix in reordering tags
Close #8016 
- Pull this branch, build and run the branch
- Go to: http://localhost:4000/components/tabs-module/example-sortable.html
- Add tabs until overflow happens
- Select a tab from more menu
- Tab should appear in the next visible space

8016 - Reorder tags

---

docs/CHANGELOG.md
src/components/pager/_pager.scss

Fixes #8880 
- go to http://localhost:4000/components/datagrid/example-paging-client-side.html
- note color of disabled pager buttons
- test all themes

8880 - Fix pager disabled color

---

app/views/components/modal/test-accordion.html
docs/CHANGELOG.md
src/components/modal/_modal.scss

This pull request will remove accordion fixed width when used in modal.
Closes https://github.com/infor-design/enterprise-ng/issues/1719
- Go to http://localhost:4000/components/modal/test-accordion.html
- Click `Show Modal`
- Check if the accordion don't have a fixed width

1719 - Accordion Fixed Width in Modal

---

app/views/components/busyindicator/test-circular.html
docs/CHANGELOG.md
src/components/busyindicator/_busyindicator.scss
src/components/busyindicator/busyindicator.js

Added circular loading type
Closes #8662 
- Go to: http://localhost:4000/components/busyindicator/test-circular
- Click Submit
- Busy indicator should be circular

8662 - Added circular loading type

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Fixes a regression from https://github.com/infor-design/enterprise/issues/8832
Fixes #8889 
- go to http://localhost:4000/components/datagrid/test-expandable-row-frozen-columns.html
- expand rows
- check the console, should be no errors. also the expandable row should resize

8889 - Fix error on datagrid eror expanding rows

---

app/views/components/cards/example-multi-select.html
app/views/components/cards/example-single-select.html
docs/CHANGELOG.md
src/components/cards/cards.js

This pull request will fix a bug selected and deselected event are not triggered on action.
Closes https://github.com/infor-design/enterprise-ng/issues/1731
- Go to http://localhost:4000/components/cards/example-multi-select.html
- Try to select, unselect a card
- See the logs

1731 - Cards Selected and Deselected Event

---

app/views/components/datagrid/test-pager-addrow.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Refresh pager when applyFilter is called and if pager API exists
Closes #8744 
- Go to: http://localhost:4000/components/datagrid/test-pager-addrow.html
- Click Add Row
- Pager should update

8744 - Refresh pager when applyFilter is called

---

docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This pull request will fix a bug in search keyword not functioning properly when using special characters.
Closes https://github.com/infor-design/enterprise/issues/8864
- Go to http://localhost:4000/components/datagrid/example-keyword-search.html
- Click on the `Magnifying Glass`
- Type `&`
- Should display `Mac & Cheese` data row

8864 - Datagrid Search

---

docs/CHANGELOG.md
src/components/pie/_pie.scss

Updated RTL style to fix chart being cut off
Closes https://github.com/infor-design/enterprise-ng/issues/1736
- Go to: http://localhost:4000/components/donut/example-legend.html?locale=ar-SA
- Chart should not be cut off

NG1736 - Fixed alignment bug in chart on RTL

---

app/views/components/button/example-menubutton-replace-text.html
app/views/components/button/example-menubutton.html
app/views/components/datagrid/example-index.html
app/views/components/line/test-axis-y-format-hours.html
docs/CHANGELOG.md
src/components/button/_button.scss
src/components/datepicker/_datepicker-new.scss
src/components/datepicker/_datepicker.scss
src/components/header/_header.scss
src/components/input/_input.scss
src/components/switch/_switch.scss
src/core/_config.scss
src/themes/theme-new-dark.scss

Fixes a few bugs noted by QA during QA period. NOTE: If this is merged just QA on main and note any issues here.
Fixes https://github.com/infor-design/enterprise/issues/8926
Fixes https://github.com/infor-design/enterprise/issues/8924
Fixes https://github.com/infor-design/enterprise/issues/8923
- go to http://localhost:4000/components/datepicker/example-index.html -> should not be able to hover the button on the readonly field
- go to http://localhost:4000/components/input/example-index.html and switch to dark mode (try all modes actually). Try to select some text on the header, in the …

Misc - Fix for 3 Release bugs

---

docs/CHANGELOG.md
src/utils/string.js

refactor the stringUtil method to validate a url
use a regexp literal instead of instantiating a new RegExp object and concatenating strings
Fixes https://github.com/infor-design/enterprise/issues/8935
Render a lot of datagrids (more than 50) with a filter on the header
Please change the target branch if needed.

optimize-regexp-for-url

---

app/views/components/cards/test-paging-datagrid.html
docs/CHANGELOG.md
src/components/datagrid/_datagrid.scss

Changed style in test page, 38px is the height of pager so made the datagrid height to be calc(100% - 38px) instead. Moved one of the height lines in _datagrid.css to avoid using !important.
Closes https://github.com/infor-design/enterprise-ng/issues/1756
- Go to: http://localhost:4000/components/cards/test-paging-datagrid.html
- Scroll up and down, pager should stay in place

NG1756 - Updated styles for pagination in test page

---

app/views/components/tabs/test-breadcrumb.html
docs/CHANGELOG.md
src/components/tabs-vertical/_tabs-vertical.scss
src/components/tabs/tabs.js

This pull request will fix a bug where focus state is undefined when using breadcrumbs startup.
Closes https://github.com/infor-design/enterprise/issues/8910
- Go to http://localhost:4000/components/tabs/test-breadcrumb.html
- Click on `Application1`
- See no errors

8910 - Tabs Breadcrumb Start

---

app/views/components/datagrid/test-addrow.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

This pull request will fix data return by select event on datagrid when having filter on.
Closes https://github.com/infor-design/enterprise/issues/8905
- Go to http://localhost:4000/components/datagrid/test-addrow.html
- Filter out name with `o`
- Click `Add Row`
- Click the last data in the datagrid
- See the object returned in the console

8905 - Datagrid Filter Add Row

---

app/data/tree-tasks.js
app/views/components/datagrid/test-treegrid-colwidth.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Included calculating width for children in tree grid
Closes #8646 
- Go to: http://localhost:4000/components/datagrid/test-treegrid-colwidth.html
- Content shouldn't be cut off in first column of first datagrid
- Width shouldn't be very long in the first column of second datagrid

8646 - Fixed auto sizing in tree grid

---

docs/CHANGELOG.md
src/components/dropdown/_dropdown.scss

Fixed  misaligned  text in action dropdown
Fixes #8957 
- [✔️ ] A note to the change log.

Fixed misaligned text in action dropdown

---

app/views/components/form/example-compact-mode.html
app/views/components/listview/example-form-compact.html
docs/CHANGELOG.md
src/components/listview/_listview.scss
src/components/listview/readme.md
src/components/swaplist/readme.md
tests/listview/listview.spec.js

This PR adds compact layout form for listview component.
Adjusted styles:
paddings = to 8px 8px 7px
font sizes = 16 px/rem, 14 px/rem, 12 px/rem
Closes #8959 
- Go to http://localhost:4000/components/listview/example-form-compact
- `p`, `heading`, `subheading` should be 14px/rem
- padding sizes of the list item should be `8px 8px 7px`
- listview with checkbox should have `37px` padding left

8959 - Add compact layout form for listview

---

app/package-lock.json
app/package.json
app/src/js/.babelrc
docs/CHANGELOG.md
package-lock.json
package.json
src/.babelrc
src/components/validation/validator.js

Adds fixes so that if the settings are undefined in some angular lifecycle situations the forms will not error out. Once checked will patch this to 4.98.1
Not sure why tests are failing will check again tomorrow. Seems odd
Fixes #8981 
- retest https://github.com/infor-design/enterprise/pull/8754

8981 - Add guards to prevent exceptions

---

app/views/components/datagrid/example-fixed-header.html
docs/CHANGELOG.md
src/components/datagrid/datagrid.js

Added scrollRowIntoView method. Will add it to NG once this is merged.
Addresses https://github.com/infor-design/enterprise-ng/pull/1773#issuecomment-2304811931
- Go to: http://localhost:4000/components/datagrid/example-fixed-header.html
- Click "Scroll Down"
- Should scroll at bottom

NG1761 - Added scrollRowIntoView

---

app/views/components/calendar/test-sort-events.html
docs/CHANGELOG.md
src/components/calendar/calendar.js
src/components/calendar/readme.md

Added customSort function
Closes #8836 
- Go to: http://localhost:4000/components/calendar/test-sort-events
- Clicking on "Sort": should sort the events by date in earliest to latest
- Clicking on "Reverse Sort": should sort the events from latest to earliest

8836 - Added customSort function

---

app/views/components/modal/test-async.html
docs/CHANGELOG.md
src/components/modal/modal.js

Added promise option for beforeclose event
Will add to NG on beforeClose once this is approved
Closes #8779 
- Go to: http://localhost:4000/components/modal/test-async.html
- Open modal
- Close modal 
- Should close after 1 second

8779 - Added promise option for beforeclose event
